### ISSUE TITLE
Plugin scaffolding tool

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10000]
Are we interested in a core scaffolding tool?
I have build my first Yeoman generator today, and it's pretty handy. I have defaulted it to my setup, but can be updated to if the core.

https://github.com/hypeJunction/generator-hypeplugin

**Comment by mrclay** [comment]
I'd definitely be into pulling something like this into core, including various common tasks related to plugins. It's probably worth thinking about how to structure plugins to make this easier. E.g. having comments to mark off various places in a plugin, like the init handler.

**Comment by hypeJunction** [comment]
Symfony Console might be an interesting option for core.

**Comment by jdalsem** [comment]
Not going to put any effort in this at this moment
