### ISSUE TITLE
Likes count in entity menu count is repeated after first appearance

### ISSUE THREAD

**Issue by Facyla** [Elgg/Elgg#10004]
In activity feed or river views, the entity menu likes count appears even for non-liked entities, if an entity has been liked before.
I'm not sure yet about the reason that produces this behaviour, but it seems that the latest view return value (called in in start.php function likes_entity_menu_setup($hook, $type, $return, $params)) is used if no new, non-empty value is returned.
I'm not sure if i should submit a PR for this : my current patch is a bit hacky, and should be better used in a plugin (override likes/count to return a string with a single space instead of nothing).

**Comment by mrclay** [comment]
Are there steps we can take to reproduce this?

**Comment by Facyla** [comment]
It happens in main activity feed, on latest Elgg 1.12 version :
- go to SITE_URL/activity : 
- like 1 entry
- refresh page so the likes numbers displays
=> all following entries have the "1 like" link (popup has the same content for each)

Notes : 
- i haven't disabled all plugins to test, but i don't know any plugin which could interfere with the "likes" plugin
- tested both on a site running on nginx, and also on another one running on Apache (i supected opcache could have an effect but that's not related afaik)

**Comment by mrclay** [comment]
> i don't know any plugin which could interfere with the "likes" plugin

I'm pretty sure this is it. Cannot duplicate. Can you attach before/after screenshots?

**Comment by hypeJunction** [comment]
Check that .hidden class is correctly applied to mwnu items. It's possible your theme uses a more detailed selector to set  them to inline display

**Comment by Facyla** [comment]
Thanks for your help !
I have tested again on a clean install, with only core plugins enabled, and cannot reproduce it either. I'm currently investigating where this comes from, but at least it looks like this issue is not a core issue.

I'll keep you informed in case i find some clear explanation on what happened :)

**Comment by Facyla** [comment]
Here's how it looks like 
![capture du 2016-07-19 11 07 02](https://cloud.githubusercontent.com/assets/286492/16944466/0f5a2c70-4da1-11e6-9f4c-25ab6a88abad.png)

**Comment by Facyla** [comment]
Ok, it was caused by a plugin which dynamically modifies menus : a missing check lead to a default behaviour which would add unwanted items to the menu.
