### ISSUE TITLE
A bug in elgg_delete_river function

### ISSUE THREAD

**Issue by tom-cat** [Elgg/Elgg#10015]
I found a serious bug in elgg function elgg_delete_river() , when we delete a river item, it only removes the contents from river table only, other data related to this river item are still exists in tables ANNOTATIONS, ENTITIES, METADATA, METASTRINGS,

RETAINING THIS VALUES IN THESE TABLES AFTER DELETING THE RIVER CONTENT WILL STRICTLY CAUSE PAGING ERROR AS SOME TIMES GET EMPTY PAGE RESULTS

can anybody have a solution on this, as deleting a river content should remove all these related values from  the stated rules maintain the integrity ?

Is this resolved in latest version of elgg ?

**Comment by hypeJunction** [comment]
River items are merely a representation of a system event: User X created Object B. Deleting a river does not delete entities, annotations, etc. Delete the object of the river item to get the behavior you are looking for.

**Comment by tom-cat** [comment]
Thanx for the info,
>>Delete the object of the river item to get the behavior you are looking for.
How can be do that ? after deleted a river item , why it retain comments and likes of that river item in other tables, which all are created as a part of same river content ? I am getting pagination issues also, which all started after deleted the river content, getting empty page results.

**Comment by hypeJunction** [comment]
River comments are in fact object comments, same for likes.
I am not sure what "pagination issues" are, elaborate.
