### ISSUE TITLE
API to notify admin(s)

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10026]
Emails, say, 2 random admins by default, filtered by hook so plugins can add/remove people.

Immediate use cases: #10147, reportedcontent, Elgg showcase submission. Anything where an admin needs to get involved, but not anyone in particular.

**Comment by hypeJunction** [comment]
IMO, you can do that by registering a notification event and hooking into get subscribers

**Comment by iionly** [comment]
Email notifications to admins for example on reported content is surely needed. Maybe it should be possible to configure the admins who should get notified specifically though. Some sites might have some "head" admin, some other admins might not available at times. If it's just randomly determined who gets notified it might get just to the "wrong" admins sometimes.

**Comment by hypeJunction** [comment]
Subscirptions hook + notification setting preference for admins. One think I will add after notifications refactor is merged is an ability to register notification events/contexts so that they automatically appear in notification settings

**Comment by jdalsem** [comment]
I do not think we need a specific api to notify a (random) group of admins. We can register subscribers in a hook or use `elgg_get_admins` and loop to notify them directly.
