### ISSUE TITLE
elgg_group_gatekeeper should do nothing (or return true) if group guid not is a group

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10029]
Currently you can not do `elgg_group_gatekeeper();` because the function assumes the pageowner is a group. Therefore, if you want to protect a page, you need to do:
```
if (elgg_get_pageowner_entity() instanceof ElggGroup) {
    elgg_group_gatekeeper();
}
```
Why not move that check to the gatekeeper function itself? Return void or (true) if not checking a group...

**Comment by mrclay** [comment]
> the function assumes the pageowner is a group

It doesn't, it checks for this in `Elgg\GroupItemVisibility::factory`, but your suggestion would make sense as an optimization.

**Comment by mrclay** [comment]
Have you observed it misbehaving? If not we can close.

**Comment by jdalsem** [comment]
> Have you observed it misbehaving? 

Nope, it seems my check is obsolete.
