### ISSUE TITLE
CLI tools

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10027]
I have started working on some CLI tools to make my life easier. In case anyone wants to contribute:
https://github.com/hypeJunction/elgg-cli

**Comment by hypeJunction** [comment]
You can now use the tool as a global composer dependency. 
I am soliciting ideas for tools that would be helpful. I would like to add cron and some basic DB manipulations. 
@Srokap I remember you were working on some CLI stuff. Any input?

**Comment by jdalsem** [comment]
- enable/disable plugins
- flush cache

**Comment by Srokap** [comment]
I don't remember the details, I just might have some branch laying around, but it probably is not much use today. Never finished that one.

My general idea was to have way to automate work with admin panel, so ie. check enabled plugins list and enable missing ones or disable unwanted ones via cron script that would call cli tools.

**Comment by hypeJunction** [comment]
You can now:
- install Elgg using CLI
- activate/deactivate plugins in bulk and one by one
- flush site caches
- run upgrade

**Comment by hypeJunction** [comment]
Also active plugins can now define their own CLI commands using `'commands', 'cli'` hook.

**Comment by hypeJunction** [comment]
You can now:

* route requests to specific pages (paths), e.g. `elgg-cli route cron/run`
* execute actions, e.g. `elgg-cli action entity/delete --query guid=25`
* search for entities `elgg-cli entities:get --type user --keyword Ismayil`
* list entities `elgg-cli entities:get --type group --guid 25,35,34`

On all of these, you can add `--as username` option that will perform the operation on behalf of that user (login/logout).

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/issues/10176 about messages/errors during CLI

**Comment by jdalsem** [comment]
This is now possible using https://github.com/Elgg/Elgg/pull/11158

**Comment by hypeJunction** [comment]
Yes, feel free to add new commands as they become needed.
