### ISSUE TITLE
Is there a need for a helper function to draw links? elgg_view_link

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10035]
currently
```php
echo elgg_view('output/url', [
    'text' => $user->name,
    'href' => $user->getURL(),
]);
```

could be replaced by 
```php
echo elgg_view_link($user->name, $user->getURL());
```

an optional extra 3rd param could be the rest of the $vars passed to output/url

```php
echo elgg_view_link($user->name, $user->getURL(), ['rel' => 'user']);
```

**Comment by beck24** [comment]
That doesn't seem like it's really improving anything other than creating a new aptly named function.  It's basically the same effort to use.

**Comment by mrclay** [comment]
I'd rather devs type a little and keep plugins compatible with previous Elgg versions.

**Comment by jdalsem** [comment]
> I'd rather devs type a little and keep plugins compatible with previous Elgg versions.

we could add it in 3.0

**Comment by jdalsem** [comment]
to make it more intelligent
```php
echo elgg_view_entity_link($entity);
```

```php
function elgg_view_entity_link($entity) {
     return elgg_view('output/url', [
         'text' => $entity->getTitle(),
         'href' => $entity->getURL(),
     ]);
}
```

**Comment by hypeJunction** [comment]
I don't see any added benefits.
