### ISSUE TITLE
elgg_view_input('checkbox') breaks 'label' var in input/checkbox view

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10031]
unfortunately i cannot use the checkbox view to display `[ ] label` with elgg_view_input('checkbox'), because the label is added above the field (and unset afterwards). Workaround is to not use elgg_view_input, but that creates inconsistency in the output. Do we consider this a bug?

/cc @hypeJunction

**Comment by hypeJunction** [comment]
https://github.com/Elgg/Elgg/pull/9892
