### ISSUE TITLE
clone $entity should reset timestamps

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10033]
currently if you clone an entity, you need to update the time_created and time_updated (and time_last_action if it is a user).

could be part of the entity __clone function

**Comment by mrclay** [comment]
If properties change, is it really a clone?

**Comment by mrclay** [comment]
Eh, sounds fine to me.

**Comment by jdalsem** [comment]
> If properties change, is it really a clone?

Date of birth of Dolly was also not the same as her 'parent'... still we consider her a clone https://en.wikipedia.org/wiki/Dolly_(sheep)
