### ISSUE TITLE
elgg_entity_gatekeeper should return entity on success

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10032]
current workflow:
```
elgg_entity_gatekeeper($guid, 'object', 'blog');
$blog = get_entity($guid);
```

could be improved to
```
$blog = elgg_entity_gatekeeper($guid, 'object', 'blog');
```

**Comment by hypeJunction** [comment]
I would rather keep elgg_entity_gatekeeper() lightweight.

**Comment by jdalsem** [comment]
why? we already load the entity in the function and current return void... what is keeping it lightweight?

**Comment by mrclay** [comment]
Duplicate of #8973.
