### ISSUE TITLE
FR: manifest check for plugin version

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10049]
Currently a plugin can require/suggest another plugin (including version).

What we want is a requirement for a plugin version only. So it's not required to have the plugin active, but IF it's active it needs to be version X

Use case: mostly in themes when overriding views/functions or calling certain plugin functions these functions need to be available. In an older version of the plugin the function isn't available, so if we call it we need to be able to 'garantee' that we use the correct version of a plugin

**Comment by jdalsem** [comment]
Not going to pursue this. I foresee a future where we get rid of manifest in favor of elgg-plugin or composer.json.

With an install focus on composer you already have the ability to require a specific plugin version.

**Comment by jdalsem** [comment]
or for this case you can use a composer conflict
