### ISSUE TITLE
Move some/all plugins to separate repos

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10045]
I've identified the steps to do this in (during 2.x) in #9419. It looks like a lot of work and I'm unwilling to take this on by myself.
- [ ] Decide `git filter-branch` vs `git subtree split` (extremely slow)
- [ ] How to setup Transfix?
- [ ] Decide which plugins will give the biggest ROI (to which ones do devs most want to add backwards-incompatible features?)
- [ ] Existing repos like [Elgg/blog](https://github.com/Elgg/blog): should we wipe and rebuild them or must we leave the old commits in place?
- [ ] Find the script @ewinslow used to make these
- [ ] Must we also distribute the docs that pertain to plugins?
- [ ] Decide a timeline

**Comment by Srokap** [comment]
You should be able to use git subtree split to separate directory with it's commit history. It is extra heavy operation though and it is fragile when it comes to renames from outside of subdir.

**Comment by hypeJunction** [comment]
It's a necessary step but I am also unwilling to invest time. Perhaps we could do this one plugin at a time. If we stick to semver and use proper constraints in Elgg's composer, I don't think breaking changes will be an issue.

**Comment by jeabakker** [comment]
github help page https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by jdalsem** [comment]
Steps to extract are documented in #11095 

I see no reason to forcefully extract plugins into repos. If someone is willing to invest the time feel free to do so and provide a PR. If there are more actions required for extraction you are free to update the docs.
