### ISSUE TITLE
Add methods to ElggGroup to enable/disable group tools

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10044]
Metadata names for group tools are hard to remember (I have to look up every time if it's _enable or _enabled and if it's true/false or yes/no). We should just hide this metadata logic behind `ElggGroup::isEnabledTool($tool)`, `ElggGroup::enableTool($tool)`, `ElggGroup::disableTool($tool)`, `ElggGroup::getEnabledTools()`

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/10558
