### ISSUE TITLE
elgg_normalize_url() with file names

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10057]
`elgg_normalize_url('robots.txt')` produces `http://robots.txt`

**Comment by mrclay** [comment]
It was built to assume domain-looking things "example.com" are domains. Bad assumption.

**Comment by mrclay** [comment]
Making a short whitelist in the function is probably the sanest option.

**Comment by mrclay** [comment]
Or check if there's a page handler registered. That would handle robots.txt and favicon.ico.

**Comment by hypeJunction** [comment]
We would need a method combining both page handlers and route hooks.

**Comment by jdalsem** [comment]
You can 'trick' the system by using a slash: `/robots.txt`

not going to try to find a good solution for these special cases... i think the overhead like checking for route definitions is not worth it
