### ISSUE TITLE
developer tools 'wrap views' options breaks some JS

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#10062]
in the course of using developer tools' option called 'wrap views' i have noticed several times that process in elgg fail unless i disable 'wrap views'. this has been over several years and i don't recall every example.
the most recent example was that the spinner buttons in the theme sandbox's 'javascript' tab do not work while 'wrap views' is enabled.
as i recall, i generally found issues when ajax was being used and so the issues may be mainly related to ajax or at least limited to javascript.

**Comment by mrclay** [comment]
> the spinner buttons in the theme sandbox's 'javascript' tab do not work while 'wrap views' is enabled

Works for me, Chrome and Firefox, caching on/off, 2.2, 2.1, and 1.12.

**Comment by mrclay** [comment]
Any messages in JS console?

**Comment by propertunist** [comment]
i just tested this again (after having updated my site's theme to better handle the position of the elgg spinner) and now the sandbox view of the spinner works with wrap views enabled. this is strange because i tested with my site disabled, so the changes i made shouldn't be relevant to the test. ill close this ticket unless i see it occur again.
