### ISSUE TITLE
popups open again after their trigger button/link is clicked to close the popup

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#10063]
since v.2.2 i am seeing that the popup dialogs that open from the topbar - such as juho's notifier and also the 'add items menu' - are incorrectly opening after they have been opened and then closed again.
1. click a button that triggers a popup to open.
2. click the same button to then close the popup.
3. the popup closes correctly but then opens again.

if i click on an area away from the popup or it's trigger button, then the popup correctly closes without reopening.

**Comment by hypeJunction** [comment]
Can you reproduce on a vanilla install?
My guess is that you have a duplicate binding somewhere. Can you check all your JS files for `rel="popup"` bindings?

**Comment by propertunist** [comment]
i have already tested with my theme disabled and with nothing other enabled that i know effect the popups. i just searched the whole elgg installation for ```rel=popup, rel="popup" and rel='popup'``` and nothing of relevance was found.. only instruction docs, core ui files and sandbox files were found.

**Comment by propertunist** [comment]
i just updated my two plugins that use popups launched from the topbar.. so that they make use of the new method of configuring popups and use less JS. however, that didn't resolve the issue with the popup being triggered to open after it has been triggered to close.

**Comment by hypeJunction** [comment]
I can't reproduce in Chrome. What browser are you using?

**Comment by propertunist** [comment]
ok, i am seeing the same behavior here with chromium 52 and firefox 48 on fedora 24.

**Comment by hypeJunction** [comment]
Ok, I reread the issue and see the problem, though I am inclined to think it's an intended behavior.

**Comment by propertunist** [comment]
in previous elgg versions, clicking the trigger buttons to close the popups did indeed just close them and not then reopen them. i'm not sure what benefit is offered by having a button that closes and then opens up a popup again. i feel this behavior is confusing and of no useful value to users. additionally this means that these buttons will change in behavior between versions without explanation.

**Comment by hypeJunction** [comment]
Fix in #10067
