### ISSUE TITLE
No way to get rid of manifest.json

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10083]
Both page handler and hook are registered as anonymous functions, so there is no way to get rid of it.  
- [ ] Manifest in walled garden mode

**Comment by jdalsem** [comment]
you can register your own pagehandler on manifest.json and with a head hook strip it from the links... so there is a way to get rid of them.... you just can't do it with unregister functions

**Comment by hypeJunction** [comment]
The idea I had in mind is to add some site settings:

- Use Elgg branding (toggles Powered by, favicons etc)
- Enable manifest.json (could be edited similar to robots.txt?)

**Comment by mrclay** [comment]
Simple setting to remove branding would be great.

**Comment by hypeJunction** [comment]
Fixed in #11545
