### ISSUE TITLE
Clean up getAccessArray()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10084]
and convert the global function calls to local methods.

See https://github.com/mrclay/Elgg-leaf/commit/b4d837a76c08ac2a37dff8f4c5a72eb73e31a0f4

**Comment by jdalsem** [comment]
@mrclay can you clarify this ticket a bit? Or close if no longer needed

**Comment by mrclay** [comment]
Clarified title & desc

**Comment by jdalsem** [comment]
With the latest changes, this has been cleaned up enough for know i think
