### ISSUE TITLE
Documentation mistake - javascript, views.php

### ISSUE THREAD

**Issue by knezmilos13** [Elgg/Elgg#10082]
Documentation states that, to include AMD JS modules from external folders (e.g. vendor), file views.php should be added to root of the plugin:

```
<?php // views.php
return [
    'underscore.js' => 'vendor/bower-asset/underscore/underscore.min.js',
];
````

However, after some debugging, I've come to the conclusion that the returned array should actually look like this:

```            
<?php // views.php
return [
    'default' => [
        'underscore.js' => 'vendor/bower-asset/underscore/underscore.min.js',
    ]
];
```

So it seems to be a mistake in documentaion, although it could also be the way it was intended to work, but the code is then wrong?

**Comment by mrclay** [comment]
Good catch! The docs example is missing the viewtype ("default").
