### ISSUE TITLE
Travis commit message test

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10089]
Something is odd is happening on Travis. It loops through the entire commit message history instead of just checking the PR range.

**Comment by mrclay** [comment]
I noticed that yesterday. I just made another PR and the problem stopped, but I don't know why.

**Comment by hypeJunction** [comment]
Still doing it here: https://travis-ci.org/Elgg/Elgg/jobs/152647975

**Comment by hypeJunction** [comment]
Seems to be working fine now. I have reset the head and cherry picked the commit. Something must have crawled into the git refs.
