### ISSUE TITLE
Input wrapper with custom HTML

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10090]
I am missing an option to wrap custom input HTML using `elgg_view_input()`. How do we feel about allowing null input name with input parameter?

``` php
elgg_view_input(null, [
   'input' => $input_html,
   'label' => 'My label',
]);
```

**Comment by hypeJunction** [comment]
Use cases:

- Multiple input group (with standard markup for consistency)
- Inputs with post/prefixes
- Custom HTML

**Comment by mrclay** [comment]
What would be the output? Just a div wrapper with label? Should it be a fieldset?

**Comment by hypeJunction** [comment]
That would be a shortcut for e.g.:

```php

ob_start();
foreach ($rows as $row) {
	$type = $row->type;
	$subtype = $row->subtype;
	echo elgg_view_input('checkbox', [
		'name' => "params[$type:$subtype]",
		'value' => '1',
		'default' => '0',
		'checked' => (bool) $entity->{"$type:$subtype"},
		'label' => elgg_echo("item:$type:$subtype"),
	]);
}
$inputs = ob_get_clean();

echo elgg_view('elements/forms/field', [
	'input' => $inputs,
	'label' => elgg_echo('attachments:settings:allow_attachments'),
]);
```

**Comment by hypeJunction** [comment]
Actually fieldset could work. We would need to add some extra styling because our CSS is very generous at styling `form fieldset`.

```php
elgg_view_input('fieldset', [
   'legend' => $legend,
   'body' => $inputs,
]);
```

**Comment by hypeJunction** [comment]
While at it, I could finally add the button bank - tired of having to style buttons horizontally all the time. #7907

**Comment by hypeJunction** [comment]
PR #10315
