### ISSUE TITLE
RTL text output not correctly formatted in river entries title / subtext

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10104]
I noticed it with the recent postings made to the Arabic support group: https://elgg.org/groups/profile/621896/arabic-support-group-%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9.

The group activity entries show title text inbetween the friendly time output. I don't know if this only happens in river entries or also in other views (listings / full views).

**Comment by iionly** [comment]
I don't care anymore about that.

**Comment by jdalsem** [comment]
This is not an issue with latest Elgg versions
