### ISSUE TITLE
Something allowed a user to like river:comment:site:default and appear on all profile pages

### ISSUE THREAD

**Issue by topdog08** [Elgg/Elgg#10107]
A user was trying to "Like" a new user or their content, they don't remember which, but instead got:

    1 like

river:comment:site:default 7 days ago
.

From that point on this user appeared in the activity profile widget for all users, or at least users whose activity for joining the site still appeared in the activity widget, which somehow matches with that text, although I could not find that string in the en.php language files, at least not the default language file.

It is possible the new user they were trying to like was deleted or had some type of error, I don't know.

However this user was able to like river:comment:site:default, which should be avoided to prevent this.
Deleting the comment fixed it, but wasn't intuitive to find and users thought our site had been hacked.

Our site is running Elgg 2.1.2.

**Comment by hypeJunction** [comment]
Elgg doesn't add a river item for new site users. Look in profile manager.

**Comment by topdog08** [comment]
Well, profile_manager has this but not an exact match:
	// river events
	'river:join:site:default' => '%s joined the site',
Which is probably why there is no message substitution, but the bottom line is how can you Like something that is a message template?  That doesn't seem like it should be allowed to happen?

**Comment by mrclay** [comment]
Report the issue here: https://github.com/ColdTrick/profile_manager/issues
