### ISSUE TITLE
Fatal sql error when loading plugins

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10119]
There is an edge case where there are no suitable plugins to be loaded (i ran into this when disabling all plugins, other than a plugin with over 40 private settings)

https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/BootData.php#L122

After removing all unsuitable plugins, there is the change no guids are left to load... it should quick return then... 

This is an edge case, but easy to fix

**Comment by mrclay** [comment]
Just curious, is the plugin with over 40 settings unusual? 40 is a completely arbitrary limit.

**Comment by jdalsem** [comment]
i do not know... i could check, but whatever the limit, the problem is still there

**Comment by mrclay** [comment]
PR #10123

**Comment by mrclay** [comment]
Fixed by #10123
