### ISSUE TITLE
elgg_get_excerpt() fails on some viewtypes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10114]
Strawman: Pass in `default` viewtype here: https://github.com/Elgg/Elgg/pull/9702/files#diff-90baf5f7cbaeb6acb5cdca9a5117d48dR77

**Comment by jdalsem** [comment]
this problem is more generic i think... as any function that uses a view for output does not function... like elgg_view_friendly_time or elgg_view_entity_list... as long as there is no fallback

**Comment by mrclay** [comment]
Also it's probably best to temporarily set the global viewtype within those functions, in case the views use subviews.

**Comment by mrclay** [comment]
See #10127
