### ISSUE TITLE
Bulk delete/disable operations

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10113]
For the sake of consistency, testability and cache reliability, I suggest that we update all bulk delete/disable operations to use batches. Now that I look closer at our DB APIs, I imagine some of the plugins might be suffering from inconsistencies in their data model. Even though a user delete is wiping all related data, plugins might want to perform certain operations when individual relationships, metadata, annotations etc are deleted.

**Comment by jdalsem** [comment]
Closing this ticket as it is too generic. We use various batch features already in the system. If you now of any places that require a batch, please let us know. We found one that we will fix in the near future already: https://github.com/Elgg/Elgg/issues/13038
