### ISSUE TITLE
elgg.deprecated_notice always outputs deprecation notices to admins regardless of debug level

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10120]
sendNotice() outputs deprecation notices as warnings, i.e. I can suppress them when debugging is turned off or set to errors only.

But elgg.deprecated_notice() only checks if logged in user is an admin and if that's true you always get to see the deprecation messages... on screen. That's not very good on a productive site even if only admins get to see them.

**Comment by mrclay** [comment]
One solution can be copied from an existing PR:
https://github.com/Elgg/Elgg/pull/9028/files#diff-fc047865b3b754b8daaca4c9714e0f41L404

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10134.
