### ISSUE TITLE
Memcache: Store last_action via separate key

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10125]
This attribute is constantly changing for logged in users, and (less frequently) objects being commented on. We'd get more usable cache hits by storing it separately.

**Comment by mrclay** [comment]
Dipped into this and it seems not worth the added complexity. We have to write to memcache anyway, so might as well write the whole entity.

**Comment by teamwebgalli** [comment]
@mrclay: the last_action should not be cached. For example, while working on the users_online plugin we experienced this problem. Since the last_action is cached it will not show the user as online.
Or is there any other API to get metadata without caching?

**Comment by hypeJunction** [comment]
Last action is an attribute. For users, it's updated with a delayed query and until recently the attribute wasn't updated instantly. Check if the issue you are having exists on 2.x branch. I don't think cache is related to your problem.

**Comment by jdalsem** [comment]
I am not convinced that @teamwebgalli s issue is related to this issue. If there is more info please open an new issue for it.
