### ISSUE TITLE
Update htmlawed library, last patch in March

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10126]
We're currently relying on a user who took the `htmlawed` namespace (but is unaffiliated), is almost 6 months behind propagating a patch, and is ignoring my PR https://github.com/kesar/HTMLawed/pull/13.

The second packagist entry is https://github.com/vanilla/htmlawed, but it adds its own functionality (would need to review to see if done safely) and at least [took a month](https://github.com/vanilla/htmlawed/commit/360ab1d5621b25643e41be446ddf8a8fafec59f0) to distribute the last patch.

**Comment by kesar** [comment]
my apologies about this. I will keep updating the library more often, specially for this security issues.

Thanks for the contribution @mrclay

**Comment by mrclay** [comment]
Fixed by #10143
