### ISSUE TITLE
MetadataTable::create() should validate entity existence

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10130]
Needs to validate that entity exists before writing row to database

**Comment by mrclay** [comment]
Seems like a rare case. Where's this causing trouble?

**Comment by hypeJunction** [comment]
`create_metadata()` doesn't validate it either, so you can just populate metadata with useless rows.

**Comment by mrclay** [comment]
I guess it would be nice to at least log an error.
