### ISSUE TITLE
ACCESS_LOGGED_IN and has_access_to_entity()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10133]
We have a flaw in our access check that manifests in notifications handling. If an item is saved with `ACCESS_LOGGED_IN`, user never gets notified about it because the SQL query in `has_access_to_entity()` does not include 1.

**Comment by hypeJunction** [comment]
I imagine this could also be a problem in a walled garden mode for public entities. I think the easiest solution is to just check explicitly in the notifications handler as I did here:  
https://github.com/Elgg/Elgg/pull/10139/files#diff-2b9c30fbd3c7363dc5506b5090f57fdeR444

But the fix would have to go into 1.12.

**Comment by mrclay** [comment]
PR #10142

**Comment by hypeJunction** [comment]
False alarm. Tests in #10175 are passing - I suppose this is taken care of somewhere in the access SQL query builder...

**Comment by hypeJunction** [comment]
Come to think of it, tests were failing in #10139, so I will need to dig deeper to see what's up.
We may still want to add https://github.com/Elgg/Elgg/pull/10142 - it may boost performance, since we won't need to query the database for access collections for each user.

**Comment by hypeJunction** [comment]
Fixed in #10139
