### ISSUE TITLE
Issue admin notices on table crashes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10146]
Related to #4993, log table crashes [seem to be most common](https://elgg.org/discussion/view/2533851/elgg-system-log-tables-get-corrupted-frequently), and I think few would consider a failed log insert worthy of disabling a site, so I suggest we handle these exceptions, log an error, and create an admin notice.

Other idea: Convert system_log (and other non-FTS tables) to InnoDB.

**Comment by mrclay** [comment]
`Elgg\Database::executeDelayedQueries` already swallows and logs exceptions.

**Comment by jdalsem** [comment]
Not experiencing this problem myself. Not going to bother with this for now.
