### ISSUE TITLE
Commit message checker sometimes checks all repo commits

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10158]
Anecdotally I fixed a PR by resetting my base branch to match origin exactly:

``` bash
git checkout 2.x
git reset --hard origin/2.x
```

...then I rebased the PR.

Maybe local use of `git pull` on the base branches is sometimes causing a merge instead of a fast-forward.

Would be nice if `.scripts/travis/check_commit_msgs.sh` could warn submitters about this instead of proceeding to go crazy.

**Comment by mrclay** [comment]
We removed the git depth limitation. It might help.

**Comment by jdalsem** [comment]
I am not experiencing this issue. If you still have this problem let us know.
