### ISSUE TITLE
update htmlawed dependency

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10166]
currently the htmlawed plugins uses 1.1.19 (5 apr 2015).
i suggest the dependency is updated to the latest version (1.1.22)

i am especially interested in 1.1.20 as that version adds the 'allowfullscreen' as a valid attribute (custom) for iframe elements. This is useful when people embed youtube videos which use this custom attribute. Otherwise youtube videos will be missing the fullscreen toggle button.

**Comment by mrclay** [comment]
Fixed #10143
