### ISSUE TITLE
API reference for 2.1 and 2.2 don't work

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10169]
It works for

http://reference.elgg.org/1.12/
http://reference.elgg.org/2.x/
http://reference.elgg.org/master/

and the default is still

http://reference.elgg.org/2.0/ (= http://reference.elgg.org).

But it fails for 2.1 and 2.2 branches.

**Comment by mrclay** [comment]
Done. https://github.com/Elgg/elgg-scripts/commit/16e4af1c86055b4e62797cc913e6e713f7784b23#commitcomment-18922443
