### ISSUE TITLE
Which release docs to use?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10174]
I am lost in our release docs. Steps vary between branches and I am not sure which is to be used.

**Comment by juho-jaakkola** [comment]
AFAIK the only difference is the part where you make the package: http://learn.elgg.org/en/2.0/contribute/releases.html#build-zip-package-for-elgg-1-n-n

Elgg 2 package contains the starter-project that has Elgg as a dependency where as Elgg 1 has core code in the root and only the dependencies are installed with Composer.

Does that clear it up?

**Comment by jdalsem** [comment]
Closing this... if you need more info just ask
