### ISSUE TITLE
Reference docs include private APIs

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10171]
😿  http://reference.elgg.org/2.2/engine_2lib_2autoloader_8php.html#a894b7a34d2c78531d294f38bf6dee317

**Comment by jdalsem** [comment]
any idea how to filter them out?

**Comment by mrclay** [comment]
I don't know. I'd like to switch to PhpDocumentor, and integrate some hand-picked API docs into elgg.org: https://github.com/Elgg/Elgg/pull/10179

**Comment by jdalsem** [comment]
so the plan is also to drop the reference as we know it?? Not using it btw

**Comment by mrclay** [comment]
Was thinking PhpDocumentor for the reference, if we keep it. No plan, just an idea.

**Comment by jdalsem** [comment]
going to leave the references as is for now
