### ISSUE TITLE
"Activate all plugins" can result in fatal error

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10181]
Test case: hypeApps and hypeWall plugins (requires hypeApps). Start with both plugins disabled. Then click on "Activate all". Result is

PHP Fatal error:  Class 'hypeJunction\\Plugin' not found in /xxx/mod/hypeWall/classes/hypeJunction/Wall/Plugin.php on line 16

The hypeWall plugin extends a class of hypeApps. Plugin dependencies seem correctly defined in manifest.xml. Nevertheless, the error.

**Comment by iionly** [comment]
@hypeJunction is this an issue with your plugins only or a general issue?

**Comment by hypeJunction** [comment]
I guess it's an issue with plugins depending on each other. Need to check. hypeApps is hopefully going away soon.

**Comment by jdalsem** [comment]
For now assuming this is a plugin related issue... could potentially be a racing condition or related to the assumption of classes available in active.php plugin file. Please reopen if there is more info

**Comment by iionly** [comment]
I don't think it's an issue related to specific plugins but rather an issue related to making use/extending a class introduced by a plugin within another plugin.

The parent class is simply not yet available at the time of activation of the "child plugin" when enabling all plugins at once even if the plugin dependency on a "parent plugin" is correctly defined in manifest.xml.

This problem might occur more often in future if more plugins make use of classes (provided by other plugins).

**Comment by mrclay** [comment]
Simplest solution: Activate All should refuse to activate a plugin that requires an inactive plugin and spit out a message to that effect.
