### ISSUE TITLE
jquery-ui 1.12 not fully compatible with jquery-ui 1.11

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10199]
jquery-ui 1.11.4 was included up until Elgg 2.1.2. In Elgg 2.1.3 and 2.2.0 it's jquery-ui 1.12.0.

Problem is that jquery 1.12 is not fully BC with 1.11. I now have a problem with the html5 uploader (plupload) in Tidypics that now has issues on Elgg 2.1.3 and newer. There's not even a plupload release avaiable that works with jquery-ui 1.12. And I don't know if I want to start modifying 3rd party scripts to fix BC issues.

Was the change from jquery-ui 1.11 to 1.12 intentional? If not, would it be possible to switch back to jquery-ui 1.11 for the release of Elgg 2.2.1 and the following 2.x releases?

**Comment by mrclay** [comment]
AFAIK was not intentional and was due to us not using a lock file. composer just started matching 1.12 in the release process. Make a new branch, use `composer require bower-asset/jquery-ui '1.11.*'`. If the install works, send the PR updating the lock file.

I'd be OK reverting to `1.11.*`, dunno about the rest of the team.

**Comment by iionly** [comment]
What about composer.json? For all the bower-asset stuff required in composer.json the caret ^ operator is used. This is supposed to pull the version given or a newer BC-compatible version (with semver version numbering in mind). But what if the assets don't completely follow semver? For jquery-ui this is already not the case as 1.12.* is not fully BC-compatible with 1.11.*. Could the same also happen with the other assets resulting in either obvious failures or (maybe even worse) not so obvious errors.

Is the composer.lock file the primary solution for defining the versions of required packages to pull or should the composer.json file be used first?

**Comment by mrclay** [comment]
Command I gave should update composer.json too.

**Comment by iionly** [comment]
Okay. I've made a test installation after executing the command you gave me (therefore jquery-ui in version 1.11.4). It seems the installation runs fine (also tested with Tidypics added).

Now I have a composer.json and composer.lock. Do I have to include both files in the PR? I'm not sure as I don't see a composer.lock in the Elgg repo.

**Comment by iionly** [comment]
Well, there's none in the 2.2 branch but there is one in the 2.x branch. So, I'll just make a PR with both files for now.

**Comment by iionly** [comment]
PR made: https://github.com/Elgg/Elgg/pull/10202.

composer.lock is listed in .gitignore and therefore haven't been added to the commit. Now I'm really confused.

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10202.
