### ISSUE TITLE
3rd party site mentioned in Italian translations

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10192]
`'actiongatekeeper:crosssitelogin' => "Spiacenti, non è possibile entrare da un altro dominio. Per favore clicca sul logo Social Business World e poi riprova, grazie.",`

I'm sure this was an accident.

**Comment by iionly** [comment]
Surely an accident by Michele who provided the Italian translation (initially). Someone else also complained about such a kind of mistake (I don't know if only in this one string or maybe in others, too). This other guy seemed to have updated the Italian translations at least to a certain extend. Though he might have modified only the 1.x translations. In 1.12 the same string currently is translated as

`'actiongatekeeper:crosssitelogin' => "Spiacenti, l'accesso al sito da un dominio differente non è permesso. Per favore riprovare.",`

**Comment by michelesbw** [comment]
Can confirm this has been corrected in Transifex https://www.transifex.com/elgg/elgg-core-2/translate/#it/engine/58929060?q=different%20domain
