### ISSUE TITLE
Add an elgg_gpl plugin for GPL sources

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10198]
This would allow us to integrate GPL functions, classes, views, assets (form Drupal/WordPress/existing 3rd party plugins) and still make MIT releases. Of course, core must be able to function without it.

Came to mind looking at this [friendly time code](https://github.com/iionly/friendly_time/blob/master/start.php) we probably want to pull in. cc/ @iionly

**Comment by mrclay** [comment]
@brettp You think this would meet our obligations?

**Comment by jdalsem** [comment]
i believe there is no need for this. The MIT release is just core and no plugins, so nothing special needed here.
