### ISSUE TITLE
Break down groups/all resource view

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10190]
It's easy enough to add new tabs to the groups/all filter, but adding new views is complicated. Also, if you want to change the order of entities in one of the tabs, you have to hijack the entire view. I propose, we break it down into subviews, and use some magic for matching a view to selected tab (filter) value.

**Comment by hypeJunction** [comment]
Actually what we need is an easy way to create a resource collection. In case of groups, it would be nice to just say extend groups/all resource collection with the discussion/all resource. Both resource views would need to get an identical set of tabs. I imagine we need to hack the layout filter and make sure the filter menu is rendered on all pages (without the magical All/Mine/Friends), so we can hook into the menu.

**Comment by hypeJunction** [comment]
See #10191

**Comment by mrclay** [comment]
Same with blog/all I think.

**Comment by hypeJunction** [comment]
There is more I am sure.

**Comment by jdalsem** [comment]
Splitting groups/all is done in https://github.com/Elgg/Elgg/commit/c6de14c2f974f85147b06bc0f085fcc492c6bed2
