### ISSUE TITLE
Error pages should use default shell

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10203]
Errors in admin context are displayed in the admin shell even for logged out users. I think this is byproduct of the response API.

**Comment by mrclay** [comment]
Confirmed on 2.x. Log out, go to /admin/users/newest.

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/Http/ResponseFactory.php#L414 The HTTP code gets set to 403, then on [line 456] it doesn't consider the response a redirect.

**Comment by mrclay** [comment]
Then on [216](https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/Http/ResponseFactory.php#L216) it's not seen as a redirect because it's also a client error.

**Comment by mrclay** [comment]
I think just a special case has to be made for redirect with `$status_code = 'admin'`.

**Comment by hypeJunction** [comment]
PR #10273
