### ISSUE TITLE
Topbar and account menu overhaul

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10201]
Try this plugin (2.*) https://github.com/mrclay/Elgg-mrclay_aalborg

The topbar would go away, with items moving into the navbar area on right, or into a new user account menu that opens when the profile icon is clicked.

The gear icon would only be seen by admins and would open the admin lightbox currently in the developers plugin.

I guess I'm looking for some consensus around this idea before I commit a bunch of time to moving stuff from the plugin into aalborg/core.

![01_tablet-layout](https://cloud.githubusercontent.com/assets/170687/12270939/b21fc4fc-b926-11e5-935b-42632d8dab3f.png)

The user account menu (inspired by G+):
![03_topbar-hover1](https://cloud.githubusercontent.com/assets/170687/12270940/b2205192-b926-11e5-8dad-8a3d7d03da4f.png)
![04_topbar-hover2](https://cloud.githubusercontent.com/assets/170687/12270942/b22990e0-b926-11e5-835a-c69a77a61dfb.png)

**Comment by jdalsem** [comment]
Where do you see the search bar in this approach?

**Comment by jdalsem** [comment]
I think moving things to right is fine by me...

But how about another additional change:
![Office 365 Waffle](https://epmpire.files.wordpress.com/2014/12/image.png)

Currently Elgg is very tool/app/feature oriented. What if the site menu is something similar to the waffles of Office 365 and Google Apps...
 
The rest of the menu bar then can be used for a breadcrumb path or for other menu items (not tools)

**Comment by mrclay** [comment]
I was wrong! My demo plugin works on 2.*. Search didn't move, it's still buried in the 2nd column on smaller viewports. There should be a [search icon](http://fontawesome.io/icon/search/) somewhere that creates the input.

**Comment by juho-jaakkola** [comment]
I like the changes made both to topbar and the account menu.

**Comment by jdalsem** [comment]
Removing from milestone... Elgg needs more theming work... maybe during 3.x we can create a new design as a plugin that can go into core in 4.x
