### ISSUE TITLE
Users should know they're entering HTML

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10219]
When we let users disable the editor they have to click "Edit HTML," which is good, but there are a few problems:
- We devs assume a longtext input accepts HTML, most users don't, and will be surprised to have their content interpreted or undesirably filtered.
- When CKeditor is in the HTML state, "HTML" is not visible. Particularly now that devs can start editors in the HTML state, users will be unaware.

Strawman: input/longtext displays a little "HTML" tab on the right side. If CKeditor loads, it adds the "visual" tab and switches to it (or not).

**Comment by hypeJunction** [comment]
We could look into ``contenteditable``

**Comment by mrclay** [comment]
If you mean other rich text editors, sure. contenteditable is a nightmare.

**Comment by hypeJunction** [comment]
I meant the attribute. I have only used it a few times and didn't have any issues with it.

**Comment by hypeJunction** [comment]
Oh, now I get it. You just want to display a badge that differentiates a plaintext input from html input

**Comment by mrclay** [comment]
Seems like this would discourage entry. Users would scream at the screen "I have to write HTML!? Forget it."
