### ISSUE TITLE
Redis ideas dump

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10227]
- Replace Memcache usage
- Store metadata for each entity (drop access control #9050)
- Cache the GUIDs in each ACL as a set. has_access_to_entity(), can check that set.
- Replace queue
- Cache and query relationships ([slide 17](http://www.slideshare.net/itamarhaber/redis-use-patterns-devcontlv-june-2014))

Just doing some brainstorming here.

**Comment by jdalsem** [comment]
Need more specific actions to act on
