### ISSUE TITLE
Future of form views

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10223]
How strongly do feel about keeping form views? I would like to move towards hookable form field config (a bit tired of trying to figure which view overrides which views that extends which view). Current strawman I have in mind:
`elgg_view_form()` triggers a `fields, <action_name>` hook and uses a convenience function to render a form. We could have a fallback to views, but I would rather we move away from using them, and shim  whatever special uses cases we may run into.

**Comment by mrclay** [comment]
If nothing is returned from the hook, we use the views? Sounds BC. I guess I want to make sure we can extend the hook-based approach. I think Drupal forms hits the sweet spot of configurability without too much complexity (I remember Zend Form... do not want to remember).

**Comment by juho-jaakkola** [comment]
Doesn't sound too drastic.

**Comment by hypeJunction** [comment]
Ref #10315

**Comment by jdalsem** [comment]
Currently we have already some nice improvements made on the form functionality:
- hookable fields config
- hookable body vars preparation
- auto sticky form logic

You will still need to call the fields config in your form view. We will keep that for now as we need to learn which issues we need to fix first with the fields/body config before moving forward. New tickets will be created if we are improving this system further.
