### ISSUE TITLE
Cache/upgrade unusable on port-forwarded configurations

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#10236]
Problem: While developing I can't use the cache or run upgrade.php (well there is a workaround for upgrade.php).

Reason: Elgg checks the connection to itself before allowing upgrades to occur, or attempting to use the symlink cache.  In a port forwarded configuration the port of the external URL is not the port the system can use when using curl or get_headers() so those fail.

    /**
     * Checks if /cache has been symlinked to views simplecache directory,
     * and if HTTP requests to /cache are are successful
     * @return bool
     * @access private
     */
    function _elgg_is_cache_symlinked() {
	if (!is_dir(elgg_get_root_path() . 'cache/')) {
		return false;
	}
	$headers = get_headers(elgg_get_simplecache_url('elgg.js'));
	return substr($headers[0], 9, 3) == 200;
    }

Proposal: Add a config flag for power users to bypass the internal connection checks for these instances.

**Comment by beck24** [comment]
Or get rid of the connection checks... are they really necessary?

**Comment by mrclay** [comment]
Does the commit where this was added tell us why it was added?

**Comment by hypeJunction** [comment]
I think I added the function for the purposes of symlinking from admin, but I am not sure where else it's called from.

**Comment by hypeJunction** [comment]
@beck24 Are you sure you traced it back correctly? This function is only used in an action that attempts to symlink /cache to /views_simplecache. It's not used to test anything else.

**Comment by mrclay** [comment]
Here's the real culprit https://github.com/Elgg/Elgg/pull/7006

**Comment by mrclay** [comment]
We blocked upgrade due to this bug https://github.com/Elgg/Elgg/issues/6521. Maybe not relevant anymore?

**Comment by juho-jaakkola** [comment]
Seems safe to remove in Elgg 3.

**Comment by hypeJunction** [comment]
As far as I can tell, you don't have to use this action, if it fails for you. After all it's your dev environment.

**Comment by hypeJunction** [comment]
Did you setup hosts file mapping on your box?

**Comment by mrclay** [comment]
Are you saying you get a 500/error for the settings page?
