### ISSUE TITLE
fix usage of deprecated can_write_to_container

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10238]

**Comment by hypeJunction** [comment]
Are there any left? I thought @mrclay fixed up the rest of them

**Comment by mrclay** [comment]
My progress got stalled https://github.com/Elgg/Elgg/pull/9888

**Comment by mrclay** [comment]
According to @hypeJunction some subpages permissions are already messed up and I didn't want to add to the confusion, but I think #9888 doesn't need to stall for that.

**Comment by jdalsem** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/9888
