### ISSUE TITLE
Elgg 2.x admin page shows a lot of information when logged out

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10258]
when logged out goto /admin. you'll see something like

![admin logged out](https://cloud.githubusercontent.com/assets/881958/18794500/07a63c32-81c0-11e6-933c-b083db9ddf05.png)

I think this shows a little bit to much info and a some incorrect info (like in the topbar 'logged in as')

I believe this has todo with @hypeJunction ResponseCode refactor. 

What to do?

**Comment by jdalsem** [comment]
can not release this way

**Comment by mrclay** [comment]
Duplicate of #10203
