### ISSUE TITLE
notification subject is broken

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10265]
when receiving an email notification i get the following broken subject

![notification subject](https://cloud.githubusercontent.com/assets/881958/18797523/94c02958-81ce-11e6-99f2-259ac73f7879.png)

the charset and further part is caused by https://github.com/Elgg/Elgg/blob/2.x/engine/lib/notification.php#L561 which has to much info

the double subject i have to find yet

**Comment by jeabakker** [comment]
everything look good until https://github.com/Elgg/Elgg/blob/2.x/engine/lib/notification.php#L613

so it's the lib that breaks it, just have to find out why

**Comment by jdalsem** [comment]
Is this still an issue?

**Comment by jeabakker** [comment]
haven't encountered this problem in a long while, so closing
