### ISSUE TITLE
output/url with href=false should output url with javascript:return void();

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10260]
currently output is an `<a>` without a href attribute..

we should also change the menuitems that are initialize with href false to output an url with javascript:void...

currently we have to many links with `href='#'` that jump the page....

**Comment by mrclay** [comment]
`=== false` then sure, use `javascript:void(0)`.

`== false` let this be interpretted as `""` (home page URL).

> change the menu items that are initialize with href false to output an url with javascript:void

I'm OK with current behavior, with spans.
