### ISSUE TITLE
Survey of server stacks

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10262]
Elgg sites that get any traction need to add additional services like Memcache. What other services are Elgg devs experienced in running in production (besides PHP/MySQL)?

E.g. We need to pick a [Pusher-like server implementation](https://github.com/Elgg/Elgg/issues/10200).

**Comment by juho-jaakkola** [comment]
Used so far only in demo environments, but documenting here anyway: ZeroMQ http://zeromq.org/

**Comment by juho-jaakkola** [comment]
http://wkhtmltopdf.org/ for generating PDF files from Elgg data/content.

**Comment by mrclay** [comment]
To be clear Rachet & ZeroMQ turn PHP into a WS server. Performance vs Node is unknown.

**Comment by beck24** [comment]
I lean on Solr for most large projects

**Comment by jeabakker** [comment]
we had memcache on some projects, but as of 2.0 we found that it slowed down more than it helped (with multiple webservers) as the network overhead of memcache was probably slowing it down.

we added elasticsearch to take the performance hit of mysql and moved mysql to innodb

**Comment by jeabakker** [comment]
next up is a mysql cluster for a project ;)

**Comment by jdalsem** [comment]
We should not use the github issues as a survey... if you want more data, we should request it on the elgg community
