### ISSUE TITLE
input/select menu items cut off at the left

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10276]
This is an issue both on Elgg 1.12 and 2.2.

**Comment by mrclay** [comment]
Probably would be fixed by https://github.com/Elgg/Elgg/pull/9288

**Comment by iionly** [comment]
It seems to be a Firefox issue. I tried to figure out when the problem started to show up first and noticed that it shows up back to 1.10 - and I was sure that this wasn't the case previously. Then I checked how it looks in Chrome and the problem with the cut off dropdown selects does not appear there.

**Comment by iionly** [comment]
Cut-off input select button elements were not an Elgg issue.

Instead it seems that the Oxygen-Gtk theme of Kde was no longer playing well with the recent releases of firefox. Switching to the Adwaita-gtk theme fixed the issue.
