### ISSUE TITLE
Setting lightbox size using elgg/lightbox not working / not working as expected.

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10282]
Use case: full-size image view in a lightbox in Tidypics. As some images might be larger than the screen size it's necessary to limit height and width of the lightbox (95%). Old way: binding tidypics-lightbox class to colorbox with using options maxWidth and maxHeight.

As I understand I should not be able to use data-colorbox-opts to achieve the same, e.g.
```php
$attachments = elgg_view_entity_icon($image, $preview_size, array(
		'href' => 'ajax/view/photos/popup_single?guid=' . $image->getGUID(),
		'title' => $image->title,
		'img_class' => 'tidypics-photo',
		'link_class' => 'elgg-lightbox',
		'data-colorbox-opts' => json_encode([
			'maxWidth' => '95%',
			'maxHeight' => '95%',
		]),
	));
```
Unfortunately, this does not work. Either the lightbox opens much too small in size (mostly on the first try) or it is much too large for large images, i.e. maxHeight/maxWidth not taken into account.

**Comment by mrclay** [comment]
Are those values not taken into account at all?

**Comment by mrclay** [comment]
You could set a breakpoint in elgg/lightbox:getOptions and see what options are getting to `$.colorbox.open()`.

**Comment by iionly** [comment]
I think none of the values set in data-colorbox-opts are taken into account. And I believe the problem is already at retrieving the data with
```
dataOpts = $this.data('colorboxOpts');
```
I made a test by assinging a json object with the desired values immediately after this line and then it works (for testing displaying an image using elgg-lightbox and setting photo:true instead of using elgg-lightbox-photo).

**Comment by hypeJunction** [comment]
I wouldn't rely on entity icon view to have support for arbitrary `data-` attributes. They probably get stripped and you don't even have them in the markup.

**Comment by iionly** [comment]
@hypeJunction Sorry. I can't follow you here. data-colorbox-opts is supposed to set valid colorbox attributes. And "photo" is a valid attribute. I just gave the example that setting the photo attribute doesn't work with elgg-lightbox class (when using elgg-lightbox-photo class this attribute is set internally in elgg/lightbox). The valid colorbox attributes is really want to set via data-colorbox-opts are maxHeight and maxWidth. And those won't work either. The point is that I can't use elgg/lightbox but have to stay with binding colorbox the old way directly to the element if I can't set the colorbox attributes via data-colorbox-opts as it is now supposed to be possible.

**Comment by hypeJunction** [comment]
You are using `elgg_view_entity_icon()` which in term is rendered by `icon/` views. I doubt that you have data-colorbox-opts in the output generated by elgg_view_entity_icon().
Try the same with output/url.

**Comment by mrclay** [comment]
The icon/default view does not pass along arbitrary attributes to the anchor. If want to add that we could add `link_attrs` option in those icon views.

**Comment by mrclay** [comment]
Just use the code @hypeJunction posted. We're already late shipping 2.3.

**Comment by iionly** [comment]
Tried it with
```php
	$img = elgg_view_entity_icon($image, $preview_size, array(
		'href' => false,
		'img_class' => 'tidypics-photo',
	));

	$attachments = elgg_view('output/url', [
		'href' => $image->getIconURL('master'),
		'text' => $img,
		'class' => 'elgg-lightbox-photo',
		'data-colorbox-opts' => json_encode([
			'maxWidth' => '95%',
			'maxHeight' => '95%',
		]),
	]);
```
and it worked - not with 'use_link' though ;-)

Maybe passing the data attributes when using the icon views would be helpful in future. It would be less code necessary (and maybe others wouldn't fall intro the same trap as I did).

**Comment by hypeJunction** [comment]
@iionly Feel free to make a PR.

**Comment by mrclay** [comment]
It might have been unwise to combine link creation and icon creation in the API.

**Comment by iionly** [comment]
I've looked at the code of elgg_view_entity_icon() and the views involved. Now I'm no longer sure it will make sense to "fix" anything here. output/url is called by the icon/* views, so it would be possible to retrieve the data-colorbox-opts attribute from $vars and add to $params for output/url. But the problem is that it's not only a single icon view involved but there could be any number of icon/type/subtype view - also coming from any 3rd party plugins. I think it would be quite confusing to require any icon view to be used with elgg_view_entity_icon() to handle the data-colorbox-opts attribute that is then to be dealt with in output/url just for the theoretical case that anyone wants to open the href link of elgg_view_entity_icon() in a lightbox. If such a situation ever arises it might be easier to use output/url directly as suggested by @hypeJunction or just to modify the specific icon/type/subtype view involved then.

**Comment by mrclay** [comment]
Right. This should just be a lesson the next time we want to add wrapper elements in views. We have the same ambiguity problem with menu items.

**Comment by hypeJunction** [comment]
We should audit the icon views and throw away most of them. They are inconsistent and overloaded.
