### ISSUE TITLE
"Logged in users" visibility group with content accessibility set to "Unrestricted", when editing (or creating new) group content, should not propose "public" item in "access" dropdown menu

### ISSUE THREAD

**Issue by oseg** [Elgg/Elgg#10285]
Scenario:
- Logged in as an admin
- Group settings "Do you want to allow private (invisible) groups?" set to "yes"
- Create a group with the following options:
  . "Who can see this group?" set to "Logged in users"
  . "Accessibility of group content" set to "Unrestricted"
- Create a content (a bookmark for instance) in this group and set its "access" to "Public"
- Logged out and click on the "bookmarks" item in the menu
- A summary of the new bookmark is displayed in the bookmark list, click the bookmark title to access the detailed information bookmark page
  => "The content you were trying to view has been removed or you do not have permission to view it" error message is displayed

Issue reproduced on both elgg v1.12.12 and elgg v2.2.1

**Comment by mrclay** [comment]
Thanks for the detailed report!

**Comment by mrclay** [comment]
1.12 and 2.2: redirects home, with content error.
2.x: 403 error page with content error.

We've never been able to decide how to display item pages if we can't reveal the group it belongs to. In the owner block (where group/user usually displays) we *could* put something like "This item belongs to an undisclosed group. Logging in *may* reveal it."

**Comment by hypeJunction** [comment]
Strawman 3: run upgrade script and fix access levels. Fix the access input and add validators in can write to container

**Comment by mrclay** [comment]
> fix access levels

To be clear, you mean we make clear we don't support this scenario.

**Comment by hypeJunction** [comment]
Yes, I think we shouldn't let this scenario happen so we don't have to fix things like this

**Comment by mrclay** [comment]
Agreed. A plugin can enable this scenario and figure out what should happen. Core can't be that opinionated.
