### ISSUE TITLE
Fix image orientation by default

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10280]
Not sure if we should support this out of the box, but we can extend the image service:

``` php

    /**
     * Automatically rotates image file based on EXIF tags
     *
     * @param ElggFile $file File entity
     * @return void
     */
    public function autorotate(ElggFile $file) {

        $path = $file->getFilenameOnFilestore();
        $image = $this->imagine->open($path);

        $this->imagine->setMetadataReader(new ExifMetadataReader());

        $autorotate = new Autorotate();
        $autorotate->apply($image);

        $image->save();
    }
```

**Comment by hypeJunction** [comment]
@beck24 What's your experience with Imagine's autorate? Does it alter the Exif data after rotation? I think adding autoratation by default might be a source of grief and extra work. I think we should instead expose an instance of Imagine for public consumption and let plugins do stuff with it.

**Comment by mrclay** [comment]
Is this a simple some "sites will want it off, some on" thing? Like we could just add a setting?

**Comment by jdalsem** [comment]
it requires the exif php extension. We need to sniff if support is available
