### ISSUE TITLE
Users can set page owner via URL

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10293]
`default_page_owner_handler` allows URLs like `?owner_guid=<other_guid>` or `?username=mrclay` to set page owner, even if it could otherwise be determined from the URL.

This block would ideally come at the end: https://github.com/Elgg/Elgg/blob/2.2.1/engine/lib/pageowner.php#L115-L139

**Comment by mrclay** [comment]
Plugins that proactively set the page owner don't have this issue. Others do: https://elgg.org/bookmarks/view/2547417/elgg-at-a-crossroads-elggorg?owner_guid=382631

**Comment by mrclay** [comment]
Because plugins can have non-standard URLs, I don't think we can just move the `get_input()` sniffing to the end without breaking BC.

**Comment by jdalsem** [comment]
it is currently position after the route detection, but before a plugin... if we do not want this behaviour we could deprecate it in the future
