### ISSUE TITLE
Setting/determining page content is a mess

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10292]
Due to `default_page_owner_handler` plugins tend to rely on `elgg_get_page_owner_entity` to get the container object, but this can return invisible groups the user shouldn't see. So depending on if a plugin uses `elgg_get_page_owner_entity` or `$content->getContainerEntity()` the plugin may or may end up with a group entity. Mix that with the complexity in `elgg_group_gatekeeper` and we have a recipe for confusion between plugins and views and routes and things like #10285 are easy to pop up and hard to fix.

Strawman 1: In `default_page_owner_handler` capture both container_guid and owner_guid. If the page owner would normally be a group invisible to the user, then `elgg_get_page_owner_entity` and `_guid` will return the content owner, but `elgg_group_gatekeeper` will know to check the real group from the URL. If a plugin sets page owner directly, use BC behavior.

Strawman 2: Add a content service that can tell you various things about this route's content and its container, at least existence and visibility to the logged in user. This could be populated early from the URL using code from `default_page_owner_handler` and `Elgg\GroupItemVisibility`, then `default_page_owner_handler`, gatekeepers, and plugin code could use it or reset it as needed. But it would always offer a more complete picture and and views like `page/elements/owner_block` would not pull blindly from `elgg_get_page_owner_entity` and render groups that should be invisible.

**Comment by hypeJunction** [comment]
I am in favor of removing the setter and relying on the hook for all routes.

**Comment by jdalsem** [comment]
The suggested changes are outdated.
