### ISSUE TITLE
Add error pages as standalone resources

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10290]
Add common error codes as handled pages, so we can do e.g. `forward('404')`.

Refs #10273, #9476, #9796, #10369

**Comment by mrclay** [comment]
I think it's important to send appropriate HTTP codes.

Strawman 1: Leave as is (is it currently a problem?)
Strawman 2: Capture URL in session, send the error code with a tiny HTML file with both JS and meta redirects to the real error pages.

**Comment by mrclay** [comment]
Refs #9476, #9796

**Comment by hypeJunction** [comment]
Strawman 2 SGTM

**Comment by mrclay** [comment]
Make sure error routes are not allowed to redirect. Send the redirect response using as few services as possible to avoid secondary failures. E.g. `include` a script instead of elgg_view().

**Comment by mrclay** [comment]
I think this should go on the 3 milestone.

**Comment by jdalsem** [comment]
I believe this is done am i right? We have resource views for some error pages...

**Comment by mrclay** [comment]
Doesn't seem critical or worth holding up 3.0 for at least.

**Comment by jdalsem** [comment]
@hypeJunction with the ability to throw in resources... do we still need this?

**Comment by hypeJunction** [comment]
Probably not
