### ISSUE TITLE
Reworking the walledgarden pages

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10305]
I would like to rework the walledgarden pages... something like below.

![walledgarden](https://s11.postimg.org/f55xj5clf/walledgarden.png)

I started a discussion on elgg.org to get users to provide fanart for the background image:
https://elgg.org/discussion/view/2553331/looking-for-full-hd-fanart-of-elgg

Benefits of this rework would be:
 - easier branding by themes
 - better UX on smaller screens
 - reduce the fancy javascript for content replacement

**Comment by hypeJunction** [comment]
Looks a bit like the landing I did for: https://smile-connect.com/

**Comment by jdalsem** [comment]
or like i did for https://login.microsoftonline.com/ :)

**Comment by mrclay** [comment]
> It should be something with the elgg logo

More stuff sites have to remove (soft thumbs down). Would be nice if tracking down a plugin to remove our branding wasn't the first thing a site owner had to do.

**Comment by hypeJunction** [comment]
> Would be nice if tracking down a plugin to remove our branding wasn't the first thing a site owner had to do.

https://github.com/Elgg/Elgg/issues/10083#issuecomment-242320791

**Comment by mrclay** [comment]
Maybe we ask for art with and without logo or something with a good place to put it?

**Comment by hypeJunction** [comment]
We just use a gradient and let themes change the styles if they must.
