### ISSUE TITLE
2.2: Need to use is_link in _elgg_is_cache_symlinked()?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10302]
I get `readlink(): Invalid argument` when my symlink is set correctly. 😕

**Comment by hypeJunction** [comment]
`is_link()` doesn't work on all platforms.

**Comment by mrclay** [comment]
Do we actually need the `readlink()` call? If the link works, I'd think realpaths would be identical.

**Comment by hypeJunction** [comment]
I guess that's what `realpath()` is for: http://php.net/manual/en/function.realpath.php. We can drop the `readlink()`.

**Comment by jeabakker** [comment]
fixed in #10342
