### ISSUE TITLE
composer can't install 2.2.1

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10306]
I get the following error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - elgg/elgg 2.2.x-dev requires bower-asset/jquery-ui 1.11.* -> no matching package found.
    - elgg/elgg 2.2.1 requires bower-asset/jquery-ui 1.11.* -> no matching package found.
    - Installation request for elgg/elgg ~2.2.1 -> satisfiable by elgg/elgg[2.2.1, 2.2.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

https://github.com/Elgg/Elgg/blob/2.2/composer.json#L25

**Comment by iionly** [comment]
Hehehe, so I'm not the only one with this problem after all. See https://github.com/Elgg/Elgg/issues/10303.

**Comment by hypeJunction** [comment]
Delete your vendors first.

**Comment by jeabakker** [comment]
I think this is because of the '1.11.*' requirement for jquery-ui. I think this means 'any' of the 1.11.x versions if this is already installed as 1.11.2 than it won't update that.

better would have been '~1.11.0' which mean the last stable in 1.11 but NOT 1.12

**Comment by mrclay** [comment]
👍 for `"~1.11.0"` but why would composer block due to stuff in /vendor?

**Comment by jeabakker** [comment]
> Delete your vendors first.

works, thank you!

**Comment by jeabakker** [comment]
PR #10308

**Comment by hypeJunction** [comment]
> why would composer block due to stuff in /vendor?

I don't know, but that's the panacea for all the composer problems :)

**Comment by jeabakker** [comment]
i think this can be closed
