### ISSUE TITLE
CKeditor not always loaded (on Elgg community site at least)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10304]
Sometimes it works, sometimes it doesn't and then I only see a plaintext input field. Refreshing the page helps but this is not satisfying...

**Comment by jdalsem** [comment]
any js errors? if it is reproducable could you see if the ckeditor js files are being loaded?

**Comment by iionly** [comment]
Problem is that it always surprised me so far and I can't reproduce it. If it happens again I hope to think of checking the browser console and maybe there's some error logged.

It might be a timeout issue as I have the impression that the community site is loading a bit slower than normal recently.

**Comment by iionly** [comment]
The error message I found in the console is

"TypeError: c[a] is undefined in https://elgg.org/cache/1474508935/default/ckeditor.js:10:10495"

As the code is minified I don't know at which line the problem occurs exactly in the unminified code.

**Comment by mrclay** [comment]
I think there's a race condition. Normally the editor requests these JS views:
ckeditor/config.js
ckeditor/lang/en.js

But sometimes these are requested, which result in 403 errors:
elgg/config.js
elgg/lang/en.js

Does this give us any ideas? cc @hypeJunction

**Comment by mrclay** [comment]
OK, I think it's due to inlining the ckeditor module in elgg.js.

**Comment by mrclay** [comment]
See #10337
