### ISSUE TITLE
Bugs when mod/profile is off

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10300]
- profile form is registered
- user URL points to home page (profile URLs should maybe work for admins and just show the hover menu? otherwise no link)

Unsure if any views need to move to core.

**Comment by jdalsem** [comment]
> profile form is registered

what do you mean?

maybe we should have a core resource to view a user... with a simple elgg_view_entity().. could still be profile/username... profile plugin would just override all the views

Alternatively we should be able to have 'no' url on the profile icon, but that is bugged at the moment... https://github.com/Elgg/Elgg/issues/6627
