### ISSUE TITLE
members plugin should not be doing fancy hook for tabs and page handlers

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10313]
Better it be regular/normal filter menu manipulation and resource files per page....

**Comment by hypeJunction** [comment]
I have started some work on that here: https://github.com/Elgg/Elgg/pull/10191/commits/1c0b7f28c081f6e806a013c3462dd72d521e3aa5

**Comment by jdalsem** [comment]
just what i had in mind... closing this as you are already working on it

**Comment by hypeJunction** [comment]
I closed that pull request. @mrclay was looking for a plugin to try out the new layouts, perhpaps this is a match made in heaven.

**Comment by jdalsem** [comment]
guess so
