### ISSUE TITLE
Responsive grid

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10316]
Me wants a responsive grid. 

Options:
- http://susy.oddbird.net/
- http://flexboxgrid.com/
- [ ] Add grid row wrapper `.elgg-row`
- [ ] Rewrite `.elgg-column-` implementation
- [ ] Decide on device breakpoints and how we are going to implement responsiveness (`.elgg-small-$x`?)
- [ ] Mobile first?

**Comment by hypeJunction** [comment]
Is everyone comfortable with SCSS? I would be willing to rewrite our CSS to SCSS, so we don't have to copy paste all the time. We need to compose our CSS anyway - each component needs to get it's own CSS view.

**Comment by mrclay** [comment]
Re SCSS, will this work well across plugins and core? Would this be something triggered by simplecache compile it or will we need a build step for core? I guess we'd lose PHP to write CSS right?

**Comment by mrclay** [comment]
More options. Overwhelming choice:
- http://leejordan.github.io/reflex/docs/
- https://philipwalton.github.io/solved-by-flexbox/demos/grids/

**Comment by hypeJunction** [comment]
https://github.com/Heydon/fukol-grids

**Comment by beck24** [comment]
Re: SCSS - I've used this library (well the LESS version) in a recent theme - https://github.com/leafo/scssphp

Looks like this:

    $less = new lessc();
    echo $less->compile(elgg_view('css/less/theme.less));

So everything is still in views that can be overridden/extended.  The compiler is fine with standard css so plugins that provide that are fine.  Why not do something like this and just pipe all cacheable css through the compiler?

**Comment by hypeJunction** [comment]
Back in the day the PHP compiler wasn't very sophisticated, maybe it has improved.
The only reason I would want to have SCSS in core is to reduce the boilerplate with vendor prefixes. I would want to include compass/css3 helpers.

**Comment by beck24** [comment]
I haven't done anything too in-depth with it, mostly just for standardizing color/size variables and using the nesting syntax.  Even that is a huge gain though.

**Comment by hypeJunction** [comment]
Nesting is great until a point. I have overused it in the past, and now I avoid deep nests. 
Compiling on demand with simplecache disabled might be a hassle, but it would be easier than using compass/sass gems.

**Comment by beck24** [comment]
Yeah you can overdo anything I suppose.  That was my thought, configuring compass locally is a pain, but this is easy and requires no config for the next developer that wants to add rules.

**Comment by beck24** [comment]
btw I've spent a lot more time using https://github.com/leafo/lessphp in my theme and I love it.  Works great with the views system, caching, and has a great way of passing php variables into less variables, which can be made hookable, so switching background images that served with elgg_get_simplecache_url() could be possible with a simple hook...

**Comment by jdalsem** [comment]
Not using any preprocessor but i think http://the-echoplex.net/csscrush | https://github.com/peteboere/css-crush is also a good alternative. Also csscrush is MIT licensed which is more favorable for Elgg... I think the usage is nearly the same. Both pure php and share similar features... language is different though... Language of Crush is more like SASS https://gist.github.com/peteboere/8419143

CSS crush can probably be easier implemented in Elgg with composer support and simple integration in the same spot as the minify... css crush can also replace the current minify library...

Like i said, i have no personal experience... just looking at the differences in code and usage.

Best scenario would be to be able to add the preprocessor without the need to change any css files to be able to use it. (so no special .scss or .less files). I think both solutions can work this way. How did you implement lessphp into your theme (besides the special syntax in the css files)?

**Comment by beck24** [comment]
In php set up any variables that are dynamically generated/cache based

```
<?php
use lessc;
$colors = [
	'primary' => '#7dd85e',
	'secondary' => '#00e2e6',
	'highlight1' => '#ddff6f',
	'highlight2' => '#fbb040',
	'dark' => '#3a3a3a',
	'light' => '#ffffff',
	'grey' => '#b3b3b3',
	'light-grey' => '#717171'
];
//http://leafo.net/lessphp/docs/
$less = new lessc();
$less->setImportDir(PLUGIN_DIR . '/views/default/css/less/');

// note variables could be hookable here in php before being passed to the less compiler
$less->setVariables([
	
	// images
	'stripe_img_url' => 'url("' . elgg_get_simplecache_url('theme/graphics/style/stripe.png') . '")',
	
	// fonts
	'Myriad_src' => 'url("' . elgg_get_simplecache_url('theme/graphics/fonts/MyriadPro-Regular.otf') . '")',
	
	// colors
	'primary' => $colors['primary'],
	'secondary' => $colors['secondary'],
	'highlight1' => $colors['highlight1'],
	'highlight2' => $colors['highlight2'],
	'dark' => $colors['dark'],
	'light' => $colors['light'],
	'grey' => $colors['grey'],
	'light-grey' => $colors['light-grey']
]);
echo $less->compile(elgg_view('css/less/elgg.less'));
```

And elgg.less:
```
@import "fonts.less";
@import "pdf.less";

body {
    font-family: @Myriad_src;
    font-size: 2rem;
    line-height: 2rem;
}
.elgg-page-header {
    background-color: @primary;
    padding: 0;
    margin: 0;
    
    h1 {
        background-color: @primary;
        font-size: 2em;
        margin: 0;
        padding-top: 8px;
    }

etc...
```

Note that @import works exactly how you'd expect so less files can be broken up into components.
This is MIT also (well dual, which I think means we can choose to accept it as MIT if we wish?)

I haven't heard of csscrush before, but it looks nice also.  Any idea if it's popular?  I'm familiar with less and sass, and I know they're in popular use in a lot of js frameworks.  If there's a clear winner for support and usage I vote we go with whatever might be most familiar to people.
