### ISSUE TITLE
Make admin menu more like gear popup

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10326]
Being able to see most options really helps me. I have some ideas.

**Comment by hypeJunction** [comment]
I like Joomla with respect to navigation. It would be great if our page menus were just submenus of site menu items. Having a full sitemap would make many things possible.

**Comment by jdalsem** [comment]
Closing this for now. I do not see it how having the full menu open all the time would help me on the admin page. Maybe having it as a dashboard/landing page could make sense but not for all pages. If you have a more defined idea, or a screenshot you wish to discuss let us know.
