### ISSUE TITLE
don't display owner block on all /activity page

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10320]

**Comment by iionly** [comment]
I would have a few more candidates for pages where the owner block seems to make no sense to me. Would it make sense to list them all here or do you want to keep this issue about the activity page only?

**Comment by hypeJunction** [comment]
Yes, list them here. There is page rework coming up

**Comment by iionly** [comment]
- messages pages,
- site notifications,
- user settings / notification settings,
- friends pages.

Messages, site notification and settings pages are private, so I don't see much need of displaying the owner block there as each user would only see their own version of these pages. An admin could view these pages of other users also, so it might make sense to display a reduced version of the owner block, i.e. only the header but not the menu (plus maybe any extended views added to the owner block). But the full owner block is kind of annoying on these pages in any case as the specific menu entries shown on these pages are below the owner block, so you might have to scroll down to reach them.

Friends page of other users is accessible for normal users, too. But maybe the owner block should be displayed only when viewing the friends pages of other users (and again maybe only the header of the owner block on your own friends pages).

**Comment by jdalsem** [comment]
is the owner block also relevant on the /all pages for content? Like file/all or blog/all??

**Comment by mrclay** [comment]
foo/all pages should not get it in 3.0. 2.x could be seen as a BC break. Dunno.

**Comment by hypeJunction** [comment]
Leave 2.x alone
