### ISSUE TITLE
add ability to define default plugin settings values in elgg-config.php

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10349]

**Comment by hypeJunction** [comment]
Might be complicated with boot cache, but worth a try

**Comment by jdalsem** [comment]
is meant as a fallback mechanisme... so elgg_get_plugin_setting would first use db/cache and if not set would look in the plugin-config file...

This way you do not have to think about default value logic in your views... `` $setting !== 'no'`` vs ``$setting == 'yes'``

**Comment by mrclay** [comment]
Cool. The boot cache shouldn't mix the defaults, just store those defaults with the system cache. Definitely should not include elgg-plugin.php on every request.

**Comment by jdalsem** [comment]
> Definitely should not include elgg-plugin.php on every request.

if we move more stuff towards the config file this will become more the case... or do you think we should move the config file into the cache?

**Comment by mrclay** [comment]
Should the plugin API somehow expose whether the default was used?

**Comment by jdalsem** [comment]
> Should the plugin API somehow expose whether the default was used?

don't see the need... and hard to expose
