### ISSUE TITLE
Private group settings

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10346]
Idea: add an interface similar to plugin and user settings for groups. Plugins can then just simply add their additional settings (we render two tabs on the edit page: Edit profile, Edit settings). Group tools can then be migrated to use private settings.

**Comment by jdalsem** [comment]
with group tools we add a lot of extra settings to groups... not only group tools.... i think the settings is a good idea, but not for the group tools... i think that even deserves its own section... so profile, tools, settings...

**Comment by hypeJunction** [comment]
I think the problem is we abuse group tools because there is no other easy way to configure groups. 
For instance, I have recently added a group tool for invites, which really should be a group a setting: 
`Allow group members to invite new members?`

**Comment by jdalsem** [comment]
agreed... so your setting should go to the settings section... the group tools could be their own section

**Comment by hypeJunction** [comment]
We currently maintain special API for group tools in core with convoluted metadata approach. Migrating tools to settings, IMO, would make things easier: 

```php
$group->blog_enable;
// vs
elgg_get_plugin_group_setting('enable_blog', $group->guid, 'blog');
elgg_get_plugin_group_setting('admin_only_blog', $group->guid, 'blog');
```

**Comment by jdalsem** [comment]
I would suggest to separate tools and plugin settings.... storage could still be settings instead of metadata..

With https://github.com/Elgg/Elgg/issues/10044 you would have a central way of setting/getting tool behaviour.

Presentation of tools vs settings should be different imho
