### ISSUE TITLE
always show configured dataroot path, even if configured in settings.php

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10350]
On the admin page (/admin/settings/advanced) we show if the dataroot path comes from the settings.php file but we don't show the configured value.

this should be added just to make sure some systemadmin didn't make a mistake

**Comment by mrclay** [comment]
👍  also show a warning if it's not writable.

**Comment by jeabakker** [comment]
I don't know why i logged this as it has been shown since d4b28c284b158419b35502cba8f3d572d2c2c6ba with a notice that it came from `settings.php`
