### ISSUE TITLE
Incomplete changelogs

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10356]
It seems the changelogs of 1.12.13 and 2.2.2 don't list all changes. But the issue might be there since a while because the changelog of 2.2.1 seems incomplete, too (checking everything manually is a bit much though...).

Missing in changelog of 1.12.13:
- security(htmlawed): upgrades htmLawed to latest, currently 1.1.22 (https://github.com/Elgg/Elgg/commit/7f808d68354ec1899d94300cf099d95154a71ca4)
- security(forms): passwords no longer stored with sticky form data (https://github.com/Elgg/Elgg/commit/9cb1b38aba7c6a07586692b809ae33ee733ac468)
- fix(js): output deprecation messages to admins in browser console only (https://github.com/Elgg/Elgg/commit/a8052f9cd5e2cbc120a6d5b7b3664049d569011e)
- fix(members): Don't rely on newest members tab set as default tab in pagehandler for members page (https://github.com/Elgg/Elgg/commit/a78aa354ffa79f9f8fb90ad8aa3cccdf4554b034)
- fix(pages): operations keep track of more than 10 child pages (https://github.com/Elgg/Elgg/commit/bc5f414bf597fe440ca096333fafea330746a323)
- docs(license): clarifies dual licensing in LICENSE.txt (https://github.com/Elgg/Elgg/commit/1db4994f8bab11898153c4c9e6e2898c0549714f)

Missing in changelog of 2.2.2:
- security(forms): passwords no longer stored with sticky form data (https://github.com/Elgg/Elgg/commit/9cb1b38aba7c6a07586692b809ae33ee733ac468)
- fix(core): page owner entity only returns users/groups user can see (https://github.com/Elgg/Elgg/commit/0d33310031024aa8940f9d3bbe5cdd80f2a4da57)
- fix(profile): use correct default access for profile fields (https://github.com/Elgg/Elgg/commit/63a01b6f8c9314ddae5819e8194938c988871a60)
- fix(notifications): only prefetch subscribers for ElggEntities (https://github.com/Elgg/Elgg/commit/65be05c567692694e052ae4711450b7c19f2d571)

**Comment by jdalsem** [comment]
This was probably caused by an incorrect resolve of a merge conflict. Thanks for finding this, but the changelog will not be updated as we are looking into changing how release notes work in the future.

**Comment by ernestbuffington** [comment]
np
