### ISSUE TITLE
FR: add input/grouppicker and input/objectpicker

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10360]
in various plugins we have group and object pickers... autocompletes (copies of input/userpicker) that almost do the same... we should rework these so autocomplete in core also can handle objects and groups

**Comment by jdalsem** [comment]
related to #4679

**Comment by hypeJunction** [comment]
We need to allow autocomplete to take a custom callback, e.g. search for users that not a member of the current group.

**Comment by jdalsem** [comment]
yep... will add that to the PR

**Comment by hypeJunction** [comment]
But be sure to sign the request if the callback is provided client side. We don't want people modifying callback function. You can check what I did in tokeninput. Alternatively, we should just add a callback register.

**Comment by hypeJunction** [comment]
Do you still want this? I think between all the search changes, this has become redundant

**Comment by jeabakker** [comment]
maybe not as independent view, but as a generic input/entity_picker

**Comment by jeabakker** [comment]
now we have a very nice userpicker but nothing for the other types, so maybe combine it all in a very nice entitypicker?

**Comment by hypeJunction** [comment]
`input/autocomplete` with `match_on=groups`

**Comment by jdalsem** [comment]
problem is input/autocomplete is not usable if you want to be able to present something different from the submitted value... input/autocomplete also does not support multiple values

**Comment by jdalsem** [comment]
userpicker has all the nice features we want for all entity types... only it is called the UserPicker and it has some user specific features like the friends_only checkbox

**Comment by hypeJunction** [comment]
Either way doesn't need to delay 3.0

**Comment by jdalsem** [comment]
moving it out of beta milestone, but wishfull thinking it can be done during beta :)
