### ISSUE TITLE
2.x walled garden behaviour incorrect

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10369]
in 2.x the response API prevent a forward to home in walledgarden modus (as it is a 403 status code). This will expose non walledgarden page layouts... not wanting that... should we remove the 403 status code handling for walled garden?

**Comment by jdalsem** [comment]
cc @hypeJunction

**Comment by mrclay** [comment]
Yes, walled garden should 307 redirect.

**Comment by hypeJunction** [comment]
I will need to look back and see. I don't want to be changing HTTP response code to some meaningless phrases a-la `walled_garden`. We should look for an appropriate place to hook into the views system and tell it when to you walled_garden layout.
What exactly is leaking?

**Comment by jdalsem** [comment]
Non walled garden layout is leaking... Current behaviour is redirect to
home if not allowed by walled garden. New behaviour is 403 response and you
stay on the page without redirect

Op 5 okt. 2016 4:08 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:

**Comment by hypeJunction** [comment]
Doesn't seem like a critical issue to me. I am not sure if using default shell is "leaking".
I want to be able to use default layout even when in walled garden mode, so we can't just enforce walled garden layout. I have use cases when the site is behind walled garden, but there are certain group and other pages that should be viewable.
I won't have time this week to fix this.

**Comment by jdalsem** [comment]
i am not talking about forcing a layout... that is up to the pages that are exluded from the walled garden rules.. but the main concern is that there is no longer a redirect if the page is behind the walled garden... i think that is the purpose of the walled garden. Changing that behaviour is not something i expect.

**Comment by hypeJunction** [comment]
Needs to be fixed as part of https://github.com/Elgg/Elgg/issues/10290

**Comment by mrclay** [comment]
PR #10376
