### ISSUE TITLE
Plugins page too resource intensive

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10367]
I have an Elgg installation with about 100 plugins with only bundled plugins enabled at this time. It takes 561 DB queries to render the page on 2.2 - don't see the exact queries because DB Info logger doesn't spit out the query parameters, but it seems:
1. We query the database to see if a plugin is active for each plugin - we should just add another select to `\Elgg\Plugins::find()` and store the active status. In 3.0, get rid of the relationship and make it a private setting or metadata
2. It needlessly reindexes plugin priorities and saves them to the database individually
3. There is something fishy with plugins settings - I thought we refactored the code to get all plugin settings on first request, but it looks like they are being pulled individually

**Comment by hypeJunction** [comment]
I have looked into trying to refactor some of the queries, but it's a dark forest with many scary monsters in there.

Strawman for 3.0: add a new database table to store plugin status and priority, so that we can quickly fetch and cache this information. Optimize ege* queries to use cached guid values instead of joining tables. Do not query the database to get active status or priority.

**Comment by jdalsem** [comment]
#11068 fixed a bunch. It could be improved some more, but not worth the trouble for now
