### ISSUE TITLE
Incorrect return in ElggRelationship::save() 

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10373]
ID is expected and bool is returned

**Comment by jdalsem** [comment]
Maybe we should remove the feature like @mrclay suggested in https://github.com/Elgg/Elgg/issues/5990

**Comment by hypeJunction** [comment]
Fine by me. But it would make sense for `add_entity_relationship()` to return an id.

**Comment by jdalsem** [comment]
Probably a dupe of https://github.com/Elgg/Elgg/issues/9019 then

**Comment by mrclay** [comment]
Different issue. #9019 is about incorrect usage, this is wrong return type.

**Comment by mrclay** [comment]
This was [broken in 1.0](https://github.com/Elgg/Elgg/commit/27009477e3f523721eacc784598a616bf438d772#diff-d20fcab6fe4581cb1ca5650eceb8cdcdL326). I suggest we just fix the phpdocs in 1.12 and fix in master.

**Comment by mrclay** [comment]
On 2nd thought, this is a real issue for the internals of `ElggRelationship::save`

**Comment by hypeJunction** [comment]
I think out API and tests assume that all ::save methods return an id on success.

**Comment by mrclay** [comment]
PR #10375
