### ISSUE TITLE
Why do we need page owner?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10372]
The page owner business causes more issues than it solves. What are the use cases for keeping it around? Just to magically render an owner block? Let's put together a list of use cases and find alternatives. I want to kill page owner and all the spaghetti that comes with it.

**Comment by mrclay** [comment]
I've used it to decorate "group" pages, add banner/CSS. I think we just get rid of the auto URL/REQUEST sniffing. Group gatekeeping is the biggest use.

**Comment by jdalsem** [comment]
we are going to live with page owner for now
