### ISSUE TITLE
composer script from starter project

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10374]
i was just wondering if the composer install/update scripts from the starterproject need to be in the starterproject or that the should be in elgg/elgg..

any reason why not?

**Comment by mrclay** [comment]
Good point, they probably could live in starter-project.

**Comment by jdalsem** [comment]
I actually thought the script calls should go to the elgg repo and not be
in the starter project

Op 6 okt. 2016 7:10 p.m. schreef "Steve Clay" <notifications@github.com>:

**Comment by mrclay** [comment]
If installed as a dependency the scripts would still run?

**Comment by jdalsem** [comment]
that is also what i am wondering... i would think/hope so... going to test it, so i will let you know

**Comment by hypeJunction** [comment]
You would want the post install script to run after all dependencies have been resolved, so it would make sense to keep the scripts in starter-project.

**Comment by jdalsem** [comment]
uh... isn't post install triggered after all is installed?

**Comment by hypeJunction** [comment]
I am not sure to be honest, it could be that it's runs after a single dependency is installed...

**Comment by jeabakker** [comment]
According to the docs of Composer scripts from dependencies aren't executed.
see: https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-

I tested this and it's true :(

**Comment by jdalsem** [comment]
So no changes needed

**Comment by hypeJunction** [comment]
We could still move the post install classes into the starter-project.

**Comment by jdalsem** [comment]
bad plan... as other people not forking the starter-project will have to copy those scripts to their own repos...

**Comment by hypeJunction** [comment]
Good point. Let it stay the way it is. Less work for us.
