### ISSUE TITLE
->guid or ->getGUID()

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10386]
what to use? some prefer a function... others an attribute/property... both serve their own purpose, but sometimes i see PR's which also change existing usage of one of the options to the other (without a specific reason in the PR). 

Should we drop getGUID() if `->guid` is the preferred?

Just a thing that bugs me... @ coldtrick we also disagree with eachother on the preferred usage

**Comment by hypeJunction** [comment]
I don't like the look of 4 capital letters in a row with brackets followings :) Plus there is always a fatal hiding somewhere there.

**Comment by beck24** [comment]
I prefer ```->guid```, less typing and the reasons IK said

**Comment by mrclay** [comment]
I also `->guid` now, in addition to the previous reasons, it's 1 less function call. I'd say soft deprecate the method versions, but don't worry about updating code. Just not worth the effort IMO.

**Comment by mrclay** [comment]
Methods are probably easier to mock, but Ismayil has taken care of that well enough.

**Comment by jdalsem** [comment]
Conclusion: ``->guid`` is the preferred way

**Comment by hypeJunction** [comment]
@brettp
