### ISSUE TITLE
ignore access as part of elgg_get_entities

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10401]
we added a helper flag to ignore access in get_entity... should we do the same in elgg_get_entities? There are a lot of usecases where we ignore access to fetch entities...

**Comment by hypeJunction** [comment]
We didn't add it. Need to figure out a way to do it. I think ``elgg_ignoring_access()`` is the way to go.

**Comment by jdalsem** [comment]
hmm... where did i see the ignore for access then... i believe you added it for fetching users... let me find it

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/pull/10379 here it is... not added yet.. but part of a PR

**Comment by jdalsem** [comment]
i see this pattern a lot:
```php
$old_ia = elgg_set_ignore_access(true);
$entities = elgg_get_entities($params);
elgg_set_ignore_access($old_ia);
```
would be nice to be able to do

```php
$entities = elgg_get_entities(['ignore_access' => true]);
```

**Comment by jdalsem** [comment]
Closing this. It works (for some usecases) but for others you still need the 'old' pattern of ignoring access. To prevent confusion on how it works, we better stick with one approach.
