### ISSUE TITLE
blog archive sidebar view should be a bit fancier

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10418]
Years should collapse... if you have a 5 year archive you now have a long list of 5 * 12 months items...
Maybe structure could be

- 2016 (current year)
 - september
 - august
 - january
- 2015
- 2014
- 2013

only current year (or latest year in the list) is expanded

**Comment by mrclay** [comment]
Put all the current logic in one view and let plugins come up with ideas. You'll never get a consensus on this.

**Comment by mrclay** [comment]
I'm fine with you improving what's there if it's worth your time.
