### ISSUE TITLE
rework listing of profile fields in group and profile details

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10412]
should reuse css or use generic styled elements like elgg-list

**Comment by hypeJunction** [comment]
I have been experimenting with profile views for my theme project and decided to use the default layout with the sidebar that holds user hover/group page menus. Keeling profile fields as a single block on top of 2 colimn wisget layout. Basically the same thing we have in groups. Looks clean and simplifies the widget layout
