### ISSUE TITLE
output longtext has double parsed urls

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10428]
when i write a blog and add in plain text an url (eg ```http://youtube.com```) this works as expected i get ```<a href='http://youtube.com'>http://youtbube.com</a>```

but if i add a link with ckeditor (so i add ```<a href='http://youtube.com'>http://youtbube.com</a>```) i get the following output ```<a href='http://youtube.com'></a><a href='http://youtube.com'>http://youtbube.com</a>```
This won't show to the user as there is no text in the fist link. But our plugin target_blank adds an icon before all external links and so i see 2 icons, when i only expected 1.

**Comment by hypeJunction** [comment]
Dupe #8490

**Comment by jeabakker** [comment]
man that was fast, the search didn't find it ;)

**Comment by hypeJunction** [comment]
:) I knew the right keywords
