### ISSUE TITLE
Tell devs all functions in /mod are private

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10438]
Unless specifically marked `@api`. This eliminates the need to prefix with underscores, mark them private, etc.

**Comment by jdalsem** [comment]
hard to do... 3rd party plugins overriding views that use internal (private) functions... will be easily broken because they depend on those functions

**Comment by mrclay** [comment]
Then we should also advise plugins around plugin function calls in views:

- Add warnings to views that use them ("don't override this view")
- Wrap usages in `if (is_callable())` checks just in case
- Move function calls outside views, or call it within the view_vars hook

**Comment by jdalsem** [comment]
just mark them private is enough for me now.
