### ISSUE TITLE
Improve discussion listing

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10436]
- Missing excerpt of the last comment (should display like the river with up to N latest comments below each)
- Missing button to add topic (should steal from elgg.org, make sure the autocompleted groups have discussions active)
- A tab to display the latest N topics _in each of your groups_ might be useful.
- Can we learn anything from https://try.discourse.org/ ?

See also: #5661, #10220, https://github.com/Elgg/www.elgg.org/issues/62

**Comment by jdalsem** [comment]
> Missing excerpt of the last comment (should display like the river with up to N latest comments below each)

not going to add this



> Missing button to add topic (should steal from elgg.org, make sure the autocompleted groups have discussions active)

Not going to add this. Global discussions will add an 'add (global) topic' button. Content add/edit form with container selection is something that we might add in the future, but that is not specific for discussions.




> A tab to display the latest N topics _in each of your groups_ might be useful.

will be added... PR underway



> Can we learn anything from https://try.discourse.org/ ?

probably, but not going to do anything specific at the moment that this ticket is required to keep open.
