### ISSUE TITLE
Move away from RST and Readthedocs

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10446]
This was suggested in conversations before but there is no master ticket. Idea was to move away from RST/ReadTheDocs and use MD / GitHub for the documentation.

Why?
- RST is harder to write then MD
- ReadTheDocs has advertisement
- ReadTheDocs has some bugs (could be caused by our own code)
- If maintained on Github, it is probably kept better up to date because other people can contribute easier

**Comment by juho-jaakkola** [comment]
@feroda you mentioned something about possibility for Sphinx to use Markdown instead of RST. Can you elaborate what you had in mind?

BTW, I found some arguments against Markdown: http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/

**Comment by jdalsem** [comment]
Did some extra research. I think we could move to Github Pages (not wiki). The documentation will then reside in the repo folder /docs

We need to select a Jekyll (http://jekyllrb.com/) theme for the documentation site

learn.elgg.org can be redirected to the elgg.github.io/elgg location

For Elgg 3.0 we need to decide what to do with our documentation. I18N is a big concern. At this moment translations are incomplete and very out of date. I think we should focus on English only and choose to drop all translations. Jekyll has support for i18n so if we want to add it later on we can.

We need to redesign the documentation structure for 3.0 with all the new features and get rid of the legacy information in the documentation.

@Elgg/core opinions?

**Comment by jdalsem** [comment]
we can even support RST in Jekyll https://github.com/xdissent/jekyll-rst... could make transition a lot easier

**Comment by mrclay** [comment]
All that sounds reasonable. Can it host multiple branches? Not a dealbreaker.

**Comment by jdalsem** [comment]
i believe you can have multiple versions/branches of your docs

**Comment by jdalsem** [comment]
Currently sticking with RTD
