### ISSUE TITLE
scan core for usage of lightbox

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10443]
AFAIK lightbox js and css is inlined... not need for elgg_require_js('lightbox'), elgg_load_js('lightbox') and elgg_load_css('lightbox') anymore

**Comment by mrclay** [comment]
> lightbox js and css is inlined

I remember removing a lot of stuff from elgg.js in master.

**Comment by jdalsem** [comment]
just ran into a situation in master... this issue just a reminder to do a full sweep
