### ISSUE TITLE
ElggEntity->getIconURL() is session bound, why?

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10440]
What was the reasoning behind making all the entity icon urls session bound?

This means that every icon url is unique per user/session, so caching servers have no useful way of caching the entity icons. This increases the load on the webserver.

Yes the serve-file doesn't boot core and is fast, but caching servers are faster ;)

@Elgg/core feedback please

**Comment by hypeJunction** [comment]
There is an exception for user icons. Basically, we don't want to leak access controlled entity icons (e.g. file thumbnails). I can't remember of hand, but I think we are updating file timestamp on access change, so the URL won't validate afterwards. I think core should stick to session binding, but plugins have the discretion to not use the binding.

**Comment by jeabakker** [comment]
> There is an exception for user icons.

are you sure, just tried on my 2.2 installation. Same icon loaded with 2 different users and i got 2 different URLs

**Comment by hypeJunction** [comment]
Doesn't use cookie if walled garden is disabled, just checked the code.

**Comment by jeabakker** [comment]
> Doesn't use cookie if walled garden is disabled, just checked the code.

https://github.com/Elgg/Elgg/blob/2.x/engine/lib/users.php#L506

**Comment by mrclay** [comment]
> plugins have the discretion to not use the binding

Meaning override the hook with same logic but `$use_cookie = false;`.

**Comment by jdalsem** [comment]
we probably should document the default behaviour of getIconURL here: learn.elgg.org/en/stable/guides/file-system.html and then we can close this ticket

**Comment by hypeJunction** [comment]
It should be in inline docs.
RST has started adding advertising... We should consider migrating our docs to MD and using Github's Jekyll instead.

**Comment by hypeJunction** [comment]
http://pandoc.org/ - can be used to migrate from RST to MD, and then we can generate MD docs from PHPDoc

**Comment by jdalsem** [comment]
Create a ticket for moving away from RST https://github.com/Elgg/Elgg/issues/10446

**Comment by jeabakker** [comment]
we recently upgraded a client to 2.2 and since then the number of requests to the webserver have doubled. This is because the images are no longer cached by the caching server.

**Comment by hypeJunction** [comment]
They should be cached by the browser.

**Comment by jeabakker** [comment]
> They should be cached by the browser.

for the current session, yes. But close the browser and try again => new session = new icon urls = new request to server

**Comment by hypeJunction** [comment]
I manually delete the cookie and I get 304 headers. Are you using stock installation?

**Comment by hypeJunction** [comment]
We have quite extensive test coverage, so I am confident that the issues is on your end - audit your hooks.

**Comment by jeabakker** [comment]
> I manually delete the cookie and I get 304 headers. Are you using stock installation?

those headers come from the server, so there was a request.

Also which icons did you check? For users they are session bound in walled garden only, is your site in walled garden?

**Comment by hypeJunction** [comment]
They are session bound in a walled garden mode. I don't understand your problem.  Do you want them not bound in a walled garden?

**Comment by hypeJunction** [comment]
Both Steve and I are in agreement that all icons should be served session bound by default for all entities.  If you want to save bandwidth, register your own hook and replace with non-session bound icons

**Comment by jdalsem** [comment]
this discussion is not about who is right... as icons linked to content that is bound by access should be limited.. (there is however some optimization possible)... this discussion is only to point out this change increases server load... it is hard to bypass this with a hook (as custom behaviour is hard to correct)... maybe a (security) setting (maybe on #10494) could help improve... if you want cacheability over security

**Comment by hypeJunction** [comment]
It takes 3 lines of code and is going to leak a lot of data. I'd rather devs decide where they want this, and write their own hooks.

```php
elgg_register_plugin_hook_handler('entity:icon:url', 'all', function($hook, $type, $return, $params) {
   $entity = elgg_extract('entity', $params);
   $size = elgg_extract('size', $params, 'medium');
   if ($icon = $entity->getIcon($size)) {
     return elgg_get_inline_url($icon, false);
   }
});
```

**Comment by jdalsem** [comment]
that is too aggressive... i would rather like to influence default behaviour

**Comment by jdalsem** [comment]
Simple usecase where the current situation is causing issues:
- walled garden site
- all content behind the wall is considered 'public' (for all logged in users)

This is a relative common situation. Firewalls (or other gatekeepers) could be used to prevent leaking outside of walledgarden.

**Comment by hypeJunction** [comment]
One option would be to add an alias `wg-serve-file` or similar and update the API to check logged in/wg status when returning the URL. But, meh, too much work.

**Comment by mrclay** [comment]
This [Quora post](https://www.quora.com/Are-Facebook-pictures-really-private-and-are-they-hosted-on-Facebook-servers) and the 1st answer are useful here. I read a more in-depth post from Facebook people on this topic a few years back but I can't find it. Their model seems to be: **unguessable is sufficient security**.

**Comment by mrclay** [comment]
Perhaps we *are* being too paranoid by default. A simple core setting to disable cookie binding in several cases seems reasonable ("Don't bind 'secret URLs' to sessions (improves cache/CDN performance)").

**Comment by hypeJunction** [comment]
In that case we could just apoend user token to non session bound URLs

**Comment by mrclay** [comment]
user token?

**Comment by mrclay** [comment]
The case we're worried about: A photo file visible only by friends. Your friend logs in, so we give her a MAC-secured URL to the file. That URL doesn't need anything related to her session. If she's going to betray your privacy, she can trivially copy the image. Our cookie-binding can do nothing to stop that.

**Comment by mrclay** [comment]
The expiration option is the way to handle other cases, like very large file downloads that would become a performance issue if the URL were shared.

**Comment by hypeJunction** [comment]
I think one of the problems that @jeabakker is talking about is that because of WG we loose the ability of caching images for all of the logged in users. So, we could just append a user token to user icons when in WG, and filter out direct requests to serve file handler.

**Comment by mrclay** [comment]
Why not just revert 4c8a7ced7ec56637dd836f2854df9f276893b876?

**Comment by hypeJunction** [comment]
Because https://github.com/Elgg/Elgg/issues/9518.

**Comment by mrclay** [comment]
Then we don't do this: https://github.com/Elgg/Elgg/blob/2.2/mod/profile/icondirect.php#L31

**Comment by mrclay** [comment]
We go back to the bad old code I guess.

**Comment by mrclay** [comment]
icondirect is only there for legacy code, right? Stock 2.2 sites don't use it?

**Comment by jdalsem** [comment]
i think current code is good... some like the security it offers. We only need a feature to control default behaviour or disable session bound icons at all

**Comment by hypeJunction** [comment]
We can just sign all serve file URLs with HMAC key so they are not guessable.

**Comment by hypeJunction** [comment]
I'd like to have acccess to icons even in walled garden mode, i.e. to include them in notifications or use in oembed.

**Comment by mrclay** [comment]
See #10503

**Comment by mrclay** [comment]
> sign all serve file URLs with HMAC key so they are not guessable

Don't we already do this by default in 2.2?
