### ISSUE TITLE
Check for context specific widget views

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10447]
Check if e.g. widgets/blogs/profile/content exists before using default. Will help reduce boilerplate and make it easier to configure widgets based on context. Currently I am never sure if I should use the page owner, widget owner or something else as listing target

**Comment by jdalsem** [comment]
personally i think it is overkill... widgets should not try to use egg_in_context or elgg_get_page_owner... the widget object has all the info you need... $widget->context or $widget->owner_guid... having various widgets developed i see no big benefit in splitting these views...
