### ISSUE TITLE
Mobile: Need more whitespace in entity lists

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10457]
So many tap targets so little space:

![img_2496](https://cloud.githubusercontent.com/assets/170687/19417616/7e8d9d2e-937f-11e6-9666-609674639220.PNG)

**Comment by hypeJunction** [comment]
Need to loose the entity menu :)

**Comment by jdalsem** [comment]
New entity menu is helping a bit.. This deserves attention, but not as a separate ticket
