### ISSUE TITLE
Checkbox input is broken... again

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10458]
Could we please check the theme sandbox before merging any field/input related changes. I am quite done with fixing the checkbox label.

**Comment by hypeJunction** [comment]
We need to make it BC with `elgg_view_input()`

**Comment by hypeJunction** [comment]
`elgg_view_field()` should be fully BC with `elgg_view_input()`, that includes the use of the `required` parameter. Label should be rendered in `elgg_view_field()` and passed on to the `elgg_view('input/checkbox')`. Check if `label` is set first, if not use `#label`, wrap it, then render input.

**Comment by hypeJunction** [comment]
![checkbox](https://cloud.githubusercontent.com/assets/1202761/19725298/12e26326-9b85-11e6-8dc7-22137e0a1e3e.png)

**Comment by jdalsem** [comment]
strange... the PR fixed this issue... i will look where this went wrong (again)

**Comment by jdalsem** [comment]
Found it...

admin css adds:
```css
.elgg-field-label {
    display: block;
}
```
causing checkboxes to always appear on a new line...

this is not present in the theme sandbox (that shows as expected IMO)

**Comment by jdalsem** [comment]
we might be using the checkboxes incorrectly in the update_advanced settings form (i think this is the main cause)!

**Comment by jdalsem** [comment]
The form uses:
```php
$body = elgg_view_field([
	'#type' => 'checkbox',
	'#label' => elgg_echo('installation:registration:label'),
	'#help' => elgg_echo('installation:registration:description'),
	'name' => 'allow_registration',
	'checked' => (bool)elgg_get_config('allow_registration'),
]);
```

it should be
```php
$body = elgg_view_field([
	'#type' => 'checkbox',
	'label' => elgg_echo('installation:registration:label'),
	'#help' => elgg_echo('installation:registration:description'),
	'name' => 'allow_registration',
	'checked' => (bool)elgg_get_config('allow_registration'),
]);
```
so no `#label`

**Comment by hypeJunction** [comment]
To stay BC it should has to support both.

**Comment by jdalsem** [comment]
why? 2.2 does not contain `elgg_view_field`..

passing `label` in `elgg_view_input` works as expected (Fully BC).. see the theme sandbox...

we only need to update the usage of the fields in these forms here

**Comment by hypeJunction** [comment]
I don't know what the correct behavior anymore... Whatever is fine by me.

**Comment by jdalsem** [comment]
`#label` is for a label above the checkbox... (just like any other field)
`label` is for a label next to the checkbox

i will update the form usage

**Comment by hypeJunction** [comment]
still a bugger
![bugger](https://cloud.githubusercontent.com/assets/1202761/20091370/7d80752e-a5a3-11e6-97d1-ba6cec801fce.png)
