### ISSUE TITLE
if multisite is removed should we still keep member_of_site relationship?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10473]

**Comment by hypeJunction** [comment]
I am for dropping.

**Comment by jdalsem** [comment]
I am not specifically pro or con, but usage of the relationship could differ from the existence of the user entity by itself... what if you create account, but do not create the relationship... those people will not be 'member of site'...

the relationship feature was added in https://github.com/Elgg/Elgg/issues/804, but is probably never been working as intended... see https://github.com/Elgg/Elgg/issues/6156
