### ISSUE TITLE
Remove support for subtype-less entities

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10476]
We have created so much boilerplate around normalizing user and group subtypes. How about we require subtype to be set on all entities. Upgrade user to user:user and admins to user:admin. Group to group:group.

**Comment by mrclay** [comment]
Save a new user, what does getSubtype() return? Empty string? Make that the default.

**Comment by mrclay** [comment]
or "default" would allow our APIs to use `""` to specify "any subtype." So many dragons here.

**Comment by hypeJunction** [comment]
That's why I say add a subtype and disallow empty subtypes. That would solve a bunch of issues in ege with pairs, etc. I would go as far as saying subtypes must be unique across all types. We can then nornalize out type subtupe strings do elgg_echo ('entity:blog'). Clean up all the URL slugs etc.

**Comment by jdalsem** [comment]
i think this makes a lot of sense... and should not be very hard to do...

**Comment by jdalsem** [comment]
ref #8943

**Comment by jdalsem** [comment]
refs https://github.com/Elgg/Elgg/issues/8571

**Comment by jdalsem** [comment]
could also fix https://github.com/Elgg/Elgg/issues/7843

**Comment by jdalsem** [comment]
related #7500

**Comment by jdalsem** [comment]
with all these related issues... seems like we have a good candidate :)

**Comment by hypeJunction** [comment]
@jdalsem I think this would really help with the routing work I am doing in #10698. Adding some magic for common routes would be nice.

**Comment by hypeJunction** [comment]
Proposed roadmap:

- [ ] Denormalize subtypes in `entities` table (get rid of subtype id's as there is no real use for them, we allow arbitrary subtype values, which populate the subtypes table; use string subtype values instead)
- [ ] Require subtypes for all entities; add defaults for user and group, as `user` and `group` respectively
- [ ] Drop `entity_subtypes` table
- [ ] Remove subtype API: `add_subtype()`, `update_subtype()`, `get_subtype_from_id()` etc
- [ ] Add runtime subtype class resolution: this could either take in the class name or closure that will return constructor class name based on database row (could use hooks)
- [ ] Drop `item:$type:$subtype` strings in favor of `$type:$subtype` and `collection:$type:$subtype`

**Comment by jdalsem** [comment]
Good plan

> Add runtime subtype class resolution: this could either take in the class name or closure that will return constructor class name based on database row (could use hooks)

Class name registration already part of elgg-plugin.php if i am correct. You should use that


> Drop item:$type:$subtype strings in favor of $type:$subtype and collection:$type:$subtype

what is your beef with this?

**Comment by jdalsem** [comment]
Also checkout issue #8851

**Comment by hypeJunction** [comment]
Working on this, almost finished, just have to update a ton of tests

**Comment by jdalsem** [comment]
This has been changed as part of https://github.com/Elgg/Elgg/pull/11327
