### ISSUE TITLE
removal of hover effect on icons also removed feedback like the likes thumb

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10477]
i can not see if i like an item based on the color of the thumb... should we do a thumbs down for unlike? Or add a highlight or selected class? Or something else? There should be some visual feedback on the thumb icon

/cc @mrclay

**Comment by mrclay** [comment]
`.elgg-icon-selected` seems most obvious, but my background in accessibility makes me wince to think of using a CSS class to indicate information. But that argument is probably over.

**Comment by hypeJunction** [comment]
Not that we have text labels accessibility shouls not be an issue. I'd prefer `elgg-state-active`

**Comment by hypeJunction** [comment]
Now*. Stupid phone.

**Comment by mrclay** [comment]
Fixed by #10891
