### ISSUE TITLE
Remove the _graphics folder

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10483]
after #10482 and #10474 there are just a few files left... they could be moved to the regular views path... we can then drop _graphics in the root folder

**Comment by jdalsem** [comment]
should the images be moved to `/views/default/` or to `/views/default/graphics/`? We need to update links accordingly

**Comment by mrclay** [comment]
I kinda think it's worth adding `img/` to the view names to keep the main default directory less cluttered.

**Comment by jdalsem** [comment]
why img? we already have graphics...

**Comment by mrclay** [comment]
Just saw that. That's fine. Odd that what's there is an HTML view :)
