### ISSUE TITLE
Users can interact with elements before event listeners are registered

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10489]
Our page rendering performance is great, but it means interactive elements are presented before event listeners have been registered.

The "progressive enhancement" solution of defaulting to usable links is still problematic. Links to partial views (not complete, or half-baked pages) should never be used. If the current page allows user input, a button that unexpectedly falls back to a link could be disastrous UX.

Strawman: 
1. At top of body, a script would register a click handler on document. If the target element had the attribute `data-elgg-click="name"`, then the event data would be captured under the key "name" and `return false`.
2. A clickable element could include this data attribute to capture early clicks.
3. For that component module, the real listener would be registered, and the data attribute removed.
4. The module could then do as it wished with the captured click data, maybe choosing to re-trigger it.

**Comment by beck24** [comment]
I don't see any reason that wouldn't work as long as that initial click handler is registered before the elements can be interacted with.

**Comment by hypeJunction** [comment]
I don't see how you would unregister the default click handler. Returning false would terminate the entire handler sequence.

**Comment by mrclay** [comment]
Removing the data attribute makes the default listener ignore the element again.

**Comment by hypeJunction** [comment]
Who removes the attribute?  It would have to be done in the AMD module doing the binding. Fine by me.

**Comment by mrclay** [comment]
I have this store-and-replay solution working. But the problem it leaves is that the UI remains frozen (doesn't respond to the click) in the meantime. And each user of the API is going to want a different solution. In some cases you might want to show as disabled/half-opaque until they're ready for clicks. Or show some kinda indicator to let the user know "we're working on it."

**Comment by mrclay** [comment]
WIP #10504
