### ISSUE TITLE
Split salutation and greeting from notification body

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10485]
Currently notifications (sometimes) have a salutation and greeting as part of the notification. This results in differences like `Dear X`, `Hi X` etc. The same applies for the greeting (`Kind regards`, `Bye!`).

If we separate this from the notification body, this could reduce the amount of translatable text and standardize the salutation and greeting for notifications

**Comment by hypeJunction** [comment]
Same with `Do not reply to this email`.

**Comment by jdalsem** [comment]
Yep... something like the notification header and footer

**Comment by hypeJunction** [comment]
I was thinking we should move notification body rendering to views. It would make it a lot easier to transition to HTML email notifications. On-site notifications do not have to be plaintext either...

**Comment by jdalsem** [comment]
don't know if we need views... can do enough at this moment... but i also see a benefit in reusing notification texts for mail and site notification (if you remove salutation/greeting... header/footer)

**Comment by hypeJunction** [comment]
Outgoing emails are ugly. If you want to do anything with them you have to invent crazy hacks.

**Comment by jdalsem** [comment]
Make a new issue for that discussion...

**Comment by hypeJunction** [comment]
I will just make a fix some day...

**Comment by hypeJunction** [comment]
I am just saying with views yiut coukd easily add a header and footer

**Comment by jdalsem** [comment]
not as long as we do not split the text... where the header and footer are appended is not so important for me... view could be fine... don't want to fall into viewtype issues like with the excerpt view though
