### ISSUE TITLE
Bring back river access_id

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10495]
I have recently realized that removing access_id from river API was a privacy issue. I had a plugin that was relying on that value being respected for some custom visibility logic and it was just being ignored. There are use cases when river items are created and are not intended for the object and target audiences.

**Comment by juho-jaakkola** [comment]
Can you give examples of such use cases?

**Comment by hypeJunction** [comment]
1. Annotation access id is ignored. If you create a river item for a public object and private annotation, it will show in the river
2. There is no way to access control river items about relationships between users or other public entities, e.g. if a site chooses not to display new friendships in the river, there is no easy way to achieve it.

**Comment by beck24** [comment]
I thought I removed it, but I can't find anything in my PR history.  Looks like I fixed some stuff dealing with disabled entities.  Not sure when this got changed.

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/pull/6203

**Comment by hypeJunction** [comment]
Strawman: add access_guid and access_owner_guid columns to allow quick acess sql lookup. Keep those in sync on update actions. Don't do big joins when not needed

**Comment by mrclay** [comment]
So river items basically have plain entity-like access control? :+1: but object/target could have diff owners and access levels. Syncing hard/impossible.

**Comment by hypeJunction** [comment]
I don't care about the target. If the target fails to enforce its own access logic on contained entities, not my problem.

**Comment by hypeJunction** [comment]
Plus it will sync based on access_guid column, so this will have to be set in stone at river creation

**Comment by hypeJunction** [comment]
We don't check container permissions in entity lists either

**Comment by beck24** [comment]
There was a problem with it the way it was previously though, I wish I could remember exactly what that was.  I think it was either river items being viewed that shouldn't be able to (seeing a river item for a blog in a hidden group you're not a member of) or problems with keeping access in sync when updating one of the associated entities...

**Comment by hypeJunction** [comment]
That could happen in any other list list as is. We don't filter by container, so you could see blogs you are not supposed to in the All blogs tab

**Comment by beck24** [comment]
ok, I don't have any specific objections to moving back to the explicit river access_id, I would like to know the specific reasons it was changed in the first place so we're not just reverting to a bunch of other issues.  If we know why it was changed perhaps we can do it in a manner that solves both sets of issues.

**Comment by iionly** [comment]
I think the problem was not the "viewing" of river entries as such where the user had no sufficient right to do so but rather that the display of the entries also included usage of API functions on the object and target (e.g. for creating the links to the object/target with getURL) that resulted in fatal errors because the user had no sufficient access level for the object and target entities. And this resulted not only in problems for displaying these river entries but the whole page was not displayed anymore if such an issue occured with a single river item in it.

**Comment by hypeJunction** [comment]
> And this resulted not only in problems for displaying these river entries but the whole page was not displayed anymore if such an issue occured with a single river item in it.

That's why we should always check instances without assuming anything in any of the views. This is a global problem and it manifests itself not just in river. I don't think it's good enough reason for heavy SQL queries in the river.

**Comment by hypeJunction** [comment]
Redundant after #11573
