### ISSUE TITLE
Menu overhaul ideas

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10506]
_Ideas from @hypeJunction:_

I don't mind Aalborg as much, it doesn't really matter which theme we use. The problem is that we are locked into a really bad navigation system:
a) with too many menus 
b) with too many dynamic items 
c) with too much sniffing for handlers/contexts in hooks.

I think I remember liking Joomla for how the navigation was directly related to content structure - the entire sitemap was easy to build. In Elgg, it's next to impossible. It's hard to move menu items around, build different menu structures, e.g. in a vertical `site` navigation system most `page` items could be registered as subitems, but because we are so context-dependent, a plugin wouldn't be able to grab all items and shuffle them for this to work.

We are suffering from navigation decisions made 10 years ago. That's why we don't see so many Elgg themes, they all look the same, and the vast majority of themes only choose to style the landing page. We are locked to a menu system organized for us not by us. **We need a tabula rasa.** Scratch all we know about Elgg's navigation, and think of what the ideal navigation would look like. Styling it and adding client-side interactions should be the last of worries

We could:
- Get rid of All, Mine, Friends tabs and use dropdown filters instead
- Rethink how we use filters and sorts - we don't need `filter` and `page` menu items to represent the same list filtered or sorted in a different order
- Most of the `page` menu items should actually be filter tabs
- Consider loosing the `page` menu - action items should be in the entity menu, other items are either in filter tabs, or a dedicated menu (I am thinking group context with all the madness that's happening there)
- Add UI that allows for submenu items in the `site` menu
- Get rid of the `More >>` from site menu. We should be thinking about the wide range of devices that are used to display these menus. Doing something server side that only makes sense for one device size is not reasonable. We could instead sniff the width using jQuery and collapse into a burger where needed.
- Avoid horizontal menus at all costs, they are not mobile friendly
- No more than 2 buttons in the `title` menu. If there is more, it shouldn't be there - move to the `owner block` or elsewhere (groups pages again)
- Remove all negative actions from title menu (Leave group shouldn't be so prominent). Delete items should not be so prominent - tack them away.
- Loose the `extra`s menu - stuff in there doesn't relate to the page. Add a list menu instead - you want an RSS representation of a list and not a page, I don't event know if RSS works with multiple lists on the page. Gallery view toggle has nothing to do with the page - it has to be related to the list etc
- Make use of owner block properly - why do we assume that it should only list things that I own? E.g. `Group members` would make perfect sense in the group's owner block. 
- Anything that is an icon menu should be thrown away: a) icons are ambiguous, b) they are hard to work with both server and client side. The only place where icons make sense is the topbar, but even then we should reconsider - we should reserve the highest value real estate for what requires the most attention from the user - notifications and actions required. `Friends` belongs in the owner block - friend requests however do belong the topbar
- We need a centralized area for plugins to put stuff that requires user's attention/action - a `to-do` list of sorts: group invitations, group admin actions, friend requests, persistent notices (similar to admin notice that require user interaction to be dismissed).

**Comment by hypeJunction** [comment]
Some work on it here: #10509

**Comment by hypeJunction** [comment]
I think most of this has been taken care of.

**Comment by jdalsem** [comment]
agree
