### ISSUE TITLE
Allow core to declare Elgg\Upgrade\Batch upgrades

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#10513]
Currently it is possible to declare `Elgg\Upgrade\Batch` upgrades only through `elgg-plugin.php` file therefore preventing core from using the upgrade interface.

We could simply add a file `engine/upgrades.php` that would return array of upgrades.

**Comment by jdalsem** [comment]
only thing we need to figure out it priority...

**Comment by juho-jaakkola** [comment]
Yes, we could order them automatically based on the dependencies. There may however be errors, so priority alone isn't enough.

**Comment by hypeJunction** [comment]
We could order them by date and lock until all previous updates have been completed.

**Comment by juho-jaakkola** [comment]
More about upgrade priority here: #10514

**Comment by jdalsem** [comment]
He @juho-jaakkola how is the progress on this?
