### ISSUE TITLE
"Erroneous data format for unserializing 'Elgg\Notifications\Event'" in file \engine\classes\Elgg\Queue\DatabaseQueue.php

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10511]
when running minute cron

**Comment by hypeJunction** [comment]
Hm, I have seen data serialization issues with PHP 7. What version are you running?

**Comment by jdalsem** [comment]
5.6.5

**Comment by hypeJunction** [comment]
Can you dig out the actual blob form the queue table that causes this?

**Comment by jdalsem** [comment]
Never got to reproduce this
