### ISSUE TITLE
Upgrade Locator should validate version before registering upgrades

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10517]
Found out when running upgrade after fresh install (group icon transfer upgrade should not be needed)

**Comment by juho-jaakkola** [comment]
The problem here is really that the `countItems()` is counting the amount of groups instead of checking how many group icons are actually in the old directory: https://github.com/Elgg/Elgg/blob/master/mod/groups/classes/Elgg/Groups/Upgrades/GroupIconTransfer.php#L14-L18

**Comment by juho-jaakkola** [comment]
Indeed, `UpgradeLocator` in fact never even checks whether `countItems()` returns anything. I'll make a fix for it.

**Comment by hypeJunction** [comment]
This is not an issue anymore on new installs
