### ISSUE TITLE
Allow upgrades to define dependencies to other upgrades

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#10514]
We could add a new method to `Elgg\Upgrade\Batch` interface:

``` php
public function getDependencies() {
    return [
        'blog:2016112701',
        'core:2016120301',
    ]
}
```

`BatchUpgrader` would then confirm that those upgrades have been finished before allowing the upgrade to be started.

**Comment by juho-jaakkola** [comment]
Note to self: it should be safe to assume that upgrade priority is the same as the upgrade creation date (upgrade that depends on another upgrade shouldn't have earlier `yyyymmddnn` timestamp).

However, we cannot assume that all plugins are necessarily always the latest version, so an upgrade might slip in if a plugin version requiring a dependency gets installed before the plugin providing the dependency.

**Comment by jdalsem** [comment]
keeping the simple situation as is for now
