### ISSUE TITLE
FR: allow installer to handle already existing settings.php file

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10520]
currently assumption is when booting Elgg that if settings file exists, Elgg is fully installed. Would be nice if we can have some other check to check if installed, so so will be forwarded to the installer. The installer should be able to accept an already existing settings file and jump to site config step

**Comment by iionly** [comment]
Which version of Elgg are you referring to? I had reported this issue after installation with an existing settings.php failed on Elgg 1.8 (https://github.com/Elgg/Elgg/issues/5832) - and is broken on Elgg 1.8 - 1.12. But it works for me on Elgg 2.0 - 2.2 (that's why I closed the issue).

**Comment by jdalsem** [comment]
happening in master... did not know it even worked in 2.x

**Comment by jdalsem** [comment]
Tested it, and it is working. Only thing is you need to go to /install.php... index will not detect a non installed db and will crash on index page....  Makes sense... happy with the fact that installer will run with settings present
