### ISSUE TITLE
DBAL exception leaks passwords

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10521]
I was rebooting the server and got shown an exception with mysql password in cleartext

**Comment by jdalsem** [comment]
admin only if i am correct or for everyone?

**Comment by hypeJunction** [comment]
Not sure

**Comment by mrclay** [comment]
IMO admins shouldn't get the password either. May be a tough problem though.

**Comment by jdalsem** [comment]
@mrclay i believe you are working on this...
