### ISSUE TITLE
GET /register HTTP/1.1" 403

### ISSUE THREAD

**Issue by dipenpatel235** [Elgg/Elgg#10538]
Hello..
i have setup elgg 2.2.2 version and working fine.

but mine one of the Bangladesh colleague have issue is not able to click on register.
when he is click on register so get 403 forbidden error. except that all are able to register.

so can u please know how can i fixed that ?
i have also check error log but not seen any error.
below is access log when he click on register

Browser 1:

13.58.7.02 - - [30/Oct/2016:02:15:57 +0800] "GET /register HTTP/1.1" 403 44 "https://mysite.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"

Browser 2:

13.58.7.02 - - [30/Oct/2016:01:35:07 +0800] "GET /register HTTP/1.1" 403 44 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"

Thanks

**Comment by mrclay** [comment]
Are you saying some browsers can load the /register page, but not others?

**Comment by jdalsem** [comment]
We have no steps to reproduce this. I have personally not ever experienced this. Closing this as it may not even be related to anything in Elgg
