### ISSUE TITLE
PHP XML support undocumented

### ISSUE THREAD

**Issue by simondeziel** [Elgg/Elgg#10546]
When deploying on Ubuntu 16.04 using nginx and PHP 7.0, I met a this weird problem leading to HTTP 500:

2016/11/01 15:21:21 [error] 4472#4472: *1 FastCGI sent in stderr: "PHP message: Exception at time 1478013681: Error: Class 'DOMDocument' not found in /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/classes/ElggAutoP.php:89
Stack trace:
#0 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/lib/output.php(57): ElggAutoP->process('Installing Elgg...')
#1 /var/www/elgg-2.2.2/vendor/elgg/elgg/views/installation/install/pages/welcome.php(6): elgg_autop('Installing Elgg...')
#2 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(362): include('/var/www/elgg-2...')
#3 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(300): Elgg\ViewsService->renderViewFile('install/pages/w...', Array, 'installation', true)
#4 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/lib/views.php(343): Elgg\ViewsService->renderView('install/pages/w...', Array, false, 'installation')
#5 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/classes/ElggInstaller.php(246): elgg_view('install/pages/w...', Array)
#6 /var/www/elgg-2.2.2/vendor/elgg/elgg/engine/classes/ElggInstaller.php(272)" while reading response header from upstream, client: MY_IP, server: MY_HOST, request: "GET /install.php HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "MY_HOST"

Simply install php7.0-xml fixed it so I think it should be mentioned over here: http://learn.elgg.org/en/latest/intro/install.html#requirements. Maybe older PHP packages used to pull this module by default but on 16.04 that's not the case.

**Comment by simondeziel** [comment]
What tipped me off is this: https://github.com/Elgg/Elgg/blob/2.2/engine/classes/ElggInstaller.php#L1064 Otherwise, nothing helpful was showing on the WebUI.

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/commit/48de11e130b034fe9db6ad35a3d06d99af54df0b
