### ISSUE TITLE
Custom index plugin not working?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10550]
custom index is not showing index page... noticed this in master

**Comment by jdalsem** [comment]
nope... it was a case of plugin order. Activity is a new plugin  in master so it was positioned last.... Just needed to move activity before the custom index plugin and it was fixed :) classic

**Comment by hypeJunction** [comment]
We should add conflicts to manifest perhaps.

**Comment by jdalsem** [comment]
its not a conflict, an order issue at max... custom_index should be below activity
