### ISSUE TITLE
Idea: should we merge members plugin into profile?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10588]
Probably not going to use members plugin if profile is disabled anyway...

Also makes sense from a breadcrumb perspective "All Members -> Profile of Jeroen Dalsem"

**Comment by hypeJunction** [comment]
Makes more sense in the friends plugin. Members as friendable users.

**Comment by jdalsem** [comment]
Leaving this as is for now. No problem to have both plugins
