### ISSUE TITLE
2.2.3 zip release incomplete (bundled plugins missing)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10585]
The same as with 2.3-rc1 zip archive: in mod are almost all plugins missing. Only the plugins pulled via composer from other repos are there.

**Comment by iionly** [comment]
Could it be that the only reason for the missing plugin folders in mod is an outdated elgg-starter-project.sh script used for creating the zip archives? The script has been recently updated by @mrclay in https://github.com/Elgg/elgg-scripts/commit/35920440ba9fb4daa552d03a4357fc0861bedfe0 and maybe this changed version has not been used for creating the recent new release zips.

I've tested locally by creating a 2.2.2, 2.2.3 and 2.3.0-rc.1 zip archive and it worked fine in all 3 cases. For 2.2.2 the composer dependencies differed partly from the 2.2.2 archive on elgg.org (possibly due to missing composer.lock) but for 2.2.3 and 2.3.0-rc.1 everything locked perfectly alright - including all plugin folders available in mod.

Could someone please try it again on the elgg.org server after updating the elgg-starter-project.sh script?

**Comment by hypeJunction** [comment]
That's possible.  I just used the scripts I have cloned months ago. I am at the airport, will retry tomorrow if noone beats me to it

**Comment by hypeJunction** [comment]
Fixed now.

**Comment by iionly** [comment]
@hypeJunction sorry, but the 2.2.3 release zip is still not fixed.

**Comment by hypeJunction** [comment]
I don't know. Used the same script. I don't have time for hunting down the exact version of scripts I should be using.

**Comment by iionly** [comment]
I've uploaded a 2.2.3 zip with bundled plugin in the mod folder at slack.

Built script available in the elgg-script repo worked for me both for the 2.2 and 2.3 branch. Could it be that you simple forgot to replace the 2.2.3 zip file on the elgg.org server?

**Comment by hypeJunction** [comment]
It's auto-generated by the release script

**Comment by iionly** [comment]
As you mentioned that you used a script "cloned months ago" I was under the impression that you were not creating the release zip on the elgg.org server where the zip would be directly copied.

@mrclay  updated the release script (in the repo) about two months ago. That's the script that worked for me. The script does not copy the plugins but makes a composer install and then zips the end result and copies it.

If the release script fails (though it worked perfectly fine for me), something is probably wrong with the Elgg installation via composer. And then it's not helpful at all to suggest making the installation via composer as the composer install instruction would probably contain the same fault.

And I think it provides simply a very bad first impression if the recommended zip release on the community site does not work. Add to that that the composer installation will not work for everyone and that beginners might fail to get it to work then.

I don't know what else I should do apart from asking to please provide a working zip of 2.2.3. I already provided a zip that is complete at slack. The only thing to do for 2.2.3 would be to replace the 2.2.3 zip on the community site with this updated zip file. For the next releases it might be helpful nevertheless to figure out why it failed - that is the composer installation - because the install instructions for composer based installation might need to be corrected, too.

**Comment by iionly** [comment]
Fixed by recreating the 2.2.3 release zip.
