### ISSUE TITLE
cacheroot turns to '/' if missing in CONFIG

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10597]
should revert to dataroot

Need to examine more where this happens

**Comment by jdalsem** [comment]
causes fatal crashes (with open_base dir policies as '/' is not default writeable)

**Comment by mrclay** [comment]
Did it get set to empty string in DB? Remove the entry if so.

**Comment by jdalsem** [comment]
who sets it in the DB?

should we do an !empty check to prevent this...

**Comment by mrclay** [comment]
Disregard, we only read it from settings.php. Which branch does this happen in?

**Comment by jdalsem** [comment]
2.2.3 (an upgraded site)

**Comment by mrclay** [comment]
[Here's](https://github.com/Elgg/Elgg/blob/2.2.3/engine/classes/Elgg/Config.php#L287) how this is set. Are you sure there's not a bad value in settings.php?

**Comment by jdalsem** [comment]
Never ran into this issue again and i do not know how to reproduce. Assuming it was a fluke.
