### ISSUE TITLE
query logger not showing all queries

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10594]
developer tools stats on screen show query count 19, but only 3 queries are shown in the debug

**Comment by mrclay** [comment]
I think the big change occurred in 2.0. I think the logger level is set later now in `Elgg\BootService::boot`

**Comment by jdalsem** [comment]
the developer tools will only show stuff that happens after the developer tools logger is registered, that is somewhere during plugins boot. Pre-plugin boot queries can only be logged in the php error log
