### ISSUE TITLE
The boot cache was rebuilt for this request

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10593]
with all caching on shouldn't this be NOT happening?

**Comment by hypeJunction** [comment]
I thought I noticed this as well

**Comment by jdalsem** [comment]
already looking into this

**Comment by jdalsem** [comment]
My problem... your config file needs to have ->boot_cache_ttl enabled

**Comment by jdalsem** [comment]
only wondering if default value of 10 is not way to low....

**Comment by mrclay** [comment]
I was paranoid about stale data preventing the system from booting, in case we missed an invalidation event. On a busy site, 10s is a lot of requests.

I do notice I didn't use the Stash stampede protection. That's probably wise.
