### ISSUE TITLE
Exception updating master

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10615]
I get this trying to apply #10577 upgrade.
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'n_table.name' in 'where clause'

QUERY: SELECT DISTINCT e.* FROM elgg_entities e JOIN elgg_metadata n_table on
e.guid = n_table.entity_guid WHERE (((n_table.name IN ('icontime')) AND ((1 = 1) AND (n_table.enabled = 'yes')))) AND ((e.type = 'group')) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 10
```

**Comment by mrclay** [comment]
I think my system is now in a bad state, thinking it already denormalized strings.

**Comment by jdalsem** [comment]
what was the pre-upgrade version?

Did you already ran the upgrade? n_table.name is only available after the upgrade....

**Comment by jdalsem** [comment]
did the upgrade say it completed?

**Comment by mrclay** [comment]
I still have a datalists table. I should've backed up before. Sad.

**Comment by mrclay** [comment]
Actually I have a 2.3 site I'll copy and upgrade.

**Comment by jdalsem** [comment]
probably your upgrade did not complete.... maybe just reverting the code might work...

datalists should have been removed but not as part of #10577... so the upgrade crashed before...

**Comment by mrclay** [comment]
Upgrade from 2.3 went fine.
