### ISSUE TITLE
Do not use autoload_cache during upgrade

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10616]
During upgrade the class autoload_cache is used. This cache is used for the storage of custom classes (and their paths). If you move a class... and fix this in the registration in a upgradescript for example... you still will have issues during upgrade if these classes are used during the system events (like plugins boot or init) as the cache is not invalidated.... maybe we could never use systemcache during the upgrade run... to prevent these kind of issues

**Comment by mrclay** [comment]
I think I proposed completely disabling caching in the default DiskCache when simplecache is off. Definitely shouldn't cache during upgrades.

**Comment by mrclay** [comment]
> completely disabling caching in the default ElggFileCache when simplecache is off. 

Not necessary. We should always use the system cache API, which does this.

**Comment by hypeJunction** [comment]
autoload cache is flushed during upgrade

**Comment by hypeJunction** [comment]
Close this

**Comment by jdalsem** [comment]
is it flushed before upgrade?

**Comment by hypeJunction** [comment]
https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/UpgradeService.php#L98

**Comment by jdalsem** [comment]
so, NO is the answer. Use case still stands

**Comment by hypeJunction** [comment]
I guess I don't understand the problem from the description.

**Comment by hypeJunction** [comment]
```php
_elgg_services()->autoloadManager->setStorage(new CompositeCache('autoload', $config, ELGG_CACHE_BLACK_HOLE));
```

**Comment by jdalsem** [comment]
yep
