### ISSUE TITLE
master: styling issues with .elgg-anchor *

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10610]
links look lower than other text... or the other way around

**Comment by hypeJunction** [comment]
Probably new anchor wrappers.

**Comment by jdalsem** [comment]
Yep the `.elgg-anchor *` styling is cause more problems...

navigation, underlining in entity menu items... links in latest comments etc...

**Comment by jdalsem** [comment]
Not an issue anymore AFAICT
