### ISSUE TITLE
No profile data being saved when members sign in with chrome on android

### ISSUE THREAD

**Issue by aharleycpl** [Elgg/Elgg#10627]
We had an issue when upgrading to the recent stable version where members who create an account with an android using google chrome browser are able to create an account but none of their profile information is passed through except their name , email and profile picture.  This was with 2.2.3.  Other browsers on android work fine as well as chrome and Edge.  

After I downgraded to 2.2.0 I no longer have that problem.   I was able to replicate the problem my users were having with a test account on my server but only with chrome on my android.

**Comment by jdalsem** [comment]
Elgg default does not store additional profile data when registering... do you use a plugin to provide the extra profile data? Maybe Profile Manager? Or a custom theme? If so, you probably should contact the plugin developer.

**Comment by aharleycpl** [comment]
We do use profile manager so perhaps that is the correct place to report to.  Took us a little bit to figure out how people were creating profiles with no data.  Thank you for pointing us in the right direction.

**Comment by jdalsem** [comment]
Tried to reproduce this on Elgg 2.3.x with Chrome on Android with the latest Profile Manager plugin and have no problems with additional profile fields not saving their data.

If you have more detailed steps to reproduce on a default Elgg installation we can reopen this issue.
