### ISSUE TITLE
Add stylable alerts/prompts to core

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10624]
Something like http://craftpip.github.io/jquery-confirm/

**Comment by hypeJunction** [comment]
Why not use lightbox?

**Comment by jdalsem** [comment]
That could be an option, but we then need to make some reusable components for alert and confirm dialogs...

**Comment by jdalsem** [comment]
or even `elgg/popup` is an option... as long as we have centralized dialog window components

**Comment by hypeJunction** [comment]
There is already lightbox, popup, jquery UI modal. IMO, we shouldn't be adding any more overlay components.

**Comment by jdalsem** [comment]
with `elgg_view_message` we have at least standardized styled messages. Dialogs can indeed be created with a lightbox, so closing this for now
