### ISSUE TITLE
master: elgg.register_hook_handler is not a function

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10620]
on admin dashboard, or plugins list

**Comment by mrclay** [comment]
Can't reproduce.

**Comment by jdalsem** [comment]
me neither

**Comment by jdalsem** [comment]
hmm it is intermittent... i now have it again

**Comment by jdalsem** [comment]
found it... sprintf change... need to figure out how to fix

**Comment by jdalsem** [comment]
had to change it from being loaded inline, to being a async dependency... don't know another way to circumvent this problem
