### ISSUE TITLE
adopt a css preprocessor

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10625]
A pure php processor can be found here http://the-echoplex.net/csscrush

This would make css more readable and easier to maintain... also it would allow use to define some global vars to be used in css so they could be easier to replace in plugin (think of colors or font family).

**Comment by jdalsem** [comment]
https://www.sitepoint.com/6-current-options-css-preprocessors/

Don't want to over complicate the things for devs, so a pure php version is the easiest way to go i think... no special installations or build processes... those build processes also stand in the way of our views system

**Comment by hypeJunction** [comment]
This is a dupe. There is already a discussion going elsewhere.

**Comment by jdalsem** [comment]
Do you mean https://github.com/Elgg/Elgg/issues/10316
