### ISSUE TITLE
Search plugin should stop extending header

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10632]
Every time it's an annoying nuance.

**Comment by jdalsem** [comment]
What alternative?
Op 25 nov. 2016 7:52 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:

>

> Every time it's an annoying nuance.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/Elgg/Elgg/issues/10632>, or mute the thread

**Comment by hypeJunction** [comment]
Will figure it out

**Comment by jdalsem** [comment]
How about the theme just echoes a view where it intends a search feature...
Search then can extend / replace that view

Op 25 nov. 2016 8:07 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:
