### ISSUE TITLE
Ajax activation of plugins is confusing

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10656]
When plugins are activated via AJAX the UI doesn't get updated, which makes you wonder what just happened. The settings icon doesn't show, any page menu items that are added by the plugin are not shown, so you have to reload the page anyway.

**Comment by jeabakker** [comment]
i also believe the plugin is no longer draggable after the ajax action

**Comment by mrclay** [comment]
Sounds like a new bug. Entire plugins list updated when I added this.

**Comment by mrclay** [comment]
> settings icon doesn't show

I'm rebuilding the entire list, not sure why this isn't updating (isn't removed either)

> page menu items that are added by the plugin are not shown

Doh, that was missed.

**Comment by mrclay** [comment]
See #10665
