### ISSUE TITLE
Use simplecache radio is missing

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10660]
@jdalsem I don't see the radio for enabling simplecache in admin settings

**Comment by hypeJunction** [comment]
And compress JS radio

**Comment by jdalsem** [comment]
i see them... did you flush the cache?

**Comment by jdalsem** [comment]
browser/OS?

**Comment by hypeJunction** [comment]
Chrome Win. I see all other ones, but not those two.

**Comment by jdalsem** [comment]
i have the same issue... maybe js related... will investigate

**Comment by jdalsem** [comment]
no issue in FF

**Comment by jdalsem** [comment]
found it... will submit a PR
