### ISSUE TITLE
Ajax view $vars are not populated with request query elements

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10667]
Can't tell for sure, but it looks like using ajax.view() with data doesn't add data to $vars

**Comment by jdalsem** [comment]
Ran into that too... Only GET vars, not POST

Op 23 dec. 2016 5:53 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:

**Comment by mrclay** [comment]
See #10672

**Comment by mrclay** [comment]
Fixed https://github.com/Elgg/Elgg/pull/10672
