### ISSUE TITLE
Separate account settings form into multiple forms

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10671]
Work started in #10445 but IMO that has some big UX issues.

Strawman: each section is a button, some show the current value (email), some don't (change password). Clicking the button does one of two things: Either displays the form in a lightbox (does not submit via ajax) or replaces the button with the form and disables all other sections. Like widgets, each button has a view so plugins can extend/show what they want.

Goals:

- remove overly-complex user settings save hook
- form body views in forms directory (where they belong)
- every section its own form
  - clear action file per section
  - can do required fields
  - performing an action is more clear (you know what you are submitting)
- could easily do ajaxed submissions

- [ ] rebase #10759 for master

**Comment by piet0024** [comment]
I have taken a look at the settings form, the work that was already started and the UX issues you have brought up. I was hoping to get some opinions/feedback on these quick mock-ups. 

The first view for each section has the title, the current value (except password) and a link to edit the section. When a user clicks on the edit link, the view will be replaced with the form view and focus on the first input (old information pre-filled). The other links will disable preventing the user to click other options unless they save or cancel the current form. Clicking save should perform the action via ajax and then replace the form with the initial section view with the updated information.

Inital View
![account_settings](https://cloud.githubusercontent.com/assets/7603237/22556829/822175ac-e936-11e6-83de-6d3b55a72ee3.jpg)

Editing Display Name
![account_settings_open](https://cloud.githubusercontent.com/assets/7603237/22556872/963a3b50-e936-11e6-961f-25d313f6bc4a.jpg)

Please let me know what you think!
What about the mock-ups do you like / dislike?
Do you feel this still looks and feels like Elgg?
Are there any UX issues you can see?
How can this settings page be improved?

**Comment by hypeJunction** [comment]
This would be a great UX improvement. Looks cool so far.

**Comment by jdalsem** [comment]
@piet0024 i think that is what @mrclay is going for with his remarks. It would be relatively simple to pick up #10445 and replace the 'info text' of the sections with the values..

**Comment by piet0024** [comment]
Hi! I've been looking at picking up the work done on #10445 and making the proposed changes. I was wondering where the best place to write some JavaScript for this would be (things like making sure the other forms can't open or perhaps they open like an accordion / replacing the info text view with the form). Should I write a function in ui.js or create a new file?

**Comment by jdalsem** [comment]
#10445 already has toggleable sections... look at how that is done. I do not think you would even need additional js

**Comment by mrclay** [comment]
#10445 allows multiple forms open at same time, but only one is submitted. Recipe for data loss.

**Comment by jdalsem** [comment]
agreed, but nonetheless you expand on it... just collapse the rest

**Comment by jdalsem** [comment]
Several changes have been made to the user settings form. Currently we are leaving it as is
