### ISSUE TITLE
Profile image not displayed (reason unknown, example given)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10686]
See https://elgg.org/profile/NBoogaa.

The profile image of this user isn't displayed anywhere on the community site. As the default image isn't displayed either, something might have gone wrong here.

Possible something went wrong with cropping or the image isn't cached correctly. If I'm not mistaken, there have been changed made with profile images and/or file caching in Elgg 2.3 that might not fully work at least on some condition - as for at least this one user.

**Comment by iionly** [comment]
The profile image of the user I've given as example shows up now on the community. It might be that the user cropped the profile image and maybe something has gone wrong at cropping before and the user fixed this now.

Closing for now until I come across it again.

**Comment by iionly** [comment]
Another example of a user where the display of the profile image (or fallback to default image) fails: https://elgg.org/profile/apjithesh

So, I think there's some bug somewhere in profile image handling in Elgg 2.3 that wasn't there before.

**Comment by beck24** [comment]
I've found that elgg_save_resized_image *requires* a valid file extension or it fails.  This is problematic when you try to use it on freshly uploaded files that are still in tmp, and it's used in the deprecated version of get_resized_image_from_uploaded_file() which operates on $_FILE in tmp

basically get_resized_image_from_uploaded_file() is broken in 2.3

**Comment by beck24** [comment]
I should point out I haven't verified that this is the cause, but it seems very likely related

**Comment by iionly** [comment]
I've tested it with uploading a jpg image without file extension. In this case the resizing fails and the uploaded image is rejected to be used as profile image.

When looking at the page elements of a page containing a broken profile image I see that the mimetype of the broken image is displayed as inode/x-empty. Filesize 0 and size 0x0px.

It might help to ask the user at https://elgg.org/profile/NBoogaa who seemed to have fixed the issue by now what he might have done "wrong" / differently the first time when it failed to work. It might be the filesize of the uploaded image being too large or maybe he tried to crop the image in a certain way and this resulted in a null image somehow.

Cropping is kind of acting strange (I don't know if it was different in the past). On testing the cropping (and resetting image cropping) it happened several times now that I got the message "cropping failed" and the profile image was totally deleted (though in this case at least the default grey head showed up again instead).

**Comment by jdalsem** [comment]
I encountered the same issue with uploading images using `get_resized_image_from_uploaded_file`..

conclusion by @beck24 that this function is broken is correct...

**Comment by jdalsem** [comment]
hmmm more is broken... but it can be fixed... will submit a PR soon

**Comment by iionly** [comment]
@jdalsem could you reproduce the behaviour showing up on the community site with profile images not showing (or likely rather the profile image files being of size 0)?

The issue with get_resized_image_from_uploaded_file() with image files without ending is surely breaking the profile image upload (or rather the resizing). But when testing the profile images without filetype extension were totally rejected for me and the default grey head still showed up as profile image. So, I think at least two (different) issues.

**Comment by jdalsem** [comment]
@iionly what are the exact steps to reproduce the community issue?

**Comment by iionly** [comment]
@jdalsem My point is that I was NOT able to reproduce the issue with a profile image not showing up so far as I see it happen on the community site.

The bug discovered by @beck24 gives me a different result. In case of uploading an image file without file extension the image gets rejected completely because the resizing fails and the default profile image is used instead (also visible for other users). Whereas the issue I see on the community site causes the default profile image NOT showing but (as it seems to me) a zero byte image file is served as profile image instead (giving the possibly wrong impression that no image is served at all).

So, that's why I think there must be some other bug we've not yet found. Or do you see any profile image for the user https://elgg.org/profile/apjithesh? If you would see a profile image, there might be an access level issue you might miss to notice when logged in as admin. But I doubt it's a permission issue actually.

Because other users can upload profile images fine (and https://elgg.org/profile/NBoogaa) managed to get his profile image to show up by now I suspect the bug is within code not executed for all users, for example it might be an issue when cropping the profile image in a certain manner or the image filesize might matter (possibly again in connection with image cropping). But as I said I wasn't able to reproduce the issue so far.

**Comment by iionly** [comment]
New guess on the reason why some profile images are broken on the community site...

Could it be that the accounts that display broken avatars are created with Twitter credentials are fetching the Twitter profile image is failing?

It has just been reported that accounts registered with Twitter do show broken images (https://elgg.org/discussion/view/2620185/imagem-twitter). Maybe the problem showing up on the community site is for the same reason.

I'm not using and never used the Twitter API plugin. Could someone verify / disprove that the broken profile images are failing to be pulled from Twitter? Maybe the twitterOAuth lib is outdated. Or the http urls might no longer work and it's necessary to switch to profile_image_url_https to get the image urls.

**Comment by hypeJunction** [comment]
Throw out Twitter plugin out of core and be done with it. I care not to maintain it.

**Comment by hypeJunction** [comment]
PR is here #10806 
Discussion on how to retire Twitter API is #10799 - we don't have any emails from users that were registered with Twitter API, so never get notifications, they can't even reset their password.

**Comment by iionly** [comment]
I guess the PR is rather https://github.com/Elgg/Elgg/pull/10800.

**Comment by hypeJunction** [comment]
Eh, yes that one
