### ISSUE TITLE
elgg_normalize_url should not add site url to tel:

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10689]
as tel: links are valid html5 links, elgg_normalize_url should not add site url

**Comment by jdalsem** [comment]
Same applies for other protocols... https://github.com/Elgg/Elgg/issues/7178 ...

why not quick return on any protocol?

**Comment by mrclay** [comment]
As we pass through `javascript:` and `php:`, clearly we're not depending on this for security. Passing through anything starting with `~^[a-z]+:~` seems fine to me.
