### ISSUE TITLE
"route:rewrite" fails to update context

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10692]
`elgg_get_context()` returns original identifier after the `route:rewrite` hook.

**Comment by jdalsem** [comment]
oei... could be a big issue... but haven't run into any problems with this yet

**Comment by hypeJunction** [comment]
This is in 2.3, we might have fixed it in master

**Comment by mrclay** [comment]
I'm testing 2.3 and in `init, system` the context has been updated as it should. Where are you checking it?

**Comment by hypeJunction** [comment]
I need to check. I think it was the route hook.

**Comment by mrclay** [comment]
Add this to the top of aalborg's start.php:
```php
elgg_register_plugin_hook_handler('route:rewrite', 'stuff', function ($h, $t, $v, $p) {
	$v['identifier'] = 'activity';
	return $v;
});
elgg_register_plugin_hook_handler('route', 'activity', function () {
	header('X-Context: ' . elgg_get_context());
});
```

Then load `/stuff` and check headers. I get the expected "activity".

**Comment by jdalsem** [comment]
@hypeJunction are you able to reproduce your problem?

**Comment by jeabakker** [comment]
according to https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Application.php#L603-L612 it's (re)set after a rewrite

**Comment by jdalsem** [comment]
Closing this as there are not steps to reproduce
