### ISSUE TITLE
elgg_view_field should unset #params for type hidden and securitytoken

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10699]
For the #type `hidden` and `securitytoken` there is a quick return, but this doesn't unset the # params so they end up as attributes in the html.

**Comment by jeabakker** [comment]
```php
elgg_view_field([
	'#type' => 'hidden',
	'name' => 'form_guid',
	'value' => $entity->getGUID(),
]);
```
```html
<input #type="hidden" name="form_guid" value="3954" type="hidden">
```

**Comment by hypeJunction** [comment]
I did suggest to @jdalsem that we should filter out anything with `#` in key in `elgg_format_attributes()`

**Comment by mrclay** [comment]
I'd be OK fixing `elgg_view_field` AND filtering in `elgg_format_attributes`.

**Comment by mrclay** [comment]
PR #10701. I decided to leave `elgg_format_attributes` alone after reading [almost anything](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) is a valid attribute name, and with front end libs using them... eh.
