### ISSUE TITLE
We should have a black list for last-forwarded from urls

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10695]
came across a situation where `serve-file` was the last forwarded from

**Comment by hypeJunction** [comment]
/action
/cache
/.*?\.(php|jpg|png|gif|woff)

**Comment by hypeJunction** [comment]
all ajax requests

**Comment by propertunist** [comment]
just a bump reminder for this as it is apparently causing the issue where users are forwarded to nothing on login on my site

**Comment by mrclay** [comment]
PR #10940

**Comment by propertunist** [comment]
thanks @mrclay, i am testing your commit here - so far it has fixed my issue and i haven't found any new ones. :)
