### ISSUE TITLE
ajax.objectify ignores some valid elements

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10709]
I have been trying to submit a form that has a button: `type="submit" name="foo" value="bar'`, and those values never make it to the request.

**Comment by mrclay** [comment]
Expected behavior [according to jQuery](https://api.jquery.com/serializeArray/):

> No submit button value is serialized since the form was not submitted using a button.

The only *semi-automatic* solutions I can see involve adding a 2nd arg:

- pass in the form submit event or submit button click event
- pass in the clicked button
- pass in a name/value pair object to be merged in

**Comment by hypeJunction** [comment]
Thinking about it more there isn't much we can/should do
