### ISSUE TITLE
Doctrine ORM?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10700]
I have been playing around with Doctrine ORM and got some basic functionality in place (Entity definitions, started on associations). We need to get away from writing SQL - it's impossible to read, follow or filter. It would involve a lot of rewriting, but in the end, I think we would benefit from not having to deal with SQL, being able to easily switch DB drivers etc. I am not sure I would be able to undertake the whole thing alone, anybody willing to participate?

**Comment by mrclay** [comment]
I keep having the idea, too, but ultimately doesn't sound fun.

**Comment by hypeJunction** [comment]
Not fun at all. But then I look at Laravel's eloquent and that's how I want to write queries...

**Comment by beck24** [comment]
I haven't done a lot with Laravel, but the little bit I have done was replacing their ORM usage with my own SQL because the generated ORM query was SLOW.  I don't know if that's a common thing, but scalability would be my initial concern based off that admittedly single experience.

**Comment by FedgeNo** [comment]
One of the few PHP conferences I actually attended seemed to be full of people that were using that sort of thing and one thing they all had in common that they were not dealing with proper relational systems that had row counts in the multi million range. The few of us that were writing our own queries also seemed to be the ones that could easily handle data sets like that without using database clusters or other expensive setups.

**Comment by hypeJunction** [comment]
Interesting. My latest thinking is we need an OO SQL query builder (don't care if it's engine agnostic). Our schema is too convoluted for ORM, but we need to move away from writing literal SQL, as it's a nightmare to test. I have done some basics for a plugin, I will try to wrap it up into something reusable

**Comment by jdalsem** [comment]
Closing this ticket as it will not get attention any time soon.
