### ISSUE TITLE
Elgg 2.3.0: Cache flushing issue after plugin deactivation?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10706]
I can't exactly say what's wrong as it doesn't seem to happen every time. It started to happen after updating to 2.3.0.

But I had it twice now that after deactivation of a plugin (or maybe deactivating at least two without reloading the plugin page is playing a role, too) the whole site got stuck in loading (due to still trying to load AMD modules provided by the plugins previously disabled).

**Comment by iionly** [comment]
Quite sure now it happens when you disable two or more plugins too fast. With the ajaxing of the plugin page you can disable a second plugin before the first plugin has been properly disabled / cache got updated. This results in the caching getting out of sync.

**Comment by iionly** [comment]
It's connected (at least for me) with the cache symlink. Without cache symlink used everything works fine. With symlink I get a 404 on require_config.js. It's not connected with enabling/disabling two plugins too fast - falsely got that impression.

**Comment by iionly** [comment]
What I see is that when the site gets stuck after enabling/disabling plugin(s) Elgg still tries to get files from the former cache directory, i.e. url
```
http://site.url/cache/<OLD_TIMESTAMP>/
```
instead of the new cache directory created when the cache got flushed.

Could it be some race condition caused by the ajaxification of the plugin page? Apart from the caching issues I also noticed that the ajaxed plugin page has quite some limitations (ever tried to reorder a plugin after enabling/disabling a plugin before reloading the plugin page... it doesn't work). If the caching issue would be due to the ajaxificated plugin page I would think it would be only an additional reason to go back to the old plain plugin page.

**Comment by mrclay** [comment]
My fixes haven't been accepted https://github.com/Elgg/Elgg/pull/10665

**Comment by iionly** [comment]
The issue with the site getting stuck might be a matter of a lack of patience on my side. At least it seems that the cache rebuilding works correctly (resulting in the site not getting stuck), if I wait longer after enabling/disabling a plugin (wating longer than the spinner is displayed), it might work. If someone could try to reproduce the issue it might prove me guess right or wrong. If it's a matter of waiting until the cache is flushed, would it be possible to disable the click event on other plugins' buttons during this time (similar to the issue of links opening a lightbox not working correctly before the lightbox AMD module is fully loaded).

**Comment by mrclay** [comment]
A maybe good enough solution #10744.

**Comment by jdalsem** [comment]
Merged #10744... good enough for now i guess
