### ISSUE TITLE
Apache 2.4 BC issue with htaccess entry

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10713]
I've updated my test/development server today. While I had Apache 2.4 before already the new version installed now seems to behave slightly different with regards to one aspect of BC (possibly the old Apache had access_compat built-in while the new one hasn't).

Resulting issue is that due to the lines
```
<FilesMatch "(nginx|htaccess).dist">
	order allow,deny
	deny from all
</FilesMatch>
```
there's a fatal error resulting in any Elgg instance no longer working.

On Apache 2.4 the lines would have to be
```
<FilesMatch "(nginx|htaccess).dist">
	Require all denied
</FilesMatch>
```
with the authz_core module loaded by Apache.

Do we even still need these lines with the *.dist templates no longer in the root directory by default?

If the entry in .htaccess is still needed, would it make sense to change the lines to have gain BC and also stay in line with the new Apache 2.4 syntax? Then might work with the following (modified code from .htaccess of phpBB)
```
# With Apache 2.4 the "Order, Deny" syntax has been deprecated and moved from
# module mod_authz_host to a new module called mod_access_compat (which may be
# disabled) and a new "Require" syntax has been introduced to mod_authz_host.
# We could just conditionally provide both versions, but unfortunately Apache
# does not explicitly tell us its version if the module mod_version is not
# available. In this case, we check for the availability of module
# mod_authz_core (which should be on 2.4 or higher only) as a best guess.
<IfModule mod_version.c>
	<IfVersion < 2.4>
		<FilesMatch "(nginx|htaccess).dist">
			order allow,deny
			deny from all
		</FilesMatch>
	</IfVersion>
	<IfVersion >= 2.4>
		<FilesMatch "(nginx|htaccess).dist">
			Require all denied
		</FilesMatch>
	</IfVersion>
</IfModule>
<IfModule !mod_version.c>
	<IfModule !mod_authz_core.c>
		<FilesMatch "(nginx|htaccess).dist">
			order allow,deny
			deny from all
		</FilesMatch>
	</IfModule>
	<IfModule mod_authz_core.c>
		<FilesMatch "(nginx|htaccess).dist">
			Require all denied
		</FilesMatch>
	</IfModule>
</IfModule>
```

**Comment by jdalsem** [comment]
> Do we even still need these lines with the *.dist templates no longer in the root directory by default?

i guess not...

**Comment by iionly** [comment]
On second thought I don't know if removal is an option. An admin might create .htaccess manually by copying htaccess.dist to root the then create .htaccess as copy of htaccess.dist (or proceed in the same way for nginx). Then the *.dist file could remain in root. I also don't know if during automatic installation / rewrite test a copy of htaccess.dist could remain in root unintentionally.

Question is: if the lines in htaccess.dist are not to be removed, is adding the whole block that checks Apache version etc. is an option? Or should we just add the alternative lines for Apache 2.4 commented out with some explaining comment asking the admin to modify .htaccess on his own if necessary?

**Comment by beck24** [comment]
I think we can safely remove these

**Comment by iionly** [comment]
PR in https://github.com/Elgg/Elgg/pull/10816.

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10816.
