### ISSUE TITLE
Elgg 2.3: More menu items no longer sorted alphabetically

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10737]
Before Elgg 2.3 the site menu items listed under "More" were listed in alphabetical order. But now this is no longer the case. It's rather difficult to find the menu item you are looking for this way.

**Comment by mrclay** [comment]
The function _elgg_site_menu_setup() hasn't been touched, so maybe the menu builder isn't auto-sorting submenus anymore.

**Comment by mrclay** [comment]
The More menu is sorted in 2.1 and unsorted in 2.2.

**Comment by mrclay** [comment]
Problem introduced by my menu work  https://github.com/Elgg/Elgg/commit/38ecfc6ba9b3aa431e9b553651e26c3dd10bbc18

**Comment by mrclay** [comment]
I think the solution is to set this default to "text": https://github.com/Elgg/Elgg/commit/38ecfc6ba9b3aa431e9b553651e26c3dd10bbc18#diff-779d610a08fcf4ba2c48347218b2db91R70

**Comment by iionly** [comment]
Sorted by "text" by default sounds right to me.

**Comment by mrclay** [comment]
@hypeJunction @jdalsem Does this solution sound right to you, too?

**Comment by hypeJunction** [comment]
The solution looks right, but we do not need to change the default at some point. It makes no sense sorting it by text, 99% of menus are sorted by priority.

**Comment by mrclay** [comment]
Well changing to priority was an accidental BC break in 2.3. We could either change back or leave default and add "text" sort to the site menu specifically.

**Comment by mrclay** [comment]
> 99% of menus are sorted by priority

Was this true in a stock install of 2.2?

**Comment by hypeJunction** [comment]
> Was this true in a stock install of 2.2?

No. For BC, we need to keep them sorted by text.

**Comment by iionly** [comment]
I think menus were sorted by text in previous versions of Elgg.

I also think it should be fixed (sorted by text) not only for BC reasons. I don't see the reason for sorting menus by priority by default as most menu items don't get registered with a specfic priority in the first place and even more important it's just a pain in the ass if you have a menu with more than 2 or 3 items that seems (by the look of it) unsorted. It's just difficult to easily find the menu item you are looking for if they are not sorted by text.

**Comment by mrclay** [comment]
PR #10756
