### ISSUE TITLE
views_simplecache creation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10731]
While working on #10637, I realized that `/views_simplecache` is not created at any given point in time. We should perhaps add API to 1) create the directory, 2) ensure it's created after install and when caches are flushed

**Comment by mrclay** [comment]
It's created here https://github.com/Elgg/Elgg/blob/2.3/engine/classes/Elgg/Application/CacheHandler.php#L149

**Comment by jdalsem** [comment]
CLosing this as, like @mrclay said, it is created. @hypeJunction if you think that it still goes wrong in certain cases, let us know

**Comment by hypeJunction** [comment]
I still see notices in simpeltests. This needs to be created during installation.

**Comment by jdalsem** [comment]
Closing this as i can't find any notices anywhere about this. Would need to have notice details before reopening.
