### ISSUE TITLE
Elgg 2.3 and master: WARNING: Metadata and annotations store only integers and strings. boolean given

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10738]
This warning shows up in the log on Elgg 2.3 and master (even on a site without any 3rd party plugins).

It seems the warning is logged at least for two things:

- liking something,
- 1 minute notification cronjob seems also to through this warning somewhere in processing notifications to be sent.

**Comment by iionly** [comment]
setRead() function in SiteNotification class of Site Notifications plugin saved read state as boolean value. I think this is the cause of the warnings.

PR in https://github.com/Elgg/Elgg/pull/10739.

**Comment by mrclay** [comment]
I don't get a notice for likes.

**Comment by iionly** [comment]
It's also due to a (site) notification sent when liking that a warning is logged. So, it seems to me it's only site notifications causing a warning after all.

**Comment by iionly** [comment]
No more warnings due to https://github.com/Elgg/Elgg/pull/10788. So, closing.
