### ISSUE TITLE
Widget settings menu item & empty form

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10746]
Settings menu item is registered even if the form is empty.

**Comment by jdalsem** [comment]
personally i do not find it that disturbing...

**Comment by hypeJunction** [comment]
It's a consistent issue we have with forms. Plugin settings form etc. Bad UX, IMO.

**Comment by jdalsem** [comment]
Plugin settings menu items only show up when needed though... or are you referring to USER plugin settings... that was fixed a while back. But removing the settings menu item for the widget should be easy peasy... will however conflict with my ajax loaded widget edit form in Widget Manager... but that can be fixed i guess

**Comment by hypeJunction** [comment]
Plugins settings menu item show even if the form body is empty.
