### ISSUE TITLE
Rename elgg/ckeditor.js to eliminate need for CKEDITOR_BASEPATH

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10758]
CKeditor only gets confused because we load a file named `ckeditor.js` and it isn't what it expects. Renaming our wrapper to something like `elgg-ckeditor.js` would eliminate the need for worrying about this global constant being set early enough.

**Comment by jdalsem** [comment]
@mrclay was this also fixed by https://github.com/Elgg/Elgg/pull/10874?

**Comment by mrclay** [comment]
Yep.
