### ISSUE TITLE
Test with Apache MultiViews on

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10757]
We've had to work around MultiViews before (#8806), but on one site this has caused issues serving simplecache from a symlink, particularly around the `/cache/0/default/elgg/ckeditor` directory, probably because MultiViews would want to stick `.js` at the end of that, which is a valid view file.

See https://github.com/Elgg/Elgg/issues/10724#issuecomment-276216744

This could be a bigger problem if we build view trees like:

* component.js
* component/resource.gif

**Comment by jdalsem** [comment]
Not going to add tests for this. MultiViews is not enabled by default and is a bad setting to have for sites like Elgg (with rewrite rules). It is causing us issues. #12998 will make sure it is disabled on more sites that allow it to be disabled. The rest of the cases will need to examine their logs (and will find that we try to disable an apache option that can not be disabled) and act on that.
