### ISSUE TITLE
Avatar Cropper breaks randomly

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#10762]
With a js error that $.imgAreaSelect is not a function

![screen shot 2017-02-10 at 3 43 44 pm](https://cloud.githubusercontent.com/assets/738363/22848222/d2d095a6-efa7-11e6-8777-63243de107fd.png)

Looks like it's due to ui.avatar_cropper.js being loaded _before_ jquery.imgareaselect.js, and there may be some race condition where jquery.imgareaselect.js isn't fully loaded yet before elgg.avatarCropper.init fires

**Comment by iionly** [comment]
Would this issue explain https://github.com/Elgg/Elgg/issues/10686?

**Comment by beck24** [comment]
I don't believe so, completely unrelated I would think

**Comment by jdalsem** [comment]
Closing as we will replace cropper functionality in Elgg 3.1 and this currently is hard to reproduce
