### ISSUE TITLE
group profile page breadcrumbs not working as expected

### ISSUE THREAD

**Issue by YanweiJiang** [Elgg/Elgg#10777]
In /views/default/resources/groups/profile.php, there is a line of code trying to push a breadcrumb without link using elgg_push_breadcrumb($group->name), but apparently it's not working. group name breadcrumb is not showing on group profile page. I tried elgg_push_breadcrumb($group->name, 'example.com'), then the group name will show up. Currently the only workaround is to add  elgg_push_breadcrumb($group->name) twice which is suggested by community member RvR. 
please refer to: https://elgg.org/discussion/view/2611849/how-to-add-a-breadcrumb-without-link

**Comment by hypeJunction** [comment]
It's intended. At some point we decided to pop the last non-link crumb as it duplicates the page title. You can unregister the hook if you want them back

**Comment by YanweiJiang** [comment]
Ok. I see. Thanks.
