### ISSUE TITLE
elgg_normalize_url() is mangling URLs

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10771]
some menu items have an invalid href... others look good. Don't know if other menus are affected. Could be a major issue or maybe just a small issue in developer tools

**Comment by mrclay** [comment]
I see the issue and I'm worried. Some menu item hrefs are like `http://site-url/http://site-url/admin/develop_tools/inspect?inspect_type=Plugin Hooks`

**Comment by mrclay** [comment]
elgg_normalize_url() is converting `http://site-url/admin/develop_tools/inspect?inspect_type=Plugin Hooks` to `http://site-url/http://site-url/admin/develop_tools/inspect?inspect_type=Plugin Hooks`.

**Comment by jdalsem** [comment]
Not related to 2.3.1... 2.3.0 also has the issue

**Comment by jdalsem** [comment]
Using a space in the url is causing elgg_normalize_url to misinterpret the url... maybe this was already always the case... as a literal space is not valid (according to the regexes used in elgg_normalize_url). But nothing changed in this function over the last years... maybe recent changes in menu service caused this issue? Maybe MenuItem->getHref() previously returned a 'save' url...

**Comment by hypeJunction** [comment]
Also this https://github.com/arckinteractive/elgg_hybridauth/issues/24

**Comment by mrclay** [comment]
I'd suggest auto-enconding the URLs as necessary.

**Comment by mrclay** [comment]
Oh, I see the problem is that FILTER_VALIDATE_URL is completely broken. http://php.net/manual/en/function.filter-var.php#104160

**Comment by jdalsem** [comment]
Can't we revert the change?

**Comment by mrclay** [comment]
See #10772.
