### ISSUE TITLE
Security docs page - needs to say framework uses bcrypt

### ISSUE THREAD

**Issue by samsch** [Elgg/Elgg#10778]
The [design/security](http://learn.elgg.org/en/stable/design/security.html) page in the docs still says that Elgg uses MD5 and a salt for password hashing.

I almost turned away from considering the framework, but fortunately I dug a bit deeper to find that the docs themselves are out of date.

This page (and any others with similar info) needs to be updated to describe the password system as using password_hash/bcrypt.

If there are other out of date security topics within the docs, they should be updated as well.

**Comment by hypeJunction** [comment]
Could you post the URLs of pages that need to be updated?

**Comment by mrclay** [comment]
He did. http://learn.elgg.org/en/stable/design/security.html

**Comment by hypeJunction** [comment]
He mentions "other out of date" pages. So, if there are actually any, URLs would help.

**Comment by mrclay** [comment]
@samsch Thanks for bringing this to our attention. 
@hypeJunction We can search for "MD5" and "salt".

**Comment by samsch** [comment]
Thanks for responding so quickly!

@hypeJunction I've only just started into the Elgg docs today, so I'm not sure if there are other places in the docs which touch on security. Sorry for being vague.

**Comment by mrclay** [comment]
PR #10779
