### ISSUE TITLE
notifications: overview of entities you get notifications from

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10786]
Currently we only show a list of groups you have a notifications relationship with... but this could also be shown for all entities. 

Plugins that add notifications relationships should not have to add their own management for enabling/disabling in the notifications plugin views

**Comment by hypeJunction** [comment]
Further, it's a wrong assumption that we only retrieve subscriptions for the container. We need to also populate subscriptions for the entity itself.

**Comment by jdalsem** [comment]
yep... adding that would probably be a breaking change as plugins probably do something like that themselves.

**Comment by jdalsem** [comment]
This list will be unmanageable long (and thus pretty useless). Not going to add this to core. Email notifications will get a direct mute link and a potential custom page to configure notifications about the entity related to the notification. On entity pages a menu item will be added to control subscriptions.
