### ISSUE TITLE
elgg-plugin.php documentation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10782]
We need to better document elgg-plugin.php. Perhaps an example with all registration types with extended examples. I now need to dig into code to see what parameter names 'actions' uses.

**Comment by jdalsem** [comment]
i believe it is correctly documented now, but not centralized, but where it is used... maybe we should move the documentation to a central location and point to that location when it is appropriate.

**Comment by hypeJunction** [comment]
Fixed with plugin bootstrap PR
