### ISSUE TITLE
Missing handler _elgg_user_get_subscriber_ban_action() for 'get', 'subscriptions' plugin hook

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10789]
I think the handler registration got added in https://github.com/Elgg/Elgg/commit/a7ab8ecbc86030adf44b623e1e600d229c7c640f#diff-91eb827ce659848eb08c231fd84757ba.

Has the addition of the handler registration been a mistake or was it intended and forgetting to add also the handler was the mistake?

**Comment by jeabakker** [comment]
there is no registration for `_elgg_user_get_subscriber_ban_action` anywhere in core, there is a registration for `_elgg_user_get_subscriber_unban_action` and that function is defined.

Ban notification is sent directly as described here https://github.com/Elgg/Elgg/blob/master/engine/lib/users.php#L799

**Comment by iionly** [comment]
@jeabakker it seems the missing handler issue I had reported got fixed in https://github.com/Elgg/Elgg/commit/e167092dd3d1a4f393b0f74ed3f6c166e14b75d4#diff-91eb827ce659848eb08c231fd84757ba by renaming  _elgg_user_get_subscriber_ban_action to _elgg_user_get_subscriber_unban_action in the handler registration.
