### ISSUE TITLE
All text bold in radio input on usage of elgg_view_field()

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10780]
Label text can/should be bold. But all the options text is also bold and I don't think that's right. It looks "Uugh!" at least to me.

**Comment by hypeJunction** [comment]
Agree. I usually change that in my themes

**Comment by jdalsem** [comment]
i also would like to remove the 110% of labels..

**Comment by mrclay** [comment]
Make labels easier to remove via plugin, but I think they're critical for out-of-the-box accessibility. Anecdotally, Amazon uses them and placeholders are [troublesome for keyboard nav](http://mentalized.net/journal/2010/08/05/dont-use-placeholder-text-as-labels/) (may be an issue on mobile, too).

**Comment by mrclay** [comment]
@iionly Can you put a PR together? @hypeJunction Do you have public code we could grab from?

**Comment by hypeJunction** [comment]
This can be done during theme rewrite. We will just stop styling ``label`` and only style ``.elgg-field-label``

**Comment by iionly** [comment]
I don't know if I can fix this, because I'm not sure I fully understand the underlying problem yet.

What I see is that elgg_view_field() styles the WHOLE input div output with label styling and not only what's between the label tags. Why? I don't understand this yet.

If you take a look at the theme sandbox forms page, there's still one elgg_view_input() example input shown where '#label' and 'label' is used. I think this example gives the output as it should look like.

The removal of label styling in CSS (and only keep .elgg-field-label styling) seems to fix the look of the inputs when using elgg_view_field. But is this really the only way to fix it? If anyone wants to use the label tag directly without using any Elgg input field API functions - and expecting the label text to be formatted like it used to be (bold, 110%) - it will no longer be the case. And if he tries to "fix" this by adding label styling to CSS it will again result in unintended changes in the look of elgg_view_field() inputs.

Isn't there a way to restrict the label/.elgg-field-label styling when using elgg_view_field explicitely to the label text only?

**Comment by hypeJunction** [comment]
Use the existing API or style your own elements. I don't want to think about people doing things their own way and expecting things to look pretty

**Comment by iionly** [comment]
May I suggest https://github.com/Elgg/Elgg/pull/10813 instead? No need to drop label styling.

**Comment by hypeJunction** [comment]
I commented on the PR. For usability having a label element is a must.

**Comment by iionly** [comment]
New PR in https://github.com/Elgg/Elgg/pull/10815.

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10815
