### ISSUE TITLE
ElggLogCache has no size limiting

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10787]
If developers screen logging is on, (and I'm reading this right) even cron scripts will capture all log messages in ElggLogCache.

I'm not sure what's a reasonable limit for messages on screen and which to include, the first N, the last N, or keep both and put "..." in the middle.

**Comment by hypeJunction** [comment]
Could this be written to disk and then read when the time to render comes?

**Comment by mrclay** [comment]
Yes, though we'd have to register for shutdown to wipe the file in case a page wasn't sent. But who would find a page with several hundred log messages useful?

**Comment by mrclay** [comment]
If this isn't causing #10781 I'm happy to just close it for now.

**Comment by hypeJunction** [comment]
I do sometimes, when I am digging through queries trying to understand what's happening. But yes, too much junk.
