### ISSUE TITLE
Creating metadata adds to memory footprint on each occurrance

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#10781]
Sample code:

    $time = time();
    $users = new ElggBatch('elgg_get_entities', ['type' => 'user', 'limit' => false]);
    $count = 0;
    foreach ($users as $user) {
        $count++;
        $user->_test_md = $time;

        if ($count == 1 || !($count % 25)) {
            error_log("memory usage: " .  memory_get_usage(true));
        }
    }

Tested on Elgg 2.3.1 
Output: https://gist.github.com/beck24/5de3570decf56c0223bd9fbc54c138c1

Without the metadata write, memory increases as the entity cache fills up then levels off, with the metadata writes memory continues to increase.  For large databases this creates OOM fatals for upgrade scripts and any long running processes that deal with metadata.

**Comment by hypeJunction** [comment]
Entity cache never grows over 100 items, we should clear metadata cache when items are popped from entity cache

**Comment by hypeJunction** [comment]
Metadata cache is flushed correctly. The problem is the metastrings cache, which never gets flushed. In your example you use variable time, so new metastrings are created each second. Don't care fixing it in 2.3, since metastrings are going away in 3.0.

**Comment by beck24** [comment]
The variable time is created outside of the loop, so it's writing the same value to each user

**Comment by hypeJunction** [comment]
All user metadata is loaded nevertheless and ends up in the metastrings cache

**Comment by beck24** [comment]
Ah, right

**Comment by mrclay** [comment]
I bet we could ditch the metastring ID cache with no problems.

**Comment by beck24** [comment]
So repeating the test without writing metadata, but still reading metadata (which means it's loaded/cached) does not increase memory.  So I think there's something different at play here.

**Comment by beck24** [comment]
I'm having a hell of a time tracking this down, it doesn't appear to be related to metastring cache

**Comment by hypeJunction** [comment]
Are working with a vanilla install? Could it be site specific? A plugin event handler?

**Comment by beck24** [comment]
It's MFP - which is really vanilla as-is, but they have a huge database.  I'm testing it locally with *all* plugins disabled except for my test plugin that just runs this test code.  There's no plugin event handlers, any event handlers firing are core.

**Comment by beck24** [comment]
I've tried clearing entity cache, metadata cache in the loop, caching is turned off but I've logged the metastrings cache just in case and it's using the nullcache.  As far as I can tell it's when the metadata is retrieved from the database and the row is passed to construct a new ElggMetadata object.  Even though that's not used anywhere (only the metadata id is returned from the update function).  Somewhere in that process something is adding to memory and not being removed.

**Comment by beck24** [comment]
I know for sure it's not site-specific as I've seen the symptoms in other large sites when trying to do full indexes in solr.  This one is just larger and more problematic as it's affecting other scripts.  Solr is just an annoyance if it maxes out memory, you can just restart it from where it left off.  These are symptoms though, this will affect any such script - and I'm thinking upgrades.

**Comment by jdalsem** [comment]
dbquery cache also disabled?

**Comment by beck24** [comment]
Yep - it's capped at 50 queries by default but I did comment it out just-in-case

**Comment by mrclay** [comment]
Could something be internally logging events, particularly `create, metadata`?

**Comment by mrclay** [comment]
What if you reduced this to 150 or so? https://github.com/Elgg/Elgg/blob/2.3.1/engine/lib/system_log.php#L205

**Comment by beck24** [comment]
Steve with the only cache I didn't check!

So it looks like the system_log cache isn't actually caching anything at all.  It's adding to a static var that it calls a cache, but doesn't do anything with it.  The size of that var is capped at 500, but each iteration is sent to ```execute_delayed_write_query($query);``` regardless.

There is no limit to the number of delayed queries

https://github.com/Elgg/Elgg/blob/2.3.1/engine/classes/Elgg/Database.php#L534

So, where best to limit this?  I don't think we should limit delayed queries as there could be something really important in there.  The log I don't see as important (to be honest, after 7 years of using Elgg I've never found it useful).  I think intention was to just drop the log entries if the cache exceeds 500?  What's the solution I can safely get into 2.3?

**Comment by mrclay** [comment]
The $log_cache static var is just for avoiding dupe log entries, but it's not quite right because it doesn't use $object_type in the key. No big deal.

Spitballing: a switch to execute log queries immediately instead of queuing them. Do this automatically for cron requests.

**Comment by topdog08** [comment]
Hi guys, just checking in on this.  One of my sites with 150,000 users plus is hitting this quite a bit, but hoping not to have to wait for 3.0 for a solution.  I'd be fine with a switch under advanced settings?

**Comment by mrclay** [comment]
@topdog08 AFAIK the last place @beck24 hasn't checked is the delayed query queue. We queue log writes so page generation takes higher priority AND so they don't flush the query cache, but this isn't as important in cron requests. So one thing to try is to disable logging completely during this particular operation, which wouldn't require an Elgg change.

**Comment by iionly** [comment]
Turning off logging with https://elgg.org/plugins/1441338 might help (at least for testing/debugging)?

**Comment by topdog08** [comment]
Hi guys, I can confirm I've had the No Logging plugin installed and active last two years and Logging is shown as Turned Off under Advanced Settings.  So, it's just the other part of this problem I need to fix.

**Comment by jdalsem** [comment]
Not sure where to pick this up. If this is reproducible in Elgg 4 please let us know
