### ISSUE TITLE
No verification email sent on change of email address

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10794]
The success message says "New email address saved. Verification is requested."

But it seems there's no email sent for verification.

**Comment by iionly** [comment]
I don't care anymore about that.

**Comment by mrclay** [comment]
Seems serious.

**Comment by jdalsem** [comment]
i care too

**Comment by rohit1290** [comment]
Can we map this issue with elgg 3.x
This is one of the critical check and should be a part of 1st release of elgg 3.

**Comment by jdalsem** [comment]
Not going to be part of Elgg 3.0 but i can add it to the roadmap of 3.1
