### ISSUE TITLE
multiple OR's in delete/disable queries are inefficient

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10798]
Current on delete/disable we select where `container_guid = <guid> OR owner_guid = <guid> OR site_guid = <guid>`

This is a very costly query as MYSQL can not optimize multiple OR's that much.

If we change this query we can optimize a lot... a LOT. One of our production databases sees a dramatic fall from 1500ms to 0ms. This massive gain is also noticeable on test/dev databases, going from 50ms to 0ms.

What is the optimisation? There are 2 options:

1) execute the query 3 times (once for container, once for owner and once for site)

or

2) use a UNION subquery to select the entities (select entities with container_guid = <guid> UNION select entities with owner_guid = <guid> UNION where site_guid = <guid>)

My preference is for number 1. There is no noticeable difference between the performance of 1 and 2. 1 is just less fancy SQL.

We can also skip the `site_guid = <guid>` for non-site entities...

**Comment by jdalsem** [comment]
This problem of course gets bigger when you recursively delete data, like a user, page (with subpages) or a group (#10770)

**Comment by jdalsem** [comment]
Sample query: `SELECT DISTINCT e.* FROM entities e WHERE ((e.container_guid = 16812232 OR e.owner_guid = 16812232 OR e.site_guid = 16812232) AND e.guid != 16812232) AND (e.site_guid IN (1)) AND ((1 = 1)) ORDER BY e.time_created desc LIMIT 0, 100;`

Just change it to 3 times:
``SELECT DISTINCT e.* FROM entities e WHERE ((e.container_guid = 16812232) AND e.guid != 16812232) AND (e.site_guid IN (1)) AND ((1 = 1)) ORDER BY e.time_created desc LIMIT 0, 100;``

**Comment by jdalsem** [comment]
Technically you could also drop `distinct` and `order_by` for these queries... but that has hardly effect on the query. It doesn't even matter if there are results or not...

**Comment by hypeJunction** [comment]
What about `guid IN (owner_guid, container_guid, site_guid)`? Probably doesn't matter all that much

**Comment by jdalsem** [comment]
thats not the same query...

**Comment by hypeJunction** [comment]
`<guid> IN (owner_guid, container_guid, site_guid)` = `container_guid = <guid> OR owner_guid = <guid> OR site_guid = <guid>`

**Comment by jdalsem** [comment]
tested... is even slower :)

**Comment by jeabakker** [comment]
fixed with #10808
