### ISSUE TITLE
elgg_get_river() doesn't work as expected when using the 'view' attribute

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10791]
Due to deprecation of elgg_delete_river() I've switched to the recommended new way ("Use elgg_get_river() and call delete() on the returned item(s)") in several plugins. Mistake of me: I've not checked the parameters of elgg_get_river() and just changed the code to use an ElggBatch with elgg_get_river() fetching the river items with basically the same parameters as used before in elgg_delete_river(). And it seemed to work.

BUT!

It seems using the 'view' attribute doesn't return exactly the river items I want to have but MORE.

Example:
```
$view = "river/user/default/profileupdate";

$river_items = new ElggBatch('elgg_get_river', array(
	'view' => $view,
	'action_type' => 'update',
	'subject_guid' => $user->guid,
	'limit' => false,
));
```
did not only the river items with the view river/user/default/profileupdate" but ADDITIONALLY items with views "river/user/default/profileiconupdate" and "river/object/poll/update" that I surely do NOT want to delete here.

It seems to work with a custom where clause:
```
$view = "river/user/default/profileupdate";

$river_items = new ElggBatch('elgg_get_river', array(
	'action_type' => 'update',
	'subject_guid' => $user->guid,
	'limit' => false,
	'wheres' => array("rv.view = \"$view\""),
));
```
But that's not really what you think of using in the first place.

So, bug or what?

And btw, there's a public usable replacement of elgg_delete_river() necessary urgently both for Elgg 2.3 and 3.0. It's just annoying that you either get the deprecated warning all the time (2.3 will get LTS so will be around for a while), or use the private _elgg_delete_river() or need to use much too much custom code to replace elgg_delete_river() by other means.

**Comment by mrclay** [comment]
Ouch, `views` and `action_types` should've been added to elgg_get_river() before we deprecated that. A few options:

1. If view(s)/action_type(s) options are passed to elgg_get_river(), issue a warning that this feature is not yet implemented, and add a docs page showing how to uses `wheres`. (my preference)
2. Un-deprecate elgg_delete_river(). Authors will have to re-code for 3.0.
3. Add support as a bugfix in 2.3.2.

**Comment by mrclay** [comment]
Actually, adding the feature is super trivial.

**Comment by hypeJunction** [comment]
I see us getting rid of view column eventually and using hooks instead, so let's just not add any API that would be building upon it. Option 1 sounds good to me.

**Comment by mrclay** [comment]
PR #10793

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/issues/10791.
