### ISSUE TITLE
[developer tools] inspect menu can crash

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10796]
When the inspect menus page is draw the menus are created and fed fake entities. This can cause issues if the menu hooks expect 'working' entities.

I encountered this problem with https://github.com/ColdTrick/dataroot_browser. I call `$edl = new \Elgg\EntityDirLocator($user->getGUID());` but the `$user` is fake and doesn't have a guid, thus crash.

I check that i have a user, but don't check if the user has a guid, because this should always be the case.

Maybe feed existing entities to the menus? https://github.com/Elgg/Elgg/blob/2.3/engine/classes/Elgg/Debug/Inspector.php#L237-L256

for `$user` we could use loggedin user. Maybe we can find a solutions for the others as well

**Comment by hypeJunction** [comment]
Menus for logged in user vs other user will vary considerably.

**Comment by hypeJunction** [comment]
And at any rate, there is too much context sniffing in menu hooks, so those are inaccurate at best.

**Comment by jdalsem** [comment]
so it should be just as good as to pass the logged in user (instead of a fake, unsaved, user)

**Comment by jdalsem** [comment]
not going to fix this in core... the issue has been taken care of in the dataroot_browser plugin
