### ISSUE TITLE
Search: no way to navigate to full post if item has no title

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10795]
There is nothing clickable to navigate to the full item if the found entity has no title

**Comment by jdalsem** [comment]
So... that should have been taken care by the entity ... or what do you think?

**Comment by hypeJunction** [comment]
Plugins already have to add a million views to make things work. I want one less thing to worry about. Search plugin should use getDisplayName at least.

**Comment by jdalsem** [comment]
yeah, if it does not use getDisplayName() yet, it should... that is the max in my opinion. No need for fancy fallback logic in search
