### ISSUE TITLE
cron/run is unreliable

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10803]
i would not rely on cron/run at this moment as the way the cron determines which ts to check/run is wrong. It uses the endtime of the previous run to determine if execution is needed. I would like to see it determined on some modulo time() instead. 

Currently (because of the bug mentioned here: #10797) it works, but if that bug is fixed it will break cron/run.

If a hourly cron finishes at 10:30 (started at 10:00) the next hourly will be 11:30. I expect (based on cron/hourly) that cron/run should kick the hourly cron at 10:00 and the next one at 11:00.

Instead of determining the need to run a specific interval based on the ts in the database it should determine it based on the start ts of the cron.

**Comment by jdalsem** [comment]
also 1st day of month is not available in cron/run as it uses a fixed offset

**Comment by jdalsem** [comment]
minutes will probably also skip 1 every 2 minutes with current implementation (`$now > $deadline` should probably work better with `>=`)

**Comment by mrclay** [comment]
This was added in #8916 but it's still not in the docs. I suggest we just cut it, which solves all the surrounding issues including the worry @beck24 mentioned [here](https://github.com/Elgg/Elgg/pull/8916#issuecomment-138330431). We could bring it back if @sh3llc0de would like to iron out the issues and finish docs.

**Comment by mrclay** [comment]
PR #10907
