### ISSUE TITLE
Ajax login is annoying

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10805]
I don't know why this was necessary, but I find it frustrating that there is a preloader, then it disappears with a system message and then I don't know what's happening and suddenly the page is reloading.

**Comment by jdalsem** [comment]
it makes sense for errors

**Comment by hypeJunction** [comment]
It would make sense for errors on all forms, but we don't do it. I'd like to roll back to using a normal submit.

**Comment by mrclay** [comment]
For errors, new UX is fine. For success, I like that the refresh feels faster (no redirect blocking page draw). I think it just needs a tweak: Keep the spinner active and don't show the success msg until the final page (re)load. I'll work on it.

**Comment by mrclay** [comment]
PR #10807, also fixes #10774.
