### ISSUE TITLE
Drop From email?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10806]
Should we drop support for From field in emails and always use the site email/name?

**Comment by jdalsem** [comment]
no

**Comment by hypeJunction** [comment]
Do you use your site installation to send email on behalf of somebody else?

**Comment by mrclay** [comment]
> send email on behalf of somebody else?

GitHub's makes sense: generic From address but with sender's name, then Reply-To to specify reply target.

**Comment by jeabakker** [comment]
> Do you use your site installation to send email on behalf of somebody else?

yes, our newsletter plugin uses it
