### ISSUE TITLE
elgg/lightbox#resize should respect max options

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10810]
Resize should respect maxWidth and maxHeight options provided with the toggle

**Comment by jdalsem** [comment]
The colorbox resize feature does not respect maxHeight/Width. These max sizes are only used when initializing the colorbox. Resize will always resize based on the content or based on provided width/height parameters. If you want to limit to some max sizes, you will need to do the calculations on your own (and pass them to the resize function).
