### ISSUE TITLE
Rethink breadcrumbs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10818]
Breadcrumbs are difficult to follow.

I think they should always originate from the container:

Name of the group (/groups/profile/$guid)
Blog (/blog/group/$guid)
Title of the blog (/blog/view/$guid)
Action (/blog/edit/$guid)

Name of the user > Calendar > Event name

Friends > Bookmarks

User > Settings > Notifications > Personal

**Comment by mrclay** [comment]
SGTM

**Comment by jdalsem** [comment]
Just as a remark... this approach will remove all ALL links, as the container will be the top level. I can live with that as the site menu items should provide access to the /all links



> Friends > Bookmarks

Shouldn't this be
Name of the user > Friends > Bookmarks?

This approach sounds good to me

**Comment by hypeJunction** [comment]
I don't think users should be seeing other users' friends' content page. Friends would always refer to my friends.

**Comment by jdalsem** [comment]
As an admin you can see other users friends

**Comment by hypeJunction** [comment]
You can deduct the user from the owner block

**Comment by jdalsem** [comment]
Ok... new scenario; what about filters...

Name of user > Groups > Owned

or just 
Name of user > groups
(and the selected tab shows you the filter)


Hmm when thinking about it, there will probably never be the need for a filter as part of the breadcrumb... nevermind.

**Comment by hypeJunction** [comment]
https://github.com/hypeJunction/hypeCrumbs

**Comment by propertunist** [comment]
i just tested hypeCrumbs - i like the idea, but it didn't change the layout of the videolist breadcrumbs for some reason

**Comment by hypeJunction** [comment]
It's not a universal solution, as plugins tend to do a lot of weird stuff with routes

**Comment by hypeJunction** [comment]
With proper breadcrumbs, it would make sense to get rid of stupid page titles, like A group with a super long name that has nothing to say's files.

**Comment by propertunist** [comment]
i think it's fine to just truncate long names
