### ISSUE TITLE
ElggEntity::delete() can cause infinite loops

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10827]
As a result of #10808, entities being deleted recursively are no longer unique, so with entities that might have overlapping owner/container this results in an infinite loop.

**Comment by hypeJunction** [comment]
https://github.com/Elgg/Elgg/pull/10826/commits/f9bb644903fcaa44880c5232a1f4a4d55685fa68

**Comment by jdalsem** [comment]
ah, so no bug in 2.3, just something in master

**Comment by hypeJunction** [comment]
It could still be an issue. A contains B, B contains C, C owns A.

**Comment by hypeJunction** [comment]
Need more tests for edge cases. Can't tell offhand.

**Comment by jdalsem** [comment]
so currently you only 'think' it is broken, or do you have cases to reproduce a problem?

**Comment by hypeJunction** [comment]
I thought it was looping, but it was the site_guid. But yes I see potential for an infinite loop

**Comment by mrclay** [comment]
All the merges I've done end up with infinite loops in the simpletests. I propose we revert #10808 from 2.3, do the merge, and reconsider it for master.

**Comment by hypeJunction** [comment]
Agree. I don't know why tests are passing in 2.3, we probably have more coverage in master

**Comment by jdalsem** [comment]
Closed this issue in favor of #10836 as previous comments are not related to the problem
