### ISSUE TITLE
Retire elgg-coding-standards repo

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10829]
After #10826 is merged, we should add docs that standards are include in core from 3.0 onwards

**Comment by jdalsem** [comment]
don't like it that much... what if plugins like to depend on the same coding standards?

**Comment by hypeJunction** [comment]
Well, redo the PR then. I am fed up with them

**Comment by jdalsem** [comment]
we can merge the PR and change it back to using a repo afterwards
