### ISSUE TITLE
Update Elgg sniffs and upgrade to PHPCS 2.8

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10825]
We are currently in the limbo due to vulnerabilities in earlier PHPCS versions. Even though it's a dev dependency and probably carries no risk, it prevents us from running builds and tests.

**Comment by hypeJunction** [comment]
Need to move sniffs added in https://github.com/Elgg/Elgg/pull/10826 to elgg-coding-standards, update composer commands, and rerun composer-lint against master

**Comment by mrclay** [comment]
@hypeJunction @jdalsem Can we recap our next steps here? As of #10831 the build issue is solved on 2.3 (AFAIK). My plan is to now re-issue a clean PR of just the merge from #10826. Once in, I'll make another PR with the new CS/linting in #10826. Just trying to not combine too many steps.

**Comment by hypeJunction** [comment]
I have turned off my laptop, so not doing anything else today

**Comment by mrclay** [comment]
Enjoy your vacation :)

**Comment by mrclay** [comment]
- [ ] re-establish function checking in 2.3. I accidentally removed this, see https://github.com/Elgg/elgg-coding-standards/commit/cdb2f2b39ede62bebd2c7b55570123bcbeb372fe#commitcomment-21374165
