### ISSUE TITLE
Ajax activate plugin and jQuery sortable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10820]
After replacing the plugin list, sortable needs to be reinitialized

**Comment by mrclay** [comment]
2.3 needs merged into master.

**Comment by hypeJunction** [comment]
Not happening until we resolve phpcs issues

**Comment by mrclay** [comment]
Whoa do we need to merge more often.

**Comment by jdalsem** [comment]
This is no longer an issue
