### ISSUE TITLE
Is the change in ACL's regarding to members being entities instead of users intended?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10839]
In https://github.com/Elgg/Elgg/commit/ec40d1a5d3f121189ab7c158b9f61307badd28d2 it has been changed that ACL can have any entity as a member. It is no longer limited to users. Is that intended? The functions and table columns suggest it should be a user.

/cc @hypeJunction

**Comment by hypeJunction** [comment]
I don't have an opinion either way. I see use cases for adding entities to access collection, but we would need to add layers for it to be of any use.

**Comment by jdalsem** [comment]
before we decide to 'allow' entities as part of ACL members, should we restore the check that the provided guids need to be users in master?

**Comment by hypeJunction** [comment]
It uses ege* so just add type param

**Comment by jdalsem** [comment]
But addUser/removeUser does not have a check

**Comment by hypeJunction** [comment]
If it expects an entity, I would change the typehint. Otherwise, yeah, validate
