### ISSUE TITLE
Blog last edited time uses time created

### ISSUE THREAD

**Issue by ravencloud** [Elgg/Elgg#10838]
Elgg/mod/blog/views/default/forms/blog/save.php

When editing a blog, the last saved time displays the created time of the original blog or if the status was changed and then edited, the time of the status change.  The revisions all show the same last edit time as the time created (or status changed). We are using 2.1.3, but it looks like it would still be an issue for 2.3.
Steps to reproduce:
-Create a blog.
-Save the blog.
-Edit the blog.
-Save the blog.
-Edit the blog.
-View the last saved time field. 

Expected results: To show the time from the first edit.
Actual results: Shows the time of creation (or if the status was changed, when the status was changed).

**Comment by hypeJunction** [comment]
I have fixed that here https://github.com/Elgg/Elgg/pull/10674/files. Don't care about it so much to fix separately in 2.3, maybe someone else does.
