### ISSUE TITLE
Bootstrap overhaul

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10857]
Ismayil made a heroic start on this in #10853 and I've saved the branch in https://github.com/mrclay/Elgg-leaf/tree/bootstrap

**Comment by gjsieben** [comment]
That is a really good concept. We should just whack it, get it done, and launch it with 3.0 (or next release).

**Comment by hypeJunction** [comment]
I needed a solid framework to work with, because I just feel ashamed of shipping projects with core UI, so I have build a new theme from scratch using Bulma.io (less expensive than bringing in all the Bootstrap JS) 
https://github.com/hypeJunction/hypeUI

**Comment by hypeJunction** [comment]
I am already transitioning a second project to hypeUI, and it works pretty good so far. Must easier to work with, easy to modify listings via hooks. I'd be willing to put in a couple of days in the next weeks to get into to core, to never see core theme again. There will be some breaking changes, but nothing major. Just a different navigation concept.

**Comment by mrclay** [comment]
I'm excited to see this take form. I propose, instead, the rest of the team try out the plugin to get a feel for it and what changes it's going to impose. In the very short term, I think the move to core would only slow you down, but I trust your instincts here that this should replace Aalborg.
