### ISSUE TITLE
master: lots of missing English translation notices

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10851]
When system cache is off, these are on every request.

**Comment by mrclay** [comment]
More notices

```
NOTICE: PHP (errno 8): 2017-03-23 19:47:15 (UTC): "Trying to get property of non-object" in file /mod/groups/start.php (line 606)
NOTICE: PHP (errno 8): 2017-03-23 19:47:15 (UTC): "Trying to get property of non-object" in file /mod/groups/start.php (line 606)
NOTICE: PHP (errno 8): 2017-03-23 19:47:15 (UTC): "Undefined variable: container" in file /views/default/output/access.php (line 49)
NOTICE: PHP (errno 8): 2017-03-23 19:47:15 (UTC): "Trying to get property of non-object" in file /views/default/output/access.php (line 49)
```

**Comment by mrclay** [comment]
We're trying to use translations in the plugin file, before they're loaded.
https://github.com/Elgg/Elgg/commit/a26c5d5a3baf4fe03805f77312ac964414d74564#diff-102a43ef071885b781657b4fc24b2c77R12 /cc @jdalsem

**Comment by jdalsem** [comment]
Should work https://github.com/Elgg/Elgg/blob/master/engine/classes/ElggPlugin.php#L841

Is system cache influencing the flags?

**Comment by mrclay** [comment]
registerEntities() also hits the static cache. Moving language registration above it was the simple fix.

**Comment by mrclay** [comment]
PR #10868
