### ISSUE TITLE
Add warning if metastring exceeded column length

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10861]
Without `STRICT_TRANS_TABLES` MySQL truncates metastrings to fit the `text` column. This is problematic when metastring's integrity is important, e.g. a long serialized string. At least a warning would help debug issues that arise from that.

**Comment by mrclay** [comment]
We can let the student's commit go in but I feel devs should self-police their size if storing serializations. There are several tables we'd need to watch and if the MySQL feature is on the end-user would get uncaught exceptions.

**Comment by mrclay** [comment]
An API that took a column definition and spat out a limit in bytes/chars would be handy. Would be great if INFORMATION_SCHEMA could have that.

**Comment by hypeJunction** [comment]
Self-policing would have to take place on each metadata write/update, which is a bit too much. Truncating metadata serialized or not without a warning, IMO, is not very developer friendly

**Comment by mrclay** [comment]
We also need to watch annotations, private settings, object description, config. As MD are loaded with entity I usually don't put anything potentially big there.

**Comment by hypeJunction** [comment]
As of late, I am leaning toward introducing my own DB tables for anything that won't be searched against. This particular issue popped up in payments API, which stores serialized order information as metadata. I should have gone with a custom table right away. Will need to rewire it at some point. For now, I had to implement some magic to explode and then glue the string back together.

**Comment by mrclay** [comment]
@hypeJunction Not a total solution but see #10864.

**Comment by hypeJunction** [comment]
I saw it, and yes it would make the situation better, especially if @jdalsem 's work to migrate title/desc to metadata is merged.
But for my use case, I still lean towards adding a custom DB table with a blob to hold the serialized data.

**Comment by iionly** [comment]
Would it make sense (maybe separately from the current PR) to also display warnings to users if they try to make postings exceeding the max length? I would image this case might be not unusual (copy+paste some document in a blog etc.). I thought this case to be the reason that triggered this issue as someone had asked about the maximum length of postings on the community site at the time the issue was opened. But maybe just a coincidence then.
