### ISSUE TITLE
Proposal: Schema improvement without upgrade

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10863]
We keep putting these off, let's just make these changes in the installer and provide a script for sites who want to upgrade a site:

- TEXT -> LONGTEXT
- utf8 -> utf8mb4

We shouldn't have any code logic that depends on the impact of these.

**Comment by jdalsem** [comment]
why not create an upgrade script for this?

**Comment by mrclay** [comment]
Feel free, but we've abandoned that effort several times.

**Comment by mrclay** [comment]
Weird, I swear someone made a PR for utf8mb4 but I can't find it.

**Comment by mrclay** [comment]
utf8mb4 was attempted in #7128.

**Comment by mrclay** [comment]
Drat. We need to know the encoding early. https://github.com/Elgg/Elgg/pull/7128/files#diff-3723ea54b26170bce8ca842694dc0facR159

**Comment by mrclay** [comment]
PR #10864
