### ISSUE TITLE
example htaccess isn't ready for PHP7

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10862]
https://github.com/Elgg/Elgg/blob/master/install/config/htaccess.dist#L42-L55 only applies to PHP5 not 7.

**Comment by mrclay** [comment]
Can you be more specific? Where is this documented?

**Comment by jeabakker** [comment]
the `.htaccess` currently has the check `IfModule mod_php5.c` but for php7 it should check `IfModule mod_php7.c`

I encountered this on my local computer when i changed the upload limit, but it wasn't applied. Until I changed the module name.

**Comment by mrclay** [comment]
I guess we have to have both then?

**Comment by jeabakker** [comment]
i think soo
