### ISSUE TITLE
custom colorbox options are transfered to other clicks

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10876]
If custom lightbox options are set on a link (using `data-colorbox-opts`) these settings are maintained for other lightbox binds.

example:
- have 1 link with a custom setting `width: '200px'`
- have 1 link with no custom settings
- click the 2nd link, it'll open with the correct width (depends on the content of the link)
- click the first link (should open a lightbox with width 200px), this is ok
- click the 2nd link it'll still open a lightbox with a width op 200px. Not ok

**Comment by mrclay** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10877.
