### ISSUE TITLE
route:rewrite hook provides falsely identifiers/segments

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10883]
Example: Private Profiles plugin (https://elgg.org/plugins/1860995) and Add New Items plugin (https://elgg.org/plugins/1301890) both in use.

The Private Profiles plugin uses "route:rewrite", "profile" plugin hook to grant/deny access to profile pages and the Add New Items plugin adds a popup menu to the topbar allowing quick access to add content forms (blogs, pages, files etc.).

Problem is that "route:rewrite", "profile" hook is falsely triggered when selecting one of the menu items of the Add New Items plugin popup menu while being on a profile page.

For example when selecting to add a new blog posting the user is forwarded to site.url/blog/add/<userid>. The "route:rewrite", "profile" hook should get triggered at all in this case. But it does get called with the invalid url site.url/profile/blog/add/<userid>.

**Comment by mrclay** [comment]
The route:rewrite hook is called for every request. I don't understand how we'd make it work any different.

**Comment by iionly** [comment]
route:rewrite hook getting called on every request is not the problem.

The problem is when registering a handler for example for the "profile" identifier and then the handler getting called when it shouldn't get called, e.g. request being "blog/add/username" made from the profile page and getting "profile/blog/add/username" when checking identifier and segments in the handler callback...

**Comment by mrclay** [comment]
I suspect the error is [$elgg_path is not defined](https://github.com/propertunist/elgg-add_items_menu/blob/2.0/views/default/add_items_menu/popup.php#L27), so the link is relative and starts with "profile/".

**Comment by mrclay** [comment]
Actually that line should get normalized, it's the onclick handler URL that's probably wrong.

**Comment by iionly** [comment]
Yeah, I also noticed that $elgg_path is not defined. I also tried without onclick and with absolute url both in the popup.php and in start.php where the menu item is registered. But the issue remained.

Do you think that it's an issue that should be / needs to be fixed in the Add New Item plugin and not in Elgg core? With the Private Profiles plugin I feel like being inbetween without being actually involved in the issue...

**Comment by propertunist** [comment]
aha, yes, the variable $elgg_path was not being set to anything in my plugin. that was the cause of the issue. thanks guys

**Comment by iionly** [comment]
Closing the issue here then.
