### ISSUE TITLE
Using 'get_sql', 'access' plugin hook can result in fatal errors with custom sql queries

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10884]
Example: Private Profiles plugin (https://elgg.org/plugins/1860995) uses the 'get_sql', 'access' plugin hook for hiding public activity of users from logged-out site visitors by adding a custom ands:
```php
$dbprefix = elgg_get_config('dbprefix');
$table_alias = $params['table_alias'] ? $params['table_alias'] . '.' : '';

$guid_column = elgg_extract('guid_column', $params, 'guid');
$owner_guid_column = elgg_extract('owner_guid_column', $params, 'owner_guid');

// Exclude entities owned by users who have chosen to keep their activity to members only
$value = self::ACCESS_LOGGED_IN;
$return['ands'][] = "NOT EXISTS (SELECT 1 FROM {$dbprefix}private_settings WHERE entity_guid IN ({$table_alias}{$guid_column}, {$table_alias}{$owner_guid_column}) AND name='plugin:user_setting:private_profiles:user_activity_setting' AND value='$value')";
```
This seems to work fine if no custom aliases are used in queries. But it seems there can be problems with custom queries where custom joins/wheres are used resulting in fatal errors / DatabaseExceptions most likely due to a faulty query resulting of the additional ands.

In one case the problem occured with the Event Calendar plugin not yet using Elgg API functions for a query yet and I could fix that by rewriting the query using elgg_get_entities_from_metadata().

But in the search plugin in search_tags_hook() elgg_get_entities_from_metadata() isn't used intentionally ("for better performance"). Not sure what to do in this case. Is there a way to get the handler code working regardless of the query it adds up to. Or is it necessary (an option) to fix the problem in search plugin code to prevent the error from occuring in this case (and maybe in any other using the 'get_sql', 'access' plugin hook)?

**Comment by mrclay** [comment]
It would help to see an example of a failed query.

**Comment by iionly** [comment]
'An exception occurred while executing

'SELECT COUNT(DISTINCT e.guid) as total FROM elgg_entities e
JOIN elgg_metadata md on e.guid = md.entity_guid
JOIN elgg_metastrings msn on md.name_id = msn.id
JOIN elgg_metastrings msv on md.value_id = msv.id
WHERE  (msn.string IN ("tags","event_tags","location","interests","skills") AND msv.string = 'test' AND ((md.access_id IN (2,-5)) AND (md.enabled = 'yes' AND NOT EXISTS (SELECT 1 FROM elgg_private_settings WHERE entity_guid IN (md.guid, md.owner_guid) AND name='plugin:user_setting:private_profiles:user_activity_setting' AND value='members')))) AND  (e.site_guid IN (1)) AND ((e.access_id IN (2,-5)) AND (e.enabled = 'yes' AND NOT EXISTS (SELECT 1 FROM elgg_private_settings WHERE entity_guid IN (e.guid, e.owner_guid) AND name='plugin:user_setting:private_profiles:user_activity_setting' AND value='members')))':


SQLSTATE[42S22]: Column not found: 1054 Unknown column 'md.guid' in 'where clause'\n\nQUERY: SELECT COUNT(DISTINCT e.guid) as total FROM elgg_entities e  JOIN elgg_metadata md on e.guid = md.entity_guid  JOIN elgg_metastrings msn on md.name_id = msn.id  JOIN elgg_metastrings msv on md.value_id = msv.id  WHERE  (msn.string IN ("tags","event_tags","location","interests","skills") AND msv.string = 'test' AND ((md.access_id IN (2,-5)) AND (md.enabled = 'yes' AND NOT EXISTS (SELECT 1 FROM elgg_private_settings WHERE entity_guid IN (md.guid, md.owner_guid) AND name='plugin:user_setting:private_profiles:user_activity_setting' AND value='members')))) AND  (e.site_guid IN (1)) AND ((e.access_id IN (2,-5)) AND (e.enabled = 'yes' AND NOT EXISTS (SELECT 1 FROM elgg_private_settings WHERE entity_guid IN (e.guid, e.owner_guid) AND name='plugin:user_setting:private_profiles:user_activity_setting' AND value='members')))


PARAMS: Array\n(\n)\n' in /xxx/engine/classes/Elgg/Database.php:445\nStack trace:\n#0 /xxx/engine/classes/Elgg/Database.php(386): Elgg\\Database->executeQuery('SELECT COUNT(DI...', Object(Doctrine\\DBAL\\Connection), Array)\n#1 /xxx/engine/classes/Elgg/Database.php(226): Elgg\\Database->getResults('SELECT COUNT(DI...', NULL, true, Array)\n#2 /xxx/engine/classes/Elgg/Database/EntityTable.php(658): Elgg\\Database->getDataRow('SELECT COUNT(DI...')\n#3 /xxx/engine/lib/entities.php(327): Elgg\\Database\\EntityTable->getEntities(Array)\n#4 /xxx/mod/search/search_hooks.php(295): elgg_get_entities(Array)\n#5 [internal function]: search_tags_hook('search', 'tags', Array, Array)\n#6 /xxx/engine/classes/Elgg/PluginHooksService.php(52): call_user_func_array('search_tags_hoo...', Array)\n#7 /xxx/engine/lib/elgglib.php(827): Elgg\\PluginHooksService->trigger('search', 'tags', Array, Array)\n#8 /xxx/mod/search/views/default/resources/search/index.php(232): elgg_trigger_plugin_hook('search', 'tags', Array, Array)\n#9 /xxx/engine/classes/Elgg/ViewsService.php(370): include('/xxx...')\n#10 /xxx/engine/classes/Elgg/ViewsService.php(306): Elgg\\ViewsService->renderViewFile('resources/searc...', Array, 'default', true)\n#11 /xxx/engine/lib/views.php(514): Elgg\\ViewsService->renderView('resources/searc...', Array)\n#12 /xxx/mod/search/start.php(62): elgg_view_resource('search/index')\n#13 [internal function]: search_page_handler(Array, 'search')\n#14 /xxx/engine/classes/Elgg/Router.php(100): call_user_func('search_page_han...', Array, 'search')\n#15 /xxx/engine/classes/Elgg/Application.php(436): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#16 /xxx/engine/classes/Elgg/Application.php(384): Elgg\\Application->run()\n#17 /xxx/index.php(8): Elgg\\Application::index()\n#18 {main}, referer: http://blackbox.home.nil/xxx/blog/owner/xxx

**Comment by mrclay** [comment]
At line https://github.com/Elgg/Elgg/blob/2.3.2/mod/search/search_hooks.php#L283, I think we also need to pass in `'guid_column' => 'entity_guid',`. Try that and let me know if it works.

**Comment by mrclay** [comment]
PR #10885

**Comment by iionly** [comment]
#10885 seems to work fine. No errors anymore and I get the expected search result.

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10885.
