### ISSUE TITLE
River table schema missing subtype key

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10896]

**Comment by jdalsem** [comment]
why do you think this is missing? Did you do some profiling?

**Comment by hypeJunction** [comment]
It's not in the schema

**Comment by jdalsem** [comment]
but why **should** it be in the schema?

**Comment by hypeJunction** [comment]
You need to define the key for it to be a key

**Comment by jdalsem** [comment]
Was it used then somewhere? Or referenced?

**Comment by hypeJunction** [comment]
You want to have the index defined when using `elgg_get_river()` with subtype set.

**Comment by jdalsem** [comment]
> You want to have the index defined when using elgg_get_river() with subtype set.

So there is a performance gain? Any evidence? Or blue eyes only...

Just adding keys could also decrease performance

**Comment by hypeJunction** [comment]
It exists on all other tables. Whatever, I don't care about it enough to have to deal with interrogation

**Comment by jdalsem** [comment]
it is no interrogation, i just wanted to clarify why you needed this change as there was no 'reason' mentioned in the issue description

**Comment by hypeJunction** [comment]
I don't need this change. As says in the issue description subtype index is missing from schema, which looks like an omission. I can't tell you if it is or it isn't because nobody documented anything. I don't want to spend any more time on this.
