### ISSUE TITLE
Idea: Elgg should be bootable without DB or dataroot

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10916]
This would allow us to use Elgg (e.g. our nice walled garden theme) for installing Elgg, or displaying exception pages.

Dataroot could default to an in-memory filesystem, with an API to detect if this were the case.

Without DB, system would just boot without any plugins and fail if the DB were touched. An installer could just use a DBAL connection directly.

**Comment by mrclay** [comment]
Building an installer and allowing a full app to recover from missing settings/DB down are somewhat different use cases and imply different design.

I think I'll start building a trivial Slim app, and refactor until I can borrow views, forms, menus, and translation to start with.

**Comment by jdalsem** [comment]
I believe this was fixed by #11092 @mrclay

**Comment by mrclay** [comment]
The [NoDataElgg](https://github.com/Elgg/Elgg/blob/afb5473c208b58467e6629eb4741f4d93fcafb34/engine/classes/Elgg/Project/NoDataElgg.php) class and [example usage](https://github.com/Elgg/Elgg/tree/afb5473c208b58467e6629eb4741f4d93fcafb34/no-data-demo). I need to re-test these and roll them into a plugin.
