### ISSUE TITLE
Adopt saner code style rules

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10926]
Don't require `@return void`.
Don't require alignment of `@param` names.
Allow `@param` description on the following line (like Drupal).

Any other annoying rules we can toss?

**Comment by hypeJunction** [comment]
It's starting to drive me nuts. We should at least skip rules that can be autofixed, and run lint-fixer periodically

**Comment by jdalsem** [comment]
leaving this as is for now
