### ISSUE TITLE
Fatal error when activating default widget > dashboard> Group Activity

### ISSUE THREAD

**Issue by olairmarcos** [Elgg/Elgg#10929]
Elgg version 2.3.2 :  Instalation from Softaculous
Fatal error when activating default widget > dashboard> Group Activity
![2017-04-20_114811](https://cloud.githubusercontent.com/assets/8938718/25242142/04ba8060-25cf-11e7-8e6b-fb5e9fefe5b3.png)

![2017-04-20_115038](https://cloud.githubusercontent.com/assets/8938718/25242157/111b3d40-25cf-11e7-87bb-257be0f0199e.png)

Elgg version 2.2.3 : Instalation from Softaculous
Works normal without error

Test in server Arvixe e A2hosting host.

Thanks for listening.

**Comment by iionly** [comment]
Got broken by https://github.com/Elgg/Elgg/commit/7644d838f713e5734126adcc8578cb199afbb4e6

Problem is in mod/groups/views/default/widgets/group_activity/edit.php with getGroup() method. This method is only available for ElggUser but on the default widgets settings page the page owner is the ElggSite entity.

Possible fix could be replacing
```php
// once autocomplete is working use that
$groups = elgg_get_logged_in_user_entity()->getGroups(array('limit' => 0));
```
with
```php
// Widget owner might not be a user entity (e.g. on default widgets config page it's an ElggSite entity)
$owner = $widget->getOwnerEntity();
if (!($owner instanceof ElggUser)) {
	$owner = elgg_get_logged_in_user_entity();
}
$groups = $owner->getGroups(['limit' => false]);
```
Don't know if there's a more elegant way to fix it.

**Comment by mrclay** [comment]
@iionly would you like to send a fix? ;)

**Comment by iionly** [comment]
@mrclay https://github.com/Elgg/Elgg/pull/10930

**Comment by jdalsem** [comment]
#10930 fixed it
