### ISSUE TITLE
Fatal error in PDO for array values from plugin settings

### ISSUE THREAD

**Issue by tanimcseku** [Elgg/Elgg#10921]
Hello,
I got in issue while submitting array values from plugin settings page. I got following fatal error after submission: 
PDO::quote did not return surrounding single quotes. 
and the exception type is: DatabaseException Object.
I have by passed that issue by writing an action hook to override the array to string and finally store in db.

**Comment by mrclay** [comment]
What PHP & DB versions are you using?

**Comment by mrclay** [comment]
This is part of a [nasty hack](https://github.com/Elgg/Elgg/blob/2.3.2/engine/classes/Elgg/Database.php#L699) that only works if PDO::quote behaves as I expected.

**Comment by tanimcseku** [comment]
My PHP version is: 7.0.10 and MySQL version is: 5.7.14

**Comment by tanimcseku** [comment]
Yes, your expectation is right.

**Comment by mrclay** [comment]
See if you can debug $quoted at this line: https://github.com/Elgg/Elgg/blob/2.3.2/engine/classes/Elgg/Database.php#L701

**Comment by tanimcseku** [comment]
Yes, I have debugged that line and get following result: 

vendor\elgg\elgg\engine\classes\Elgg\Database.php:701:string '''' (length=2)

**Comment by hypeJunction** [comment]
I don't see the problem. Plugin settings are not designed to be stored as arrays

**Comment by tanimcseku** [comment]
I was using:

**Comment by tanimcseku** [comment]
I was using: 
	  echo elgg_view_field(array(
			'#type' => 'select',
			'name' => 'params[name][]',
			'options_values' => $array,
			'multiple' => true,
			'value' => $values,
	  ));
and got that exception. @hypeJunction

**Comment by hypeJunction** [comment]
As I say, plugin settings are not designed to store arrays. I suppose this exception is not the one that needs to be thrown, but that doesn't change the fact that Elgg's private settings storage is dumber than metadata storage (I have been long advocating for losing private settings table and migrating everything to metadata, only plugins and widgets use it and it's a needless overhead).

**Comment by mrclay** [comment]
Okay, so Database::sanitizeString needs to reject arrays with an error and maybe cast everything else to string?

@tanimcseku You'll need to serialize your value before save. Simplest would be to make your own `<plugin_id>/settings/save` action.

**Comment by tanimcseku** [comment]
Okay. I have resolved that by writing an action hook to override the array into comma separated string and again in my working page or settings page by converting that string input into array using a comma as tokenizer.
