### ISSUE TITLE
Elgg 2.3: no html editor when editing a discussion reply

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#10936]
When editing a discussion reply you get no ckeditor / longtext input form but just a normal text input form.

**Comment by mrclay** [comment]
Not sure why @hypeJunction changed this https://github.com/Elgg/Elgg/commit/100bd412ca00a1369873c7a33fb6d63f21e2f656#diff-fd9a3a4f41c5ac407295ce2066d33832R20

**Comment by hypeJunction** [comment]
Can't remember. Possibly the visual editor switch supposed to do the job?

**Comment by iionly** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10937.
