### ISSUE TITLE
Fatal error in elgg version 2.3.2 in DatabaseSessionHandler

### ISSUE THREAD

**Issue by tanimcseku** [Elgg/Elgg#10943]
Dear Concern,
During checking latest stable elgg version i.e. 2.3.2 I got following fatal error:

Fatal error: Class Elgg\Http\DatabaseSessionHandler contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (SessionHandlerInterface::open, SessionHandlerInterface::read) in C:\wamp64\www\elgg-2.3.2\vendor\elgg\elgg\engine\classes\Elgg\Http\DatabaseSessionHandler.php on line 12

Note that the fatal error is found in php version 7.0.10, but it is fine 5.6.25

**Comment by mrclay** [comment]
Trying running `composer install` when you switch PHP versions.

**Comment by mrclay** [comment]
The source file definitely implements the method: https://github.com/Elgg/Elgg/blob/2.3.2/engine/classes/Elgg/Http/DatabaseSessionHandler.php

**Comment by tanimcseku** [comment]
Yes, I have also seen that the source file is implemented perfectly. Then why for php version 7.0.10 it throwing that error?

**Comment by mrclay** [comment]
Try restarting apache. http://stackoverflow.com/a/38116182

**Comment by jdalsem** [comment]
If there is more info available let us know. Closing this for now as it sounds like a installation specific problem
