### ISSUE TITLE
Admin menu takes too long to set up

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10947]
When this happens clicking a dropdown item just reloads the page, starting the problem over again. A case could be made for somehow sending this functionality inline in case elgg.js/AMD breaks.

**Comment by mrclay** [comment]
Clicking "Settings" before JS setup could just reload the page with all of the Settings submenus fully expanded.

**Comment by jdalsem** [comment]
This is not an admin menu specific problem. There could be various things on a page that block or delay javascript from executing. Maybe setting the href of those parent items to false could fix this specific problem. Speeding up javascript execution is a different discussion. Closing this as it is not specifically related to the admin menu.
