### ISSUE TITLE
RSS views have /serve-file URLs that require cookies

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10950]

**Comment by hypeJunction** [comment]
I never understood usefulness of RSS in an access controlled system. IMO core shouldn't even be supporting out of the box

**Comment by jdalsem** [comment]
This is a similar problem as access bound data so marking it as a duplicate of https://github.com/Elgg/Elgg/issues/3643. Removal of RSS in core can be discussed here https://github.com/Elgg/Elgg/issues/11021
