### ISSUE TITLE
Memcache: cache more metadata

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10965]
Now that these are access-free, they can be more freely cached, and this can probably all be done in \Elgg\Cache\MetadataCache.

**Comment by propertunist** [comment]
@mrclay  what metadata are you referring to by the word 'these'? ;)

**Comment by hypeJunction** [comment]
All of it. Metadata will no longer be accessed controlled in 3.0

**Comment by mrclay** [comment]
Feel free to cherry-pick https://github.com/Elgg/Elgg/commit/c3f38e084a4250a3f704ba767e237b487a68f590

**Comment by propertunist** [comment]
i see, ok - thanks for clarifying

**Comment by jdalsem** [comment]
@mrclay was this already tackled by you recently? or does it still need work

**Comment by mrclay** [comment]
In 01074610db25ef99eb35cd4f993d097380baa983
