### ISSUE TITLE
Form submission issue with disabled submit button

### ISSUE THREAD

**Issue by ravneet-core** [Elgg/Elgg#10969]
If the submit button is disabled and the form containing CKEditor textarea is submitted with Javascript then it is submitted with blank textarea values.

**Comment by hypeJunction** [comment]
How do you submit the form? Forms with disabled submit buttons are not meant to be submitted, so I don't think it's a bug. I'd try something like:

```js
define(function(require) {
   var Ajax = require('elgg/Ajax');
   var ajax = new Ajax();

   $(document).on('submit', '.my-form', function(e) {
      e.preventDefault();
      var $form = $(this);
      $form.find('[type="submit"]').prop('disabled', true);
      ajax.action($form.attr('action'), {
           data: ajax.objectify($form),
      }).done(function(response) {
           // do stuff
      });
   });
});
```

**Comment by ravneet-core** [comment]
I want to stop multiple submissions on a clicking the submit button for any form in whole elgg site. So to achive this I tried writing the code as

`$('.elgg-button[type=submit]').on('click', function() {
	$(this).attr('disabled', true);
	this.form.submit();
});`

It works fine except that it submits blank value for the textareas which are using CKEditor like in comment form.

**Comment by mrclay** [comment]
Instead listen for the form submit event, set a 0ms timeout and disable the button there.

**Comment by jdalsem** [comment]
this is a timing issue... ckeditor writes its values to a hidden input. I believe it does this on losing focus and/or on form submit. Maybe you are preventing ckeditor from doing this and are thus ending up with empty values.

Like @mrclay suggested you could try and move the disabling of the buttons to the form submit event. I think the timeout is not needed btw.

Closing this issue as it is not specifically Elgg related.
