### ISSUE TITLE
System cache: overhaul to write PHP scripts and try memcache

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10966]
Instead writing PHP scripts like `<?php return [...];` would allow APC gains and of course memcache would be ideal, though the system cache would need to recompute/resave on demand but doesn't seem hard.

**Comment by jdalsem** [comment]
I don't see a problem with the current implementation and i am unsure about the performance gains. Please provide a PR and some figures that prove the performance gain if you want to discuss this further.
