### ISSUE TITLE
Chaining .fail()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10978]
It seems that there is no way to add a custom fail handler on top of the default one with elgg/Ajax calls.

**Comment by mrclay** [comment]
Seems to work for me in 2.3.

```js
ajax.action('fake').fail(function () {
  // executed after the default error handler
  console.log(arguments);
});

ajax.action('fake', {
  error: function () {
    // replace default handler
  }
}).fail(function () {
  // this is still called
  console.log(arguments);
});
```

**Comment by hypeJunction** [comment]
So, this works, BUT it replaces the default .fail() handler so action system messages are not displayed.

**Comment by hypeJunction** [comment]
Never mind. All works fine.
