### ISSUE TITLE
Document tweak for Elgg 2.x in subdirectory on Nginx

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10979]
The config always dumps the whole path into `$_GET['__elgg_uri']`. Fine if you're at the root. In a subdirectory you must do something like this:

```php
// before \Elgg\Application::index(), strip leading subdirectory from path
$subdir = '/sites/elgg/';
if (!empty($_GET['__elgg_uri']) && 0 === strpos($_GET['__elgg_uri'], $subdir)) {
	$_GET['__elgg_uri'] = substr($_GET['__elgg_uri'], strlen($subdir) - 1);
}
```

**Comment by jdalsem** [comment]
does this still apply to your latest config changes?

**Comment by mrclay** [comment]
No. This is only a 2.x issue. master uses Symfony's request the way it was designed.

**Comment by jdalsem** [comment]
Not going to update the 2.3 docs just for this special case.
