### ISSUE TITLE
(Bug) Failed to Create Cache Path

### ISSUE THREAD

**Issue by ObeeWanKenobee** [Elgg/Elgg#10977]
http://127.0.0.1/install.php
Step 1: OK
Step 2: Done
(Here the headache starts.)
Step 3: Fatal Error. (Failed to Create Cache Path)
Step 4: Cant create site.
Step 5: Failed to Create Cache Path.
->vendor/tedivm/stash/src/Stash/Utilities.php
->vendor/tedivm/stash/src/Stash/Driver/FileSystem.php
Did everything said in your Docs but still can't find why. Any help will be appreciated. 😄

**Comment by gnh1201** [comment]
I found how to solve this problem!I
```
chown -R myuser:mygroup /tmp/elgginstaller
chown -R myuser:mygroup /var/lib/php/sessions
```

**Comment by hypeJunction** [comment]
We should probably cherry-pick this in after all: https://github.com/Elgg/Elgg/pull/12082/commits/f6f53ba858bad9644fd58212dd4e24a0ca03ac7f

**Comment by ChengxiX** [comment]
I met the same issue now.
