### ISSUE TITLE
jquery version hasn't been updated in elgg v2.3 documentation

### ISSUE THREAD

**Issue by oseg** [Elgg/Elgg#10972]
jquery version hasn't been updated in elgg v2.3 documentation:
https://github.com/Elgg/Elgg/blob/2.3/docs/intro/development.rst

jQuery version should not be v1.11.0 but v2.2.4

**Comment by smellems** [comment]
`Bundled with Elgg are jQuery 1.11.0, jQuery UI 1.10.4, jQuery Form v20140304, jQuery jeditable, and jQuery UI Autocomplete.`

In Elgg 2, jQuery is no longer "bundled" with Elgg, but installed using Composer.  Should change to better reflect how Javascript dependencies are installed.

**Comment by oseg** [comment]
Ok, but what about users who download elgg v2.3.3 from the "stable release" link of page https://elgg.org/about/download ?

I had a quick look into https://github.com/Elgg/Elgg/blob/2.3.3/composer.json and noticed that jquery version is supposed to be v2.1.4. But I got v2.2.4 when I call jQuery.fn.jquery()...

**Comment by mrclay** [comment]
Docs are out of date, indeed. But the lock file determines version: https://github.com/Elgg/Elgg/blob/2.3.3/composer.lock#L11

**Comment by oseg** [comment]
Thanks for the clarification about composer (I am not familiar with it yet)

**Comment by nschonni** [comment]
There is also a copy of 1.4 https://github.com/Elgg/Elgg/blob/master/mod/pages/vendors/jquery-treeview/lib/jquery.js

**Comment by jeabakker** [comment]
fixed with #11053
