### ISSUE TITLE
Message Board Owner index page breadcrumb returns boolean and is an owner check necessary?

### ISSUE THREAD

**Issue by cleverthings** [Elgg/Elgg#10988]
In the Message board owner index page \mod\messageboard\views\default\resources\messageboard\owner.php I have two changes:
The first sanity check may not be necessary, but I have added a forward if not owner - is this already checked with a gatekeeper somewhere???

$page_owner = elgg_get_page_owner_entity();
if (!$page_owner) {
    forward('', '403');

And to fix the breadcrumbs from returning a boolean, I changed this line - but I'm new to elgg and there might be a better way:
// elgg_push_breadcrumb($page_owner->name, $page_owner->getURL());
elgg_push_breadcrumb($page_owner->name, "messageboard/owner/$page_owner->username");

**Comment by mrclay** [comment]
First change is welcomed, but the second isn't a great idea. Groups can be page owners and won't have that profile URL.

**Comment by cleverthings** [comment]
Yikes! That's why I haven't been submitting any pull requests. ;)  I have to retest and see why I made that change in the first place. All I wrote was it was returning a boolean instead of the url.  I'll test again and provide more info if there is a problem. Thanks!

**Comment by mrclay** [comment]
Don't hesitate to send PRs. It has no cost to us and is easier to issue feedback on.

**Comment by jdalsem** [comment]
This has been improved as part of https://github.com/Elgg/Elgg/commit/11ee1ed647d1bec627e3283329abd248b8f717cf
