### ISSUE TITLE
Remove RSS from core

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11021]
@hypeJunction says: "prehistoric technology that Elgg can't deal with gracefully. If there were lists API fin, but all this overhead without any gain in an access controlled system makes no sense"

The functionality is in decent shape (case for moving it to a plugin) but implementation of RSS feeds really needs to be more considered by site owners. Even for blogs the site/entries may be access-controlled.

**Comment by jdalsem** [comment]
With a new config option you can now easily disable the promotion of RSS urls. This can be reopened if someone is willing to provide a PR to discuss.
