### ISSUE TITLE
Cron scripts cannot update existing entities even with ignored access

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#11062]
This is due to the has_access_to_entity() check on the ElggEntity update method.  The has_access_to_entity() check ignores the access setting (for good reason), but this is an unintended side effect.

https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Database/AccessCollections.php#L382

I think has_access_to_entity() should remain as-is, but the update function should only use that if access is not ignored.

**Comment by hypeJunction** [comment]
I don't see any calls to has_access_to_entity() in master that would affect editing permissions.

**Comment by beck24** [comment]
hmm, I'm pretty sure I traced it back to that.  Commented it out and it worked.
Though now that I think about it, that site is on 2.2, and I don't see it in master - maybe it got refactored away since then.  I'll close this for now.
