### ISSUE TITLE
null annotation value

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11079]
It seems that following metadata/annotation refactor, Elgg no longer allows annotations with null value

**Comment by jdalsem** [comment]
did it? do we find this a problem?

**Comment by hypeJunction** [comment]
It seems it was allowed - one of the plugins started throwing (there was a bug :) that was saving null annotations). It was possible, now it's not. I can't think of a use case when you would store null annotations, so I don't care either way

**Comment by jeabakker** [comment]
> I can't think of a use case when you would store null annotations, so I don't care either way

👍
