### ISSUE TITLE
Drop legacy urls plugin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11097]
just as we extracted (and dropped) twitter_api plugin...

lets vote :)

**Comment by hypeJunction** [comment]
I have projects that have been upgraded from 1.8 to 2.x that use it. There is no effective way to rewrite all inline URLs (stored in metadata/description), plus we might need it for 3.0 changes

**Comment by jdalsem** [comment]
we can still remove it to a separate repo but just not bundle it... i see no need to provide it by default

**Comment by jdalsem** [comment]
@hypeJunction with the new route system are you willing to reconsider removing this from core?

**Comment by hypeJunction** [comment]
As long as it's available somewhere, I am fine getting rid of it. Less code to test.

**Comment by jeabakker** [comment]
I updated https://github.com/Elgg/legacy_urls with the state of the plugin as of today
