### ISSUE TITLE
Replace bower 

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11091]
So, looks like bower is deprecated and will no longer be maintained. 

While I like the convenience of using composer asset plugin, it's really just a hack, and we should really move towards a decent asset management framework, i.e. Yarn or Webpack, something that would allow us to run jobs, compile modules etc.

**Comment by jeabakker** [comment]
Found this blog post https://bower.io/blog/2016/using-bower-with-yarn/ which suggests we should switch to Yarn

**Comment by mrclay** [comment]
Yarn is just a faster npm with lock files, and we already use it.

**Comment by hypeJunction** [comment]
Short term solution would be to revive https://github.com/Elgg/Elgg/pull/9831

**Comment by mrclay** [comment]
Isn't this just a matter of moving packages from composer to packages.json and re-aligning view maps?

**Comment by hypeJunction** [comment]
Installation would become a lot more complex, because you would need to have npm installed

**Comment by jdalsem** [comment]
this would add some burden to people installing this from composer... need good updated installation docs on how to do so.... composer installation docs are already very thin

**Comment by jdalsem** [comment]
+ release deployment docs need to be updated

**Comment by mrclay** [comment]
Ah I missed that all our package.json is dev dependencies. Frankly I can't see us escaping that in 2017.

**Comment by mrclay** [comment]
Yep, npm-asset is a fine transitional move.

**Comment by jeabakker** [comment]
the bower assets have been replaced by npm assets. With the use of Asset Packagist as the source for bower/npm packages it was less of a problem, but still it needed to be changed.

fixed in #13282
