### ISSUE TITLE
master: don't try to migrate wwwroot on every request

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11116]
Some sites may have a reason for wanting it empty. So we should only do this in the case that the dataroot was just migrated. @hypeJunction

**Comment by hypeJunction** [comment]
We should just write an empty string

**Comment by mrclay** [comment]
Empty string would cause Request to guess it, with undesirable results for some sites. I think the DB to settings.php copying is fine, just do it once somehow.

**Comment by jdalsem** [comment]
Not happening anymore (for a long time)
