### ISSUE TITLE
bootloader is caching settings of ALL entities should be PLUGINS only

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11124]

**Comment by mrclay** [comment]
BootData [limits plugin settings](https://github.com/Elgg/Elgg/blob/2.3.3/engine/classes/Elgg/BootData.php#L116) to the active plugin GUIDs, also modifying any setting invalidates the boot cache anyway.

**Comment by jdalsem** [comment]
oops.. missed that line
