### ISSUE TITLE
Elgg cannot connect to itself to test rewrite rules properly

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11127]
Getting this message during upgrade:

Elgg cannot connect to itself to test rewrite rules properly. Check that curl is working and there are no IP restrictions preventing localhost connections.

**Comment by hypeJunction** [comment]
You need to modify .htaccess

**Comment by jdalsem** [comment]
about the rewrite rules? did it

**Comment by jdalsem** [comment]
Is there something special about upgrade.php?

**Comment by jdalsem** [comment]
everything else works

**Comment by jdalsem** [comment]
upgrade has its own validation... something you guys missed?

**Comment by jdalsem** [comment]
also getting a very strange forward url after `upgrade.php?upgrade=upgrade`

**Comment by jdalsem** [comment]
adding a wwwroot into the config solved the problem... i am wondering if that is what should be done as the docs in settings.php say it will be sniffed...

**Comment by mrclay** [comment]
Once upgraded, does the site work with wwwroot commented out in settings.php?

**Comment by jdalsem** [comment]
yeah... also before... only problem is during upgrade

**Comment by jdalsem** [comment]
do we even need a rewrite tester during upgrade?

**Comment by mrclay** [comment]
It would be great to get rid of it.

**Comment by jdalsem** [comment]
not having this problem anymore

**Comment by rheman** [comment]
Hi everyone.

I have the same trouble on elgg v3.3.1. I want to upgrade. But I get the following error every time I try.

`Elgg cannot connect to itself to test rewrite rules properly. Check that curl is working and there are no IP restrictions preventing localhost connections.`

The is my apache configuration.

```
 <VirtualHost _default_:443>
                ServerAdmin webmaster@localhost
                ServerName pessek-elggfinal331.com
                DocumentRoot /home/pessek/Documents/WEB/elgg-3-3-1

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                #   SSL Engine Switch:
                #   Enable/Disable SSL for this virtual host.
                SSLEngine on
                SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
                SSLCertificateKeyFile   /etc/ssl/private/ssl-cert-snakeoil.key


     <Directory /home/pessek/Documents/WEB/elgg-3-3-1>
                        Options Indexes FollowSymLinks
                        AllowOverride All
                        Require all granted
      </Directory>

</VirtualHost>
```

Regards,

**Comment by jdalsem** [comment]
@rheman i think this is not the right thread to start a new discussion, but depending on where you upgrade from you might need to update your htaccess file (new rewrite rules). It is mostly enough to copy `/install/config/htaccess.dist` to `.htaccess`
