### ISSUE TITLE
Remove 1.11.2-discussion_plugin upgrade in master

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11136]

**Comment by jdalsem** [comment]
why... it is 1.11... the upgrade does not exist in master anymore am i right?

**Comment by jdalsem** [comment]
oh no... it is still there... shouldn't it be removed?

**Comment by hypeJunction** [comment]
I guess it can be removed. From 2.3 onwards, it would possible to upgrade to pretty much any future version, thanks to db migrations and async upgrades. But yes, 1.11 upgrade is pretty useless.

**Comment by jdalsem** [comment]
1.11 upgrades do not belong in master so removal is the right plan

**Comment by hypeJunction** [comment]
I will remove them

**Comment by jdalsem** [comment]
Removed as part of https://github.com/Elgg/Elgg/commit/7fc9de18f2cbc83547c91ec49e47cc7a13e46775#diff-9561a6228a2e6a8dc7f59b62ac58b402
