### ISSUE TITLE
Create ElggTempFile

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11139]
ElggFile will be created in dataroot, but it would be nice if we could create ElggFiles in a system temp folder. Core has some uses of ElggFile that create temp files in dataroot (for example icon handling). This is a performance issue for dataroots on a network share and also an issue if the tempfiles are not cleaned up (maybe even due to a error).

Creating those files in a local system temp location will solve that problem.

ElggTempFile should return false on `save` and have a `tempfolder` filestore.

Also create an helper function to easily create a tempfile for plugins
`elgg_get_temp_file`. This could then be used by things like export/download actions to create a temp file to concat things in.

**Comment by mrclay** [comment]
```php
$CONFIG->cacheroot = sys_get_temp_dir();
```

**Comment by jdalsem** [comment]
what are you suggesting @mrclay ?

**Comment by mrclay** [comment]
Which problems remain after setting cacheroot to the temp dir?

**Comment by hypeJunction** [comment]
`ElggFile` still expects an owner guid and tries to resolve the directory bucket

**Comment by jdalsem** [comment]
> Which problems remain after setting cacheroot to the temp dir?

the same as ElggFiles have nothing to with cacheroot... only dataroot

Setting cacheroot to a local folder is also a bad idea on multi webserver setups

**Comment by jdalsem** [comment]
> ElggFile still expects an owner guid and tries to resolve the directory bucket

can still do that inside the temp folder

**Comment by jdalsem** [comment]
> ElggFile still expects an owner guid and tries to resolve the directory bucket

not required if we add a custom file store

**Comment by mrclay** [comment]
In general I'd like to direct plugins to use Stash's API somehow and get rid of our crusty APIs.

> Setting cacheroot to a local folder is also a bad idea on multi webserver setups

Why?

**Comment by jdalsem** [comment]
> Why?

Flush caches only flushes on local server... and triggers update on the other... that resets the update_ts... that triggers on another server.... current mechanisme does not flush caches across multiple web servers...

beside that it uses realpaths instead of relative paths in the view path cache that also causes issues

but this is going offtopic

ElggTempFile could be very straightforward...

**Comment by mrclay** [comment]
> but this is going offtopic

Cool, but can you please open an issue to outline what's still problematic about multi-server use? I put a bunch of work into adding cacheroot and it's a bummer if it really didn't help anything.

**Comment by jdalsem** [comment]
> Cool, but can you please open an issue to outline what's still problematic about multi-server use? I put a bunch of work into adding cacheroot and it's a bummer if it really didn't help anything.

This might be perception. I tried to logically explain the error based on current code, but was not able to find something wrong with it. Maybe we should just try to enable it on one of our multiserver setups. Will report back if not working correctly.

**Comment by jdalsem** [comment]
Added in #11320
