### ISSUE TITLE
Remove coverage badge from readme

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11135]
I suggest we remove the coverage badge from readme. It's an inaccurate figure because it doesn't include simpletests, which cover a great share of our API. 
Moving onwards we should bootstrap sqlite on Travis and move simpletests to phpunit. But that's another epic adventure.

**Comment by jdalsem** [comment]
isn't there a way to get the simpletest coverage data?

**Comment by hypeJunction** [comment]
I tried that at some point, but it was pain in the ass

**Comment by jdalsem** [comment]
so your suggestion is to remove the badge until we have simpletests moved to phpunit?

**Comment by hypeJunction** [comment]
Something like that. It creates a bad first impression. I'd rather we add a note in readme about test coverage with a link to scrutinizer.

**Comment by jdalsem** [comment]
Fine by me

**Comment by jdalsem** [comment]
just leaving this as is
