### ISSUE TITLE
input/select still uses input-dropdown class

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11146]
should actually be input-select... should we replace this or just add input-select as a class

for consistency

should we also deprecate the input/dropdown view?

**Comment by hypeJunction** [comment]
Add `input-select`.
`input/dropdown` has been deprecated since before 2.0. We should just remove it.

**Comment by jeabakker** [comment]
> input/dropdown has been deprecated since before 2.0. We should just remove it.

maybe but there was no deprecation warning in view, so devs didn't know

**Comment by jdalsem** [comment]
`input/dropdown` does not throw a deprecation notice... i therefore expect it still to be used

**Comment by hypeJunction** [comment]
ah, ok. Whatever, we can still throw it out. It's a major release :)

**Comment by jeabakker** [comment]
rel #5097

> we can still throw it out. It's a major release :)

it may break to many things, can still deprecate it

**Comment by mrclay** [comment]
If `input/dropdown` is virtually costless to keep and widely used, keep it.
