### ISSUE TITLE
Remove `elgg_register_menu_item()`

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11144]
Removing this will encourage better practices in registering menu items and avoiding global state.

**Comment by jdalsem** [comment]
could you clarify a bit more... i am all for registering menu items in hooks, but why would this function be a problem?

**Comment by jdalsem** [comment]
Closing this as i see no benefit removing this function

**Comment by hypeJunction** [comment]
Plenty of benefit directing people to using menu hooks and not relying on global state, but whatever

**Comment by mrclay** [comment]
The state is not global and we can think of these functions as programming an initial menu handler. I can't think of any problems ermi() cause that a registered handler wouldn't.
