### ISSUE TITLE
ElggUser::isAdmin problems

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11151]
Something is off with the method, it doesn't return correct results. Checking ``elgg_is_admin_user()`` seems fine.

**Comment by mrclay** [comment]
It's a simple attribute check, working for me on master.

**Comment by hypeJunction** [comment]
It was failing in tests. Will need to see what's happening.

**Comment by hypeJunction** [comment]
I think the issue is with attribute propagation/entity cache. I will try to add a failing test

**Comment by hypeJunction** [comment]
Indeed problems with cache #11197
