### ISSUE TITLE
Morning zen

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11152]
So, waking up after a good night sleep with some philosophical thoughts about Elgg.

- [ ] calling factory should by default return a new instance of Application unless use_singleton parameter is set to true
- [ ] make all static Application methods concrete, make singleton private
- [ ] retire elgg() as it adds another API convention and complicates things, move existing public services to e.g. elgg_menus()

**Comment by mrclay** [comment]
Q: What can you do with a new Application instance with most Elgg functions broken? elgg_view() won't work.

**Comment by hypeJunction** [comment]
This is just general feeling. Need to look at actual internals.

**Comment by mrclay** [comment]
Will send a PR in a bit.

**Comment by hypeJunction** [comment]
If we move elgg() declaration to autoloader, w could use it as proxy for Application, but without all public services, IMO. Same goes for _elgg_services(), they are declared too late.

**Comment by mrclay** [comment]
Sounds like elgg() would be like Application::getInstance() (using default options in factory). I'd rather just get rid of elgg(). If we have to use a singleton pattern (and will do) it's better to look like it.
