### ISSUE TITLE
phpunit via elgg-cli

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11163]
I am leaning towards bootstrapping phpunit via elgg-cli, so we have more control over before/after state:

https://gist.github.com/wandersonwhcr/cfaec6002eef02579ad9452a672d99c4

This will allow us to dynamically register active plugin tests.

**Comment by mrclay** [comment]
I enjoy using PHPStorm's PHPUnit runner, is that going to be impossible?

**Comment by hypeJunction** [comment]
We can keep phpunit.xml as is, so you can still run static tests.

**Comment by hypeJunction** [comment]
My ultimately goal is to have `elgg-cli test -c all -r ./clover` run all test suites including phpunit static and integration, plugin tests, and simpletests, and generate a coverage report.
