### ISSUE TITLE
Investigate memcache performance

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11166]
Memcache build is suspicious, it takes twice as much time to complete, which makes me believe we have a problem somewhere. You would expect it to be much faster. 

https://travis-ci.org/Elgg/Elgg/builds/265526955

**Comment by hypeJunction** [comment]
Likely. It's flushed after each test

**Comment by hypeJunction** [comment]
We could use a different prefix for each test.

**Comment by jdalsem** [comment]
Investigation in memcache results in the following conclusion:
- datacache and localfilecache have no use for persistent caching: overhead of writes (in bootservice) do not outweigh the benefits of memory based fetching of some data. The amount of queries (where memcache might be of use) have been reduced by preloaders.
- localFileCache / ServerCache should not use persistent cache (as it could contain server specific data, like paths)
- slower changing (and less frequently accessed) data, like system_cache, are more eligible for persistent caching (leaving that config intact)
