### ISSUE TITLE
Kill elgg_load_library()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11176]
Remove that bloody idiocy from core. It's 2017 and there is OOP.

**Comment by iionly** [comment]
Past discussion: https://github.com/Elgg/Elgg/pull/7443. Any new pro/cons?

**Comment by hypeJunction** [comment]
It probably costs more to keep track of libraries than it is to just require a file with all the functions once, it's a drop in a sitewide scope, especially with opcache enabled. Just switch to static methods as Ewan suggested if you are concerned about performance, PSR-0 is your friend

**Comment by iionly** [comment]
I guess the additional effort necessary to switch from libs to classes might not matter much when updating a plugin for 3.0 anyway as the effort is already quite high anyway (compared to 1.x -> 2.x). Me thinks I need to look into the static methods stuff as this might be the way to go to get it working with "minimum" effort. Only remaining problem might be 3rd party libraries included in plugins.

**Comment by mrclay** [comment]
Just require the file(s) in start.php. A 1 minute migration that adds pretty much 0 runtime cost if those functions don't get called.
