### ISSUE TITLE
Input should be aware of Request

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11177]
Router::route() takes in a request but Input has no clue what the request is. Either router needs to replace the request, or request needs to be injected in the input. IMO, we should just loose Input service and use the request.

**Comment by mrclay** [comment]
set_input is a weird feature

**Comment by hypeJunction** [comment]
Just inject directly into request and remove input config

**Comment by mrclay** [comment]
Two semi-related thoughts: 1. The auto HTML sanitization in `get_input()` has been very good for security. 2. If we ever do get around to exposing the Request to plugins, it should be a [PRS-7 implementation](https://packagist.org/providers/psr/http-message-implementation) with "safe" methods that auto-sanitize.

**Comment by hypeJunction** [comment]
Done already
