### ISSUE TITLE
Please remove nofollow tag from bookmarks

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#11181]
rel = nofollow tags are added by htmlawed by default. Doing this in plugins makes it hard to overwrite that with a hook. 

https://github.com/Elgg/Elgg/blob/642842d70c2a142d3596a81453b6ab5e2d6f03b8/mod/bookmarks/start.php#L49

**Comment by hypeJunction** [comment]
You can use `'view_vars', 'output/url'` and change `rel` to whatever you please.
