### ISSUE TITLE
Consider removing hooks and events during seeding

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11183]
I think we should just backup events and hooks during seeing, because there is a lot happening and we just really want some entities in the database

**Comment by hypeJunction** [comment]
Muuuuuuch faster

**Comment by mrclay** [comment]
Hesitant 👍 . I could imagine 3rd-party plugins needing to test their handling of create events for core objects. Hypothetically if core started creating river items by listening to object events, seeding would be incomplete

**Comment by hypeJunction** [comment]
I have rewired test seeding.
