### ISSUE TITLE
User entity attributes are not propagated correctly on update

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11197]
See login test case in #11196 https://github.com/Elgg/Elgg/pull/11196/files#diff-5397bbdf86bb3accdfde768f77265f0fR24

**Comment by hypeJunction** [comment]
I suspect it's related to #11151

**Comment by jdalsem** [comment]
I believe you confirmed that this after the attribute to metadata migration this was no longer an issue
