### ISSUE TITLE
Allow more access to stack traces

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11192]
Odd that we call it "trace level" when we omit stack traces for all elgg_log() usages. Because we do this, logged messages are often a pain to debug.

Should we add a real "trace level" that determines which log levels get a trace?

**Comment by hypeJunction** [comment]
I believe the latest Logger changes cover this.

**Comment by jdalsem** [comment]
With the latest (monolog) Logger features (since 3.x) we have stack traces available for certain log levels
