### ISSUE TITLE
Memcached should be in sync with entity cache

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11199]
`last_action` and `last_login` attributes are written to DB with a delayed query. Somewhere along the line, there is a discrepancy between entity attributes and memcache: https://travis-ci.org/Elgg/Elgg/jobs/268006673#L884

**Comment by hypeJunction** [comment]
I think persistent cache should be injected into entity cache and kept in sync. Looking at the code all operations are duplicated for both caches.

**Comment by mrclay** [comment]
Crazy idea: last_update, et al. are not internal attributes, and not saved in caches. Read/writing them always uses queries. No need to delay queries or thrash external caches for the current user viewing pages.

**Comment by hypeJunction** [comment]
Sounds fine

**Comment by hypeJunction** [comment]
Fixed in the new caching API
