### ISSUE TITLE
Check up on the annotations warning

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11207]
WARNING: PHP: 2017-08-25 18:12:21 (UTC): "Argument 1 passed to Elgg\UserCapabilities::canEditAnnotation() must be an instance of ElggEntity, boolean given, called in /home/travis/build/Elgg/Elgg/engine/classes/ElggAnnotation.php on line 116 and defined" in file /home/travis/build/Elgg/Elgg/engine/classes/Elgg/UserCapabilities.php (line 263)

**Comment by jdalsem** [comment]
I am not seeing this error. If you can provide steps to reproduce, let me know.
