### ISSUE TITLE
Centralize all DB operations in EntityTable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11200]
There is too much room for failure with entity updates taking place across multiple tables and methods. Entity classes also write to DB. DB state is in discrepancy with entity attributes and entity caches due to delayed DB writes. IMO, all DB writes should be moved to entity table, secondary tables should be injected into entity table, all cache updates should take place after DB writes from entity table.

**Comment by hypeJunction** [comment]
All the delayed queries are bad. We register them for each event but don't clean them up once they are irrelevant. If an entity has been updated 10 times on run time, delayed query will be executed 10 times on the same entity to update last action. Doesn't make sense.

**Comment by hypeJunction** [comment]
Also gets messy if you set last action then ban (or do something else that invalidates entity caches).

**Comment by mrclay** [comment]
> All the delayed queries are bad

Agreed, asks for a mess, but I've used the API in plugins when I needed to make sure my code was the last to update an entity.

**Comment by jdalsem** [comment]
I can not think of anything actionable regarding this at the moment
