### ISSUE TITLE
DI and mutable services

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11202]
So, I was looking into the issues with propagation of attributes and caches, and it comes to my attention that we inject session into entity cache with its state when entity cache is instantiated. Session state is mutable (logged in user changes, ignored access changes), hence entity cache behavior is not stable. We should either be injecting services by references, or just stop injecting them, or just rely on global state. With the new testing bootstrap global state isn't a problem for testing.

**Comment by mrclay** [comment]
Well, entity cache assumes the session will reach back and clear() when the session changes, and generally it does. This arrangement came about because we commonly flip access control on and off and we don't want to clear the entity cache each time.

**Comment by mrclay** [comment]
It might make sense to move the entity cache *inside* ElggSession so it manages the cache more directly.

**Comment by hypeJunction** [comment]
We do want to clear entity cache each time. I am running tests and entity cache goes out of sync:

1. Load a public entity - propagates to cache
2. Update entity attributes with ignored access - entity cache ignores changes
3. Use get_entity() and you get an entity with previous state

**Comment by mrclay** [comment]
Yeah, do it. That system was probably optimized for the older, more chaotic boot procedure.

**Comment by mrclay** [comment]
Better to have a simper, predictable system even if it costs some queries occasionally.

**Comment by hypeJunction** [comment]
It's covered by tests now. `get_entity()` could take second attribute for ignored access, could be passed to access sql builder without having to set/unset ignored access. Same for ege*

**Comment by mrclay** [comment]
> get_entity() could take second [argument] for ignored access

Often these calls are inside API functions that just accept GUID.

**Comment by jdalsem** [comment]
Need something more actionable for this issue to stay open
