### ISSUE TITLE
Failed update persists entity attributes

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11201]
```php
$ia = elgg_set_ignore_access(false);
$user->language = 'de';
$user->save(); // false

echo $user->language; // de
echo get_entity($user->guid)->language; // en
```

The problem is that subsequent calls to other methods that do not require permissions checks could propagate these attributes to caches.

**Comment by mrclay** [comment]
So we either revert attributes on a failed save, or provide a revert() method and beg plugins to use it. Any other ideas?

**Comment by mrclay** [comment]
We might want to add `$entity->hasUnsavedChanges()` and have entity caches check it.

**Comment by hypeJunction** [comment]
We should start throwing exceptions, IMO. Ideally we would have a set of HTTP exceptions, which would be caught in router. Failing silently is not an option anymore.

**Comment by mrclay** [comment]
You mean if a plugin uses permissions in a valid way to block a save(), we should throw? Of course, plugins can try/catch a FailedSaveException, but it's a big BC break.

**Comment by hypeJunction** [comment]
Plugins should only be saving in actions, that would be caught by the router. So, we are just making their lives easier.

**Comment by mrclay** [comment]
Legacy written actions would lose custom error messages and, more importantly, any work that came after, or partial Ajax response data that was going to be returned. These aren't reasons not to change, but considerations we can't ignore.

**Comment by hypeJunction** [comment]
Let's stick with untestable code that has a brain of its own. Maybe in another 20 years we will finally learn

**Comment by mrclay** [comment]
save() returning false doesn't make it untestable. It's a trade off like everything else. The greater crime toward untestability is all the invisible caching. I gave a [solution above](https://github.com/Elgg/Elgg/issues/11201#issuecomment-324699948) that I could try.

**Comment by mrclay** [comment]
Another: the moment an attribute is changed, purge the entity cache of it and disable caching for it. Leave it to be cached on a later request.

**Comment by jdalsem** [comment]
will this still be a problem when the attributes have been moved to metadata?

**Comment by hypeJunction** [comment]
> will this still be a problem when the attributes have been moved to metadata?

It would for user entities

**Comment by jdalsem** [comment]
There is no clear direction for a solution for now. If using save() do not assume it is successful
