### ISSUE TITLE
metadata permissions not applied during set

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11210]
when creating/editing metadata on an entity permissions aren't checked

**Comment by hypeJunction** [comment]
IMO, it's a good think. I would go as far as removing all metadata events and hooks. Make it a lightweight storage.

**Comment by mrclay** [comment]
Related to #11211?

**Comment by jdalsem** [comment]
No longer applicable. There is no longer a permissions check on writing metadata (see #12585)
