### ISSUE TITLE
Coupling of services

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11220]
There is currently too much coupling and cross-dependence between services, in some cases close to being circular. Instead of concentrating everything in a single DI container, I'd rather group service in multiple containers. Unfortunately there is too much mutability in services, so there is also a constant risk of services going out of sync with each other because dependencies are not injected by reference, e.g. ignored access in session, or hook handler registrations (registering a handler after a service dependent on hooks has been instantiated does not propagate these registrations to the dependent service). We should isolate mutable services or make them immutable, and then add dependent services to them or use global state. 
At the very least session and hooks should be isolated into independent services. Database tables could also become an independent container with each table as service (though I really think having tables as service is not a good idea because they all rely on each other and it's an ugly mess, they should just be merged or we should leverage foreign keys).

**Comment by hypeJunction** [comment]
There is a need for a thorough inspection of services: for mutability, for dependence on other services and how those could be eliminated. One way to go about it is by starting to write tests to see where it becomes problematic.

**Comment by mrclay** [comment]
Logging is the classic example here. You want it nearly everywhere, it needs hooks and other dependencies to do its job.

To me, our web of declared circular references is still miles better than having all code reach out for globals at any moment.

**Comment by mrclay** [comment]
> constant risk of services going out of sync with each other

Do you mean the problem of, e.g., "I created a new Logger but 5 dependencies have stored a reference to the old one"?

**Comment by hypeJunction** [comment]
Config is also mutable, so shouldn't be injected into other services.
All caches are mutable, should be moved to a respective new container.

**Comment by hypeJunction** [comment]
> Do you mean the problem of, e.g., "I created a new Logger but 5 dependencies have stored a reference to the old one"?

Logger is the least of the worries, but yes.
Nothing prevents plugins from registering hook handlers at the runtime, e.g. within a view. View service has already been instantiated at that point with hooks injected as they were when hooks were first instantiated. So this creates a situation where some services might trigger that hook handler, others might not. Russian roulette

**Comment by mrclay** [comment]
> View service has already been instantiated at that point with hooks injected as they were when hooks were first instantiated. So this creates a situation where some services might trigger that hook handler, others might not. Russian roulette

No, not at all. Every service gets the same hooks instance.

**Comment by hypeJunction** [comment]
The situation with imagick, I'd expect elgg_set_config('image_processor', 'imagick') to work irrespective when it was called, but that's not the case if somewhere we have called imageService

**Comment by hypeJunction** [comment]
> No, not at all. Every service gets the same hooks instance.

I don't think that's the case. At least not something I have seen with session

**Comment by mrclay** [comment]
That's just a race condition with reading the config value, not an issue with multiple copies of the dependency.

**Comment by hypeJunction** [comment]
Should be an easy test to write to prove me wrong, but I don't think service props are in sync with service.

**Comment by mrclay** [comment]
Search for ServiceProvider::setValue usages. Those are sources of concern, particularly if a key has already been set. We'd probably be wise to not allow mutation of a key once set, but we'd have to refactor some current techniques.

**Comment by hypeJunction** [comment]
I don't think the key is the problem, the arguments are. Mutable arguments are not passed by reference, so the state of hooks or session varies between services based on when they were instantiated. Dependent services are not aware of mutations in session or hooks

**Comment by mrclay** [comment]
> Mutable arguments are not passed by reference

All objects are passed by ref.

**Comment by hypeJunction** [comment]
Honestly, what I have seen with session is that they are not. Give me a test.

**Comment by hypeJunction** [comment]
The reason for #11204 is discrepancies I have seen in session state. Mutating session service did not mutate it in dependant services. Tests results were non-sensical and debugging revealed that things are not in sync, which is a massive problem, if it's true. I hope I am wrong, but I have spent a few days on those tests, and I am quite sure arguments are not passed by reference.

**Comment by hypeJunction** [comment]
@mrclay So, you are right that arguments are passed by reference, however, if the service is replaced using `setValue`, dependents still hold references of the first instance. I believe this was causing me grief in #11196, with some services being instantiated prior to session being replaced with a mock. I guess #11204 is not as critical as I thought it was, but it would still make sense getting it in some shape or form to resolve problems with ignored access and caches.

**Comment by hypeJunction** [comment]
As for this particular ticket, I still think it would be beneficial to detach some of the high-level services, and try to reduce coupling, and potential race conditions.

**Comment by hypeJunction** [comment]
Closing for now. This is getting better.
