### ISSUE TITLE
Allow plugins to replace dependencies during boot

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11221]
> @hypeJunction: we should either expose a pre-boot event to replace services (maybe look for boot.php in plugin root) and do other naughty things, or decouple hooks service from the DI container (see session PR) and trigger a hook before default core factory is called allowing plugins to build their own services.

A general problem is we require a partial boot to event find out which plugins are active and can be successfully started.

**Comment by jdalsem** [comment]
Currently Elgg does a low pass on active plugins to load services from elgg-services.php in the plugin root. This works fine.
