### ISSUE TITLE
elgg/Ajax#objectify doesn't work with nested values

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11237]
```html
<input type="text" name="a[b]" value="x" />
```
`a[b]` comes out as text instead of being unwrapped into an object. 

There seem to be many pitfalls in form submission, and perhaps it would be better to rewrite Ajax API to use jquery form.

**Comment by mrclay** [comment]
Ugh.

**Comment by hypeJunction** [comment]
Looks like FormData is now supported by all browsers: https://developer.mozilla.org/en-US/docs/Web/API/FormData

**Comment by jdalsem** [comment]
Works fine with FormData at the moment
