### ISSUE TITLE
Teach elgg/Ajax#action to resolve /action path

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11236]
`elgg/Ajax#action` should be able to resolve paths with or without `/action`

**Comment by jeabakker** [comment]
if provided with `action` like `action/blog/edit` this gets striped here https://github.com/Elgg/Elgg/blob/master/views/default/elgg/Ajax.js#L307-L309

and then the action part gets added again here https://github.com/Elgg/Elgg/blob/master/views/default/elgg/Ajax.js#L326

so both `elgg/Ajax#action('blog/edit')` and `elgg/Ajax#action('action/blog/edit')` work

**Comment by hypeJunction** [comment]
Hm, perhaps I had a typo. Will reopen if it doesn't work.
