### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by jlmeyer01** [Elgg/Elgg#11235]
Does anyone know of a 2017 linux webpage that walks you step by step in setting up Elgg, all the ones I find are old and want you to install PHP5 when PHP7 is out, I would like one that is built on centos like facebook is

**Comment by jeabakker** [comment]
I don't think there are any guides which will guide you through the entire process. But there are lots of guides which guide you through parts of it:

- install a linux server
- install apache/nginx with PHP7
- install Elgg http://learn.elgg.org/en/stable/intro/install.html
- installing Elgg plugins http://learn.elgg.org/en/stable/admin/plugins.html

**Comment by jdalsem** [comment]
Closing this issue here. If you need support you can visit https://elgg.org and look for support in any of the groups
