### ISSUE TITLE
Make clearer elgg-plugin.php should be static and side-effect free

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11261]
See the benefits here: https://github.com/Elgg/Elgg/issues/5947#issue-18474335

We want no Elgg API calls or side-effects caused. Think of it as a non-public JSON file.

**Comment by hypeJunction** [comment]
Maybe we should just add static config cache, and populate it before API is loaded.

**Comment by mrclay** [comment]
Without API we won't know which plugins are active, but it's not a big deal to read the disabled configs anyways.

**Comment by jdalsem** [comment]
changing it to a json file makes it very clear...

**Comment by mrclay** [comment]
True, and also clear that nothing sensitive should be stored in there. Damn I hate to change format again.

**Comment by jdalsem** [comment]
elgg-plugin.php is only in master am i right? should not be that big of a deal

**Comment by hypeJunction** [comment]
You want to be able to reference PHP classes without having to include the entire namespace path and worrying about namespace separator escaping. I don't think JSON is going to work for this. I envision us allowing declaring hook/event/page handlers using elgg-settings, and now that those support invokable classes, I'd like to have IDE support.

**Comment by jdalsem** [comment]
> You want to be able to reference PHP classes

this requires plugins to be 'started' if they provide their own classes

**Comment by jdalsem** [comment]
i am fine with how it currently works by the way... only thing is you can not use it without the engine at this moment... but that is not yet required at this point

**Comment by mrclay** [comment]
http://learn.elgg.org/en/2.3/guides/plugins.html#elgg-plugin-php We already say "is not guaranteed to run at any particular time".

FWIW, class constants will invoke autoload, but things like `Foo::class` or callbacks like `"Foo::bar"` will not.

**Comment by hypeJunction** [comment]
Yes, `Foo::class` can be analyzed statically, but you if we switch to JSON, we would have to include an entire path. 
Further, JSON is problematic with paths for `views`

**Comment by mrclay** [comment]
Yeah, keep the PHP.

**Comment by jdalsem** [comment]
than we can not use it earlier than we are doing it now... and we can close this discussion as it is not static

**Comment by hypeJunction** [comment]
Paths are static, php will resolve them whether or not the engine is booted.
Basically the file output must be serializable.

**Comment by jdalsem** [comment]
if you want to autoload classes and paths to classes the application needs to know where these classes are... plugins can provide their own vendor (see the vendor autoload feature in plugin start). Not included plugin autoloads will not be resolvable by PHP

**Comment by hypeJunction** [comment]
Hence I am suggesting we add a static config cache service, which will run at application boot and cache static config for all plugins. Then instead of reading config on each call, we use the cached value.
