### ISSUE TITLE
Large tables added in comments or pages are truncated (elgg v2.3.4)

### ISSUE THREAD

**Issue by oseg** [Elgg/Elgg#11279]
Suggested Fix: add an horizontal bar if table width is larger than elgg-output width

For instance, in aalborg_theme/views/default/elements/typography.css line 133, the elgg-output class could have some overflow properties:

.elgg-output {
	margin-top: 10px;
        overflow-x: auto;
        overflow-y: hidden;
}

**Comment by jdalsem** [comment]
the usage of tables is discouraged. Tables are not responsive and should be avoided if possible.
