### ISSUE TITLE
master: removed plugins warning after upgrade

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11289]
WARNING: Failed to load package for 19. D:/htdocs/core19/mod/htmlawed/ is an invalid plugin path.

WARNING: Failed to load manifest for plugin 19. Package cannot be loaded

WARNING: Failed to load package for 19. D:/htdocs/core19/mod/htmlawed/ is an invalid plugin path.

WARNING: Failed to load manifest for plugin 19. Package cannot be loaded

WARNING: Failed to load package for 3. D:/htdocs/core19/mod/aalborg_theme/ is an invalid plugin path.

WARNING: Failed to load manifest for plugin 3. Package cannot be loaded

WARNING: Failed to load package for 3. D:/htdocs/core19/mod/aalborg_theme/ is an invalid plugin path.

WARNING: Failed to load manifest for plugin 3. Package cannot be loaded

**Comment by jdalsem** [comment]
maybe we should deactivate these plugins before upgrade...

**Comment by jdalsem** [comment]
@elgg/core has anyone have an idea how we could do this in a correct way? We do not really know when we are upgrading (or from which version we are coming) at a moment before the plugins get disabled...

**Comment by hypeJunction** [comment]
I think we should just leave it as is. It gives admins an idea of what plugins have been removed.

**Comment by jdalsem** [comment]
i do not think this is very user friendly... at least we could mention it somewhere this happens when upgrading.. problem is it could also mean you have a bugged (non bundled) plugin after an upgrade.. maybe we can figure something out during the beta phase... moving this issue to 3.0 milestone
