### ISSUE TITLE
is dual domain possible ?

### ISSUE THREAD

**Issue by dipenpatel235** [Elgg/Elgg#11285]
hello..
i want to open same site as dual domain 
so it is possible to make same elgg as dual domain ?

**Comment by mrclay** [comment]
I think the caching strategy we use would cause problems, putting absolute URLs in CSS/JS files, e.g.

**Comment by ernestbuffington** [comment]
You can use federatedX and it will not cause a problem. Just federate the user database as that is probably the only thing you would want a second site to inherit. MariaDB has great support for this.

**Comment by dipenpatel235** [comment]
Thanks @ernestbuffington i will check that and update to you.
Thanks
