### ISSUE TITLE
proposed for dynamic database update from non-legacy module or plugins

### ISSUE THREAD

**Issue by francescobianco** [Elgg/Elgg#11280]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by jdalsem** [comment]
Elgg already has its own db abstraction layer and uses phinx for database migrations. There are thoughts to do something with a query object, but nothing serious going on in that field at this moment. You could take a look on how Elgg is doing the abstraction. If you think your project can help Elgg you are free to provide a PR so we can discuss integration. For now i am closing this as i see no direct need/use for javanile/moldable in this project.
