### ISSUE TITLE
Suggestion for - mod and theme missing files.

### ISSUE THREAD

**Issue by ernestbuffington** [Elgg/Elgg#11312]
Would be nice if an old theme was loaded and a drop-down window would outline how to update it or even the current mod. i.e. Any theme that might just be missing a few things that could be fixed easily. Maybe an outline of what needs to be added or what is missing. This way when a new user takes over a theme project he knows how to re-version and update. Would make this project sail even faster forward.

Small outline:
Missing files
Brief Description of each files connectivity and responsibility.
RE-Versioning reminder for people who take-over theme or mod projects that have been abandoned.

Thanks,
The Ghost

**Comment by jdalsem** [comment]
There is no list of required files for themes. Best to do is take a look at the theme_sandbox in the developers_tools plugin and see what parts of the theme need fixing.
