### ISSUE TITLE
On Mac in Safari and Chrome the URL constructed to download a file is false

### ISSUE THREAD

**Issue by Maartenvanhof** [Elgg/Elgg#11317]
If you use Safari or Chrome (Firefox does not has this behavior) and I want to download a file not uploaded by me, the URL to download is false.

What happens. If I click on download the URL that opens is changed to the address of the file. But it creates an URL with 3x the HTTP start.
http://boz-nooitaf.work/http://boz-nooitaf.work/http://boz-nooitaf.work/serve-file/e1508865699/l1508705804/da/c1/_2FDl7dfSr-EfG19Hk_CtU2Vp863xdlVsof6UZPG5Pw/1/161/file/1508705804zo%20versla%20je%20de%20robotisering%20als%20werknemer.pdf

In Firefox it is created as it should be.

If I try to download a File I have uploaded this does not happen. All versions of OSX, Safari, Chrome and Firefox are current as far as I can see.

It might be a problem with the Apple Webengine. I send a bug report to Apple also.

**Comment by hypeJunction** [comment]
Are you using latest Elgg 2.x? There was a problem with special characters in file names, which should have been resolved.

**Comment by Maartenvanhof** [comment]
This the version: Release - 2.3.1, Versie - 2016092300

That is the latest?

**Comment by Maartenvanhof** [comment]
I see there is a version 2.3.4
I will update first.. and let everybody know if it is solved with the new version.

**Comment by jeabakker** [comment]
looks like the same problem as #10771 which was fixes in #10772 for Elgg 2.3.2

**Comment by Maartenvanhof** [comment]
The automatic update was a version behind. By hand the latest version installed and the problem is solved. Thanks everybody.

**Comment by Maartenvanhof** [comment]
Solved by the latest version of the software
