### ISSUE TITLE
CKEditor 5 for Elgg 3

### ISSUE THREAD

**Issue by nschonni** [Elgg/Elgg#11313]
https://ckeditor.com/blog/CKEditor-5-A-new-era-for-rich-text-editing/
Looks like there would be a bunch of breaking changes, and it is still at a 1.0-alpha.
Just flagging it as a discussion point for the next major release

**Comment by jdalsem** [comment]
It is probably too early to add this. CKEditor 5 is missing a lot of features compared to CKeditor 4 at this moment. We hope to release Elgg soon, so providing CKeditor 5 is not wise in my opinion. If CKEditor 5 comes out, a plugin for Elgg could easily provide a newer version.
