### ISSUE TITLE
code documentation: replace @access private with @internal

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11338]
ref #10171, #9300

`@access private` prevents the function from being included in HTML output, but is a phpDocumentor tag https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.access.pkg.html

preferred use is `@internal` which does the same but is an official PHPDoc tag https://docs.phpdoc.org/references/phpdoc/tags/internal.html

**Comment by mrclay** [comment]
I've been resistant to pursue this because it would make private API function calls look like deprecated functions (strikethrough in IDEs), but we should serve the docs more than anything.

**Comment by jeabakker** [comment]
@mrclay So for you the usage of `ViewsService::findViewFile` https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/ViewsService.php#L263 is striked through?

For me it's not, i'm using Eclipse

**Comment by jeabakker** [comment]
since reference.elgg.org uses DoxyGen for parsing and DoxyGen doesn't support `@access` but does support `@internal` this would help

https://www.stack.nl/~dimitri/doxygen/manual/commands.html

**Comment by mrclay** [comment]
Disregard my earlier comment. Latest PHPStorm doesn't strike through.

**Comment by hypeJunction** [comment]
It does for me...

**Comment by mrclay** [comment]
June 2016 PHPStorm [changed behavior](https://youtrack.jetbrains.com/issue/WI-22284#comment=27-1482041) to basically ignore `@internal` when rendering code.
