### ISSUE TITLE
master: river table subtype column needs to be filled

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11346]
With the denormalization of the `entities` table the `river` was forgotten

ref #11327, #11310

**Comment by jdalsem** [comment]
@hypeJunction was this on purpose or by accident?

**Comment by mrclay** [comment]
Can the type/subtype in river just be pulled in via object_guid?

**Comment by hypeJunction** [comment]
An oversight. I assumed there was already a subtype string in there, but with new defaults those need to be populated. I would just remove type and subtype and use object column, we already join in to check the access.

**Comment by jdalsem** [comment]
Older discussion here: https://github.com/Elgg/Elgg/issues/6671

I think we should remove the columns also

**Comment by hypeJunction** [comment]
Working on this. Throwing out type and subtype from river table
