### ISSUE TITLE
Malformed message-id?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11350]
Recent discussion topic: https://elgg.org/discussion/view/2711497/message-could-not-be-delivered-to-some-yahoocom-recipients

Message-Id given as example there is `"Message-ID: </.entity.111.2222222222.3333@site.url>"`

Is that really what it's intended to be?

Some testing gave me these results (site url as `site.url/subfolder`):

On Elgg 1.9 (maybe 1.10/1.11, too) it looks like: `"Message-Id: <20171101193525.AA999999999@site.url/>"`

On Elgg 1.12 and 2.3.4 I got an id of the form: `"Message-ID: </subfolder/.default.1111111111.2222@site.url>"` and `"Message-ID: </subfolder/.entity.2222.3333333333.4444@site.url>"`

Does this really look like it's supposed to look like? I would rather say the message-id on Elgg 1.9 looks right but the later ids not. The message guid as part of the id seems alright. But what about the url path and the words "entity" or "default"?

**Comment by jeabakker** [comment]
it's created as intended see https://github.com/Elgg/Elgg/blob/master/engine/lib/notification.php#L251-L336
and i do believe it's valid according to RFC-2822 https://tools.ietf.org/html/rfc2822

**Comment by iionly** [comment]
@jeabakker I think you're right (let's say by 99.9999%). I wasn't sure about the slashes being valid characters but I think now that they are. Interesting to note is that older Elgg versions (at least older than 1.12) had the same message-id layout created in Elgg code but the actual message-id sent was different. I think php mail() replaced the message-id with its own format.

Let's see if there's any response in the discussion thread regarding the Elgg version involved. Most likely it's not the latest 2.3.4 that contains your UTF-8 fix. So, closing the issue for now.
