### ISSUE TITLE
Elgg zip release contains at least an outdated .htaccess

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11362]
I don't know how the release process works exactly. But it seems to me that the .htaccess file in the zip release comes from the Elgg-starter project. Unfortunately, the .htaccess file over there is outdated, i.e. doesn't have any changes made in htaccess.dist of the Elgg repo.

Some other files in the starter repo also differ from their corresponding files in the Elgg repo. For these files I don't know if the differences are valid or if they are also just outdated.

If it's only .htaccess that's outdated, I could make a PR. But I can't be of much help for the other files.

If an automatic sync between the repos would be possible (in the best case before a new zip release is created), it might be the best way.

**Comment by iionly** [comment]
PR for updated .htaccess in https://github.com/Elgg/starter-project/pull/41.

If any other files are outdated, someone else would have to fix them.

**Comment by jeabakker** [comment]
Just so you know, this is how the release process works http://learn.elgg.org/en/stable/contribute/releases.html

**Comment by jeabakker** [comment]
I merged the PR, I don't think any other files are outdated
