### ISSUE TITLE
master: DenormalizeEntitySubtypes fails due to old unit test failures

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11365]
I got "Unable to perform migration DenormalizeEntitySubtypes, because the database contains objects without a subtype" due to running old unit tests.

Here's the SQL I used to fix it:
```sql
DELETE FROM elgg_entities
WHERE guid IN (
  SELECT guid
  FROM (
    SELECT guid
    FROM elgg_entities e
    LEFT JOIN elgg_entity_subtypes s ON (e.subtype = s.id)
    WHERE s.id IS NULL
    AND e.type = 'object'
  ) q1
)
```

**Comment by jdalsem** [comment]
what do you want with this?

**Comment by jdalsem** [comment]
Closing this as i think this is not something we need to fix. This is just your own db maintenance... Thanks for logging the query for future reference.
