### ISSUE TITLE
Admin should be able to upload svg and WebP files to represent groups or upload them anywhere for that matter.

### ISSUE THREAD

**Issue by ernestbuffington** [Elgg/Elgg#11360]
If this is already in place it does not work. I created a **Magento** programming group and tried to upload the **SVG** logo and no dice. The system should support any and all file types that are available. Some folks now use only **SVG** and simply refuse to use any other image format except for **WebP**.

What can I do to allow the use of **SVG** and **WebP** everywhere on our developer site. We also have an area so developers can show off their **SVG** logo design and their **WebP** work.

Thanks,
Ernest Buffington

**Comment by jdalsem** [comment]
This is currently not possible with default Elgg. Elgg uses the Imagine library for image handling. By default it uses the PHP GD library and that does not support handling of SVG or WebP images.

It theoretically would be possible to add SVG and/or WebP support to your site by creating a plugin that implements support for these image types.
