### ISSUE TITLE
Elgg 2.3.4: installation fails with existing settings.php

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11361]
PHP 5.6 (don't know if it might work on PHP 7.X).

Error is
```
PHP Fatal error:  Interface 'Throwable' not found in /INSTALLDIR/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/DriverException.php on line 33
```
Problem is that the installation doesn't even start if you create settings.php manually. If you create it manually for example at step 2 of the installation (before database credential input in step 3), the installation continues and finishes without issues though.

**Comment by iionly** [comment]
So, site.url/install.php works. Just need to remember that...

**Comment by jdalsem** [comment]
yep... with an existing settings it currently is not detected that there is an install needed. Manual going to install.php is the solutions is the case... maybe we could add a not somewhere in the installation docs that this is the case.
