### ISSUE TITLE
Suggestion: using input/number for num_display input of widgets

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11364]
It might not be too late for 3.0 to consider (and I would make a PR if usage of input/number would be accepted).

Right now we have mostly a dropdown selection to define the number of items shown in widgets. Disadvantage is that you have only the numbers offered by the developer. Also the dropdown could get long. And there are inconsistencies regarding the offered numbers (not necessarily in Elgg core but surely with 3rd party plugins' widgets).

Coldtrick uses a text input in some of their plugins (e.g. in Widget Manager). That solves the issues with the dropdown selection. But the text input validation happens only after submit.

A number input would solve all issues. The user can choose the number of items to be displayed in +/-1 steps. And there's input validation before submit possible (only numbers, minimum of 1, even a maximum number would be possible).

So, what do you say? Starting with core widgets would be a start.

If you agree, should I add a maximum item limit (e.g. 20 or 30)?

**Comment by beck24** [comment]
Makes sense

**Comment by jeabakker** [comment]
would be great if you could do this. Don't add max, just a min of 1

**Comment by jdalsem** [comment]
i believe there is just one view you need to change into a `input/number`... that is `object\widgets\elements\num_display`... and of course change all calling views... Be advised to set the default values correct as with input/selects it would default to the first value in the list

**Comment by iionly** [comment]
It's ```object/widget/edit/num_display.php```. I wasn't aware that this view! Most likely I would have realized it exists once opening a core widget's edit.php.

But I think a default max value is necessary (of course, allowing the calling views to override this). Without any max value restricting the user input some funny or clueless user would surely enter a vast high number resulting in a out-of-memory issue. How about defaulting to a max value of elgg_get_config('default_limit') (fallback 20)? Any higher max value necessary for a specific widget can still be set by the calling view (I will take the hightest value of the existing selects 'options' array as the max for the core widgets).

**Comment by jdalsem** [comment]
sounds good... if you make a PR we can discuss it further

**Comment by jdalsem** [comment]
Closed by #11396
