### ISSUE TITLE
Use callable type hint in params

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11370]
Notably it was missing in elgg_register_page_handler, but we should remove all our hacky `is_callable` checks.

**Comment by hypeJunction** [comment]
What do you mean exactly? I'd rather we add callable type hint everywhere

**Comment by mrclay** [comment]
For static methods the type hint autoloads the class. Not a dealbreaker though.

**Comment by hypeJunction** [comment]
Does it though? I don't think use statements do, so I wonder why type hints would

**Comment by jeabakker** [comment]
> so I wonder why type hints would

I think PHP needs to check if your var is of the correct type therefor it probably does instanceof en this loads the class (in order to be able to check extends etc)

**Comment by hypeJunction** [comment]
Yes, but by then you would already be calling the function... I think @mrclay means during SPL load.

**Comment by mrclay** [comment]
To be clear: Let's use the `callable` type hint everywhere and get rid of is_callable checks.

Yes, if you use a static method callable, the class will be loaded when not needed, but I no longer think this is a performance issue worth confusing code.

**Comment by hypeJunction** [comment]
There is also added benefit of IDE support, especially when it comes to string callables

**Comment by mrclay** [comment]
Just changing the PHPDoc gives you IDE support, which is worth doing in 2.3 now.

**Comment by jdalsem** [comment]
Not going to typehint as it will autoload all classes. Elgg relies heavy on class based callbacks for hooks and events and we do not want those classes to be loaded if they are never used.
