### ISSUE TITLE
Investigate installation on https

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11371]
See https://elgg.org/discussion/view/2713856/installation-woes

**Comment by smellems** [comment]
Had the same problem when trying to install the latest 2.3 with HTTPS enabled.

I was getting `Blocked loading mixed active content “http://...` errors for CSS and Javascript and could'nt get through the install process.

Installed without HTTPS and site now seems to work well over HTTPS

**Comment by jdalsem** [comment]
After some investigation i provide #12756 for detecting more https installation scenarios... however there can still be issues where your server setup could provide some issue where https is not detected. If the `$_SERVER['https']` is missing, for example if your https encryption is offloaded to a proxy. Currently we have no solution for those cases.
