### ISSUE TITLE
Bug in calling numeric username

### ISSUE THREAD

**Issue by aliroayaei** [Elgg/Elgg#11375]
Hi. In the system we use, the national code is used as the username, and the user name may start with zero. For example, we may have two user names 1152535 and 001152535. But when we use the get_user_by_username function, it does not count zero before it and we get into trouble when calling the user. So check this out
Thank you

**Comment by mrclay** [comment]
What version?

**Comment by mrclay** [comment]
Just curious: Have you verified that the username is being stored correctly in the users_entity table?

**Comment by aliroayaei** [comment]
Version 2.3
Yes, the username is stored correctly

**Comment by jeabakker** [comment]
Confirmed

Problem comes from https://github.com/Elgg/Elgg/blob/2.3/engine/classes/Elgg/Database/EntityTable.php#L1270
which cases an SQL which doesn't match on string. In master this problem doesn't exist.

**Comment by mrclay** [comment]
I'd suggest prefixing these "0"-first usernames with "u" or something. You're bound to run into other problems with naive PHP's comparisons.

@jeabakker do we even need this check? If it got quoted I don't foresee an issue.

**Comment by jdalsem** [comment]
it would not be wise to change anything to our SQL queries in Elgg 2.3 anymore if it is not required. Having all number usernames is a bad practice in general. So i suggest you add a prefix to the username. On a side note; Elgg 3.x is not having this issue as this query is nonexisting.

Closing this as won't fix for now
