### ISSUE TITLE
travis: let seeder use local images for icons to prevent timeout issues

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11386]
@hypeJunction do you now if this can be done easily or is supported somewhere in the seeder features?

**Comment by hypeJunction** [comment]
Sure, instead of reading a URL, you can point it to a local file.

**Comment by jdalsem** [comment]
not with current faker AFAICS... we need to provide our own image provider so we can use a local folder with a few images to randomly serve when requested.

**Comment by hypeJunction** [comment]
IMO, they don't need to be so random.
