### ISSUE TITLE
Possible PHP 7.2 incompatibility issue with incompatible method declarations

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11399]
See also discussion at https://elgg.org/discussion/view/2717814/fatal-error-php-error-between-installation-step-4-and-5

A fatal error seems to occur when trying to install Elgg 2.3.4 on PHP 7.2:
```
Fatal error: Declaration of ElggSite::delete() must be compatible with ElggEntity::delete($recursive = true) in /XXX/elgg/elgg/engine/classes/ElggSite.php on line 28
```
Not sure if this is the only occasion that a method calling the parent method is incompatible with regard to function attributes. Is testing PHP 7.2 compatibility already done (or possible at all at the moment if not)?

**Comment by jdalsem** [comment]
7.2 is not officially released yet... we would be very pro active if we had already supported that... i expect a 7.2 release soon and we can add tests for in in travis shortly after

**Comment by iionly** [comment]
Nov 30th seems the planned release date of 7.2. Not that far away. Anyway, the fatal error shown above seems to have already a warning in previous php versions. So, would it be necessary to correct the delete method in the ElggSite class in any case... strictly speaking?

**Comment by jdalsem** [comment]
yes it should

**Comment by jdalsem** [comment]
#11426 fixes the issue you mentioned. Currently we are not actively testen for PHP 7.2 but if you find more issues, feel free to report them
