### ISSUE TITLE
master: how to set order_by?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11412]
normalizeOrderByClauses, in the deprecation notice, asks for a closure that returns "a prepared clause". Some issues:

- It looks like the closure should return an OrderByClause
- There's no code to execute the closure, so it's broken
- It doesn't tell you you can return an array of OrderByClause

In particular I was trying to convert the $options in MetadataCache::populateFromEntities.

cc @hypeJunction

**Comment by mrclay** [comment]
Does the closure have to call OrderByClause::prepare or does the system do that for me?

**Comment by mrclay** [comment]
Looks like the message is just wrong. See #11413

**Comment by hypeJunction** [comment]
Closures get injected as expression into a new clause instance and get expanded when prepared. So a closure should return a string, but in case of order by it's bad, I guess, because we need two arguments. I think requiring an OrderByClause is the cleanest solution.

**Comment by hypeJunction** [comment]
There needs to be a way for a plugin to get a table alias, so we should support closures, but they should return an array of column and direction. Optionally we can ask for a string and preg match a string as we do during normalisation. 

Also not sure if DBAL supports it, but we should try and accommodate orders without direction, e.g. ``ORDER BY FIELD(id, 3, 11, 7, 1)``

**Comment by mrclay** [comment]
Ahh, so you *can* do:

```php
'order_by' => [
    new OrderByClause(function ($qb) { return 'a.col1'; }),
    new OrderByClause(function ($qb) { return 'b.col2'; }, 'DESC'),
],
```

So this lets you see the current query before you decide the order by expression, but do you see a solid use case for this? I just wonder if there's not immediately useful API surface area we could remove to simplify a bit.

**Comment by hypeJunction** [comment]
Eventually I want to throw away all of these in favour of one array of filters that you can use to alter query builder instance. I don't see why we separate joins, wheres and order by, when it would be logical to do all at once. 

There is a case for allowing hooks to alter options, but we might as well add a global hooks to alter query builder. 

I am looking at these as an intermediate API to deal with array options until we can move to dull blown OO query. 

In this case if the join is done without a set alias, you wouldn't know that column b ist indeed column b, so you would use second argument to read the alias.

Maybe I am overcomplicating thing with trying to foresee future

**Comment by mrclay** [comment]
Is there an example in core of the Right Way to build a query now? I guess I think it's wrong to badger devs with deprecation notices to convert a bunch of option keys if we can easily do that work for them. What do devs *get* for that trouble?

**Comment by mrclay** [comment]
Like, what do I get for performing [this conversion](https://github.com/Elgg/Elgg/pull/11413/files#diff-f11972107fd003c08d1d30be4fdb37a7L169)?

**Comment by hypeJunction** [comment]
I am working on it, but yes, agreed. For select, group by and order by clauses we can just find an alternative solution that doesn't require QB.

**Comment by jdalsem** [comment]
In https://github.com/jdalsem/Elgg/commit/e77e4898fd0206c7358673c30f44502a3d675fd5 i removed the deprecation notice. Forcing devs to change their code without any benefit is not a good idea. In the future this might be deprecated again, but that is for later.
