### ISSUE TITLE
Put Config table values into boot cache

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11417]
At least for tests, we don't need to read config table on each Application boot

**Comment by mrclay** [comment]
We shouldn't store the site secret in cache, so I figured breaking up the config loading into 2 places wasn't worth the complexity.

**Comment by hypeJunction** [comment]
Right, I guess we should just mock ConfigTable::getAll(), but that probably reduces reliability of integration tests.

**Comment by jdalsem** [comment]
Leaving this as is for now
