### ISSUE TITLE
fetching entities with boolean values in metadata/privatesettings fails

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11427]
somewhere https://github.com/Elgg/Elgg/blob/master/views/default/admin/upgrades.php#L13 is cast to an `int` and therefore the query fails. If I change `false` to `0` or `'0'` it works

@hypeJunction help please

**Comment by jeabakker** [comment]
also applies to metadata https://github.com/Elgg/Elgg/blob/master/mod/site_notifications/views/default/resources/site_notifications/view.php#L26

**Comment by hypeJunction** [comment]
Need to resolve boolean to int here: https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Database/LegacyQueryOptionsAdapter.php#L609

**Comment by jdalsem** [comment]
Still have this problem on the upgrades page (using private settings)

**Comment by hypeJunction** [comment]
Link to code?

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/blob/master/views/default/admin/upgrades.php#L13

**Comment by hypeJunction** [comment]
can you see the actual value in the database?

**Comment by jdalsem** [comment]
can check... changing the query to 0 gives result

**Comment by jdalsem** [comment]
values in db are 0 or 1
