### ISSUE TITLE
Is upgrade travis job using correct version to upgrade to?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11435]
I was wondering why https://travis-ci.org/Elgg/Elgg/jobs/308473739 failed... in the mean time PHP7 requirement was added to master... could it be that the upgrade job is not using the PR branch to upgrade to? Is maybe "git checkout -" the issue in the config? I am not entirely sure what version gets installed with this command....

@mrclay or @hypeJunction do you know?

**Comment by hypeJunction** [comment]
Oddball. Maybe config has changed but cached? Try wiping the build cache for that PR

**Comment by jdalsem** [comment]
Another strange case.... https://travis-ci.org/Elgg/Elgg/jobs/308964045... also looks php7 related

**Comment by jdalsem** [comment]
Closing this as we moved to github actions
