### ISSUE TITLE
Elgg 3 install / post-install issues

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11433]
I had to make a fresh test installation of Elgg 3 because my existing installation stopped working after the database scheme changes.

I had some issues during installation:

* installation only started when calling site.url/install.php (I understand that might be necessary now with settings.php present but on a normal installation for dummies without settings.php it's a bit annoying at least),
* after entering database credentials Elgg wasn't able to connect to the database at first (settings.php was created and details were correct but Elgg failed nevertheless). Only on a page refresh the installation continued (without any changes in settings.php),

Major problem is after installation has finished "successfully" the site doesn't load at all due to out-of-memory issues.

Here are the log entries that were created during installation and afterwards when trying to access the site (increasing memory limit to 512M only results in slightly different lines of code causing the out-of-memory errors):
```
[Tue Nov 28 21:50:21.621756 2017] [php7:error] [pid 14516] [client 127.0.0.1:39196] PHP Fatal error:  Uncaught ConfigurationException: Elgg\\Config::factory: Reading configs failed: File /elgg-install-folder/elgg-config/settings.php not present.  in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Config.php:186\nStack trace:\n#0 /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Application.php(463): Elgg\\Config::factory(NULL)\n#1 /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Application.php(511): Elgg\\Application::factory(Array)\n#2 /elgg-install-folder/index.php(8): Elgg\\Application::index()\n#3 {main}\n  thrown in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Config.php on line 186

[Tue Nov 28 21:59:03.648764 2017] [php7:notice] [pid 14516] [client 127.0.0.1:39270] PHP Notice:  Undefined property: ElggUser::$admin in /elgg-install-folder/vendor/elgg/elgg/engine/classes/ElggUser.php on line 162, referer: http://site.url/install.php?step=admin

[Tue Nov 28 21:59:29.391363 2017] [php7:error] [pid 14516] [client 127.0.0.1:39270] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Http/Request.php on line 76, referer: http://site.url/install.php?step=complete
[Tue Nov 28 21:59:29.400786 2017] [php7:error] [pid 14516] [client 127.0.0.1:39270] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Application.php on line 488, referer: http://site.url/install.php?step=complete

[Tue Nov 28 21:59:29.413122 2017] [php7:error] [pid 14516] [client 127.0.0.1:39270] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: http://site.url/install.php?step=complete

[Tue Nov 28 22:01:29.377044 2017] [php7:error] [pid 14513] [client 127.0.0.1:39300] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Http/ResponseFactory.php on line 500

[Tue Nov 28 22:07:37.337032 2017] [php7:error] [pid 14517] [client 127.0.0.1:39324] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Http/Request.php on line 76
[Tue Nov 28 22:07:37.931527 2017] [php7:error] [pid 14517] [client 127.0.0.1:39324] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /elgg-install-folder/vendor/elgg/elgg/engine/classes/Elgg/Application.php on line 488
[Tue Nov 28 22:07:39.802730 2017] [php7:error] [pid 14517] [client 127.0.0.1:39324] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

**Comment by hypeJunction** [comment]
Elgg installer doesn't have any tests at all, that would be a good place to start

**Comment by iionly** [comment]
Has anyone done a fresh install of 3.0-dev recently and could either reproduce my out-of-memory issue or not? It would already help me to know if there might be no problem in master after all and I have to start looking for the cause in my server config.

**Comment by hypeJunction** [comment]
It's done for every build on Travis. I have installed 3.0 recently and didn't have issues.

**Comment by iionly** [comment]
Damn. I was afraid to get that response. It failed for me on two machines. First, still on php 5.6 before 3.0 became php 7 only. And then on a second machine with php 7.1. Any idea what server config issue could cause a memory issue resulting in the above errors?

**Comment by hypeJunction** [comment]
@juho-jaakkola, you mentioned a memory issue to me the other day. Could you compare notes?

**Comment by iionly** [comment]
Don't bother. I don't care anymore.

**Comment by jdalsem** [comment]
we care...
