### ISSUE TITLE
dont force return an int in database calculate functions

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11446]
example `Elgg/Database/Entities->calculate` (do a avg for 1 and 2 for example)

it could also be float or string... just remove the cast

add a regression test for this

@hypeJunction

**Comment by jdalsem** [comment]
ref #1559

**Comment by hypeJunction** [comment]
You don't need me to fix this. I am already over my head with things to do.

**Comment by jdalsem** [comment]
mentioned you because you did the change and was wondering if there was a specific reason for that...

**Comment by hypeJunction** [comment]
Probably some stupid old test that expects an int.
