### ISSUE TITLE
multiple order by metadata s fail?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11456]
should this be possible?
```php
'order_by_metadata' => [
   [
       'name' => 'title',
       'order' => 'ASC',
   ]
]
```

this however seems to work...
```php
'order_by_metadata' => [
       'name' => 'title',
       'order' => 'ASC',
]
```

i thought we could have multiple order bys....

/cc @hypeJunction

**Comment by hypeJunction** [comment]
Never was possible, but shouldn't be a problem to add as a feature

**Comment by jdalsem** [comment]
hmm i came across this in master... but it probably did not even work there and is not present in 2.3 afaik... closing this as i do not need a new feature at this moment

**Comment by hypeJunction** [comment]
Metadata orders are not very efficient, so I'm not sure we should even encourage it. It should be easy to add a custom join and order by clauses, if anyone needs it.
