### ISSUE TITLE
PHPCS should only check php files

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11458]
https://travis-ci.org/Elgg/Elgg/jobs/312426495#L856

**Comment by jdalsem** [comment]
why not have a CS for CSS?

**Comment by hypeJunction** [comment]
I am not sure what the effects of that are going to be if it confuses a css construct for a php function, especially when CSSCrush is used to its fullest

**Comment by jdalsem** [comment]
The issues detected in the mentioned job are completely valid and should be fixed... we can revisit the CS rules for CSS when they are causing unwanted issues
