### ISSUE TITLE
page/components/list doesn't support array 'class' in $vars

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11468]
when provided in elgg_list_entities => 'list_class'

**Comment by mrclay** [comment]
I don't understand the problem. `list_class` is a documented key and works.

**Comment by mrclay** [comment]
Passing in list_class to outputs the class in the list UL. Where are you seeing the issue?

**Comment by jdalsem** [comment]
probably does not support `'list_class' => ['class A', 'class B']`

**Comment by mrclay** [comment]
I have some ideas to make use of this [ClassList](https://gist.github.com/mrclay/64b6301fb7adcea0ff0716f60639bcd2) object.

**Comment by mrclay** [comment]
PR #11481
