### ISSUE TITLE
Migrate private settings to metadata

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11492]
With all the changes to metadata, both private settings and metadata are identical key => value storages. It would reduce all the overhead if we just migrated everything to metadata.

**Comment by juho-jaakkola** [comment]
This might very easily cause conflicts with the names of the keys. There definitely exists some set of plugins, where an identical key is used both for private setting name and metadata name.

**Comment by hypeJunction** [comment]
We can just prefix them. Conflicting keys is not an excuse for thousands of lines of useless code.

**Comment by jdalsem** [comment]
Please not work on this for Elgg 3.0 as it would open up a ton of work... please try to finish the running PR's and the regression issues caused please

**Comment by hypeJunction** [comment]
My priority is get the test coverage up. 60% coverage on engine is sh*t, doesn't invoke any trust. More lines of code, more tests they require. But I am already fed up and it doesn't seem like anyone else cares about shipping tested code.

**Comment by jdalsem** [comment]
> My priority is get the test coverage up. 60% coverage on engine is sh*t, doesn't invoke any trust. More lines of code, more tests they require. But I am already fed up and it doesn't seem like anyone else cares about shipping tested code.

i do care... but getting the tests to a certain percentage is not the goal at the moment. I feel we are still doing it a lot better than we used to do. I do not want to wait until we have an acceptable percentage with the beta release

**Comment by hypeJunction** [comment]
We are doing a lot better because I put in 200 hours into creating bootstraps, migrating tests, coverting a ton of code into OOP. and there is still no light at the end of the tunnel.
I don't see what's the rush with 3.0. There is already too much breaking changes, so might as well get it all done in one go and live with clean and tested code, rather than spending another 2 years implementing BC hacks, stacking more bad code on top of bad code.

**Comment by jdalsem** [comment]
> We are doing a lot better because I put in 200 hours into creating bootstraps, migrating tests, coverting a ton of code into OOP. and there is still no light at the end of the tunnel.

Thats why we have to live with the state as it is know... otherwise it will never be finished



> I don't see what's the rush with 3.0. There is already too much breaking changes, so might as well get it all done in one go and live with clean and tested code, rather than spending another 2 years implementing BC hacks, stacking more bad code on top of bad code.

3.0 is almost 2 years underway. We need to move forward, otherwise we wait another 2 years

**Comment by hypeJunction** [comment]
Do what you want
