### ISSUE TITLE
DBAL and ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11499]
Query builder doesn't support insert with update. How should we proceed? Use raw sql or select and then update/insert?

**Comment by jdalsem** [comment]
do we currently use `ON DUPLICATE KEY` in core?

**Comment by hypeJunction** [comment]
Yes. I have gone with Update and count rows, if 0 then insert

**Comment by jdalsem** [comment]
hmmm that is not really transactional... we still have a few usages of `ON DUPLICATE KEY`.. what does DBAL say we should do in these cases?

**Comment by hypeJunction** [comment]
Various forums suggest using raw SQL, which kind of defeats the purpose of DBAL. 
This is what I have done with private setitngs: https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Database/PrivateSettingsTable.php#L148
I think those writes are quite rare, so we can live with extra queries for now. We can implement better caching at a later point, now that we have a caching API, it should be easy.

**Comment by jdalsem** [comment]
going to stick with this for now
