### ISSUE TITLE
master: replies and comments no longer chronological

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11508]
I'm OK with us switching the direction as long as it's not a huge hassle to reverse it.

**Comment by jdalsem** [comment]
where do you experience this? i see them chronological...

**Comment by mrclay** [comment]
Master branch. We removed `reverse_order_by` but didn't fix the comments order to compensate.

**Comment by jdalsem** [comment]
i still do not see what is wrong with it... it was intensional to reverse the order... they still are chronologically however... newest first

**Comment by mrclay** [comment]
@Elgg/core are we committed to changing to newest-first comments in 3.0 by default?

Crazy idea: The default comments view (no offset) displays a link to "Load all comments", followed by the latest latest N comments in reading order, and the comment form.

**Comment by jdalsem** [comment]
> @Elgg/core are we committed to changing to newest-first comments in 3.0 by default?

yes... i believe both you and @hypeJunction liked the change



> Crazy idea: The default comments view (no offset) displays a link to "Load all comments", followed by the latest N comments in reading order, and the comment form.

nope

**Comment by mrclay** [comment]
OK I'm pushing upstream. See https://github.com/Elgg/Elgg/pull/11517#issuecomment-353464815
