### ISSUE TITLE
No longer possible to specify MariaDB / MySQL port since 2.0 upgrade

### ISSUE THREAD

**Issue by michaeldg** [Elgg/Elgg#11500]
Hi,

Since 2.0 version it is no longer possible to specify a port of the MariaDB server. This is needed when a client proxy, such as MaxScale or ProxySQL is used. 

I have fixed it here:
https://github.com/Elgg/Elgg/commit/470b3e8bb94b0830528b76f1df8378df8bca3245
I am working with a customer who uses Elgg but we are unable to test it in the customer's environment. And I am unable to setup a test environment due to firewall in the customer's guest network.

If somebody else could verify that my change works and that the test cases still pass I can make it a Pull Request. Let me know please.

**Comment by michaeldg** [comment]
PR would be from this branch: https://github.com/michaeldg/Elgg

**Comment by mrclay** [comment]
Looks right but needs to pass code style requirements. Travis will point out what to do.

**Comment by michaeldg** [comment]
Ah, yes, good point. I saw my tabs are different from yours. Anything else to change?

**Comment by mrclay** [comment]
`if(` should be `if (`. Our style is close to PSR-2.

**Comment by jdalsem** [comment]
why are we not allowed port number to be set explicitely via the config / settings.php? This feels like unnecessary magic...

**Comment by mrclay** [comment]
@jdalsem Good point. @michaeldg The port should be passed by its own config key `dbport`.
