### ISSUE TITLE
master: entering a incorrect path for dataroot crashes installer

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11511]
i entered `d:\htdocs\dataroot` as path... the settings step tries to create a cache path... this crashes.. probably missing a slash

updating the path to `d:/htdocs/dataroot/` in settings.php and refreshing the page worked

**Comment by hypeJunction** [comment]
Need to use ``Paths::sanitize()`` for all paths

**Comment by jeabakker** [comment]
I entered `D:\dataroots\elgg30beta\` same issue
