### ISSUE TITLE
Theming sandbox layout broken

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11516]
Some menu stuff is overflowing

In iFrame
![image](https://user-images.githubusercontent.com/881958/34210414-0d76b2aa-e596-11e7-8467-89fd317e56be.png)

In popout (or full view)
![image](https://user-images.githubusercontent.com/881958/34210462-3576f04e-e596-11e7-8514-4be9fab7f00c.png)

**Comment by jdalsem** [comment]
need to move theme sandbox to a normal default layout

**Comment by hypeJunction** [comment]
MIght be able to reuse some stuff form hypeUI. I did that there already.

**Comment by jdalsem** [comment]
did a similar thing in https://github.com/Elgg/Elgg/pull/10471
