### ISSUE TITLE
master: all DB queries hitting error log despite settings

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11547]
When we create the logger (before we set the level from the DB setting) we do this:

```php
$php_error_level = error_reporting();
		
if (($php_error_level & E_ALL) == E_ALL) {
	$this->level = self::INFO;
} ...
```

So even INFO level calls get written to the log before the boot is finished.

**Comment by mrclay** [comment]
E_ALL should probably map to NOTICEs, not INFO.

**Comment by jdalsem** [comment]
but how would you get info logs if you need them?

**Comment by mrclay** [comment]
@jdalsem See #11549
