### ISSUE TITLE
Elgg 2.3.5 Tests Page Not Found

### ISSUE THREAD

**Issue by p3core** [Elgg/Elgg#11558]
I am getting a **Page Not Found** error when I do unit tests...
https://mydomain.xyz/engine/tests/suite.php
I searched quite a bit for this error but I was not able to get a solution...
I thought this issue must be resolved...

Thanks

**Comment by mrclay** [comment]
Is it an Elgg 404 error page or something generated by your webserver?

**Comment by mrclay** [comment]
Wait, I bet you need to use this URL: https://mydomain.xyz/vendor/elgg/elgg/engine/tests/suite.php

**Comment by p3core** [comment]
@mrclay 
The RUN button points to the below URL;
https://mydomain.xyz/engine/tests/suite.php
The Error is generated by Elgg...
I am getting a **Fatal Error** when I run the test from the below URL;
https://mydomain.xyz/vendor/elgg/elgg/engine/tests/suite.php
**ERROR MESSAGE:-**
__Fatal Error: Class 'UnitTestCase' not found in C:\xampp\htdocs\xyz\vendor\elgg\elgg\engine\tests\ElggCoreUnitTest.php on line 9__

The core team must look into it...
