### ISSUE TITLE
master: logs always displayed, even to non-admins, and in js/css

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11560]
If you turn on logging, logs will be displayed to normal users and in js/css files, breaking them.

**Comment by mrclay** [comment]
I propose:

- Logger loses "display" setting. Calculate based on level != 0.
- Default log printer is LogPrinter (only error log)
- Only the developers plugin can send log data to HTML

Otherwise we need to pull logic out of developers plugin to use anytime display is true.

**Comment by mrclay** [comment]
See #11549

**Comment by jeabakker** [comment]
reopening as normal users and logged out users can still see the logging info if "Log to screen is enabled"

**Comment by jeabakker** [comment]
Sorry closing again as you want to be able to see debug logs for normal users and/or logged out users in case you're developing. As the developer tools plugin (mostly) isn't enabled on production sites leaving as is.
