### ISSUE TITLE
master: need to convert old page handler routes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11563]
@hypeJunction:
```
/engine/lib/admin.php:206
/engine/lib/admin.php:207
/engine/lib/admin.php:208
/engine/lib/admin.php:209
/engine/lib/admin.php:210
/engine/lib/comments.php:31
/engine/lib/cron.php:16
/engine/lib/filestore.php:142
/engine/lib/users.php:792
/engine/lib/users.php:793
/engine/lib/users.php:794
/engine/lib/users.php:795
/engine/lib/users.php:796
/engine/lib/users.php:797
/engine/lib/widgets.php:213
```

@mrclay
```
/mod/activity/start.php:68
/mod/bookmarks/start.php:25
/mod/dashboard/start.php:12
/mod/developers/start.php:20
/mod/developers/start.php:21
/mod/discussions/start.php:13
/mod/embed/start.php:23
/mod/externalpages/start.php:14
/mod/externalpages/start.php:15
/mod/externalpages/start.php:16
/mod/externalpages/start.php:17
```

@jeabakker
```
/mod/friends/start.php:13
/mod/friends/start.php:14
/mod/groups/start.php:23
/mod/invitefriends/start.php:14
/mod/legacy_urls/start.php:13
/mod/legacy_urls/start.php:14
/mod/legacy_urls/start.php:20
/mod/members/start.php:12
/mod/messageboard/start.php:16
/mod/messages/start.php:36
/mod/notifications/start.php:17
/mod/pages/start.php:22
/mod/profile/start.php:18
/mod/profile/start.php:21
/mod/reportedcontent/start.php:16
/mod/search/start.php:15
/mod/site_notifications/start.php:21
/mod/thewire/start.php:41
/mod/uservalidationbyemail/start.php:21
/mod/web_services/start.php:21
```

**Comment by hypeJunction** [comment]
Can we get 2-3 people to take of this? I can take over everything in `engine/`. Let's get it over with.

**Comment by mrclay** [comment]
How do we handle cases like `activity` and `activity/all` being the same route? Technically we could call `activity` the route "collection:river:default" (a distinct route) that happens to point to the same resource, but I think would be better to allow specifying multiple paths for the same route. The generator would use the first one to create URLs.

**Comment by mrclay** [comment]
Well we could use `activity/{ignored?}` as the path, but then if other plugins wanted to implement `activity/foo` they would need to also redefine `activity/{ignored?}` because it would match the first found. Actually I'm not sure how it would work.

**Comment by mrclay** [comment]
We should probably be combining all route declarations in all active plugins into 1 array, *then* registering them all. That would let later plugins override set routes like devs will expect.

**Comment by mrclay** [comment]
Nevermind, RouteCollection only keeps the last registered route per name.

**Comment by mrclay** [comment]
See #11567

**Comment by hypeJunction** [comment]
I think this is the last actionable thing before 3.0 RC. I don't have any more time this week though

**Comment by jeabakker** [comment]
I'm going to migrate all mod routes

**Comment by hypeJunction** [comment]
Are we done with this?

**Comment by jdalsem** [comment]
no

**Comment by jeabakker** [comment]
two plugins remaining 
- embed
- webservices

as we are removing legacy_urls from core

**Comment by hypeJunction** [comment]
Ah, ok. I am a bit tired of updating plugins for now.

**Comment by jdalsem** [comment]
we will be doing them

**Comment by jdalsem** [comment]
al page_handler registrations have been changed into routes!
