### ISSUE TITLE
Change plugin licenses

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11568]
I propose that we use MIT for all the newly added plugins: `activity`, `friends`, `system_log`.

`notifications` and `search` have been rewritten from scratch, so I'd license them as MIT as well.

**Comment by hypeJunction** [comment]
CC @brettp

**Comment by jdalsem** [comment]
we cannot change the license without the authorisation of all the authors. i currently see no benefit in changing the license. Closing for now
