### ISSUE TITLE
Allow inspecting routes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11571]
Although I'm glad to see the death of all these page handlers, it was easier to do a symbol search, type "page_han" and see most of our routes pop up. Though it will be great to see all our routes... basically everything the app can do in one place. You know, all that untested functionality!

**Comment by hypeJunction** [comment]
Converting resource views to objects would be a good cure for untested functionality :) https://github.com/Elgg/Elgg/pull/10319/files#diff-25751cda9455aea3c487edb686a095b8

- [ ] Wire up developers plugin to show routes and associated handlers/resources (linked to view inspector)
- [ ] Add a route test case and start testing routes (test matching, test matched params, test response code, testing actual output might be to much hassle)

**Comment by jeabakker** [comment]
fixed in #11667
