### ISSUE TITLE
Truncate cron handler output

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11603]
Cron handler output is written to private settings, and in case of very long output, it errors.

**Comment by jdalsem** [comment]
maybe write output to dataroot?

**Comment by hypeJunction** [comment]
Not a blocker

**Comment by jdalsem** [comment]
it is, as it is a know bug. RC should be free of known bugs

**Comment by hypeJunction** [comment]
I don't care enough for spend time on it.

**Comment by hypeJunction** [comment]
Plus it's a bug since 2.x
