### ISSUE TITLE
Friends' resources should probably only be visible to the logged in user

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11609]
a) Friendships should be considered private information
b) What's the relevance for someone to see someone else's friends' stuff

**Comment by jdalsem** [comment]
Maybe so you can see what 'Friends of Ismayil' are doing... Don't know why it should be protected... you are not seeing something that is not for your eyes...

Maybe some end users could be questioned about this behaviour?

**Comment by hypeJunction** [comment]
I have worked on networks, where friends/followers information was not public. There should be an easier way to restrict access to anything that exposes friendship information.
Additionally, friends routes shouldn't even be registered if friends plugins is not enabled.

**Comment by jdalsem** [comment]
Maybe as mentioned in #11605 adding access to routes could limit access to FRIENDS of page_owner? Or add a plugin dependency/requirement in the route definition?

**Comment by jdalsem** [comment]
https://github.com/ColdTrick/no_friends :)

**Comment by jdalsem** [comment]
I do not think there can be consensus about the suggestion that friends relationship should/could be private and what that would imply for Elgg. 

I created #12712 to limit routes to other plugins
