### ISSUE TITLE
Phinx upgrade slow when running in browser

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11601]
That makes no sense and feels a bit slow... is there something we can do to improve that? Could not be a problem for now, but certainly in a few years where there will be more upgrade scripts.

**Comment by hypeJunction** [comment]
That's the idea of migrations. We don't have to go back and alter old migrations, they run in sequence.
I am not sure why they are slow though, running from command line is really fast. Perhaps the problem is in the console wrapper classes.

**Comment by jdalsem** [comment]
maybe it is just an issue on my development machine and not in a real life situation :)

**Comment by hypeJunction** [comment]
I did notice slowness then when running installer from browser. Not sure what it relates to though.

**Comment by jdalsem** [comment]
It is not that bothering that it deserves any attention at the moment
