### ISSUE TITLE
suggestion: add access to routes

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11605]
just like actions.... access => 'logged_in'... saves adding a gatekeeper

good idea @hypeJunction ?

**Comment by hypeJunction** [comment]
What I have in mind is the ability to replace all the gatekeeper junk with some sort of middleware definition a-la Laravel.
Adding access would be a good start, but there is also walled garden, and I would like that to be extendable - add custom logic without having to hijack the route.

```php
return [
    'routes' => [
        'foo' => [
            'path' => '/bar',
            'resource' => 'bar',
            'middleware' => [
                 \Elgg\Gatekeeper::class,
                 \Elgg\NoWalledGarden::class,
                 \MyPlugin\Paywall::class,
            ],
        ],
    ],
];
```

**Comment by jdalsem** [comment]
well at least we now have a good point to extend/add features

**Comment by hypeJunction** [comment]
Let's leave it for later. I need to figure it out in my head

**Comment by jdalsem** [comment]
With the middleware config in place there is no need for an extra `access` parameter in the config that does the same (and is even more limited).
