### ISSUE TITLE
routes: should we transform query params into resource view vars?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11600]
That removes the need to do get_input in resource views... 

/cc @hypeJunction

**Comment by hypeJunction** [comment]
We couldbut I have a strange feeling about it, but can't pin point why. Let me sleep on it.

**Comment by jdalsem** [comment]
usecase = `search?q=query` for example

**Comment by jdalsem** [comment]
Decided to leave this as is. There is not real gain (not a single line of code to win). Having a distinction between route parameters and query parameters (and how to get them) will make devs more concious on the difference (also related to how they are filtered).
