### ISSUE TITLE
License in compose.json is deprecated

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11610]
as a result (currently) Packagist isn't updating. 

To what should we update the license `GPL-2.0-only` or `GPL-2.0-or-later` for a list of supported licenses see https://spdx.org/licenses/

Packagist issue https://github.com/composer/packagist/issues/858

**Comment by jeabakker** [comment]
@Elgg/core @Elgg/contributors opinions?

**Comment by hypeJunction** [comment]
I think GPL 3 is significantly different.

**Comment by sembrestels** [comment]
Some of the plugin's code (such as groups) is GPLv2-only, so unfortunately if Elgg is packaged with all its plugins, it must have `GPL-2.0-only` license.

**Comment by jdalsem** [comment]
When Elgg changes license, the plugins will also change licenses i assume

**Comment by jdalsem** [comment]
The issue with packagist is a confirmed bug on their side
