### ISSUE TITLE
master: experiencing frequently a 30sec timeout after cache flush

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11618]
Maybe something related to Stash?

Seeing this a lot:
```
"unlink(D:/htdata/23jan2018\\1952a01898073d1e\\561b9b4f2e42cbd7\\38a865804f8fdcb6\\57cd99682e939275\\263a120f26b016a4\\2cc36b3a40e87525\\7572559ca86e781b\\a8fe8073a0b725c6\\af3a232fb3b7898f\\12135a8956bf78d0.php): Resource temporarily unavailable" in file D:\\htdocs\\core19\\vendor\\tedivm\\stash\\src\\Stash\\Driver\\FileSystem.php (line 326),
```

**Comment by hypeJunction** [comment]
I think it's Windows being stupid. I have the same issue. My guess is Windows is locking those files when reading. Could someone on Linux see if it's an issue?

**Comment by hypeJunction** [comment]
One proposal I would have is to put file cache into `/cache` directory and then just wipe it without using Stash.

**Comment by hypeJunction** [comment]
Also now that we have an abstraction layer we can switch to Doctrine or something else
