### ISSUE TITLE
Fix ElggCrypto tests

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11625]
@mrclay I discovered today that a bunch of unit tests were not autoloads, and hence weren't running for months. I have fixed what I could, but ElggCrypto is a bit odd and I couldn't make sense of it. Could you take a look and see if you can fix it? https://github.com/Elgg/Elgg/pull/11624/commits/fb6698d1d54c6562bed0dc0bf6925b9b289a7184#diff-9c573e6f88c7d060d5e135a8047423d6R63

**Comment by mrclay** [comment]
Ugh, maybe make it a thin wrapper of something with tests. https://packagist.org/packages/pragmarx/random

**Comment by hypeJunction** [comment]
Maybe just throw that test away and write a new test  for  the output length and intersect chars

**Comment by mrclay** [comment]
It's mostly based on https://github.com/zendframework/zend-math/blob/release-3.0.0/src/Rand.php might as well use that.
