### ISSUE TITLE
master: cannot use plugins with camelcase name

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11648]
ran into this during upgrade with the hypeFaker plugin

ref #8963

**Comment by jdalsem** [comment]
do we still want to allow this? see also discussion in #8963

**Comment by jdalsem** [comment]
does it have languages?

**Comment by hypeJunction** [comment]
no

**Comment by jdalsem** [comment]
i am looking into this

**Comment by jdalsem** [comment]
i can no longer reproduce this issue

**Comment by hypeJunction** [comment]
You probably have run into an issue because a plugin wasn't returning an array from the language file, but was using add_translations()
