### ISSUE TITLE
Intermittent issues with route test

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11643]
Example here https://travis-ci.org/Elgg/Elgg/jobs/331832362#L1043

Restarting the job might fix it

**Comment by hypeJunction** [comment]
To get anywhere with these tests we need to review and rewrite the boot sequence. It's expensive, inconsistent and not OOP. I don't have any more energy or good will to be dumping into Elgg. I have other things I'd rather be doing. I have put in over 1000 hours into this release and it's unhealthy. I am out.

**Comment by hypeJunction** [comment]
This is keeping me up at night, so I am going to get down the bottom of this.

**Comment by jdalsem** [comment]
have fun!

**Comment by jdalsem** [comment]
when fixing this https://github.com/Elgg/Elgg/pull/11662 it shows all kinds of new view related errors.... that were previously missed (or not tested)... might also cause routing issues maybe?

**Comment by hypeJunction** [comment]
maybe, if there are cache latency problems, maybe some entities become unavailable...
I have also fixed some issues with seeder in the gatekeeper PR, which were replacing falsey values for int properties.

**Comment by hypeJunction** [comment]
Can be closed
