### ISSUE TITLE
Make 3.0.0-beta release

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11642]
- [x] manual test fresh install
- [x] manual test upgrade 2.3 to 3.0-beta -> no upgrade specific issues
- [x] double check upgrade docs/instructions
- [x] run release script
- [x] tag release
- [x] create `3.x` branch
- [x] make `3.x` branch the default branch
- [x] protect the `3.x` branch from deletion/force pushes
- [x] update Transifex auto update resources (so we don't have to push for new keys)
- [x] check starter-project in order to be able to create zip release on community
- [x] branch starter project 
- [x] update the docs
- [x] make zip release for community

**Comment by hypeJunction** [comment]
Branch starter project and update the docs

**Comment by jdalsem** [comment]
Running a manual upgrade from 2.3 to master worked fine (besides the issue with camelcased plugins not working #11648)

**Comment by jeabakker** [comment]
Beta PR #11672

**Comment by jeabakker** [comment]
BETA IS OUT!

**Comment by jeabakker** [comment]
I updated the starter-project

- created a `2.x` branch for supporting releases of 2.x
- in `master` changes have been made to support 3.x releases

**Comment by jeabakker** [comment]
made a zip release, but it's broken, need a beta.2
