### ISSUE TITLE
cli: can't run cli from starter-project

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11679]
During the composer install `elgg-cli` is copied to `vendor\bin\elgg-cli` and when i try to run it from the commandline (in the root of my project, eg the starter-project) i get the error:

`Composer dependencies are not installed or you are trying to run the script outside of an Elgg installation's root directory.`

It couldn't load the `autoload.php` file https://github.com/Elgg/Elgg/blob/3.x/elgg-cli#L10-L14

And maybe the check fo the settings file https://github.com/Elgg/Elgg/blob/3.x/elgg-cli#L28 also needs a review.

**Comment by hypeJunction** [comment]
Try `php ./elgg-cli list`
