### ISSUE TITLE
z-index issue with sysmessage and widget add panel lightbox

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11688]
![image](https://user-images.githubusercontent.com/861833/35684141-46fb857c-0766-11e8-9ed6-7fb19c4fb22d.png)

**Comment by jdalsem** [comment]
maybe... but this was an error that existed before opening the lightbox... maybe we should close messages when opening a lightbox?

**Comment by hypeJunction** [comment]
I'm not sure how the JS looks now, but last time I checked it wasn't very OOP out there, so it might be a hassle.

**Comment by jdalsem** [comment]
Can be fixed by #11749 and #11748
