### ISSUE TITLE
should elgg_generate_url trigger the error on missing route

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11694]
If you want to generate a link based on a route name that is not configured (because the plugin is not enabled) it now logs an error... is this what we want? Maybe a NOTICE makes more sense... 

Use case:
link to `activity/all` but the plugin is disabled `elgg_generate_url` returns an empty string (which is fine) if route is not configured... i can act on that.. but i do not want to see the error in the log

**Comment by hypeJunction** [comment]
I think the question should be why activity/all is outside a plugin. 
I don't mind downgrading to notice.

**Comment by jdalsem** [comment]
i just created a widget in my own plugin with a link in it to `activity/all`... would like to be able to use elgg_generate_url for that... or a theme that adds a menu item somewhere.... they can't check if the plugin is enabled as the route could theoretically be provided by another plugin

**Comment by hypeJunction** [comment]
Let's downgrade the error and return false to indicate unregistered route
