### ISSUE TITLE
REST API ?

### ISSUE THREAD

**Issue by CristianCardosoA** [Elgg/Elgg#11695]
Is there any REST API ? I'm developing a native mobile IOS App, so I'm wondering If Elgg contains a REST API to retrieve friends, comments, posts, feed, etc.

**Comment by hypeJunction** [comment]
Elgg comes bundled with web services plugin, which provides RPC API.

**Comment by jdalsem** [comment]
Take a look at the docs here http://learn.elgg.org/en/stable/guides/web-services.html
