### ISSUE TITLE
master / 3.0-beta: max-width too wide on large screens or not used?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11709]
Usage of full width on large screen seems problematic to me. Isn't there any maximum width anymore at all? Mobile first approach is fine but if you have a width > 1000 on a desktop it becomes too wide when using the full width (maybe not even with a sidebar as on the activity page). Too read any text or text excerpt if the lines are so long is no longer easily possible.

As I understand there was a change to get page body and topbar width in line (as it seems not by restricting top bar width but the other way round). Is it working as intended - with no upper limit apparently - or is is not working as intended. If it's working as intended is it done in a way to easily allow setting an upper limit by a theme plugin?

**Comment by hypeJunction** [comment]
There is an upper limit of 1280px, which is more or less a standard these days.

**Comment by hypeJunction** [comment]
The media queries are in the theme variables, so you can change them with a hook. 

From the docs:
```
vars:compiler, css
Allows plugins to alter CSS variables passed to CssCrush during compilation. See CSS variables <_guides/theming#css-vars>.
```

**Comment by iionly** [comment]
Need to test this out a lot more to understand. Changing desktop width variable also affects the topbar (on reduction gets messed up) and whole elgg-inner area. I was referring to the main column mainly that seem getting too wide to me on large screen with the whole width used (regarding length of lines for text). I guess it's a theme plugin development issue not not a core issue to get it right (e.g. with the page content still centered when setting a max-width for elgg-body).
