### ISSUE TITLE
master / 3.0-beta: no margin or padding on left border

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11707]
Seems to be that all forms and the page body is directly starting on the left border without any padding or margin on the site frontend. In the admin adrea this seems different and there's some margin on the left.

Is the missing margin intentional? Looks quite strange to me.

**Comment by hypeJunction** [comment]
I see sufficient padding on all screen sizes.

**Comment by iionly** [comment]
It might be that the screen resolution of 1280x800 that I can test it with is an unlucky one. If I slightly decrease width of the browser window I get a padding on the left. Just with 1280 (possibly a bit less window resolution due to window borders and scrollbar) the left padding is gone and the fields and labels start at the left window border.

**Comment by hypeJunction** [comment]
That's a possibility. We can probably add some "safe space" to the media query

**Comment by hypeJunction** [comment]
I am not inclined to provide a fix for this. This situation would only arise when the viewport width is 1280px exactly, which is a very unlikely scenario, even then all content fits, it's just the lack of padding on each side. Themes can deal with it if they want to. Once `calc()` is supported in media queries we can deal with it, for now I don't have a solution except for targeting viewport width between 1275px and 1285px to add some padding... meh 😒 
https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by hypeJunction** [comment]
I don't think there are tablets with resolution that high. We can add padding globally, but I am not sure it's worth the effort. I have looked at the stats and devices at 1280px account for 3% of devices. It's not a very common resolution, most is either a lot more or a lot less. I'd just wait and see I we get any more issues reported.

**Comment by iionly** [comment]
I wouldn't be surprised if no one would complain, so closing.
