### ISSUE TITLE
master / 3.0-beta: custom_index plugin has all widgets in the left column

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11708]
css class of right column seems wrong.

**Comment by jdalsem** [comment]
i do not have this issue... when is this happening? screenshot?

**Comment by iionly** [comment]
On closer inspection of the code it seems the problem might not be within the custom_index plugin itself (where I get all widgets in one column on the index page even if the code is supposed to create two columns) but rather a more general issue with grids. The grids page of the theme sandbox also shows all columns below each other and not side-to-side as expected. See screenshot:

![sandbox_grids](https://user-images.githubusercontent.com/1773681/36112563-618e927c-102a-11e8-883c-a1e9e7cf58d0.png)

**Comment by jdalsem** [comment]
hmm.. still do not have the same problem...

Did you do a composer install? 
Which PHP version? 
Which browser?
Any errors in the error log?

**Comment by hypeJunction** [comment]
Sounds like a cross-browser compatibility issue. What browser do you use and does it fully support flexbox?

**Comment by iionly** [comment]
I did a composer install with the master (3.x) starter project. PHP version 7.2.2. I tried with FF 52.6 (LTS) and latest Palemoon browsers. That's what I can test with. Any idea if FF 52 already did fully support flexbox?

**Comment by hypeJunction** [comment]
I think it does. I will check later

**Comment by hypeJunction** [comment]
I thought that CssCrush adds vendor prefixes, maybe that's the culprit

**Comment by jdalsem** [comment]
it should

**Comment by iionly** [comment]
I've configured my notebook to allow for external apache access so I could test on a newer browser and on a higher resolution.

It seems it's a matter of screen resolution != usable resolution within the browser window. The notebook screen has a resolution of 1280x800 px but within the browser window the resolution is smaller due to window borders. So, the available width is below the desktop variable limit of 1280 px resulting in all columns getting displayed below each other. With a higher screen resolution the grid is displayed correctly in the sandbox and the index page widgets are displayed in two columns.

Still, it's really rather odd to have only one column available at a width of 1280 px. It's seems much too wide for just a single column to me.
