### ISSUE TITLE
2.3.5: PHP warning flooding logs

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#11704]
`WARNING: 2018-02-09 08:12:17 (UTC): "count(): Parameter must be an array or an object that implements Countable" in file /var/www/html/wtm/docroot/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php (line 934), referer: http://localhost:8100/`

Happens when getting entityWhereSql for a subtype-less entity such as ElggUser

**Comment by jeabakker** [comment]
fixed in #11820
