### ISSUE TITLE
.elgg-fieldset-has-legend needs margin bottom

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11703]
having multiple fieldsets after eachother looks weird... 

maybe the margin should be added on every fieldset...

**Comment by jdalsem** [comment]
maybe only a problem on admin

```
fieldset {
    border: none;
    margin-bottom: 1rem;
}
```

**Comment by hypeJunction** [comment]
Fieldsets are overused, so if you don want to add margins, at least to `fieldset + fieldset` and add top margin.

**Comment by jdalsem** [comment]
a lot of fieldset css rules broken by the changes in https://github.com/Elgg/Elgg/commit/521041d340dbc7d9b6dfba3cd0ecef18f38efc7b

reasons for those changes was #11245... might even consider reverting that extra div



also should `legend` be a direct child of `fieldset`... i think so

**Comment by hypeJunction** [comment]
`fieldset` is a very dumb markup element that doesn't respect many of the CSS rules, including flex, hence extra div. But yes, legend should be a direct child

**Comment by hypeJunction** [comment]
Do  you have a screenshot of a problem you are trying to fix with this?
