### ISSUE TITLE
running unit tests with a settings file fails

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11713]
I configured a settings file as per https://github.com/Elgg/Elgg/blob/3.x/phpunit.xml#L10 in a project. And i encountered errors.

`icon_sizes` weren't configured and other errors.

Maybe https://github.com/Elgg/Elgg/blob/3.x/engine/tests/classes/Elgg/BaseTestCase.php#L50 should merge the settings file with default values

**Comment by jeabakker** [comment]
I configured a settings file because i encountered an error in the Stash cache path with max path length on Windows. I wanted to change cachepath to `sys_get_temp_dir()` but that required a settings file, couldn't be done with a ENV var

**Comment by hypeJunction** [comment]
Settings file would have to specify all values needed by tests. Otherwise it gets really confusing.

**Comment by jdalsem** [comment]
why... regular site operation also does not need the full settings...

**Comment by hypeJunction** [comment]
At what point do you decide which settings are to be used and which not? I think the idea of the settings file in tests is to provide full controls of the environment.

**Comment by jdalsem** [comment]
Keeping current situation for now... not that bothering
