### ISSUE TITLE
3.0-beta: module layout in IE

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11715]
this is from the theming sandbox
![image](https://user-images.githubusercontent.com/881958/36152154-3de68e38-10ca-11e8-8441-54597f29050b.png)

header titles should be on the left side, not right

Also on the user settings page

**Comment by hypeJunction** [comment]
Are we talking IE or Edge?

**Comment by jeabakker** [comment]
IE haven't tested Edge (yet)

**Comment by hypeJunction** [comment]
Sorry, I am not going to bother with IE11

**Comment by jdalsem** [comment]
we will

**Comment by jdalsem** [comment]
```
.elgg-module > .elgg-head {
	display: flex;
	justify-content: flex-end;
	align-items: center;
}
```

```justify-content: flex-end;``` might be the culprit... why not `flex-start`

**Comment by hypeJunction** [comment]
Because that pushes out the menu if there is one. You can try adding margin-right: auto
