### ISSUE TITLE
unable to save text with unicode chars

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11716]
Test with 😉 smiley

Saving the text above (just copy paste to Elgg) is failing. Should the utf8 upgrade by @mrclay have fixed that problem?

**Comment by hypeJunction** [comment]
It works for me. I already wrote a plugin for inserting emojis, and they work fine in title and description.

**Comment by jdalsem** [comment]
executing 'INSERT INTO elgg_30testmetadata (name, entity_guid, value, value_type, time_created) VALUES(?, ?, ?, ?, ?)' with params [\"description\", 141, \"Test with \\ud83d\\ude09 smiley\", \"text\", 1518530074]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value:

**Comment by jdalsem** [comment]
problem in multiple installations on 2.3 and on master

**Comment by jdalsem** [comment]
> It works for me.

2.3 and master?

**Comment by hypeJunction** [comment]
2.3 never had support for mb4 chars

**Comment by jdalsem** [comment]
Fun thing... 
- 2.3 just truncates data 
- my master installation throws a database exception
- other master installation replaces unicode chars with ?????

**Comment by hypeJunction** [comment]
Adding a test to verify would go a long way

**Comment by jdalsem** [comment]
Needs retest

**Comment by jdalsem** [comment]
still getting this... will try to reset my dev environment to get a clean test

**Comment by jeabakker** [comment]
no problems for me

**Comment by jdalsem** [comment]
hmm tried on client installation and it works.. assuming this is an issue with my local isntallation/config
