### ISSUE TITLE
.elgg-menu-hz menu items should get margin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11729]

**Comment by hypeJunction** [comment]
Menu items have padding to increase click area. No need for margins

**Comment by jdalsem** [comment]
if you have a menu styled with `elgg-button` this causes problems.. only thing that rest is adding 
'item_class' => 'mrm', or adding custom css... is that what we want? can live with that

**Comment by hypeJunction** [comment]
Good point. Let's keep open for now
