### ISSUE TITLE
elgg-3: elgg_get_entities_from_plugin_user_settings pairs fails

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11739]
set a plugin user setting for a user and try to retrieve it with name_value_pairs, this fails

```php
$options = [
		'type' => 'user',
		'limit' => 1,
		'plugin_id' => 'somepluginid',
 		'plugin_user_setting_name_value_pairs' => [
 			'name' => "somename",
 			'value' => 'somevalue',
 		],
];
```

but this succeeds
```php
$options = [
		'type' => 'user',
		'limit' => 1,
		'plugin_id' => 'somepluginid',
		'plugin_user_setting_name' => "somename",
		'plugin_user_setting_value' => 'somevalue',
	];
```

cause 'prefix' only get's appied to 'names' not 'name' in a pair
https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/Database/LegacyQueryOptionsAdapter.php#L480

**Comment by hypeJunction** [comment]
Are you sure it ever worked like that? As far as I remember that was supported by metadata pairs, but with private settings, you had to nest the array.

**Comment by jeabakker** [comment]
no not sure, but i expect it to work the same ;)

**Comment by hypeJunction** [comment]
Well, if there are no tests for it, there is no way of knowing. I am not a big fan of user settings, so won't be putting time into it.
