### ISSUE TITLE
FR: elgg_clear_sticky_form should return saved values

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11734]
now returns `void`
so i have todo
```php
$vars = elgg_get_sticky_values('some form');
elgg_clear_sticky_form('some form');
```
why not
```php
$vars = elgg_clear_sticky_form('some form');
```

**Comment by jdalsem** [comment]
this depends a lot on how you do thinks... i think it would be wise not to touch these functions. Optimization of stickyforms can be done somewhere else

**Comment by jdalsem** [comment]
staying with my previous comment
