### ISSUE TITLE
FR add plugin settings param to flush cache on settings save

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11745]
i have multiple plugins that have the need to flush cache after a plugin settings save

to prevent to use custom plugin settings save actions, a plugin settings save hook or a action hook to flush the caches, i would like to be able to add a hidden form input to flush cache on the plugin settings form.

This way i can just add
```
elgg_view_field([
'#type' => 'hidden',
'name' => 'flush_cache'
'value' => 1,
]);
```
on the plugin settings form. The default action will just check the existence of this input and flush the cache.

**Comment by hypeJunction** [comment]
Maybe we should just always flush it on settings changes.
