### ISSUE TITLE
unable to login direct after registration (with no validation plugins)

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11752]
it looks like i am not logged in... maybe some session issue?

I thought after a registration i would be logged in immediately. After a refresh i was logged in... maybe an issue with last forwarded from.... need to investigate more. (Happenend on FF)

**Comment by jeabakker** [comment]
probably the new session_id (which is stored in a cookie) doesn't get set due the elgg/Ajax

**Comment by hypeJunction** [comment]
Could be a side effect of changes I made in https://github.com/Elgg/Elgg/pull/11742, which probably doesn't replace the cookie when it's simply sent with Ajax response. I am in bed sick, can look next week

**Comment by hypeJunction** [comment]
Can you verify that his been fixed with latest Ajax and login changes?

**Comment by jdalsem** [comment]
This currently works fine
