### ISSUE TITLE
page/components/tabs should not draw a module... 

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11756]
having tabs in elgg-head of module causes styling issues... it also makes no sense... it is a component... not a module

**Comment by hypeJunction** [comment]
It was a tabbed module, so it made sense that tabs were in the module head. Now it's all messed up.

**Comment by jdalsem** [comment]
What is messed up

Op 26 feb. 2018 7:00 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:

**Comment by hypeJunction** [comment]
You render two semantically incoherent elements within module body. You can't target the tabs as a standalone element - if I want to style tabs like the module header (e.g. add some background and span them accross the module width), I have to do weird stuff with CSS. When you target module body you also affect the tabs. The idea was too keep them independent from each other. It's easier to destyle module header, then to style tabs as a module header within module body.

**Comment by jdalsem** [comment]
will revert this specific fix https://github.com/Elgg/Elgg/commit/a47b24c370ed6fb3d3a81716b0f6d120f0844adf as https://github.com/Elgg/Elgg/pull/11765 also solved the problems i had with having tabs in the header
