### ISSUE TITLE
is having unwalled action by default the intended behaviour

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11759]
registering actions via elgg-plugin or via elgg_register_action will set `walled = false` for the action router... is that intended?

/cc @hypeJunction

**Comment by hypeJunction** [comment]
That's how it always was. Not sure if that's how we want to keep it moving forward

**Comment by jdalsem** [comment]
i am not sure that is how it always was (as i needed to create hook for actions in the past to allow outside of walled garden)

**Comment by hypeJunction** [comment]
All actions were excluded from walled garden. Check the config, it's `action/.*`

**Comment by jdalsem** [comment]
i see... i was looking at remnants from plugin code for Elgg 1.8... `action/.*` is allowed since Elgg 1.9
