### ISSUE TITLE
unable to use login as plugin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11764]
Switching user causes me to log out (maybe related to #11752)

**Comment by jdalsem** [comment]
seems to be working now... maybe a fluke on my install

**Comment by jdalsem** [comment]
worked on profile of the users... not on a group profile? need more info

**Comment by hypeJunction** [comment]
Happening to me intermittently as well. Not sure what the problem is...

**Comment by hypeJunction** [comment]
I tried to get to the bottom of this yesterday at no avail. I think something odd is happening during redirect and either the new session is not properly created or the cookie is lost somewhere during the response.

**Comment by jdalsem** [comment]
occurs everywhere... selecting login as from a user hover menu results in being logged out

**Comment by hypeJunction** [comment]
Can't reproduce

**Comment by jdalsem** [comment]
will try to retest with latest version

**Comment by jdalsem** [comment]
still have problem

**Comment by jeabakker** [comment]
no problem for me

**Comment by jdalsem** [comment]
tested with a client installation and also no problem, so assuming this is something related to my installation/config
