### ISSUE TITLE
elgg-3: Ajax.objectify no longer works with non form elements

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11809]
https://github.com/Elgg/Elgg/pull/11747 changed the supported elements which can be sent to `Ajax.objectify()`. Before it was any element (eg an `input` element).

Now only `form` elements can be provided, otherwise an error `TypeError: Argument 1 of FormData.constructor does not implement interface HTMLFormElement.` occurs.

cc @hypeJunction

**Comment by hypeJunction** [comment]
I don't think using inputs without forms is a good idea to start with.

```js
var data = new FormData();
data.set('my-input', $('#my-input').val());
elgg.action('action', {
   data: data
});
```
