### ISSUE TITLE
Feature request: Heroku install instructions (and I'll help!)

### ISSUE THREAD

**Issue by karlbecker** [Elgg/Elgg#11818]
Hello!
I was wondering if someone would like to help me create easy Heroku installation instructions. 

Ideally, we could create a ["Deploy to Heroku" button](https://devcenter.heroku.com/articles/heroku-button) to allow anyone to deploy this very easily.  However, if that's not too easy with the steps needed for installation, maybe we could just write up simple instructions for it.

Anyone able to help me with this?  I'm aiming for total simplicity in instructions, so we can get as many people moved off of, say, Facebook or Twitter, and onto an open-source, not-for-profit system like Elgg.

Thanks!

**Comment by hypeJunction** [comment]
I can help with directions, if you are stuck :)

**Comment by karlbecker** [comment]
Absolutely no progress 😊 
Hopefully someone can take it over!

**Comment by hypeJunction** [comment]
FYI, I don't think Elgg will even work on Heroku, because Heroku has an ephemeral file system, hence none of Elgg's dataroot usage will be possible.

**Comment by jdalsem** [comment]
Closing as no one is working on this
