### ISSUE TITLE
_elgg_walled_garden_remove_public_access plugin hook callback can't be unregistered

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11811]
In ElggSite.php the _elgg_walled_garden_remove_public_access() callback is registered for the 'access:collections:write', 'all' plugin hook. As it seems it's not possible to unregister this callback from a plugin if you want to get the public access level back with walled-garden enabled.

**Comment by hypeJunction** [comment]
It is possible, as I did once, but had to do some crazy hacking. I need to dig out that code

**Comment by jeabakker** [comment]
we'll fix it
