### ISSUE TITLE
rethink active/inactive plugin logic in plugins db/service vs plugin entity

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11827]
follow up on #11826

no rush... this can be improved later on

**Comment by hypeJunction** [comment]
I think plugins shouldn't be entities to start with. It would be a lot easier to have two DB tables one for plugins with their status and second for plugin settings.

**Comment by jdalsem** [comment]
We are not going to change anything about the current logic. The plugins service knows the states of all plugins, thus has the ability to cache that knowledge.
