### ISSUE TITLE
Elgg-3: get_user_by_username should be case insensitive (like 2.3)

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11841]
With the change to metadata this changed.

**Comment by hypeJunction** [comment]
Metadata name value pairs support case_sensitive.
But in the long run, usernames can not be case sensitive because we use them in URLs. We will end up with clashing usernames. /profile/Someone and /profile/someone should be identical

**Comment by jdalsem** [comment]
so you agree with the change then :) as this PR makes it insensitive

**Comment by jdalsem** [comment]
thought this was a PR... nevermind... still it needs to change to insensitive

**Comment by hypeJunction** [comment]
Oh,I misread the title. Yes, agreed
