### ISSUE TITLE
Simple editor and embed menu

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11847]
Should embed menu be available when editor is in a simple mode?

**Comment by jdalsem** [comment]
good question... but i could argue for both cases

**Comment by hypeJunction** [comment]
I have been extending embed with some custom stuff, and I feel like when it comes to comments, some of those elements are an overexaggeration.

**Comment by jdalsem** [comment]
Going to leave this as is. You can remove the link for simple editors if needed
