### ISSUE TITLE
3.x: cant do a fresh install

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11852]

**Comment by hypeJunction** [comment]
I had a ton of issues on 7.0, but everything went smoothly on 7.2

**Comment by jdalsem** [comment]
i'm on 7.2

**Comment by hypeJunction** [comment]
All tests would have failed, no?

**Comment by jdalsem** [comment]
yes, but i am IRL

**Comment by jeabakker** [comment]
tried the following
- install using `elgg-cli`: no problems
- install using browser: fatal error

The fatal error is caused by `elgg()` which tried to get the DI Definitions from the active plugins. Since there is no database this crashed.

**Comment by jeabakker** [comment]
we need to make https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/Database/Plugins.php#L713 work in 'install' mode

**Comment by jeabakker** [comment]
maybe we need to re-implement https://github.com/Elgg/Elgg/blob/2.3/engine/classes/Elgg/Database.php#L631 or something similar so that the database knows it's correctly configured/installed

**Comment by hypeJunction** [comment]
I am looking into it now
