### ISSUE TITLE
CSS doesn't handle SVG entity icons

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11853]
We have addes support for SVG icons a while back, but having tried to use them, there are no CSS rules to actually make them work.

**Comment by ObeeWanKenobee** [comment]
@hypeJunction this should do the trick right?

background: transparent url(icons.svg#icons) no-repeat;

or use svgxuse.js plugin from https://github.com/Keyamoon/svgxuse

I use svgxusejs plugin in my project and is working perfectly fine

**Comment by hypeJunction** [comment]
The problem is image containers that either overflow or shrink. We need to add some rules so they are appropriately sized

**Comment by ObeeWanKenobee** [comment]
oh, ok.

can I see your css so I can help?

**Comment by hypeJunction** [comment]
Add an svg entity icon to your plugin views (see entity icon docs) and you will see what I am talking about.

**Comment by jdalsem** [comment]
At the moment we do not use svg images in core projects and are not planning to do so very soon. It is currently not worth the effort to put in time to investigate how we need to handle this.
