### ISSUE TITLE
cpanel virus wearning

### ISSUE THREAD

**Issue by obddahl** [Elgg/Elgg#11864]
The file you uploaded, elgg-2.3.6.zip, contains a virus so the upload was canceled: {HEX}php.exe.globals.409.UNOFFICIAL FOUND

**Comment by obddahl** [comment]
ok glad there is no virus, but  makes it  impossible  for me to  upgrade

**Comment by hypeJunction** [comment]
This value has been there all along.

**Comment by obddahl** [comment]
Hate technology more and  more, always causing  problems.
we can spend half our life try solving them, getting  nowhere.

**Comment by obddahl** [comment]
solved it  by  upload  via  ftp instead
