### ISSUE TITLE
ElggInstallerTest::testBatchInstall fails localy

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11878]
if i run `vendor\bin\phpunit -c .\phpunit.xml --filter ElggInstallerTest` localy the test fails. Travis has no problems.

Propably the database mock is wrong, but on travis it uses the actual database

**Comment by hypeJunction** [comment]
Works for me, but I do have DB set up with env vars

**Comment by jdalsem** [comment]
Currently unable to reproduce with and without env vars and also without settings.php
