### ISSUE TITLE
Elgg 2.3: class ElggCrypto not found whe executing seeder script or use _elgg_services()->seeder->seed();

### ISSUE THREAD

**Issue by aleamb** [Elgg/Elgg#11873]
Hi.

I Have tried to seed database with fake data through adding an API call with webservice plugin. My start.php is

```
/**
 * Init plugin1 plugin.
 */
function plugin1_init() {

    elgg_ws_expose_function(
        "test.seed",
        "seed",
        [],
        'Service for seed database',
        'GET',
        false,
        false
);
}
function seed() {
    _elgg_services()->setValue('mailer', new \Zend\Mail\Transport\InMemory());
    _elgg_services()->seeder->seed();
}

```

Calling that method throws error:

"Class '\\Elgg\\Database\\Seeds\\ElggCrypto not found'

In line 478 of vendor/elgg/elgg/engine/classes/Elgg/Datavase/seeds/Seed.php it  should be new \ElggCrypto() but new ElggCrypto() instead?

If execute seed.php from .scripts directory, it gets shame error.

**Comment by hypeJunction** [comment]
In 2.3 seeding API is still private, and won't be made public until 3.0. We are only using it to test upgrade paths from 2.3 to 3.0. I will look into the issue regarless.

@jeabakker I see that 2.3.6 build is broken but the release was made anyway. https://travis-ci.org/Elgg/Elgg/jobs/358930562

**Comment by aleamb** [comment]
Nice. 
Thanks, hypeJunction.

**Comment by hypeJunction** [comment]
@aleamb If you are starting a new project, you might as well try Elgg 3. It's still in beta, but pretty stable. I am building my first Elgg 3.0 project and it's a lot more fun to work with.

**Comment by aleamb** [comment]
@hypeJunction yeah, my company has commissioned me for building a social application. I have chosen Elgg 2.3 beacuse 3.0 is, effectively, in beta and still mistrust about 3.0 version.

But if it is acceptably stable, i'll try it.

**Comment by hypeJunction** [comment]
I think we are  close to release candidate, ironing out last minute issues and having more testers would speed up the process especially if they are savvy enough to dig out the cause and help with commits
