### ISSUE TITLE
Document pitfalls of using entity gatekeeper hooks

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11871]
Add warnings to docs about using entity gatekeeper hooks

- [ ] Plugins should be aware that by using the hook they are bypassing the access system, which is handy in some cases, but hooks must verify if `elgg_has_access_to_entity()`

**Comment by jdalsem** [comment]
I think there is no special reason to mention this with this hook. A lot of hooks are in the system that influence access. If one should use hooks they are expected to know what part of the system they are influencing.
