### ISSUE TITLE
download with error message

### ISSUE THREAD

**Issue by BogusCurry** [Elgg/Elgg#11907]
Hello ;D
When I download the beta versiion, become I this

------------------------
An unrecoverable error has occurred and has been logged. Contact the site administrator with the following information:

Exception at time 1523791864. 
---------------------------------------
https://elgg.org/getelgg.php?forward=elgg-3.0.0-beta.3.zip

pls fix it ;D

Edit: The same by the stable version .. 

Greetings
Bogus

**Comment by jdalsem** [comment]
You need to examine the PHP error log to find out what the actual error is. If there is a problem with both the beta release and the 2.3 (stable) release, there might be something system/environment specific that is causing these issues.

**Comment by jeabakker** [comment]
SInce this is an error on the Elgg.org page i logged the error in the plugin causing the issue and further tracking of he issue will happen there https://github.com/Elgg/community/issues/23
