### ISSUE TITLE
master: old timestamp limiters are not working

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11902]
these are deprecated but not part of the legacy adapter

'modified_time_lower'	=> ELGG_ENTITIES_ANY_VALUE,
'modified_time_upper'	=> ELGG_ENTITIES_ANY_VALUE,
'created_time_lower'	=> ELGG_ENTITIES_ANY_VALUE,
'created_time_upper'	=> ELGG_ENTITIES_ANY_VALUE,

**Comment by hypeJunction** [comment]
They are. There is a string concat logic somee

**Comment by hypeJunction** [comment]
Somewhere

**Comment by jdalsem** [comment]
yep... i was looking at exact the same timestamps

**Comment by jdalsem** [comment]
should we show deprecated notices if you use the old ones?

**Comment by hypeJunction** [comment]
We can. We need to de ideas if we are upgrading old queries. If we do add notices, if we don't then remove the other ones. Steve had a ticket open for that.
