### ISSUE TITLE
Blank pages afer updating to PHP 7.2

### ISSUE THREAD

**Issue by beautylix** [Elgg/Elgg#11906]
When I click the upgrade,php, it shows:

Fatal error: Declaration of ElggSite::delete() must be compatible with ElggEntity::delete($recursive = true) in /var/www/mydomain.com/public_html/vendor/elgg/elgg/engine/classes/ElggSite.php on line 28

Only blank pages and some errors, please fix to work on PHP 7.2, thanks

**Comment by hypeJunction** [comment]
Disable strict mode

**Comment by beautylix** [comment]
In strict mode, these PHP errors are still there

**Comment by jdalsem** [comment]
This is already fixed. You need to update your Elgg version to 2.3.5 or higher.
