### ISSUE TITLE
Login errors need better/customizable messages

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#11911]
If a banned user attempts to login the error message is:

> Unexpected error while performing an AJAX call. Maybe the connection to the server is lost.

Additionally, any plugin that prevents login via the login,user event cannot set a custom error message, it only shows this one until a page refresh.

![screen shot 2018-04-16 at 7 57 57 pm](https://user-images.githubusercontent.com/738363/38846423-1c4af238-41b1-11e8-8e26-685ce246956b.png)

**Comment by jdalsem** [comment]
well that is not how it should be
