### ISSUE TITLE
Leave comment button is too big

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11939]
The Leave comment button in Comments module header is gigantic. Either a link or a smaller button would make it look a lot more appealing.

@jdalsem

**Comment by jdalsem** [comment]
should we style all `elgg-button` in module menus with less padding?

**Comment by hypeJunction** [comment]
> should we style all elgg-button in module menus with less padding?

That would make sense.

Perhaps a more generic way to size buttons would be a plus. `.elgg-button.is-small` or `.elgg-button.elgg-button-small`

**Comment by jdalsem** [comment]
> Perhaps a more generic way to size buttons would be a plus. .elgg-button.is-small or .elgg-button.elgg-button-small

the risk would be devs mixing this up....
