### ISSUE TITLE
Elgg 2.3 to 3.0 upgrade issues

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11937]
- takes forever ~(probably due to database migrations with indexing still active)~ The async upgrades get stuck somehow, running them on the site or in `elgg-cli` takes ages. with no progress. In the browser hitting `F5` will remove the hanging upgrade from the list, and then i can continue

**Comment by hypeJunction** [comment]
My first suspect would be the profile fields upgrade, as it does a crazy batch operation, which probably takes forever.

**Comment by hypeJunction** [comment]
See #11942
