### ISSUE TITLE
master: queries executed pre plugin boot

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11932]
An Elgg boot sequence will take (with all caches enabled) 7 queries.

1) Load all config
2) Load site entity
3) Load session
4) Load logged in user entity
5) Load metadata for user entity
6) Get (i think 'all') plugin entities
7) Get metadata for plugin entities

After this plugin logic happens

In the shutdown sequence 3 write queries happen:
1) write logged in user metadata `prev_last_action`
2) write logged in user entity table `last_action`
3) write session to DB

Any ideas which queries are candidates for reduction? I think
- loading all config (can happen in bootcache)
- loading site entity (can happen in bootcache)
- logged in user (with metadata) in session (maybe)
- the plugin entities (some are retrieved from bootcache already, don't know why this is still happening)

If you want to check for yourself, pull #11931, as that already fixes a lot of unnecessary queries.

**Comment by hypeJunction** [comment]
> Load all config

The problem is site secret. @mrclay doesn't want it in boot cache

> Load site entity
> Load logged in user entity

These shouldn't be an issue with persistent cache (memcache or redis)

**Comment by mrclay** [comment]
My feeling was that boot was reasonably optimized when I left it (starting to be a ton of work and regressions for marginal gain). An extra and fast query to keep a master key out of caches seems worth it. When I looked last views to render a full page were a pain point, so try not to do it :)

**Comment by hypeJunction** [comment]
I agree that gains are marginal at this point.

**Comment by jdalsem** [comment]
The main reason i put it here was, because i analyzed the current need for queries. These queries mentioned were the result after i fixed a few bugs which resulted in having somewhere between 40 - 50 queries... so me solving them to get it back to 7 was pretty useful. This is what is left. I personally think having the plugin entities not cached could still be a bug. I will investigate that somewhat further. The rest is fine by me. Persistent entity caches probably will solve the site and user entity (i am not able to test that).

**Comment by jdalsem** [comment]
No extra work needed at the moment
