### ISSUE TITLE
Elgg 3.0 installation issues

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11935]
Fresh install using the website (no `settings.php` present)
- after entering the database settings (username, pwd, etc) the next step fails with an error 'couldn't connect to database' hitting refresh on the form will continue the installation as expected
- no plugins active

Fresh install using the website (`settings.php` present)
- no plugins active

Fresh install using `elgg-cli` (no `settings.php` present)
- no installation issues
- upgrades not registered (go to upgrades page will register them)
- activate new plugins upgrade is available
- deactivate old plugins upgrade is available
- migrate profile fields upgrade is available
- running `upgrade.php` cleared new and old plugins upgrade, profile fields remain. Running `elgg-cli upgrade` directly after `elgg-cli install` has the same effect

**Comment by hypeJunction** [comment]
Conclusion: use elgg-cli 😁

**Comment by jeabakker** [comment]
redid the tests with #11966 and everything is OK now
