### ISSUE TITLE
2.3: two fast clicks / doubleclick inserts embed content twice

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11949]
Most likely on 3.0, too.

If I happen to click twice fast enough or am used to doubleclicks, it can happen that the content to be embedded is added twice.

**Comment by jdalsem** [comment]
This is similar too https://github.com/Elgg/Elgg/issues/5984...

maybe the easy fix could be a onSubmit js check that just disables the button (and re-enables after ajaxComplete)

**Comment by jdalsem** [comment]
Closed by #13023
