### ISSUE TITLE
Elgg 3: On plugins listing page elgg-plugin.php is included twice

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11946]
Why??

I had a define in the `elgg-plugin.php` on the plugins list I got a warning, already defined.
Why is de file included twice, should only be once, correct?

**Comment by hypeJunction** [comment]
Can you verify again with the boot changes

**Comment by jeabakker** [comment]
tested again with current version, still happens.

Simple test, add a `var_dump(1);` in a `elgg-plugin.php` and go to the plugins page
