### ISSUE TITLE
Fix for Warning of get_user_notification_settings in notifications plugin

### ISSUE THREAD

**Issue by zenga22** [Elgg/Elgg#11941]
**I was getting the following warning in Elgg v2.3.6.**
> WARNING: Deprecated in 2.3: get_user_notification_settings has been deprecated by ElggUser::getNotificationSettings() Called from \[\# 24\] /var/www/html/s/social/vendor/elgg/elgg/engine/lib/notification.php:532<br /> -> \[\# 23\] /var/www/html/s/social/mod/notifications/views/default/notifications/subscriptions/personal.php:33 

**Fixed it using the following code modification.**
```
--- orig/mod/notifications/views/default/notifications/subscriptions/personal.php
+++ new/mod/notifications/views/default/notifications/subscriptions/personal.php
@@ -30,7 +30,7 @@ $fields = '';
 $i = 0;
 foreach($NOTIFICATION_HANDLERS as $method => $foo) {
        $checked = false;
-       if ($notification_settings = get_user_notification_settings($user->guid)) {
+       if ($notification_settings = $user->getNotificationSettings()) {
                if (isset($notification_settings->$method) && $notification_settings->$method) {
                        $checked = true;
                }
```

**Comment by jeabakker** [comment]
fixed with fcfbb0e9a1c5b7b7aeaf5c31b6e512485b6b6f7c
