### ISSUE TITLE
Review use of access queries in session handling

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11957]
When booting the session, we may want to ignore access, as there is really no point in having it there, and it plugins may potentially corrupt the boot process by registering access sql queries that prevent users from being fetched, e.g. when implement private profiles.

**Comment by hypeJunction** [comment]
``_elgg_sessions_boot()`` should be using ignored access to fetch a user.
Might also be related to #11764

**Comment by hypeJunction** [comment]
It probably has, but I think the problem is with session boot and possible query pollution by SQL hooks

**Comment by jdalsem** [comment]
Non-public profiles/users have a large set of issues (session_boot, login, register, password forgot, mute notifications, all logged out actions that involve a user). All issues could be solved by a plugin that replaces all needed parts of the system. Elgg will not implement this as a standard feature.
