### ISSUE TITLE
Strip :before and :after in notification events handler

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11956]

**Comment by jeabakker** [comment]
I take it you mean https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/Notifications/NotificationsService.php#L278
and 
https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/Notifications/NotificationsService.php#L282

But replace with what? I use those hooks sometimes. And the `PluginHooksService` doesn't have `triggerBefore` or `triggerAfter` (like the `EventsService` does)

**Comment by hypeJunction** [comment]
No, I meant the events that trigger notifications. Not sure what my thinking was. Now that doesn't sound like a good idea.
