### ISSUE TITLE
Elgg Class Loader

### ISSUE THREAD

**Issue by gadgetman2016** [Elgg/Elgg#11964]
Elgg class loader should probably use require_once instead of require in "vendor/elgg/elgg/engine/classes/Elgg/ClassLoader.php"

**Comment by jeabakker** [comment]
The class loader only gets called when PHP doesn't know the class. So once a file is included PHP knows about the class and doesn't call it again for the same classname

https://secure.php.net/manual/en/language.oop5.autoload.php
