### ISSUE TITLE
make composer great again

### ISSUE THREAD

**Issue by ObeeWanKenobee** [Elgg/Elgg#11983]
Ugh guys, hi there.

I always encounter this kind of error while playing.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/jquery ^2.1.4 exists as bower-asset/jquery[dev-master, 1.12.1-patch1, 1.8.3-patch1] but these are rejected by your constraint.
  Problem 2
    - The requested package bower-asset/jquery-ui ~1.11.4 exists as bower-asset/jquery-ui[1.12.1.x-dev, dev-master, 1.12.1, 1.12.1] but these are rejected by your constraint.
  Problem 3
    - The requested package bower-asset/jquery-form ^3.51 exists as bower-asset/jquery-form[dev-master, 3.32.0-patch2013.04, 3.25.0-patch2013.01, dev-develop, dev-feature-testing, dev-functional-testing] but these are rejected by your constraint.
  Problem 4
    - The requested package bower-asset/sprintf ~1.0.3 exists as bower-asset/sprintf[1.1.1.x-dev, dev-master, 1.1.1, 1.1.1] but these are rejected by your constraint.
  Problem 5
    - The requested package bower-asset/jquery.imgareaselect ~0.9.10 exists as bower-asset/jquery.imgareaselect[1.0.0.x-dev, dev-master, 1.0.0, 1.0.0, dev-mobile, dev-new] but these are rejected by your constraint.
  Problem 6
    - The requested package bower-asset/fontawesome ~5.0 exists as bower-asset/fontawesome[dev-master, dev-archive-doc-transfer, dev-fa-4] but these are rejected by your constraint.
```

So I suggest you add this to suppress this nonsense.

```
	"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	],
```

so it will look like

```
. . . .
        "process-timeout": 0,
        "platform": {
            "php": "7.0"
        },
	"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	]
 . . . .
```

That's all.

**Comment by jeabakker** [comment]
probably you're missing the `fxp/composer-asset-plugin` as described in our installation instructions http://learn.elgg.org/en/stable/intro/install.html#upload-elgg

Yes we know that now it should be done by the [Asset Packagist ](https://asset-packagist.org/), but that also has the disadvantage that the `repositories` in `composer.json` is a root only configuration, so users will need to add this to their own project.
Once we test the new way the installation instructions will change accordingly.

**Comment by ObeeWanKenobee** [comment]
Good Rainy Afternoon @jeabakker . oh, sorry 'bout that. As usual, I always check/read documentations of frameworks/softwares I'm playing with before running it and updated the global package `fxp/composer-asset-plugin` to the latest `dev-master` version (because of what happened to the compatibility issues happening recently in composer and npm) but it didn't solved the issue until I append the 
```
"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	]
```
to the config area which solved the problem.

> (ugh, skip this, it's just a suggestion:
> And also, shouldn't we use `filp whoops` or `tracy's debugger` while in dev env or in the dev-panel? because, in my point of view, it's tiring to check error logs and having no idea what's going on exactly.)

Thanks man,
That's all

**Comment by ObeeWanKenobee** [comment]
Since @hypejunction now have come up with a great changes to composer.json, I should now close this issue. Thanks and good day

**Comment by jdalsem** [comment]
the change is only proposed and not yet in. When it is in, this issue will automatically be closed. Reopening this to make sure we keep track of everything

**Comment by jeabakker** [comment]
Updated the docs and config in #12025
