### ISSUE TITLE
Elgg.org is DOWN for everyone.

### ISSUE THREAD

**Issue by TomOndiba** [Elgg/Elgg#11981]
Elgg.org is DOWN for everyone.
It is not just you. The server is not responding.

**Comment by jeabakker** [comment]
There was a problem with renewing the SSL certificate.

Everything should be OK now

cc @brettp

**Comment by yurtseverfazli** [comment]
> There was a problem with renewing the SSL certificate.
> 
> Everything should be OK now
> 
> cc @brettp

In Turkiye, Elgg.org is still down. I have not connects it since last night. It still displayes 502 Bad Gateway at the moment

**Comment by jeabakker** [comment]
> In Turkiye, Elgg.org is still down. I have not connects it since last night. It still displayes 502 Bad Gateway at the moment

thanks for reporting this. 

ps: Just to be clear Elgg.org hasn't been down for 4 years ;)

**Comment by yurtseverfazli** [comment]
Thanks for your reply. I haven't connected elgg.org for about two days. But
today, at least, I am on connect with it.

10 Eki 2022 Pzt 09:59 tarihinde Jerôme Bakker ***@***.***>
şunu yazdı:
