### ISSUE TITLE
container_guids=0 in legacy options adapter

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11992]
setting ```'container_guids' => 0``` is not correctly normalized

**Comment by jdalsem** [comment]
what should it be... and what does it do now?

**Comment by hypeJunction** [comment]
`container_guids = 0` should become `container_guids => [0]`, it resets it to null. I assume it checks somewhere for `empty` instead of `isset`. It works fine with singular `container_guid`
