### ISSUE TITLE
Plugins not working correctly during 'upgrade'

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12004]
During the 'upgrade', 'system' event plugin entities don't work correctly.

This is both in the `Bootstrap` class and in `elgg_get_plugins()`

For example `ElggPlugin::getID()` won't return the id of the plugin

**Comment by jeabakker** [comment]
See https://github.com/Elgg/Elgg/pull/11971#issuecomment-389912868

**Comment by hypeJunction** [comment]
See #12007
