### ISSUE TITLE
FR elgg-3: badge counter > 1000 need to shortend

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12020]
Example a blog has 10.000 likes. The badge now will show 10000. Should this be simplified to 10K?

- how to control? Using an extra menu var (`round_numbers => true|false`)

**Comment by rohit1290** [comment]
I have checked and found that the badge counter are used inside a hooks function and as far as my understanding goes, using a menu vars (`round_numbers => true|false`) is not available inside hook functions. I have created a PR without the the same.

If menu vars are possible inside a hook function, then please do share an example. I will update the code accordingly.
