### ISSUE TITLE
Check innodb prefix befor altering it

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12038]
https://elgg.org/discussion/view/2778665/upgrade-to-elgg-30

**Comment by jeabakker** [comment]
Encountered same error as reported in discussion

`
ELGG.ERROR: An exception occurred while executing 'SET GLOBAL innodb_large_prefix = 'ON'':
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation
`

**Comment by iionly** [comment]
I also came across this (https://github.com/Elgg/Elgg/issues/12126#issuecomment-410458288). In my case it was already "ON" so I could safely comment out the line that tries to set the value. I think the problem would occur on any installation where the DB user has restricted privileges.

**Comment by iionly** [comment]
Worth noting: it's not sufficient to only set innodb_large_prefix to ON. For the option to fully work it's also necessary to have innodb_file_format=barracuda and innodb_file_per_table=true. Default value of innodb_large_prefix for MySQL <= 5.7.6 is OFF and for > 5.7.6 it's ON. For MariaDB < 10.2.1 the default is OFF and then it's on but it also got deprecated with MariaDB 10.2 and removed in MariaDB 10.3.

With the problem of global scope variables not permitted to be changed without full permissions to the DB server wouldn't it be better to just add innodb_large_prefix set to ON as install/update requirement in the install docs, possibly test the value at the beginning of the installation but not trying to change or set the value at all during the installation?

**Comment by jdalsem** [comment]
i think this upgrade will need to check the correct value and if that fails provide instuctructions in the docs on how this could be fixed. I believe installation already sets the tables correctly (need to check this)
