### ISSUE TITLE
Add Elgg repo to Snyk for vulnerability testing

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12053]
Snyk.io has a pretty decent database of vulnerabilities and would help us catch things like: https://snyk.io/vuln/composer:symfony%2Fhttp-foundation. I am not sure off-hand if we are affected.

**Comment by jdalsem** [comment]
scrutinizer also caught this recently... might be fixed by a recent composer update

**Comment by jdalsem** [comment]
Tried Snyk, but it does not provide any more information than we currently get from Github security checks and scrutinizer checks, so not going to add another tool for no reason
