### ISSUE TITLE
No edit/delete link in group entity menu

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12055]

**Comment by hypeJunction** [comment]
It was never there. It was always in the edit form, I guess to avoid accidental deletion.

**Comment by jdalsem** [comment]
i would like to see consistency in entity menus

**Comment by hypeJunction** [comment]
I am fine with that. Let's remove the delete button from the form then

**Comment by jdalsem** [comment]
> Let's remove the delete button from the form then

yep, that makes sense
