### ISSUE TITLE
FR: after password reset -> user should be logged in

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12051]

**Comment by hypeJunction** [comment]
Not sure what the security guidelines are. Need to poke around. Seems reasonable, but perhaps considered unsafe?

**Comment by Facyla** [comment]
I'd see 2 use cases : 
- basic: having one's password changed is the final step of the process, so i'd vote for logging in the user. The page should have the same requirements as the login page, but that is already the case. 
 - special: the login process might require additional verification steps, eg. text challenge, captcha, checking user validity against other systems (eg. fetch some user rights from LDAP, SMS-based validation, etc.) => these should be applied before the user logs in

I think login in right away would be OK if the login is performed as an action (so any custom logic is applied) and triggers the corresponding event and plugin hooks (so other/further authentication methods apply)

**Comment by jdalsem** [comment]
The requested behaviour was already since long part of core
