### ISSUE TITLE
2.3: activity page filter error on Chrome (Chromium)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12065]
Filtering activity page entries fails on Chrome (Chromium 66). Selecting anything but all fails. It always reloads the "all entries" selection. On Firefox it works without issues.

**Comment by jeabakker** [comment]
Does this also happen on elgg.org?
I tried on elgg.org and a few local dev sites and i have no problems.
using Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by iionly** [comment]
I can't reproduce it anymore. I don't remember what i was doing when it occured. Most likely I had played around with site cache settings during testing of some plugin and hadn't properly refreshed the page on Chrome (with seems to cache data slightly more aggresively in the browser compared to FF).
