### ISSUE TITLE
2.3/3.0: requirements of Elgg not fully listed in docs?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12066]
Discussions like https://elgg.org/discussion/view/2780800/exceptiontitle (and I think there were similar others in the past) make me wonder if all the requirements / php extensions necessary to install and operate are listed in the docs.

Is there a php extension or extensions missing in the requirement list? If so, which one - problem might also be that they are named differently on different systems?

**Comment by RiverVanRain** [comment]
LGTM
`apt-get install php-pear php7.0-curl php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-xml php7.0-mbstring php7.0-xsl php7.0-intl`

**Comment by iionly** [comment]
I'm not sure what you mean by LGTM. You have several extensions listed that are not mentioned in the requirements. So, if they would really be required it wouldn't be LGTM. On the other hand, I don't think that all of the extensions you listed are required. At least not required by Elgg core whereas some 3rd party plugins might need them installed.

What I miss in your list is for example the PDO extension. Is is needed or not for Elgg 2 + 3? Or is the mysql extension still the required extension whereas the PDO extension would only provide additional functionality not needed by Elgg.

For the xml extension I've found out that some distributions (e.g. openSUSE I use) have no separate xml extension at all (support is already in core), so I would get quite desperate when searching for it. On the other hand, *buntu distribution have a separate xml php extension (which might or might not be required by Elgg - at least currently not mentioned in the docs). The not-knowing-for-sure is why I opened the issue (and also can't provide any PR to fix it myself).

**Comment by hypeJunction** [comment]
php7.0-curl - not sure if it is actually used in core, web services AFAIR rely on file_get_contents; but it's an extension I use a lot in plugins. We should just require it, pull in guzzle and replace insecure file_get_contents() on remote resources
php7.0-gd - required if imagick is not used
php7.0-mcrypt - I think crypto services only use it as a fallback in previous php versions, not sure if it's needed anymore
php7.0-xml - required by functions that manipulate dom 
php7.0-mbstring - I thought php7 uses MB by default, if not, we should just require it, as we added multibyte DB support
php7.0-xsl - not sure what this does
 php7.0-intl - I don't think it's used by core, I use it in some plugins that deal with payments and currencies
