### ISSUE TITLE
Elgg 3: group tool deprecated notices

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12067]
In the core plugins the new way of registering group tool options isn't being used causing deprecated notices

Rel #12049

**Comment by hypeJunction** [comment]
I have replaced it in all core plugins

**Comment by jeabakker** [comment]
hmmm, i did an update and still get the messages. I see you did it correctly, i'll check my installation

**Comment by jeabakker** [comment]
never mind i know what's wrong.. aaahhhh windows
