### ISSUE TITLE
elgg()->group_tools->all() needs same hook as ->group()

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12075]
it is needed to provide conditional registered group tools

**Comment by hypeJunction** [comment]
You can just alter the config, there is no point in having an extra hook.

**Comment by hypeJunction** [comment]
What would make sense is filtering tools by group subtype, which is currently not possible unless you have an actual group instance.

**Comment by jdalsem** [comment]
we can just reuse the same hook as ->group(), just without params

**Comment by hypeJunction** [comment]
Perhaps ->group() should just accept subtype. I don't think there will be any filtering based on an individual group.
