### ISSUE TITLE
profile/edit clear multiselect

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#12086]
If you have a multiselect field on the profile screen (for example using the profile_manager plugin) there's no way of clearing the options (I believe, because of [this line](https://github.com/Elgg/Elgg/blob/2.3/actions/profile/edit.php#L30)) . Is there any workaround for this?

**Comment by jdalsem** [comment]
That line only prevents NOT submitted profile fields. If you want to clear a field, submit an empty string. If the multiselect is not working as expected, please report it at the appropriate plugin.

**Comment by dploeger** [comment]
@jdalsem If I understand [this line](https://github.com/Elgg/Elgg/blob/2.3/actions/profile/edit.php#L100) correctly, the core actually supports a multi select (regardless of profile_manager) and multi selects don't send anything when no option is selected. For example see this code:

```
<html>
    <head/>
    <body>
        <h1>Form

        </h1>
        <form action="" method="POST">
            <select name="test[]" multiple>
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
            <input type="submit" value="Go">
        </form>


<h1>
Returned
</h1>
<?php

if (isset($_POST)) {
    print_r($_POST);
}
?>

    </body>
</html>
```

When nothing is selected, test is missing from $_POST. So the (supported) multi selects can never be cleared.

I could solve this in the plugin (e.g. check, if there's a value for a multiselect field. If not, reset it), but the core would be missing the feature then.

How about it?

**Comment by jeabakker** [comment]
In core we 'solve' this problem for checkboxes by having a hidden input on the form with no value, which will be submitted and therefor you can clear fields. (see https://github.com/Elgg/Elgg/blob/3.x/views/default/input/checkbox.php#L38)

This isn't implemented for selects, but that's how you can solve it. just make sure the hidden input is before the select and doesn't have the 'array' name (eg `name="somename"` and not `name="somename[]"`)

**Comment by dploeger** [comment]
@jeabakker Great. Thanks. I will propose adding this for the multiselect-input type in the profile_manager plugin.
