### ISSUE TITLE
elgg 3: plugin load order is incorrect when using bootcache

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12101]
plugins get loaded in the wrong order, this causes issues with 
- overloading views
- overloading entity registrations
- etc.

because of missing data in https://github.com/Elgg/Elgg/blob/3.x/engine/classes/Elgg/Database/Plugins.php#L776-L785

plugins get ordered by GUID

**Comment by jdalsem** [comment]
volatile data is no longer present in bootdata, in 2.3 it looks like it is... 

i believe it should not exist in volatile data, however sorting needs to be done differently then..

**Comment by jdalsem** [comment]
broken since https://github.com/Elgg/Elgg/pull/11925 ... we will fix the boot loader

**Comment by hypeJunction** [comment]
Volatile data was never meant to be cached and there was a comment about it in code.
I think fixing the tests for https://github.com/Elgg/Elgg/pull/12028 would be a better way to solve this.
