### ISSUE TITLE
elgg 3: page/components/module title can't be '0'

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12128]
When 
```php
echo elgg_view_module('info', '0', 'some content');
```
 the title (`0`) isn't displayed as it doesn't pass the `if($title)` test

https://github.com/Elgg/Elgg/blob/3.x/views/default/page/components/module.php#L32

**Comment by hypeJunction** [comment]
We keep running into this problem. Let's add `elgg_is_empty()`.
