### ISSUE TITLE
Unregister token refresh loop on expiry

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12127]
One error message is enough, no need to loop indefinitely.

**Comment by jdalsem** [comment]
we should retry indefinitely, but show the message only once... and if retry succeeds, we should also remove the message

**Comment by hypeJunction** [comment]
Will it ever succeed?

**Comment by jdalsem** [comment]
retry could also mean server has gone away / bad internet connection. That can restore
