### ISSUE TITLE
Stripping html tags necessary in messages_send() of messages plugin?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12133]
There's this discussion on the community site: https://elgg.org/discussion/view/2798328/emails-from-messages-do-not-retain-their-html-tags

It's about sending of email notification on new messages getting stripped from html tags.

As it seems the Elgg core elgg_send_email() function (https://github.com/Elgg/Elgg/blob/1cb28271f8f9c517f25c73424e22bbbf1c17ba15/engine/lib/notification.php#L592) strips html tags BUT does this only after triggering the 'email', 'system' plugin hook. So, you could use the hook to deal with email sending on your own (and also allow sending of html mails).

So, why would it be necessary for the messages plugin to also strip html tags before then making use of notify_user() which I assume means that the actual sending of the email gets done by elgg_send_email() in the following where the html tags again get stripped but at least only after the email', 'system' plugin hook gets triggered whereas the filtering within the messages plugin messages_send() can't be avoided?

**Comment by hypeJunction** [comment]
There is a ton of legacy code in messages plugin. It's not necessary to strip tags, they should be stripped by the email transport.
