### ISSUE TITLE
elgg3: single unvalidated user delete fails

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12146]
On the unvalidated users page the deletion of a single entry fails. Delete all selected users works (also for the user entry that could not get deleted separately).

Update: Deletion of all users also does not work correctly. It only deletes one of the selected users at a time. So: single user deletion does not work at all and All user delete only deletes one entry.

**Comment by jeabakker** [comment]
I believe this was fixed in 4630e3a74d90c8f1c36430c2a4ed5abc71fc5df1

**Comment by rohit1290** [comment]
Single unvalidated user delete is working in Elgg 3.0.0-rc.2
