### ISSUE TITLE
elgg3: removed plugins not showing up again in plugin list after re-adding to mod folder

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12152]
I've had the issue with one plugin and could reproduce it then with a second plugin.

To test:

1. install a plugin the normal way (well, normal in the sense that I just put the plugin folder in mod and didn't use composer),
2. then disable it and remove the plugin folder from the mod directory,
3. I then flushed the cache when testing with the second plugin,
4. then place the plugin folder in mod again and try to find it in the plugin list to enable it again... it doesn't show up anymore for me.

**Comment by RiverVanRain** [comment]
Just tested it with one of my plugin - same issue on 2.3.8

**Comment by TomOndiba** [comment]
@iionly,  same issue with my elgg3. First i thought i my eyes were not seeing correctly. rechecked my mod folder and there they where looking at me... however on the admin plugin area, the plugin were no listed like other plugins!

**Comment by hypeJunction** [comment]
There is an open PR to fix the issue. Could you try it?

**Comment by iionly** [comment]
Re-opening as the issue seems still there (see discussion https://elgg.org/discussion/view/2880789/problems-with-hosting-elgg-on-strato - ignoring the other things mentioned in this thread).

There was the PR https://github.com/Elgg/Elgg/pull/12143 but it never got merged and possibly the issue is still unfixed.
