### ISSUE TITLE
elgg3: no space between bottom of profile-field box and top of widgets

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12153]
Is it intentional that there's no vertical space between the bottom border of the profile fields box and the top border of the top-mosts widgets title sections? Looks strange because there are vertical spaces between all the other profile page elements.

**Comment by jeabakker** [comment]
apparent when viewing a profile page of a user you can't edit. So tray as a logged out user or a non admin

For the users who can edit, spacing is provided by the widget add button
