### ISSUE TITLE
elgg-3: Custom delete page

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12156]
I want to call a custom delete page (example: "action/myplugin/delete") when I delete any entity that belongs to myplugin.

I have define the actions path in my elgg-plugin.php file but when I am deleting the entity, it is calling "action/entity/delete" and my custom delete path i.e., "action/myplugin/delete" for myplugin is not getting executed.

**Comment by hypeJunction** [comment]
You also need to replace the menu item and use your own URL.

**Comment by hypeJunction** [comment]
There is plenty of examples of how to alter menu items in the community and docs.
It is best to avoid using custom delete actions, instead add your clean up logic to `delete, <entity_type>` event.

**Comment by rohit1290** [comment]
Perfect `elgg_register_event_handler('delete', "object", 'custom_delete_data')` did the trick. 
No need for any additional delete.php file.
