### ISSUE TITLE
elgg3: no fallback default icon images for size master/original

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12166]
For users there's a default image to be used as fallback in master size. For other entity types (groups) there's no master size fallback. I don't know what's supposed to act as fallback for the "original" icon size in any case.

Use case example: if you would like to display the group profile image in master size (or original size) this might work if the group gets its own group image but if it hasn't one yet there's the alt text displayed instead if any default image.

**Comment by hypeJunction** [comment]
Do you suggest we add default images for those? What size would they be? I'd prefer to solve this by just having one svg fit all sizes, but I guess too late for 3.0

**Comment by iionly** [comment]
As master/original size is not fixed I would have thought the simpliest way would be to just create copies of the large default icon image named accordingly.

But I just noticed that for the user icon fallback images the master size is just 1x1px. So, this could be an option for the non-user default icon images, too.

**Comment by iionly** [comment]
I no longer care.

**Comment by jdalsem** [comment]
I do

**Comment by iionly** [comment]
I closed it after the PR to fix the issue was there seemingly unnoticed for 2 months.

But what's the point if Elgg core doesn't support original icon size anyway? If the saving of original images has to be implemented within a plugin the corresponding fallback icons could also be provided by the same plugin.

If you want to add the icon images, you could re-open https://github.com/Elgg/Elgg/pull/12223.

**Comment by jdalsem** [comment]
if for some entities a master fallback icon is missing, it should exist, that still needs to be fixed. The discussion about 'original' images is something else. There maybe some solution underway that could help you where we change the logic of which icons are saved on upload of a new icon
