### ISSUE TITLE
elgg3: is handling of group profile images original images as intended?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12165]
On Elgg 2.x and before the uploaded image file to be used as group profile image was kept (named group_guid.jpg). On Elgg 3 the unresized image file is no longer kept. While the master thumbnail is not changed in size (as long as resolution is < 2048px) the master thumbnail is still going through the resize process and therefore loses some quality.

While not keeping the original image any longer seems consistent with user profile image handling where the original image file apparently was never kept, I wonder why introducing now the "original" size in serving of icons if there's no original image to be served. Add to that that the "original" image icon file gets created as copy of the master thumbnail.

Wouldn't it be consistent in the handling of the icon images to either keep a copy of the original uploaded image file OR if the uploaded unmodified image file is not to be kep to serve directly the master thumbnail instead of creating the "original" copy that is of no higher quality and in case of very large resolutions of the uploaded image also has no longer the original resolution?

**Comment by hypeJunction** [comment]
Adding original to icon size config would preserve the original. Not sure what the current situation is, but sounds like a bug introduced after the migration.

**Comment by iionly** [comment]
Wouldn't just adding original size to icon size config mean that the image still gets through GD (or imagick) and therefore doesn't get saved unmodified (even if the size is the same)? I'm not sure about the situation either. I believe the "original" size got added only with 3.0. On 2.x you still had to handle serving the original file on your own. 3.0 only saves master size and creates other sizes on the fly when needed. But it seems to me that dealing with the original uploaded image file might have been forgotten. That is newly uploaded image files on 3.0. For existing group images there's a migration script to rename the existing files.

On 2.x the groups plugin saved the uploaded image file separately before using saveIconFromElggFile() to create the thumbnails. On Elgg 3 the groups plugin uses only saveIconFromUploadedFile() which creates only the master thumbnail immediatelly. Preserving the original image file could either be done again separately by the groups plugin (then only for group entities). The other approach could be to let saveIconFromUploadedFile() always save the original file for all kind of entities (this would be kind of BC as other types of entities never had the original file preserved and on a missing original version it would be created from the master thumbnail on the fly).

**Comment by jdalsem** [comment]
The saveIcon logic is meant for saving thumbnails. Not for saving the original file.

You could increase the resolution of master and also the quality in the icon_sizes config. That way you could have a quality that is closer to the original, but the saveIcon functions will always recreate an image.

So if the original is important to your entity, use the saveIcon for the thumbnails and store the original as a separate file with the entity.

For groups we dropped original on purpose as we see no need to keep the original. Master is good enough.

**Comment by iionly** [comment]
@jdalsem 

99% of the code is already there to optionally (!) allow saving the original file. saveIconFromUploadedFile() offers no plugin hook to deal with saving the original file at this point but directly calls saveIcon() instead. In saveIcon() there would be a plugin hook triggered but at this point it seems much simpler to offer the handling of the original file saving directly in core. Within generateIcon() called from saveIcon the special case of leaving out the resizing IS already implemented. So the only modification necessary would be a second call of generateIcon() for the original size in saveIcon - but only for the case the entity type:subtype would have the original size registered.

My PR was just lacking the correct handling of the case where the original size is not registered and I would likely also have had to modify the tests to cover the original size handling.

I don't think that any adjustments in master icon resolution or quality is an alternative. If the file goes through the resize process there's always a loss in quality (even at 100% quality). And increasing the target resolution is also not an option - you would have to increase it to be able to keep the original resolution but then you risk OOM errors if someone tries it with a very large image (GD is still the default image lib).

Implementing the saving of the original file for every use case separately seems also not the best way to proceed. For one, the core code is already almost 100% ready to deal with it so what's the point in doing it within every plugin independently where needed? And with different plugins trying to do the job in different ways it might also result in conflicts.

My PR did not register the original size for any entity type (even if I had opened this issue wth the group images in mind). I just wanted to provide the option within Elgg core to let the original file be saved if a plugin registers the original size for some entity type. My use case would be for group images where I see a noticeable loss of quality when using the master size of an image taking the whole width of the content area as group profile image.

Is there any sense in re-trying the PR (getting it to pass all tests this time) or would it get denied in any case?
