### ISSUE TITLE
3.0 Avatar needs min-width (mobile)

### ISSUE THREAD

**Issue by zerosonesfun** [Elgg/Elgg#12177]
In 3.0, avatars need a minimum width. On mobile, if you post a bookmark, then go to the latest activity, the avatar is so tiny that it looks like a bullet point.

**Comment by breathingboard** [comment]
All that needs to be done to fix this, is in the avatar.css file, add a min-width. At first I went with 25px as the smallest an avatar should ever get since 25px is set as the "tiny" size already. 

`.elgg-avatar {
	position: relative;
	display: inline-block;
	min-width: 25px;
}`

**Comment by breathingboard** [comment]
I take that back. The above solution somewhat works, but, I think the real issue could be that the bookmark posts aren't the same width as other post types for some reason. Therefore, since bookmarks are wider in the activity stream, the avatar is smaller. Maybe the solution is to fix something related to the post size?

**Comment by breathingboard** [comment]
This seems like a possible solution. I have narrowed it down to being the link which is causing the avatar to shrink down too small on mobile. The link in a bookmark post is an attachment in the CSS. If you add code which truncates the URL, then the avatar will not shrink down too small on mobile:

`.elgg-river-attachments.clearfix {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 250px;
}`

I don't know yet if this will mess anything else up though.

**Comment by hypeJunction** [comment]
`.elgg-river-attachments` is a container used not just for bookmark URLs. `output/url` truncates the link to 100 chars, I think, so perhaps bookmarks plugin is doing something weird and not using the proper output view.

**Comment by jdalsem** [comment]
maybe fixed by #12254

**Comment by jdalsem** [comment]
Fixed in #12371
