### ISSUE TITLE
Elgg3 - Override topbar menu $item->getName() issue

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12171]
What I am trying to do is override the topbar menu and unset the menu if $item->getName() != 'login_as_return'.

Here is my code:
```
	elgg_register_plugin_hook_handler('register', 'menu:topbar', function ($hook, $type, $menu){
		foreach ($menu as $index => $item) {
			if ($item->getName() != 'login_as_return') {
				unset($menu[$index]);
			}
		}
	});
```
After execution of the above code, I found that 'profile','settings' and 'logout' is still shown and are not unset.

To fix this, I have to execute the foreach loop 3 more times to unset the remaining 3 items.

**Comment by hypeJunction** [comment]
Menus in 3.0 is a collection. Just do `$menu->remove('login_as_return')`

**Comment by hypeJunction** [comment]
Read it again.
```php
$item = $menu->get('login_as_return');
$menu->fill([$item]);
```

**Comment by rohit1290** [comment]
I am getting this error:
ELGG.CRITICAL: InvalidParameterException: Collection Elgg\\Collections\\Collection only accepts instances of ElggMenuItem

**Comment by rohit1290** [comment]
I even tried this
```
		foreach ($menu as $index => $item) {
			if ($item->getName() != 'login_as_return') {
				$menu->remove($item->getName());
			}
		}
```
I am still getting 'settings', 'friends' and 'logout'

**Comment by rohit1290** [comment]
Thanks @hypeJunction I was finally able to solve the issue
Here's the final code:
```
	elgg_register_plugin_hook_handler('register', 'menu:topbar', function ($hook, $type, $menu){
		$item = $menu->get('login_as_return');
		if($item != null){
			$menu->fill([$item]);
		} else {
			$menu->fill([]);
		}
	});
```
When the user is not logged in as any other user then $item will be null and hence the error.

**Comment by hypeJunction** [comment]
Set a much higher priority on your handler registration. They are probably added after your handler is called.
