### ISSUE TITLE
3.0 Buttons not fully responsive (mobile)

### ISSUE THREAD

**Issue by zerosonesfun** [Elgg/Elgg#12175]
On mobile, buttons are not responsive. On the profile page and in the backend, the buttons stay in the horizontal row.

Logged in, viewing another member's profile. Buttons are off the visible screen. You must scroll right:
![img_3930](https://user-images.githubusercontent.com/41351317/45687469-eaf1e580-bb1c-11e8-89e2-c8e8c06ae52d.JPG)

Backend in various spots. This is one example:
![img_3931](https://user-images.githubusercontent.com/41351317/45687479-efb69980-bb1c-11e8-98ef-5541f5495afe.JPG)

**Comment by hypeJunction** [comment]
Which buttons?

**Comment by jdalsem** [comment]
screenshot could also help
