### ISSUE TITLE
FR: Support changing member search sorting

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#12172]
When doing a member search, the results seem to be sorted by relevance (which is not understandable by the common user). A better option IMHO would be to sort by display name.

This feature request is about making the order configurable.

---

*Hint*: To enable order by displayname, you have to set 

```
$options['order_by'] = 'ue.name';
```

in `mod/members/views/default/resource/members/search.php:25`

**Comment by dploeger** [comment]
Still in v3.1

Here, you need to change this part:

```
$content = elgg_list_entities([
	'query' => $query,
    'type' => 'user',
	'list_type_toggle' => false,
    'no_results' => true,
    'sort' => [
        'property' => 'name',
    ]
], 'elgg_search');
```

(by adding the sort option)

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/13984
