### ISSUE TITLE
Please preserve "All | Mine | Friends" tab structure when upgrading from 2x to 3x, for consistent UI experience

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12173]
The new tabs in Elgg 3x, vertically stacked, takes up a lot of screen space in hand held devices ( majority users are using this ). And thus, Upgrading from 2x to 3x give multitude of users a different UI - unexpected and less user friendly

"All Site Activity" is unnecessarily larger in Elgg 3x

Can there be a secondary collapsible menu on left side of "All site activity" that on click will show "All | Mine | Freinds". If not, at least the tab structure of "All | Mine | Friends" as in 2x, please let be preserved in 3x or at minimum provide an option in Settings to do this. Many thanks.

![1](https://user-images.githubusercontent.com/43325988/45602608-d3442f80-ba3e-11e8-8452-3e8d4b8caefd.PNG)

**Comment by rohit1290** [comment]
This can easily be achieved by overriding the "river/filter" view.

Step 1: Add a file in your plugin - mod/yourplugin/views/default/river/filter.php
Step 2: Make the "All/Friend/Mine" tab as per your convenience.

Simple!

**Comment by hypeJunction** [comment]
In core, we provide a generic solution. Feel free to implement alternative in your theme. We are targeting a wide range of sites on wide range of devices. Stacking tabs provides better usability when you have layouts with say 10 tabs that overflow the viewport.

**Comment by hypeJunction** [comment]
When I design the initial theme, the tabs were horizontal with overflow scroll. Steve decided it wasn't usable and proposed stacking them. I don't think there is a single solution that would work for all sites. Implement whatever UX you want, theming in Elgg is easy.

**Comment by daniyaree** [comment]
Thanks @hypeJunction. Can you please make available a zip version of "the initial theme, where the tabs were horizontal with overflow scroll."

Collapsible menu is almost universal in all responsive UI, so a secondary collapsible menu or whatever it is called ( as shown in the green bordered box in the above pic ) would be more usable - can Steve kindly re-think ?

**Comment by hypeJunction** [comment]
Look though github history, I don't have time for this.

**Comment by iionly** [comment]
Would it be an option to collapse the tabs (like the site menu does) on small viewports? Horizontal is no option due to overflow (you might not even need 10 tabs if you have some long title in one tab or the translation is much longer than the original title). But a vertical stacking of let's say 10 tabs would fill the whole screen (even with only the 3 tabs it's quite much). And possibly more often than not you wouldn't make use of the others but the default tab anyway. Collapsing the tabs could be a solution (I don't know if there's a special fontawesome icon for collapsed tabs or if reusing the burger icon would be convenient).

**Comment by daniyaree** [comment]
I am on the go and would like to reply in details after some time. Thanks iionly and others for keeping the issue open. Some quick points

- "collapse the tabs (like the site menu does) on small viewports?" is certainly an option, and we are already doing this with site menu
- if a tab has long name, usually other scripts or sites will truncate it reasonably with ... suffixed
- here the use case is core : Activity - All | Mine | Friends. The names are not long and tabs are only 3. Elgg 2x and multitude of sites using Elgg 2x has its users accustomed to UI as depicted on the left side of the figure above. No complaints from them and apparenly no github issues critcising that so far. So why break it ?
- upgrading to 3x from 2x Aarlborg will break this and mean extra work for site maintainers who are already overburdened with newer php versions, plugin update wait times etc
- if there are extra tabs cannot there be a drop down from a "more" menu?
- wordpress's social script buddypresses standard themes let users scroll by swipe horizontally if there are more tab or horizontal buttons
- on landscape view : Activity - All |Mine | Friends look really desolate with lot of empty space on either side of the words and to get to real content its a long scroll
On portrait view also the 2x UI was much eye candy and useful too.
Many thanks for keeping the discussion open.

**Comment by mrclay** [comment]
flex-direction needs a “row-if-all-fit”

**Comment by iionly** [comment]
https://github.com/Elgg/Elgg/pull/12258 displays the tabs in a row with wrapping.

The All | Mine | Friends tabs are displayed in one row even on very small screens. The tabs on the members and group pages are displayed in one row if the width is not too small (i.e. not a mobile phone with a very low resolution). So, for Elgg core tabs they should get displayed mostly in one row. If there's more than one row (with one single tab in a new row in the worst case) you could argue what's worse: this single tab in a row or in case of displaying the tabs in a column the wasted space (with a 100% tab with a short label in the middle) even on medium screens (e.g. width 720). Anyway, it can be easily customized _either way_.

**Comment by daniyaree** [comment]
When the mobile  screen shows a vertical stack of tabs on clicking a burger icon, it is okay. Because clicking any of the tabs will cause disappearance of the tabs and take you to the intended page.

However, when you get a vertical  stack of tabs already fix displayed on the mobile screen ( as in Elgg 3x Activity : All | Mine | Friends ) nothing changes unless you scroll and scroll below to see different content. This does not fit user expectancy of the usual regular user.

"Stacking tabs on top of each other, complicates the UI and makes it harder for the user to navigate."
A vertical stack of tabs neither look like real world tabs nor like usual online tabs. Please see this excellent guideline on tabs
https://usabilitygeek.com/14-guidelines-for-web-site-tabs-usability/

**Comment by iionly** [comment]
I thought the PR was not wanted after it was there unmerged for so long: https://github.com/Elgg/Elgg/pull/12258.

**Comment by jdalsem** [comment]
unfortunately time is limited and examining other peoples PRs are very time consuming, but your question is valid. I need to investigate what the best solution is, it might be your PR (we can recover that if needed)
