### ISSUE TITLE
Elgg 3 - TheWire's thread showing all the wire posts

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12170]
When I select the "Thread" option of a wire, it is showing me all the wirepost instead of showing me only that thread specific posts.

**Comment by rohit1290** [comment]
I have tested the code and commit https://github.com/Elgg/Elgg/pull/12302/commits/3d03ac5eba57b32019fb571f06a4d2f2d4bd7609 has resolved this issue.

Closing this Issue.

**Comment by jeabakker** [comment]
thanks for confirming
