### ISSUE TITLE
3.0 Groups boxes not fully responsive (mobile)

### ISSUE THREAD

**Issue by zerosonesfun** [Elgg/Elgg#12178]
On mobile, in a group, the boxes (such as the latest activity box) are cut off. You have to scroll to the right. This screenshot I'm realizing is a very bad example. Just know that this screenshot is showing me scrolled to the right. :)

![img_3932](https://user-images.githubusercontent.com/41351317/45688208-c991f900-bb1e-11e8-9350-d9a008aa120f.JPG)

**Comment by jdalsem** [comment]
Currently unable to reproduce
