### ISSUE TITLE
Revisit checkboxes and hidden inputs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12189]
I am noticing that Chrome has changed behaior of how inputs with the same name are submitted to the server. Instead of one overwriting the other, I am seeing both being sent as array. We may need to review the uses of hidden fields in checkboxes.

**Comment by jdalsem** [comment]
I have checked and am not experiencing this behaviour. The behaviour is as expected, and works without any issue. If you have steps to reproduce, let me know.
