### ISSUE TITLE
Elgg 3: \Elgg\Collections\Collection unset in foreach is wonky

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12183]
If i have a collection of MenuItems and loop through them with a foreach and unset during this process some items are skipped

```php
foreach ($menu_items as $index => $menu_item) {
    if ($menu_item->getName() === 'someitem') {
       unset($menu_items[$index]);
       continue;
    }
    // other stuff
}
```

if there are for example 10 items in the collection, and i unset number 5, i believe number 6 is skipped and the next in the foreach is number 7.

It probably has to do with the internal pointers during loops which aren't handled correctly

@hypeJunction do you have any idea??

**Comment by jeabakker** [comment]
I encountered this during troubleshooting https://github.com/ColdTrick/group_tools/blob/master/classes/ColdTrick/GroupTools/GroupSortMenu.php#L207-L228

**Comment by rohit1290** [comment]
I had the same issue
https://github.com/Elgg/Elgg/issues/12171

This solved my problem as suggested by hypeJunction

```
$item = $menu->get('login_as_return');
$menu->fill([$item]);
```
