### ISSUE TITLE
2.3: new group content notification not sent if content previously saved in private

### ISSUE THREAD

**Issue by oseg** [Elgg/Elgg#12199]
Context: 
- elgg 2.3.8 fresh install
- In advanced settings, set "Content access/The default access permissions" to "Private"

Scenario:
1. Log in as "admin user"
2. Create an open group called "test new content notifications"
3. Log in as "test user"
4. Join "test new content notifications" group
5. In "Settings/Group notifications", enable Email notification from "test new content notifications" group
6. Log is as "admin user"
7. In "test new content notifications" group, add a page called "test page notif", leave default access to "private" and save
8. Wait for more than 1 minute or trigger artificially "cron/minute" url
9. Edit "test page notif" page, change "private" read access to "Group: test new content notifications" and save
10. Wait for more than 1 minute or trigger artificially "cron/minute" url

Results:
"test user" did not receive any email notification of the new group page creation

Expected results:
"test user" received a email of the new group page creation

Note 1:
The issue is also reproduced with a bookmark content

Note 2:
The notification is sent if the read access is set to "Group: test new content notifications" in step 7.

**Comment by hypeJunction** [comment]
Notifications are not sent for private content, because users don't have access to it. Notifications are only triggered by `create` event. This behavior is expected and not a bug.
You can register notifications to a custom event, e.g. `publish`, and then trigger it when content access changes, but you also need to maintain some flag to ensure that notification is not sent every time access changes, but only once.

**Comment by oseg** [comment]
Ok I understand now, I was using the private access as a kind of draft mode.
It is more a feature request than a bug. Should I close the issue or leave it as a feature request ?

**Comment by jeabakker** [comment]
@oseg check out the [advanced_notifications ](https://github.com/ColdTrick/advanced_notifications/releases) plugin
It has a feature the will send out the notifications when content becomes public

**Comment by oseg** [comment]
Thanks guys for the short answers, I will close the issue and try the advanced_notifications plugin
