### ISSUE TITLE
elgg3: (friendlytime) date output with php date() ignores site/user language setting

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12245]
With
https://github.com/Elgg/Elgg/blob/9318e919ab43069434478741d6769a012dc56355/views/default/output/friendlytime.php#L18
you always get the English months short names regardless of the language set in site or user settings.

**Comment by hypeJunction** [comment]
http://us2.php.net/manual/en/function.setlocale.php

**Comment by jdalsem** [comment]
Fixed in #12405
