### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by Tyranwyn** [Elgg/Elgg#12244]
I created a Dockerfile and a docker-compose file to easily deploy a basic (for the moment) version of elgg. Let me know what you think. Should I create a pull request or what do you guys want to do with this? :P

https://gist.github.com/Tyranwyn/50f39db8476cf0d8fc6ed59db362cb6f

**Comment by Facyla** [comment]
I am also considering similar things, but rather with the code, data and database files outside from the container, eg. build reusable containers for Elgg, but allow custom code and make data persistence easier (rsync, etc.)
I'm not very advanced on that topic yet, but very interested!

**Comment by jeabakker** [comment]
We already have some docker containers configured for Elgg 2.3 https://hub.docker.com/u/coldtrick/

**Comment by ytjohn** [comment]
I built one this week for 3.1.0. Geared towards being able to develop plugins/themes.

https://cloud.docker.com/u/ytjohn/repository/docker/ytjohn/elgg

https://github.com/ytjohn/elgg-docker

**Comment by jdalsem** [comment]
Elgg will not provide their own docker repo (or maintain a list of containers). You can easily find containers for Elgg and/or Apache/PHP that you can use for your project.
