### ISSUE TITLE
elgg3: forward after entity delete not ideal

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12251]
For example deleting a file or blog when viewing this entity in full view results in a forward to the container_entity (owner profile page) after deletion. When deleting an entry from a list view you return to the list after deletion. I would say that also the deletion from full view should forward to the corresponding list view after deletion and not the profile page.

**Comment by jdalsem** [comment]
which list do you want to go then after deletion from fullview?

**Comment by jdalsem** [comment]
maybe we could check for an existence of a route name for that container...

**Comment by iionly** [comment]
container's page sounds right. That how it is on Elgg 2.x (at least for blogs I've just checked and you get redirected either to the Mine tab of blogs or the the groups blog page when deleting a site-wide or group blog from full view respectively).

**Comment by Facyla** [comment]
What about forward to REFERER in general, and container tool page (or any other custom logic depending on the actual tool) only when deleting from full view? 
When they are not deleting from a full view, i guess people usually want to get back to the former context they were working in, which might not always be the container's URL, but rather some custom page or even home page (eg. from a widget).
