### ISSUE TITLE
Elgg 3: GroupIconTransfer upgrade needs rework

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12253]
The logic for checking if the upgrade should be skipped is flawed, check the most recent group if the icon is on the old place?? 

What if this upgrade is done after a new group is created with an icon? That icon will be in the correct location. Thus this upgrade can't be run for all the old groups.

Maybe check the oldest group if it has been moved, but process the group newest to oldest (like now), that could be better.

**Comment by iionly** [comment]
Is checking any group (regardless if oldest or newest) reliable? What if I try to fix group icons by manually re-uploading the image of a group (e.g. starting with oldest group). And then noticing the pending upgrade? Wouldn't a dumb script that goes through all groups to transfer the icons be safest?

**Comment by jeabakker** [comment]
logic was changed in 94248fbcf7ab512ac375add7da828396408fb8fd
