### ISSUE TITLE
Elgg3x : RSS feed, Book Mark, and Report missing

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12259]
Usually by the side of content of a page, for example a Blog post page or Activity page, three utility stuffs have been easily available so far in Elgg, and in the current Elgg 2x. These are : links or buttons for Reporting a content, Bookmark, and RSS feed, Cannot see this in Elgg3x.

**Comment by iionly** [comment]
Extra menu in the sidebar has been dropped. The menu items formerly in the extra menu are not in the footer. Or rather: they are supposted to be:

* Reported content menu item shows correctly,
* Bookmarks menu item is missing because it's not registered (forgotten to add the register to footer menu code when removing the extras menu or no longer registered on purpose?),
* RSS menu item is registered to be shown on pages where an rss feed is available (e.g. pages with lists). But something seems wrong in identifying the autofeed resulting in the rss feed never showing up!

**Comment by daniyaree** [comment]
Elgg 2x site members are very much accustomed to  to use RSS menu item and Bookmarks menu item, at least in the following pages
Activity stream
Blog page ( list of excerpts )
Bookmarks

Having at least  Bookmarks icon near the title of the content ( be it side bar or a drop down or whatever, but near the top as is the usual custom and UI everywhere ) helps a lot, to save articles for later reading or reference. RSS menu item is really massively helpful as the browser seems not to show feed icon even if the page has feeds ( in Wordpress and Drupal and many others it shows up), so having the RSS menu item on the page is very necessary for those who have been or want to use feeds.

While upgrading from 2x to 3x it will be a broken user experience. How do we fix it ?

Last but not the least, we can report a content, but how do we report a comment ? This is very much needed in present social sites, specially when there is NO "block a member by another member" or when the content owner cannot delete a comment on her content. This is perhaps another new issue.

**Comment by jdalsem** [comment]
The menu items have been moved to the footer menu (as mentioned by @iionly). The extras menu no longer exists. If you still have the need for these menu items somewhere in the top you can register the hook call backs to your own menu and output that menu on top of the owner block.

**Comment by jdalsem** [comment]
For the reporting of entities (and thus comments) is a separate issue #3562

**Comment by daniyaree** [comment]
"The menu items have been moved to the footer menu (as mentioned by @iionly)."

So,  the three links or buttons for Reporting a content, Bookmark, and RSS feed are now available in footer ? Is it now available in the downloadable RC zip for testing ? Many thanks.

 The extras menu no longer exists.

**Comment by jdalsem** [comment]
> Is it now available in the downloadable RC zip for testing

It will be in the next RC
