### ISSUE TITLE
Elgg 3x : Burger icon on top bar behaves inconsistently

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12266]
In Chrome and Firefox, almost latest versions, on tapping the burger icon at times nothing happen. At other times it works ok. This behavior happens in both closed and open state. Is it due to rapid taps ? I cannot reproduce by any definite sequence but it keeps on happening.

**Comment by hypeJunction** [comment]
I would presume script loading time. Do you have the caches enabled?

**Comment by daniyaree** [comment]
I checked. None of the caches are enabled.

**Comment by jdalsem** [comment]
Closing this as i cannot determine if there is an actual problem with Elgg. We have no other reports and no experience ourselves to keep this ticket open.
