### ISSUE TITLE
Elgg 3x : Long names need visual truncation at least

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12273]
Long user names pushes away Edit and other icons making those invisible on mobile screen - please see screenshot pic attached
![screenshot_20181118-223328](https://user-images.githubusercontent.com/43325988/48675742-d06ed380-eb82-11e8-9b19-491657891012.png)

**Comment by jdalsem** [comment]
CSS should be your friend. I can live with the currently implementation in Elgg. Currently there is no CSS that could help us in a consistent way (every browser).
