### ISSUE TITLE
FR: translatable site name

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12278]
This is part of a larger problem of localizing entities, but I have received a comment that Browser tabs always appear in English.

**Comment by jdalsem** [comment]
what are you suggesting?

**Comment by jdalsem** [comment]
You want a translatable site name?

**Comment by hypeJunction** [comment]
I am not sure. Maybe wrap in elgg_echo().

**Comment by Facyla** [comment]
Having every interface element translatable seems a very good idea. 

Meanwhile i'm not sure that someone who already edits php translations files would need the raw title string to be translatable: it'd be easier to override the corresponding view, and use a proper key instead for the sake of maintainability (and probably introduce other language-related changes, eg. header style, images such as background, etc. especially if language reading direction changes)

Maybe replacing the few interface config strings (site name and description) by translation keys would be better than translating the whole $site->name string. Then admin config is picked only if there is no translation string?

**Comment by jdalsem** [comment]
Not going to do this. The usecase is very small and it is relatively easy to introduce when overriding the site class or the related views
