### ISSUE TITLE
Elgg 3x : Comment submit button not visible properly in mobile view

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12272]
One has to scroll to see the submit button. UI should be better. Please see how github submission of comments ( or new content / issues ) is handling this. Ideally on clicking in the text box the cursor blinks and the on screen typing key board shows up and just above it the Submit button stays fixed. Please take a look at the same thing in Github. Most mobile UI follows this standard.

**Comment by jdalsem** [comment]
With the current version of Elgg (v5) the behaviour of the comment form is similar to that of github. When (on mobile) you activate the editor field/area the field will scroll into view, thus allowing to enter data with the on screen keyboard while still seeing the editor and the comment submit button.
