### ISSUE TITLE
module body could use clearfix

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12279]
floating stuff inside module body is now always required to have a wrapping div with clearfix

**Comment by hypeJunction** [comment]
Just don't use floats. You will thanks yourself later.

**Comment by jdalsem** [comment]
i was using elgg-col classes... they still use float

**Comment by hypeJunction** [comment]
Those are dumb, because they expect things to stack without a container.
My suggestion for core: don't use float, if you do, then clear it yourself. In this case, wrap your cols, they shouldn't float relative to module body anyway.

**Comment by jdalsem** [comment]
agreed, i will solve this myself
