### ISSUE TITLE
Elgg 3x : Embed falls over.

### ISSUE THREAD

**Issue by Krisstoffer** [Elgg/Elgg#12274]
Just testing out the latest release (Elgg Release 3.0.0-rc.1, version 2017041200
) , looks great so far! 
However I did run into an issue when attempting to use the embed option, I tested in blogs and on group pages to verify it wasn't focused on one area.

My process was as follows:
login -> goto blogs -> add post/page -> wait for editor to load -> click embed content -> error occurs. 

`[20-Nov-2018 04:16:39 UTC] [2018-11-20 04:16:39] ELGG.CRITICAL: Exception at time 1542687399:
Error: Call to a member function getData() on null in /Users/Krisstoffer/Projects/elgg/mod/embed/views/default/embed/layout.php:11
Stack trace:
#0 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(522): include()
#1 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(455): Elgg\ViewsService->renderViewFile('embed/layout', Array, 'default', true)
#2 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/lib/views.php(251): Elgg\ViewsService->renderView('embed/layout', Array, 'default')
#3 /Users/Krisstoffer/Projects/elgg/mod/embed/views/default/resources/embed/embed.php(18): elgg_view('embed/layout', Array)
#4 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(522): include('/Users/Krisstof...')
#5 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(455): Elgg\ViewsService->renderViewFile('resources/embed...', Array, 'default', true)
#6 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/lib/views.php(428): Elgg\ViewsService->renderView('resources/embed...', Array)
#7 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Router.php(260): elgg_view_resource('embed/embed', Array)
#8 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Router.php(124): Elgg\Router->prepareResponse(Object(Elgg\Http\Request))
#9 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Router.php(98): Elgg\Router->getResponse(Object(Elgg\Http\Request))
#10 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Application.php(466): Elgg\Router->route(Object(Elgg\Http\Request))
#11 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Application.php(362): Elgg\Application->run()
#12 /Users/Krisstoffer/Projects/elgg/vendor/elgg/elgg/engine/classes/Elgg/Application.php(418): Elgg\Application::route(Object(Elgg\Http\Request))
#13 /Users/Krisstoffer/Projects/elgg/index.php(8): Elgg\Application::index()
#14 {main}
 {"exception":"[object] (Error(code: 0): Call to a member function getData() on null at /Users/Krisstoffer/Projects/elgg/mod/embed/views/default/embed/layout.php:11)"} {"backtrace":[],"process_id":6883,"memory_peak_usage":"2 MB","memory_usage":"2 MB","url":"/embed","ip":"::1","http_method":"GET","server":"elgg.exp","referrer":"http://elgg.exp/blog/add/47"}`

I am testing locally given this is an RC release and I did verify the issue exists with and without simple cache enabled. I'm unsure what if anything else you will need from myself to verify, replicate and resolve the issue but let me know and I'll provide what I can.

**Comment by rohit1290** [comment]
I believe that the issue has been fixed in https://github.com/Elgg/Elgg/commit/8a4b80e58a0d440b4250cc1d655780b2174cfbdf#diff-6245125a0a5e1e20d43005a8904b2328R98

The error was getting generated because it was not able to get proper config for embed_tab
`$selected = elgg_get_config('embed_tab');`

With the above mentioned change the tabs are now working correctly and I have tested this in Elgg 3.0 RC2 and there was no problem with embedding files in blog.

**Comment by jdalsem** [comment]
thanks for testing it out
