### ISSUE TITLE
Elgg 3: config->wwwroot and HTTPS

### ISSUE THREAD

**Issue by gnh1201** [Elgg/Elgg#12290]
I always set https to elgg, but hyperlinks of elgg is always fixed to http.
I have not figured out where to solve this problem in db or any other config.
I need a way to use https correctly in elgg.

**Comment by jdalsem** [comment]
In the site config (as a site admin) you can configure the site URL. Just enter https://yoursite.com and it should be fine

**Comment by gnh1201** [comment]
I could not find URL field in the admin panel. I am using the elgg 3.x branch.

**Comment by jeabakker** [comment]
In that case you need to set `$CONFIG->wwwroot` in the `/elgg-config/settings.php` to the correct URL

**Comment by gnh1201** [comment]
I already edited it like your reply. but, $config->wwwroot dose not work for set https.

**Comment by gnh1201** [comment]
Elgg does works well all. without 2 issues.
I think it is not wrong installation. I will find how to fix, soon.

**Comment by gnh1201** [comment]
I was able to materialize this problem with a few tests.
Fortunately, there is no problem using HTTPS on my site.
However, when connecting from http (not https), some url does not seem to refer to `$config->wwwroot`.

This can be a problem for users of reverse proxy in cloudflare or apache, nginx.

I saved the results of this problem in the github gist.
https://gist.github.com/gnh1201/15a23b7b6e5a3332b9d3781444fd6bd2

**Comment by demyxco** [comment]
Having this same problem too using Traefik as the reverse proxy and SSL terminator. Seems like the action URL in the search form does not honor the https protocol in `$CONFIG->wwwroot`.

```
Mixed Content: The page at 'https://domain.tld/' was loaded over a secure connection, 
but contains a form that targets an insecure endpoint 'http://domain.tld/search'. 
This endpoint should be made available over a secure connection.
```
