### ISSUE TITLE
post/comment modification & notification missed

### ISSUE THREAD

**Issue by TNTBOMBOM** [Elgg/Elgg#12321]
There are 3 major features missing regarding the topic:

- You cant modify/fix your post in wire (thats big issue if you have typo with it)

- There is no notifications on the page of the web if someone commented or asked something on a topic/comment you posted already , making it difficult to keep track what ppl said. (required for social media). The only way i can see to make that happen is by if the user clicked on Account -> Notifications Manually which makes it horrible. 

- No Preview,Flag/sign or anything if the comment were modified or changed. Which is not good if someone changed his speech in discussion or ..etc from cases.

**Comment by jdalsem** [comment]
> You cant modify/fix your post in wire (thats big issue if you have typo with it)

We will keep this behaviour as is. Think twice before posting :)

> There is no notifications on the page of the web if someone commented or asked something on a topic/comment you posted already , making it difficult to keep track what ppl said. (required for social media). The only way i can see to make that happen is by if the user clicked on Account -> Notifications Manually which makes it horrible.

In the topbar a notifications icon will show an indicator (a number) that new notifications (like someone commented on your content). It will only show if you have unread notifications. Plugins (like https://github.com/juho-jaakkola/elgg-notifier) could be  used to enhance the experience.

> No Preview,Flag/sign or anything if the comment were modified or changed. Which is not good if someone changed his speech in discussion or ..etc from cases.

#13916 added `edited` timestamp information to content
