### ISSUE TITLE
Elgg 3: cli disable plugin doesn't seem to work

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12324]
tried to disable a plugin, didn't seem to work

need to find out what went wrong

**Comment by jeabakker** [comment]
maybe, but i was trying to disable a plugin without any dependencies ;)

**Comment by rohit1290** [comment]
Found another anomaly, on line 54 of PluginsDeactivateCommand.php and line 54 of PluginsActivateCommand.php

https://github.com/Elgg/Elgg/blob/45e7f294e8265166f7a41a5048aedd1d2b053673/engine/classes/Elgg/Cli/PluginsDeactivateCommand.php#L54

https://github.com/Elgg/Elgg/blob/45e7f294e8265166f7a41a5048aedd1d2b053673/engine/classes/Elgg/Cli/PluginsActivateCommand.php#L54

which one is correct? or both are same?

**Comment by jeabakker** [comment]
unable to reproduce (with or without dependencies)
