### ISSUE TITLE
Deleting "Activate new plugins" failed

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12357]
When I am deleting "Activate new plugins" from Pending Upgrade the message shown is "Activate new plugins has been deleted." however the task is not removed from Pending Upgrade

**Comment by jeabakker** [comment]
Deleting an upgrade make it so it gets rediscovered. It maybe a dumb way, certainly now that we can reset complete upgrades.

Maybe don't allow the removal of upgrades??
cc @jdalsem

**Comment by rohit1290** [comment]
The challenge that I am facing is that I don't use core plugin like activity, friends, friends_collections, system_log etc. So when I am trying to do a normal upgrade using mydomina.com/upgrade.php the upgrades are getting locked due to "Activate new plugins"
![screenshot from 2019-01-09 19-32-11](https://user-images.githubusercontent.com/2772844/50904049-51d93880-1445-11e9-9b66-0f22d793e275.png)

So every time I have to unlock the upgrade.

Next time when I run the upgrade again it shows the same error. Now I want to remove the "Activate new plugins" from Pending Upgrade tab and delete is the only option I have. There should be an option to remove the task from pending upgrade.

**Comment by jeabakker** [comment]
In #12365 i made a fix that should skip the upgrade if non of the plugins are found

**Comment by rohit1290** [comment]
Perfect! #12365 fixed the issue.

> Deleting an upgrade make it so it gets rediscovered. It maybe a dumb way, certainly now that we can reset complete upgrades.
> 
> Maybe don't allow the removal of upgrades??
> cc @jdalsem

Do you want me to keep the issue open if you want to discuss further on the above mentioned scenario?

**Comment by jeabakker** [comment]
yes keep open for now
