### ISSUE TITLE
elgg 2.3: wrong use of continue

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12388]
https://github.com/Elgg/Elgg/blob/2.3/engine/lib/input.php#L290

should be `break`

**Comment by rohit1290** [comment]
I believe that break or continue, both will give the same result for this case:

Explanation:
- If I use break, the program will terminate the switch case and then check if there is any additional code after the switch-case block and finally move to next array element of $match_on.
- If I use continue, the program will directly move to next array element of $match_on.

In this case there is no additional code that needs to be executed after the switch-case and hence both break or continue will give the same result.

**Comment by jeabakker** [comment]
behaviour is probably the same but php gives a warning
