### ISSUE TITLE
Elgg 2 + 3: CKEditor version outdated

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12392]
The version of ckeditor that comes with Elgg 2 but also with 3.0-rc.2 is not really fresh anymore at all. While there might be no severe issues under normal conditions it could be that some clients might have issues nevertheless with some rarer used OSes/Browsers (e.g. might be a bug with ckeditor due to using Edge browser or not: https://elgg.org/discussion/view/2883970/edge-browser-support).

Would it be an option to upgrade the version of ckeditor delivered with Elgg 2.3.x to the latest version 4 available?

Would it make sense to start Elgg 3 with version 5 of ckeditor right from the start? Might be too late for that but maybe something to consider for 4.0 and stick with the (latest) version 4 of ckeditor for Elgg 3.

**Comment by jeabakker** [comment]
The problem with CKEditor is that minor versions also break stuff. if we were to upgrade in Elgg 2.3 to a newer version existing plugins which use CKEditor would break. This can't be done.

We upgraded CKEditor a few times during the development of Elgg 3.

It's always possible to make a plugin ;) which delivers a newer version.

**Comment by iionly** [comment]
Seems a lose-lose situation either way. With the same version of ckeditor used over several years it's to be expected that some browser incompatilbilities or browser-specific bugs show up at some point. It's not much help then to say that the ckeditor plugin is at least compatible with some 3rd party plugin that might not even be used on the site. But I'm lacking the knowledge which plugins might require BC with ckeditor to work. Likewise, I can't judge which browser issues might be there or not (e.g. not having Edge browser for testing available). Maybe I come up with a ckeditor plugin at some later point when I happen to have no other stuff to do - not really motivated though as I already maintain the Extended Tinymce plugin though.
