### ISSUE TITLE
elgg 3: ElggUser should have banned = 'no' by default

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12403]
Before 3.0 this was handled by the users_entity table

check other attributes, solve in `initializeAttributes`

**Comment by hypeJunction** [comment]
Handling of such cases should IMO be taken care of at the database level. It would be easier and less prone to regression to have `DEFAULT 'no'` set on the MySQL column

**Comment by jeabakker** [comment]
but there is no more table that can handle this, it was all moved to metadata

**Comment by hypeJunction** [comment]
Ah, true that. I have been living in a world free of metadata tables in the last few months. Breath of fresh air :)
