### ISSUE TITLE
Feedback needed: DigitalOcean Marketplace

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12437]
See the original question here https://elgg.org/discussion/view/2900629/elgg-on-the-digitalocean-marketplace

https://marketplace.digitalocean.com/vendors

**Comment by rohit1290** [comment]
I will definitely vote for this.

I am planning to move to cloud server but there are no tutorials/guide on hosting elgg on Cloud Server, be it DigitalOcean, AWS, Azure or any other cloud server.
I have been using shared server and I have very limited knowledge on Cloud Servers. So anyone with limited expertise like me will always appreciate one-click elgg install VM or stuff like that.

**Comment by jdalsem** [comment]
Closing this as nobody is working on this at the moment
