### ISSUE TITLE
Wire posts show author's username as "river:create:object:thewire"

### ISSUE THREAD

**Issue by themanyone** [Elgg/Elgg#12490]
Posts on The Wire show up on Activity pages as written by "river:create:object:thewire". Will try, as a beginner to Elgg coding, look at the code later, but got a lot of chores to do before then. Image attached.

![t](https://user-images.githubusercontent.com/8588690/55452407-0f2a8680-5584-11e9-99ab-e4bc1cf222bf.png)

**Comment by jeabakker** [comment]
Have you tried flushing the caches, as the language keys are present in the translation files 
http://learn.elgg.org/en/stable/guides/views/simplecache.html#regenerating-the-simplecache

**Comment by themanyone** [comment]
Thanks for the insight about the language keys. I did flush the caches after updating to the latest git pull, and even resorted to deleting the contents of the cache folder, which got rid of avatars and files but that's no problem. The upgrade didn't have permission to change the database connection coalition to utf8mb4_unicode_ci so I fixed that manually just now, but still no go.

**Comment by themanyone** [comment]
Patches by rohit1290 resolved the issue. (Replaced all instances of 'river:create:object:thewire' with 'river:object:thewire:create' in *.php)

**Comment by themanyone** [comment]
Wondering if I should reopen until some fixes appear in git.

**Comment by jeabakker** [comment]
It's a very strange failure, could you maybe provide some more information
- Elgg version
- Any 3rd party plugins enabled (this includes a theme)
- any modifications made to Elgg core

**Comment by jeabakker** [comment]
I don't see how the language key still uses the old key. according to https://github.com/Elgg/Elgg/blob/d27a0c64e6af6b34ff6ddd9734bf8c16c5fcffdb/mod/thewire/views/default/river/object/thewire/create.php#L31 it should use the new key

**Comment by themanyone** [comment]
The official Elgg git doesn't have this problem. Turns out my fork does, although they should be the ?same?. I'm going to try to narrow it down by adding official Elgg as upstream to my repo and syncing, then checking core diffs and plugins. Check back later...
