### ISSUE TITLE
Elgg 3: Issue with elgg-cli upgrade async

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12509]
I was trying to migrate my elgg 2.3 to elgg 3 using `vendor/bin/elgg-cli upgrade async -v` and I got the following error.

```
Cannot use Elgg\Cli\Application as Application because the name is already in use in /home/myuser/some/path/vendor/elgg/elgg/engine/classes/Elgg/Logger.php on line 5
PHP Fatal error:  Call to a member function log() on null in /home/myuser/some/path/vendor/elgg/elgg/engine/classes/Elgg/Loggable.php on line 65
```
Here's the step that i followed:

- I clone my database, data folder and source of Elgg 2.3 to a new path (I wanted to go for a trial upgrade before the actual one, hence a duplicate copy)
- changed the required settings in the database (path, dataroot, url)
- Copied the new elgg 3.0 source code to the duplicate path.
- run `composer install`
- run `vendor/bin/elgg-cli upgrade async -v` using ssh

I am new with elgg-cli so I am not sure its actually elgg's issue or if there some problem with my elgg duplication.

**Comment by jeabakker** [comment]
there was a (potential) namespace conflict. I don't know why this isn't encountered during our unit tests Maybe it depends on the php strictness configuration
