### ISSUE TITLE
Elgg3: line breaks in the middle of words

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12508]
Words are separated in the middle on the install pages in the right (main) column. Looks bad!

**Comment by iionly** [comment]
It might be not only on the install pages but a general issue with line breaks: https://elgg.org/discussion/view/2915222/elgg-301-mobile-views

**Comment by iionly** [comment]
The line breaks in the middle of words show up everywhere!

**Comment by jeabakker** [comment]
True, it depend on your browser. See #12371 Webkit browsers (chrome, safari etc) have better support that others 
https://caniuse.com/#feat=word-break

**Comment by iionly** [comment]
Tested on Linux (can't test on another OS).

With Firefox 66 (which should fully support word-break) the problem shows. In the dev-tools I see usage of
```
word-break: break-all;
```
On Chrome (or rather Chromium 73) everything is alright. Here I see
```
word-break: break-word;
```
being used.

So it seem to me the fallback (break-all) is used on Firefox instead of the actually intended break-word. Commenting out the fallback line results in correct line breaks also on Firefox

**Comment by iionly** [comment]
https://github.com/Elgg/Elgg/issues/12511 is also connected with this. With break-word only (for Firefox) the text is not split so extreme but only after the display name and then the text from the profile fields is also separated only after complete words.

**Comment by jeabakker** [comment]
> So it seem to me the fallback (break-all) is used on Firefox instead of the actually intended break-word.

correct, Firefox doesn't support `word-break: break-word` if we remove `word-break: break-all` it would do default breaking which is whole word. 
This leads to problems with very long words like `MyAwesomeDisplaynameIsVeryAwesomeAndThenSome`

**Comment by iionly** [comment]
Give https://github.com/Elgg/Elgg/pull/12522 a try.
