### ISSUE TITLE
Elgg 3: Alter database encoding for multi-byte support

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12513]
Lot of people use shared server and they don't have super user access to mysql.
In such scenario, the following error are getting generated for "Alter database encoding for multi-byte support"
```
Upgrade "Alter database encoding for multi-byte support" failed
Failure to set 'innodb_large_prefix'. Ask your database administrator for more information.
Alternatively ask the database administrator to (temporarily) set 'innodb_large_prefix' to 'ON'.
An exception occurred while executing 'SET GLOBAL innodb_large_prefix = 'ON'': SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```
What can be an alternative to this?

**Comment by jeabakker** [comment]
there is no alternative. Your site will then have to work without multi-byte support, which i no problem for the normal operation of Elgg.
Some things may not work like storing emoji characters.
