### ISSUE TITLE
Elgg3: member display name displayed in very narrow 2nd column after avatar in hover menu

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12511]
At first I thought the display name would be shown vertically. But it's actually displayed horizontally broken almost after every character!

Additionally, profile fields' content is also displayed in the hover menu (currently also in the same narrow column below the display name). Even if the profile fields' text would be displayed nicely, does this make sense? With all profile fields completed (maybe with a lot of text in some cases) the hover menu would burst!

**Comment by rohit1290** [comment]
Having the same issue

![image](https://user-images.githubusercontent.com/2772844/55679479-e6aadf80-5929-11e9-8195-8889c922d90b.png)

**Comment by daniyaree** [comment]
The fix solves this problem. Thanks. But what happens when the user name is long, for example "Gilligilliabracadabrahocuspocus". Can the css fix please also include auto-truncation of long and too loooong names and specially long unicode names suffixed by ...?

**Comment by iionly** [comment]
Connected with https://github.com/Elgg/Elgg/issues/12508.

Proper word-breaks give better results.

But even with line breaks better handled I think the profile field content might better not be shown as it could be quite an amount in some cases when users filled all their profile fields and entered a lot of text.

With only avatar and display name being shown it might also be better to show the display name below the profile image.
