### ISSUE TITLE
Elgg 3 : Unicode user names give error message

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12518]
As an admin create a new member with username in unicode non-English characters. Elgg allows creation of such name and such name is displayed in user list. But when the name is clicked it shows error message.
Steps to reproduce : 
Go to /admin/users/add and add an user with the name in unicode characters, eg:  मकरन्द
Now come to admin/users/newest or the member list and click on that username's displayname
Error:
[ The page you are trying to view does not exist or you do not have permissions to view it ]

**Comment by jeabakker** [comment]
I tried to create a user with the username ` मकरन्द` (copy & pasted from above) this fails because of invalid characters in the username

If i use ` मकरन्द` as the displayname and any English charaters for the username i don't have any problems.

Do you have any plugins enabled which would allow unicode characters from being used in the username?

**Comment by rohit1290** [comment]
I don't think there is any plugin for that.

What daniyaree is trying to say is that user in India might use Hindi names like `मकरन्द` as username and elgg should have the functionality to allow unicode characters for username. This is also applicable for other countries as well where user might use unicode symbols in username.

I am not sure how much rework will it requires but if we are moving ahead with the idea of not implementing this feature in the core then we need to at-least add a check that user cannot use unicode characters in username and should use only English alphabets for the same.

**Comment by jeabakker** [comment]
> we need to at-least add a check that user cannot use unicode characters in username and should use only English alphabets for the same

this check is currently in place

**Comment by rohit1290** [comment]
> this check is currently in place

I tried the same in elgg 3.0 but the user got created and it did not fail.

![image](https://user-images.githubusercontent.com/2772844/56214535-b4148b80-607b-11e9-92eb-e24464639142.png)

See it allowed me to create a user with unicode username.

**Comment by jeabakker** [comment]
In your screenshot you only see the display name not the username. I tried it today as mentioned above https://github.com/Elgg/Elgg/issues/12518#issuecomment-483656146 and it didn't work (for the username, display name is no problem).

**Comment by rohit1290** [comment]
![image](https://user-images.githubusercontent.com/2772844/56215733-c1cb1080-607d-11e9-8252-5e355be7842a.png)

I hope this helps, a database entry for the user where the username for the user is "मकरन्द"

**Comment by rohit1290** [comment]
I tried again with my name in hindi characters and it allowed me.. Here's a screenshot of the user under unvalidated section. You can clearly see that the username is in unicode.
![image](https://user-images.githubusercontent.com/2772844/56216116-782ef580-607e-11e9-880b-06cf95d0f81f.png)

**Comment by jeabakker** [comment]
maybe it depends on copy and paste which is what i used.

**Comment by jeabakker** [comment]
does this also result in errors on Elgg 2.3?

**Comment by rohit1290** [comment]
No, in Elgg 2.3.7 the unicode username is working fine

![image](https://user-images.githubusercontent.com/2772844/56219314-25f0d300-6084-11e9-888b-2fdfaaa7073b.png)

**Comment by jeabakker** [comment]
OK this needs to be fixed in the routing logic of  Elgg 3 as it worked before. Will look into this some more

**Comment by rohit1290** [comment]
I have been trying to find the problem and I am 100% sure this is a route problem.
Somehow, the username is getting converted from Unicode to UTF-8 (hex). Which means `मकरन्द` is getting converted to `%E0%A4%AE%E0%A4%95%E0%A4%B0%E0%A4%A8%E0%A5%8D%E0%A4%A6`

The URL is actually becoming :
`http://myelggsite.com/profile/%E0%A4%AE%E0%A4%95%E0%A4%B0%E0%A4%A8%E0%A5%8D%E0%A4%A6`

If I select the first 3 value `E0 A4 AE`, this represents character `म` (Source: https://www.utf8-chartable.de/unicode-utf8-table.pl?start=2304&number=128)

But I am not able to find where this Unicode to UTF-8 conversion is happening. I am posting my finding here as it might save you the debugging time.

Also, if someone can point me where to dig in then I can look into this some more.

**Comment by jeabakker** [comment]
> But I am not able to find where this Unicode to UTF-8 conversion is happening

> Also, if someone can point me where to dig in then I can look into this some more.

Either in the Elgg Router or in Symfony/routing

**Comment by daniyaree** [comment]
Looking at these files, or elsewhere ? 


** vendor\symfony\polyfill-php72\bootstrap.php **

```
if (!function_exists('utf8_encode')) {
        function utf8_encode($s) { return p\Php72::utf8_encode($s); }
        function utf8_decode($s) { return p\Php72::utf8_decode($s); }
```


** vendor\mrclay\minify\min\lib\FirePHP.php **

```     
    foreach ($object as $key => $val) {                

                // Encoding the $GLOBALS PHP array causes an infinite loop
                // if the recursion is not reset here as it contains
                // a reference to itself. This is the only way I have come up
                // with to stop infinite recursion in this case.
                if ($key == 'GLOBALS'
                   && is_array($val)
                   && array_key_exists('GLOBALS', $val)) {
                    $val['GLOBALS'] = '** Recursion (GLOBALS) **';
                }

                if (!$this->is_utf8($key)) {
                    $key = utf8_encode($key);


 private function json_utf82utf16($utf8)
    {
        // oh please oh please oh please oh please oh please
        if (function_exists('mb_convert_encoding')) {
            return mb_convert_encoding($utf8, 'UTF-16', 'UTF-8');
```

** \vendor\symfony\polyfill-php72\Php72.php [ This file is part of the Symfony package.] **

```
final class Php72
{
    private static $hashMask;

    public static function utf8_encode($s)
    {
        $s .= $s;
        $len = \strlen($s);

        for ($i = $len >> 1, $j = 0; $i < $len; ++$i, ++$j) {
            switch (true) {
                case $s[$i] < "\x80": $s[$j] = $s[$i]; break;
                case $s[$i] < "\xC0": $s[$j] = "\xC2"; $s[++$j] = $s[$i]; break;
                default: $s[$j] = "\xC3"; $s[++$j] = \chr(\ord($s[$i]) - 64); break;
            }
        }

        return substr($s, 0, $j);
    }
```


** \vendor\monolog\monolog\src\Monolog\Formatter\NormalizerFormatter.php **


```
/**
     * Detect invalid UTF-8 string characters and convert to valid UTF-8.
     *
     * Valid UTF-8 input will be left unmodified, but strings containing
     * invalid UTF-8 codepoints will be reencoded as UTF-8 with an assumed
     * original encoding of ISO-8859-15. This conversion may result in
     * incorrect output if the actual encoding was not ISO-8859-15, but it
     * will be clean UTF-8 output and will not rely on expensive and fragile
     * detection algorithms.
     *
     * Function converts the input in place in the passed variable so that it
     * can be used as a callback for array_walk_recursive.
     *
     * @param mixed &$data Input to check and convert if needed
     * @private
     */
    public function detectAndCleanUtf8(&$data)
```


** vendor\monolog\monolog\src\Monolog\Handler\ChromePHPHandler.php **

```
$json = @json_encode(self::$json);
        $data = base64_encode(utf8_encode($json));
        if (strlen($data) > 240 * 1024) {
            self::$overflowed = true;
```

**Comment by daniyaree** [comment]
This problem still persists in the latest and newer versions of Elgg 3x. Is this not a "critical" bug as it makes user accessing their account impossible when clicked on such user names? Thanks for a bug-fix.

**Comment by RiverVanRain** [comment]
Duplicate #13067
