### ISSUE TITLE
Elgg 3: Database cleanup on migration

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12516]
I have a fresh copy of elgg 3 and a migrated copy of elgg 2 to elgg 3.

I was comparing the database for both and I found out the the following table are not there for the fresh copy of elgg 3 and they were not removed when i migrated my site from elgg 2 to elgg 3.

- elgg_entity_subtypes
- elgg_geocode_cache
- elgg_groups_entity
- elgg_objects_entity
- elgg_sites_entity
- elgg_users_entity 

Are there table left out or is it kept intentionally for a reason?

**Comment by rohit1290** [comment]
seems like if there was a problem in the migration the tables are left out. Is there any way I can re run the migration and complete the process what was left out?

**Comment by jdalsem** [comment]
the upgrade scripts should remove the tables, there is no way to 'restart' them because when they are finished they cannot be restarted, however, are you sure the scripts have done their job? They should delete tables. Does your sql db account have the rights to drop tables?

**Comment by rohit1290** [comment]
Yes, i have given full privilege to the sql db account.
I think the upgrade is not complete.. because I am not able to login to my test sever and If i run upgrade.php it like the script is running for forever and i can't see any update in database. Is there a way to track where the problem is? There is nothing in my error_log file.

**Comment by jdalsem** [comment]
check the migrations table if all migrations have run... you should see all migrations found in /lib/schema/migrations

**Comment by rohit1290** [comment]
ok.. you are right.. the migration was not completed... it's only showing me 3 line items.
![image](https://user-images.githubusercontent.com/2772844/55781226-4d193480-5ac7-11e9-8cca-aa3e8bc78065.png)

And if I am correct the next one will be ChangeTableEngine migration.

I have check the code for ChangeTableEngine and its simple ALTER command. I am not sure why it is not getting executed.

**Comment by rohit1290** [comment]
ok.. found the problem.. I manually executed the alter command for each table mentioned in ChangeTableEngine class and found that metadata table that is around 800+ MB is taking time. However, the engine is already MyISAM type.

To save time, we can incorporate a check in ChangeTableEngine:
Check if the table's engine is already MyISAM or not.
```
$data = SHOW TABLE STATUS WHERE `Name` = "prefix_tablename"
if($data->Engine != "MyISAM"){
  // Run the alter commnad
}
```

**Comment by jdalsem** [comment]
they need to become innodb... the myisam is only the rollback

**Comment by rohit1290** [comment]
ok.. closing the ticket.. i have manually done the migration by studying the migration code and running the sql query manually via phpmyadmin. I guess the problem is with my mysql connection.
