### ISSUE TITLE
Elgg 3: user language not fully applied on whole site

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12519]
Tested with German set as user language and English as site language.

Part of the site (or maybe I should say some element of pages) is then displayed in German while other elements still show up in English. This happens both in admin area and on frontend and both for Elgg core (+ bundled plugins) and 3rd party plugin site elements.

**Comment by iionly** [comment]
Seems connected with Systemcache, i.e. with systemcache enabled the language is mixed and with systemcache disabled the whole site is showing in the language selected as user language.

**Comment by jdalsem** [comment]
can confirm... will investigate
