### ISSUE TITLE
elgg 3: Unknown column 'acl.subtype' in asynchronous upgrades

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12512]
I am getting the following error on asynchronous upgrade via my browser:

`
[Sun Apr 07 00:56:33 2019] [error] [client 223.223.129.115] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'acl.subtype' in 'where clause' at /home/myuser/public_html/v3/vendor/elgg/elgg/engine/classes/Elgg/Database.php:474)","sql":"SELECT COUNT(DISTINCT e.guid) AS total FROM ck_entities e WHERE (e.guid NOT IN (SELECT acl.owner_guid FROM ck_access_collections acl WHERE acl.subtype = :qb1)) AND ((e.enabled = :qb2) AND (e.type = :qb3))","params":{":qb1":"friends",":qb2":"yes",":qb3":"user"}} {"backtrace":[],"process_id":157357,"memory_peak_usage":"20 MB","memory_usage":"20 MB","url":"/v3/admin/upgrades","ip":"223.223.129.115","http_method":"GET","server":"www.mydomain.in","referrer":"https://www.mydomain.in/v3/admin","unique_id":"XKmDAM-SyIgAAmVELQMAAAAJ"}, referer: https://www.mydomain.in/v3/admin
`

**Comment by rohit1290** [comment]
I believe this error was happening because the elgg did not complete a successful "site.com/upgrade.php"
Once the upgrade is finish, the asynchronous upgrade is working fine.

Not sure if i need to keep the ticket open. Do you want to add a check in the asynchronous upgrade page that if 1st upgrade.php is not run successfully then the page will not show the checklist.

**Comment by jdalsem** [comment]
does your db account have enough rights to alter the table structure? Seems to me a similar issue like #12516?

**Comment by rohit1290** [comment]
Closing the ticket.. i have manually done the migration by studying the migration code and running the sql query manually via phpmyadmin. I guess the problem is with my mysql connection.
