### ISSUE TITLE
Elgg 3x: Comment box disappears after the first comment is made.

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12533]
In Elgg as well as almost all heavily used sites, comment box appears at the end of the content post OR (if already comments are there) at the end of content + comments. Once you make a comment, you are taken/scrolled to that comment, and you can also see the comment box, in case you want to make another comment (thus inviting participation and making the site engaging).

In Elgg 3.0.1 the comment box is there as expected after the content but once the first comment is made it disappears.

**Comment by dranii** [comment]
+1

**Comment by dranii** [comment]
It does not happen in Elgg 2x. Somewhere in the upgrade, things have changed. Default comment order, which is the usual, oldest first, has also changed,

**Comment by dranii** [comment]
It does not happen in Elgg 2x. Somewhere in the upgrade to 3x, I think bugs have entered. Default comment order, which is the usual oldest first, has also changed. I am not sure, if sites upgraded from 2x to 3x, maintains the standard comment pattern (as in Elgg 2x).

**Comment by jdalsem** [comment]
#13006 gives control over collapsed state of the comments box

the order of comments is changed for ajax submit/loading reasons and will not be changed
