### ISSUE TITLE
Elgg 3.0.2 - Notification in top bar shows no counter

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#12546]
Site Notification (core plugin) activated but there is no visual indication that will show if there are any new notifications.

**Comment by jdalsem** [comment]
not a bug, but a feature request as this was never present

**Comment by daniyaree** [comment]
Hmmm, @jdalsem you are right. The visual indicator was for friends and messages. Now the Notification icon (bell or something) is in the top bar. Previously "Notification" was in the drop down menu. So now when messages etc show visual indicator but Notifications donot some users (test users) were confused.
