### ISSUE TITLE
sort_by priority issue with ElggMenuItem

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12548]
Let say I have 10-20 menus under 'site' and I am using a custom theme to show the menu using 
`elgg_view_menu('site', ['sort_by' => 'priority']);`

What I found was that all the menu has the default priority of 100 that makes the menu sorting impossible.

The menu priority should be done based on the respective plugin priority.

So, If I have Activity plugin on the top in my plugin list, Activity menu should appear at the top and so on.

Here's how you can reproduce the issue.
Keep `Event Manger` plugin first then `Activity` plugin -> Event Manager plugin appears on top for `elgg_view_menu('site', ['sort_by' => 'priority']);`
Keep `Activity` plugin first then `Event Manger` plugin -> Event Manager plugin still appears on top for `elgg_view_menu('site', ['sort_by' => 'priority']);`

**Comment by jeabakker** [comment]
It should do a fallback to registration order if priority is the same.

Now comes the 'fun' part. Since Elgg 3.0 we can have a Bootstrap class instead of start.php anything handled in Bootstrap is done before start.php so in your example although the activity plugin is first the bootstrap of event manager is handled first. Atleast in handling init system events, and therefor probably in the menu hooks too

**Comment by rohit1290** [comment]
Ok, got it. For the time being I have created a start.php file for Event Manger and calling the `elgg_register_menu_item` from there, this has resolved the priority problem for now.

But this should be fixed in core so that the menu do a proper fallback to registration order irrespective of being called from `Bootstrap` class or `start.php`

**Comment by jeabakker** [comment]
> Ok, got it. For the time being I have created a start.php file for Event Manger and calling the `elgg_register_menu_item` from there, this has resolved the priority problem for now.

The rest of the plugin still works? Or did you copy all the contents of the Bootstrap. As i don't believe both are supported ate the same time.

> But this should be fixed in core so that the menu do a proper fallback to registration order irrespective of being called from `Bootstrap` class or `start.php`

It has more todo with the registration order of the hooks, Bootstrap wins over start.php. All plugins should move to Bootstrap

**Comment by rohit1290** [comment]
> The rest of the plugin still works? Or did you copy all the contents of the Bootstrap. As i don't believe both are supported ate the same time.

No i created a start.php file and added the following code:
```
elgg_register_event_handler('init', 'system', 'my_event_init');
function my_event_init() {
        elgg_unregister_menu_item('site', 'event');
	elgg_register_menu_item('site', [
			'name' => 'event',
			'icon' => 'calendar-alt',
			'text' => elgg_echo('event_manager:menu:title'),
			'href' => elgg_generate_url('default:object:event'),
		]);
}
```

**Comment by jdalsem** [comment]
core can not garantee that the order presented is the one you would like to have... if you want more control over the site menu i would suggest the menu_builder plugin. Currently nothing is going wrong, so i am closing this ticket
