### ISSUE TITLE
Composer message about elgg/sniffs

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12549]
Doing a fresh composer install:

Failed to download elgg/sniffs from source: Failed to clone https://github.com/Elgg/elgg-coding-standards.git, git was not found, check that it is installed and in your PATH env.

Is this something we can fix?

**Comment by hypeJunction** [comment]
Did someone ever update Elgg's packagist.org after Github moved towards hooks for integrations?

**Comment by jeabakker** [comment]
I have access to most of Elgg's repos on Packagist, so it should be done automaticly when i logged in after they said i should.

Maybe the problem has to do with the license in the composer.json, will look into it

**Comment by jdalsem** [comment]
The elgg/sniff dependency is currently requesting a `-dev` branch. Primarily that will be download from source (if possible). In my installation that was not possible due to the fact that i did not have git cli available. Tagged versions will normally be downloaded from dist... i tried this with `v0.1.0` and there was no message. As this message is only a warning and downloading from dist works fine i am closing this issue.
