### ISSUE TITLE
Elgg 3.0.2 - "Feature" in Wire post apparently not working as memebers expect.

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#12547]
When site admin chooses "feature" option for a Wire post, apparently it does not goes to the top (sticky at top), neither there is any visual marker to identify it as "Featured"
In desktop view there is right lowermost side block that enlists "featured" but in the commonly used mobile view "featured" remains unknown as it is at the bottom-most part if you scroll.

**Comment by jdalsem** [comment]
there is no feature feature in thewire plugin... are you confusing this with a feature from thewire_tools plugin? If so, please report it there.
