### ISSUE TITLE
Elgg 3.0.2 - Newly registered user are not getting validation mails

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12555]
Thus they cannot become site members. Tested with same setting with only core Elgg 2x and Elgg 3.0.2. No such problem with Elgg 2x. Such problem only with Elgg 3.0.2. Standard Cpanel hosting with php7x

Mail delivery is failing, which may or may not be due to this:
`SMTP error from remote mail server after end of data:
550 Messages should have one or no Content-Type headers, not 2`

**Comment by rohit1290** [comment]
Can you verify if any specific entries appear in /var/log/exim_rejectlog or /var/log/exim_mainlog during the failed delivery attempt?

**Comment by jeabakker** [comment]
I can see Elgg sets multiple `content-type` headers. I can't find anything saying it's not allowed.

One `content-type` header comes from the mail message, https://github.com/Elgg/Elgg/blob/0f920398c776301badb404f4cb3984d3542f4caf/engine/classes/Elgg/EmailService.php#L109

the other from the plain text part of the message. https://github.com/Elgg/Elgg/blob/0f920398c776301badb404f4cb3984d3542f4caf/engine/classes/Elgg/EmailService.php#L169

This is logical as when multiple parts (html or attachtments) are added each part should have a `content-type`.
