### ISSUE TITLE
Revalidate implementation of Collection

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12558]
Scrutinizer issue
https://scrutinizer-ci.com/g/Elgg/Elgg/issues/3.0/files/engine/classes/Elgg/Collections/Collection.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc&fileId=engine/classes/Elgg/Cli/UpgradeCommand.php&honorSelectedPaths=0

https://github.com/Elgg/Elgg/blob/0f920398c776301badb404f4cb3984d3542f4caf/engine/classes/Elgg/Collections/Collection.php#L272-L282

**Comment by jdalsem** [comment]
See also https://scrutinizer-ci.com/g/Elgg/Elgg/issues/3.0/files/engine/classes/ElggBatch.php?selectedLabels%5B0%5D=9&selectedSeverities%5B0%5D=10&orderField=path&order=asc&fileId=engine/classes/ElggAnnotation.php&honorSelectedPaths=0
