### ISSUE TITLE
validate EntityTable::updateRow() result usage

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12567]
https://scrutinizer-ci.com/g/Elgg/Elgg/issues/3.0/files/engine/classes/Elgg/Database/EntityTable.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc&fileId=engine/classes/Elgg/Database/Entities.php&honorSelectedPaths=0

**Comment by rohit1290** [comment]
I just checked the link shared above and I don't see any issue with 3.0 or 3.x branch

**Comment by jeabakker** [comment]
I hate not having permalinks ;)
The issue probably had to do the the documented return value and het actual usage of the return value

**Comment by jdalsem** [comment]
all usage of this function use it correctly... don't know what could have been wrong
