### ISSUE TITLE
views_simple_cache folder not created in symlinked cache folder 

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12565]
For some unknown reason (no errors to be found) elgg is unable to create files (or the folder) in views_simplecache. The situation was on a symlinked cache folder... system cache no problem... need to investigate

**Comment by RiverVanRain** [comment]
Can you explain in more detail (scenario?) about this because I don't have such problem. Maybe I missed something.

**Comment by jdalsem** [comment]
I think i have figured it out. The following might be the case:

- a operational site added a symlink for the assetroot (cacheroot/views_simplecache)
- a sysadmin clears all files on disk in cacheroot (removing views_simplecache) but this leaves the symlink alive
- apache chokes on the invalid symlink (serves no css/js)
- simplecache request is not handled by cachehandler -> no files/folder created

Solution (if you manually clear cache folder contents and have a symlink to your assetroot):
- manually recreate the symlink
