### ISSUE TITLE
Can bypass maximum "Number of items to display" in user widgets

### ISSUE THREAD

**Issue by MakerLab-Dev** [Elgg/Elgg#12591]
Steps to reproduce.
1. Go to your Elgg profile https://myelggsite.com/profile/yourusername
2. Add a widget like for example the "Activity" widget, and click the settings button
3. In the field "Number of items to display" you can't set it to more than 20 but if you press "ctrl+shift+i" to inspect the field and change the "max" property of to something like "20000000" then you can successfully set the "Number of items to display" to any value.

*Note: Actually you can bypass the "Number of items to display" property in any widget you have permissions to change.

![image](https://user-images.githubusercontent.com/47223013/57575861-14b49f80-7453-11e9-8abd-8965124a54bd.png)

I'll update this issue with more information or a solution when I have time

**Comment by jeabakker** [comment]
This basicly applies to every html form on the internet. Therefor programmers should always verify user input serverside.
Yes, the widget has it's own max number of items set and maybe it should verify that number when getting results. 
The question is does it break anything with a large value? Yes it may take longer, but nothing actualy breaks.

**Comment by jdalsem** [comment]
there is work to be done on form input validation... there are tickets around that propose a more declarative approach on form creation that can also handle server side input validation. That is the way to go...
