### ISSUE TITLE
add case insensitive column for metadata values

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#12595]
this can replace the binary casting in queries. CASTing prevents the use of indexes. Therefore the metadata queries can be slowed if requested case sensitive (default). Pre Elgg 3.0 this was less of a problem as metadata joins happend on value_id in metadata table first. After that a query on the value_string was executed...

**Comment by jdalsem** [comment]
same for annotations and private settings

**Comment by daniyaree** [comment]
Can this be a problem when Elgg 2x is upgraded to 3x?

**Comment by jdalsem** [comment]
No, it is not a problem. The reason we need this is purely for improved performance. We are currently running Elgg 3 sites fine without this.

**Comment by jdalsem** [comment]
pushing data model changes (and investigations) to the next major

**Comment by jdalsem** [comment]
Tried to get more data to support adding this, but at the moment i have not found usecases which help to support a good reason to add this extra column
