### ISSUE TITLE
Improve input password usability 

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12645]
For the use of password managers
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#Allowing_autocomplete

**Comment by iionly** [comment]
There was password field autocomplete in the past. But it got disabled by default by https://github.com/Elgg/Elgg/pull/10297. With the always_empty attribute autocomplete can be enabled. Would it make sense to add a site setting to give the admin the choice (security vs. laziness)?

**Comment by jdalsem** [comment]
No #10927 did not do that. There is another PR that adds security settings to disable the autocomplete for password fields, but that is not active by default
