### ISSUE TITLE
Scrolling shouldn't hide popups

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12652]
I belive @jdalsem added a change to hide popup on scroll. I don't think that's a good approach, as there are many pitfalls. A large enough popup can push out of the screen causing a scroll event which then hides the popup, so you never get to see it. You should also be able to scroll to the bottom of the popup if it's very long (e.g. a very long menu).

**Comment by jdalsem** [comment]
we should make the content in the popup scrollable then

**Comment by hypeJunction** [comment]
It will be hard to size the height of it

**Comment by hypeJunction** [comment]
Can't reach the end of the user hover menu as admin
