### ISSUE TITLE
Sending a POST request without a body responds 400

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12654]
When sending a POST request without a body, I am seeing an error about image upload size

**Comment by hypeJunction** [comment]
```js
var ajax = new Ajax();
ajax.path('path');
```

**Comment by jdalsem** [comment]
master or 3.0?

**Comment by hypeJunction** [comment]
3.0.3

**Comment by hypeJunction** [comment]
I think it might be related to empty `FormData`:
```js
var ajax = new Ajax();
ajax.path('path', {
   data: new FormData(),
});
```

**Comment by hypeJunction** [comment]
Post request with a body without files and parameters also results in an error. I don't know why `Request::validate()` was changed to read the count of parameters. That has nothing to do with the POST request content length.

**Comment by hypeJunction** [comment]
This methods makes no sense at all. If the purpose of it is to determine that uploaded files were too large, that will be evident from `UploadedFile` error. Now, it's just causing headache. I have a webhook sending a post request to Elgg, and I get a response that uploaded file is too large.
