### ISSUE TITLE
QueryCache issue on Elgg 3?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12675]
I don't know the possible reason for the error mentioned in https://elgg.org/discussion/view/2932073/error-message-during-installation-v303. Maybe there's some issue in the current Elgg 3?

**Comment by jeabakker** [comment]
> Fatal error: Default value for parameters with a class type hint can only be NULL in /vendor/elgg/elgg/engine/classes/Elgg/Cache/QueryCache.php on line 36

I can't find a class type hint
https://github.com/Elgg/Elgg/blob/090b34d68d2c217ef4e35abdaa3575ececa6578c/engine/classes/Elgg/Cache/QueryCache.php#L30-L41

**Comment by iionly** [comment]
Maybe it's the php version used (< 7). I've now asked in the discussion thread if he has at least php 7.0 installed.

**Comment by iionly** [comment]
Assuming this issue is most likely not an issue due to no response in the discussion thread on the community for 2 weeks now.

**Comment by AbdulazizSobh** [comment]
i have the same issue
