### ISSUE TITLE
Something messed up with posting a reply on community site (for unknown reasons)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12686]
When I want to write a reply in this thread (using the url with friendly title)

https://elgg.org/discussion/view/2943379/how-add-google-ads-code-in-the-site-i-use-elgg-3

it does not work. I can't add anything in the editor area (it works on non-html mode but any text get lost if changing back to html mode).

But if I go to the same discussion thread without the friendly title

https://elgg.org/discussion/view/2943379

there's no issue with posting a reply!

**Comment by jdalsem** [comment]
I have no problems and also see no issues in console logs... maybe you are experiencing a javascript issue specific to your browser? I can also see other users have had successful comments posted... so assuming this is something not related caused by Elgg

**Comment by iionly** [comment]
Maybe a browser issue as it seems to work on Chrome but not on Firefox.

But I'm talking only about this single discussion thread. Posting works fine in any other thread but not in this one if calling the page with full url including friendly title. So, I wonder what should cause this problem then on my side...

**Comment by jdalsem** [comment]
that i do not know... maybe a js issue specific for this page? Or some weird caching issue... unfortunately we cannot give all our attention to unreproducable issues that only happen with 1 person on 1 page in 1 browser :(
