### ISSUE TITLE
Drop support for container permissions without subtype

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12684]
Container permission overrides are becoming a nightmare to manage, because some plugins call canWriteToContainer() without type/subtype. In projects with granular permissions checks this turns into a nightmare: following the hooks and their outputs and devising some really hacky ways of managing it all. It would be easier to just not support the generic check.

**Comment by jdalsem** [comment]
feel free to provide a PR with a deprecation strategy
