### ISSUE TITLE
Hook and Event are not @internal API

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12738]
`\Elgg\HooksRegistrationService\Hook` and `\Elgg\HooksRegistrationService\Event` have been marked as internal and they are not. They are used in hook handler invocation, hence not `@internal`.

**Comment by hypeJunction** [comment]
Or maybe not.

**Comment by jeabakker** [comment]
correct, probably some more classes are in core, but too much copy-pasting has it's effect
