### ISSUE TITLE
Elgg 3.1 - Error on running upgrade

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12750]
Whenever I am running an upgrade on 3.1, I am getting the below error and the upgrade process is stopping:

`PHP Notice:  Array to string conversion in vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 1079`

**Comment by jdalsem** [comment]
are you running the upgrade from the commandline? or from the browser?

**Comment by rohit1290** [comment]
browser

**Comment by jdalsem** [comment]
i am unable to reproduce it with the latest version... do you have custom plugins enabled? are you seeing any more information (like a trace) in the error log?

**Comment by rohit1290** [comment]
I have disabled all the plugin and run the upgrade again. I am getting the same error.

Error log only shows: PHP Notice:  Array to string conversion in vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 1079

Browser is showing:
![image](https://user-images.githubusercontent.com/2772844/61649403-0abee080-accf-11e9-87b2-beda788df356.png)

**Comment by rohit1290** [comment]
ok.. so here is what my analysis is..

The error is because of `$limit = '(' . $index->getLimit() . ')';` at `vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php` on line `1079`

I did a var_dump of `$index->getLimit()` and the output was `["subtype"]=> int(50)` which is an array. Ideally, `$index->getLimit()` should only return `50` and not the array.

Further, I did a var_dump of `$index` and the output was

```
object(Phinx\Db\Table\Index)#153 (4) {
  ["columns":protected]=> array(3) { 
    [0]=> string(4) "type" 
    [1]=> string(7) "subtype" 
    [2]=> string(10) "owner_guid" 
  } 
  ["type":protected]=> string(5) "index" 
  ["name":protected]=> string(18) "type_subtype_owner" 
  ["limit":protected]=> array(1) { 
    ["subtype"]=> int(50) 
  } 
}
```
I believe that `type_subtype_owner` was recently introduce in https://github.com/Elgg/Elgg/issues/12553

I guess you already have the `type_subtype_owner` index created in your entities table and hence you are not getting the error. For people like us who will have to migrate from 3.0 to 3.1 might have this issue.

**Comment by rohit1290** [comment]
Found it!

https://github.com/Elgg/Elgg/blob/ecf6c76816626b0e1970afcfd0b34eb96072ac8b/engine/schema/migrations/20190606111641_entities_add_type_subtype_container_and_owner_indexes.php#L35

https://github.com/Elgg/Elgg/blob/ecf6c76816626b0e1970afcfd0b34eb96072ac8b/engine/schema/migrations/20190606111641_entities_add_type_subtype_container_and_owner_indexes.php#L43

I guess this should be `'limit' => 50`

**Comment by jdalsem** [comment]
Thanks for the investigation... did you install with composer? This feature (array definition of limits for index lengths) is part of phinx 0.10.x (https://github.com/Elgg/Elgg/commit/52ebe5885ece97df257c1cd927c8f4d46e3a364b). How did you update Elgg? With a git checkout? Did you run composer install afterwards?

**Comment by rohit1290** [comment]
i only did a git checkout for 3.x. Let me run the composer update and get back to you on this.

**Comment by jeabakker** [comment]
> i only did a git checkout for 3.x. Let me run the composer update and get back to you on this.

ps: do a `composer install`

**Comment by rohit1290** [comment]
The upgrade is working fine after `composer install`
Closing the ticket
