### ISSUE TITLE
Elgg 3: ajax response with http exception

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12755]
for example loading a ajax view which is protected by a gatekeeper and between requests your session expired

**Comment by jdalsem** [comment]
error in log:

ELGG.ERROR: Unable to send the following response: \nHTTP/1.1 404 Not Found\r\nCache-Control: must-revalidate, no-cache, no-store, private\r\nContent-Type:  text/html; charset=UTF-8\r\nDate:          Mon, 22 Jul 2019 09:39:08 GMT\r\nExpires:       Thu, 19 Nov 1981 08:52:00 GMT\r\nExpires:       Thu, 19 Nov 1981 08:52:00 GMT\r\nPragma:        no-cache\r\nPragma:        no-cache\r\n\r\nDe pagina die je opvraagt bestaat niet, of je hebt onvoldoende rechten om deze te mogen bekijken.\nbecause another response has already been sent: \nHTTP/1.1 200 OK\r\nCache-Control: must-revalidate, no-cache, no-store, private\r\nContent-Type:  text/html; charset=UTF-8\r\nDate:          Mon, 22 Jul 2019 09:39:08 GMT\r\nExpires:       Thu, 19 Nov 1981 08:52:00 GMT\r\nPragma:        no-cache\r\n\r\n  {"backtrace":["[#6] /data/data/websites/nextintranet/intranet-3.0-349/vendor/elgg/elgg/engine/classes/Elgg/Http/ResponseFactory.php:350","[#5] /data/data/websites/nextintranet/intranet-3.0-349/vendor/elgg/elgg/engine/classes/Elgg/Application.php:375","[#4] /data/data/websites/nextintranet/intranet-3.0-349/vendor/elgg/elgg/engine/classes/Elgg/Application.php:492","[#3] /data/data/websites/nextintranet/intranet-3.0-349/vendor/elgg/elgg/engine/classes/Elgg/Application.php:359","[#2] /data/data/websites/nextintranet/intranet-3.0-349/vendor/elgg/elgg/engine/classes/Elgg/Application.php:415","[#1] /data/data/websites/nextintranet/intranet-3.0-349/index.php:8"],"process_id":37242,"memory_peak_usage":"5.01 MB","memory_usage":"4 MB","url":"/ajax/view/event_manager/event/attendees_list?limit=20&offset=20"
