### ISSUE TITLE
New Install 3.1.2 using CLI getting Critical: Exception

### ISSUE THREAD

**Issue by walterwhiteknives** [Elgg/Elgg#12809]
Here's what it says. I changed username and site for privacy.
`
CRITICAL: Exception at time 1567381121:
DatabaseException: An exception occurred while executing 'SELECT * FROM elgg_config':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'elgg312.elgg_config' doesn't exist in /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php:448
Stack trace:
#0 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php(386): Elgg\Database->executeQuery(Object(Elgg\Database\Select), Object(Doctrine\DBAL\Connection))
#1 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php(193): Elgg\Database->getResults(Object(Elgg\Database\Select), NULL, false, Array)
#2 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database/ConfigTable.php(157): Elgg\Database->getData(Object(Elgg\Database\Select))
#3 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/BootService.php(92): Elgg\Database\ConfigTable->getAll()
#4 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(99): Elgg\BootService->boot(Object(Elgg\Di\ServiceProvider))
#5 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(47): Elgg\Application\BootHandler->bootServices()
#6 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application.php(215): Elgg\Application\BootHandler->__invoke()
#7 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application.php(174): Elgg\Application->bootCore()
#8 /home/username/site/vendor/bin/elgg-cli(51): Elgg\Application::start()
#9 {main}
`

**Comment by slyhne** [comment]
Same problem here - looks like the installer is not able to create tables in database.
Install fails both with CLI tool and https://myserver.org/install.php. All prechecks are fine.

Elgg: 3.1.2 installed using composer
OS: Ubuntu server 18.04.3 LTS
PHP: 7.2.19
Nginx: 1.14
MariaDB: 10.1.41

**Comment by leboemori** [comment]
Been having exactly the same issues.  The installation steps do really need to to updated to give more detailed pointers.
All modules seem to be loaded for me:
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by jeabakker** [comment]
fixed by @12815
