### ISSUE TITLE
Upgrading from Elgg 3.1.1 to 3.1.2 - Phinx Issue

### ISSUE THREAD

**Issue by Udinra** [Elgg/Elgg#12806]
Followed below steps for Upgrade

1. Over write 3.1.1 files with 3.1.2
2. Checked if any change in Elgg Nginx configuration or Settings is required
3. Navigated to upgrade.php caused below issue

The command defined in "Phinx\Console\Command\Init" cannot have an empty name.

The dashboard does show version 3.1.2 and plugins also are from 3.1.2

**Comment by Udinra** [comment]
https://github.com/cakephp/phinx/issues/1599 This talks about the issue and resolution. May be included in next release

**Comment by PerJensen** [comment]
Hmm, unfortunately I didn't see this post before upgrading to 3.1.2. Did you find a solution @Udinra or are you waiting for a fix.

**Comment by jeabakker** [comment]
fixed by #12815
