### ISSUE TITLE
Getting issue while install of Elgg 3.1.2

### ISSUE THREAD

**Issue by GaneshKandu** [Elgg/Elgg#12805]
Hi,

i am getting issue while install of Elgg 3.1.2 on ``Database installation`` step ie. 3rd

![img_20190829](https://user-images.githubusercontent.com/12833130/63930891-cf53c680-ca71-11e9-8e42-82d974e903d1.png)

cant proceed to next step
installation doesn't shown any error message just this message mentioned in image

**Comment by jeabakker** [comment]
probably due to #12806

**Comment by walterwhiteknives** [comment]
I have the same problem on a clean new install.

**Comment by walterwhiteknives** [comment]
@jeabakker I've gotten with my host and given the install process (quoted from pdf), and they said there is nothing on their end stopping the install from happening, and suggested I get with you. They also said there are no server errors on their end. I'm getting the exact same thing as in Ganesh's image above. I don't know what to do next. Thanks.

**Comment by demyxco** [comment]
I had to use the CLI to install it:
```
vendor/bin/elgg-cli install
```

**Comment by walterwhiteknives** [comment]
I'm completely unfamiliar with CLI

**Comment by demyxco** [comment]
@walterwhiteknives 

```
php /path/to/elgg/vendor/bin/elgg-cli install
```

**Comment by walterwhiteknives** [comment]
Thanks for the help. Where would I execute that at?

**Comment by demyxco** [comment]
@walterwhiteknives you'll have to do some research as it is out of scope on this thread.

**Comment by walterwhiteknives** [comment]
@demyxco Ok I'll see what I can come up with. Thank you again

**Comment by walterwhiteknives** [comment]
@demyxco I ran that and there's a bunch of critical errors in the window

**Comment by walterwhiteknives** [comment]
Here is what it says. I changed username and site for privacy.

`CRITICAL: Exception at time 1567381121:
DatabaseException: An exception occurred while executing 'SELECT * FROM elgg_config':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'elgg312.elgg_config' doesn't exist in /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php:448
Stack trace:
#0 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php(386): Elgg\Database->executeQuery(Object(Elgg\Database\Select), Object(Doctrine\DBAL\Connection))
#1 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database.php(193): Elgg\Database->getResults(Object(Elgg\Database\Select), NULL, false, Array)
#2 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Database/ConfigTable.php(157): Elgg\Database->getData(Object(Elgg\Database\Select))
#3 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/BootService.php(92): Elgg\Database\ConfigTable->getAll()
#4 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(99): Elgg\BootService->boot(Object(Elgg\Di\ServiceProvider))
#5 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(47): Elgg\Application\BootHandler->bootServices()
#6 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application.php(215): Elgg\Application\BootHandler->__invoke()
#7 /home/username/site/vendor/elgg/elgg/engine/classes/Elgg/Application.php(174): Elgg\Application->bootCore()
#8 /home/username/site/vendor/bin/elgg-cli(51): Elgg\Application::start()
#9 {main}
`

**Comment by GaneshKandu** [comment]
@walterwhiteknives deleting ``settings.php`` from ``elgg-config`` folder it works
but still there is error
```
Enter data directory path: /home/soft/elggdatadir/
PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php on line 149

In Database.php line 448:

  An exception occurred while executing 'SELECT *
                        FROM preeg_users_sessions                               
                        WHERE session = ?' with params ["7452a1931bd89d04b946816085cd7891"]:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'elgg312.preeg_us
  ers_sessions' doesn't exist


install [-c|--config [CONFIG]]

```
