### ISSUE TITLE
Remove static file Etag from default .htaccess

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#12817]
```
# Conditional requests are controlled through Last-Modified and ETag headers.
# Elgg sets these on dynamically generated cacheable files so this is just for
# static files. Note: Apache sends Last-Modified by default on static files so
# I don't think we need to be sending ETag for these files.
<FilesMatch "\.(jpg|jpeg|gif|png|mp3|flv|mov|avi|3pg|html|htm|swf|js|css|ico)$">
	FileETag MTime Size
</FilesMatch>
```

This seems to have the opposite effect. I'd rather rely on default Apache behavior. With this, I am getting a different ETag every time and files aren't cached.

**Comment by hypeJunction** [comment]
Very intermittent. Could someone else verify?

**Comment by jdalsem** [comment]
tested, but i can't find a difference with or without this setting in the htaccess

**Comment by jdalsem** [comment]
Maybe there is a reason why we have this (see https://www.keycdn.com/support/configure-entity-tags-etags)... but it has been this way for over 10 years. Current config is the same as the default of Apach 2.4 and up... there should be no problem. If you receive different etags you need to investigate further as i can not reproduce the described behaviour.

**Comment by hypeJunction** [comment]
Possibly my IDE was autosaving files and changing the modified time. Closing for now.
