### ISSUE TITLE
Any way to set redis password and database?

### ISSUE THREAD

**Issue by karnakitab** [Elgg/Elgg#12821]
Is there any way to set redis password and database?
I can set this:
```
$CONFIG->redis = true;

$CONFIG->redis_servers = array (
	array('127.0.0.1', 6379)
);
```
But do not know how to implement specify redis password and database name.

**Comment by jeabakker** [comment]
I have no experience with redis, but i believe our current implementation only supports server config. not `database` and `password`

see https://github.com/Elgg/Elgg/blob/a44a73bc5c42bd260ea572bd4d1827cf73d47851/engine/classes/Elgg/Cache/CompositeCache.php#L257-L269

**Comment by jdalsem** [comment]
should be an easy fix to allow redis options to be set in settings.php... adding it to the roadmap
