### ISSUE TITLE
Words break at any point in 3.2.0

### ISSUE THREAD

**Issue by anthonykozar** [Elgg/Elgg#12889]
I installed Elgg for the first time a few days ago, so I don't have any knowledge of how previous releases worked, but I have noticed a couple of issues so far with version 3.2.0.

First, word breaks can happen anywhere in rendered text which makes it very awkward to read.  The following rules in the elgg.css stylesheet are the problem:

body {
	word-break: break-all;
	word-break: break-word
}

"break-word" is an invalid value.  It should be "normal".  Of course, the first rule is superfluous.  The following rule also will be unnecessary if the above is fixed:

@media screen and (min-width: 50rem) {
  .elgg-table thead th, .elgg-table tfoot th, .elgg-table-alt thead th, .elgg-table-alt tfoot th {
	word-break: normal
  }
}

I'll open another issue for the second problem I've noticed.

THANKS!

**Comment by iionly** [comment]
Which browser and which version of this browser do you use?

I had the same problem reported in https://github.com/Elgg/Elgg/issues/12508 and made a PR in https://github.com/Elgg/Elgg/pull/12522. For me it was an issue happening in Firefox but with Firefox 67 and later it seems no problem anymore (havent't tested Elgg 3.1 or 3.2 yet though).

**Comment by anthonykozar** [comment]
Sorry for forgetting to include browser details and for missing the previous closed issues.  I am experiencing the problem in Safari 11.1.2 and Firefox ESR 52.9.0 on Mac OS X 10.11.6 ("El Capitan).  Also, I see it on my Android phone with Firefox 66.0.2.  Yes, my desktop browsers are out-of-date but I am using the latest version of Safari that I can.  My computer is too old to upgrade to a newer version of Mac OS X and newer versions of Safari are not available for El Capitan.  I'm still using Firefox 52 because I sometimes need the Java plugin.

I see that the Elgg developers marked this issue as "won't fix".  I think that is a shame for a number of reasons.  I understand that it is difficult to support a range of browsers but in my opinion there are significant benefits to doing so.  In this case, I think there is a good solution that will make Elgg look good in new browsers while still looking decent in old browsers under most circumstances.  Simply remove the "word-break: break-all" rule!  It is always being overridden in new browsers but it is a poor fallback for the old ones.

I hope that this issue will be reconsidered.  Of course, once I learn enough about Elgg to add my own CSS tweaks I'll be able to improve the look of the new site that I am building, so it is not an "essential" fix.

One other comment:  When I first installed Elgg, the sidebars were always displaying below the main content in my desktop browsers.  I.e. it was behaving like the mobile layout.  I thought something was broken for a couple of days until I tried increasing the width of my browser windows.  I keep my browser windows at about 1220px wide but the desktop layout only kicks in at 1280px.  No big deal I suppose, but it was pretty confusing and it made me question whether the UI of Elgg 3.x was really as nice as the videos I saw.  I could not find any 3.x themes on the community site that significantly alter the core theme, so I guess I need to make my own...

**Comment by anthonykozar** [comment]
Correction: I don't think the word break issue affects Safari 11.1.2.  I was mistaken in thinking that it was present in all of the browsers that I am using.  Sorry :(

BTW: I was able to write a plugin incorporating iionly's suggested fix from PR #12522 and I am now much happier with the appearance of my site.  Thanks!!! ^_^

**Comment by jeabakker** [comment]
> I see that the Elgg developers marked this issue as "won't fix". I think that is a shame for a number of reasons. I understand that it is difficult to support a range of browsers but in my opinion there are significant benefits to doing so. In this case, I think there is a good solution that will make Elgg look good in new browsers while still looking decent in old browsers under most circumstances. Simply remove the "word-break: break-all" rule! It is always being overridden in new browsers but it is a poor fallback for the old ones.

please see our browser support policy http://learn.elgg.org/en/stable/intro/install.html#browser-support-policy

We can do a best effort to support older browsers, but no guarantees.

**Comment by anthonykozar** [comment]
Thank you for the explanation!  I really do appreciate all of the hard work that has gone into Elgg.  Elgg's out-of-the-box functionality and extensibility is very impressive.  The documentation has been very helpful so far and, obviously, the developers are responsive to issues.  All around, a great open-source project!!  Thanks! :)
