### ISSUE TITLE
Priority for views in elgg-plugin.php

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#12917]
I'd like to rewrite my start.php to elgg-plugin.php to save code and move to the new standard. I have extended some views with a priority. How can I set the priority in the views key in elgg-plugin.php? I didn't find any documentation about it.

**Comment by jdalsem** [comment]
you can't (at the moment)... the views section is currently only meant for registering custom views. Extending views is not possible in elgg-plugin.php. If you want to get rid of the start.php you can also use a bootstrap class (which you can register in elgg-plugin.php). See for an example: https://github.com/ColdTrick/saml_sso/blob/cfb705bb91e4108e55497c396337ff3ee907e574/elgg-plugin.php#L8
