### ISSUE TITLE
FR: add smtp mail support to core

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12938]
with our current mail transport it shouldn't be that hard to set smtp settings in `settings.php` and use a smtp server

**Comment by NerdsvilleCEO** [comment]
@jeabakker I could volunteer to fix this... I believe if the transport is changed to Smtp, it could be configured using the settings.php as you mentioned...
https://docs.zendframework.com/zend-mail/transport/smtp-options/

SendmailTransport is just a wrapper around php `mail` so the support would be limited to Windows. SmtpTransport is likely a good move as well to prevent the email from ending up in SPAM... thoughts?

**Comment by jeabakker** [comment]
@NerdsvilleCEO if you'd like to give it a try, please do.

The mail transporter needs to be set in the ServiceProvider https://github.com/Elgg/Elgg/blob/9b99598fd24002eda8e510abc6dd5fdb77703931/engine/classes/Elgg/Di/ServiceProvider.php#L474

To eighter sendmail (default) of if smtp settings are set in the `settings.php` to the `Zend\Mail\Transport\Smtp` (with the correct settings)

Maybe take a look at how we did it for the `imageService` there we switch between `gd` (default) and `imagick` (when set in the settings)
https://github.com/Elgg/Elgg/blob/9b99598fd24002eda8e510abc6dd5fdb77703931/engine/classes/Elgg/Di/ServiceProvider.php#L441-L455

**Comment by jeabakker** [comment]
PS: we'd like to be able to support smtp in Elgg 3.3 which is scheduled for the end on January

No rush ;)

**Comment by NerdsvilleCEO** [comment]
yip, this is exactly where I was looking to make the change :) should be a pretty simple fix, by should... I mean I hope ;)

Will keep you posted

**Comment by jeabakker** [comment]
@NerdsvilleCEO any progress update?

**Comment by NerdsvilleCEO** [comment]
@jeabakker this is on my schedule, had a hiccup getting the static assets serving, it seems that the php built in server doesn't serve those and you need nginx or Apache (not sure why that is without looking more into it)

Is there an IRC somewhere if I hit more issues (I shouldn't now that the app is running)

I'll keep you posted, goal is to have this finished by the end of the week (before Monday)

Thanks

**Comment by jeabakker** [comment]
> Is there an IRC somewhere if I hit more issues (I shouldn't now that the app is running)

there is https://elgg.slack.com which you can join

> I'll keep you posted, goal is to have this finished by the end of the week (before Monday)

Great thanks

**Comment by NerdsvilleCEO** [comment]
@jeabakker this website seems to require an elgg.org email address

**Comment by jeabakker** [comment]
@NerdsvilleCEO I can invite you, should i use the email address on your GitHub profile?

**Comment by NerdsvilleCEO** [comment]
Sure, I just updated the email :)
