### ISSUE TITLE
HTMLawed removes ids

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#12934]
I've recently came across this bug and I'm not quite sure, if it's HTMLawed-related or in the Elgg core.

The problem occured when I was enriching CKeditor with the TOC plugin to allow building tables of contents (for pages specifically). Now, the plugin just walks through the text, identifies headings, creates a list and links to those headings *by adding an id attribute to them*.

HTMLawed has a setting called "unique_ids", which is enabled per default and should remove duplicate ids from texts. It does that by storing all IDs it came across in a global variable.

The bug happens because apparently, the validate:input-hook is called three times in a row. The first call doesn't do anything, because it doesn't find handlers (which is strange, but I didn't find the cause). The second call runs HTMLawed on the text, which creates the global variable recording all ids.

On the third run, HTMLawed sees the same IDs and as it has already recorded them it believes, that those are duplicated and removes them.

So effectively, in the last run, HTMLawed removes all id attributes, which are required by the ckeditor toc plugin (because that's how anchors in HTML work).

I mitigated that by overriding the default config for unique_ids in the config:htmlawed hook, however this doesn't feel like the right solution.

I'm actually mostly wondering, why the text is validated three times.

Perhaps you can help there.

**Comment by jdalsem** [comment]
this sounds strange... will need to investigate this

**Comment by dploeger** [comment]
To reproduce:

* Enable CKEditor
* Enable [CKEditorExtended](https://elgg.org/plugins/1939122)
* Install [TOC plugin](https://ckeditor.com/cke4/addon/toc) (either directly use our [plugin](https://github.com/wabuehamm/elgg-plugin-wabue) or inject the plugin like we did there)
* Set up CKEditorExtended according to this:

![image](https://user-images.githubusercontent.com/203453/69856956-1890fd80-128f-11ea-88e9-f501c779c6e6.png)

The settings are these:
```
toolbar: [['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'], ['NumberedList', 'BulletedList', 'Undo', 'Redo', 'Link', 'Unlink', 'Image', 'Blockquote', 'Paste', 'PasteFromWord', 'Maximize']],
removeButtons: 'Subscript,Superscript', // To have Underline back
allowedContent: true,
baseHref: elgg.get_site_url(),
removePlugins: 'liststyle,contextmenu,tabletools,tableselection',
extraPlugins: 'blockimagepaste,image2',
defaultLanguage: 'en',
language: elgg.get_language(),
skin: 'moono-lisa',
contentsCss: elgg.get_simplecache_url('elgg/wysiwyg.css'),
disableNativeSpellChecker: false,
disableNativeTableHandles: false,
removeDialogTabs: 'image:advanced;image:Link;link:advanced;link:target',
customConfig: false, //no additional config.js
stylesSet: false, //no additional styles.js
```

* Write a text with multiple headings
* Add the toc
* Investigate in Developer tools, that all headings now have ids
* Save the page
* Investigate in Developer tools (or directly in the entity's metadata) that the ids are gone

The removal happens during saving the document in the third call of https://github.com/Elgg/Elgg/blob/24c70d2a6aa2cfb04f608db263da39786148bbbc/engine/lib/input.php#L258

**Comment by jdalsem** [comment]
simpler to reproduce... with everything disabled (no editor) you still have the problem with input like

`<p id="testid">text</p>`

will check why the ids are removed

**Comment by jdalsem** [comment]
currently every time you do `get_input` Elgg will validate the complete input stack (all fields) and thus if that happens multiple times Htmlawed will remember ids from a previous filtering... we thought about caching the input, so it will not filter multiple times... that is hard to do without breaking some other features, so for now we chose to just disable the unique id scan. This was the only thing that behaves globally in Htmlawed.

**Comment by dploeger** [comment]
Plus, it's just a major "inconvenience" to have potentially duplicate ids and thus invalid HTML. Good call.

**Comment by jdalsem** [comment]
plus it checks only partially the html (only the input) and not the full end result where you can have as much identical ids as you would like.. so it is not really that important

**Comment by jdalsem** [comment]
thanks again for the good report

**Comment by dploeger** [comment]
yw, thanks for looking into it in such a short time!
