### ISSUE TITLE
notifications must use routes in breadcrumbs

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12945]
https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/notifications/views/default/resources/notifications/groups.php#L26
https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/notifications/views/default/resources/notifications/index.php#L26

**Comment by jdalsem** [comment]
Closed in favor of #12943
