### ISSUE TITLE
Update breadcrumbs to use routes

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#12943]
Various plugins contain hardcoded urls in breadcrumbs... please update to use routes

https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/friends_collections/views/default/resources/friends/collections/add.php#L22-L23
https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/friends_collections/views/default/resources/friends/collections/edit.php#L23-L24
https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/friends_collections/views/default/resources/friends/collections/owner.php#L27
https://github.com/Elgg/Elgg/blob/d0230710b6bf0f905b76c1c1ea4ab40891b63560/mod/friends_collections/views/default/resources/friends/collections/view.php#L24-L25

Please note these are links to the `friends` plugin which could be disabled

**Comment by jdalsem** [comment]
Made it a more generic ticket
