### ISSUE TITLE
Multi level approvals on user Posts

### ISSUE THREAD

**Issue by srehmann** [Elgg/Elgg#12981]
Hi,
I am very new to elgg. Wanted to know if there's any plugin which could allow multi level approval for any user post before its shown on the main listing? Until it's approved, only the owner can see it and the approver.
If there ain't any plugin, can anyone help me write my own?

**Comment by jdalsem** [comment]
Hi @srehmann,

as far as i know there is no such plugin, but you better ask this kind of question in the community (http://www.elgg.org) as we like to keep github for bugreports and core development only.

If you need to find information on writing your own plugin, you can visis http://learn.elgg.org.
