### ISSUE TITLE
Edit avatar failure

### ISSUE THREAD

**Issue by fengbinchen** [Elgg/Elgg#12991]
If I go to my 'Edit avatar' page and click 'Save' without changing anything, it gives 'Avatar upload failed'. If I change the the avatar or resize/move the cropping window, then it works.

After some debugging, it seems that if I don't change anything, the file is not passed to the server side. However I've no idea how to fix this issue. I'm using version 3.1.1. Can you help? Thanks!

**Comment by jeabakker** [comment]
What would be the point of clicking on 'Save' if you haven't changed anything?

The current working is as intended, eighter:
- upload a new icon (and maybe change the cropping)
- or change the cropping of the current icon

Everything else will result in a failure as there are no changes
