### ISSUE TITLE
Elgg 2.3: testing compatibility with PHP 7.4

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12994]
Maybe Elgg 2.3 is already fully compatible with PHP 7.4 (not tested yet). But if not it might be worth testing and if there are issues that could be fixed while keeping BC it would be nice considering Elgg 2.3 is still LTS.

**Comment by jdalsem** [comment]
Automated testing is in the working https://github.com/Elgg/Elgg/pull/12977, however there are some issues regarding our unit tests to make the PR work that need to be fixed

**Comment by jeabakker** [comment]
We can't add PHPUnit tests for Elgg 2.3 on PHP 7.4 because we'd need to update the PHPUnit testsuite to a version which is incompatible with the minimal PHP version of Elgg 2.3.

So yes, maybe Elgg 2.3 can work with PHP 7.4 but we can't test is
