### ISSUE TITLE
FR Elgg 4: fully compatible with PHP 8.0

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12993]
AFAIR there's no release date for PHP 8.0 yet but it might get released in 2020.

May I suggest to consider releasing Elgg 4 not before PHP 8.0 is out and make it compatible with PHP 8.0? Only if PHP 8 might not get released in 2020 (or early 2021) it might make sense to release Elgg 4 sooner.

But right now I would like to suggest to NOT stick with the 1 year release schedule for major Elgg versions only for staying within the schedule. PHP 8 compatibility would be a nice feature (worth waiting for?).

**Comment by jdalsem** [comment]
As i am currently unaware what the exact changes for Elgg regarding to PHP 8 would be i am not sure we can make this kind of a promise. I do expect Elgg 4 to be coming somewhere at the end of this year, but i think it would be unwise for various reasons to set a minimal requirement of PHP 8 for the Elgg 4 release. It might not even be necessary. Making Elgg 4 compatible with PHP 8 is probably a high priority when PHP 8 is released, but it does not have to be a breaking change for Elgg. **We can add PHP 8 support in minor releases also.**

The 1 year release schedule is merely a guideline, not an exact law, but having a timeline for major releases gives us the opportunity to get rid of deprecated code that is high maintenance and will give us the ability to make some important changes. Postponing that is not a wise decision.

**Comment by iionly** [comment]
I've NOT suggested making PHP 8.0 a minimum requirement for Elgg 4! Just an ADDITIONAL compatibility with PHP 8.0 if possible.

With PHP 7.4 released I read about the next planned release to be PHP 8.0. And that 8.0 might get releases around the end of 2020 - but not a definite release date yet!

So, if it happens that PHP 8.0 is supposed to be released at about the same time a possible release date of Elgg 4 is near it might make sense to maybe wait a bit longer if it could be make compatible with PHP 8.0. I think it can't be decided right now with neither a release date for PHP 8.0 nor Elgg 4 know. Maybe making Elgg compatible with PHP 8.0 in a later Elgg 4.x release could be an option. But what if this wouldn't be possible without breaking BC? Then it would have to wait until Elgg 5 before it would be possible.

I believe this issue can't be decided either way just now. I just thought it would be useful as a reminder and once the situation with regard to release dates, features, compatibilty etc. of Elgg 4 and PHP 8 becomes clearer it could have been released.
