### ISSUE TITLE
FR Elgg 3.3: fully compatible with PHP 7.4

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12992]
If I'm not mistaken 3.3 will be the last minor release in the Elgg 3 branch. Maybe it would make sense with LTS in mind to implement PHP compatibility as best as possible, i.e. right now compatible also with PHP 7.4

**Comment by jeabakker** [comment]
already working on it #12977

**Comment by jeabakker** [comment]
it's now compatible with 7.4
