### ISSUE TITLE
FR: make Spam Login Filter a bundled plugin

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13008]
The Spam Login Filter plugin is a must have on 99% of all sites (at least in my opinion).

Unfortunately, there's no official release of the plugin for Elgg 3 available on the community site. The version on github might work or might not. But having such an important plugin only on github is not at all user-friendly (expecially with unexperienced users in mind).

It's surely not necessary to add many (if any) additional plugins to core. But I think the Spam Login Filter plugin should be considered definitely!

**Comment by rohit1290** [comment]
I have a working plugin for elgg 3 - https://github.com/rohit1290/spam_login_filter
If that is fine, I can take this up and add this plugin to the core.
