### ISSUE TITLE
Bundle a better theme

### ISSUE THREAD

**Issue by rjcalifornia** [Elgg/Elgg#13031]
Would you be open to review theme proposals so that it can be added instead of the current theme?

As of right now, default theme looks dated. A better theme will improve the image of elgg.

**Comment by jdalsem** [comment]
We are always open for proposals. You can try to do a redesign in a plugin, or just by providing PR's with css/html changes to core. Please also provide screenshots which showcase the changes. Is there a specific part of the theme you wish to tackle?

**Comment by rjcalifornia** [comment]
>Is there a specific part of the theme you wish to tackle?

Everything. A complete redesign. I have three proposals which are already available in the Community Plugins Page:

https://github.com/rjcalifornia/connect-theme

https://github.com/rjcalifornia/architect-theme

https://github.com/rjcalifornia/purple-theme

All those themes are templates ported to elgg, and all of them are under MIT license.

**Comment by RiverVanRain** [comment]
This commit should be [here](https://github.com/Elgg/community). 
@rjcalifornia Just make a new PR there instead of showing your repos.

**Comment by rjcalifornia** [comment]
> This issue should be [here](https://github.com/Elgg/community).
> @rjcalifornia Just make a new PR there instead of showing your repos.

Oh ok, will do

**Comment by iionly** [comment]
I think the issue had been opened here at the right place! The other repository is for the specific theme of the Elgg Community site (elgg.org) with exclusive adjustments just for this site. As I understand you want to propose a generic new theme to be bundled with Elgg (like Aalborg had been pre-3.0). For this purpose it might be best to make a PR here (and probably against the master branch for the upcoming 4.0 as I don't think any new plugins will be bundled with Elgg 3.3 at this time anymore).

**Comment by rjcalifornia** [comment]
> I think the issue had been opened here at the right place! The other repository is for the specific theme of the Elgg Community site (elgg.org) with exclusive adjustments just for this site. As I understand you want to propose a generic new theme to be bundled with Elgg (like Aalborg had been pre-3.0). For this purpose it might be best to make a PR here (and probably against the master branch for the upcoming 4.0 as I don't think any new plugins will be bundled with Elgg 3.3 at this time anymore).

Correct!
