### ISSUE TITLE
Provide an option to preserve comment order in Elgg 3x upgrade from 2x

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13032]
The comment order, now in reverse chronology in 3x, will make reading any discussion topsy turvy, suppose if you were to read so many discussions in reverse order in the current elgg site, it would be impossible to make head or tail out of the discussion. Similarly - same thing will happen in upgrades from Elgg 2x to 3x upgrade, halting upgrades indefinitely.  Another confusion is : in Elgg 3x in activity stream and in actual contents comments have different orders.  This is critically confusing for the site members. An out of the box solution will greatly enhance the experience of webmasters and end-users. Many thanks.

**Comment by jdalsem** [comment]
Like i mentioned here: https://github.com/Elgg/Elgg/issues/12533#issuecomment-573050205 the comment order will not change because of how the comments are loaded at this moment. I do not see how this is related to upgrades. What solution do you have in mind?

**Comment by daniyaree** [comment]
The solution may be to use whatever was being done in 2x for comments - preserve that in 3x also. As far as I can see - there was no issues, no problems, no requests to change the comment order as it appears in elgg org or elgg 2x

It is very related to upgrade in the sense, that all previous discussions will lose the order of reading and understanding a discussion, if the latest comment appears at the topmost. If the order of old comments ( in 2x) is preserved indeed in upgrade to 3x, and the changed order appears only in new comments after the upgrade, some discussions will have latest comments at top and some at bottom.

Before we proceed further in this discussion : can we put B before A, just because my keyboard is behaving odd? can we read English from right to left just because my spectacles are loaded with some sort of strange glasses now? What is the comment order in Elgg org now or in this GitHub or facebook or google forums or WordPress or almost anywhere?  If "how the comments are loaded at this moment" are a reason, I should ask to revert to how comments are loaded in 2x.

Another solution may be port into 3x the codes of Advanced Comment that let latest comments appear at bottom most, with comment entry box also at the bottommost + the user getting autoscrolled to the comment he or she just posted.

This is just so basic, and already in Elgg 2x as well as in Elgg org, its sort of sad that we are arguing about this here, and still no idea whether this will be solved.

**Comment by jdalsem** [comment]
There is the ability to influence the order with a hook https://github.com/Elgg/Elgg/blob/e17c3c94e14d8f9509a2f42b23803fd744895f34/engine/lib/comments.php#L52 and documented here http://learn.elgg.org/en/stable/guides/hooks-list.html#other

we could add a site setting, similar to how we did with the collapsed state of the comment box to control the default comment order.

**Comment by daniyaree** [comment]
A huge amount of thanks @jdalsem 
I was about to comment and say thanks - it was still re-opened at that time but unfortunately I got late.
One request is that : is the comment box appears at the end of all comments (just as it happens in elgg org now or in almost all discussion sites or social site). If its so, then great. If not, an admin option to put the comment box at the end of all comments will help
- end users to seamlessly use sites upgraded to 3x from 2x in expected UI behavior
- one will not have to scroll up all the way across 20, 30 or 50 or more comments to get to the comment box again thus discouraging commenting
Many thanks @jdalsem

**Comment by jdalsem** [comment]
i made a small followup PR that addresses your issue
