### ISSUE TITLE
make deleteOwnedAccessCollections and deleteAccessCollectionMemberships use batches

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13038]

**Comment by jeabakker** [comment]
With the current implementation it's hard to introduce batches.
Batches are there to reduce the chance of OOM errors. This is still a potential problem however in all the years we haven't ran into this issue related to access collections.

The duration of a call to these functions could also be a factor, but that won't be solved with batches. For that other changes need to be implemented.
