### ISSUE TITLE
should we drop diagnostics plugin?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13074]
it works... but i never used it in my entire live

**Comment by rjcalifornia** [comment]
No. Keep it.

**Comment by jdalsem** [comment]
@rjcalifornia thanks for your feedback. Can you let me know how/when you use this plugin?

**Comment by RiverVanRain** [comment]
@jdalsem I agree. Currently, it's an absolutely useless plugin. Almost all reports that it generates are already in the Elgg 'Information' menu section.
I never used it too and always delete it from our custom apps.

**Comment by jdalsem** [comment]
we kept the feature, but dropped the plugin :)
