### ISSUE TITLE
unable to see invalid plugins in plugin list

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13097]
because we now show the active plugins first, the invalid plugins are hidden, however switching to inactive plugins will not show the invalid plugins...

**Comment by iionly** [comment]
Why not just undo https://github.com/Elgg/Elgg/issues/12923 ? What was the motivation of showing just active plugins by default anyway apart from showing a shorter list by default?

**Comment by jdalsem** [comment]
> Why not just undo #12923 ?

maybe we will



> What was the motivation of showing just active plugins by default anyway apart from showing a shorter list by default?

most people only work with their active plugins, so having a shorter list could make sense

**Comment by RiverVanRain** [comment]
> most people only work with their active plugins, so having a shorter list could make sense

It's wrong. Newebies may not be aware of other inactive plugins. Personally, I want to know about the all plugins' statuses because some of them may suddenly be inactive (yes, this happens sometimes).

**Comment by rohit1290** [comment]
I would also prefer to show all the plugins (Active or Inactive) in one page.

**Comment by iionly** [comment]
Of course you mostly work with activated plugins only... but NOT necessarily on the plugin page!

I would go there mostly to make changes in the activated/deactivated state of plugins or changing the order of the plugins (where it might also matter to see the currently disabled plugins).

As RvR already said it's especially the newbies who would likely got confused additionally when disabled plugins are not displayed by default (resulting most likely in an additional and unnecessary question-reply loop onm the community site). And everyone else might have to make additional clicks most of the time to get all plugins displayed...

**Comment by jdalsem** [comment]
Fixed during https://github.com/jdalsem/Elgg/commit/5888aa89d3d1aab2c29a71074754ed5c8f27199f by no longer filtering the page by default to only show 'active'
