### ISSUE TITLE
Elgg 4: remove support for composer project plugin imitation

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#13096]
in `Elgg\Database\Plugins` there is support to handle a Composer base project (like the `Elgg/starter-project`) as a semi functional plugin. It can have
- `start.php`
- `views` directory
- `languages` directory

All this support should be removed in favor of making users create a fully functional plugin.

**Comment by jdalsem** [comment]
same as #11180?

**Comment by jeabakker** [comment]
agree
