### ISSUE TITLE
Elgg Image Entity not readable by social media

### ISSUE THREAD

**Issue by merilturock** [Elgg/Elgg#13122]
The Elgg core has a problem in storing the Elgg image entity for file, group the images are stored in 700 file permission in default & the HMAC url return has C1 instead of C0 ... The URLS that have C1 has no permission for other websites to retrieve the image this is causing a big trouble for elgg to get shared in social media.. 
Image URL don't work:  /serve-file/e0/l1581349092/di/**c1**/
Image URL work: serve-file/e0/l1581349001/di/**c0**/  

Elgg version: 2.3.14

**Comment by jeabakker** [comment]
You're correct that entity icons in Elgg 2.3 by default are session bound (c1) and don't work outside of the website.
In Elgg 3.0 we added a site security setting which can control if the entity icons are session bound (c1) or not (c0).

So time to update to a newer version ;)

**Comment by merilturock** [comment]
How to change all the entity to (c0) in elgg 2.3 where should i change?? .. As i have lot of things to upgrade at present it will take time for me to shift to the new version.. I will also request to release the final upgrade for elgg 2.3.X security/ fixing this update by reverting to the previous thing as this is ruining the elgg representation in social media... elgg 2.3.X cannot be left like this for the large no of users who are in the LTS batch ..

**Comment by RiverVanRain** [comment]
@merilturock Elgg 2 must die. Let core developers move forward.

**Comment by merilturock** [comment]
Dude even i will move to elgg 3.0 but not in immediate effect my website is bit large & it's 8 years old.. I have been in elgg 7.0 so i know how things work here.. What i am asking is you cant leave an elgg version with this feature that only support's one user while the other suffers being the LTS version & the last version of 2.3.X they need to do something about this are at-least give me a temp solution in removing this & giving it to default C0 .. I am not saying elgg should not move forward all those things.. I really appreciate the core Teams work they're doing a fabulous job..

**Comment by jeabakker** [comment]
https://github.com/Elgg/Elgg/blob/7804230a2fd21a1c6d411a4166114c8411786e80/engine/classes/Elgg/EntityIconService.php#L388
change the `true` to `false`

**Comment by merilturock** [comment]
Thank you jeabakker it's now working perfectly ..

**Comment by AbdulazizSobh** [comment]
I want to know how to activate this feature in version 3.3.4

**Comment by jdalsem** [comment]
> I want to know how to activate this feature in version 3.3.4

go to the security admin section and disable 'Session bound entity icons'
