### ISSUE TITLE
File plugin not clearing previous thumbnails when file is replaced / deleted.

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13189]
When a file is edited, previously created masterthumb* and thumb* files are not getting removed from users directory. Instead new thumbnails are created.

Also if we delete the file entity later, these images will remain as orphan entries in the data directory.

Elgg V 3.3.3, with only files plugin enabled.

**Comment by RiverVanRain** [comment]
Confirmed.
