### ISSUE TITLE
Notifications send out as if the logged in user has created the object and not owner_guid

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#13185]
I'm creating an object as admin on behalf of another user using a web service. But the notification send out displays the logged in admin user instead of the owner of the object.

This is because in this line

https://github.com/Elgg/Elgg/blob/d90b5904f4c0cca25e3b1c35003a595d1e4e26c2/engine/classes/Elgg/Notifications/Event.php#L55

the logged in user is used instead of the owner of the object.

What's the cause for this?

**Comment by jeabakker** [comment]
The automatic notifications (based on events) assume the current user did the action which triggered the event.
You can always look at the `prepare, notification` or `prepare, notification:<type>` hooks to change the actor of the notification event to the owner of the object (in case of your webservice call).
http://learn.elgg.org/en/stable/guides/notifications.html#enqueued-notifications
http://learn.elgg.org/en/stable/guides/hooks-list.html#notifications

**Comment by jdalsem** [comment]
If you are doing things 'as another user', you can make sure you are logged in as that user by setting the session data accordingly. River events and notifications always assume the logged in user as the actor.

**Comment by dploeger** [comment]
Yeah, I know that there are workarounds for this but I was keen on understanding why there's a difference between the actor and the owner of the object?

**Comment by dploeger** [comment]
But thanks for the hints.

**Comment by jdalsem** [comment]
difference between actor/owner is for example 'I join YOUR group' or 'I like YOUR blog'

**Comment by dploeger** [comment]
Ahhhh! That makes sense. Thanks.
