### ISSUE TITLE
Elgg 3.3.3: Lost password failure

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#13183]
Steps to Reproduce:

1. Request a new password using 'Lost password' form
2. Receive an email, confirm URL and enter a new password which contents an ampersand  **&**
3. Automatically logged in.
4. Logged out and try to login again using new password

You will get Error message: _We could not log you in. Please check your username/email and password._

[Disscussion on Community](https://elgg.org/discussion/view/3017062/troubles-with-forgotpassword).

Same on issue #13067

**Comment by jeabakker** [comment]
nice find ;) existed since Elgg 1.8.4
