### ISSUE TITLE
Install plugin via cli

### ISSUE THREAD

**Issue by dploeger** [Elgg/Elgg#13196]
It's currently not possible to fully install a plugin via the command line, because the plugins on disk are only refreshed when opening the UI. There are some other points where the refresh code is called (in ActivateNewPlugins.php for example), but I haven't found a way to run the code using the cli.

So when running plugins:list or plugins:activate, the plugins should be refreshed as well.

**Comment by jdalsem** [comment]
hmm good point... will check this out

**Comment by dploeger** [comment]
I'm at proposing a plugins:refresh command in a PR.

**Comment by jdalsem** [comment]
or `plugin:list -refresh`?

**Comment by dploeger** [comment]
Good idea. I'm still trying to figure out how to setup the test case for that. I already overridden getPath to return a path inside the test folder, but the plug-in entities in the database are mocked as well, right?

**Comment by dploeger** [comment]
Added a pr for that.

**Comment by dploeger** [comment]
Sorry, had some hard time with my IDE doing things that messed up the files. Finally added the correct PR. :)

**Comment by dploeger** [comment]
@jdalsem Any chance this might get merged? My test system currently relies on that.

**Comment by jdalsem** [comment]
we are aiming at a new release this friday
