### ISSUE TITLE
Issues on file input validation

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13190]
When a user is uploading a file through the "file" plugin, no server side validation is happening on the upload input field. Only client side validation is happening.

With simple manipulation, users can create a file entity without uploading any file.

Elgg V 3.3.3, with only files plugin enabled.

**Comment by RiverVanRain** [comment]
Just reproduced this:
`http://localhost/elgg/action/file/upload?__elgg_token=nZXf4c794EnvUsqY1lXbnQ&__elgg_ts=1587744268&upload=false&access_id=2`

The parameter _false/true_ for 'upload' input doesn't matter.
