### ISSUE TITLE
File plugin not generating thmbnails according to the registered sizes.

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13208]
Though three icon sizes, (small, medium, large) are registered using the file_set_custom_icon_sizes() hook for image uploads, only a thumb file 60x60, a master thumb (same size as the original uploaded image) and the original image is getting uploaded. The other registered thumbnails are not getting generated.

**Comment by jdalsem** [comment]
thumbnail images are generated on first use... if these sizes are not used anywhere on your site, the icons will not physically generate

**Comment by sarathsince85** [comment]
Thanks @jdalsem. Sorry for wrong reporting.
