### ISSUE TITLE
Friends access collection is broken

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13202]
Creating a new friends access collection results in a fatal error, although the collection get created.
Simple Elgg V.3.3.4, installation
Attached is the error_log, hope it helps. 

> [Fri May 08 05:37:36.403515 2020] [php7:notice] [pid 15192:tid 1920] [client ::1:52605] [2020-05-08 00:07:36] ELGG.CRITICAL: Exception at time 1588896456:\r\nError: Object of class Elgg\\Menu\\Menu could not be converted to string in C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Views\\HtmlFormatter.php:315\r\nStack trace:\r\n#0 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\lib\\output.php(139): Elgg\\Views\\HtmlFormatter->formatElement('div', Array, Object(Elgg\\Menu\\Menu), Array)\r\n#1 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\views\\default\\object\\elements\\summary\\metadata.php(41): elgg_format_element('div', Array, Object(Elgg\\Menu\\Menu))\r\n#2 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(508): include('C:\\\\xampp\\\\htdocs...')\r\n#3 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(441): Elgg\\ViewsService->renderViewFile('object/elements...', Array, 'default', true)\r\n#4 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\lib\\views.php(222): Elgg\\ViewsService->renderView('object/elements...', Array, 'default')\r\n#5 C:\\xampp\\htdocs\\sites\\elgg\\mod\\friends_collections\\views\\default\\collections\\collection.php(66): elgg_view('object/elements...', Array)\r\n#6 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(508): include('C:\\\\xampp\\\\htdocs...')\r\n#7 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(441): Elgg\\ViewsService->renderViewFile('collections/col...', Array, 'default', true)\r\n#8 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\lib\\views.php(222): Elgg\\ViewsService->renderView('collections/col...', Array, 'default')\r\n#9 C:\\xampp\\htdocs\\sites\\elgg\\mod\\friends_collections\\views\\default\\resources\\friends\\collections\\view.php(28): elgg_view('collections/col...', Array)\r\n#10 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(508): include('C:\\\\xampp\\\\htdocs...')\r\n#11 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php(441): Elgg\\ViewsService->renderViewFile('resources/frien...', Array, 'default', true)\r\n#12 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\lib\\views.php(404): Elgg\\ViewsService->renderView('resources/frien...', Array)\r\n#13 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Router.php(280): elgg_view_resource('friends/collect...', Array)\r\n#14 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Router.php(128): Elgg\\Router->prepareResponse(Object(Elgg\\Http\\Request))\r\n#15 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Router.php(104): Elgg\\Router->getResponse(Object(Elgg\\Http\\Request))\r\n#16 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Application.php(473): Elgg\\Router->route(Object(Elgg\\Http\\Request))\r\n#17 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Application.php(359): Elgg\\Application->run()\r\n#18 C:\\xampp\\htdocs\\sites\\elgg\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\Application.php(415): Elgg\\Application::route(Object(Elgg\\Http\\Request))\r\n#19 C:\\xampp\\htdocs\\sites\\elgg\\index.php(8): Elgg\\Application::index()\r\n#20 {main}\r\n {"exception":"[object] (Error(code: 0): Object of class Elgg\\\\Menu\\\\Menu could not be converted to string at C:\\\\xampp\\\\htdocs\\\\sites\\\\elgg\\\\vendor\\\\elgg\\\\elgg\\\\engine\\\\classes\\\\Elgg\\\\Views\\\\HtmlFormatter.php:315)"} {"backtrace":[],"process_id":15192,"memory_peak_usage":"14 MB","memory_usage":"8 MB","url":"/sites/elgg/friends/collections/view/7","ip":"::1","http_method":"GET","server":"localhost","referrer":"http://localhost/sites/elgg/friends/collections/add/testuser1"}\n, referer: http://localhost/sites/elgg/friends/collections/add/testuser1

**Comment by RiverVanRain** [comment]
I can't reproduce it. All works very fine.

**Comment by RiverVanRain** [comment]
This does not affect the "add friends collection" action but the _'object/elements/summary/metadata'_ view.
