### ISSUE TITLE
File plugin throwing unfriendly error messages

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13207]
The file plugin is throwing unfriendly messages to the end users when an error happens. For example when a user uploads a bigger size file, a Fatal error appears with the blue screen. This is not at all a friendly experience to the end user. We need to make it more user friendly, like the regular error messages.

Elgg 3.3.4 installation

**Comment by RiverVanRain** [comment]
Fixed in Elgg 4
