### ISSUE TITLE
Unicode Teaser or Excerpt in the River page or Blog posts list page showing data corruption or non-unicode characters

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13229]
Unicode words have Juktakkhor or Conjunctive words and if they get truncated irregularly, the resulting thing can look ugly or meaningless or just odd, also if they show non-unicode characters like & etc it breaks the viewing aesthetics or pleasure.
This happens in River page or the user's Blog index page where small truncated portions of texts of the blog are displayed in a list like way.

For example, I get 
দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ&...
Note that & is not expected and looks odd
What is expected is
দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ... or something similar without the "&"
To reproduce this (in Elgg 2x, I am yet to test Elgg 3x)
please copy paste the following in the blog BODY field, save and then view the River page

`দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষদ্ধক্তপ্লক্তক্ষ দ্ধক্তপ্লক্তক্ষ `

This apparently does not happen in two or three other cms which I tested previously, so I am not sure what is happening here or what we can do here for example, like **Unicode::Truncate - Unicode-aware efficient string truncation** so that **All truncated strings will continue to be valid UTF-8: it won't cut in the middle of a UTF-8 encoded code-point.**

Please note that same problem can happen not just in blog but anywhere where we must truncate for display with truncated part ending with ... etc. In fact long unicode user display names or such other file name etc can also appear odd if such truncation happens.

Please see this https://metacpan.org/pod/Unicode::Truncate

**Comment by daniyaree** [comment]
Thanks @RiverVanRain. As I already told in the opening post : I did not test in Elgg 3x. I tested in 2x and wanted to find out if others are getting the "error" too. now I have tested in Elgg 3x and yes, the error is NOT there. So it means, in this thing, 2x and 3x are truncating differently or something is different. If I / anyone can pinpoint, I may try then back-porting to 2x. That is why asked you, if you are able to reproduce it on 2x. Many thanks.

**Comment by RiverVanRain** [comment]
> now I have tested in Elgg 3x and yes, the error is NOT there. 
So, it's not [a security issue](http://learn.elgg.org/en/3.x/appendix/support.html#long-term-support-releases) for Elgg 2 and must be closed here.

**Comment by daniyaree** [comment]
Security issue? No, I never told its a security issue. Its an usability issue for Unicode users. Whatever is being done in 3x so as NOT to produce that "error" should be applicable to 2x also, imho. Thanks.

**Comment by jdalsem** [comment]
Closing this as it look as 3.x does not have this issue and 2.x will only receive security updates
