### ISSUE TITLE
Please bring back the ease of navigation, and ease of adding content by single click in Elgg 3x

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13231]
Ideally, it would be great if a mini form for adding blog post could be found atop every activity and profile page. This is because something similar to hypewall  never got incorporated into core despite several discussions in github, and Wire behavior is not understood by the current generation of users. Still, Elgg 2x provided ease of adding blog content, by intuitive one  click action. In Elgg3x, to a new site member it is challenging "how to add content", while existing users have to unlearn and re-learn things, which "trouble" they may avoid and no more post content.

In Elgg2x, as soon as you log in to the site, you see in the right side bar, link/menu to your own blog and there you can start posting.
![2a](https://user-images.githubusercontent.com/43325988/84027798-34e3c480-a9ad-11ea-89a0-2813e4d5bc0d.jpg)
![2b](https://user-images.githubusercontent.com/43325988/84027815-3a410f00-a9ad-11ea-9a96-1965d8b773ad.jpg)

In Elgg 3x, there is nothing as soon as you login, that can inspire you to add content or engage with the site. You expect something will come up if you click the profile pic or Account drop down at the rightmost corner - but then, there is also nothing, or nothing from clicks thereto.
Compare this with the simplicity, ease and UI friendliness of Elgg 2x.
I understand that everything can be "developed" but OOB if the experience is great, whats the harm? By dropping nav bar the overall size of Elgg 3x has not reduced, in fact, its much more bulkier than Elgg2x. Speed is also little bit less, as appreciable on slower connections. So I think and propose with all humbleness, let us return to the easier ways for the end user / site-members.

![1](https://user-images.githubusercontent.com/43325988/84027836-4331e080-a9ad-11ea-895c-cbdaab5f8835.jpg)
![1b](https://user-images.githubusercontent.com/43325988/84027854-4927c180-a9ad-11ea-982f-6f5f635674f0.jpg)

**Comment by jdalsem** [comment]
The hypewall discussion has been started here: #10553. 

The number of clicks to be able to write a blog in Elgg 2 vs Elgg 3 are the same. The only difference is that on your landing page (activity) there is no owner block menu, thus you need to use the site menu for navigation to the blog feature.

**Comment by daniyaree** [comment]
Thanks.
Not same number of clicks to own blog imho
In Elgg 2x, from landing page its just one click to your own blog page.
And its obvious and inviting as the owner block is prominent, your own icon or pic etc
In Elgg 3x, blog link in top nav bar - its so neutral, "whose blog" "may be general blog list" etc 
Also it is 2 clicks to your own blog > first you click on Blog and reach blogs/all 
then from there to your own blog
The owner block was there for a purpose ! It also served another purpose of making the screen not too wide to read on modern desktop pcs out-of-the-box. At present the distance the eyeballs have to travel from left to right and vice versa is awesome (and forbidden in all UI) - nad the redesign is responsive thus in smartphones but not in desktop - the owner block mitigated this to some extent but this is out-of-topic here :)

**Comment by jdalsem** [comment]
> Not same number of clicks to own blog imho

It is 2 clicks to start contributing, as the "Add a post" is also on the "All blogs" page. It is indeed an extra click to get to 'Your blogs'

The owner block menu is not consitently present throughout the site. So you can not assume it is there for 'readability' of the content. In some cases it is a side effect at best. The logic of the owner block is that it is present on pages where content is shown that is owned by a certain user. On 'all activity' that is not the case (it is owned by different persons), but it is on 'My activity'.

The current max width of the screen = 1280px. That might be debatable, but choices have been made in the past. Also this is relatively easy to adjust as a lot of the css variables are hookable (by a developer).

As this issue is only about a difference of opinion i am closing this, but if you still want to continue discussing it feel free to do so.

**Comment by daniyaree** [comment]
yes, its not a critical issue - please feel free to close as unnecessary long list of "open" issue is not wanted. however, just as a side note, its not 1280 always - its 1300 plus upto 1900 and even at 1280 its too wide an UI to read and scan - that is why books have columns if its too wide. Its not my words, any UI audit will say this. having BLOCKs helped this - they break the viewing area in an easy for eye to digest ways. In wide screens blocks are shown laterally while in mobile they go to the bottom. Thus everyone is benefitted  - be it desktop user or be it smartph user. As noted this is out-of-topic here but I mentioned if any theme developer is casually reading these discussions may help in his or her theme plugin for the community.

**Comment by jdalsem** [comment]
> its 1300 plus upto 1900 and even at

Where do you see this happening? The css  contains max-width to 80rem, which effectively should limit the max width to 1280px. It should not exceed this limit anywhere.

The 'blocks' are potentially present (there are left and right sidebar elements). But if not used content will flow until it reaches max width.

**Comment by daniyaree** [comment]
I see - I get your point. You are correct. What I was meaning that 1280 is much more than the recommended 700 for desktop reading. UI principles are all about personal opinions as well as real life user studies. 700 is what they recommends, and Elgg 2x with side blocks helped that. 

Also its convenient for the user to read same width in every page, for example, in activity page, which is greatly read - one type of width - then in blog page, another type of width - this hampers the flow.

In 1300 to 1900 screen 1280 width looks like a lot (feeling and perception issue)  and when there are blocks (placed laterally, right or left) it becomes easy for the eye and the brain. So far with Elgg 2x we did not have to bother as things just happened out of the box :)
