### ISSUE TITLE
"Like" count is not getting refreshed immediately in Elgg 3x

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#13237]
In Elgg 2x, as soon you like something, the Like icon (thumbs up) changes color as well as "1 like" appears instantly. In Elgg 3x it does not appear unless the page is refreshed. Compare with the bottom  picture. This is not an expected behavior as well as the site-members over the years have got accustomed to the usual behavior.
Elgg3x does show highlighted or color-changed thumbs-up icon but no "1  like"
![1](https://user-images.githubusercontent.com/9887635/84572715-8e872d00-adb9-11ea-9000-20bd1334c569.jpg)
Elgg2x shows instantly "1 like"
![2](https://user-images.githubusercontent.com/9887635/84574281-0f96f200-adc3-11ea-8f3c-5079127bd5dd.jpg)

**Comment by RiverVanRain** [comment]
All works very well. 
We're discussed already about it on Community.
It's occurs on the shared hosting or slow DB connection only.
Also, you've not provide which Elgg version you use.

**Comment by dranii** [comment]
Its Elgg 3.3.6. And it does not work as well as Elgg 2x in this issue. Its not about my hosting but what connection end users are using. However, this issue remains even if you wait and wait - see the screenshot. It mentions "1 like" - that is, when the 1st like is made, the thumbup icon gets highlighted/changes color but "1 like" is never shown unless you refresh the page. In Elgg 2x one does not have to refresh the page - as it shows up instantly.

**Comment by jeabakker** [comment]
You're correct that the 1st like doesn't show up directly after clicking Like. 

This has to do with how we make the menu items. In Elgg 2 this was a mess and we fixed this in Elgg 3. The only downside is that after the 1st Like no counter appears. After that the counter works and any additional Likes are shown directly.

The list of people who Likes a post get ajax loaded, so server response and connection speed have to be taken into account. The reason we now load it later and not directly on the page is performance.

**Comment by jdalsem** [comment]
Closing this as the '1 like' text not showing has been explained. If you are the first liker... there is no need to show the text '1 like' instantly, because you can deduct that yourself
