### ISSUE TITLE
FR : please provide visual clue if an user have joined a group or not

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13241]
In the Group Home page or Group landing page, there can be a long list of groups and many of which I may have already joined. Although there are obvious links to My Groups | Groups I own etc, it is good and helpful to see at a glance which I have joined or YET to join. In fact, its already there, but hidden inside the vertical ellipsis (3 dots) that appear by the side of each Group's name.  Can it be simply freed from the vertical ellipsis, and just show "Join group" or "Leave Group" or simple icons (entry or exit arrow). If this is provided in the core, imho it will be an useful and helpful UI/UX to lots of users.

`On Android, it is referred to as Overflow Menu. ... Technically these are used to display Secondary options as opposed to Primary ones which are directly displayed in the UI. Overflow Menu options can also contain Destructive actions. (delete/edit)`

Thus, Joining (or leaving) a group is a primary action (the first or most primary thing I can do to a Group : Join it), and thus it may be good to just put a mini text label or indicative icon, rather than 3 dots here.

**Comment by jdalsem** [comment]
I disagree on having JOIN/LEAVE as primary actions in a list of groups. I do however think we need to add visual indicators to the listing of group if you are already a member/owner of the group. I suggest we do this in the imprint (textual) next to `x members`.
