### ISSUE TITLE
Group owner cannot edit or delete abusive comment

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13240]
I am using Elgg 3.3.6, clean install without anything extra.

Apparently a  Group Owner (group admin / the person who created the group) can edit/delete in his group : 
a blog post by another user, 
a photo by another user
a file uploaded by another user
a discussion post (can be deleted or closed)
if such stuff is  bad or obnoxious or against group policy. 
However, if there is a bad comment by a another user (a group member), for example a bad user or a good user making an abusive comment occasionally, and there is immediate need to hide/edit/delete it, its not possible by the Group owner.

**Comment by jdalsem** [comment]
so what you are saying is that group owners can not edit/delete comments on group content?

**Comment by daniyaree** [comment]
Yes, Group Owners can edit/delete abusive (or "bad") Group content but cannot edit/delete comments on group content.

**Comment by jdalsem** [comment]
we will investigate, as this should be possible

**Comment by daniyaree** [comment]
Thanks !

**Comment by iionly** [comment]
It hasn't worked on Elgg 2.x either (while it had worked on Elgg 1.x if I remember correctly). To get it done right (as I think it should be) I wrote a plugin for Elgg 2 (see https://elgg.org/plugins/2642878). I think it might still work even on Elgg 3 (untested; the only difference is that the group discussion replies might no longer have to be handled separately).

**Comment by daniyaree** [comment]
Thanks @iionly 
Elgg_2.X_comment_edit_permissions_v2.0.0 (by iionly) seems to work, **though I need to test more**. [Using  Elgg 3.3.6, clean install, no other extra stuffs ]. So far, what I have found :

- Group owner can edit or delete a comment.
- The comment author can edit or delete his / her own comment.
- Another group member cannot edit/delete that comment.
- In the River also, the comment (deleted one) is removed

This is what is expected behavior. This is also exactly what I was looking for. **Many ∞ thanks @iionly**. If this continues to work with all future next versions of Elgg, then it will be really great and of immense help to all. 

Off topic - I have three questions which are not urgent and off-topic but related to this

- can this plugin have an extension / option to empower a Blog owner to edit/delete a comment (or at least show : under moderation) because this is the expected behavior in any Blog (Wordpress, Drupal etc), and members are always asking for this facility, as Abuse reporting for a specific comment is not a core feature of Elgg.
- Elgg_2.X_comment_edit_permissions_v2.0.0  - is there anything that is critically stopping to label it as Elgg_3.X_comment_edit_permissions_v2.0.0 
- As this problem is apparently solved, I am closing it for now. Please be kind to bear with me if I find problems again and need to report and re-open) or may be (if need be)  an issue can be submitted  [here](https://github.com/iionly/comment_edit_permissions) ?

**Comment by jeabakker** [comment]
reopening this issue al we still need to fix this unexpected behavior in Elgg
