### ISSUE TITLE
Listening to events from ckeditor

### ISSUE THREAD

**Issue by mopena** [Elgg/Elgg#13266]
Does anyone know how to listen for a "click", "change", "blur" on a textarea element that has been converted into a ckeditor input?

**Comment by jeabakker** [comment]
For help in developing Elgg, please go to our community site.
I think this is a question best asked in this group https://elgg.org/groups/profile/834462/beginning-developers

Github is mainly for bug reporting / feature requests (and PR's) The Elgg community is for support
