### ISSUE TITLE
When I visit my elgg site in https, the resources are not displayed.

### ISSUE THREAD

**Issue by ChengxiX** [Elgg/Elgg#13263]
When I visit my elgg site in https, the css and other resources are not displayed. I ve learn that it is because the chrome's strategy, so what should I do?
Maybe I can edit the sql to replace all the http://... link to https://... link

**Comment by RiverVanRain** [comment]
GitHub isn't a support group.
Ask your question on Community [elgg.org](https://elgg.org/)
Besides, there's already discussions about it.

**Comment by ChengxiX** [comment]
> GitHub isn't a support group.
> Ask your question on Community [elgg.org](https://elgg.org/)
> Besides, there's already discussions about it.

Thank you.
