### ISSUE TITLE
Registering plugin hook 'view', 'all' via elgg-plugin.php not working

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13261]
I try it with
```
	'hooks' => [
		'register' => [
			'view' => [
				'all' => [
					'elggx_fivestar_view' => [],
				],
			],
		],
	],
```
but it doesn't work, e.g. I don't see the callback registered in the list of hooks in the admin "Inspect" section.

When taking the Boostrap approach using elgg_register_plugin_hook_handler() in the init function it works though.

Could it be that 'all' is currently not supported in elgg-plugin.php hook registering or is it just to be done differently (docs lacking proper info?)?

**Comment by jeabakker** [comment]
drop the `register` key like this
```php 
'hooks' => [
	'view' => [
		'all' => [
			'elggx_fivestar_view' => [],
		],
	],
],
```

**Comment by jeabakker** [comment]
the `register` part is implicit, if you with to unregister that needs to be an option of `elggx_fivestar_view` see http://learn.elgg.org/en/stable/guides/plugins.html#elgg-plugin-php for examples

**Comment by iionly** [comment]
Oh, I did take the example code from there. I guess I chose the wrong one though. But my main mistake probably was that I included the file with the callback function with require_once(). It seems it's mandatory to provide a class that contains the hook callback function instead.

**Comment by jdalsem** [comment]
it should be possible to use a function callback... can you post a sample of your elgg-plugin containing the hook registration and the inclusion of the lib file containing the function? that way maybe we can tell you what is going wrong

**Comment by iionly** [comment]
It looks a bit like a mess to me. Unfortunately...

In https://github.com/iionly/elggx_fivestar/blob/master/elgg-plugin.php is an example how I include the files with the hooks (in this case the registering of the view failed to work due to the above resolved issue with the wrong hook name).

But I came across other problems. In one case with another plugin it probably failed to work to register the hook callback function because the function still used the legcy style arguments. I would have to verify this though because I moved the plugin hook registration from elgg-plugins.php to the Bootstrap class init() function before I had noticed this.

Today I have yet another case: I added a class with two plugin hook callback functions. I'm trying to register the plugin hooks in exactly the same way in elgg-plugin.php. For one callback it works but for the other it does not. No errors in logs or anywhere.

Even worse: unregistering callbacks (from Elgg core). If the plugin hook registration is still done in start.php I can't unregister via elgg-plugin.php. It's a bit frustration if I have to do the unregistering/registering by trial and error in each case to see which method works.

**Comment by jdalsem** [comment]
> It looks a bit like a mess to me. Unfortunately...

Trust me, it will get better 



> In https://github.com/iionly/elggx_fivestar/blob/master/elgg-plugin.php is an example how I include the files with the hooks (in this case the registering of the view failed to work due to the above resolved issue with the wrong hook name).
> 
> But I came across other problems. In one case with another plugin it probably failed to work to register the hook callback function because the function still used the legcy style arguments. I would have to verify this though because I moved the plugin hook registration from elgg-plugins.php to the Bootstrap class init() function before I had noticed this.

please verify and report if you an actual problem



> Today I have yet another case: I added a class with two plugin hook callback functions. I'm trying to register the plugin hooks in exactly the same way in elgg-plugin.php. For one callback it works but for the other it does not. No errors in logs or anywhere.

Could you provide some detail (maybe in a new ticket) about the specific problem you have?



> Even worse: unregistering callbacks (from Elgg core). If the plugin hook registration is still done in start.php I can't unregister via elgg-plugin.php. It's a bit frustration if I have to do the unregistering/registering by trial and error in each case to see which method works.

This is indeed the case (for some situations), but we are in a transition period. In Elgg 4 there will be no start.php, only elgg-plugin and bootstrap class, so if you are unregistering, you have to pay a bit more attention at this moment.
