### ISSUE TITLE
ui: Making elgg listing more flexible

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13299]
Right now for entity listing ul and li are used..

- https://github.com/Elgg/Elgg/blob/3.3/views/default/page/components/list.php#L76
- https://github.com/Elgg/Elgg/blob/3.3/views/default/page/components/list/item.php#L54

Instead of that can we make it more flexible so that it accepts div, table tags etc easily, by passing it as a listing param?

**Comment by jeabakker** [comment]
You can pass `list_type` to `elgg_list_entities` if you wish to use a different listing type (eg. table) also you can pass `item_view` to show an item differently.
https://github.com/Elgg/Elgg/blob/400112c2188a4bac9f7327d8e15471f9c22841d4/engine/lib/entities.php#L563-L570

**Comment by sarathsince85** [comment]
@jeabakker : I tried that and I am currently using that. But for a simple thing like this, we need to unnecessarily duplicate two views. For example if I want to wrap it inside "div", I need to duplicate two files. 

Instead if we can pass two additional parameters like "list_wrapper" & "item_wrapper", we can just reuse the same core files, without duplicating it in the theme again.

**Comment by jeabakker** [comment]
Currently there are no plans of implementing this request.

There are several ways to change the listing
- using `list_type` and `item_view` in `elgg_list_entities()`. Keep in mind in the new views you can still output the 'original' core views to prevent code duplication. This gives the most flexibility to change output.
- you can use the `view`, `<view name>` hook to wrap the output in any element you like, see for example https://github.com/Elgg/Elgg/blob/66ec1342faef7d693d072b48264151d374c46576/mod/developers/start.php#L281-L296

**Comment by sarathsince85** [comment]
I am sorry if I am missing something here or I am not clear presenting my issue.

As per your above answer, suppose if I want to get an output like
```
<div class="elgg-list">
    <div class="elgg-item elgg-item-user">
        .....
    </div>
</div>
```
instead of 
```
<ul class="elgg-list">
    <li class="elgg-item elgg-item-user">
        .....
    </li>
</ul>
```
I have to either 

1. override the page/components/list.php and page/components/list/item.php file or
2. use the view hook and then use some pattern recognition algorithm on the output to identify and replace the "ul" and "li" with "div"

Seems both methods are overkill for a simple problem which can be resolved by passing two additional parameters. 

I can render my own html output with out overriding views by using ege* and then iterating through it. But this also is a problem as I have to take care of pagination etc.

**Comment by jeabakker** [comment]
> I have to either
> 
>     1. override the page/components/list.php and page/components/list/item.php file

correct

This will make sure that every listing in the system is changed to your requirements. You then don't have to change the calling code. So overriding 2 views will make sure the entire system is changed, that's very little effort.
If you wish to only do it in certain listings than you would have to change all the calling code paths.

**Comment by sarathsince85** [comment]
> This will make sure that every listing in the system is changed to your requirements

I dont plan to change every listing in the system. For example I may be using the core plugins like blog, pages etc... and in this case, I am fine with the default listing.

I may need custom listing in special scenarios only. In such cases, I can easily pass those two above variables and get a listing according to my needs.

> So overriding 2 views will make sure the entire system is changed, that's very little effort.

Yes.  overriding two core views is easier job. But maintaining those two views updated for every new release of Elgg is a difficult task.

> If you wish to only do it in certain listings than you would have to change all the calling code paths.

Why? For example, if I want to create a list wrapped in div, I can easily do it by
```
echo elgg_list_entities([
    ....
    'list_wrapper' => 'div',
    'item_wrapper' => 'div',
    ....
]);
```
This wont break anything in the system. We can modify the core views like below

1. In the list.php, give 'ul' as a fallback like
```
$list_wrapper = elgg_extract("list_wrapper", $vars, "ul");
----
echo elgg_format_element($list_wrapper, ['class' => $list_classes], $list_items);
```
and in the item.php give 'li' as fallback
```
$item_wrapper = elgg_extract("item_wrapper", $vars, "li");
----
echo elgg_format_element($item_wrapper, ['class' => $list_classes], $list_items);
``` 
Hope I am clear. This will give more flexibility and less maintenance troubles.
