### ISSUE TITLE
allow access to the correct client IP when behind loadbalancer / reverse proxy

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#13344]
In \Elgg\Http\Request
https://github.com/Elgg/Elgg/blob/cc990bda2a2eed8f7d794c2291b5521cca534eb6/engine/classes/Elgg/Http/Request.php#L265-L279

A setting needs to be set to allow the correct IP to be returned

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/13356
