### ISSUE TITLE
Search results are displayed twice

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#13353]
Some metadata are displayed twice in the searching results.

For example, 'interests, skills':
![screenshot](https://user-images.githubusercontent.com/2176145/101092801-304e4080-35cb-11eb-8b83-462a24e768d5.png)

#13268 doesn't affect this issue

**Comment by jdalsem** [comment]
Which version of Elgg? Any additional plugins? Does it happen with those extra plugins disabled?

**Comment by RiverVanRain** [comment]
Elgg v3.3.13.
No any activated 3-rd party plugins.
Issue persists with deactivation of all bundled plugins except Profile and Search.
