### ISSUE TITLE
Deploy translated documentation on learn.elgg.org

### ISSUE THREAD

**Issue by Facyla** [Elgg/Elgg#13351]
Hello, 

The translation of all projects on Transifex have been fully completed for French language : https://www.transifex.com/elgg/dashboard/all_resources/fr/

How can this work now be integrated on http://learn.elgg.org ? Currently only "en", "es" and "de" are available, whatever the version : 
![image](https://user-images.githubusercontent.com/286492/100716723-60be9080-33b9-11eb-87ac-5e1fc6e12e38.png)

I know the release process should add all available translations above some percent of completion, however the latest release apparently did not automatically integrate these translations (they were above 95%, but not yet 100% at that time). 
Also, i do not know if that process includes the older translations as well ? The translation coverage is now 100% for all available documentation versions (Elgg 1, Elgg 2 and Elgg 3), and i really think users with older versions would also find documentation Elgg 1.12 and 2.3 still valuable.

I'd be happy to help integrate these translations if i can in some way ?

**Comment by jdalsem** [comment]
This is something we need to add to the projects of ReadTheDocs. As of last week i also have the rights to manage these translation projects, so i hope to add it soon

**Comment by jdalsem** [comment]
The French translations are now available on http://learn.elgg.org/fr/latest/

The translations for Elgg 1.x and 2.x are not updated as they are not yet pulled from transifex into the Elgg repository. For 1.x this will not happen. For 2.x this might happen if there comes a patch. This might be done a final time just before release of Elgg 4.x.

The translations for Elgg 3.x will be updated on a regular basis.

**Comment by Facyla** [comment]
Thank you very much !
