### ISSUE TITLE
elgg4: no minified js/css??

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13384]
on fresh install simplecache is not uncommented in `elgg-config/settings.php` but also not configurable in `admin/site settings`

2 questions:
- should it not be uncommented in generated settings file?
- why is it not configurable in site settings? If not configurable why show a toggle?

**Comment by RiverVanRain** [comment]
> should it not be uncommented in generated settings file?

I always do this during installation.

> why is it not configurable in site settings? If not configurable why show a toggle?

I suppose this can be removed from site settings. 
We've the Developers tools in browsers and we can use the 'Pretty print' option to view no minified JS/CSS.
