### ISSUE TITLE
The problem of showing the titles of the elements

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13410]
Since I updated the script to the latest version, this problem appeared, which is that the titles of the posts and files and all the sections on the site do not appear. This is the case in Google, and while sharing the topic on a site such as Facebook and the sites that accept participation, the biggest problem is that it does not appear on Google as well. The section, for example, posts, then the name of the site. This is everything, and the title of the main topic does not appear 
this discussion on elgg https://elgg.org/discussion/view/3094371/why-does-not-the-title-of-the-blog-or-other-sections-appear

**Comment by jdalsem** [comment]
What is your 'latest' version?

Does this problem occur with only default Elgg plugins enabled? Or do you have custom plugins, like a template or some SEO plugin that might interfere?

**Comment by AbdulazizSobh** [comment]
Use the latest version v3.3.16
Also, I am using the same plugin that I used previously. I just updated some
Also, this is a list of plugins that I use: https://textuploader.com/18zwo

**Comment by RiverVanRain** [comment]
This has to do with a third party plugin. 
The solution is [here](http://elgghacks.com/questions/view/6767/the-problem-of-showing-the-titles-of-the-elements).
 I recommend closing this issue.

**Comment by jdalsem** [comment]
@AbdulazizSobh can you confirm this was the case?
