### ISSUE TITLE
FR : is there any way to filter / add some value to the name

### ISSUE THREAD

**Issue by physcocode** [Elgg/Elgg#13415]
is there any hook / template / filter to add things or filter name of a person site wide ? I was trying to create a verified profile badge but did not find any consistent way to add badge besides name , I did come out with a  tacky way to achieve it here (https://elgg.org/plugins/3081433) but it breaks when name is shown in places like title

**Comment by jdalsem** [comment]
There is not a single way to do this. You could extend the ``ElggUser`` class with a custom class and override the ``getDisplayName()`` function, but that would mean it even shows in emails (where you probably do not want it). So you will need to target the specific views where you would want to show the badge (for example the ``object/elements/imprint/byline`` or the ``resource/profile/view`` views).
