### ISSUE TITLE
Adoption of Santa Clara Principles on transparency and accountability of content moderation and remedies for abuse

### ISSUE THREAD

**Issue by cleverthings** [Elgg/Elgg#13419]
Feature Request: As social media platforms have been recently weaponized for the dissemination of misinformation, I'd love to see the Elgg framework and/or a plugin make it easier to moderate content while automating compliance with the Santa Clara Principles of transparency and content moderation. In addition to the Santa Clara Principles posted at [https://www.santaclaraprinciples.org/](url), there was a recent research paper by Eric Goldman that has several recommendations for many reasonable remedies for content moderation: [https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3810580](url). It seems that if Elgg wants to be a future-proof viable social media platform, that we should develop more tools to make content moderation easier. Let's be proactive, instead of reactive to a growing problem. Thanks!

**Comment by jdalsem** [comment]
I think this research paper has some valid points and based on this report i could also think of places where Elgg could improve. However i also read this paper as a responsibility **for companies** to conform to these principles. As always Elgg is open for Pull Request with actual code improvements. Go to the Elgg community (elgg.org) for discussions and try to mobilize contributors. Elgg also has a plugin ecosphere in which there is always room to develop and share plugins that help in providing more transparency for communities.
