### ISSUE TITLE
I am not receiving the activation message

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13420]
When registering a new member, the activation message does not arrive in the mail
Although I used to use Unvalidatedemailchange but after deactivating it the problem still remains

**Comment by jdalsem** [comment]
There could be multiple reasons:

- mail not being sent
  - check if your server is configured correctly (are you only not receiving on registeration of a new user?)

- mail not being received
  - check if mailaddress is correct
  - check if mail is not blocked by spam rules

This could be a problem in the code, or, more likely in your setup. Please report back here if you have steps to reproduce an issue within the code.

**Comment by AbdulazizSobh** [comment]
i checkd if mailaddress is correct
i checked if mail is not blocked by spam rules
Also this problem appeared only after updating to the new version before that it was working

**Comment by jdalsem** [comment]
What is the version? How did you install? Any other plugins that might interfere?

Please answer all these questions that you see in the issue template. They are important and help us analyze the problem

**Comment by AbdulazizSobh** [comment]
More precisely, the problem appears after registration. It is normal for a message to arrive in the e-mail to activate the account, but it is not sent anywhere in the mail. I checked this, but it appears in the Control Panel of Users: Unvalidated
Even for Resend validation in Users: Unvalidated when using it, the message is not sent either

**Comment by AbdulazizSobh** [comment]
Version 3.3.16
a plugin I use https://justpaste.it/4sqod
The method for updating the method that I follow most often is to delete the files for the old script and replace them with the new script and enter upgred to update the script

**Comment by jdalsem** [comment]
did you download the code from the Elgg website, or from github (via git checkout)

**Comment by AbdulazizSobh** [comment]
Elgg website

**Comment by jdalsem** [comment]
What version did you upgrade from? 3.3.15?

**Comment by AbdulazizSobh** [comment]
I don't remember good but I guess 3.3.14

**Comment by jdalsem** [comment]
I see no related changes between those versions https://github.com/Elgg/Elgg/compare/3.3.14...3.3.16

You will need to investigate it yourselves further before i can be of any more assistance

**Comment by AbdulazizSobh** [comment]
Is there anything specific to check?

**Comment by jdalsem** [comment]
error logs.... try it with a mail address you own... add debug logging in your code... revert to 3.3.14 and verify it works....  do a clean 3.3.16 installation and try again

**Comment by AbdulazizSobh** [comment]
You have tried all the suggested methods and the problem still exists: 
There is nothing in the error logs
I try with a mail address I owned
I tried to return to an old version and then update the script, but the problem exists in the old version and the modern version has not been solved

**Comment by jdalsem** [comment]
this is not helpful... you stated earlier that it was working before upgrading to 3.3.16, but now you tell me that the problem also exists in the old version? Have you ever seen a working email? Revert back to that version and report back again

**Comment by AbdulazizSobh** [comment]
I assure you that I took this step
After making sure, I was working on version 3.3.8 specifically, and I went back to this version and took this step even without activating any add-on

**Comment by jdalsem** [comment]
so to be precise: in which version does it work for you?

**Comment by AbdulazizSobh** [comment]
It was working before I upgrade that's what I remember, but now it doesn't work even on the old version as I tried.

**Comment by jeabakker** [comment]
Do you know which mail method you're using? sendmail (the default) or SMTP?
If you're using sendmail have you tried a simple test to see if the server can mail?
Make a php file (for example `mail.php`) and put in 
```php
<?php
mail('youremail@domain.ext', 'Test subject', 'Test body');
```

If you receive this message then you're one step further in the analysis, if you don't receive anything than the problem isn't related to Elgg.

**Comment by AbdulazizSobh** [comment]
I have added this file to the mail.php URL and I have not received a message

**Comment by AbdulazizSobh** [comment]
Also I have tried to send a message to Horde's message management program on the hostname and it has sent the message successfully

**Comment by AbdulazizSobh** [comment]
Therefore, mail can be sent from the server, but the secret does not send the activation message

**Comment by jeabakker** [comment]
> I have added this file to the mail.php URL and I have not received a message

this means it's a problem of your server and has nothing to do with Elgg. Maybe your hoster applies limitations or something else is wrong, ask your hoster for help.

**Comment by AbdulazizSobh** [comment]
He contacted the guest and told me that the hosting has no problem, and I also tested sending a message via Horde, the program attached to the hosting to control the mail, and I received the message successfully, but elgg does not send the message to react in any way

**Comment by jeabakker** [comment]
the example which I've given you is the basic PHP mail feature https://www.php.net/manual/en/function.mail.php if that doesn't work mail from Elgg will also not work.
