### ISSUE TITLE
Cannot run Elgg 3x with php 8x

### ISSUE THREAD

**Issue by rhisss** [Elgg/Elgg#13428]
Tried with both php 8.0.2 and 8.0.3
Latest Elgg 3.3.16, core and without any other plugins, as is - gives no output.
In the same server setup I have tried Wordpress and Drupal, which are running fine with php8x
I also find that Elgg 4 release is past due date.

**Comment by jdalsem** [comment]
Elgg 3.x isn't compatible with PHP 8.

You'll have to wait until Elgg 4 is released, that has support for PHP 8
