### ISSUE TITLE
Elgg 3: Cached elgg.js and Google Safe Browsing

### ISSUE THREAD

**Issue by gnh1201** [Elgg/Elgg#13441]
Google Safe Browing misdiagnoses elgg.js (cached elgg.js) as having phishing elements. No editing has been made except for the default js.
It's not a malicious or edited code, it's a cached JavaScript file with a default state.
What steps can I take?

**Comment by RiverVanRain** [comment]
And why do you think that it's an Elgg's issue? You should take steps yourself as a webmaster to fix this problem, eg. prevent certain directories in robots.txt from being scanned by Google.
Read the [Google documentation](https://developers.google.com/search/docs/advanced/security/prevent-malware?hl=en)

**Comment by gnh1201** [comment]
This is because Google has clearly identified the elgg.js file as malware. It is not the result of other directories or files.
I know this is a misdiagnosis, but I think it is necessary to track which part of the default elgg.js file is recognized as malware.

**Comment by gnh1201** [comment]
As you said, I think I can add the cache directory as a deny list in the robots.txt file to prevent Google from checking malware.
Thank you for your advice.

**Comment by RiverVanRain** [comment]
We've never had such problems on any site with any version of Elgg since 1.8.x. 
I think you should use Webmaster tools/Search console to solve this issue.

Just added [our robots.txt](https://o.wzm.me/topics/p/v/138772/843), you can try it.

**Comment by jdalsem** [comment]
I have tested multiple Elgg websites with the Google Safe Browsing check (transparancy report) and found no issues on all sites. Please share details of a report and investigate the reason of the error before reporting here again. We use github for things we need to change in Elgg, not as a support forum for your specific site. (You can use the Elgg community for that)
