### ISSUE TITLE
MOD group_tools wrong translation in group_tools/languages/de.php

### ISSUE THREAD

**Issue by itsc-uni-luebeck** [Elgg/Elgg#13483]
There is a typo in the translation of the following code:

'group_tools:notify:transfer:subject' => "Administration dr Gruppe %s wurde Ihnen zugeteilt",

this should be:

'group_tools:notify:transfer:subject' => "Administration d**e**r Gruppe %s wurde Ihnen zugeteilt",

Thanks for the fix

**Comment by jeabakker** [comment]
you should report this issue with the group_tools plugin https://github.com/ColdTrick/group_tools not with the Elgg core team.
