### ISSUE TITLE
Allow content owners to edit/remove comments on their content

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13499]
No idea if this is the right place to say this here. Blog owners should have the ability to delete a comment (for example, an offensive or abusive one in a social site) on the blog post she/he wrote. Currently WP/Drupal and possibly others do have this ability.

_Originally posted by @daniyaree in https://github.com/Elgg/Elgg/issues/4903#issuecomment-846489500_

**Comment by jdalsem** [comment]
I think it applies to all content... but this change is debatable. On wordpress blogs are posted by 'editors'. In Elgg blogs can be added by anyone (regular community members). This means if someone does not like a comment on their own blog they could remove it. That sounds like censorship... how would you like to deal with that?

**Comment by RiverVanRain** [comment]
This ability can be given through the option in the "Site settings". 
By default, this option should be disabled. 
Additionally, we can control it in groups.

**Comment by iionly** [comment]
Can be controlled via plugin (see https://elgg.org/plugins/2642878) if default behaviour is not wanted. Seems unnecessary to add a setting to core.

**Comment by RiverVanRain** [comment]
As always, @iionly makes us happier :)

**Comment by jdalsem** [comment]
If you are happy, i am happy. Going to close this as a plugin exists.
