### ISSUE TITLE
Improve chat

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13498]
Improving the chat by making it synchronized with sending and receiving messages at the same time without the need to update the page and add a mini chat, such as Fri Cat, I know that there is a copy, but it is not related to the conversations on the main site, it means that the conversations will be in the place where they were conducted

**Comment by RiverVanRain** [comment]
Any issue in Elgg? No? 
Why are you creating this here?

**Comment by AbdulazizSobh** [comment]
Is there a specific location?
