### ISSUE TITLE
Add followers to members

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13491]
Adding followers to members mainly to the site this is very good for further interaction, and you can also add a follow button next to the members within the posts and topics that they publish this will be a great feature This addition provides the feature of followers, https://elgg.org/plugins/724666 but it is old I suggest adding it permanently

**Comment by jdalsem** [comment]
The currently implementation of 'Friends' in core is in fact a system of followers and following. Terminology can be changed by the site owner (with the help of translations). What else would you like to have added to the system?

**Comment by AbdulazizSobh** [comment]
I know the friends system, but friends are different from followers and followers. There can be many of them, but friends are some. Friends cannot be changed to followers because friends cannot be dispensed with. Also suggested the follower system and also add the follow button next to the member’s profile picture within topics and posts.

**Comment by RiverVanRain** [comment]
> suggested the follower system and also add the follow button next to the member’s profile picture within topics and posts.

Subscriptions?

The friends system can be easily customized to whatever you want.
Just use hooks and override views.

For translations I recommend [this awesome plugin](https://github.com/ColdTrick/translation_editor)

**Comment by AbdulazizSobh** [comment]
But what I mean is the presence of followers beside them with friends
For example, friends must send an approval request, but followers can follow the member’s activities.

**Comment by jdalsem** [comment]
Ah ok, i see. You want both a friends system AND a followers system present on your site. With the current Friends plugin in Elgg you can only do one of the two. I think your specific case is not something we are going to add to Elgg core. You will need to use plugins like the one you mentioned to do this for you.

If the plugin is too old, reach out to the developer or fund someone to get it updated.
