### ISSUE TITLE
Posting a comment on a long unicode blog post shows Fatal Error at times.

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13546]
Trying the latest Elgg 4.0.0 beta 1 release as is, out-of-the-box with no further change/config/mods or plugins

- A new blog post with a long matter of unicode text (for example a big long story) is made
- Now a comment is added 
- The loading icon goes round and round, and the site message in green "your comment successfully posted" shows up
- But the comment does not show up under the blog-post while the loader icon goes on and on
- Coming back to the activity page, it does show the comment has been added
- Clicking the blog post link from activity page, takes you to the blog post and indeed the comment is there BUT along with Fatal Error Message box and the entire page turned blue/jeopardized [ see picture ]

This happens inconsistently and not always but quite often to be problematic. So you may need to try a few times to reproduce the error. Apparently it _seems_ NOT to happen when the blog post is just one or few lines or not a long / very long unicode matter. Not sure if this same happens with very long text matter in English also.
The **Error log** shows
```
[13-Jun-2021 00:44:31 UTC] [2021-06-13T00:44:31+00:00] ELGG.CRITICAL: Exception at time 1623545071:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'm4lkoec8idr85pj8jpleosl2dr' for key 'PRIMARY' in /home/xxxx/xxxx/elgg4/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:92
Stack trace: (do i need to post here the entire stack trace??)
```

![elgg error 4a](https://user-images.githubusercontent.com/43325988/121792413-088f0380-cc12-11eb-8b11-ef213f61538b.png)

**Comment by jdalsem** [comment]
Closing this as https://github.com/Elgg/Elgg/pull/13563 is merged and i expected the changes in that PR will fix this issue
