### ISSUE TITLE
Elgg4: plugin re-ordering ("To Bottom") fatal error

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13550]
Maybe it happens only on the first attempt when the order of plugins hasn't been changed at all before.

I selected "Bottom" from the plugin's entity menu (in this case the "Login as") plugin to move it to the end of the plugin list. The plugin was disabled at that time.

The error I got was
```

An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'tj29njlc0vcrg7045nkt2ic4dr' for key 'PRIMARY'

Log at time 2021-06-13T10:43:26+02:00 may have more data.

INSERT INTO elgg_users_sessions (session, data, ts) VALUES(:qb1, :qb2, :qb3)

array (
  'qb1' => 'tj29njlc0vcrg7045nkt2ic4dr',
  'qb2' => '_sf2_attributes|a:3:{s:14:"__elgg_session";s:22:"DUx87Szsf-yHdwrg0PdKTu";s:10:"_elgg_msgs";a:0:{}s:4:"guid";i:40;}_sf2_meta|a:3:{s:1:"u";i:1623573805;s:1:"c";i:1623573297;s:1:"l";s:1:"0";}',
  'qb3' => 1623573805,
)
```

On further attempts to use the up/down or top/bottom entity menu entries no further errors occured.

**Comment by jeabakker** [comment]
The database exception has been fixed in #13563 the exception was unrelated the this specific action and could occur on multiple cases.
