### ISSUE TITLE
Elgg4: verification email/friending email do not contain full page url/activation token

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13553]
The url in the email is just the site url. Activation token is missing.

Edit: seems not only the activation email. The same with friending email notifications. The url is also only the site url in this case without leading to the page where I could accept the friend request.

**Comment by jeabakker** [comment]
this is probably a problem in the translations.

We removed the salutation and sign-off from all the language keys (in English) and the translations still have the placeholders, then `elgg_echo()` provides too few arguments and `vsprintf` fails, thus empty string

We're looking into the possibility for us to fix this

**Comment by jeabakker** [comment]
fixed in #13574
