### ISSUE TITLE
Elgg4: no links displayed in (html) email when mail client displays it in plaintext

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13552]
E.g. the verification mail doesn't show the activation link if the mail program does not display the email in html. There's also no indication that you don't see the complete content if you don't display the email in html.

By default, the Elgg 4 site sends mails in html now. The admin won't realize the problem with the incomplete display of emails immediately though.

I don't know what could be done:
* modify the html email content to display urls also in non-html mode?
* or some hints both in the admin area along the html email setting and within the email body that you would have to display the email in html mode to see the complete content.

Personally speaking, I wouldn't like it if I'm forced to display an email in html mode to be able to see all relevant content. After all it's definitely not reducing the possible risk of some malicious things being done if you need to let your emails be displayed in html.

**Comment by jeabakker** [comment]
The HTML content is based on the same text as the plain text content. Differences are with plain text we do a `strip_tags`  and for HTML we add all the additional HTML content.

However for example if you use `notify_user()` whatever you supply as `subject` and `message` should be present in both plain text and HTML.

I think the problem with the verification mail was an incorrect translation (which we fixed), do you have more examples? Or is the issue still present with the current 4.0 branch?

**Comment by iionly** [comment]
At least for the pending friend request confirmation I can confirm that the mismatch of number of placeholders in the translation caused the problem. Now I also understood that the site url link at the bottom is displayed as intended and not the link meant to bring me to the pending friends page. So, I think it's likely only a translation issue.

**Comment by jdalsem** [comment]
with translations fixed, this should not be an issue anymore
