### ISSUE TITLE
docs: intro

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#13566]
in intro/install/xampp:
- line 44: `Uncomment this line in ``C:\xampp\php\php.ini``::` double colon

in intro/install/easyphp:
- line 22:  `and uncomment this line::` double colon
- line 30: `and uncomment this line::` double colon

in intro/install/virtual:
- line 13: `To be::` double colon

**Comment by Facyla** [comment]
There are a few more in the same file, i did not want to send a comment for every translated string
