### ISSUE TITLE
Elgg4: detailed user and group notification settings not showing input field labels correctly

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13576]
See for example

![User_Notification_Settings](https://user-images.githubusercontent.com/1773681/122822767-cd11ca80-d2de-11eb-9f6c-2d04efcc6173.png)

As the site and logged-in user language are both English I don't think it's a translation issue.

**Comment by jeabakker** [comment]
eighter #13461 or #13504 broke this
cc: @jdalsem
