### ISSUE TITLE
Elgg 3.3 (Elgg4?): get_current_language() (or rather detectLanguage() function) seems buggy

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13582]
Problem probably started with Elgg 3.1 that deprecated get_language() to be replaced by get_current_language().

Use case: Tidypics HTML5 uploader

I use get_current_language() to retrieve the logged-in user's language to display the text output of the HTML5 uploader in the preferred language. This works fine up to Elgg 3 but no longer works as expected on Elgg 3.3 (can't test Elgg 3.1-3.2 but I expect the problem started with get_current_language() on Elgg 3.1).

What goes wrong?

There's something going wrong with resolving the currently selected user language while also taking into account the language saved/retrieved from browser detection and/or the cookies.

For this use case logged-out language handling is not relevant, so I haven't tested this any further.

For logged-in users I would think the language returned by get_current_language() should be the user language selected in the user settings in the first place. And changing the user language setting should immediately return the newly set language correctly when using get_current_language().

But it failed to work here:

* when not allowing the cookie to be saved (e.g. prevention by browser settings or an browser addon) the language returned by get_current_language() seems wrong (not necessarily equal the user language and/or site language set),

* even allowing the cookie to be saved the change of user language in the user settings is not correctly taken into account by get_current_language() either. The rest of the site would change to the new language but the text output of the HTML5 uploader still shows up in the formerly selected language on Elgg 3.3 (while correctly changing the language on Elgg 3.0)

**Comment by jeabakker** [comment]
As far as i can see some of the logic was changed.

Before it was
- URL param
- logged in user language
- site language
- English

Now it's
- URL param
- if no user logged in store that language in a cookie (cookie lifetime is just this session)
- check for language cookie
- logged in user language
- browser language
- site language
- English

This means if a user (not yet logged in) visits the site with an URL language param the site will show in that language. If the user then logs in the site will remain in that language even if the user language is different.

**Comment by iionly** [comment]
Is language cookie really for the session only? Even then it's a problem as the cookie overrides the user language and changing the user language seems not immediately taken into account (cookie not updated?).

Maybe the user language should be the top priority once set and come before cookie and browser detection. Only for the very first visit when creating a new account it might make sense to rely on the browser detection and cookie and the set the user language based on the detected language. What else would be the purpose of the cookie for existing users?

**Comment by jeabakker** [comment]
I've tried the following:
- go to my site with the url param `?hl=de` the site shows up in German (default site setting is English)
- A language cookie was created with German as language (session bound)
- I created an account and logged in
- The account was created with the German language as preference
- I changed the language of the account to French, saved and the site shows in French

Different test
- go to my site with the url param `?hl=de` the site shows up in German (default site setting is English)
- A language cookie was created with German as language (session bound)
- I log in with an existing account (with English as preference) the site shows English

During the system boot when the session is loaded, the language of the user is set as the language to use:
https://github.com/Elgg/Elgg/blob/221b759de6cbe0098a9dfe7e696691059b7cbc19/engine/lib/sessions.php#L374-L409

with the relevant part in `ElggSession`
https://github.com/Elgg/Elgg/blob/221b759de6cbe0098a9dfe7e696691059b7cbc19/engine/classes/ElggSession.php#L208-L216

Which goes to the `Translator`
https://github.com/Elgg/Elgg/blob/221b759de6cbe0098a9dfe7e696691059b7cbc19/engine/classes/Elgg/I18n/Translator.php#L229-L231

this way `getCurrentLanguage()` works with the user language
https://github.com/Elgg/Elgg/blob/221b759de6cbe0098a9dfe7e696691059b7cbc19/engine/classes/Elgg/I18n/Translator.php#L210-L220

Where do you think something is wrong? And do you have steps to reproduce?

**Comment by iionly** [comment]
I did describe the use case in my initial posting. It's about making direct use of the function get_current_language() (replacement of get_language()).

It's within Tidypics that I call it for loading the matching plupload (HTML5 uploader) language file depending on logged-in user language.

Here's where I call get_current_language()
https://github.com/iionly/tidypics/blob/729c20682047f018eceb186c3e5f1fc1541e4514/lib/tidypics.php#L292

and the only call of tidypics_get_plugload_language() is at
https://github.com/iionly/tidypics/blob/729c20682047f018eceb186c3e5f1fc1541e4514/classes/TidypicsBootstrap.php#L48-L52

On Elgg 3.3 changing the user language results in the intended immediate change of the language the site is displayed but with the exception of the text output of the plupload uploader. That's different to how it was on Elgg 3.0 with the former get_language() function where also the language used by the uploader changed immediately.

The second thing seems to happen if you don't allow the cookie to be saved (via browser addon). And if you don't fiddle with the user language setting after account creation and login either. Steps here were:
* site language English
* preferred website language set in browser German
* site is displayed in German (before and also after account creation)
* but now the text output of the HTML5 uploader is English (site language)
* up until this point the language cookie is never created.

**Comment by jeabakker** [comment]
I looked into this issue. The problem you encounter is that the requireJS configuration is served from a simplecache url. Thus it's cached for ALL users.
The define you do https://github.com/iionly/tidypics/blob/729c20682047f018eceb186c3e5f1fc1541e4514/classes/TidypicsBootstrap.php#L48-L52 is therefor cached with the information of the first users which requests the site.

You need to find a different way to load the languages. If you `var_dump()` `$plupload_language` it will always show the correct language for the current user. At least it did in my tests.

**Comment by iionly** [comment]
I now use elgg_register_external_file / elgg_load_external_file instead. It shows the correct language now. I also use elgg_get_simplecache_url but I'm not sure it's of much use.
