### ISSUE TITLE
Elgg3: installation fails using non-default MySQL and/or HTTP port

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13590]
I'm just reporting.

See https://elgg.org/discussion/view/3108267/cannot-install-elgg-3319-on-xampp-7420

Not sure if it's an issue with HTTP port number or MySQL port number or both. Or it might be happening only on XAMPP.

**Comment by jeabakker** [comment]
found it, it had to do with the database configuration for the Phinx migrations (schema updates) this also handles the installation
