### ISSUE TITLE
Elgg 4.0 - Beta 2 cannot install

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13602]
All fresh and default out-of-the-box installs from downloadable zip file, using php8
Elgg 4 beta 1 gives the installation screen and can be installed - no problem with php7x or php8
Elgg 4 beta 2 : Fatal error in exception handler. Check log for Exception at time 1625914796
And installation cannot be done.

**Comment by jdalsem** [comment]
any more information in the log?

**Comment by jeabakker** [comment]
there was an error in the ZIP file. If you check there is a file `elgg-config/settings.php` remove that file and the installation should work.
All zips have been updated.
