### ISSUE TITLE
Elgg 4.0.0-beta.3 : Support Question on  Files

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13638]
Elgg 4.0.0-beta.3 : Files

As per as I can remember FILES used to be part of the default installation of Elgg, that is, it was part of the already activated integrated plugins. So that on installation, site user could add Blog | Files | Group | Bookmarks

- fresh install of Elgg 4.0.0-beta.3 : Files not seen
- activated it from plugins
- cannot see "Settings" icon/option by side of Files or in the plugin settings in Admin right Side Bar
- how do we specify what TYPE of file users can upload as all files types MAY NOT BE SAFE and hamper site security
- does Elgg has internal settings to deny exe files or harmful files uploaded via FILES *
- how to add / alter permissible File size via Plugins > File > Settings *

Thanks.

Relevant community discussions,"Learn" pages and projects:

- http://learn.elgg.org/en/stable/plugins/file.html
- https://elgg.org/plugins/1095821/releases/lakisprei#elgg-object-1980720
- https://elgg.org/plugins/1095821 [no version for Elgg3x, Elgg4x]

**Comment by jeabakker** [comment]
> * fresh install of Elgg 4.0.0-beta.3 : Files not seen

this is a bug, will be fixed

> * cannot see "Settings" icon/option by side of Files or in the plugin settings in Admin right Side Bar
> * how do we specify what TYPE of file users can upload as all files types MAY NOT BE SAFE and hamper site security
> * does Elgg has internal settings to deny exe files or harmful files uploaded via FILES *
> * how to add / alter permissible File size via Plugins > File > Settings *

The File plugin doesn't have any settings. 
So there are no limitations of what users can upload. 
Since all files are stored in the dataroot of the Elgg installation (which shouldn't be accessible from outside the Elgg application) and files are not stored with execute rights risks are limited.

**Comment by daniyaree** [comment]
"Since all files are stored in the dataroot of the Elgg installation (which shouldn't be accessible from outside the Elgg application) and files are not stored with execute rights risks are limited."

Thanks. But virus containing files even outside Elgg can cause red alert on the webhost server to shut down the site temporarily even though my Elgg site may be running smoothly. This is actually a critical security issue and File should be installable only when the Admin has chosen the file types.

**Comment by jeabakker** [comment]
> But virus containing files even outside Elgg can cause red alert on the webhost server to shut down the site temporarily even though my Elgg site may be running smoothly.

Currently we don't see how this could be prevented from within Elgg. Even if you limit uploading files to certain extensions (like only `.jpg`) a user could simply rename ``virus.exe` to `virus.jpg` and uploading would continue.

The only way to prevent this would be to implement a virus scanner in the application is some form. The File plugin is meant as a generic plugin. If you need additional security it's always possible to implement this through plugins.
