### ISSUE TITLE
 Elgg 4.0.0-beta.3 : Cannot add or save Bookmark

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13637]
Testing with FRESH default install of Elgg 4.0.0-beta.3, and no other plugins.
Cannot add or save Bookmark.

Steps to reproduce
- go to add bookmark page as an user/site-member
- fill in the Title field
- fill in the Address of the bookmark field
- Hit "Save"
- Error message : "Your bookmark could not be saved. Make sure you've entered a title and address and then try again."
- Bookmark is NOT saved

**Comment by jeabakker** [comment]
I'm unable to reproduce this issue could you give a bit more information
- which browser
- what did you type in the Title field
- what did you type in the Address field

When this error occurred you should be returned the the add/edit form with the fields filled in with what you entered, is this correct and does it contain what you typed?

**Comment by daniyaree** [comment]
@jeabakker 

Are you using php 8x?

- Browser for me is latest stable FF and Chrome (Windows Desktop PC) and Chrome in Android Smart phone
- Title field is any plain text and address field is any proper http or https or http www address - please see the attached screenshot
- The same page/form is returned with an error message and yes, also with the fields filled in with what I entered - see the attached screenshot
 Thanks

![3](https://user-images.githubusercontent.com/43325988/130688446-54a35c48-839f-4565-96fa-84c8146597fe.png)

**Comment by jeabakker** [comment]
I wasn't using PHP 8, I asked @jdalsem to test on PHP 8 and the problem occurred. 

We fixed it, thanks
