### ISSUE TITLE
Issue with 'transport', 'system:email' plugin hook

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#13669]
References

1. https://elgg.org/discussion/view/3091302/how-to-get-email-parameters-using-the-transport-systememail-plugin-hook
2. https://elgg.org/discussion/view/3077430/configuring-smtp-settings
3. https://elgg.org/discussion/view/3090898/zend-mail

Its almost 1 year, I am struggling with configuring the mail service of elgg in AWS SES system. Finally I was using phpmailer for sending the emails by hooking into 'transport', 'system:email' plugin hook which result in so many inconsistencies.

Following is the simplified version of my code. 
`elgg_register_plugin_hook_handler('transport', 'system:email', 'my_phpmailer_hook');

function my_phpmailer_hook(\Elgg\Hook $hook) {
    // assume someone else already sent the message
    if ($hook->getValue() === true) {
        return;
    }
    $email = $hook->getParam('email');
    if ($email instanceof \Elgg\Email) {
        $recipient = $email->getRecipient();
        elgg_log($recipient->email, "ERROR");
    }	
}`

But running this hook returning me the following error 
`Error: Cannot access protected property Elgg\Email\Address::$email`

Is there a way, I can catch the e-mail before its been thrown out of the system and reroute it?

**Comment by RiverVanRain** [comment]
Your code is wrong.
You must use this hook to configure `Zend\Mail\Transport\TransportInterface`.
`Zend\Mail\Transport\Sendmail` is used by default.

**Comment by sarathsince85** [comment]
@RiverVanRain : Please understand that I have gone through each and every documentation available regarding this topic before posting the question here. If you have a working solution, please share it which will be helpful rather than giving me the same links which you have already shared through the [community discussion channel](https://elgg.org/discussion/view/3091302/how-to-get-email-parameters-using-the-transport-systememail-plugin-hook). 

### According to the documentation

1. **prepare, system:email** - This hook allows you to alter an instance of \Elgg\Email before it is passed to the email transport. This hook can be used to alter the sender, recipient, subject, body, and/or headers of the email.
2. **validate, system:email** - This hook allows you to suppress or whitelist outgoing emails, e.g. when the site is in a development mode. 
3. **transport, system:email** - delivering emails via a third-party proxy service such as SendGrid or Mailgun.

What I am looking for is a hook which will allow me to catch the final email (just before the final message is thrown out of the server / handed over to Zend). According to the documentation, transport, system:email is the hook to be listened. But unfortunately its not working as expected.

**Comment by RiverVanRain** [comment]
If you read the documentation and Elgg's source code carefully, you would understand that `transport, system:email` hook is not for what you want to do.

Use `prepare, system:email` instead.
Check out the Elgg's source code for examples.

**Comment by RiverVanRain** [comment]
And of course it's not an Elgg issue. I think that you should have continued the discussion in the community.

**Comment by RiverVanRain** [comment]
Also, you can get an email in your code using this:
`$recipient_email = $email->getTo()->getEmail();`

[Reference](http://reference.elgg.org/classElgg_1_1Email.html)

**Comment by sarathsince85** [comment]
I am sorry, that I couldn't follow what you are saying. 

From my understanding, if I intercept at the "[prepare](https://github.com/Elgg/Elgg/blob/3.3/engine/classes/Elgg/EmailService.php#L66)", "system:email" level, then I will be missing the results of "[validate](https://github.com/Elgg/Elgg/blob/3.3/engine/classes/Elgg/EmailService.php#L77)" & "[zend:message](https://github.com/Elgg/Elgg/blob/3.3/engine/classes/Elgg/EmailService.php#L147)" hooks. Otherwise I have to duplicate the whole code again in my plugin. 

So what I am looking for is to intercept at the end, once the whole mail is composed and is ready for going out of the system.

**Comment by RiverVanRain** [comment]
`transport, system:email` hook will include the email you [previously prepared](https://github.com/Elgg/Elgg/blob/3.3/engine/tests/phpunit/unit/Elgg/EmailServiceUnitTest.php#L75). It's only needed for configuring outgoing mail transport (by default, `\Zend\Mail\Transport\Sendmail()`).

> So what I am looking for is to intercept at the end, once the whole mail is composed and is ready for going out of the system.

try:
`$recipient_email = $email->getTo()->getEmail();`

**Comment by jdalsem** [comment]
Trying to summarize this discussion.

**SMTP Delivery**
It should be possible to deliver to SES using SMTP configuration in your `settings.php`. This is the best option. If this does not work for you, your energy should focus on investigating why this is the case (as you mentioned you could get it working with phpmailer) Below an example of how we deliver to a Office365 SMTP server. 

```php
//$CONFIG->emailer_smtp_settings = array(
//	'name'              => 'localhost.localdomain',
//	'host'              => '127.0.0.1',
//	'port'              => 25,
//	'connection_class'  => 'login',
//	'connection_config' => [
//		'username' => 'user',
//		'password' => 'pass',
//		'ssl'      => '', // OPTIONAL (tls or ssl)
//		'port'     => '', // OPTIONAL (Non-SSL default 25, SSL default 465, TLS default 587)
//		'use_complete_quit' => '', // OPTIONAL
//	],
//);


$CONFIG->emailer_smtp_settings = array(
	'name'              => 'your_connection_name',
	'host'              => 'yourdomain.mail.protection.outlook.com',
	'port'		    => 25,
	'connection_class'  => 'smtp',
	'connection_time_limit' => 30,
	'connection_config' => [
		'ssl'      => 'tls', // OPTIONAL (tls or ssl)
	],
);
```

**Use hooks to control delivery**
The correct hook for taking over delivery of mail is `'transport', 'system:email'`. In this hook you will need to prepare the emailmessage yourselves.

**Inject your own service provider**
This is not recommended, but Elgg allows you to take control of the mailer service. Use this only as a last resort. You can register your own mailer class (as long as it is an instance of `Laminas\Mail\Transport\TransportInterface`) by registering your own service:
```php
$custom_mailer = new YourTransportMailer();
_elgg_services()->set('mailer', $custom_mailer);
```

**Comment by sarathsince85** [comment]
@jdalsem : thanks for the clarification. We have tried all permutations and combinations for the smtp setting for AES. But we couldn't fix the issues. Will try again.

Cant we introduce a new hook, with which the final prepared email can be [caught](https://github.com/Elgg/Elgg/blob/3.3/engine/classes/Elgg/EmailService.php#L156) before it is thrown out of system? Using a custom mailer may achieve this, but as you mentioned it may complicate things more.

@RiverVanRain : Thanks a lot for your guidance. The following code worked.
`$recipient_email = $email->getTo()->getEmail();`
 Cheers 👍
