### ISSUE TITLE
Elgg 4.1:  let user Pick a Group while adding a discussion topic

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13678]
In user> Discussion topics > Add discussion topic
allow an user (site member) to choose a group (if he is already a member of various groups) from a drop-down list **just as in elgg dot org [Pick a group]**- if under "Plugin Settings: Discussions" Global discussions is enabled she or he should be able to post a discussion topic as an open(global) topic OR select from a drop-down list of her/his Groups.

If Global discussion is not enabled, still "Add discussion topic" button can be shown as a logical UI/UX and on clicking this - a message is displayed asking the user to choose a group first.

**Comment by jdalsem** [comment]
Related to https://github.com/Elgg/Elgg/issues/5764
