### ISSUE TITLE
Elgg 4.0:  Turning on the core Site-Notification Plugin makes the Top Bar oddly disproportionate.

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13696]
Turning on the core Site-Notification Plugin makes the Top Bar oddly disproportionate. In mobile screen and in smaller size desktop screen this then takes up a lot of screen real estate. I am using latest Elgg 4 (fresh install, no other plugins) & php 8x and latest FF & Chrome. Deactivating the Site Notification plugin again makes the Top Bar normal.

![top](https://user-images.githubusercontent.com/43325988/135004282-8fc276fc-42da-4916-b7aa-3b619414f8b0.png)

**Comment by jdalsem** [comment]
This is not a bug... there is no room for all the menuitems, searchbar, site name and icons to fit. That is why it wraps to a new line.. to make space. It will fit back on a single line if, for example, you make your site name smaller (less characters).
