### ISSUE TITLE
[Feature]: Whoops for error reporting

### ISSUE THREAD

**Issue by rjcalifornia** [Elgg/Elgg#13918]
### Describe the feature

I think elgg can take advantage of reporting libraries, such as Whoops:
https://github.com/filp/whoops

It is fast, simple, and customizable. 

### Is your feature request related to a problem?

I'm always frustrated when you just see the elgg screen of death.

### Describe alternatives you've considered

The developer tools plugin is a hit or miss. It would be better to use a more mature library for error management.

**Comment by jdalsem** [comment]
I think this feature is too much developer oriented. The Exception pages of Elgg could surely get some more love, but we need to improve it merely for the regular end user, not for developers. If you need more details for debuging and want something like whoops, you should be able to create a plugin to do that.
