### ISSUE TITLE
[Bug]: setting validation status during register might not work

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#13920]
### Elgg version

4.x

### Source of your Elgg installation

GIT clone

### Describe the bug

As there is no logged in user setting metadata will not work. Still need to confirm this.
https://github.com/Elgg/Elgg/blob/8c1063d09d69e495b2171d27578e0379d422ee42/actions/register.php#L64-L67

### Steps to reproduce

1. with no validation plugins/settings enabled register a user
2. check is the user has a validation status (entity explorer)

### Expected behaviour

the user should have an validation status of `true`

**Comment by jeabakker** [comment]
> I can't reproduce it.
> The registered user has just been successfully validated.

that's a good thing ;)

**Comment by jdalsem** [comment]
This is not a problem. With the proposed steps there is no issue. The validation metadata is present.
