### ISSUE TITLE
[Bug]: Front Page Demo does not display the activity/river module

### ISSUE THREAD

**Issue by laurentiu86stan** [Elgg/Elgg#13967]
### Elgg version

4.1.5

### Source of your Elgg installation

Elgg.org website

### Describe the bug

The Front Page Demo does not display the river module, it's not even present in the code of content.php. Or am I missing something?!

### Steps to reproduce

1. Fresh Elgg install;
2. Front Page Demo plugin is active by default;
3. The river module setting is set to on;
4. The river module does not appear;
...

### PHP version

7.4

**Comment by jdalsem** [comment]
thanks for reporting... it will be fix in the next patch
