### ISSUE TITLE
[Feature]: add 'stale' or 'inactive' users filter for admin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13987]
### Describe the feature

 - [x] add a filter/tab to list users that have been stale / inactive for a certain periode (maybe configurable)
 - [ ] add a cron job to remove inactive users

### Is your feature request related to a problem?

Make sure content makes more sense... inactive users might have no value on the site. Same logic could also be use for legal purposes

### Additional context

The Elgg community has a separate plugin to do this https://github.com/brettp/stale_users

**Comment by iionly** [comment]
Maybe it would then be helpful/necessary to also have a kind of "protected" status an admin can assign to user accounts to except them from deletion of "inactive" users. Or to exclude accounts that have posted some or any kind of content from deletion by a cronjob. There might be some accounts that have been very active in the past but are currently not active anymore. You probably won't get them deleted by some automatic process only to find out later that all their content got removed, too, or they might return at a later time only to find out about that by themselves.

**Comment by jeabakker** [comment]
We're not going to add a CRON based auto cleanup of inactive users. This is way to risky as @iionly already stated.

If cleanup of inactive users is needed on your community you know what the criteria are that define an inactive user and can create a cleanup job for those users

**Comment by jdalsem** [comment]
Partially fixed in #14085. CRON job will not be added.
