### ISSUE TITLE
[Bug]: Bring back the 'creating', 'river' plugin hook, please!

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13997]
### Elgg version

4

### Describe the bug

Before Elgg 4 there was the 'creating', 'river' plugin hook allowing altering the river entry attributes on creation of a river item. I used it in Tidypics to replace the generic comments view with specific views depending on comments made on images or albums. That seems no longer possible on Elgg 4 at all as the 'create:before', 'river' hook only allows to stop the creation of the entry as such but has no way to return the modified array.

### Expected behaviour

I really need this hook back. Elgg 4.0, 4.1 and probably 4.2 are probably lost for use of Tidypics but if there's any chance at all I would like to see the removed plugin hook added again. It's sooo tyring to have to rewrite the plugins for every major new Elgg version unnecessarily.

**Comment by RiverVanRain** [comment]
@iionly Good catch!

I didn't pay attention to it but now I confirm that it's true.
We also use this hook for some plugins.
And this hook is very useful.

**Comment by iionly** [comment]
The only less-than-ideal solution currently possible seems to be using the 'create:after', 'river' event and then updating the database directly with a Querybuilder query. The "wrong" database entry has then already been created though, so it could happen that something else is done before the river entry can be corrected.

**Comment by jeabakker** [comment]
I tried to change the view in the 'create:before' event handler on the provided river item and that seams to work.

something like this
```php
elgg_register_event_handler('create:before', 'river', function(\ElggEvent $event) {
   /* @var $river \ElggRiverItem */
   $river = $event->getObject();
   $river->view = 'my view';
});
```
Have you tried this? Could that work for you (as it does exactly the same as the hook did)?

**Comment by iionly** [comment]
Thanks. Works today. I don't know what went wrong when testing the before event yesterday. I only had opened the issue after I thought it wouldn't work this way.

Yes. The before event can indeed replace the former hook then!
