### ISSUE TITLE
[Bug]: admin section does not appear in the user hover menu

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14008]
### Elgg version

4.2

### Source of your Elgg installation

Elgg.org website

### Describe the bug

When you click on the user hover menu, the 'admin' section is missing. 

### Steps to reproduce

1. Log in as an administartor
2. Click on any user's avatar to display the user hover menu

### PHP version

7.4

### PHP error log

```text
Menu item toggle_admin has no item contents view set
```

**Comment by jdalsem** [comment]
fixed it... thanks for reporting
