### ISSUE TITLE
[Bug]: BC promise within Elgg 4.x broken

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#14028]
### Elgg version

4.2

### Source of your Elgg installation

Elgg.org website

### Describe the bug

I made a release of Tidypics for Elgg 4.0 and expected it to work also on Elgg 4.1 / 4.2 (apart from deprecation warnings). I can't test on Elgg 4.1 but it definitely does not work on Elgg 4.2.

Jquery-UI seems to work totally different (also on different location, different version and themes missing) now expecting some jquery-patch.js to be included for jquery-ui/core but it doesn't work to get the dependency resolved with AMD. So, TOTALLY BROKEN!

I tried to get it working by including the old jquery-ui version directly in Tidypics' vendors folder. At first, it seemed to work and I got the HTML5 uploader working again. But now it seems the new jquery version included in Elgg 4.2 is not backward compatible with the version packed in Elgg 4.0. So, again: STUCK!

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

Within an Elgg major release any bugfix or minor release should not break backward compatibility.

**Comment by iionly** [comment]
I already had to deal with the changes necessary to upgrade Tidypics from 3.x to 4.0. I had managed in the end partly due to trial and error due to missing documentation on the HTML5 uploader side about which jquery-ui modules are needed.

But with Elgg 4.2 the jquery-ui themes are missing apart from the basic theme and the change of path, so it did no longer work to rely on Elgg core smoothness theme like done here
https://github.com/iionly/tidypics/blob/4562b8fe0c10837530d95dacf9f2ec72e9491365/elgg-plugin.php#L440 

But the real problem was the the module jquery-ui/core seemed to require the new module jquery-ui/jquery-patch so
define(['jquery', 'elgg', 'elgg/Ajax', 'jquery-ui/core', 'jquery-ui/widget', 'jquery-ui/widgets/button', 'jquery-ui/widgets/progressbar', 'jquery-ui/widgets/sortable', 'jquery.plupload-tp', 'jquery.plupload.ui-tp'], function($, elgg, Ajax) {

was no longer sufficient. I haven't managed to get it working with jquery-ui version 1.13 at all. How would you fix a AMD module dependency issue without fixing it in the module code directly?

The other problem I had struggled with was in fixing the deprecated usage of elgg.security.token. Before it worked with
```
var data = elgg.security.token;
```
but 
```
var data = security.addToken;
```
apparently does not work as I thought. It took a while due to lack of error messages before I understood that the problem is not within the uploader code somewhere but instead
```
var data;
data = security.addToken(data);
```
works.

**Comment by jdalsem** [comment]
> I already had to deal with the changes necessary to upgrade Tidypics from 3.x to 4.0. I had managed in the end partly due to trial and error due to missing documentation on the HTML5 uploader side about which jquery-ui modules are needed.

I think you had a hard time with this as you kept using a 'old' js library (plupload) for uploading the images. Newer versions of plupload are available and other js uploaders are present that probably work better with AMD and newer jQuery and jQueryUI versions.

> But with Elgg 4.2 the jquery-ui themes are missing apart from the basic theme and the change of path, so it did no longer work to rely on Elgg core smoothness theme like done here
> https://github.com/iionly/tidypics/blob/4562b8fe0c10837530d95dacf9f2ec72e9491365/elgg-plugin.php#L440

The themes provided by the components-jqueryui dependency were never exposed (via views) in Elgg but only the UI js. Besides that i do not believe that all third party code is part of our BC policy. This might not be explicitely mentioned in the docs, but i feel i can see that here.

A relatively simple solution for your plugin is to include the themes in your own plugin. I tried to search for a package with only the jquery-ui-themes for 1.13.x but did not find any. You can download the jquery themes for 1.13 here: https://jqueryui.com/download/all/. Another alternative is to switch to the default jquery-ui-theme as that one is provided by the Elgg core jquery-ui dependency.


> But the real problem was the the module jquery-ui/core seemed to require the new module jquery-ui/jquery-patch so define(['jquery', 'elgg', 'elgg/Ajax', 'jquery-ui/core', 'jquery-ui/widget', 'jquery-ui/widgets/button', 'jquery-ui/widgets/progressbar', 'jquery-ui/widgets/sortable', 'jquery.plupload-tp', 'jquery.plupload.ui-tp'], function($, elgg, Ajax) {
> 
> was no longer sufficient. I haven't managed to get it working with jquery-ui version 1.13 at all. How would you fix a AMD module dependency issue without fixing it in the module code directly?

This indicates that your js requires some older jquery code. The patch is only needed if you use 'old' jquery functions that are no longer part of the versions of jquery-ui and jquery that are bundled in Elgg 4.0. Would it not solve your problem if you included the `jquery-ui/jquery-patch` dependency in your module define?

> The other problem I had struggled with was in fixing the deprecated usage of elgg.security.token

Luckily you figured it out yourself, but you mixed up how to migrate this. `elgg.security.token` is a variable (holding the token data) and `security.addToken()` is a function to add a token to existing (form)data. It was probably never a good idea to use `elgg.security.token` directly but to use `elgg.security.addToken()`. Your currently solution is the correct one.
