### ISSUE TITLE
[Feature]: Move admin menu to topbar

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#14045]
### Describe the feature

Move the admin menu sections to the site topbar

![image](https://user-images.githubusercontent.com/861833/173610937-a96d2801-578d-4eff-a816-c8c977451306.png)

### Is your feature request related to a problem?

1. The admin menu items drop to the bottom of the page (not part of the hamburger on mobile)
2. The menu can be very long so you need to scroll a lot to access your menu item

**Comment by rjcalifornia** [comment]
Or integrate a better administration dashboard design?

**Comment by jdalsem** [comment]
> Or integrate a better administration dashboard design?

Any ideas on this @rjcalifornia

**Comment by rjcalifornia** [comment]
@jdalsem I strongly suggest to consider replacing completely the current Administration page, and use the Gentelella Admin Template:

https://github.com/ColorlibHQ/gentelella

It has been integrated in several frameworks. I've even created a theme for elgg 2.x using Gentelella.
