### ISSUE TITLE
cli command logging should respect 'quiet' flag

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#14046]
should `$cli_command->notice()` for example reach the cli screen output if command is started with `quiet` flag

also consider the verbose flag...

**Comment by jeabakker** [comment]
The ``$cli_command->notice()`` ``$cli_command->error()`` and ``$cli_command->write()`` respect the ``quiet`` flag
The ``$cli_command->getLogger()`` respects the verbosity level
