### ISSUE TITLE
There is no deprecated function in the documentation

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14113]
`_groups_get_group_acl` is no longer used in the Groups plugin.

`$group->getOwnedAccessCollection('group_acl')` is used instead. 

Unfortunately, I don't know which Docs section this belongs to. Otherwise, I would open PR.

**Comment by jdalsem** [comment]
This function was marked as @ internal (also starting with an underscore is intended to be internal). Internal functions are not documented in the upgrade notes.
