### ISSUE TITLE
Should we use vanilla/htmlawed ?

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14131]
### Describe the feature

htmlawed in this library is rarely updated although a new version [has already been released](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/index.php).

In addition, htmlawed is [also available](http://www.bioinformatics.org/phplabware/sourceer/sourceer.php?&Sfs=composer.json&Sl=.%2Finternal_utilities%2FhtmLawed) for use through composer.

### Is your feature request related to a problem?

I'm always frustrated when [...]

**Comment by jeabakker** [comment]
> htmlawed in this library is rarely updated although a new version [has already been released](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/index.php).

vanilla/htmlawed is up to date until 1.2.5. 1.2.6 was only released recently. So not that far behind.

> In addition, htmlawed is [also available](http://www.bioinformatics.org/phplabware/sourceer/sourceer.php?&Sfs=composer.json&Sl=.%2Finternal_utilities%2FhtmLawed) for use through composer.

yes it has a composer file, but where can i get it from on packagist? Or even a CVS? 
I found https://packagist.org/packages/htmlawed/htmlawed but that also is just a wrapper project like vanilla/htmlawed

If there is a way to get the original htmlawed project I'm all for it, but i can't find it yet

**Comment by RiverVanRain** [comment]
Ok. I'll bump a vendor then ;)
