### ISSUE TITLE
[Bug]: installation error 4.3.1 version 

### ISSUE THREAD

**Issue by erolonlinee** [Elgg/Elgg#14142]
### Elgg version

4.3.1

### Source of your Elgg installation

Composer install

### Describe the bug

I installed version 3.3.23 without any problems, but I encountered a problem while installing version 4.3.1.

> `Warning: include_once(C:\wamp64\www/vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp64\www\index.php on line 3

`

> ` Warning: include_once(): Failed opening 'C:\wamp64\www/vendor/autoload.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp64\www\index.php on line `3

### Steps to reproduce

1.
2.
3.
...

### PHP version

7.4.26

**Comment by jdalsem** [comment]
the autoload file is generated by composer... maybe you need to try and run composer install again so the file will be generated again. 

Can you verify the file exists? Do you use the latest version of composer (v2)?

**Comment by erolonlinee** [comment]
I didn't install composer, I downloaded the zip file, I extracted it to the location where my web server is

**Comment by erolonlinee** [comment]
I followed the installation steps on the elgg site think i did what you mean 
```
composer self-update
composer create-project elgg/starter-project:dev-master ./path/to/project/root
cd ./path/to/project/root
composer install
composer install # 2nd call is currently required
vendor/bin/elgg-cli install # follow the questions to provide installation details
```

I have uploaded some files to my computer using these commands with composer
then I threw these files into the elgg 4.x file that I had downloaded and it worked.

**Comment by jdalsem** [comment]
My guess is you downloaded the wrong zip (just the source code, not the release). Glad that you got it working now!
