### ISSUE TITLE
[Feature]: make an \ElggEntity::deleteAllMetadata function 

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#14147]
### Describe the feature

https://github.com/Elgg/Elgg/pull/14144#discussion_r958373122

### Is your feature request related to a problem?

I'm always frustrated when [...]

**Comment by jdalsem** [comment]
I have thought about this, but we will leave it as is for now. All remove functions on ElggEntity have the ability to remove a single or multiple
