### ISSUE TITLE
[Bug]: Elgg 4.3 login with an unvalidated account doesn't show correct error message

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#14162]
### Elgg version

4.3.*

### Source of your Elgg installation

Elgg.org website, GIT clone

### Describe the bug

When an account isn't validated yet the error message is wrong

### Steps to reproduce

1. register an account (with a validation plugin enabled like uservalidationbyemail or admin validation)
2. after registration try to login
3. the error message is ``elgg_echo('LoginException:DisabledUser')``

### Expected behaviour

Show the error of the validation plugin

### Additional notes

caused by 82b6ffe4df9edea5ddddb7368918540f1034a61b

reported on the community https://elgg.org/discussion/view/3269711/new-user-walled-site-gets-message-account-deactivated#elgg-object-3269771

**Comment by valmiki** [comment]
Thank you for the fix!
Jan
