### ISSUE TITLE
[Bug]: wrong redirect after user delete

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#14184]
### Elgg version

4.3.3

### Source of your Elgg installation

Elgg.org website

### Describe the bug

After deleting an unvalidated user the redirection leads to the no longer existing page site.url/admin/users/newest.

**Comment by jeabakker** [comment]
fixed in https://github.com/jeabakker/Elgg/commit/b5b35701b61c5aabedbd8bf00fe4a68405d08b39
