### ISSUE TITLE
[Bug]: elgg_redirect_response does not forward site to foward url

### ISSUE THREAD

**Issue by gadgetman2016** [Elgg/Elgg#14210]
### Elgg version

4.1.4

### Source of your Elgg installation

Elgg.org website, Other

### Describe the bug

The function "elgg_redirect_response" does not forward site the forward url. The deprecated method "forward" works. Behind the scenes both methods are doing different things.

### Steps to reproduce

1. 
2.
3.
...

### Expected behaviour

When "elgg_redirect_response" is called with forward url, it should forward the site to the forward url.

**Comment by RiverVanRain** [comment]
The snippet of your code would give more insight into what you are doing wrong.

Assume, you're trying to cause a redirect in the `view`.

Try this:

```
$exception = new \Elgg\Exceptions\HttpException();
$exception->setRedirectUrl($forward_url);
throw $exception;
```

**Comment by jeabakker** [comment]
The result of `elgg_redirect_response` is a response that should still be handled by the response system.

Mostly this function is used in [actions ](http://learn.elgg.org/en/stable/guides/actions.html#writing-action-files) and [controllers](http://learn.elgg.org/en/stable/guides/routing.html#route-controllers).

**Comment by gadgetman2016** [comment]
@RiverVanRain, your code snippet works, but it causes errors when logging in to a site. The following is the snippet of code that I am using.

```
// forward contractors to search page
if( $role && EC_Utils::ec_is_contractor($role) )
{
    $forward_url = elgg_get_site_url() . 'jobs/search';
        
    elgg_redirect_response( $forward_url );
}
```

@jeabakker, if the result of `elgg_redirect_response` is suppose to be  handled by the response system, what exactly is it suppose to do. The function `forward` works perfectly for forwarding the site. Elgg says that the method is deprecated and `elgg_redirect_response` should be used.

**Comment by jeabakker** [comment]
@gadgetman2016 if you have your code snippet currently in a resource file you may have to move it to a [middleware ](http://learn.elgg.org/en/stable/guides/routing.html#route-middleware) in your route registration.

```php

ContractorRoleGateKeeper {

   public function __invoke(\Elgg\Request $request) {
       $role = find_role();
       if ($role && EC_Utils::ec_is_contractor($role) {
            return elgg_redirect_response('jobs/search');
       }
   }
}
```

**Comment by gadgetman2016** [comment]
@jeabakker , there are many places in my resource files that require forwarding to a new url, with that being said I do not think that your solution will work for me. Can we have a more general replacement to `forward ` where no exceptions need to be thrown and no middleware need to be set?

**Comment by RiverVanRain** [comment]
@gadgetman2016 So, it's not the Elgg issue but your code.
Using @jeabakker solution you can add a middleware to [elgg-plugin.php](http://learn.elgg.org/en/stable/guides/routing.html#custom-middleware). In this case, you don't need to rewrite all your resources.

**Comment by jdalsem** [comment]
The intended use for `elgg_redirect_response` is as @jeabakker has described. 'forwarding' in your code should be done in middleware or in controllers, not in views/resources
