### ISSUE TITLE
Installing elgg | Fatal error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query()

### ISSUE THREAD

**Issue by sedsajad720** [Elgg/Elgg#14211]
Hello everyone.

I am trying to install Elgg on xampp and everything works fine. But in database step of installation, I get this error.

Fatal error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in C:\xampp\htdocs\sites\elgg\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php on line 81

What I've tried:
1. Downgrading my php version from 8.1 to 7.4
2. Changing the declaration of 'query()' method in the 'PDOConnection.php' to 'query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)'

I also get 502 status code when I'm trying to reach your website: https://elgg.org/

Thank you in advance.

**Comment by jeabakker** [comment]
Which version of Elgg are you trying to install?
This sounds like an PHP version issue.

We're aware of the website issue, will be fixed asap.

**Comment by sedsajad720** [comment]
Thanks for the quick reply! The version is elgg-3.3.20.

**Comment by jeabakker** [comment]
Elgg 3.3 is incompatible with PHP8+ you should try with PHP 7.4.

You state you already tried that, but it should work just fine.

**Comment by jdalsem** [comment]
Assuming this is an installation error i am closing this issue.
