### ISSUE TITLE
[Bug]: Username not validated for special characters

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14239]
### Elgg version

4.3.4

### Source of your Elgg installation

Elgg.org website

### Describe the bug

If non-standard characters are used in the username, as `Username™`, then links to neither the user profile nor the user settings work.

### Steps to reproduce

1. Register with username `Username™`
2. Try to go to User's profile page; you will be redirected on Activity
3. Try to go User's settings page; link is empty

### PHP version

8.1

**Comment by jeabakker** [comment]
ps: steps to reproduce would be nice ;)

**Comment by RiverVanRain** [comment]
> Is this related to #12518 or #13067?

I dont't think that.

It's not unicode. And even with #12518 there are no problems.

We use this regex:
`$whitelist = '/^([A-Za-z_0-9]+)$/i';`

But the valation is skipped with the mentioned example.

**Comment by jeabakker** [comment]
I found the issue in the username validation, will be fixed.
