### ISSUE TITLE
Issue on hook 'action:validate', 'plugins/settings/save'

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14289]
Trying to register this hook handler:

```
_elgg_services()->hooks->registerHandler('action:validate', 'plugins/settings/save', function (\Elgg\Hook $hook) {
	elgg_unregister_plugin_hook_handler('sanitize', 'input', \Elgg\Input\ValidateInputHandler::class);
});
```

does nothing.

Elgg 4.3.7.
No third party plugins installed.

**Comment by jdalsem** [comment]
Unable to reproduce. I have tested it on 4.3.4. 

After unregistering the hook, you can confirm with:
`var_dump(_elgg_services()->hooks->hasHandler('sanitize', 'input'));exit();`

It should show no hooks have been registered.

**Comment by RiverVanRain** [comment]
Return:
`bool(true)`

This hook worked on 3.x but not since 4.x

I've created [custom plugin](https://github.com/RiverVanRain/hooks) with 2 branches

**Comment by jdalsem** [comment]
We are still unable to reproduce this on 4.3.7.

> No third party plugins installed.

If you use your own plugin, that could be the issue. You are registering your own sanitize input hook handler.

**Comment by RiverVanRain** [comment]
The custom plugin is just an example and for testing.

Issue is still on 4.3.7.

_elgg-plugin.php:_

'hooks' => [
	'action:validate' => [
		'plugins/settings/save' => [
			\Elgg\Input\ValidateInputHandler::class => ['unregister' => true],
```
		],
	],
],
```

_\views\default\plugins\my_plugin\settings.php:_

```
echo elgg_view_field([
	'#type' => 'plaintext',
	'#label' => elgg_echo('settings:head_extend'),
	'name' => 'params[head_extend]',
	'value' => $entity->head_extend,
];
```

Filling out the form with `<script>test</script>` returns `test` on save.

**Comment by jeabakker** [comment]
```
'hooks' => [
	'action:validate' => [
		'plugins/settings/save' => [
			\Elgg\Input\ValidateInputHandler::class => ['unregister' => true],
		],
	],
],
```
will do nothing as the plugin hook ``\Elgg\Input\ValidateInputHandler::class`` wasn't registered on the `action:validate, plugins/settings/save` hook.

If you wish to unregister plugin hook during your action you need to write a plugin hook on the `action:validate` of your action and then unregister the input validation hook

**Comment by RiverVanRain** [comment]
> If you wish to unregister plugin hook during your action you need to write a plugin hook on the action:validate of your action and then unregister the input validation hook

Of course,[ I did that](https://github.com/RiverVanRain/hooks/blob/master/elgg-plugin.php#L12) from the very beginning.

I've tried now without custom sanitize input hook:
_elgg-plugin.php:_
```
'hooks' => [
	'action:validate' => [
		'plugins/settings/save' => [
			\wZm\Hooks\FilterHooks::class => [],
		],
	],
],
```


_\wZm\Hooks\FilterHooks.php_

```
namespace wZm\Hooks;

class FilterHooks {

	public function __invoke(\Elgg\Hook $hook) {
		elgg_unregister_plugin_hook_handler('sanitize', 'input', \Elgg\Input\ValidateInputHandler::class);
	}
}
```

Nothing.

This issue is actually for ANY `action:validate` plugin hook, e.g. [this](https://github.com/ColdTrick/widget_pack/commit/5d4942acc15e865829cfe34869b2543bc0da7b92#diff-36ebbf9cd9dd44609af8460cef4c40c05ca202f841f592a027a054a262ef0271L34).

**Comment by RiverVanRain** [comment]
Seems, 'hooks' via **elgg-plugins** has same problems #14319
