### ISSUE TITLE
[Feature]: allow the user to configure a personal default list length

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#14361]
### Describe the feature

see https://github.com/ColdTrick/user_default_limit

Just like personal default access level, allow a personal default list length

**Comment by jdalsem** [comment]
With the current availability of ajaxed pagination / endless scroll there is no real need to have this configurable on a per user preference. You already have the possibility to set a different limit site wide (other than the default of 10) as a site administrator.
