### ISSUE TITLE
[Bug]: "Utilities" submenus not accessible

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#14374]
### Elgg version

5.0.0

### Source of your Elgg installation

Composer install

### Describe the bug

If the list is long, you cannot access "Utilities" submenus from the admin panel. 
Ideally, the list should be scrollable to view all the menus, but currently the list is a static view and I cannot access the menus at the bottom. Please take a look at the screenshot attached.

### Steps to reproduce

Hover over the "Utilities" menu with a big list.

### Additional notes

![image](https://github.com/Elgg/Elgg/assets/2772844/9d5f096f-885a-4f2e-9731-865974239fe2)

### PHP version

8.1.5

### PHP error log

```text
None
```

**Comment by jdalsem** [comment]
In Elgg v5.1 we have moved all 'utilities' to a dedicated topbar menu item. This slightly reduces the occurence of this overflow issue. We are not going to provide a definitive solution for this issue, as we want to keep things simple. For your own environment there might be different solutions such as reorganizing the menu items, or removing the sticky behaviour of the topbar.
