### ISSUE TITLE
Revisit cache logic

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#14595]
We now have various classes and storages for caches. We should use composite caches for storage. Helper classes should only differentiate between purposes of these caches. Currently we have some inconsistencies in how these caches exist. We also need to take a look on the ease of use of the caches with regard of DI.

For @jeabakker we need to have a look at the Preloader logic in relation to caches... don't know why exactly, but we can still have a look :)

**Comment by jeabakker** [comment]
https://github.com/Elgg/Elgg/blob/11ce0cd7f42708d2272eeb86bb1c0d254b433cc3/engine/classes/Elgg/EntityPreloader.php#L34-L41

**Comment by jdalsem** [comment]
Various changes have been made to consolidate all caches. This improves readability by a lot
