### ISSUE TITLE
[Feature]: update lint checker

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#14615]
### Describe the feature

Our current link checker for the GitHub actions is outdated, so it should be updated

### Is your feature request related to a problem?

I'm always frustrated when [...]

**Comment by jeabakker** [comment]
https://github.com/super-linter/super-linter

**Comment by jdalsem** [comment]
Not able to upgrade at the moment (the current commit message checker has features we want). Leaving this as is for now (until it breaks)
