### ISSUE TITLE
[Bug]: ELGG.CRITICAL: Found unconstructed IntlDateFormatter

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14712]
### Elgg version

5.1.9

### Source of your Elgg installation

Elgg.org website, Composer install

### Describe the bug

Recently, this critical error has started to appear on all instances with the Elgg v5.1.9. 

The error appears on PHP v8.2.23 and v8.3.12 both.

`php_intl` extension is installed and enabled.

Could you explain this and how to resolve this issue?

References: 
https://github.com/php/php-src/issues/12912 
https://github.com/php/php-src/issues/12943

### Steps to reproduce

1.
2.
3.
...

### PHP version

8.2.23, 8.3.12

### PHP error log

```text
ELGG.CRITICAL: Exception at time 1727799250:
Found unconstructed IntlDateFormatter
{
"backtrace":[],
"process_id":861468,
"memory_peak_usage":"12.41 MB",
"memory_usage":"12MB",
"url":"/blog/view/7369",
"ip":"43.133.208.84",
"http_method":"GET",
"server":"site.com",
"referrer":"https://site.com"
}" 
while reading response header from upstream, client: 43.133.208.84, server: site.com, 
request: "GET /blog/view/7369 HTTP/1.1", 
upstream: "fastcgi://unix:/run/php/php8.3-fpm.sock:", host: "site.com", referrer: "https://site.com"
```

**Comment by jeabakker** [comment]
https://github.com/Elgg/Elgg/blob/50ba175da2309dbb95357a60ce479216c2cb63dc/engine/classes/Elgg/I18n/DateTime.php#L169

is the only place we use `IntlDateFormatter` if you add a try/catch around this like suggested in https://github.com/php/php-src/issues/12912#issuecomment-1848339470 does this solve the issue.

If so we can patch it

**Comment by RiverVanRain** [comment]
Yeah, this works:

```
protected function formatIntl(string $format, string $language) {
		$correct_format = $this->dateFormatToICU($format);
		if ($correct_format === false) {
			return false;
		}
		
		try {
			$locale_for_language = _elgg_services()->locale->getLocaleForLanguage($language);
		
			$locale = new \IntlDateFormatter(elgg_extract(0, $locale_for_language, $language), \IntlDateFormatter::FULL, \IntlDateFormatter::FULL);
			$locale->setPattern($correct_format);
		
			return $locale->format($this);
		} catch (\Exception $e) {
			elgg_log($e->getMessage(), 'ERROR');
			return false;
		}
	}
```

**Comment by jeabakker** [comment]
I'll fix it, thanks for the research
