### ISSUE TITLE
Replace sprintf.js by jQuery i18n plugin

### ISSUE THREAD

**Issue by sembrestels** [Elgg/Elgg#5117]
sprintf.js is a monster, while i18n is just what we need:

https://github.com/recurser/jquery-i18n/
https://github.com/recurser/jquery-i18n/blob/master/src/jquery.i18n.js

**Comment by jdalsem** [comment]
Do we want this in @Elgg/owners ? I can do a PR

**Comment by mrclay** [comment]
Sure, in master.

**Comment by ewinslow** [comment]
Yea. Would ultimately prefer a message format based system, but reducing js
blast in the mean time seems like a good idea.

**Comment by jdalsem** [comment]
@ewinslow is it smart to tackle this, regarding to your latest work on the message formats?

**Comment by ewinslow** [comment]
I'd rather we just get it right for 2.0 and use MessageFormat
