### ISSUE TITLE
rel=popup should support multiple identical popups for the same entity

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5121]
The popups won't get closed at all if there are more than one popup link with the same href.

I added a sidebar module to activity page to display latest likes. None of the popups that are also found from the river list get closed.

Using Elgg 1.8.13
All browsers are affected

**Comment by ewinslow** [comment]
@juho-jaakkola any updated thoughts on this?

**Comment by juho-jaakkola** [comment]
I suggest the 2. option: "Change our JS to support multiple popups and change to using a class rather than an id"

**Comment by jdalsem** [comment]
You can already do this with the toggle feature currently in elgg. Only problem is that there is a major overlap with the 'popup' feature, that is why i suggested to drop that in #7944

**Comment by jdalsem** [comment]
Closing this as the behaviour requested can be achieved using rel='toggle'
