### ISSUE TITLE
pages (new features): autosave drafts and statuses

### ISSUE THREAD

**Issue by jrtilson** [Elgg/Elgg#5155]
Hello, 

We've been looking to implement autosave drafts and status for the pages plugin (pretty much the same as blogs). I've started to do the work on this in our fork but I thought I'd ask here if there is any interest in this and if there is any preference in how the autosave drafts are handled. 

The main question is, if desired, should autosave drafts be a regular revision or should they be a completely new type of revision just for autosaves? (ie: two different annotations)

The pages plugin currently has some basic history functionality built in, but no real way to revert/edit revisions (I think just making them editable would be a good start).

Lastly, I think being able to set a published/draft status would be pretty useful.

Any thoughts?

**Comment by jdalsem** [comment]
Closing this for now as there is no progress and i also do not think draftability makes sense for the pages feature
