### ISSUE TITLE
Add ability to undo item deletion

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5172]
I've had it happen before where an object will get deleted by accident but there's no way to recover it because we hadn't backed up the DB yet. Add to that the fact that restoring from DB backup is a huge hassle even if we had it, and you have a good case for marking items for deletion without actually deleting them, similar to how you can trash gmails but they're still kept around for 30 days.

Proposal:
1. Add a boolean field to the entities table that marks an item deleted or not. Also a timestamp field that specifies when the deletion happened. Maybe make these one field.
2. Update the entity delete function to just set the flag to true and set the timestamp appropriately.
3. Add a function for undoing deletion (`undelete`? `setDeleted(false)`?)
4. Add a cronjob that goes through and deletes anything that has been marked deleted for more than X days/seconds.
5. Add a function `deleteForRealz` that does what current `delete()` does.
6. Add some admin and possibly user UI for recovering deleted entities.

We may also have to do the whole "deletedWith" relationship thing ala disabling entities.

**Comment by beck24** [comment]
And it's happened again... :(
Non-dev end users just don't seem to get that deleting a user will delete their stuff.  It's intuitive to me, but I guess not to people outside of the elgg world.  This has to be bumped in priority because I can't handle this happening every 6 months.
This was even a client who went through this previously and completely forgot...

Thinking about how this would work - it's hugely BC breaking.  On top of the recursive delete/undelete we'd also need events to fire on undelete, that would probably reverse whatever a delete event did.  Existing delete events would probably be unfavorable knowing that it's not *really* deleted.
I'm going to make #6950 a priority as long as there's no objections to that method, that can be done a little sooner/easier.

**Comment by mrclay** [comment]
For the short term I suggest we make user (and group) "delete" menu items lead you to a confirmation page where the user must check that they understand that the content will be deleted (show some content stats, provide some views so sites could extend it).

Currently on my sites I remove user delete menu items unless a special query param is present.

**Comment by brettp** [comment]
Can you override the delete action and just have it disable the user and
its contained entities?

On Tue, Jan 6, 2015 at 1:56 PM, Steve Clay <notifications@github.com> wrote:

> For the short term I suggest we make user (and group) "delete" menu items
> lead you to a confirmation page where the user must check that they
> understand that the content will be deleted (show some content stats,
> provide some views so sites could extend it).
>
> Currently on my sites I remove user delete menu items unless a special
> query param is present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/5172#issuecomment-68913378>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by iionly** [comment]
As mrclay said: first thing to do would be to alter the confirmation messages for deletion of users and groups to point out very clearly that deletion of the user/group will result in their content getting deleted, too. Most likely, this would make acccidential deletion of content much more unlikely already.

Then the Expirationdate plugin comes to my mind (originally by Brett): https://community.elgg.org/plugins/836423.

This plugin allows to set an expiration date (by adding metadata to the entity) when an entity should get deleted (alternatively just disabled). Via cronjob the expired entities are deleted/disabled at this date then. Maybe this plugin could be useful as a starting point for implementing a "user/group garbage can" plugin for inattentive admins. Then the safety net wouldn't have to be directly implemented in core (and could be disabled if it's not needed).

Wouldn't it possible to alter the delete actions for users and groups to just disable these entities (additionally all contained entities) and additionally add an expiration date (e.g. +1 day/week/month). After the expiration date has been reached the user/group gets deleted in the normal way. In the admin section a "user/group garbage can" page could be added to allow for removing the expiration date metadata and activating the users and groups again if the admin (or maybe even the user who asked for the account to get deleted) changed his mind or if the deletion had only been a mistake.

**Comment by jdalsem** [comment]
Related to the discussion in #10770
