### ISSUE TITLE
Provide support for easily authoring in custom format and publishing in HTML

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5181]
This is a fairly major feature request, but I think could go a long way toward improving the user experience. I'm sure we can figure out a way to break it down into smaller deliverables.
## Proposal: Provide input/longtext view with a "format" option

The view needs to know the format so it can present the user with the right editor. This would default to html, I assume, for BC. This format is then also passed via hidden input to the form's action so that we know what converter to use to transform it to HTML before we store it in the DB. The original content and authoring format can be stored as metadata. Note that this means actions would have to be rewritten somehow to respect custom formats.
## Brain dump and motivation:

It's been said that Markdown is an authoring format while HTML is a publishing format. Right now, it seems like plugins assume a particular format. Either plaintext or HTML input (presumably edited by WYSIWYG editor), and there's no easy way to switch to another. I personally really find markdown more enjoyable to write in than any WYSIWYG editor. There are plenty of other formats as well, like wiki, rst, textile, LaTeX, etc.

**As a user**, I'd like Elgg to allow me to author in my format of choice (assuming it's supported by a plugin in the hosting site, of course), and save both the authored content as well as the content-for-publishing. Note that this is relevant even when we're not talking about different formats but just filtering content for autolinking `@mentions` or `#hastags` or removing `<script>` tags. You want to store the originally authored content for editing so you don't lose information and you parse and store the for-publishing version so you don't have to re-parse for mentions and hashtags every time the blog is displayed somewhere. And you certainly wouldn't want to parse a more involved format like markdown every time you need to display a blog.

**As a webmaster**, I'd like an easy way to opt for something other than the compulsory HTML/WSYIWYG option. I find that it gives amateur users just enough rope to hang themselves with. It encourages formatting instead of focusing on content. Right now, Elgg assumes WYSIWYG too much to do that easily.

I feel like forcing a site to choose and stick with a single format is pretty inflexible, since they might want to change things up down the road (e.g., like how I've lobbied for switching from HTML WYSIWYG to markdown on the community site), so this rules out supporting only one format at a time.
## Potential feature list:
- Site owners can install plugins to support multiple authoring formats.
- Site owners can pick a default/preferred format.
- Their users can author in their format of choice.
- The originally authored content is saved for editing.
- The content is pre-parsed to HTML for publishing.
- Users can change their preference.
  - New content is authored in this new format.
  - Old content retains it's original format when edited.
- Maybe allow users to do conversion (formatA => HTML => formatB) 
- Maybe allow site owners to do forced conversion

**Comment by jdalsem** [comment]
This can be easily achieved by hyjacking view output via a view_vars hook
