### ISSUE TITLE
Cache files routed via /cache/ handler as static, public files

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5186]
Originally brought up here: https://groups.google.com/d/topic/elgg-development/KIgNZdFNd-w/discussion

Summary:
* keep cache handler in very similar way, and additionally
* have writable `/cache/` dir in wwwroot (yes, the same as cache handler)
* when we get the request (sort of
`http://my_page.com/cache/1361945379/default/js/elgg.js` or similar)
    * if we don't have static file, we do everything as usual, but after
that we create directory structure in `/cache/` dir to match url
    * next time we get the request it grabs existing file directly (we
recognize this case with rewrite rule flag - same as for page handlers
now)
* if we didn't have write perms, we just don't save - system is as today
* if cache is refreshed, timestamp changes and we point to different
path (we'd need to cleanup old cached files) 

See: #5174, #5091, #4476, #5105, #4460

**Comment by ewinslow** [comment]
Sightly modified idea:

Symlink from /cache/ to a subdirectory in the dataroot. This way we don't need a writable directory in wwwroot, and we can also support deployment tools like envoyer. they rebuild wwwroot code after each deployment and then flip a symlink to make the upgrade atomic so no request gets made in the middle of an update. If we actually stored the caves files in wwwroot, we'd lose them at each upgrade, breaking old clients.

**Comment by ewinslow** [comment]
I still think my idea from before about converting js/elgg (https://github.com/Elgg/Elgg/issues/5186#issuecomment-53230152) would be a good solution that is still reasonably backwards compatible. We'd have a few more files to do this with, but I feel it could work reasonably well...

**Comment by ewinslow** [comment]
That said, if we want to do https://github.com/Elgg/Elgg/issues/8382 it'd probably be best not to introduce `js/elgg.js` and just skip straight to `elgg.js` as the view name.

**Comment by mrclay** [comment]
Done in #8538!

**Comment by ewinslow** [comment]
Wow, closing 2 year old tickets is nice!
