### ISSUE TITLE
Plugin names cannot be translated in plugin usersettings module blocks

### ISSUE THREAD

**Issue by adayth** [Elgg/Elgg#5196]
In `views/default/core/settings/tools.php` developers cannot translate plugin names to provide a friendly name for plugin names.

``` php
$title = $plugin->getManifest()->getName();
$body = elgg_view_form('plugins/usersettings/save', array(), array('entity' => $plugin));
echo elgg_view_module('info', $title, $body);
```
Currently, in my site I changed `$title` with `$plugin->getID()` and appended ':usersettings:title' to provide a translation for these module box titles using `elgg_echo($title)`

**Comment by jdalsem** [comment]
Translatability for the usersettings form is already reported before in #2201. #8055 is providing the fix
