### ISSUE TITLE
Overflow: hidden on elgg-body hides dynamic content

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5197]
E.g. At the end of a form I have a Bootstrap [dropdown](http://twitter.github.com/bootstrap/components.html#buttonDropdowns) button group. The dropdown doesn't show because the display is clipped to the end of elgg-body.

**Comment by mrclay** [comment]
With browsers farther along I think it's time to revisit this.

**Comment by hypeJunction** [comment]
We can add a better clearfix using pseudo selectors to prevent floated elements from overflowing .elgg-body. I am not a big fan of table-cell display though. Min-height imho should be avoided at all costs as they tend to create gaps in responsive layouts - as seen in widget columns on mobile.

This is what is used by Foundation for clearing:
```sass
@mixin clearfix {
  &:before, &:after { content: " "; display: table; }
  &:after { clear: both; }
}
```

Re: .elgg-image-block, in custom themes, I have opted for using absolute positioning of the image with a left padding on the body. This won't work for core however.

**Comment by ewinslow** [comment]
:+1:

http://caniuse.com/#feat=flexbox

**Comment by mrclay** [comment]
Yep: https://philipwalton.github.io/solved-by-flexbox/demos/media-object/

**Comment by mrclay** [comment]
PR #9288. Lotta scary changes!

**Comment by mrclay** [comment]
In 2.0.x can we deploy a less radical technique to address 1px clipping of radios/checkboxes? Maybe a pixel of left margin in certain circumstances?

**Comment by mrclay** [comment]
Not a blocker for 2.2. Removing milestone.
