### ISSUE TITLE
Possible system cache race conditions

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5201]
This is relatively low priority.

I was using system cache to store some data and noticed once that one of the requests (one of JS actually) got error with coudn't open file (this file is read on every core run). This didn't repeat. We could possibly review the code and think of using flock's or securing it in some other way so we have 100% reliability here in healthy server cases.

**Comment by jdalsem** [comment]
@Elgg/core do we want to do something with this?

**Comment by mrclay** [comment]
Indeed Stash is an option, and 3 would be the time to do it. I fear it will be slower, but beats breaking sites.

**Comment by mrclay** [comment]
Cool if someone wants to work on it. Not necessary for 3.0

**Comment by hypeJunction** [comment]
Can close
