### ISSUE TITLE
Add release status to plugin's manifest

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5211]
In my daily work with elgg that's very common that I deal with the plugins that are under development and these that are "stable" versions. Maybe it would be good idea to add such info to manifest and mark it on plugins list (ie. light yellow background for unstable plugins).

I think it would be useful mostly for developers working with elgg to mark plugins in main repo that shouldn't be enabled by other developers on their installations or on production servers.

**Comment by jdalsem** [comment]
I like the idea, but it is only really useful for devs. You can also add BETA to the versionnumber to achieve the same info...
