### ISSUE TITLE
Generic method for adding tokens to links for user authentication

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5213]
User validation by email generates a code that is added to the link in the validation email. https://github.com/Elgg/Elgg/blob/master/mod/uservalidationbyemail/lib/functions.php#L16

The code in the link is used to authenticate and sign in the user.

Many people request this kind of feature also for other emails. For one client I even made a plugin that parses all the email bodies before sending and adds similar token to all links.

So how about adding a generic method in core to generate and validate links that would allow automatic authentication? In theory this feature would reduce site security but would it be an actual problem if the token generation was strong enough?

Maybe it could use some of the same code as web services plugin that also saves tokens to database. Currently the problem is just that web services doesn't support multiple tokens:
https://github.com/Elgg/Elgg/blob/master/mod/web_services/lib/tokens.php#L30

Comments?

**Comment by twentyfiveautumn** [comment]
If the user had to login to subscribe it seems like a reasonable expectation that they would need to login to unsubscribe. Then no security issue is raised. I do like the landing page idea to make it easy to unsubscribe once logged in.

**Comment by jdalsem** [comment]
the current ElggCrypto and HMAC functions offer enough features for this issue for now
