### ISSUE TITLE
Localize ACLs

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5225]
Provide a mechanism for localizing the name of an ACL. For example, right now group ACL's are saved using the language of the group owner.

**Comment by ewinslow** [comment]
@mrclay's entity list system will resolve this. #2567 

Should we just close here, or worth leaving open to make sure we don't forget.

**Comment by jdalsem** [comment]
This can perfectly done nowadays with the `'access_collection:name'` plugin hook
