### ISSUE TITLE
URL service for producing/validating URLs/paths

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5227]
This would cover things like:
- Get URL path from root. E.g. "/", "/subdir/"
- Is a URL within the site? Options for allowing differences between HTTP/HTTPS
- Is a URL within the current domain?
- Get URL segments created by page handler

**Comment by mrclay** [comment]
- [ ] validate redirect in #7795

**Comment by ewinslow** [comment]
Also see https://github.com/php-fig/http-message/blob/master/src/UriInterface.php

**Comment by ewinslow** [comment]
Still want this, but doesn't need to block 2.0

**Comment by jdalsem** [comment]
Currently we have enough api for parsing and validating urls
