### ISSUE TITLE
Add more granular system events than init system

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5228]
The idea is to encourage registration of particular things only when they're necessary. Ie. we need to register actions only in action handler. In other cases (apart from generating action tokens) we don't need to load and instantiate whole actions service. Having that we let plugin creators register and do specific stuff only when necessary not on every init.

List of events we could use (more is better IMO):
* `'init:action', 'system'` - on action handler execution (just after init system?)
* `'init:page_handler', 'system'` - on page handler execution (just after init system?)
* `'init:cache', 'system'` - on cache handler execution (just after init system?)
* `'init:widgets', 'system'` - widget types registration (called laizily from widgets service)
* `'init:views', 'system'` - views extensions etc. (called laizily from views service) - not sure if pagesetup shouldn't serve this purpose
* probably most of the services that accept registration to them could have their own init event

If you have more ideas, please add.

Note that most of these seem to be very littile cost registrations, but I'd like to save here on additional logic that plugins sometimes do and can be tricky sometimes. And additionally in ideal world we woudn't load services that are in fact not used.

**Comment by jdalsem** [comment]
Closing this as the approach with a plugin config file opens up specific phases in the init of plugins... different sections from the plugin file could load at different moments
