### ISSUE TITLE
Merge messageboard into thewire

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5249]
messageboard comments should be converted to wire posts, and then we can add an option in the wire settings page that can control enabling/disabling the equivalent of the current messageboard widget. This just seems like a no-nonsense simplification that also gives the ability to like/comment/reply on messageboard posts.

**Comment by mrclay** [comment]
What's the modern use case for messageboard? Seems like a 90s guestbook. Anyway this doesn't seem worth putting effort into to.

**Comment by ewinslow** [comment]
Deprecate in favor of the wire then?

**Comment by iionly** [comment]
Or: keep it just as it is.

The messageboard entries have a slightly different angle than wire postings. They address the recipient more personally. The guestbook reference seems to fit. But just because it's "so 90-like" doesn't mean it's unnecessary anymore.

**Comment by mrclay** [comment]
Yeah, to be clear my prefered outcome is to leave it as is.

**Comment by mrclay** [comment]
If it's 90's it means it's never coming back, like the X-Files.

**Comment by iionly** [comment]
@mrclay Wrong: http://en.wikipedia.org/wiki/The_X-Files_%28miniseries%29 :smile:

**Comment by jdalsem** [comment]
I'm with leaving this as is. Can always move it out of core and drop support in 3.0

**Comment by mrclay** [comment]
@iionly I was joking :) yeah, I'm excited.

**Comment by ewinslow** [comment]
SGTM
