### ISSUE TITLE
Allow to set default views tree to other than 'default'

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5258]
We have project where we've rewritten whole view tree for different templating system but have reasons to not just replace 'default' one (mostly BC for projects that use only parts of our templating system). Recently we've stumbled upon problem with `add_to_river` that checks if river view exists in default tree and we need to artificially create river views in default view tree (we use our views for river display).

My thought is that we might want to have sometimes different viewtype act as the default one, this way we'd have `elgg_get_default_viewtype` and `elgg_set_default_viewtype` functions and use them instead hardcoded 'default' as it happens currently.

**Comment by jdalsem** [comment]
I can understand the need, but probably nobody is current willing to put in the time for this to happen. Closing the issue for now. Feel free to submit a PR if you still think this should be in core.
