### ISSUE TITLE
Make password recovery pluggable

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5286]
Currently the only way to request a new password is via email.

Having a pluggable password recovery system would make it possible to create plugins that allow to reset password for example by SMS.

**Comment by jeabakker** [comment]
Currently there are 2 ways to handle this.

If you wish to send a different notification, you can hook on the email notification and send it through a different system. All information (user, verify link) is present.

If you wish a completely different system, take over the request new password action

Not going to change this at the moment
