### ISSUE TITLE
Add job queue

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5400]
My notification pull request #5389 has a message queue. When reviewing it, Evan said he'd really like a full job queue. 

Issues/decisions when writing a job queue:
- delivery/completion guarantees
- job state tracking
- transactions
- priority
- throttling
- push vs pull
- failure handling

**Comment by jdalsem** [comment]
With the current queue system you are free to create your own queue logic with little effort. No need to have more features in core at the moment.
