### ISSUE TITLE
Force all pages shown to logged out users to use the walled garden page shell

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5487]
When in walled garden mode, users can see pages like /login if they know to type in the URL directly. Refs #5483

**Comment by jdalsem** [comment]
Currently users will see the walled garden page shell for `/register`, `/login`, `/forgotpassword` and the `external pages`, so i am closing this ticket. I do not think it is a good idea to *force* all pages to have the walled garden page shell
