### ISSUE TITLE
htmlawed filters out WBR elements

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5489]
So long URLs displayed don't get the benefit of soft wrap points.

I Imagine this is in 1.8, too.

**Comment by mrclay** [comment]
Even [more betas](http://www.bioinformatics.org/phplabware/sourceer/sourceer.php?&Sfs=changelog.txt&Sl=.%2Finternal_utilities%2FhtmLawed%2Fbeta).

**Comment by jdalsem** [comment]
still waiting for a final release of htmlawed
