### ISSUE TITLE
Allow pre-opened comment fields in the river

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5501]
We could add a hook to the river/elements/responses view to determine whether or not to apply the "hidden" class to the form. (In my app I'm showing the form wherever there are already comments.)

If I remove "hidden", the menu toggler stills works, but has the "elgg-state-active" class when the form is hidden. The JS should compensate by adding elgg-state-active to the comment button, so these are in sync.

It would also be nice to set focus on the input after the form slides down, in case it's below the fold.

**Comment by jdalsem** [comment]
you could achieve this with a hook on the view vars for 'forms/comment/save' and maybe some additional css
