### ISSUE TITLE
elgg_get_entity_metadata_where_sql metadata and annotations tables are named the same (n_table)

### ISSUE THREAD

**Issue by SimonEbeling** [Elgg/Elgg#5515]
When passing metadata-options through "elgg_list_entities_from_annotations($options)" the function "elgg_get_entity_metadata_where_sql" names annotation table and metadata the same which gives a database error that the table must be uniqe.

![untitled-1](https://f.cloud.github.com/assets/3341534/532443/ef625742-c146-11e2-92af-32a3a48e115c.png)

My quick-fix solution for this was making a name-variable:

```
if($n_table == 'annotations')
{
$table_name = 'a_table';    
}
else{
$table_name = 'm_table';
}
```

and then using the name-variable instead of the string "n_table" in the rest of the function.

**Comment by jdalsem** [comment]
Currently in Elgg/master unable to reproduce. Good chance this has been fixed somewhere in the past years. If someone has steps to reproduce let us know.
