### ISSUE TITLE
Provide error logs in admin panel for asynchronous requests (ie. cron)

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5532]
The idea is to have special error and exception handlers for pages like cron (or other 3rd party integrations that want to use it, like asynchronous callbacks), pages that don't output to the browser, that would catch errors and exceptions and present in admin panel on special page maybe? We could have them logged to separate files (for each request) in particular data root subdir.

It can be done via plugin, but having it in the core would make diagnosing cron problems easier IMO.

**Comment by jdalsem** [comment]
These errors can/will also appear in the PHP error logs... do you really want to duplicate that error log?

**Comment by jdalsem** [comment]
Closing this as we can use PHP error logs for this. If needed a plugin could provide this feature.
