### ISSUE TITLE
Creating annotation as user without access to it trigger create event with empty object

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5537]
In case we create annotation for different owner_guid and access_id private, we're able to create it, but [this code](https://github.com/Elgg/Elgg/blob/master/engine/lib/annotations.php#L104):

```
            $obj = elgg_get_annotation_from_id($result);
            if (elgg_trigger_event('create', 'annotation', $obj)) {
                return $result;
            } else {
```

Causes trigger to be run with empty value in `$obj`.

**Comment by ewinslow** [comment]
Still a valid bug, it seems to me.

**Comment by jdalsem** [comment]
Code has long been changed somewhere during 1.x. I believe this particular situation will not happen anymore.
