### ISSUE TITLE
Make page/components/list more configurable

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5545]
While #4449 aims to add completely different renderers for lists, I'd like to just be able to more simply alter rendering of page/components/list through the elgg_list_entites() functions. Examples:

* pass in a view name to be used instead of `elgg_view_list_item()`
* allow removing the UL/LI elements

This way you could simply pass in a view to render the entity as a TR or whatever without having to create your own full list handler and copy/pasting the pagination stuff.

**Comment by jdalsem** [comment]
I believe this is fixed with #7903
