### ISSUE TITLE
Add "close all" option for admin notices and info about more notices

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5576]
Sometimes if you ie. disable many plugins on code update, you may produce a lot of admin notices. Clicking on them one by one is a lot of effort to do and may cause users to miss new notices or confuse second page showing up after reload with new notices.

If we had more than 10 notices we could show static (not closeable) info on bottom of the list telling sth like "23 more notices". Could actually think of separate page showing all of them with pagination (maybe there would be a good place for "close all" button)

**Comment by ewinslow** [comment]
Ran into this recently myself. Having to close them one by one is definitely still annoying...

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/pull/11523
