### ISSUE TITLE
enhancement: ui selection method for filtering content of entity lists by groups/containers

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#5588]
presently items that have been added to groups are somewhat 'buried' in the site structure in terms of navigation paths from the homepage. e.g. files for a particular group require the user to click through the group page, then click the files tab..
not only is this an unnecessarily high number of pageloads and clicks but also complicated the task of locating a particular file when uncertain of which group the file is contained within.

my desired solution is to amend the entity listing code and 'tabbed filter' view (or other relevant view) to include a ui device (e.g. a dropdown selector) that allows entity (and river) lists to be filtered by group. this would allow users to visit the 'view all files' page and then quickly change to view only files for a specific group.

this process would further be improved by including the functionality of the containers plugin that i have created here: http://community.elgg.org/plugins/1211419/0.4.1/containers
which would allow users to choose the containing group directly from the 'entity creation form/page' and also show which group that the entities are contained by on the summary and full listing views for each entity (where appropriate).

**Comment by jdalsem** [comment]
Closing this ticket as with #8671 is now is much easier to find your own content, so there is less need for a owner filter in groups content listings

For the other issues there are already solutions with the use of some plugins or can be solved with theming. Also the 'advanced' filtering of content is something that can/should be part of a search feature instead of begin part of the default content listings of Elgg.

**Comment by propertunist** [comment]
change #8671 is one that i already coded on my own site several years ago, but it does not provide the type of effect that this ticket is intended to facilitate. being able to see items in specific groups all from the activity page is a very useful feature, especially if the data load is ajaxed.
