### ISSUE TITLE
enhancement: comment summaries with a 'see more' link

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#5632]
essentially this is a request for the 'facebook' like feature of having comments that are longer than a particular length shortened to be only 1,2 or 3 lines long and to add a hyperlink marked 'see more' or similar to either view the entire comment (loaded via ajax) or to simply navigate to the comment in full (ajax is preferable for me).

i thought i had already seen this either in trac,github or the elgg community - however, after searching i have not found the idea mentioned.. either as a request or as part of a plugin.

**Comment by jdalsem** [comment]
i do not feel the urge anymore to pick this up currently as comments are currently excerpts in the activity stream, so the 'long comments' issue is no longer the case

**Comment by jdalsem** [comment]
Closing this ticket as we currently show excerpts of comments in the river, so this wish became obsolete
