### ISSUE TITLE
Add support for perceptual diffs for default theme and bundled plugins

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5649]
That's a long term idea. Google uses it in porcess of continious deployment to catch any visual changes and make it easier to catch by the person reviewing it.

We might consider implementing such approach for default theme and plugins. Especially to catch missing page parts. CSS changes seem low priority in our case. AFAIK they use Phantom.JS for making screenshots. That tool should probably be run outside of Travis - it would probably kill it.

See: http://pdiff.sourceforge.net/ and https://www.youtube.com/watch?v=UMnZiTL0tUc

Probably should go to long term future release/duscussion

**Comment by jdalsem** [comment]
I think the effort to create this will not outweigh the benefits
