### ISSUE TITLE
CKEditor doesn't work on android

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5686]
I didn't see single situation where it works. It shows up simple textarea with link "Remove editor".

My phone:
```
Sony Xperia Pro
Android 4.0.4
```
Default internet browser.

**Comment by jdalsem** [comment]
CKEditor 5 will have full support for mobile
http://ckeditor.com/support/faq/features#question10

**Comment by jdalsem** [comment]
With #8157 merged the toggle editor link will no longer show up if a browser does not support the ckeditor and as ckeditor will be updated in the future, i am closing this ticket.
