### ISSUE TITLE
Add elgg_notify_user()

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5691]
It generates a notification object and then sends it through NoticationsService::sendNotification() - probably by adding a wrapper like sendImmediateNotification() or something since it is protected. The reason is to enable sending immediate notification when we want to send out a single notification (receive private message, friend request, etc.)
- Needs to handle i18n to recipient's language automatically (`notify_user()` requires translated strings)

**Comment by ewinslow** [comment]
@juho-jaakkola do we still need this ticket or can we consolidate somehow?

**Comment by iionly** [comment]
I think it's still needed. Apart from handling the recipients language (both for on-site notifications and email notifications) it might also be useful to be able to define a custom url used for the link of the subject of on-site notifications. Currently (with notifiy_user()) it's not possible in any case to make the subject line a link at all. You can only make the subject line a link if you provide an object in the params array and this only works with entitities of type object. You can't provide a custom url directly at all but the object view is used automatically instead.

**Comment by jdalsem** [comment]
Closing due to lack of attention.
