### ISSUE TITLE
Put all mysql_* calls behind the API

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5703]
This is step towards DBAL.

There several issues:
- [ ] upgrade scripts
- [ ] tests
- [ ] installer
- [ ] Elgg_CacheHandler
- [ ] mod/profile/icondirect.php

Id like all of them to use Elgg_Database methods instead of mysql_* directly, so we could abstract DB layer inside this class only.

**Comment by mrclay** [comment]
Working towards this in #8160

**Comment by mrclay** [comment]
Are we OK using ext/mysql in one more upgrade script (https://github.com/Elgg/Elgg/pull/8204/files#diff-f2d30973364dd8802a8ac699ee66a4eeR11)? /cc @brettp

**Comment by brettp** [comment]
We need to come up with a method that doesn't load the entire result set
into memory when using arbitrary SQL (i.d., not something that can be
ElggBatch'd).

On Wed, Apr 15, 2015 at 8:02 AM, Steve Clay <notifications@github.com>
wrote:

> Are we OK using ext/mysql in one more upgrade script (
> https://github.com/Elgg/Elgg/pull/8204/files#diff-f2d30973364dd8802a8ac699ee66a4eeR11)?
> /cc @brettp <https://github.com/brettp>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/5703#issuecomment-93357157>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by mrclay** [comment]
Option to have get_data() return a row iterator. FC with PDO, but not a full PDO result API. Just Countable and Iterator.
