### ISSUE TITLE
Allow view function that can be resolved with plugin priority

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5705]
Motivation: For rapid customization of sites I plan to create a plugin that allows (more or less) hot swappable "submodules" that consist of one PHP file each.

I can use the "view" hook to extend/replace, but this is only a filter of the completed rendering process. I'd like to be able to programmatically emulate having a view file in my plugin. Ie. This file may be overridden by a later plugin, and if it extends, it may come between other extending views.

I think this leads to views being objects with a render() method.

**Comment by jdalsem** [comment]
You can do this by quick returning in the view_vars hook... or maybe you can do a similar thing with elgg_set_view_location.. nonetheless i do not see we can do anything else here
