### ISSUE TITLE
Add gender field to users table for eventual i18n purposes

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5732]
Gender often changes the inflection of the words we use. E.g. he/she/they for male/female/unknown-n/a-etc. There is no way for us to handle this currently in our i18n. Adding a gender field would be a step in the right direction.

**Comment by hypeJunction** [comment]
With metadata being much simpler now, there is not reason to deal with any more additional attributes. Can be closed.

**Comment by jdalsem** [comment]
Agreed
