### ISSUE TITLE
permissions check hook for metadata uses different hook name pattern

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5753]
For editing a user it is 'permissions_check', 'user'. For annotations, 'permissions_check', 'annotation'. For metadata, it is 'permissions_check:metadata', <entity type>. See ElggEntity::canEditMetadata() and ElggMetadata::canEdit()

**Comment by jdalsem** [comment]
Is this something we want to standardize in 2.0?

**Comment by ewinslow** [comment]
I don't. Rather leave it alone. Naming awkwardness is not a compelling enough reason to break all permissions hooks... :(.

**Comment by ewinslow** [comment]
But others may disagree...

**Comment by jdalsem** [comment]
> Naming awkwardness is not a compelling enough reason to break all permissions hooks

i also agree
