### ISSUE TITLE
Add ability to select container for content

### ISSUE THREAD

**Issue by cash** [Elgg/Elgg#5764]
There would be a select or autocomplete for selecting container for content. The access control would auto refresh based on selection.

This replaces #4873 and #4730

**Comment by hypeJunction** [comment]
This is what I have for discussions. A bit of an overkill: https://github.com/hypeJunction/hypeDiscussions/blob/master/views/default/input/discussions/container.php

**Comment by mrclay** [comment]
Changing container after content exists invites trouble, e.g. access levels on comments/likes, but definitely workable for new

**Comment by jdalsem** [comment]
Keeping the forms as is for now. If needed plugins can easily override the container input. They can have a look at the discussions plugin as an example on how it could be done.
