### ISSUE TITLE
Handle invalid chars in htmlspecialchars()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5790]
http://nikic.github.io/2012/01/28/htmlspecialchars-improvements-in-PHP-5-4.html

Instead of returning empty string on invalid chars, better to use substitution chars on 5.4 and drop them in 5.3.

Low priority.

**Comment by jdalsem** [comment]
@mrclay anything to do for this?

**Comment by mrclay** [comment]
This will be easy now. `htmlspecialchars($str, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');`
