### ISSUE TITLE
Automatically include CSRF tokens in all same-domain jQuery ajax requests

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5814]
It would be nice if we didn't have to wrap libraries' ajax functions with our own in order to support CSRF protection. E.g. jQuery has $.ajax, Angular has $http, etc. but we don't want to have to support two wrappers. Instead, the best practice should be to configure the library to include the tokens automatically. We would do this in core for jQuery, but others could do it themselves for any other JS libraries they want to integrate.

Can anyone think of a reason not to do this? Too magical?

**Comment by mrclay** [comment]
I assume you mean setting up a handler via http://api.jquery.com/ajaxSend/, and the handler would auto-add tokens to /action/ requests. Not a bad idea, but this doesn't seem to be a big source of dev issues.

**Comment by ewinslow** [comment]
Yes that was the idea, but let's not track issues for non problems.
