### ISSUE TITLE
On soft logout, XHR load the login form back into topbar

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5817]
By soft logout I mean when a token refresh request returns that the user has been logged out. https://github.com/Elgg/Elgg/pull/5807/files#L3R43

**Comment by jdalsem** [comment]
token invalid does not mean that a user is logged out... Just refreshing should also suffice in many situations.

**Comment by jdalsem** [comment]
> token invalid does not mean that a user is logged out... Just refreshing should also suffice in many situations.

For this reason i am closing this
