### ISSUE TITLE
Fresh installation fails if settings.php is already present

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#5832]
Tested with master from 2013-07-18.

If the installation is done with settings.php either created manually or still present from a former installation (also 1.9-dev) the installation fails right from the start. My guess is that the installer assumes the database to be already initialized when settings.php exists instead if initializing it using the credentials present in settings.php.

**Comment by oscardo** [comment]
Is only /var/www/html/ for default o (/Your_site/www) allow permitions 770 or 777 
chmod 770 /var/www/html/*

**Comment by iionly** [comment]
Are you asking a question or are you trying to make a suggestion?
@oscardo 
I think the permissions have nothing to do with this issue here. If settings.php is not yet present, the permissions must be set to allow for the webserver to create settings.php during the Elgg installation. But this issue here is about the installation not working as expected (as it worked on older versions of Elgg) if you manually create a settings.php before doing the installation.

Though I have to admit that I haven't tested on 1.12 or 2.X if it maybe works again already (maybe at least on 2.X by chance due to change of location of the settings.php file?).

**Comment by iionly** [comment]
On Elgg 2.0 and newer it works again to manually create settings.php and do an installation with a fresh database. On Elgg 1.8 - 1.12 it's still broken. Nevertheless, I think it's time to close this issue with a "won't fix anymore on Elgg 1.X" as I don't expect anyone is still interested in this issue on Elgg 1.X.
