### ISSUE TITLE
Clean up API for dynamic menus

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5835]
The plugin hooks work, but they're poorly documented and give people too much to learn. We should enable more static registration/unregistration by allowing people to register with factory functions:

```php
elgg_register_menu_item('menu-name', 'menu-item-name', function($params) {
  return array(
    'text' => $params['entity']->getDisplayName(),
    'href' => $params['entity']->getUrl(),
  );
});
```

Then you can always unregister menu items like so:

```php
elgg_unregister_menu_item('menu-name', 'menu-item-name');
```

Rather than like so:

```php
elgg_register_plugin_hook_handler('prepare', 'menu:menu-name', function($hook, $type, $items, $params) {
  foreach ($items as $key => $item) {
    if($item->getName() == 'menu-item-name') {
      unset($items[$key]);
    }
  }

  return $items;
}, 1000);
```

Plugins that just want to tweak a single property on a menu item will have to register for the prepare, menu:menu-name plugin hook, which I think is fine as it will be very rare. I think devs would be more likely to just do this with copy-paste.

**Comment by jdalsem** [comment]
I think the documentation on http://learn.elgg.org/en/2.0/guides/menus.html is good enough as is
