### ISSUE TITLE
More advanced upgrade feature

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5842]
Currently the upgrade page is just a white screen with ajax load spinner and the upgrades are simple script files.

Let's make a new system that has an actual UI which makes AJAX calls to upgrade scripts that give detailed information about the progress of each individual upgrade.

- The page would tell how many individual upgrades need to be run
- The page structure would be as simple and minimal as possible (See also #6232 )
- Each of the upgrades would hold information about their nature:
  - Quick and simple (e.g. add a new column to a db table) or
  - Extensive and time consuming batch upgrades (e.g. migrate 10k+ annotations to entities)
- A progress bar for each of the batch upgrades
- Each upgrade would have it's own success/progress/failure messages that would be displayed to the end user

**Comment by jdalsem** [comment]
Upgrades made simpler with #10118
