### ISSUE TITLE
Support nesting plugins into packages

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5852]
The idea is to allow organizing plugins into tree structure, not only flat one as it happens now. In effect we'd have a way of bundling plugins into groups having the same directory (ie. `mod/package_name/`).

This requires making sure that plugins will work even if it files are not put directly into mod dir. We make several good steps towards that in 1.9

Motivation is to allow bundling several plugins into single package. Possible pros:
* easier deployment of sets of plugins, I can have single repo with multiple plugins and have easy way of incorporating them into project as one as single svn external or git submodule
* forcing some additional dependencies in particular plugins set
* more organized plugins list - tree view? (useful when having hundreds of plugins)

I feel API is slowly going that path, but we didn't have ticket for that.

I imagine two possible implementations:
* package has plugins nested directly in it + manfest.xml that configures additional requirements (plugins order) and holds necessary package data
* package is just a plugin as any, but we add API for pointing paths containing nested plugins (set in manifest or hardcoded, ie. `mod/package_name/plugins/subplugin_name/`)

Assigning as long term.

**Comment by mrclay** [comment]
With the move toward composer plugins, is this still worth effort?

**Comment by ewinslow** [comment]
I think not.
