### ISSUE TITLE
remove_group_tool_option not authoritative enough

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5854]
Calling remove_group_tool_option(...) hides the options when creating a new group, but any options that had default_on = true still show up in already-created groups regardless. This is not intuitive.

/cc @bradmsmith

**Comment by jdalsem** [comment]
This is not true in Elgg 1.9. If you remove the group tool option, it will not show up on the edit form. The functionality  however will still be enabled, but that is another issue.

**Comment by jdalsem** [comment]
related #4812
