### ISSUE TITLE
Make site registration closed by default

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5871]
1. Anti-spam plugins seem like a requirement now for open public registration, and we should recommend that users install some before opening.
2. See [Clyde K's story](http://community.elgg.org/discussion/view/1458505/fighting-spammers). Basically as soon as your site is known to spammers, it's dangerous to have open reg before you can get anti-spam plugins in place.

Granted, reinstalling an established site will probably be rare, but having open reg by default just seems to go against the principle of secure by default.

**Comment by ewinslow** [comment]
Not a BC break so not a 2.0 blocker.

**Comment by mrclay** [comment]
PR #10918
