### ISSUE TITLE
Walled garden page handler

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#5874]
Walled garden mode shows by default an anonymous and boring front page. If I want to present my site with my own front page (and other logged out pages), it is a major project where I need to overwrite several wg files.

It would be nice with an easier solution like a wg page handler.

[Discussed in google groups](https://groups.google.com/forum/#!topic/elgg-development/uZaJmXSgHCo)

**Comment by jdalsem** [comment]
There is a walled garden page handler: 
`elgg_register_page_handler('', '_elgg_walled_garden_index');`

you could register your own for the frontpage with 
`elgg_register_page_handler('', 'my_walled_garden_index');`

only problem is by default the walled garden page handler is registered very late and thus will override your page handlers if it is registered at a normal moment.

Solution:
Create an init function registered after the walled_garden_init (> 1000).

```php
elgg_register_event_handler('init', 'system', 'my_late_init', 2000);
function my_late_init() {
    // optionally check if walled garden
    elgg_register_page_handler('', 'my_walled_garden_index');
}
```
