### ISSUE TITLE
Don't allow entity save with empty owner/container

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5875]
This seems like a usability issue for new devs because such entities can lead to errors during views (particularly owner_guid = 0).

Are 0 valid values for these in any cases? If not, refusing to save would be better than [breaking listing pages](http://community.elgg.org/discussion/view/1425890/add-new-object-subtype-pages).

**Comment by jdalsem** [comment]
Closing this in favor of #6428 as that ticket tackles more then just owner/container
