### ISSUE TITLE
Improve site_notifications UX

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5876]
This issue is about the site_notifications plugin for 1.9.

There is currently no support for displaying site_notifications as either read on unread. The "read" status will always be false and the notification will be deleted instantly when the notification link is clicked.
1. It's not good that a notification is instantly deleted. There may be need to check the notifications later. Instead the read and unread notifications should be displayed for example with different background color.
2. There should be a counter next to the topbar menu icon displaying how many unread notifications there currently are. Also it would be great if the menu item would open a popup that lists the latest notifications.
3. Users shouldn't see an unread notification about a piece of content that they have already seen. So we also need some way to monitor what entities users are viewing.
   - Let's add e.g. a plugin hook 'viewing', 'entity' to elgg_view_entity(). Site_notifications plugin can then hook to it and check whether there is a notification about the entity and set $notification->setRead(true) when needed.

This plugin addresses some of the mentioned issues: http://community.elgg.org/plugins/1156632/1.8.4/notifier

**Comment by jeabakker** [comment]
fixed in #13394
