### ISSUE TITLE
Simplify metadata to string[]

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5889]
Eliminate value_type, owner_guid, access_id, and enabled. Devs can cast to integer as needed. Get `->` always returns the "first" (lowest id) string, set removes all existing values, and a secondary read/write API would be used for arrays (e.g. tags).

Owner/access on metadata makes reliable read/write difficult. If I write and there's an existing value I don't have access to, should it be removed?, etc. In effect metadata may be completely different by users. We don't need this complexity.

**Comment by ewinslow** [comment]
As much as I would love to see this happen, I don't think it can reasonably be done because of the BC issues it would cause...
