### ISSUE TITLE
Support HTTP 206 Partial Content for file downloads

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5891]
It makes sense to have in file plugin, but I'd lean towards having such functionality in core on top of ElggFile to be more general and reusable for plugin devs.

It should help in more efficient handling of big file downloads and continuing interrupted ones.

See example: http://stackoverflow.com/questions/157318/resumable-downloads-when-using-php-to-send-the-file

**Comment by ComputationalComplexity** [comment]
I have been working on this as a plugin, but to no avail I'm afraid. Can't get it to work on all devices... This is a major disadvantage of elgg and it would be nice with more people working to solve it.

**Comment by Srokap** [comment]
I suspect we might have problem with proper multiple ranges handling. Most of examples assume single range request, but there's no guarantee that specific browser or video player won't request multiple ranges. Would need to carefully go through RFC https://tools.ietf.org/html/rfc7233#section-4.1

**Comment by mrclay** [comment]
See https://github.com/Elgg/Elgg/pull/9147. It will use Symfony's BinaryFileResponse, which handles ranges.

**Comment by hypeJunction** [comment]
I have just implemented a video player with video.js and videos are streamed with 206 responses supported by the file serving API. If anyone interested, https://github.com/hypejunction/elgg_file_viewer
