### ISSUE TITLE
Getting notification subscriptions of specific entity (and user)

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5911]
In Elgg 1.9 users can be subscriped to follow an entity using:

``` php
elgg_add_subscription($user_guid, $method, $target_guid);
```

But there aren't yet public functions like these:
1. Check if user has subscriped to an entity

``` php
elgg_has_subscription($user_guid, $method, $target_guid);
$entity->hasSubscriped($user, $method);
```
1. Get all subscripers

``` php
elgg_get_subscripers($entity, $method);
$entity->getSubscripers($method);
```
- Returns ElggUser[]
- Could default to any method if not  given as parameter
  1. Get all subscripers and their preferred methods

``` php
elgg_get_subscriptions($entity);
elgg_get_user_subscriptions($entity, $user);
$entity->getSubscriptions($user);
$entity->getUserSubscriptions($user);
```

 These would basically return the same as Elgg_Notifications_SubscriptionsService::getSubscriptions()

``` php
 array(
     <user guid> => array('email', 'site', 'sms'),
     <user guid> => array('site', 'sms'),
 );
```

Any opinions on which (if any) of these should belong to the core?

cc: @cash

**Comment by jdalsem** [comment]
Resolved in https://github.com/Elgg/Elgg/pull/13408
