### ISSUE TITLE
Eliminate context

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5912]
Context is a nebulous concept that does a bunch of magical things, like making menu items selected. Basically a global variable telling the system "what plugin is handling this page?/what's happening right now?". With Elgg pages often pieced together by the actions of many plugins, this is harder to make sense of and hard to document best practices.

An improvement would be to break this out to multiple stacks with particular (very well-chosen) names that lead to documentation, or figure out better systems for solving these problems.

A simple improvement might be to start using prefixed strings in the context so it's clearer what a particular "context" really means.

(A very low priority issue, but I wanted to document it)

**Comment by jdalsem** [comment]
We do not encourage the use of context features, but we have no plans to actively force devs to get rid of this concept.
