### ISSUE TITLE
Pick a JS framework

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5921]
Current contenders:
 * Ember (http://emberjs.com/)
 * Angular (http://angularjs.org/)
 * Polymer (http://www.polymer-project.org/)
 * React (http://facebook.github.io/react/)

Previous discussion: https://groups.google.com/forum/#!topic/elgg-development/OL8G06isaJU

**Comment by ewinslow** [comment]
Durandal has since been superceded by Aurelia.
AngularJS is soon going to be eclipsed by Angular 2.0

This confirms my suspicion that we should perhaps NOT pick a JS framework and instead just make it dead simple to expose HTTP APIs for all our stuff.

**Comment by ewinslow** [comment]
Closing this. If you disagree, please reopen, but I just have become convinced that we are not going to make progress toward this end any time soon...

**Comment by hypeJunction** [comment]
+1 on investing into API

**Comment by beck24** [comment]
ditto

On Fri, Mar 20, 2015 at 5:13 PM, Ismayil Khayredinov <
notifications@github.com> wrote:

> +1 on investing into API
> On Mar 21, 2015 12:29 AM, "Evan Winslow" <notifications@github.com> wrote:
>
> > Closing this. If you disagree, please reopen, but I just have become
> > convinced that we are not going to make progress toward this end any time
> > soon...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Elgg/Elgg/issues/5921#issuecomment-84193805>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/5921#issuecomment-84201113>.
>



-- 
Matt Beckett
http://mattbeckett.me
Direct Line: (250) 667-0871

**Comment by hypeJunction** [comment]
I have been doing experimentation with Vue.js, in case it is of interest to anyone:
https://github.com/hypeJunction/elgg-vue
https://github.com/hypeJunction/elgg-vue-likes

**Comment by mrclay** [comment]
Great, you've tackled the hard part of allowing plugins to contribute components. Ideally we wouldn't be stuck with AMD loading or could compile to a bundle, but this is a good compromise for now. I guess for now we'd be just dumping any necessary initial state into JSON?

**Comment by hypeJunction** [comment]
I like the idea of having async components - they can be bundled using your combiner, if need be (not sure if it handles text! modules).
By initial state do you mean the state of the Vue app, or the component state?

**Comment by mrclay** [comment]
> By initial state do you mean the state of the Vue app, or the component state?

Everything required to draw the page. Either we ship it in the page or every page has to make a separate Ajax request to finish drawing.

**Comment by hypeJunction** [comment]
It depends how we approach it, both are possible. In my ideal world, we would remove all elgg_list_ functions and offset rendering until after Ajax fetch from a json viewtype. So something like:

```
elgg_register_listing($view); // bootstraps /ajax/listing/$view endpoint
// would be even better if we could just return and instance of ElggBatch instead of using views
elgg_view_listing($view); // renders a component
```
