### ISSUE TITLE
Consolidate delete actions

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5922]
### Goal
- Delete a bunch of duplicate plugin code (fun!)
- Write less plugin code in the future
### Example actions that could be consolidated
- discussion/delete
- discussion/reply/delete
- groups/delete
- bookmarks/delete
- blog/delete
- messages/delete
- thewire/delete
- pages/delete
- messageboard/delete
### system messages

Each content type spits out messages appropriate to the subtype. For example instead of "Can't delete this entity" it would say "Can't delete this blog".

Message keys can instead be generated in a standardized way based on plugin type and subtype.
### forwarding destination

Generally you're forwarded to the listing view of the content you just deleted, but sometimes even this depends on properties of the container.

Instead of in the action, the forwarding destination can be provided as a form parameter. Example:

``` html
<form action="/action/entity/delete">
  <input type="hidden" name="forward" value="/groups/12345">
  <input type="hidden" name="guid" value="56789">
  <input type="submit" value="Delete">
</form>
```

This should be safe because we would already have validated csrf tokens. It also allows the UI more control over the destination (might be context-dependent).
### custom delete logic

Examples:
- pages has to "move" child pages up one level
- groups deletes the avatar from the filesystem

For groups, we could standardize the avatar code to work with any entity and bake it into the unified delete action. We could also just do it in a `before:delete` event.

For pages, it seems like this would have to go in a `before:delete` event.

`before:delete` should only fire when all security checks have passed of course.
### custom permissions checks

Most of these actions check `canEdit()`, but pages is hard-coded to only allow owners and admins

We can use a [new `canDelete` function](https://github.com/Elgg/Elgg/issues/2975) or equivalent so that this can be customized at the plugin-hook level instead of hard-coded into the actions.

**Comment by hypeJunction** [comment]
Here is the code I currently use:

```php

$guid = get_input('guid');
$entity = get_entity($guid);

if (!$entity instanceof ElggEntity) {
	register_error(elgg_echo('entity:delete:fail'));
	forward(REFERRER);
}

if (is_callable(array($entity, 'canDelete'))) {
	if (!$entity->canDelete()) {
		register_error(elgg_echo('entity:delete:fail'));
		forward(REFERRER);
	}
} else if (!$entity->canEdit()) {
	register_error(elgg_echo('entity:delete:fail'));
	forward(REFERRER);
}

set_time_limit(0);

// determine what name to show on success
$display_name = $entity->getDisplayName();
if (!$display_name) {
	$display_name = $entity->guid;
}

$container = $entity->getContainerEntity();

if ($entity->delete()) {
	// determine forward URL
	$forward_url = REFERRER;
	$referrer_url = !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
	if ($referrer_url) {
		$segments = explode('/', parse_url($referrer_url, PHP_URL_PATH));
		if (in_array($entity->guid, $segments)) {
			// referrer URL contains a reference to the entity that will be deleted
			$forward_url = ($container) ? $container->getURL() : '';
		}
	} else if ($container) {
		$forward_url = $container->getURL();
	}

	system_message(elgg_echo('entity:delete:success', array($display_name)));
	forward($forward_url);
} else {
	register_error(elgg_echo('entity:delete:fail'));
	forward(REFERRER);
}
```

**Comment by hypeJunction** [comment]
Made it into a plugin, as I am done writing delete actions in my life: https://github.com/hypeJunction/Elgg-actions_delete

**Comment by hypeJunction** [comment]
We can do this with #9215.
@ewinslow @jdalsem @juho-jaakkola Re: the discussion we have had at ECI, I have double checked permissions and there is no issue.

**Comment by jdalsem** [comment]
Security issue still exists... will inform security@elgg.org

**Comment by jdalsem** [comment]
a lot of custom delete actions have already been moved to the generic delete action as the generic delete combined with events can almost tackle all situations. Not going to keep this broad ticket open until everything is moved
