### ISSUE TITLE
Remove twitter_api from core

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5927]
For discussion.

I don't think it makes sense to bundle this integration with core. We don't bundle any third-party API plugins, and we can easily distribute it as the officially "blessed" version without bundling it with the rest of core.

**Comment by jdalsem** [comment]
assigning this to 2.0 so we can easily pull it out

**Comment by ewinslow** [comment]
Sweet

**Comment by ewinslow** [comment]
What I want to avoid is having to sync fixes from this repo to the individual plugin repos or something like that. I think we should:
* merge everything from 1.9 up through to master
* extract twitter_api to its own repo from master
* delete twitter_api from 1.9 (security releases promised through Jan 2016, so it's possible we would need to update 1.9) and include it via composer instead.
* merge this change up through to master

If that goes smoothly I think we should just do it for the rest of the plugins as well. I feel it would be a much cleaner move to be completely composer-managed if we did not bundle any elgg plugins with core... but that's a separate ticket...

**Comment by mrclay** [comment]
Too late for 2.0

**Comment by jeabakker** [comment]
rel #10799
