### ISSUE TITLE
Expose DI system to plugins

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5930]
**Goal:**
- Make it possible for plugins to write highly testable code

**Requirements:**
- Standard way to inject existing services
- Plugins can provide new services that other plugins can inject
- Prevent plugins from overriding certain services

**Existing work/inspiration:**
- Angular's DI system (services, filters, directives, controllers)

**Comment by jdalsem** [comment]
Core has enough features for this at the moment
