### ISSUE TITLE
Add some introductory block/widget explaining features on the page

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5937]
It could be very similar to widget in admin panel, but I imagine it as element extendable by the plugins (plugin hook?) so each plugin could (optionally) add few words about its features.

It would help in explaining new users specifics of the page and introduce existing naming convetions (even if page owners decide to use own translations). See https://github.com/Elgg/Elgg/issues/5923

I imagine it as roughly sth like that:
```
Welcome User1!
You'll find here several ways to communicate and share your thoughts:
* Blog - The best way to share longer bieces of content
* The Wire - A microblogging system to let others know what you're up to

etc.
```
It sounds like a natural part of custom_index plugin, just below welcoming title.

**Comment by ewinslow** [comment]
I don't see us creating something like this out of the box. I'm fine with supporting the use-case via plugins, but Elgg is so customizable that I don't want to have to design a help system that won't break as soon as someone writes a naive theme that hasn't taken these tours into account.

I think our time is better spent making Elgg more usable in the first place.
