### ISSUE TITLE
Support scheduling posts

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5943]
### Goals
- Avoid bursts of content and dry spells
- Target time-of-day for highest reach to target audience without having to be at a computer at that time.
- Allow for a review period before content goes live
### Requirements
- Scheduled content should never show up in normal feeds
- Can set publish date to some point in the future
- Content owners and site admins should still be able to view scheduled content
### Design

My first thought is that I think we can achieve this most simply by:
- Denying access to content for which `time_created` is set in the future
- Changing the default value of `created_time_upper` in `elgg_get_entities` to `time()`. This allows owners and admins to see the scheduled posts when specifically requested.
### Potential problems

Syndication of published content often works with "push". But there is no event triggered when scheduled posts get published, so you can't ping external sites (e.g. blog=>community cross posting).
### Alternate design
- Disable scheduled posts.
- Set `disable_reason` to `"scheduled"` (or something)
- Set `time_created` to target publish time
- Have cron running that queries for scheduled posts and publishes them if current time is after target publish time (firing all the appropriate events).
- Change `create_time_upper` to default to `time()`

**Comment by jdalsem** [comment]
This can be handled with a plugin like https://github.com/coldtrick/blog_tools
