### ISSUE TITLE
Add hook to getDisplayName and add to ElggEntity

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5965]
Comment objects have no title/name, so when you need to draw a breadcrumb to one, the URL goes to the container, but getDisplayName is empty. Two ideas:
1. in ElggComment, override getDisplayName so it returns getDisplayName of the container entity (assuming the container is an ElggObject because regular entities don't have getDisplayName()).
2. Add getDisplayName() to ElggEntity and have it fire a plugin hook, passing the entity into $params.

This would essentially allow this method to become a sort of __toString(). Each entity could always have _something_ to use as link text, and plugins could change this dynamically based on needs. E.g. I have a proxy object for each user. I want the title of this object to show as "Foo for User Name", but if I set that in the DB, it can get out of sync.

**Comment by jdalsem** [comment]
getDisplayName is part of ElggEntity and usecases for a hook can also be solved by extending classes, so closing this issue
