### ISSUE TITLE
Possibility to uninstall plugin data

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#5966]
Let's make it possible to uninstall all plugin data (both in database and in data folder) by clicking an Uninstall button in the plugin list.

**Uninstalling a plugin could include deleting the following data:**
- The objects created by the plugin
- Subtype from dbprefix_entity_subtypes table
  - Especially annoying because of the visible "item:object:my_plugin_subtype" string
- Plugin usersettings
- Relationships created by the plugin
- Any additional data folder data that isn't deleted automatically along the entities created by the plugin

**There could also be a page that would first display a summary about the data to be deleted:**
- 2104 entities of type: object/blog
- The object/blog subtype
- Plugin usersetting "elgg:blog:my_blog_setting" for 135 users
- The folder whatever_blog_cache_files in data folder
- etc.

Deleting a lot of data like this is dangerous but let's start working on this so that plugins in the future will have their data saved using best practices so that plugin uninstallation won't touch any data that doesn't belong to the plugin.

**Comment by jdalsem** [comment]
We chose to only add a feature to remove plugin (user)settings for now.
