### ISSUE TITLE
Hide more stuff if profiles plugin is disabled

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5967]
* Disable edit profile page and link in user settings
* Remove friends listings pages, icon in topbar
* Remove anchor from topbar user icon

I don't know if some of those should be tied to other plugins, but if disable every plugin, I think these shouldn't be available. Goal is to be able to strip Elgg down to simple user management.

**Comment by jdalsem** [comment]
> Remove friends listings pages, icon in topbar

This should go to a friends plugin #7874 



> Disable edit profile page and link in user settings

Don't like the suggestion as the profile plugin now only provides a front for displaying profiles and does not control any edit features what so ever (for example the default profile fields also come from core). Leaving this as is, will allow plugin devs to just provide a new front for profiles and not mind the edit stuff.



> Remove anchor from topbar user icon

I would only move the topbar menu item registration to the profile plugin. Making a PR for that.

**Comment by jdalsem** [comment]
Closing this as everything this issue mentioned has been moved to the profile plugin, or has been commented on.
