### ISSUE TITLE
Consolidate create actions

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5970]
This is related to #5922, but might be trickier.

Thoughts:
- Would likely require designing a whole new plugin-friendly way to define entity property validation rules outside the action (required, minlength, maxlength, text/email/url/etc.). Probably a good thing to do anyways.
- Some content types are very different (blogs have drafts, pages have revision history, etc.). Could be an opportunity to unify how we handle this across subtypes.
- Will need to anticipate more than just core content types so that other plugins could use this rather than creating their own actions. In particular, will need to handle arbitrary metadata fields.
- How to handle file uploads?

For field-validation, I'm thinking some kind of HTML5-inspired static configuration:

``` json
{
  "object:blog": {
    "properties": {
      "title": {
        "type": "text",
        "required": true
      },
      "// defaults to not required, type 'text'",
      "summary": {
        "maxlength": 150
      },
      "description": {
        "type": "html",
        "required": true
      },
      "comments_on": {
        "required": true,
        "options": ["yes", "no"]
      },
      "access_id": {
        "type": "access"
      }
    }
  }
}
```

**Comment by jdalsem** [comment]
This will be solved as part of #6760
