### ISSUE TITLE
remove_entity_relationships() does not trigger events

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5988]
I'd think it should build an array of `ElggRelationship`s, call the event on each. For those that return true, generate a list of IDs and delete using a query with `IN ()`.

**Comment by mrclay** [comment]
See https://github.com/arckinteractive/Roles/pull/20/files

**Comment by mrclay** [comment]
@hypeJunction thoughts on the proposal in the description?

**Comment by hypeJunction** [comment]
That could work.

**Comment by beck24** [comment]
Makes sense to me

**Comment by jeabakker** [comment]
Implemented a fix the make the events trigger during most operations, just not when we're deleting a complete entity because than all tables are cleaned.
