### ISSUE TITLE
Replace add_entity_relationship with elgg_create_entity_relationship

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5992]
Goals:

* Change API to return ElggRelationship or null
* If already exists, just return existing ElggRelationship (currently returns false in this case)
* Keep BC of the "create", $relationship_name event
* name prefixing
* This becomes a usable replacement for passing null to the constructor (#5991)

**Comment by jdalsem** [comment]
Something to take on for 2.0?

**Comment by mrclay** [comment]
Rather wait and see how lists affects relationships.

**Comment by ewinslow** [comment]
Closing this. Let's just throw our eggs in the lists API basket. Either way I'm not going to be able to approve a new global function as suggested in the title.
