### ISSUE TITLE
Make "discussions" its own plugin

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#5994]
I think we've discussed this before but never wrote it down.

There are use-cases for having discussions independent of groups. For example:
 * A site wants to just allow people to post discussions but to no particular group
 * We want to allow plugin projects to be containers for discussions on the community site

If anyone from outside the core team wants to take ownership of this plugin, I'm willing to let you extract it from core entirely and release it separately (as the official discussions/forum plugin), though we'd have to clear that approach with the rest of the team probably.

@juho-jaakkola, @jdalsem -- any takers?

**Comment by jdalsem** [comment]
Done in https://github.com/Elgg/Elgg/commit/a4e484e62db117531763c0487c4b04c098bfb909
