### ISSUE TITLE
Stop using user emails in SMTP From field

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5999]
Improper use of it, cause not delivering emails at all (ie. when sender domain has strict SPF policy) or [sending them to spam](https://support.google.com/mail/troubleshooter/2411000).

I think we should choose from **(solution A)**:
```
From: site@email.com
Reply-To: internal_author@address.com
```

Or **(solution B)** follow the case [A.2.2 from RFC 822](http://tools.ietf.org/html/rfc822#appendix-A.2.2)
```
George Jones logs in as Jones on his  host.   His  secre-
tary,  who logs in as Secy sends mail for him.  Replies to the
mail should go to George.
     
From:    George Jones <Jones@Group>
Sender:  Secy@Other-Group
```

All RFCs are consistent that:
```
In all cases, the "From:" field SHOULD NOT contain any mailbox that
does not belong to the author(s) of the message.  See also Section
3.6.3 of RFC 5322 [RFC5322] for more information on forming the
destination addresses for a reply.
```
- http://tools.ietf.org/html/rfc5322#section-3.6.2
- http://tools.ietf.org/html/rfc2822#section-3.6.2
- http://tools.ietf.org/html/rfc822#section-4.4.2

SPF RFC parts:
- http://tools.ietf.org/html/rfc4408#section-2.2
- http://tools.ietf.org/html/rfc4408#section-3

I'm leaning towards solution A.

**Comment by ewinslow** [comment]
I don't think we include user emails in outgoing notifications anymore, since that would actually be a privacy violation. Closing this as obsolete.
