### ISSUE TITLE
need for extra information in elgg_view_menu

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#6050]
in the prepare hook of elgg_view_menu, the original menu items (from register) are missing.

If you want to redraw a menu with different sorting (eg filter menu sorted by "text" you can't do this by the prepare hook.

Please add the original menu items to the params in https://github.com/Elgg/Elgg/blob/master/engine/lib/views.php#L636

**Comment by jdalsem** [comment]
with the menu vars hook this issue is now resolved
