### ISSUE TITLE
Reported content: simpler Ajax form

### ISSUE THREAD

**Issue by acracia** [Elgg/Elgg#6082]
When a user wants to report any content/user for spam or abuse, after clicking in 'report this' they get directed to a new page with a complete edit form.

i feel when reporting for spam i dont need a whole edit window with the ability to write code and html to report something like spam

It will be much lighter for the server and easy to report with a small window overlayed and a set of options: spam/abuse/other for example, that appear when i click on 'report this'

This suggestion has a low priority.

**Comment by jdalsem** [comment]
Was fixed with #7731
