### ISSUE TITLE
Document all elgg_get_config() options in core

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6099]
Right now we have tons of these, most are not documented, and we have no formalized way to say which are part of the public API and can be freely altered by users.

**Comment by jdalsem** [comment]
I think we only need to upgrade that file to a RST file and add it to the documentation appendix and we are done i think

**Comment by jdalsem** [comment]
@mrclay can you help with this as you recently check all config parameters you should now know what they are used for and which should be kept private

**Comment by jdalsem** [comment]
The Config class has most of the variables documented and commented. The config values that we might be missing are hard to find... will add them if we find them in the future
