### ISSUE TITLE
Add way to document hooks/events in manifest.xml or programmatically

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6111]
The Tools : Inspect page can only present a dull list of hooks/events that have handlers registered at boot time. We need to be able to document these _in the source_, and not rely on keeping documentation up to date.

**Comment by jdalsem** [comment]
this can also be extracted from elgg-plugin.php

**Comment by jdalsem** [comment]
I see no reason to put any effort in this. Function documentation could document what a hook/event listener does... Plugin documentation need to describe available triggers
