### ISSUE TITLE
Group edit scalability

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#6113]
At some point in recent versions a feature was added to transfer group ownership in which a dropdown is populated with the names/usernames of every member in the group.  This is done using ElggBatch but even so with a group of more than 400 users I'm getting OOM errors.  I imagine there are more populous groups out there too.
Additionally, the usability of a dropdown menu decreases with the number of options, at ~400 it's pretty unusable.

I've fixed this in a plugin by using a custom userpicker in its place.  Though core doesn't have a userpicker with a custom callback that I'm aware of.

Though I'm not usually a proponent of 'pull this plugin into core' I do really like how this is working: https://github.com/hypeJunction/elgg_tokeninput

**Comment by jeabakker** [comment]
@hypeJunction i like your idea but what with a group of 400+ users, how do you find the correct user as there is no search option on that page?

**Comment by hypeJunction** [comment]
I guess that is a separate issue. All I am suggesting is to sniff for page owner and add a link to transfer ownership to menu if the page owner is a group and user is a member.

**Comment by beck24** [comment]
I agree, if you can't find someone because the population is too big then the UI is failing
