### ISSUE TITLE
Add option to increment/decrement to API that's atomic SQL query

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6119]
I wast thinking about it several times. It would simply do `UPDATE table SET val = val +1 WHERE ...` and would be safer in case of concurrent increments (ie. many likes occuring in parallel kept as simple counter). Right now if we did `$entitiy->val = $entitiy->val + 1`, it could lead to loosing some of the likes.

It makes sense as Elgg sort-of resembles elements of no-sql storages and they often support incrementing as separate operation to typical get/set (ie. memcache or redis).

See #4268

**Comment by jdalsem** [comment]
Leaving this as is
