### ISSUE TITLE
Generalize entity icon system

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#6152]
Currently we have the config "icon_sizes" with an array of icon sizes and some extra attributes. We are also allowed to change this, and add new stuff. Unfortunately we still have to store all these icons ourselves.

I would suggest a more generic mechanism where entity icon storage is taken care of by core. This would require some helper functions for the Entity class, like `$entity->saveIcon($icon_data)` or `$entity->saveIconFromUploadedFile($file_name)` but also `$entity->removeIcon()`. This could replace all existing icon storage like for instance in the core account or group plugin. And this makes it easier for plugin authors to add this feature to their plugins (like in ColdTrick/blog_tools). It would also be great to have a generic view handling the entity icon.

Besides generalized handling of storage and viewing, i also opt for an extension of that functionality with the feature that if you request an icon size that does not have the image stored on disk (for example a new thumbnail size), it will generate the thumbnail if there is a config in the "icon_sizes" array. That way you can easily change it from withing themes or update your plugins without much problems with icon_sizes.

Any ideas? Elgg 1.10?

### URLs cacheable by proxy caches

Background: http://community.elgg.org/discussion/view/1281934/elgg-and-cloudflare-optimizing

### Multiple different icons per entity

For example, avatar + cover photo on a user.

### Uploading + serving various image formats

 * Progressive JPEG: http://community.elgg.org/discussion/view/1162289/progressive-jpegs
 * Transparency: https://github.com/Elgg/Elgg/issues/2648
 * Webp: https://developers.google.com/speed/webp/

### Use a third-party OO manipulation library

We don't want to have to reinvent the wheel here...

### Skip Elgg engine for image content request

I'd like there to be a way to link directly to the thumbnails without going through page handler, for performance. This should work even for private images by generating secret-enough urls.

**Comment by hypeJunction** [comment]
Some ideas:
* Deprecate 'icon_sizes' config in favor of a plugin hook 'entity:icon:sizes',$type that passes 'type' and 'subtype' as parameters (not sure if we actually want to allow per-entity icon sizes)
* Implement an abstraction layer for image manipulations, so we can easily integrate Imagine, Zebra etc.
* Do not expect jpeg. We should be able to store and handle other image types

**Comment by ewinslow** [comment]
Do we need an abstraction layer or should we just use `Imagine`? So far we've been introducing abstraction layers, but even that is a bit of work. The nice thing is that we aren't then beholden to our dependencies' APIs, but how valuable is that, really?

**Comment by brettp** [comment]
I was thinking the same thing about Elgg\Filesystem\*. I understand the
lure of abstraction, but I'd rather use 3rd party libs in earnest instead
of Elggifying them.

On Sun, Mar 22, 2015 at 10:32 PM, Evan Winslow <notifications@github.com>
wrote:

> Do we need an abstraction layer or should we just use Imagine? So far
> we've been introducing abstraction layers, but even that is a bit of work.
> The nice thing is that we aren't then beholden to our dependencies' APIs,
> but how valuable is that, really?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/6152#issuecomment-84760452>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by ewinslow** [comment]
I think the issue ends up being that as soon as the library falls short of
what we need we'll end up elggifying it anyways (since that's the best way
to avoid reinventing the wheel while also providing the level of
abstraction and API you need.

That's what happened with Gaufrette... E.g. I wanted to get collection
objects back so I could do things like call ->map on them. I wanted single
File objects for the views system refactor, etc.

**Comment by jdalsem** [comment]
i wanted to make this my hackathon task

**Comment by brettp** [comment]
>  That's what happened with Gaufrette... E.g. I wanted to get collection
objects back so I could do things like call ->map on them. I wanted single
File objects for the views system refactor, etc.

It's a nice feature, but is that something we really _need_? 

I think some of this is learning to work within the vendor libs' constraints and with upstream to get features in. Heavy use of 3rd party libs is still a newish concept for Elgg devs. Wrapping APIs isn't re-inventing the wheel, but it sure is repainting the car.

**Comment by ewinslow** [comment]
Sgtm - my advice remains: focus on the api, documentation, and requirements. Don't bother putting a bunch of effort into implementing until we have those really nailed down. If you wanted to do those before the hackathon, that'd be fine too, then you can implement during hackathon.

**Comment by jdalsem** [comment]
removing this from the 2.0 roadmap as it is not a blocker...

**Comment by hypeJunction** [comment]
See #9636

**Comment by hypeJunction** [comment]
I think most of this has been resolved. If something is outstanding, please open new issues.
