### ISSUE TITLE
Members plugin should show members

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#6156]
Currently the members plugin says it shows the 'members' of your site. However all the functions used show all the user in the system.

Since Elgg (in theory) is multi site, this conflicts.

I would like to make the members plugin an actual members plugin (so relationship = 'member_of_site'). When I do this some functions can be depricated as they no longer serve any purpose
- get_number_users (https://github.com/Elgg/Elgg/blob/master/engine/lib/statistics.php#L71)
- get_online_users (https://github.com/Elgg/Elgg/blob/master/engine/lib/statistics.php#L103)
- find_active_users (https://github.com/Elgg/Elgg/blob/master/engine/lib/users.php#L352)

When doing this some admin pages/widgets also need to be changed

**Comment by jdalsem** [comment]
Dropping the member of site relationship is further discussed in #10473
