### ISSUE TITLE
File plugin should be using default icon_sizes

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#6181]
The file plugin uses its own icon_sizes. I think it should be nice if it uses also the default icon_sizes array, so themers have all thumbnail sizes available when changing look and feel of the file plugin. If the extra sizes for file are still required, the could easily be added.

Unexpected behaviour by using other thumbnail generation example here #6168

This change could best be combined with https://github.com/Elgg/Elgg/issues/6152 so there is no issue when introducing new icon_sizes for files that already have thumbnails generated.

**Comment by hypeJunction** [comment]
See #9636 and #9608. How do we transition if at all?

**Comment by hypeJunction** [comment]
Moving this to 3.0 milestone, let's just run an upgrade script and normalize all sizes.
