### ISSUE TITLE
Admins can create content with another user as container

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6186]
E.g. user Admin browses to "John's files", hits "Upload a file" and the result is a file contained by John (shows up in "John's files") but cannot be edited by John because Admin owns it. This is likely to confuse users at the least and probably cause other problems because the system is designed under the assumption that when container_guid is a user, that user is also the owner.

I would call this a bug, with the fix being to hide the "add content" buttons if the page container is a user and not the user logged in.

I assume this is in 1.8, too.

**Comment by jdalsem** [comment]
Current implementation works fine
