### ISSUE TITLE
Allow arbitrary attributes in menu items/links

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6191]
E.g. I need to customize a lightbox link but there's no way I can set data-colorbox-opts on the link. In general it would be handy to set arbitrary attributes on either the LI or the A/SPAN.

(For now I can make an item was href = false and pass in custom markup as the text, but this is not a great solution)

**Comment by jdalsem** [comment]
Function docs state that attributes end up in the menu item 
https://github.com/Elgg/Elgg/blob/master/engine/lib/navigation.php#L91
