### ISSUE TITLE
Always check if user is allowed to write to container

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#6192]
Some of the bundled plugins never check if user can_write_to_container() which causes a fatal error. (E.g. when trying to create content inside a group they're not members of).

Instead they should be forwarded and given an error message.

Affected plugins:
- Bookmarks
- File
- Pages

**Comment by jeabakker** [comment]
In `ElggEntity::save()` a check is done for `can_write_to_container()`. So save fails if not allowed, you can act on that (like the core plugins do).
If you wish to add a better error message than 'save failed' you can check before if  `can_write_to_container()` would fail and show a better error message.
