### ISSUE TITLE
Add option to trace plugin hooks/events execution behavior

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6210]
The idea is to be able to ie.

- see which callback caused the permission_check result to change
- react to the problems during plugin initialization
- profile plugins

Could achieve it by allowing to register some additional callbacks:
- before next handler
- after handler (could make it the same with the first one)
- exception handler (allowing to handle or just catch exception from the handler and ie. disable plugin failing on init event)

Most useful would be monitoring permissions computation. I'd gladly hear better solution. Maybe some option to implement handlers service in own way for selected events only?

I'm worried about performance though.

**Comment by jdalsem** [comment]
With the ability to inspect hooks and events in the developer tools we have enough developer tools on site. IDE's and debuggers will help you the rest of the way. Not worth putting it in Elgg.

**Comment by hypeJunction** [comment]
I would still like to know which handler changes permissions, it's always a game of hide and seek
