### ISSUE TITLE
XHR requests should get JSON for fatal errors

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6228]
E.g. use elgg.action() for an ajax action that has a fatal error. The response is the typical HTML page, so nothing is shown to the user.

**Comment by jdalsem** [comment]
this is impossible to do as we do not standardize results from actions. If someone chooses to exit in an delete action for example catching this is impossible. Also fatal errors do not result in correct error codes to be caught by an ajax error handler.

See also #5134

**Comment by jdalsem** [comment]
what is your idea @mrclay ?

**Comment by mrclay** [comment]
I'm suggesting to adjust the exception handler to detect XHR, and if so, maybe send a simple `{"exception":"..."}` that would be caught by elgg.action()

**Comment by jdalsem** [comment]
impossible as ajax calls could do a exit

**Comment by mrclay** [comment]
If they successfully get to the exit(), then there's no problem to report.

**Comment by jdalsem** [comment]
oh i was too quick on the trigger, but that would means it can only work with an exception handler... still fatal errors will not be caught...

**Comment by mrclay** [comment]
Yes, but that's PHP's (current) limitation. There are RFCs to make more exceptions catchable.

**Comment by mrclay** [comment]
The most common exception I hear of is calling methods on null/false (e.g. assuming get_entity() returned an entity). If that can't be handled, then there's probably no point to this.

**Comment by jdalsem** [comment]
okay, so the exception handler detects a elgg_is_xhr() and then returns an ErrorResult with the exception message as the error message?

**Comment by mrclay** [comment]
I'm thinking the exception handler would detect elgg_is_xhr(), and if so just send a JSON response and exit.

**Comment by jdalsem** [comment]
why not a ErrorResult? that will already be caught by elgg.action

**Comment by mrclay** [comment]
OK, yes. I didn't know ErrorResult was an established response type.

**Comment by mrclay** [comment]
Where is this handling code in js/lib?

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/blob/1.10/js/lib/ajax.js#L201

**Comment by mrclay** [comment]
Thx. I'm thinking in these cases elgg.action should *not* continue to call the `custom_success` handler. Effectively, this response means we can't guarantee anything on the server happened. It should probably trigger the error handler you've added here: #7853

**Comment by mrclay** [comment]
...but allow the exception message to be shown to the user, not just the generic language.

**Comment by jdalsem** [comment]
if the exception is having a 404 header the generic function (from #7853) is already catching it i think. We could still check the body for valid json and check for the exception text being available like you suggested.

**Comment by mrclay** [comment]
Right, I think we'd be sending a 5xx response code with the JSON.

**Comment by mrclay** [comment]
PR #8362
