### ISSUE TITLE
Better support taxonomies

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6237]
Currently taxonomies like tags/categories piggyback on the metadata system, but metastrings are reused widely, leading to limitations like #6236. Essentially we need for each taxonomy to have its own isolated storage. I see a couple solutions to this.
1. We store entries as object/hashtag and use relationships to bind them to entities. This eases the use of tag descriptions, and allows access-controlled tags, etc. but also adds a ton of complexity to taxonomies and, of course, would involve rewriting & migrating our existing tag/categories solutions. I.e. serious BC costs and potential for a lot of unwanted complexity (how do you make sure with an access-controlled taxonomy that users can't create entries with the same name?)
2. We namespace metastring storage by usage. The metastrings table gets an additional column taxonomy_guid (default 1), and we slowly add the ability to specify taxonomy_guid into the API where useful. E.g. to implement categories, we make a global entity to represent categories and always use that GUID when manipulating categories. Within that safe namespace, metastrings could be trivially renamed/deleted without impacting other systems. Notice that this would not at all impact the querying/metadata cache functions, since metastring IDs are still unique.

**Comment by jdalsem** [comment]
Improving the taxonomies features might still be useful, but is not getting any attention at the moment. A new issue will be created when there is renewed interest/activity related to these features.
