### ISSUE TITLE
Support migrating a site from http to https

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#6273]
When a site owner wants to switch to https, it is hardly possible unless you do this upfront. All existing content which has http external content embedded will not be displayed. Like videos, graphics (loaded with http) 

This is a feature request. I am not sure it is fully possible, since we do not know which external sites do and do not support https. But youtube, google, facebook and offcourse the site itself does. Maybe it could be a setting, which urls to rewrite.

**Comment by mrclay** [comment]
Just a note we've dropped login-over-HTTPS for 2.0 #8318

**Comment by jdalsem** [comment]
Elgg is not going to provide something in core for this. Migrating from http to https is relatively simple and can be done with some db scripts to update urls in the database and some server configuration. It is possible to create a plugin if you think this needs to be done more frequently.
