### ISSUE TITLE
Provide way of short-circuiting egef_* functions when we know that result will be empty

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6277]
It's sometimes handy to mark during constuction of options that result set will be empty. So far I've seen solutions like `$options['wheres'][] = "1 = -1";`, which are inefficient as they hit DB. [We have such cases in the core](https://github.com/Elgg/Elgg/blob/cfdaea89172b0cefa09a5f6ec35fba7dfe3fb00b/views/default/page/elements/comments_block.php#L49)

Idea is to introduce some kind of marker in options, hat we could use instead. That is especially useful then constructing query options in many steps ie. directly i a view. I was using similar mechanism myself most often as replacement of `A IN (B)` operator when B set was empty and wanted to get empty result set as well.

If course one could redesign it's code to just return empty set during query construction, but I think it would just add boilerplate code in some cases.

**Comment by jdalsem** [comment]
currently we do not use this trick anywhere in core. I also see no other use for having a feature that returns an empty set
