### ISSUE TITLE
image assignment as 'last_forward_from'

### ISSUE THREAD

**Issue by keviocastro** [Elgg/Elgg#6278]
In ElggSite->checkWalledGarden() is assigning to 'last_forward_from' url of an image group.

image: http://mysite/groupicon/1512/tiny/1385988683.jpg

Code snippet:
```php
if (!$this->isPublicPage()) {
    if (!elgg_is_xhr()) {
        $_SESSION['last_forward_from'] = current_page_url();
    }
    register_error(elgg_echo('loggedinrequired'));
    forward();
}
```

**Comment by jdalsem** [comment]
i believe this behaviour is no longer present in Elgg
