### ISSUE TITLE
embed: support links from the links plugin as embed objects

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#6283]
being able to reference links in pages/blogs is a useful feature for cross-referencing..
adding the ability to embed links via the embed plugin could provide that..

e.g. a list of available (searchable) links is provided via an embed menu/option and then that link is added to the current page - ideally with the option given to insert at the current cursor location or in a specific css / div area at the end of the document with a title such as 'sources' or 'links'.

**Comment by jdalsem** [comment]
We have something like this created in this plugin https://github.com/ColdTrick/embed_extended

**Comment by jdalsem** [comment]
This smells like something for ECML. Closing this ticket for now.
