### ISSUE TITLE
Member alphabetical sort order

### ISSUE THREAD

**Issue by spatialed** [Elgg/Elgg#6321]
Add a tab to all member lists to sort them alphabetically. For example:
-Sort site members alphabetically
-Sort friends alphabetically
-Sort group members alphabetically

**Comment by jeabakker** [comment]
> Sort group members alphabetically

was fixed in 25929426871cc09d81b0612b239e9ea025bc808c

**Comment by jeabakker** [comment]
> Sort friends alphabetically

fixed in 298df35167f59ef220bc1022b7750f8d7651e6c1
