### ISSUE TITLE
CSS behaviour on <p> should only apply on <p>'s in elgg-output

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#6333]
Elgg adds default margins to paragraphs `<p>` in the typography css. I believe this should be changed to apply only to `.elgg-output` which is the class used by the `output/longtext` view, which is used to display content (like in blog).

If agreed i can provide a PR

**Comment by jeabakker** [comment]
fixed with 55b094bed7041220435b6c974101188cb7f186bf
