### ISSUE TITLE
Warn site owners when not loading site from sites_entity URL

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6354]
When migrating a DB site owners sometimes forget to update the URL in sites_entity, or they might try to access the site via IP/a different protocol/port. The result can be broken sessions/scripts/CSS.

It would be nice if we could catch these scenarios and insert a brief error message/link at the top of the document that explains the situation.

Plan: Detect this server-side and send vanilla JS code to check this client-side before showing the message. I guess my only worry here is for site owners that might run Elgg behind a proxy and so relying on PHP alone might yield false positives.

**Comment by jdalsem** [comment]
our documentation describe the steps to migrate... if you forgot a step... too bad :)
