### ISSUE TITLE
Warn about open_basedir when data directory not found

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6370]
See http://community.elgg.org/discussion/view/1587396

http://lu1.php.net/manual/en/ini.core.php#ini.open-basedir

**Comment by jdalsem** [comment]
Troubleshooting install guid is already mentioning open base dir setting as a potential problem regarding the dataroot. http://learn.elgg.org/en/stable/intro/install.html#troubleshooting

The issue is too specific to do more i think.
