### ISSUE TITLE
Trigger notification prepare hook from notify_user()

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#6372]
The 1.9 notifications system has two hooks:
 - 'prepare', "notification:$event_description"
 - 'send', "notification:$method"

The ```notify_user()``` function has only the latter. Let's trigger also the prepare hook  from it so plugins can modify the notification message.

**Comment by jdalsem** [comment]
@juho-jaakkola is this by any chance already done?

**Comment by juho-jaakkola** [comment]
No

**Comment by ewinslow** [comment]
What is the status on this?

**Comment by jdalsem** [comment]
Fixed in #10139
