### ISSUE TITLE
Use PHP-DI for our dependency injector

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6387]
http://php-di.org/
- Seems mature
- Has the features I expect from a DI system
- I like the roadmap for its 4.0.0 release
- DI-only, so doesn't tie us to any other framework
- Seems flexible enough to be able to inject classes from other frameworks
- The less code we have to maintain the better.

**Comment by ewinslow** [comment]
This is something we can do under the hood during 2.x, but we don't have to hit it in 2.0 necessarily.

**Comment by jeabakker** [comment]
fixed in #11674

**Comment by jeabakker** [comment]
maybe not fixed yet, but PHP-DI is available also for plugin devs

**Comment by jdalsem** [comment]
Not going to put in any work soon.
