### ISSUE TITLE
input/plaintext is lossy if the existing value contains HTML

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6394]
Since we use htmlspecialchars' 4th arg to not double encode entities, if your content is like `& becomes &amp;`, that's going to get converted to `& becomes &` when you display it back in the input.

It would be a good idea to include comments justifying the use of the 4th argument in places we do because it creates an opportunity for data loss and user confusion.

**Comment by jdalsem** [comment]
besides input/plaintext do you have other places in mind? if not this could be fixed with a simple PR am i right?

**Comment by mrclay** [comment]
I don't actually see a fix for this. Early on in the projects Elgg needed to have specified different handling for ["raw" strings](http://www.mrclay.org/string-subtypes/unescaped/) vs [markup](http://www.mrclay.org/string-subtypes/markup/), with the former always being fully-escaped and the latter not being escaped at all.

At this point almost all strings stored in Elgg go through the HTML pipeline, including components like HtmLawed which forcibly converts strings like " < " to entities. Hence even strings that *should* be non-HTML need to be escaped with double-encode off, and wherever you use `$double_encode = false` you will have bugs with content that looks HTML-ish.

The solution is to provide a guide for creating code that handles strings properly, but migrating existing content would be nightmarish. For single-line content like titles, how we do it in core plugins (escape immediately to HTML) is probably the least against-the-grain in Elgg.

**Comment by jdalsem** [comment]
closing this as there is no big issue and no clear idea what a potential solution should be
