### ISSUE TITLE
Invitefriends: allow plugin authors to utilize invite features even when registration is disabled

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#6418]
There should be a simple way for plugin authors to re-enable invites even if default registration is disabled, in case their plugin provides some other way to register (e.g. oAuth).

See #6401

**Comment by hypeJunction** [comment]
I am leaning towards closing this as won't fix at the moment. The core do not provide means of registration other than by using the register form. If a plugin were to allow registrations by other means, none of the logic packaged with invitefriends would apply anyway, the plugin would need to reimplement it.

**Comment by isoguci1** [comment]
I am not sure if related to hypeJunction, but to add to my prev. comment, the plugin "Registration by Invitation" (https://community.elgg.org/plugins/1142917/releases/1.0) does the job, at least on Elgg 1.9.
