### ISSUE TITLE
Remove string-based bools in database tables

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#6432]
I've never liked the "yes|no" enums used as bool values. It adds method overheads to rewrite these to actual bool values in the API, and increases the possibility of introducing bugs like:

``` php
if ($entity->enabled) {
    // Ack, "no" evaluates as true here!
}
```

Ditto for anything using "yes/no" or "on/off" MD.

**Comment by jdalsem** [comment]
There is no need to replace the `enum` value types in the database. There are no gains. Enumerations are faster, more efficient in storage. There is also no real boolean value, so we still need to convert to booleans in API. See also https://stackoverflow.com/questions/2023476/which-is-faster-char1-or-tinyint1-why
