### ISSUE TITLE
Radio inputs slightly clipped on left side in webkit

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#6448]
Affects Chrome / Safari. Doesn't seem to be an issue in Firefox, haven't checked other browsers yet. See attached screenshot from Chrome.
![screen shot 2014-02-09 at 12 05 08 pm](https://f.cloud.github.com/assets/43375/2120321/0f307392-91ad-11e3-8055-d08df467e6cb.png)

Quick fix is adding margin-left: 1px to the input.

**Comment by mrclay** [comment]
See also https://github.com/Elgg/Elgg/issues/9287#issue-125167584

**Comment by mrclay** [comment]
@lweddewer You mentioned seeing the clipping on your own site, where did it occur?

**Comment by mrclay** [comment]
I think #5197 should get the attention (move .elgg-body to flexbox)

**Comment by lweddewer** [comment]
@mrclay: I saw it at the bottom of https://elgg.org/plugins/new
I used Firefox Release 43.0.3 on Linux.
Also tested Chrome Version 47.0.2526.106 (64-bit). Here all looks fine:

![260106_fehler_selectbutton_chrome_okay](https://cloud.githubusercontent.com/assets/8478427/12150198/b64bf7c6-b4a8-11e5-85db-08c49703d7f1.png)

**Comment by jdalsem** [comment]
Currently not reproduce-able with elgg/master on Windows (Chrome/FF/Opera). Closing for now

**Comment by mrclay** [comment]
Fixed by move to flexbox.
