### ISSUE TITLE
Login popup opens in a wrong location

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#6452]
See http://community.elgg.org/discussion/view/1148550/pop-up-log-in-box-displaying-below-the-fold

**Comment by jdalsem** [comment]
I can confirm this still happens on Opera on Windows 10

**Comment by hypeJunction** [comment]
Let's use the new AMD popup module for this.

**Comment by jdalsem** [comment]
Can you take this on then?

**Comment by hypeJunction** [comment]
I don't think we can implement it until 3.x.

**Comment by mrclay** [comment]
@hypeJunction it already uses it. Note that #10908 doesn't fix this in Safari.

I also tried the latest jQuery 2.x and UI 1.12, neither fixed it. 😕

**Comment by hypeJunction** [comment]
On most sites, I now use a lightbox. Also keeps the bots out.

**Comment by mrclay** [comment]
> On most sites, I now use a lightbox. Also keeps the bots out.

What part of the lightbox keeps the bots out? Lightbox uses ajax? Is registration lightboxed? Do you remove the /login /register pages?

**Comment by hypeJunction** [comment]
I put them behind `elgg_ajax_gatekeeper()`
