### ISSUE TITLE
Dev tools: Show file/line numbers for all callables

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6483]
In particular, dev tools should help you locate callables that aren't static methods/functions. For Closures, include file/line number. For dynamic method callbacks/invokable objects, include the classname of the object.

**Comment by jdalsem** [comment]
It is recommended to use readable callbacks. Anonymous callbacks are not recommended, but are not disallowed. A downside of the anonymous callbacks are harder readable in stacktraces or in Developer Tools. We accept this for now. In core we have no (AFAICT) anonymous callbacks.
