### ISSUE TITLE
page handler limitations

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#6490]
in the .htaccess the following is configured
```
# Everything else that isn't a file gets routed through the page handler
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([A-Za-z0-9\_\-]+)$ engine/handlers/page_handler.php?handler=$1 [QSA,L]
```
This means if the path you request is a directory or file the pagehander isn't fired.
If I go to /pages/ I get a 403 forbidden because directory browsing is disabled. However I expected the pages plugin to handle this and forward me to /pages/all, but since the system isn't allowed to pick this up no such luck.

Why is the condition there for directories? I fully understand the need for file (eg /mod/file/thumbnail.php?.....)
Is it possible to drop the directory condition? Please give me feedback

**Comment by ewinslow** [comment]
I don't think we are going to take any action on this...
