### ISSUE TITLE
Write a browser test suite for Travis

### ISSUE THREAD

**Issue by sembrestels** [Elgg/Elgg#6492]
http://docs.casperjs.org/en/latest/testing.html

It consists in write some tests to check that some processes continue working and run them in Travis each time there is a commit.
- [ ] Installation test
- [ ] User registration test

**Comment by jdalsem** [comment]
Travis has documentation about settings up browser testing here: https://docs.travis-ci.com/user/gui-and-headless-browsers/

Going to close this ticket as i do not expect any one making an effort into getting this in core any time soon.
