### ISSUE TITLE
Add support for CSS async loading

### ISSUE THREAD

**Issue by sembrestels** [Elgg/Elgg#6517]
It is important to provide a way to load CSS asynchronously because sometimes they are dependences of asynchronous JS, for example lightbox.

It is also an opportunity to unify CSS and JS function declarations in elgglib.php.

**Comment by ewinslow** [comment]
I think we definitely still want this.

**Comment by jdalsem** [comment]
removed from the 3.0 milestone as it does not require a breaking change to implement, so it can even go in a minor

**Comment by jdalsem** [comment]
css async loading is still a pain. Not going to put in the time at the moment. If someone has a viable PR than feel free to submit
