### ISSUE TITLE
Use Imagine for image manipulation

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#6561]
https://imagine.readthedocs.org/en/latest/

Note: requires PHP 5.3

See discussion here: https://github.com/Elgg/Elgg/pull/6389

**Comment by ewinslow** [comment]
This seems like a great idea... And we're on php 5.4 now so the 5.3 requirement is nbd

**Comment by ewinslow** [comment]
This can be done after 2.0.0

**Comment by jdalsem** [comment]
Added in https://github.com/Elgg/Elgg/pull/10279
