### ISSUE TITLE
Use elgg_normalize_url() in profile edit action

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#6569]
Right now we're doing this:

```
    if ($value && $valuetype == 'url' && !preg_match('~^https?\://~i', $value)) {
        $value = "http://$value";
    }
```

Is there a reason we're not using elgg_normalize_url()? Quick search didn't pull up anything. There are use cases for non-http(s) URLs in this field.

**Comment by mrclay** [comment]
Accidental closing.

**Comment by mrclay** [comment]
elgg_normalize_url needs to be broken apart for different usages #6340

**Comment by jdalsem** [comment]
do we need to add a hook only for the url white list? Or shall we add a hook for `profile/edit` to allow sanitizing all input vars?

**Comment by mrclay** [comment]
I think providing full form validation via hooks would open a can of worms, but probably be worth pursuing in another ticket.

**Comment by mrclay** [comment]
Maybe at least a workflow for single-value validation would be worth figuring out before we tack on something custom here.

**Comment by jdalsem** [comment]
Leaving this as it is for now
