### ISSUE TITLE
Feature: Allow multiple widgets layouts in a same page

### ISSUE THREAD

**Issue by ManUtopiK** [Elgg/Elgg#6595]
Currently it is not possible to display two (or more) layout widgets on the same page. This could be useful to do this, and provide developers the ability to make more customizable pages. 

The following files should be modified: 

- `js/lib/ui.widgets.js` (must change selectors, replace some hidden inputs to jQuery data) 
- `page/layouts/widgets/add_button.php` (rel[toggle] should point to an unique selector) 
- `page/layouts/widgets/add_panel.php` 
- `page/layouts/widgets.php` (change some id to class) 

I already did this feature. Are you interested to include it in core?
This feature doesn't break old scheme.

**Comment by hypeJunction** [comment]
I believe this is fixed by #9609. Please reopen if there is more we should do.
