### ISSUE TITLE
elgg_register_js with fallback for require.js

### ISSUE THREAD

**Issue by ManUtopiK** [Elgg/Elgg#6600]
There is a fallback with require.js. It could be useful to use it. `elgg_register_js` doesn't seem to provide it.
They talk about how to do it [in the wiki](https://github.com/jrburke/requirejs/wiki/Upgrading-to-RequireJS-2.0#wiki-pathsfallbacks). If you are not using v2.x, there is a method for handling that here too (but I think you have updated recently).

`src` should be also an array, like that:
```
elgg_register_js('jquery.form', array(
	'src' => array(
		'http://malsup.github.io/min/jquery.form.min.js', // CDN
		'/vendors/jquery/jquery.form.js' // local fallback
	),
	'deps' => array('jquery'),
	'exports' => 'jQuery.fn.ajaxForm',
));
```
Or one other exemple with most explicit CDN:
```
elgg_register_js('chart', array(
	'src' => array(
		'//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js', // cloudfare CDN
		'/mod/myPlugin/vendors/Chart.min.js' // local fallback
	),
	'deps' => array('jquery')
));
```
What do you think about it ?

**Comment by jdalsem** [comment]
If i am correct this is currently possible with Elgg
