### ISSUE TITLE
Reduce HTTP requests for scripts

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6602]
In head alone we have:

* require_config
* require
* $
* $migrate
* $UI
* $form
* js/elgg

AMD modules are deferred, which is sort good unless user clicks a button and the AMD module still hasn't loaded to set up the event handler.

**Comment by jdalsem** [comment]
Do we really want to put effort into this? With all the splitting up into AMD modules this is something that will always be a problem. HTTP/2 is just approved, so we can expect bundled request in the future. Don't feel like putting to much effort in this.

**Comment by ewinslow** [comment]
Agree.
