### ISSUE TITLE
Metatags repeated

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#6609]
If identical metatags are added from different plugins

$data['metas'][] = array();

 it appears for each time it's added.

**Comment by jdalsem** [comment]
We could use named keys for the registrations in core:
`$data['metas']['rss_link'] = array()`

that way you can overwrite what you want. 

If somebody adds the "same" array on another key, too bad, then you have a duplicate.

**Comment by mrclay** [comment]
Sounds fine to me
