### ISSUE TITLE
Admin panel CLI

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6612]
That's just my wish to make tool for enabling/disabling plugins from the shell level.

In our company, we have quite complex deployment on top of Elgg and it's tricky when you accidentally disable crucial plugin on dev machine. Typical approach (`disabled` file in mods) doesn't make it much easier as it highly depends on modifications from the plugin to go even to that point and you end up hacking stuff around to reenable it.

It would be very natural and easy to simply have CLI tool as alternative interface to admin panel that allows:
- listing plugins
- disabling/enabling plugin by name
- reordering plugins

While having it it would make sense to include critical features that may influence access to the installation or typical maintenance tasks, like changing site URL or clearing cache.

I will probably write something like that at some point, but it makes sense to just include it to the core instad making a plugin from it, as it's only CLI tool.

I think it might be useful for automatic deployment to ie. allow running upgrade or clearing cache from CLI just after deploying code automatically or automating enabling of plugins.

Any objections to adding such tool to the core?

**Comment by jdalsem** [comment]
PR in #11041
