### ISSUE TITLE
Umlaut-issue in text of urls (output/url)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#6613]
Example use case that arised the issue: image titles in Tidypics. A user reported a problem with umlauts in image titles on the gallery pages. The image title on this pages is a link (displayed with output/url).

In output/url the link text is filtered by htmlspecialchars (formerly it was htmlentities but changed with Trac ticket #2036). The problem with umlauts (maybe other special characters too?) and htmlspecialchars will most likely only occur when the client browser (image upload/ entering image title) does not use UTF8 encoding.

If htmlspecialchars is used at output time, is the proposed way to fix encoding issues at input time (within 3rd party plugins) or would it be better to avoid possible encoding issues by fixing the problem in Elgg core (within output/url)?

**Comment by jdalsem** [comment]
@Elgg/owners is this something Elgg should fix? Or is this a case where the plugin needs to be updated?

**Comment by mrclay** [comment]
Can you be more clear about what series of events causes the problem, particularly in a core Elgg install? I like to use the string Iñtërnâtiônàlizætiøn to test things.

**Comment by iionly** [comment]
Sorry. I'm currently knocked out by the flu and therefore can't give any useful feedback this week.

**Comment by iionly** [comment]
The umlaut issue (äÄ öÖ üÜ) was reported to me. I hadn't come across it myself. I couldn't reproduce it back then and still can't reproduce it now. The only explanation I had back then was the change from htmlentities to htmlspecialchars as the output is handled by the core output/url view.

Closing as no one else seems to have this issue.
