### ISSUE TITLE
Allow components using global functions to be tested

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6636]
Say you're trying to test a component class which deep down needs to use `get_user()` or even `sleep()`. There are no clean methods of mocking those (you can see one not great option [here](https://github.com/mrclay/Elgg-leaf/blob/persistent_login_svc/engine/classes/Elgg/PersistentLoginService.php#L314)).

Using global functions also allows outside state dependency to hide in your component (not good). I suggest a simple class like Elgg_Globals, with a `__call` method that just calls the global function of the same name. `$globals->sleep(1)` would call `sleep(1)`.

This would be explicitly passed in to components needing it (a mark of shame that should motivate refactoring), but, importantly, it would allow these calls to be mocked in unit tests.

**Comment by hypeJunction** [comment]
Is this still relevant with the direction we are headed in terms of testing?

**Comment by mrclay** [comment]
This would break static analysis, which I think would make things worse.
