### ISSUE TITLE
enhancement: simplify, unify & extend thumbnails

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#6672]
there are many tickets relating to thumbnails, yet i am not aware of one that covers these points.
there is no really consistent use of thumbnails across plugins.. some have different sizes, some don't store all the available sizes, some use different rendering approaches, some use different php approaches etc.

i suggest adding a system wide set of variables that store the dimensions of thumbnails that are used, wherever thumbnails are used. so the administrator can choose height and width values for each named size of thumbnails (tiny, small, large etc.) and then all thumbnails will use these sizes.
this will ensure consistency across the site and across entity types.

an upgrade/re-processing script would be required that can batch process existing thumbnails, when the sizes are changed.

this approach will also simplify and enhance the process of optimisation of images/caching, since thumbnail cache values can be changed in one place in the code.
(ideally the admin options would also include a way to set the cache expiry values for thumbnails - for browser and cdn/proxy level caching).

adding the ability to grab screen captures from videos that are uploaded to the file plugin for use as thumbnails would also be great - i like the idea of grabbing 3 from specific times in the videos and allowing the uploader to choose the best one. (these values could be pre-defined by the admin).

**Comment by ewinslow** [comment]
Consolidating on #6152
