### ISSUE TITLE
filestorename of files uploaded using file plugin are not kept updated

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#6677]
1. upload a file via the file plugin. (i am testing with video files - flv and mp4)
2. edit the elgg file object and upload a different file to the previously created file object.

examining the filestore directory, shows that the 2nd uploaded file is stored with the file name of the 1st file..
so if i upload xyz.flv and then replace it with xyz.mpg.. the file that is on the hard drive is still called xyz.flv even though it is an mpg.

besides that this is confusing when looking manually at the filestore - this may also cause problems when performing operations on filestore files - as i am currently, to generate video thumbnails.

**Comment by mrclay** [comment]
PR #9615
