### ISSUE TITLE
Elgg 1.9: handling of file names of language files has changed

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#6712]
On previous versions of Elgg (at least 1.7 and 1.8) the language a language file is provided for was determined by parsing only the first two characters of the file name. This behaviour allowed to store more than a single language file in the same directory, e.g. put together all language files for Elgg core plus bundled plugins in a single directory for a specific language, by naming them for example like: de.php, de_blogs.php, de_groups.php etc.

This is still possible on Elgg 1.9 but only if you do not use the new language file scheme (only return = array...) but keep the old scheme ($german = array(...); add_translation('de', $german);). On using the new scheme on Elgg 1.9 if the file name is for example de_blogs.php this is interpreted as a language file for the language "de_blogs".

If Elgg 1.9 would continue to only parse the first two characters of the file names of language files (which of course must match the two-character Iso-code), it would be possible to keep more than a single language file within a directory but also to switch to the new scheme for these language files.

**Comment by jdalsem** [comment]
What is needed to close this ticket?

**Comment by iionly** [comment]
If possible restore the "old" way (pre 1.9) of handling language files filenames:

* don't parse the filename to the latest dot but to the first dot with everything before the first dot defining the language code,
* allow for putting more than a single language file of the same language within the same language folder again, e.g.

de.blog.php
de.core.php
de.some_3rd_party_plugin.php

* allow this with the new language array scheme within the language files, i.e. without the need to use add_translation() in the language file and without the need to use register_translations() for the language files to be loaded.

**Comment by iionly** [comment]
Giving up on seeing any changes here as no one but me seems to be interested.
