### ISSUE TITLE
Allow token-based auth for actions

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6736]
The tokens on the page currently time out, which has historically caused problems when composing long form content and requires us to do this "heartbeat" hack to make sure they don't time out.

A more popular option these days, especially for APIs, is to ask clients to provide a token in the header or query params (e.g. /endpoint?auth=###). I think our web services API may even already support this? It would be nice to support this out of the box for actions.

This makes the following things easier:
- multi-login
- native mobile dev
- other stuff

**Comment by jdalsem** [comment]
Leaving this as is for the moment. Switching to a mechanism without the need for a heartbeat would be nice, but at the moment not worth the effort.
