### ISSUE TITLE
Prefetch metastring IDs for elgg_get_entities_from_metadata

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#6763]
I'm working with a fairly large database (960k entities) with 32 million metadata records.
A script I'm working on is importing new entities and checking for duplicates by metadata.

With a metadata table this large (and expected to hit 52 million by the time I'm done) the native egef_metadata function is pretty slow, it repeatedly joins the metadata table to denormalize the metastring values.

In an effort to increase efficiency I've made the script pre-fetch the metastring ids, then use elgg_get_entities with a single join of the metadata table using the fetched ids.
This alone has reduced the execution time of the script by 96%

I think we should see if we can prefetch the ids in the native egef_metadata function instead of the multiple joins.

**Comment by jdalsem** [comment]
maybe we should compare both solutions... also additionally metastring ids could also be cached in other ways like memcache

**Comment by mrclay** [comment]
I began work on this by [converting joins to subqueries](https://github.com/mrclay/Elgg-leaf/commit/f82a03f55cb9966f6149b76d40f093ee1b118107) (not passing tests yet but things work).

**Comment by mrclay** [comment]
One thing learned: MD.name_id matching in entity/MD fetch functions is case-insensitive. I would think this would worsen performance and yields very little gain in the API.

**Comment by mrclay** [comment]
See #10039

**Comment by jdalsem** [comment]
Current path is to go with denormalizing metastrings
