### ISSUE TITLE
Allow no-forward action() calls

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#6774]
It would be nice to have an option to make a call to action() with a flag to prevent forwards. Every once in a while, I feel like reusing an action within an action, but the forward prevents me from doing so, and I end up either requiring the action file or creating a copy of sorts.

**Comment by jdalsem** [comment]
Closing this as there is a work around with a hook. Including multiple action files is bad practice and with the new approach (as being discussed in #6760) this specific change will be obsolete.
