### ISSUE TITLE
Using dynamic methods as event handlers is too hard

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6795]
Overview: http://www.mrclay.org/2014/04/27/events-with-dynamic-handlers-simplified/

I propose we allow handler callbacks like `"service->method"` where, on triggering, this results in the call `_elgg_services()->service->method($event, $type, ...);`

**Comment by mrclay** [comment]
We'd also want to allow some core handlers to be able to be removed, but no chance that plugins would accidentally reference them. So I suggest:

- `foo->` would reference a service "foo" on a public service container (not `_elgg_services()`).
- Elgg core would register *some* (not all) services on this same container, prefixed with `elgg:`.

E.g. to unregister a core handler and replace it with your own:

```php
elgg_unregister_event_handler('foo', 'bar', 'elgg:svc->fooHandler');
elgg_register_event_handler('foo', 'bar', 'my_svc->fooHandler');
```

But core could still reference the core service container by prefixing `_elgg:` instead. So `_elgg:views->` would reference our private ViewsService.

**Comment by hypeJunction** [comment]
Seems like extra work without much gain, if we can't teach IDE to
autocomplete these.

**Comment by mrclay** [comment]
IDE support is indeed a problem. The gain is that we can start using objects with their own internal state while handling events/hooks. With functions/static methods, shared state has to live somewhere else and be referenced statically.

**Comment by hypeJunction** [comment]
What happened to using __invoke?

**Comment by mrclay** [comment]
#8399 (using __invoke) is a step better, but the object is thrown away after the handler is called, there's no way to access the object before/after or pass in constructor arguments.

To complete these we'd also have to expose a public DIC but we need to do that anyway. Let's say you wanted to count events:
```php
class EventCounter {
    private $i = 0;
    public function getCount() { return $i; }
    public function handler($e, $t, $o) {
        $i++;
    }
}

// register service
elgg()->svcs->register('event_counter', EventCounter::class);
// register for events
elgg_register_event_handler('all', 'all', 'event_counter->handler');

// get count later:
elgg()->svcs->event_counter->getCount();
```

**Comment by mrclay** [comment]
The example above *can* be implemented today, of course, but none of the pieces would be very testable/reusable.

**Comment by hypeJunction** [comment]
I see the point. I have ended up calling a function from all handlers that
was wired to a singleton in my latest attempt to make roles testable.

**Comment by jdalsem** [comment]
Closing in favor of #7461
