### ISSUE TITLE
Provide polyfills for old browsers so we can use new JS features today

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6797]
We have no standard way of accomplishing this right now.

Doing this would let us use up and coming standards that aren't yet available in all browsers. More modern browsers would be rewarded by loading less js to fill the gaps.

https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills

**Comment by jdalsem** [comment]
I think this can be accomplished with plugins that are freely available. We also do not want to encourage people to use old browsers. HTML5 is now very much the standard. Maybe on a new big standard we can supply a polyfill solution
