### ISSUE TITLE
Simpler, OO API for the DB

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6798]
Exploration for a further simplification of the DB API.

We made good strides by switching from the previous argument list in 1.6 to named arguments in 1.7. I think we can do even better.

Goals:
- Testability (OO, no globals)
- Unify attribute and metadata API
- Return ElggBatch (or equivalent) by default

My idea is very similar to the [mongo API](http://mongodb.github.io/node-mongodb-native/markdown-docs/queries.html)

Current:

``` php
// Global, hard to test/mock
elgg_get_entities(array(
  // hard-coded support for <= and >= comparison
  'time_created_lower' => 12345,
  'time_created_upper' => 54321,

  // very verbose when metadata is involved
  'metadata_name_value_pairs' => array(
    array(
      'name' => 'tags',
      'value' => array('foobar'),
      'operand' => 'IN',
    ),
  ),
));
```

Proposed:

``` php
// OO, mockable
$entities->find(array(
  // generic support for all operands on attributes
  'time_created' => array(
    '>=' => 12345,
    '<=' => 54321,
  ),

  // metadata API is identical to attribute API
  'tags' => array('foobar'),
));
```

Relationships could be queried similarly:

``` php
// Everyone I've added as a friend
$relationships->findEntities('object', array(
  "subject" => elgg_get_logged_in_user_guid(),
  "name" => "friend",
));
// Alternatively
$relationships->findObjects(...);

// Groups I'm a member of
$relationships->findEntities('subject', array(
  "subject" => array("type" => "group"),
  "name" => "member",
  "object" => elgg_get_logged_in_user_guid(),
));

// Alternatively...
$relationships->findSubjects(...);


// Events I'm attending or may be attending
// that haven't ended yet,
// from soonest to start to furthest out
$relationships->findEntities('object', array(
  "subject" => elgg_get_logged_in_user_guid(),
  "name" => array("rsvp-yes", "rsvp-maybe"),
  "object" => array(
    "type" => "object",
    "subtype" => "event",
    "endTime" => array(">=" => time()),
  ),
), array("sort" => "object.startTime ASC"));
```

Here are some sample interfaces:

``` php
namespace Elgg\Storage\Entities;

interface Collection {
  /** @return Item */
  function get($id);
  /** @return Item[] */
  function find(Query $query);
  /** @return Item[] */
  function remove(Query $query);
  /** @return int */
  function count(Query $query);
}

interface Query {
  /** @return Query */
  function prop($name, $comparison, $value);
  /** @return Query */
  function sort(array $options = array());
  /** @return Query */
  function limit($limit);
  /** @return Query */
  function offset($offset);
}
```

I imagine we would then want similar collections and query objects for several other tables:
- annotations
- acls
- cookies
- private settings
- relationships
- river
- sessions
- metadata?
- objects, sites, users, groups?
- queue?
- system log?

Would require the DI system to be available to plugins before this could truly become a more useful option than the current approach.

Similar proposals have been made in the past but I can't find the bugs at the moment.
## Rollout plan

It would be too much to try to do all this at once. We should convert step-wise in a way that wraps our current public API trivially so we can just start refactoring internal code to rely on the objects instead of the global functions.

So for V1 I'm thinking something like the following, though not sure on specifics of some function arguments. This just gives a general idea.

``` php
class Entities {
  function find(array $options = array()) {
    return elgg_get_entities_from_metadata($options);
  }
}

class Relationships {
  function findSubjects(array $options = array()) {
    return elgg_get_entities_from_relationship(array_merge($options, array(
      'inverse_relationship' => true,
    )));
  }

  function findTargets(array $options = array()) {
    return elgg_get_entities_from_relationship(array_merge($options, array(
      'inverse_relationship' => false,
    )));
  }
}

class River {
  function find(array $options = array()) {
    return elgg_get_river($options);
  }
}

class Annotations {
  function findEntities(array $options = array()) {
    return elgg_get_entities_from_annotations($options);
  }
}
```

**Comment by ewinslow** [comment]
I kinda like CakePHP's new "fluent" API that they added in 3.0.

```
$recentBlogComments = $entities->where(['container_guid' => $blog->guid, 'subtype' => 'comment'])->orderBy(['time_created' => 'desc']);

foreach ($recentBlogComments->slice(0, 10) as $comment) {
  // Iterates through the first ten comments
}
```

But there are things I would change, too.

Like the API for comparisons other than '==' is really strange:

```
where(['id >' => 12345])
```

I'd rather separate out the comparison, since I don't like string parsing much. But I supposed I could be convinced otherwise:

```
where(['id' => ['>' => 12345]])
```

Cake's approach is certainly more terse...


I also don't like that you can filter a result set and then retroactively expand it with orWhere(...). 

```
$supersetOfTheSubset = $subsetOfArticles->orWhere(otherCondition);
```

It's not how you usually I think of filtering collections. If you wanted a union I think you should have to do:

```
$subsetOfArticles->union($articles->find()->where(otherCondition))
```

I feel like this could make it too easy to open up security issues by ignoring the inherent access level restraints that Elgg has. If we pass a result set, clients shouldn't be able to just do orWhere('1' => '1') and get the whole database...

**Comment by ewinslow** [comment]
Would still love to unify our DB interfaces around collections.

Latest iteration of my idea of an OO API for this...:

```php
interface Repository<T> {
  add(T $item): string // creates a new entry and returns the key
  addAll(T[] $items) // returns nothing. Query the repository with find() to see what changed
  delete(string $id): ?T // shorthand for deleteAll([$id])[0]
  deleteAll(string[] $ids): T[] // returns the list of deleted entries
  where(array $options): Map<T> // A read-only, subset/view of the repo entries
  get(string $id): ?T // Fetch a value by ID
  has(string $id): boolean // shorthand for !is_null(get($id))
}
```

Basically instances of "Repository" would map somewhat closely to database tables, however we could introduce automatic joins.

Cake's interface is so collections-friendly that it feels almost silly to do any reimplementation, but I wonder if we can just wrap their implementation like we've done with some other APIs...

**Comment by ewinslow** [comment]
I don't see this happening for 2.0.

**Comment by ewinslow** [comment]
And it can always be introduced some time during 2.x.

**Comment by hypeJunction** [comment]
FYI, I am working on a modified version of #11115. As the first step, I will bring in a fluent tested OO query API, then we can refactor ege*

**Comment by hypeJunction** [comment]
Also building in search and sort API right away #10688

**Comment by hypeJunction** [comment]
The ultimate goal is to switch to sqlite for integration testing, which will require all MySQL to be rewritten with DBAL

**Comment by jdalsem** [comment]
is this something that could be finished in a few weeks? i really want to release a prerelease of Elgg 3.0 this year...

**Comment by hypeJunction** [comment]
Search and all the spagetti sql are two things left that really bother me. I will see how it goes and let you know.
