### ISSUE TITLE
varchar(50) for class column in entity_subtypes table is restrictive

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#6802]
As I am starting to use PSR-4 for autoloading entity classes, the callable class names are getting rather long and don't fit into the 50 chars allocated for class names.

**Comment by mrclay** [comment]
In 1.x, extend `class` to VARCHAR(255), add plugin hook for registering types, and deprecate add_subtype and friends. In 2.0 remove them.

**Comment by ewinslow** [comment]
+1 for removing subtypes table in 2.0. Class identifiers do not belong in the database in the first place...

**Comment by hypeJunction** [comment]
How do we want to approach removing class identifiers from the DB?

**Comment by mrclay** [comment]
I think we trigger a hook with $type/$subtype. If it doesn't return a class name, look up a DB value and issue a depreciation notice.

**Comment by mrclay** [comment]
On second thought let's not deprecate until we really need to.

**Comment by mrclay** [comment]
We can't get rid of subtypes table unless we also change entities table (and any others) to use strings instead of IDs.

Easier: require plugins to *always* use `elgg_add_subtype()` in plugin/start.php. We can load the "class" columns of existing rows, but if a given cache doesn't match the table, the column should be emptied.

**Comment by ewinslow** [comment]
SGTM.

**Comment by mrclay** [comment]
PR #8688

**Comment by mrclay** [comment]
Increase the size of `class` column to 255 in 1.11

**Comment by mrclay** [comment]
I still think #8688 has merit here, but we'll have to wait until 3.0. Basically we should start encouraging plugins to call add_subtype() in init, so their plugins will work in 3.0 as well as being BC with previous versions (at least as far as this API).

**Comment by ewinslow** [comment]
Agreed. That sounds like a good plan to me...

**Comment by ewinslow** [comment]
Alternatively we could come up with a new declarative API that does the
right thing. Going with my obsession for return-from-file configs:

```php
// subtypes.php
return [
  'object:blog' => [
    'class' => ElggBlog::class,
  ],
];
```

Then this could be configured to do the right thing across 2.x and 3.x.

**Comment by mrclay** [comment]
Strawman: New function `elgg_register_subtype($type, $subtype, $class_name)` all *required* arguments. Under the hood this creates a class-less subtype table entry, and populates a memory-only lookup. `rowToElggStar` looks up this first, if not it falls back to the old API (class name in DB).

With this, a plugin would need only call the new function in its init. No need for activate/deactivate scripts. When plugin doesn't init, it reverts to no class name.

**Comment by hypeJunction** [comment]
+1 for the suggested strawman. Do you suggest we deprecate the subtype table, or just deprecate the class column?
