### ISSUE TITLE
Consistency in elgg-image-block - site-notifications

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#6809]
Normally elgg-image-block consists of elgg-image (the icon) and elgg-body (everything else).

In site-notifications a third div has been added.
```HTML
<div class="elgg-image-block">
	<div class="elgg-image"> ... </div>
	<div class="elgg-image-alt"> ... </div>
	<div class="elgg-body"> ... </div>
</div>
```
There should be consistency.

**Comment by mrclay** [comment]
PR: #7884. I *do* think rendering is part of our BC policy, so even though this just changes HTML I think this should go in master (it will affect plugins already written to work around the current markup).
