### ISSUE TITLE
Pull out scripts into composer lib

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6817]
Would be great to be able to use these scripts in plugins, for example. May warrant porting the conventional-changelog code to php.

**Comment by jdalsem** [comment]
would be nice but not required for a release... removing the milestone

**Comment by jdalsem** [comment]
Better do this in 4.0

**Comment by jdalsem** [comment]
Decided that this is not worth the effort. Reuse will be minimal
