### ISSUE TITLE
support configuration of individual view paths

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6844]
Use case: third party assets

Now that we support static assets as views, it would be uber cool to also be able to specify that a file or files in the vendors directory should be the content for a particular view. That way we don't have to copy third party assets into the views system to get the benefits of the view conventions.

`set_view_location` only works on directories, not individual views, iirc.

possible API:
```php
<?php
// /views.php
return [
  'default' => [
    'js/my/lib.js' => __DIR__ . "/bower_components/mylib/mylib.js",
  ],
];
```

**Comment by jdalsem** [comment]
i think these absolute paths provide more features than thought of before; for instance you could have online editing of view files (but store them in dataroot), or you can have cached version of the views, just by pointing the view location to the correct files... very interesting change!

**Comment by ewinslow** [comment]
Yes, I'm excited about the new possibilities, but trying to be diligent about adding auto-tests wherever possible to cover all features that we didn't have tests for before, so it is taking some time to be thorough.

**Comment by mrclay** [comment]
```php
elgg_register_views_prefix_dir('js/jquery', __DIR__ . "/bower_components/jquery/src", "default");
```

FWIW this seems implementable without a huge rewrite (seems a bit risky for 2.0 at this point). `getViewLocation()`, before returning the core views dir, would check the viewname against the list of prefixes.

**Comment by ewinslow** [comment]
I think that depends when we want our freeze date to happen. There's still a lot of like to get in for 2.0... And I have other ideas of what is like to see happen for 2.0 regarding views system. The rewrite makes those easier too.

**Comment by ewinslow** [comment]
I.e. aliasing `js/{view}` and `js/{view}.js` to `{view}.js`. Similarly for CSS.

**Comment by mrclay** [comment]
I think a set of goals would help https://docs.google.com/document/d/15zFQ2Rnttx2Ni9onKha5rjaBVVHlBqhYXnsh489sxe0/edit
