### ISSUE TITLE
Choose language code standard

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6856]
We have at least one language that does not have corresponding translation of it's name.

`cmn.php` chould be `Chinese (Mandarin)` and we only have `zh` for `Chinese`.

It would be nice to find some standard for that and verify that we cover all cases correctly,

**Comment by mrclay** [comment]
Please see #8683

**Comment by jdalsem** [comment]
Not going to add any other languages codes at the moment. If we receive new translations via Transifex, we can add those translation codes to the list.
