### ISSUE TITLE
ege() with "guids" => array() acts as if no setting

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6858]
Coworker ran into this, either a code bug or docs bug. if "guids" is an array with 2 GUIDs, you get 2, with 1 you get one, with 0 you get all. An empty array is kind of a special case, but programmatically it could definitely occur.

I guess it should always return empty array (or count 0).

BC issues unknown.

**Comment by jdalsem** [comment]
i think i disagree on this issue. The usage of guids (`e.guid`, `e.owner_guid`, `e.container_guid`, `e.site_guid`) should be consistent. They should limit the results (if provided). Passing empty guids will always result in no limitation. 

For example: providing `container_guids => array()` is not limiting on containers, so `guids => array()` should also not limit on guids. This is consistent for all guids.

If you have some logic where you expect that to return nothing, you could add that check yourself.

**Comment by hypeJunction** [comment]
I agree with @jdalsem. IMHO, you would pass array(0) to get emtry results.

**Comment by mrclay** [comment]
We have `ELGG_ENTITIES_ANY_VALUE` to ignore the value, but I know no one uses it. Considering the vote here I'm closing to keep BC.
