### ISSUE TITLE
edit page for files does not handle non existent guids

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#6863]
if i navigate to /file/edit/12345 and there is no object with guid 12345 i am taken to an error page instead of being cleanly forwarded elsewhere.
the edit page in the file plugin does not check for the existence of an entity with the guid that is entered by the user, via the url.

**Comment by jeabakker** [comment]
I don't think this is an issue anymore. The edit page check if the guid is a valid ElggFile, if not goes away
