### ISSUE TITLE
Verify translations correctness and come up with strategy against mistakes.

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6864]
As discussed here: https://github.com/Elgg/Elgg/pull/6860#discussion_r12829829

We noticed that some translations in foreign languages that's supposed to be done are fetched in exact the same as english version.

It may be a result of mistake when working with tx cli tool and pushing languages fetched in default mode, not the `translator` one. In such case we push as translations, not translated in fact strings.

My proposition is to make a tool similar to this one: https://github.com/Srokap/polish_translation/blob/master/validate.php, but for all languages in order to give translators feedback on wrong translations or delete them from transifex.

Possible approaches:
- we do nothing about that as it's the domain of translators to worry about translations correctness/quality
- we make simple tool and send reports to translators to indicate existence of the problem and let them deal with that (or not) on their own
- we delete wrong translations on our own based on results from the tool

I'm leaning towards second option.

Opinions?

**Comment by jdalsem** [comment]
The suggested approach is not workable. What is considered 'bad translation' is hard to determine.
