### ISSUE TITLE
Drop requirement to add someone as friend before messaging them

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6895]
http://community.elgg.org/discussion/view/1667047/compose-a-message-to-empty

People don't necessarily realize they need to add friends first. If someone has no friends we should tell them that's what they need to do before they can PM anyone.

Alternatively, we just let them type in whoever's name and automatically add them as friend like we're doing on the community site for group posts now.

**Comment by jdalsem** [comment]
This has been resolved in Elgg 2.0 https://github.com/Elgg/Elgg/pull/8259
