### ISSUE TITLE
On HHVM, XPath query for "//body[1]" returns a single DOMText

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#6903]
**Update:** See https://github.com/facebook/hhvm/issues/7745 for details.

---

When using HHVM 3.2.0-dev  https://github.com/facebook/hhvm as PHP fastcgi  server a fatal error occurs:

```
Fatal error: Call to undefined method DOMText::setAttribute from context ElggAutoP in /engine/classes/ElggAutoP.php    
```

De line item that is failing is:

```
$autop->setAttribute("r", "1");    
```

Issue could not be reproduced by Facebook team and has been closed until a failing test case can be presented. It is currently unclear if Elgg has a bug or HHVM. 

That line item is marked to be reviewed anyway, so maybe now it is a good time to do it. It seems to be the only issue with Elgg core and would make Elgg HHVM compliant

**Comment by jdalsem** [comment]
@gerard-kanters can you check if this issue still exists when using HHVM?

**Comment by gerard-kanters** [comment]
Facebook closed the issue, since they could not reproduce the error. The error still occurred at HHVM 3.3 production version. I have not upgraded or tested later releases.

**Comment by mrclay** [comment]
HHVM won't likely work on this bug until it's reproducible outside the full Elgg stack, and even in the Elgg requests, it's intermittent.

At most we could do is test for the DOMText node and retry the query once.

**Comment by mrclay** [comment]
Ugh, the query feeds a loop, so we'd have to pre-check the entire loop for DOMText nodes.

**Comment by jdalsem** [comment]
@gerard-kanters can you confirm we still experience this issue (with the latest HHVM version?)

**Comment by gerard-kanters** [comment]
I am sorry, we abandoned HHVM because of instability issues we experienced.

**Comment by mrclay** [comment]
Allegedly it's fixed, we're just waiting for Travis to update.

**Comment by hypeJunction** [comment]
Anything actionable here?

**Comment by mrclay** [comment]
I've refiled this as https://github.com/facebook/hhvm/issues/7745

**Comment by jdalsem** [comment]
Closing this as @mrclay stated in facebook/hhvm#7745 the tests were passing.
