### ISSUE TITLE
[Aalborg theme] User icons are not links to profile anymore

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#6906]
I find myself very annoyed by it lately, as I'm used to opening user profile in new tab with middle mouse button, and currently the only way I can, is to click on user icon and than on hover menu position.

I think it shouldn't be much problem to keep user icon as link so it fallbacks gracefully on missing javascript, as well as allows opening profile in new tab as I mentioned.

**Comment by mrclay** [comment]
Aalborg is now core in master. I think TODO here is to get rid of the`span.fa-caret-down` that covers the link.

**Comment by hypeJunction** [comment]
Wow. My opinion on this has changed drastically. Once I am done with the entity menu changes I have in mind, we can consider retiring user hover and moving it to entity menu. The icon could still bring up a user card with the actions menu on hover.

**Comment by mrclay** [comment]
See #10400. Maybe a short term cleanup.

**Comment by mrclay** [comment]
A user card would be great, ideally allowing noting the user's role(s) in context. E.g. "Original Poster" in a discussion.
