### ISSUE TITLE
support named parameters for elgg_echo

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6908]
Backwards compatibility for language strings that take a bunch of parameters is a hassle. Customizing the language string to support a different order of arguments in the output text than in the elgg_echo call is possible with numbered params, but not very fun to keep track of. You have to use numbered parameters but it is not very readable at all.

Being able to use named arguments in new language strings would be awesome, since precise argument ordering wouldn't be as important (we actually learned a long time ago that this was a bad idea which is why we switched the DB querying functions to take a single options array instead of a list of 13 parameters).

**Comment by jdalsem** [comment]
Won't fix. Changing this would mean too much of an impact on the current way things work and the need is not that big
