### ISSUE TITLE
Need to rethink tabs on mobile

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6911]
These assume quite a lot of horizontal space, of which precious little is actually available. See groups or showcase on the community for examples of how this starts to look bad on phones.

I wonder if there's a smarter overflow strategy we can use (e.g. horizontal scrolling so you can swipe to get more). Or else just a different way to design the experience that is cleaner for mobile. These end up taking quite a lot of space when they wrap and push the content even further down than it already is.

**Comment by ewinslow** [comment]
I've seen some sites do horizontal scrolling of navigation.

**Comment by jdalsem** [comment]
leaving this as is for now
