### ISSUE TITLE
Main nav menu improvement thoughts

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6912]
1. The slide-down animation feels a little janky to me. Anyone seeing jittery or inconsistent animation rendering here? What are we using to do that animation? If a JS lib, can we switch to CSS? If CSS then I guess we'll just have to wait for the browser to get better...
2. The "More" menu still shows up when the links are stacked top-to-bottom. I think it should not. We don't need an overflow menu when they're just stacking on top of each other.
3. I really would like to see a slide-out-from-left pattern instead.
4. Can we have it auto-hide after selecting something. As it is, when the page refreshes, it feels like the menu vanishes instantly whereas it entered more naturally before. I think it should always exit/enter the same way, no?
5. It takes up a non-trivial amount of vertical space just to show the one hamburger icon. Can we merge this icon into the topbar or something?

@PerJensen

**Comment by juho-jaakkola** [comment]
Related: #8699
