### ISSUE TITLE
"Replies" section of river items is huge

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#6914]
I think we need to show excerpts or a "...more" link or something to calm that down.

![screen shot 2014-06-07 at 4 35 01 pm](https://cloud.githubusercontent.com/assets/43375/3209721/65c154b4-ee83-11e3-8053-36568b1edf30.png)

**Comment by ewinslow** [comment]
If that screenshot is still accurate then I am still in favor of fixing this ticket...

**Comment by jdalsem** [comment]
Already fixed by #7860 by adding excerpts to the responses/comments
