### ISSUE TITLE
Elgg_Database::getResults ignores bad callbacks

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6937]
If $callback is not empty but isn't callable, that seems like a concern worth raising. Instead the function just doesn't call it.

**Comment by ewinslow** [comment]
We should throw exceptions for stuff like this...

**Comment by hypeJunction** [comment]
Exception please. When I use a custom callback, I usually expect a certain behavior from anentity afterwards.

**Comment by mrclay** [comment]
PR #8155
