### ISSUE TITLE
input/userpicker unable to remove all values

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#6982]
When using the userpicker in an edit situation there is no way to clear all the values

Example:
I supplied `values = array(1,2,3)` and `name = "params[user_guids]"` if i remove all the users (eg 1,2 and 3) there is no longer any input with the name user_guids thus it's not submitted in the form and the action can't remove all the users.
This only applies to auto detecting actions (eg widgets/save, plugins/settings/save)

Suggestion:
like with the input/checkboxes include a hidden input with a value 0 or ""

**Comment by jdalsem** [comment]
@juho-jaakkola do you know why this was reverted?

**Comment by juho-jaakkola** [comment]
The PR was flawed.

**Comment by jdalsem** [comment]
New PR provided; position is everything, the previous PR positioned the hidden input after the checkboxes, thus always overriding the input provided. This new PR has the input before the userpicker, thus acts as a fallback value.
