### ISSUE TITLE
Make base test case for views

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6987]
See https://community.elgg.org/discussion/view/1833024/making-elgg-more-testable#elgg-object-1833063

Caveat: some views may depend on plugin hooks or global state, but this would be a start.

**Comment by mrclay** [comment]
FYI PHPUnit's assertSelectCount() has moved to [phpunit-dom-assertions](https://github.com/phpunit/phpunit-dom-assertions).

**Comment by jdalsem** [comment]
with `ViewRenderingTestCase` we can now implement view tests if needed
