### ISSUE TITLE
Have phpunit auto-execute tests in mod/*/phpunit

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#6988]
See https://github.com/ufcoe/Elgg-ufcoe_testable/blob/master/phpunit.xml

You'd need a [bootstrap](https://github.com/ufcoe/Elgg-ufcoe_testable/blob/master/phpunit-bootstrap.php) to autoload out of /classes.

Or phpunit.xml would be for core, and phpunit-plugins.xml could do this.

**Comment by hypeJunction** [comment]
Fixed by #11168
