### ISSUE TITLE
Add instructions how to deal with markup syntax when translating the docs

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#6995]
see discussion at https://community.elgg.org/discussion/view/1833136/what-specific-semantics-are-to-be-known-for-creating-elgg-docs-translations-from-po-files

When translating the docs it's necessary to handle markup syntax like links correctly. The correct way should be described in the docs itself and these instructions should also be available at Transifex (either the instructions themselves or at least a link to the docs).

**Comment by iionly** [comment]
I don't care anymore about that.

**Comment by jdalsem** [comment]
we care
