### ISSUE TITLE
Add recommendations from community discussions to JS docs

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6996]
People are starting to write JS for 1.9 and the best practices are not clear at all. See the confusion:

https://community.elgg.org/discussion/view/1835258/javascript-error-with-requirejs
https://community.elgg.org/discussion/view/1827358/how-to-correctly-use-elgg-register-js-elgg-define-js-on-elgg-18-and-19

**Comment by jeabakker** [comment]
#8296 and #9386 improved the docs enough
