### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#6997]
The hope is that being able to do more integration-level tests with an in-memory sqlite DB would be much safer/faster than how we currently do it (spin up actual mysql instance which is shared b/w test runs).

**Comment by mrclay** [comment]
In PHP7 ext/mysql will no longer be bundled. Though it will most likely we widely installed on hosts for years, I think Elgg 2.0 should make a serious push to move to PDO in the simplest way possible.

**Comment by ewinslow** [comment]
I started to swap for doctrine components and gave up because it was impossible to do in a completely BC way.

Guess that makes it the perfect candidate for 2.0

**Comment by ewinslow** [comment]
Our tests are now failing because the latest nightlies of PHP 7 don't include ext-mysql...

Time to remove PHP 7 from the tests for now, but just makes this switch all the more important I guess...

**Comment by ewinslow** [comment]
@mrclay after the switch to Doctrine's DBAL (thanks for that!), what is left to do here?

**Comment by mrclay** [comment]
- Alter Elgg\Database\Config::getConnectionConfig() to return an array directly compatible with Doctrine\DBAL\DriverManager::getConnection()
- This will allow us not to hardcode MySQL in Elgg\Database::connect()
- Provide a way to inject a custom Config into Database constructor

**Comment by jdalsem** [comment]
There is no pressing urgency for this feature. We are open for PR's if someone is willing to put in the effort.
