### ISSUE TITLE
thewire delete action needs more error handling

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#7003]
1. click the delete icon for a wire message in a wire list.
2. click the delete icon again BEFORE the page has refreshed.

a php error is thrown since there is no check in the delete action code to check whether the wire entity exists and it is already deleted from the first click.

```
Fatal error: Call to a member function getSubtype() on a non-object in /var/www/html/mysite/mod/thewire/actions/delete.php on line 12
```
this may apply to other actions, i haven't looked yet.

**Comment by jdalsem** [comment]
Fixed in #8143
