### ISSUE TITLE
Add support for HTML imports

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7014]
Background reading:
- Spec: http://w3c.github.io/webcomponents/spec/imports/
- Polymer: http://www.polymer-project.org/platform/html-imports.html
- HTML5 Rocks: http://www.html5rocks.com/en/tutorials/webcomponents/imports/

You can sort of already do this with the head plugin hook, but it would be nice to use IDs and dedupe like we do with CSS and JS.

**Comment by jdalsem** [comment]
HTML Imports was an experimental technology, never implemented in any other browser. The spec is superseded by ES modules, which is widely supported.
