### ISSUE TITLE
Allow sites to expose theme sandbox publicly

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7036]
Precedent:
- Google: http://www.google.com/design/spec/
- Yelp: http://www.yelp.com/styleguide
- Github: https://github.com/styleguide

In particular I think our use-case here is Elgg or the Elgg community, which can serve as public documentation for what components are available and how they're meant to be used.

**Comment by jdalsem** [comment]
The current focus of the theme sandbox is for developers, not for site users
