### ISSUE TITLE
Better organization for theme preview

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7037]
It's late so forgive me if I'm coming from way out of left field. Our theme preview has only one level of navigation and I think it may deserve two. This is how I kind of logically group all the different components. Wonder what others think.

Typography:
 * Colors
 * Headings (h1-h6, elgg-heading-*)
 * Utilities (elgg-subtext, etc.)

Controls:
 * Buttons (elgg-button-*)
 * Inputs (elgg-input-*)
 * Menus (elgg-menu-*)

Containers:
 * Modules (elgg-module-*)
 * Layouts (elgg-layout-*)
 * Grid (elgg-grid)
 * Tables (elgg-table)
 * Image block (elgg-image-block)
 * Lists (elgg-list)

Content:
 * Icons (elgg-icon-*)
 * Tags (elgg-tag, elgg-tagcloud)
 * Messages (elgg-message)

**Comment by jdalsem** [comment]
Why not put it all on one page? With a sidebar menu to toggle the items on the page?

**Comment by ewinslow** [comment]
Long pages are long? Harder to find stuff?

I don't really recall what problem I was having

**Comment by jdalsem** [comment]
I think people are used to it now... if it causes real problems we can always revisit the organisation
