### ISSUE TITLE
Upgrade UX suggestions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7039]
I was just trying to upgrade from 1.8 and was getting infinite ajax loops. 
- [ ] Add feedback to the user
- [ ] Terminate ajax script after several dry runs (nil `$numSuccess` probably indicates problems with the upgrade scripts)
- [x] Allow admins to increase the  `$batch_run_time_in_secs` without having to hack into the code (in my case it was taking 3.5 sec for the batch to run)

**Comment by jdalsem** [comment]
@hypeJunction i believe these issues became obsolete... am i right?
