### ISSUE TITLE
embed: manifest.xml requirement

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#7042]
While working on an extension to the exmbed plugin I found some unexpected / unwanted behaviour

according to the manifest the embed plugin requires 'file_uploading'????? what if for example the videolist plugin wanted to offer support for the embed plugin, it would have to provide 'file_uploading' but is doesn't and it would be unlogical for the plugin to say that is does.
Wouldn't it be better to require 'embedding' (if this is English?)

**Comment by jeabakker** [comment]
@Elgg/owners @Elgg/contributors any thoughts on this one

**Comment by mrclay** [comment]
My guess is this was added when CKeditor was first added (had file uploading but was never released).

**Comment by iionly** [comment]
"file_uploading" is supported by the bundled File plugin. The embed plugin allows for embedding files that are already there on the site and allows uploading of new files to be embedded (that are then saved in the files section). This has nothing to do with the CKeditor files adding that had been a temporary feature.

I would think that other plugins can hook into the embed plugin to allow for embedding other types of content to be embedded without providing the "file_uploading" support on their own. But if you disable the File plugin you won't be able to upload new files to be embedded at least to the files section.

**Comment by jeabakker** [comment]
> I would think that other plugins can hook into the embed plugin to allow for embedding other types of content to be embedded without providing the "file_uploading" support on their own. But if you disable the File plugin you won't be able to upload new files to be embedded at least to the files section.

very true, but if you have the file plugin disabled (not needed on your community) you first you need to enable the file plugin, because it offers file_uploading, then enable your own plugin which supports embed. Then you can deactivate the file plugin again.
This however leaves you with a plugin in the plugin list with a warning.

I would like to know a better suggestion for
```xml
<requires>
	<type>plugin</type>
	<name>file_uploading</name>
</requires>
```
But i don't know a good English term for 'embedding'

**Comment by hypeJunction** [comment]
I understand the intention, but if you implement custom file uploading logic in a plugin, the chances are you are using custom forms and actions, so whatever is hard coded here will not work anyway. 
I think I have opened a ticket in the past suggestion to move the embed logic to the file plugin and leave embed just such a skeleton for plugins to extend

**Comment by jeabakker** [comment]
i'm not talking about custom file embedding. If for example i wish to build in support for the embed plugin in say videolist. the videolist plugin needs to provide file_uploading in order to work with the embed plugin????

on a related not i also reported a ticket about the logic in embed #7044

**Comment by iionly** [comment]
I don't know if the embed plugin would currently work at all without the files plugin enabled. That's maybe the point to clarify before thinking about changes in manifest.xml.

If the requirement of the files plugin is rather a "suggestion" than a "requirement" then it would be possible to simply change the manifest of the embed plugin accordingly. Then you could use the embed plugin with whatever other plugin you have in mind (e.g, videolist) to allow for embedding (external) content.

But if the files plugin is required for the embed plugin to work in the first place I don't see much sense in only making any changes in the manifest of the embed plugin. Then a complete overhaul would be necessary (for example in the way @hypeJunction suggested by moving the file upload/embed functionality completely into the files plugin and making the embed plugin rather a helper plugin providing a common interface for allowing other plugins providing the actual support of embedding different types of content).

**Comment by cash** [comment]
The manifest should have required a plugin that provides embedable content so maybe "embedable_content" rather than "file_uploading". At the time, we were not thinking ahead to future uses of the embed plugin.

**Comment by hypeJunction** [comment]
IMHO, any content is embeddable. For all we know, the plugin might add a tab with a text input, and inject user input right back into the editor/textarea wrapped in some HTML tag (in fact that's what we do file embeds, we just generate an HTML img tag).
