### ISSUE TITLE
embed: difference between readme and reality

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#7043]
While working on an extension to the exmbed plugin I found some unexpected / unwanted behaviour

according to the README:
`Adding a Tab ..... priority: Placement of the tab.`
however the tabs menu isn't sorted by priority, but by the default ('text') so there is no way to order the tabs (it depends on you language)

**Comment by ewinslow** [comment]
So should we fix the docs or fix the behavior?

**Comment by juho-jaakkola** [comment]
I generally dislike menus sorted by link text. It's not good UX that page contents change depending on the language.

The only exceptions are menus with a lot of nested links, e.g. navigation tree of the pages plugin.

**Comment by hypeJunction** [comment]
I am with Juho on this one. Page menu drives me nuts for that reason.

**Comment by ewinslow** [comment]
OK so pretty much agreed that it should sort by priority as documented. Sorting by label doesn't give enough control.

**Comment by beck24** [comment]
same experience here - sorting by label sucks

**Comment by hypeJunction** [comment]
I suggest adding 'sort_by' as param to whatever view is generating the menu

**Comment by jeabakker** [comment]
fixed in #8142
