### ISSUE TITLE
Embed: item view behaviour

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#7044]
While working on an extension to the exmbed plugin I found some unexpected / unwanted behaviour

the output view is largely based on embedding a object:file with simpletype = image
if you embed a non image file you get the usericon, this also applies to all other forms of listings (eg blogs)
there should be a dynamic based listing like for elgg_view_entity, my suggestion:
`/embed/item/<type>/<subtype>` 
`/embed/item/<type>` 
`/embed/item/default`

**Comment by jdalsem** [comment]
We decided to remove the embed plugin in favor of editor improvements https://github.com/Elgg/Elgg/pull/14187
