### ISSUE TITLE
Make Elgg_Amd_Config::getConfig pluggable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7045]
RequireJS times outs failing to load multiple dependencies. I am sure I could increase the ```waitSeconds``` param from within the JS, but perhaps it would make sense to make the config pluggable server-side.

**Comment by RiverVanRain** [comment]
Just tested this commit https://github.com/jdalsem/Elgg/commit/a0d06a8608e088f1943460d713b49adec156cb1d with ElggCKEditor:

elgg_define_js('ckeditor', array(
		'src' => '/mod/ckeditor/vendors/ckeditor/ckeditor.js',
		'exports' => 'CKEDITOR',
		'waitSeconds' => 0,
	));
	elgg_define_js('jquery.ckeditor', array(
		'src' => '/mod/ckeditor/vendors/ckeditor/adapters/jquery.js',
		'deps' => array('jquery', 'ckeditor'),
		'exports' => 'jQuery.fn.ckeditor',
		'waitSeconds' => 0,
	));

Works like a charm

**Comment by jdalsem** [comment]
Fixed in #7885
