### ISSUE TITLE
CSSMin::minify is restarting Apache

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7050]
Not entirely sure what's causing this, but something in CSSMin::minify is restarting Apache on Win.

**Comment by jdalsem** [comment]
@hypeJunction can you try updating the vendor to see if that is solving this issue for you?

**Comment by mrclay** [comment]
We should switch to https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port, which is the original source of cssmin. Minify just has an old copy.

**Comment by hypeJunction** [comment]
This hasn't manifested itself in a while.
