### ISSUE TITLE
Split delete user event into before/after

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7051]
General procedure: 
1. call `elgg_trigger_before_event` first (if false, cancel)
2. change `elgg_trigger_event` to a deprecated event. See https://github.com/Elgg/Elgg/blob/1.9/engine/lib/sessions.php#L321
3. call `elgg_trigger_after_event` very last.
4. change core handlers to use before/after events

I don't expect this to be as easy as it sounds.

**Comment by mrclay** [comment]
For existing events like this, let's just add the after event.

**Comment by jdalsem** [comment]
delete event is deprecated but is not being reported (no version specified)
