### ISSUE TITLE
Allow search custom joins in core search hooks

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#7062]
I often find myself having to replace search hooks to make it possible to do a search by relationship.
eg. search for members in a group

This would be much easier if the core search hooks allowed custom joins/wheres in the params.

**Comment by ewinslow** [comment]
@beck24 -- how would this work if you were doing search via sphinx?

**Comment by beck24** [comment]
it wouldn't, for solr (never used sphinx) I'd either need to defer to the default elgg search for custom joins, or parse the joins into something custom for solr.

**Comment by ewinslow** [comment]
Seems like you'd want to define a new search type and issue searches through that. The implementation details could involve custom joins or something else for sphinx/solr, but I wouldn't want clients assuming the implementation details if we can avoid it.
