### ISSUE TITLE
Warn if robots.txt is being overridden by a physical file

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7067]
https://community.elgg.org/robots.txt is currently:

```
User-agent: *
Disallow: /
```

But if you look at https://community.elgg.org/admin/configure_utilities/robots, you can see plugins should be configuring it to be like so:

```
User-agent: *
Disallow: /search/
```

Even if I explicitly modify the robots.txt in the given text field, nothing changes.

Discovered this during search for "Elgg community plugins" on Google.

**Comment by jeabakker** [comment]
warning added in #8161
