### ISSUE TITLE
Commit only non-dev requirements to the main repo

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#7071]
I think we just need to keep in the repo stuff that's a necessary requirement to run Elgg, so ie. we shouldn't commit PHPUnit and it's dependencies. It also significantly increases repository size ([over 50k lines of code](http://www.ohloh.net/p/elgg)).

Unfortunately:
- composer installs [dev dependencies by default](http://seld.be/notes/composer-installing-require-dev-by-default)
- as a developer, we want to have dev dependencies installed and not need to do magic while commiting code

While having more data than necessary in composer.lock might not be a problem, it's definitely not much fun to have to downgrade packages to `--no-dev` version before commiting changes to vendor dir. Perhaps it's not that big problem if we do package bumps and composer.json changes not that often. We'd need to keep some discipline in that matter to not accept commits that include dev deps to the repo.

Note that we wouldn't have this problem if we didn't commit vendors in the first place, so that's a result of our assumption that Elgg must be ready to install just after checkout. So we need to live with that somehow or revise this assumption.

**Comment by ewinslow** [comment]
We no longer commit any PHP deps to the repo, so this is fixed IIUC.
