### ISSUE TITLE
Don't commit to supporting the API of our dependencies

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7080]
I was just trying to update the markdown library to use composer and realized that it is basically impossible because we provide the existing version using `elgg_register_library` which is a pretty clear commitment to supporting the full public API of that library. Unfortunately, it's not really feasible to provide a wrapper and leaving it in place is the easiest solution.

I think we should only export exactly the API we want to and not let our dependencies become part of our API. Plugins that depend on a feature should explicitly and directly depend on that feature, not do so "through" Elgg core.

I think this should go for javascript as well, made possible by AMD and explicit dependencies.

**Comment by mrclay** [comment]
Do our docs state anywhere that plugin devs should not depend on stuff in composer.json?

cc @jeabakker

**Comment by ewinslow** [comment]
I don't believe they do.

**Comment by jeabakker** [comment]
@ewinslow said in https://github.com/Elgg/Elgg/pull/8620/files#r33578485
> Agree with Steve: let's not encourage folks to have indirect dependencies. Removing one of our requirements should be considered a BC change.

this implies that as a plugin dev i can no longer rely on the fact that jquery is available in Elgg

**Comment by ewinslow** [comment]
Correct.

**Comment by jdalsem** [comment]
As a plugin developer this now **requires** composer support in all my plugins, even for the *basic* stuff like jquery, jquery-ui... isn't that asking too much from plugin developers??

Why don't we agree on not committing to *support* the dependencies, but do commit on keeping them *available* between major releases?

**Comment by jeabakker** [comment]
> Why don't we agree on not committing to support the dependencies, but do commit on keeping them available between major releases?

:+1:

**Comment by ewinslow** [comment]
For 2.x sure. It would be too breaking. But I also don't want Elgg to grow into a behemoth that can never remove any of its dependencies.

What's so hard about requiring jquery in your plugin via composer? Have you also considered that you might not need jquery at all? Browsers are much better now than they once were, and jquery is quite large.

If requiring plugins to explicitly declare all direct dependencies pushes them to ultimately have fewer dependencies, I'd think that's a good thing, no?

**Comment by jdalsem** [comment]
Ok... lets discuss this the other way around... if Elgg does not "provide" recommended libraries, you will end up different plugins requiring different (but overlapping) dependencies, like jquery, mootools, prototype. I do not think site owners would like to have all those libraries loaded (because their site will then become a behemoth also).

Why would you really want to be able to remove dependencies in minor releases? Installing them is not the same as loading them... Elgg could maybe never use any functionality of it (so it *could* be removed), but is keeping the dependency round (until the next major release) for plugin developers

**Comment by hypeJunction** [comment]
That's the problem I was bringing up in the composer-related ticket. For sites installed and managed without composer, lack of dependency libraries becomes an issue for plugin devs - you never know what to required, define, package etc.

**Comment by ewinslow** [comment]
> Why would you really want to be able to remove dependencies in minor releases?

Install/build performance comes to mind. In any case, waiting until the major release to drop dependencies from composer.json seems like a good compromise for now.

Eventually we should just require composer for managing an Elgg site, I would think. If we want to make it friendly to non-techies then we can build a UI that makes that easier.

**Comment by ewinslow** [comment]
I think we have a general agreement here not to remove dependencies during a major release cycle.

**Comment by jdalsem** [comment]
Reopening as i would like to see this documented somewhere on learn.elgg.org

**Comment by iionly** [comment]
Maybe I don't fully understand the consequences here. Am I required to handle dependencies of plugins by composer, i.e. I MUST add composer support to 2.0 plugins or they might only work with a zipped Elgg installation (with a defined range of dependencies defininitely included) but not on a composer Elgg installation?

**Comment by mrclay** [comment]
@iionly Nothing has changed. If we remove dependencies it'll only be during major releases.

**Comment by mrclay** [comment]
I guess that also includes dependencies only used internally? e.g. Stash.

**Comment by ewinslow** [comment]
Adding composer requires to your plugins is not strictly required but it's a really really really good idea. It's just a much better way to do development because so much manual effort is removed. It's like a better manifest.xml that actually enforces all the constraints you specify as opposed to just serving as documentation.

Your plugin will work if it depends on something Elgg pulls in, regardless whether the installation is composer or zip (BTW these are really the same thing if you think about it except that we've just executed all the composer commands for you to generate the zip archive).

**Comment by ewinslow** [comment]
Yes, that includes internal only dependencies too. We can always just add new deps and stop using old ones, but we won't remove them for fear of breaking folks...
