### ISSUE TITLE
need a way of streaming media files from the elgg filestore

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#7089]
while upgrading the file plugin to support video / audio streaming, i have found some limitations of the elgg filestore structure and so far have not found an efficient way to resolve this.
there is a long thread on this topic here (https://community.elgg.org/discussion/view/1653829/anyone-excited-to-team-up-to-create-an-enhanced-video-plugin-for-elgg).

essentially, nginx (and possibly other servers) are not serving video / audio files from within the elgg filestore in a way which supports streaming, thus the seeking features in media players are lost for mp4, mp3 and webm formats. some exploration revealed that:

* flash files do stream correctly from within the filestore
* adding an 'alias' directive to point to the elgg filestore from within the site's nginx configuration file does then allow the files to be streamed correctly (with the response including Accept-Ranges header info). however, this totally bypasses the elgg security/privacy code and thus can only be used if the nginx config is extended to include use of the security mods, which is not a great solution since it only resolves the situation for nginx and is quite complex.
* the issue appears to be due to the elgg filestore being outside of the root directory for the site, as defined in the webserver config file.

various suggestions were presented by steve clay and also some input was given from a coder on the nginx forums. however, so far i have not seen a fully working solution.

converting files for playback through flash 'could' be a workaround, except that adobe are stopping support for linux/gnu and the solution would be best if it did not use proprietary code.

without some kind of adjustment somewhere, the media will only playback linearly, with no streaming.
any ideas how to resolve this peacefully? ;)

**Comment by propertunist** [comment]
this appears to have been resolved in elgg 1.9+ :)

**Comment by mrclay** [comment]
Handling range requests is the way to close this ticket.

**Comment by propertunist** [comment]
that's what i did too, yes. however, there was (as i recall) another issue with privacy/security in elgg 1.8 that was related to this, which no longer effects the streaming process in later versions. you can close this if you want.

**Comment by mrclay** [comment]
[This](https://bitbucket.org/thomthom/php-resumable-download-server/src/8713d54809617b24a63065ef3e5afd998288ad36/index.php?at=default&fileviewer=file-view-default) was built in [2007](http://www.thomthom.net/blog/2007/09/php-resumable-download-server/) and updated many times; I'd guess it's the most mature implementation, though in need of a bit of refactoring.

A question is would this change be BC? We'd be sending audio/video with Content-Disposition: inline instead of attachment.

**Comment by hypeJunction** [comment]
#9354 should have solved this. Please reopen if there are further points to address here.
