### ISSUE TITLE
Add annotations services as abstraction over annotations table

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7096]
- elgg_get_entities_from_annotations
- elgg_get_annotation_from_id
- elgg_delete_annotation_from_id
- create_annotation
- update_annotation
- elgg_get_annotations
- elgg_delete_annotations
- elgg_disable_annotations
- elgg_enable_annotations
- elgg_get_entities_from_annotation_calculation
- elgg_annotation_exists

**Comment by jdalsem** [comment]
There has been a seperation of table logic vs service handling in #11403. This is enough for now.
