### ISSUE TITLE
Make jQuery available as its independent AMD libraries

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7099]
Since jQuery 2.0, it's been possible to include the various individual AMD modules independently without necessarily pulling down the whole thing lib.

Could be good to just expose all these AMD modules and then depend on only the individual pieces we need (if we even need it anymore for Elgg 2.0)...

**Comment by jdalsem** [comment]
Do this also for jquery-ui as mentioned in #7191

**Comment by ewinslow** [comment]
Relevant: http://developer.telerik.com/featured/jquery-using-only-what-you-need/

**Comment by ewinslow** [comment]
This should be trivial now that we can register whole views directories in arbitrary locations.

The rub is going to be that the deep AMD structure might actually slow things down unless we do something fancy to preload the individual modules.

**Comment by mrclay** [comment]
Loading `jquery` would make [around 30 requests](https://github.com/jquery/jquery/blob/master/src/jquery.js). I think this will be prohibitively slow for the vast majority of sites.

**Comment by ewinslow** [comment]
Closing this as I don't see anyone using the independent libraries anyways.

We can revisit once http2 gets better adoption...
