### ISSUE TITLE
remove type prefixes from static views

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7103]
Right now we are putting different types of resources under different prefixes:

- `css/elgg/component/*` for CSS
- `js/elgg/component/*` for JS
- etc...

But with web components, what you really want is to put all the resources for a single component in one directory so they can live really close to each other:

```
elgg/component/
  styles.css
  behavior.js
  template.html
```

I fear that there is probably not a way to do this until 2.0

**Comment by jdalsem** [comment]
i am not considering this a very important issue...

**Comment by ewinslow** [comment]
Same, unfortunately
