### ISSUE TITLE
Move to PSR-4 autoloading in core and plugins

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7117]
Basically for core this would just mean we can remove the `Elgg` from the directory structure, which is minor but still a nicety. It also would more clearly discourage any more classes prefixed with Elgg but not PHP-namespaced.

However, this will have slightly bigger benefits for plugins (ours and 3rd-party), which will tend to have deeper namespaces (e.g. for official Elgg plugins: `Elgg\Plugin\`).

**Comment by jdalsem** [comment]
Currently we support PSR-4 autoloading in Core and  3rd party plugins. However we are not going to make sure all our base classes also are namespaced. The amount of work changing this can not be justified by the 'benefits' of less deep folder structures.
