### ISSUE TITLE
The "friend" relationship type is a source of confusion

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7144]
Consider that the user Joe friends the user Jane. "Joe friended Jane" is an unambiguous statement, but we currently store this as the very ambiguous relationship "Joe is a friend of Jane". This could mean 3 things:
1. Jane considers Joe a friend of hers
2. Joe has offered his friendship to Jane
3. Joe thinks Jane would consider him a friend

If you want to show Jane her friends, the ambiguity means you don't know if she would be the subject or the target in the relationship.

Hence I recommend we rewrite "friend" to "friended", as in the unambiguous "Joe friended Jane".

At the very least we should clarify this issue in the docs somehow. See also #2748

**Comment by jdalsem** [comment]
Closing this as the amount of work an re-education of current developers are not beneficial over the 'clearer' way of wording for the relationship.
