### ISSUE TITLE
configurable icon_sizes vs. relying on existence of icon_size keys

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7153]
With #7088 the hardcoded usage of icon_sizes keys was removed from the default.php views. Within the Elggx_Badges plugin I'm overriding the user's default.php view and at upgrading the view to match the new default.php the following made me think there's a little flaw in allowing to configure the icon_sizes array complely freely:
```php
$size = elgg_extract('size', $vars, 'medium');
$icon_sizes = elgg_get_config('icon_sizes');
if (!array_key_exists($size, $icon_sizes)) {
	$size = 'medium';
}
```
Size medium is the fallback size here (but other sizes might be used as fallback elsewhere). But how to guarantee that any icon_size key is really defined? Adjusting the size for the different keys is only one thing you can do when configuring the icon_sizes array (and changing the sizes might result in other issues with layout / CSS I don't want to refer to here). In principle you could also change the array keys of the icon_sizes array for example via settings.php.

Would it be worth to write down at least in the docs that you shouldn't change the array keys (or only add new keys but not modify or remove the existing keys)?

**Comment by hypeJunction** [comment]
I don't think this is relevant anymore.
