### ISSUE TITLE
Implement a test for correct naming (county codes used) of language files

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7154]
This is a continuation / separate summary of the discussion started at #7146.

Problem: currently there is no definite (Elgg) standard of how to deal with country codes with more than 2 characters (e.g. pt_BR or ja_JP). Also there is no test to make sure than any language file pulled from Transifex is named correctly and to test if there might be language files included for basically the same language but using short and long country code respectively (e.g. pt/pt_PT or ja/ja_JP).

The necessity to decide on a (new) standard / list of supported languages has already been pointed out in #6856 (still open) as ISO 639-1 is outdated. A test of correct naming seems an additional necessity now as language files are already pulled in from Transifex.

For implementing a test it seems necessary to:

* decide on a standard of supported languages / country codes. While the language codes used by Transifex are no official standard it seems a likely choice right now with relying on Transifex.

* adding the list of country codes somewhere to be useable for the test (currently the country code language strings are included in the main language file but the list is limited to two-character codes. I don't know how this list could be used for a test, so a separate updated list might be necessary or the language strings should be saved separately. Indenpendently of a test it seems necessary to update the county code language strings anyway to also include the new languages).

* decide on a language file naming convention. First of all the naming convention has to be based on the country codes standard in use. But it's also necessary to decide on how upper/lower case issues are to be dealt with (currently upper case letters in language file names are converted to lower case). And it's to be decided on how non-letter characters are handled (currently there's a differentiation between "_", e.g. pt_BR.php, and "-"). In connection with deciding on a naming convention it might also be worth taking #6712 into account that arised with Elgg 1.9.

* implement the test itself. Well, I've no idea how to even start with that as I've never done that...

**Comment by mrclay** [comment]
See #8683

**Comment by iionly** [comment]
Test provided by https://github.com/Elgg/Elgg/pull/8954.
