### ISSUE TITLE
<elgg-button> html component

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7166]
This is a discussion about the API for a hypothetical `<elgg-button>` component that could simplify how buttons are rendered on Elgg sites (or any sites, for that matter). Note that discussing how it is implemented (with Angular, react, Polymer, whatever) is not really in scope, since it could potentially be implementated in any or all of those frameworks. 

This is the beginning of our switch to JS-rendered UI, and I think having a solid button component is going to be a basic necessity for that.

We simply want to ask the question:
 * Is this component worth doing?
 * What general feedback on the API?
 * Might this make sense to distribute as its very own thing, separate from Elgg core, and billed as a replacement/extension of the browser's <button> tag?

Basic API summary:

```html
<elgg-button type="{{default | danger | confirm | share | cancel | special | link}}"
                     size="{{small | default | large}}" href?>
  {{label}}
</elgg-button>
```

Differences from the default browser `<button>`:

 * `type` is used primarily for styling, to promote a consistency between the visual presentation of the button and the semantic significance of the action that will be performed when the button is clicked.
 * `size` is new and allows growing/shrinking the button appropriately. mostly in terms of font-size/padding.
 * Accepts an `href` attribute, in which case it will behave like an `<a>` tag (but still visually looks like a button).

Differences from existing elgg button:

Uses an html element instead of just classes. This provides a higher-level API and allows us a little more freedom over the implementation. I.e. you could map the Elgg API to ionic's button or bootstrap's button. You can't do this currently with the class-based implementation.

**Comment by jdalsem** [comment]
Closing this as we are going to use regular buttons for buttons https://github.com/Elgg/Elgg/pull/10464
