### ISSUE TITLE
Have users send email invites through their own email app

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7171]
http://www.useronboard.com/how-mailbox-onboards-new-users/ (slide 62).

Benefits of letting users compose the invite message in their mail app of choice:
- Contacts autocomplete because their email client already knows their contacts
- Dramatically lower chance of invite email bouncing or getting filtered to "promotions" since it's from a real person instead of whatever mail server Elgg is running on.
- Inviter can customize and personalize the message instead of being artificially limited to text (since it's not from the Elgg app, we dont need to worry about malicious users include something malicious in the invite text and making the Elgg site look bad).

**Comment by ewinslow** [comment]
Downside of this is that the os email app may not be configured to their email app of choice. E.G. if they use Gmail but OS opens some stock mail Client.

This seems exceedingly unlikely on mobile and potentially very common on desktop.

**Comment by jdalsem** [comment]
This can be easily created as a plugin. Not going for this in core at this moment
