### ISSUE TITLE
Skype URI not recognized by elgg_normalize_url()

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#7178]
When creating a menu item or display Skype URI in widgets the URI is distorted.

This could be fixed similar to handling the mailto: URI

My skype plugin now has to trick  ElggMenuItem::factory to show the URI in the text area. This results in double <a> tags which violates the HTML standard.

This can be easily solved changing this line in the function elgg_normalize_url()

 } elseif (stripos($url, 'javascript:') === 0 || stripos($url, 'mailto:') === 0 ) {

into

 } elseif (stripos($url, 'javascript:') === 0 || stripos($url, 'mailto:') === 0 || stripos($url, 'skype:') === 0) {

**Comment by jdalsem** [comment]
@mrclay do you still have that PR lying around?

**Comment by jdalsem** [comment]
this is no longer an issue
