### ISSUE TITLE
jquery-ui AMD shim

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7191]
I am working with some AMD modules that define their depencies as ```jquery-ui/sortable```. Perhaps we should shim jquery-ui and provide a list of exported widgets

**Comment by jdalsem** [comment]
can we also add the complete ui library then instead of a custom?

**Comment by hypeJunction** [comment]
I am with @jdalsem on this. Let's include the full library with stylesheets (or at least have the stylesheets somewhere in the vendor lib so that they can be included without having to roll out a theme with the correct UI version etc).

**Comment by beck24** [comment]
ugh, yes, I'm tired of unregistering and reregistering jquery-ui stuff.  Lets get it all in there, even if it's not all loaded by default.

**Comment by jdalsem** [comment]
Added it as an extra task to #7099
