### ISSUE TITLE
Move media queries from aalborg/css to css/elements/*

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7223]
Most of the media queries in Aalborg theme are located in ```views/default/aalborg/css.php```. They should be moved to each respective file under ```views/default/css/elements/*```.

1. It would be easier to find the media query definitions if they were in the same file as the default definitions for each element.

2. Having them in a non-core view file causes problems if a custom theme extends Aalborg. How to reproduce:
  - Custom theme is located after Aalborg in plugin list (since it is overriding it)
  - Custom theme extends on of the core views ```css/elements/*.php```
  - The styles in ```css/elements/*.php``` now get included *after* ```aalborg/css.php``` in the view priority, so some of Aalborg's media query definitions do not take effect breaking parts of the responsive layout

**Comment by ewinslow** [comment]
@juho-jaakkola what's the latest on this? Is it possible to do in a backwards compatible way?

**Comment by juho-jaakkola** [comment]
The 2. point wasn't a problem. But IMO it's confusing that multiple css files have definitions for the same selectors.

There's no backwards compatible way, so Elgg 2.0 it is. (Although we *did* agree that view contents are not considered API.)

**Comment by ewinslow** [comment]
That was for HTML. CSS is different, I would think

**Comment by mrclay** [comment]
No longer relevant #10385
