### ISSUE TITLE
Failed to upload avatar larger than 4 mb

### ISSUE THREAD

**Issue by lianglee** [Elgg/Elgg#7224]
Failed to upload avatar larger than 4 mb

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 21596 bytes) in /lib/filestore.php on line 150

Elgg 1.9.1

**Comment by hypeJunction** [comment]
I am closing this issue. Imagine is soon to be in core, there isn't much we can do about memory issues.

**Comment by hypeJunction** [comment]
Image orientation #10280
