### ISSUE TITLE
404 response for favicon.ico should be minimal

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7261]
If you go to yoursite.com/favicon.ico and there is not favicon.ico file, Elgg will handle it as a pagehandler allowing plugins to provide the image for example. But if no one returns an image Elgg will draw a 404 html page (loading the shell and all). This could provide some problems, for example on walled garden pages. I would suggest that Elgg low priority page handler (or hook) to return no data (html) if noone else registers an icon

**Comment by ewinslow** [comment]
I think we should just focus on favicon.ico as a special case and make that work better. We can address the others when we get to them. We don't have to solve the general case to make a significant improvement here.

**Comment by mrclay** [comment]
:+1:

**Comment by mrclay** [comment]
PR #7760
