### ISSUE TITLE
Elgg lightbox is failing to detect the image mimetype

### ISSUE THREAD

**Issue by teamwebgalli** [Elgg/Elgg#7279]
Elgg lightbox is failing to detect mimetype when images are loaded inside lighbox. Setting the photo:true as explained here http://stackoverflow.com/questions/11923290/colorbox-unable-to-display-dynamically-generated-image works.

**Comment by beck24** [comment]
Additionally I've found that simply appending anything with an image-like extension to the url works.

eg. [url]/file/download/123456?foo=test.jpg

**Comment by juho-jaakkola** [comment]
You can force lightbox to handle content as image either by:
 - Setting the option: ```photo: true```
 - Giving the triggering element the class: ```elgg-lightbox-photo``` (instead of just ```elgg-lightbox```)

So I'd say this is working as intended. Reopen if you disagree.
