### ISSUE TITLE
Elgg's default theme going forward

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#7328]
Aalborg theme has been well received (it makes me happy) and seems to be regarded as the new default theme. But actually and so far it's just a plugin / theme. It's a designer's suggestions on how he feels Elgg should look like.

I would like to hear what you guys imagine about Elgg's default theme going forward.

One can imagine that Elgg include an acceptable theme in the core, like the current, and additionally includes the official theme as a plugin (aalborg_theme). The official theme must be renewed periodically and can be created by an interested designer chosen / contacted by the core team. Just like it happened with Aalborg theme.

I believe that it is better to release a brand new theme once in a while instead of adjusting the existing, unless there is obvious bugs.

The next theme could come with version 1.10 or 2.0. I think it will be exciting with different designers' contributions to Elgg's look over time. This is how wp does, I think.

What do you think?

**Comment by jdalsem** [comment]
My suggestion:
- from 1.11: fresh install has Aalborg default enabled
- from 1.11: Aalborg gets a few color schemes
- from 2.0: Drop core theme in favor of Aalborg (no longer a plugin)
- from 2.0: Add a new theme as a plugin

**Comment by jdalsem** [comment]
i maybe have a designer that could provide a new theme for 2.0

**Comment by juho-jaakkola** [comment]
I would very much like to have the official theme in its own repository, so it could be easily forked.

**Comment by jdalsem** [comment]
still i would like to drop the current default layout in favor of the aalborg theme.

Maybe we can force that there is minimal 1 theme plugin enabled

**Comment by hypeJunction** [comment]
Perhaps one thing we should be working on is converting the theme to less or scss,

**Comment by PerJensen** [comment]
:+1:

> from 1.11: fresh install has Aalborg default enabled
> from 2.0: Drop core theme in favor of Aalborg (no longer a plugin)
> from 2.0: Add a new theme as a plugin
>
> i maybe have a designer that could provide a new theme for 2.0

**Comment by jdalsem** [comment]
so no colorschemes @PerJensen ?

**Comment by PerJensen** [comment]
I was thinking that could go in its own plugin.

**Comment by jdalsem** [comment]
the "Aalborg Color Scheme Changer" plugin... also a good idea

**Comment by ewinslow** [comment]
+1 for keeping the theme in its own plugin.

**Comment by jdalsem** [comment]
@ewinslow plugin is fine by me, but how about the default Elgg look and feel?

**Comment by ewinslow** [comment]
barebones. Almost no CSS. Resets/normalize perhaps.

**Comment by PerJensen** [comment]
@ewinslow Do you want to keep aalborg as a plugin instead of moving it to core
Do you want to replace aalborg with new theme-plugin in 2.0 or have two theme-plugins?

**Comment by ewinslow** [comment]
Keep Aalborg as plugin. Merging to core is busywork with no benefit. I
don't think the core "theme" needs to do anything meaningful at all,
really. Just make sure we have a bundled theme included and enabled by
default.

**Comment by ewinslow** [comment]
Two theme plugins is my preference

**Comment by jdalsem** [comment]
Ok, resume:
- create ticket to make Aalborg Theme default enabled (for 1.x)
- create ticket to switch to a bareboned core css (for 2.x)
- create ticket for creation of new theme for 2.0 release

Agree?

**Comment by ewinslow** [comment]
SGTM

**Comment by juho-jaakkola** [comment]
Should we have the new theme it's own git repository? That way updates could be directly merged into customized themes built on top of it.

I'm not sure if merging would work on highly customized themes (merge conflicts), but even in those cases it would be easier to compare what has changed.

**Comment by ewinslow** [comment]
New theme in own repository, yes

**Comment by jdalsem** [comment]
Closing this discussion as there are now seperate tickets for the different tasks
