### ISSUE TITLE
Travis - Commit message test

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7344]
Whenever I squash commits, original line breaks are removed, so I end up with long commit descriptions.

```
Checking commit message for 97cfd58f57bda23ae9e659638adc4b079846d623 ... Fail
Longer than 160 characters at line 3
     1	deprecate(filestore): deprecate file_get_simple_type() and file_get_general_file_type()
     2	
     3	Deprecate file_get_simple_type(), found in mod/file/start.php, and file_get_general_file_type(), found in engine/lib/filestore.php in favour of a pluggable elgg_get_file_simple_type() added to core api
./.scripts/validate_commit_msg.php exited with error!Checking commit message for 6b0d505d7cf0beb6841fcf3ee671e14deeeeafe0 ... Ok
```

Is there any way to automatically collapse long commit descriptions?

**Comment by jdalsem** [comment]
I have no idea how to handle this and Elgg will probably not change your commit message when submitting a PR, so i think you should solve it with your own software. Maybe @Srokap has a great idea, but for now i am closing this ticket
