### ISSUE TITLE
FR: general comment entity menu item

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#7356]
In the river a comment item is added to the menu if $object->canComment(),

why is this not added to the entity menu?
- [x] add general entity menu hook to add menu item
- [x] add a general id to the comment listing so the link can jump to the comments

**Comment by jdalsem** [comment]
@jeabakker i believe this ticket can be closed... please investigate

**Comment by jeabakker** [comment]
yes fixed in #11297
