### ISSUE TITLE
Make ACCESS_* constant labels more intuitive

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7363]
Keys for access labels are not intuitive enough. 

``` php
    $access_array = array(
        ACCESS_PRIVATE => elgg_echo("PRIVATE"),
        ACCESS_FRIENDS => elgg_echo("access:friends:label"),
        ACCESS_LOGGED_IN => elgg_echo("LOGGED_IN"),
        ACCESS_PUBLIC => elgg_echo("PUBLIC")
    );
```

Several options:
- use shortnames we use elsewhere, and namespace differently `'access:label:friends', 'access:label:private', 'access:label:logged_in', 'access:label:private` etc
- use constant values - `'access:label:'. ACESS_FRIENDS, 'access:label:'.ACCESS_PRIVATE`

**Comment by jdalsem** [comment]
vote for shortnames... simple one to tackle for Elgg 2.0

**Comment by ewinslow** [comment]
This does not have to be BC breaking. I think if we want to rename language keys we should come up with a similar BC system as views where we can alias one key to another to avoid breaking people.

**Comment by ewinslow** [comment]
Since it's not BC breaking, it doesn't need to block 2.0
