### ISSUE TITLE
Decide either to remove or fully support multisite

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7372]
Elgg has never officially had a full multisite support. There are however both core features and open issues about it.

Let's decide either to:
- Drop multisite support completely
- Start working on making it less of a hassle to try to maintain one

Neither necessarily needs to happen anytime soon, but it would be nice to have a clear direction.

**Comment by twentyfiveautumn** [comment]
What can I do with multisite that I can't do with a single site. Seems like unless they were all small sites performance would suffer rapidly. I'm sure there's more to it that I don't understand though.

**Comment by jdalsem** [comment]
I think i changed my mind regarding multisite implementation in Elgg. There is no real benefit in a shared database if there is no shared functionality between those sites. The current (partial) implementation of multisite in Elgg is limited to the concept of a Site entity where other Entities can exists on (site_guid in the tabels). There is no other feature in Elgg related to this concept. There is no management tool to create multiple sites. This has to come from other tools / plugins.

There is no documented way on how one should access another site, (other than the default) on an Elgg installation.

Besides the lack of features in core for a multisite implementation (where different sites use the same database), there is also the (performance) downside of having one big database for all data. I currently think it is easier and more future proof to have a seperated database for each website.

The downside of this approach is that you have to put in more effort if the sites share information (like accounts or notifications/messages) or features. But there are multiple solutions for these problems.

There are currently multiple flaws in the Elgg system related to multisite. And my current stance on this subject is to **remove multisite** completely from the system. I think it would be a good plan to remove this in Elgg 3.0. Does anyone have an opinion on this matter?

Removing it would mean

- Dropping the site_guid columns
- Removing support for site_guid(s) in egef* functions
- Removing site_guid from Entity classes
- Removing ElggSite functions to get Entities located on the site
- Updating AccessCollections code
- Updating Config Class code
- Breaking/Fixing tokens generation code
- Webservices plugin needs attention
- a lot of core functions have a site_guid parameter
- do we offer a migration process if you have multiple sites???

Benefits of removing multisite

- No need to fix the broken implementation
- Less/No debate on how multisite issue should be solved in core
- One less where clause in queries
- Less code to read/maintain
- We could be clear about what Elgg advises on multisite implementations

**Comment by mrclay** [comment]
My favorite option: document prominently that MS isn't supported and site_guid should only be set to 1 and should not be read. Anywhere there's a site_guid argument, add a `@link` to those docs. Removal would be tons of work, would break a ton of plugins and core stuff (our test coverage is small) for little gain.

**Comment by mrclay** [comment]
...Though I think we could remove things like `WHERE site_guid` clauses without changing the API.

**Comment by jdalsem** [comment]
I am not happy with just documenting that it is not supported. We could leave site_guid function params intact in functions to not break all the code, but we should remove the code that uses the site_guid.

Currently we have traces of some kind of experimental support for multisite in the code... we should get rid of that. I think the amount of work to remove this is not that much.

Removing all traces or just documenting the fact that we are not supporting MultiSite, we at least should be much clearer about it. Therefore we first need to make the decision if we want it out or in. How do we organize a vote for this?

**Comment by hypeJunction** [comment]
Before voting, I would like to see at least one example of a site that uses multisite.

**Comment by jdalsem** [comment]
We created a multisite community on www.pleio.nl (still on Elgg 1.8) with over 600 sites. 

Elgg core was customized to 'fully' support multisite. They share code, database and dataroot

**Comment by hypeJunction** [comment]
So, why drop rather than make it full support?

**Comment by jdalsem** [comment]
As it will take a lot of discussion and work to make it fully supported and i do not think having multisite support in the database is a good approach on multisite installations

**Comment by jdalsem** [comment]
Multisite is gone

**Comment by philosofree** [comment]
Hi Jerome,
I am not sure if Elgg multisite is what I need, so i will ask the question though it has gone now anyway.
What I want to do is have a different site main page with a different menu for users to access EITHER group registration and control OR member registration and control.
I want the same database for both.
Can I achieve this now that multisite is gone?
thanks
Phil

**Comment by philosofree** [comment]
If so, how do I proceed, because I can find no documentation on how to do this?

**Comment by hypeJunction** [comment]
@philosofree, best to be asked on the community site. I am sure there is a way, just provide more info on the differences between the two.

**Comment by philosofree** [comment]
thank you ismayil i will do that

*Abundant Life! *
*Phil Cheney*
+1 6479384043
phil@philcheney.com
Skype: PhilCheney
Facebook <http://www.facebook.com/PhilosofreeCheney>     LinkedIn
<http://ca.linkedin.com/in/philosofree/en>    Blog
<http://www.diamondmine.me/blog/>
Author/coach Website: philcheney.com or my.advantace.com
Art, Music and Writing: art.advantace.com
Construction: trade.advantace.com
Publishing: publishing.advantace.com
Products : Books
<http://www.amazon.com/Phil-Philosofree-Cheney/e/B00PPG8R9A> Music CDs
<https://www.createspace.com/2263483>
