### ISSUE TITLE
ECML: question of life and death

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7375]
There seems to be opposition to keeping ECML alive, as noted in #3360
I have grown to like ECML as it allows to safely embed content that would have otherwise been stripped off by htmlawed. Obviously there are pitfalls, but I would like to see this functionality stay alive, or otherwise I would be interested in hearing ideas about how to implement a similar functionality.
One of the options is oembed, but that only covers URLs. The beauty of ECML is that it allows rendering content based, e.g. on entity guid.

`[elgg guid="123" full=1]`

**Comment by hypeJunction** [comment]
I have since played with the idea of URLs and ECML can happily die. As long as the current repo is around to help migrate existing tags.

**Comment by beck24** [comment]
ok, it's been answered then!  ECML will die

**Comment by hypeJunction** [comment]
I am reopening this. Let's get ECML into core, but with a slightly modified approach. Instead of using hooks, we map ecml tags to views, which control which attributes are too be used/ignored.

```
[player src="https://www.youtube.com/watch?v=G_Qt7fyaGKk" width="500"]
```

```php
// views/default/ecml/player.php
$src = elgg_extract('src', $vars);
$width = elgg_extract('width', $vars);

$params = []; // prepare params
echo elgg_format_element('iframe', $params);
```

**Comment by jdalsem** [comment]
Like!!

**Comment by mrclay** [comment]
Pardon my ignorance, where does ECML get parsed/replaced? E.g. looking at the output/longtext view, it seems like parse_urls could interfere with ECML markup, and autop could interfere with ECML output (maybe unavoidable).

**Comment by hypeJunction** [comment]
I think you specify views whose output is then scanned for ecml and expanded

**Comment by mrclay** [comment]
So in practice just like "output/longtext". If your ECML attribute has a URL surrounded by spaces, parse_urls will mangle it, and elgg_autop will always add unneeded `<p>`s around the ECML substitution. Imperfect but acceptable.

**Comment by hypeJunction** [comment]
Yeah, there is some work to be done

**Comment by hypeJunction** [comment]
In reference to @mrclay 's concern, I was asked to fix a related bug. Posting temp solution for future reference

```php

elgg_register_plugin_hook_handler('view_vars', 'output/longtext', 'mf_embed_custom_url_parse', 999);

/**
 * Implement custom URL parsing to avoid rewriting ECML tags
 *
 * @param string $hook "view_vars"
 * @param string $type ECML view
 * @param array  $vars View vars
 * @return array
 */
function mf_embed_custom_url_parse($hook, $type, $vars) {

	$parse_urls = elgg_extract('parse_urls', $vars, true);
	if (!$parse_urls) {
		return;
	}

	$value = elgg_extract('value', $vars);
	if (!$value) {
		return;
	}

	// parse urls excluding ecml tags
	$callback = 'mf_embed_url_parse';
	$regex = '/<a[^>]*?>.*?<\/a>|<.*?>|\[.*?]|(^|\s|\!|\.|\?|>|\G)+(h?[t|f]??tps*:\/\/[^\s\r\n\t<>"\'\)\(]+)/i';

	$value = preg_replace_callback($regex, $callback, $value);

	$vars['parse_urls'] = false;
	$vars['value'] = html_entity_decode($value, ENT_QUOTES, 'UTF-8');
	return $vars;
}

/**
 * Callback function for url preg_replace_callback
 *
 * @param array $matches An array of matches
 * @return string
 */
function mf_embed_url_parse($matches) {
	if (empty($matches[2])) {
		return $matches[0];
	}

	$text = $matches[2];
	return $matches[1] . elgg_format_element('a', array(
				'href' => $matches[2],
				'rel' => 'nofollow',
					), $text);
}
```

**Comment by mrclay** [comment]
Life? Death? Something will happen with ECML someday, but removing from milestone.

**Comment by hypeJunction** [comment]
I am planning to fork ecml and deal with it on my own terms

**Comment by jdalsem** [comment]
ECML features have been removed in Elgg 4.0
