### ISSUE TITLE
Consolidate "viewtype" and "format" concepts

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7376]
Steve just started work on #2815 in #7360, which opens up the possibility of having lots of different renderings for the same object in a single viewtype. It occurred to me that this is almost exactly what the "viewtype" system is for in the first place. So I figured: why not explore whether we could merge the two?

This would prevent viewtype/format confusion by consolidating on a single "format" concept.

It's bothered me for a while now that our view structure is like:

```
views/{format}/{view}.php
```
- It feels backwards: format (viewtype) comes at the end of the filename in every other context, not the beginning
- It forces related code to be very separated from each other. It's easy to forget that the other viewtypes exist, and it's difficult to keep them up to date

What if we could change it to this?

```
views/{view}.{format}.php
```

If format == 'default', then you just leave it off entirely.

So instead of:

```
views/default/object/entity/link.php // part of Steve's work
views/default/object/entity.php
views/rss/object/entity.php
```

You'd just have:

Option 1: separate the format with dots (`.`):

```
views/object/entity.php
views/object/entity.link.php
views/object/entity.rss.php
```

Option 2: separate the format with slashes (`/`):

```
views/object/entity.php
views/object/entity/link.php
views/object/entity/rss.php
```

**Comment by mrclay** [comment]
I prefer the option 1 above, but I'm not sure where to begin on this.

**Comment by ewinslow** [comment]
We could have something in the plugin manifest that opts the plugin in to the new structure.

**Comment by ewinslow** [comment]
There would be no special handling of viewtypes during the view registration phase, only during rendering.

**Comment by jdalsem** [comment]
we are not going to pursue this at the moment
