### ISSUE TITLE
Deprecate plugin settings

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7403]
It feels like a bad idea to have metadata/settings attached to plugins. If you switch between equivalent plugins, you lose the data. That seems sad and not very interoperable.

Why not just configure all settings on the site entity with namespaces?

Same thing with usersettings. It's non-trivial to have interoperability with data when the info is specifically attached to the particular plugin that created it.

**Comment by jdalsem** [comment]
I think the usecases where similar plugins use the exact same settings are very rare. Closing this issue as there is no direct benefit. Reopen if you disagree
