### ISSUE TITLE
posts to thewire need to be checked for duplicates

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#7432]
1. write a post to the wire in thewire's posting box
2. click 'send' / 'submit'
3. click 'send' / 'submit' again  quite quickly (as  may occur accidentally or due to a harware / timing glitch).

the wire post is now submitted twice, instead of the double submission being detected or prevented.

i was seeing occaisional double entries in thewire stream and this is my best guess as to the cause.

**Comment by jdalsem** [comment]
Closing in favor of the more generic approach in #5984
