### ISSUE TITLE
Update core plugins to use class autoloading instead of elgg_*_library

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7445]

**Comment by ewinslow** [comment]
This only makes sense to do if we want to extract all plugins to their own repos.

@Elgg/owners in the past we have been against that splitting. How do we feel about it now?

**Comment by mrclay** [comment]
I vaguely remember 3rd party plugins calling load library for bundled plugins, which we should definitely put an end to in 2.0. Besides that I don't see a big gain here.

**Comment by ewinslow** [comment]
Not really worth it. Closing.
