### ISSUE TITLE
Need a better friends picker view

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#7463]
The current picker has issues with scalability (loads all user friend entities) and possibly translations (https://community.elgg.org/discussion/view/1928557/friends-picker)

I suggest an entity picker (like userpicker view) that simply limits to friends.
Alternately/including a visual picker with ajax pagination and text filter.  Essentially the way FB does it.

**Comment by jdalsem** [comment]
@hypeJunction was this fixed by #10307?

**Comment by hypeJunction** [comment]
Yes, it uses userpicker
