### ISSUE TITLE
Tag-like content stripped from email

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7480]
For #889 HTML decoding was added to emails, but unfortunately this was placed *before* elgg_strip_tags. In effect, non-tag HTML content like `&lt;joe@example.org&gt;` gets turned into a tag, and so is then stripped away inadvertently.

**Comment by ewinslow** [comment]
This still an issue?

**Comment by mrclay** [comment]
Yes. https://github.com/Elgg/Elgg/blob/master/engine/lib/notification.php#L675 elgg_strip_tags() needs to come *after* html_entity_decode().
