### ISSUE TITLE
intermittent script errors - requirejs

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#7483]
i've been seeing several variations of requirejs related errors appearing in the firefox console here. they usually appear once the page has loaded and are of this type:
```
Error: Script error for: http://mysite.tld/ajax/view/js/languages?language=en&lc=1415992254
http://requirejs.org/docs/errors.html#scripterror
```
i have disabled every plugin and just kept several core ones active (blog, groups, bookmarks, file, htmlawed, invite friends, likes, members, messages, the wire) and the errors still appear from time to time. if i sit with two browsers open, looking at the console output and repeatedly refresh the pages over and over, i will see an error of this type within a minute or so.
before i disabled many other plugins that i am testing with 1.9 i was also seeing one that relates to a timeout - http://requirejs.org/docs/errors.html#timeout

i am new to AMD and 1.9, so not sure where to start with this.

**Comment by jdalsem** [comment]
Fixed in #7885
