### ISSUE TITLE
Crazy brain dump: Event streams as replacement for hooks/events

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7494]
Idea is to replace this kind of nested if logic:

``` php
elgg_register_plugin_hook_handler(...);
function discussion_notification_email_subject($hook, $type, $returnvalue, $params){
    /** @var Elgg\Notifications\Notification */
    $notification = elgg_extract('notification', $returnvalue['params']);
    if ($notification instanceof Elgg\Notifications\Notification) {
        $object = elgg_extract('object', $notification->params);
        if ($object instanceof ElggEntity) {
            if ($object->getSubtype() === 'groupforumtopic') {
                $returnvalue['subject'] = $object->getDisplayName();
            }
            $container = $object->getContainerEntity();
            if (($container instanceof ElggEntity) && ($object instanceof ElggComment)) {
                $returnvalue['subject'] = 'Re: ' . $container->getDisplayName();
            }
        }
    }
    return $returnvalue;
}
```

With this kind of thing instead:

``` php
$onSystemEmail->forEach(function($email) {
  // All the above logic
});
```

Now that the individual hook is an object, we can remove if-statements and assignments by using `filter` and `map` respectively. Instead of:

``` php
/** @var Elgg\Notifications\Notification */
$notification = elgg_extract('notification', $returnvalue['params']);
if ($notification instanceof Elgg\Notifications\Notification) {
  $object = elgg_extract('object', $notification->params);
  // ...
}
```

You can do:

``` php
$notificationObjects = $onSystemEmail
    ->map(function(EmailEvent $email) { return elgg_extract('notification', $email['params'])})
    ->map(function(Notification $notification) { return elgg_extract('object', $notification->params); });
```

Then you can replace this further logic:

``` php
if ($object instanceof ElggEntity) {
    if ($object->getSubtype() === 'groupforumtopic') {
        $returnvalue['subject'] = $object->getDisplayName();
    }
    $container = $object->getContainerEntity();
    if (($container instanceof ElggEntity) && ($object instanceof ElggComment)) {
        $returnvalue['subject'] = 'Re: ' . $container->getDisplayName();
    }
}
```

with more of this style:

``` php
$groupForumTopics = $notificationObjects->filter(function(ElggObject $object) { return $object->getSubtype() == 'groupforumtopic'});
$groupForumTopics->forEach(function(ElggObject $object, &$result) { $result['subject'] = $object->getDisplayName(); });

$comments = $notificationObjects->map(function(ElggComment $object) { return $object->getContainerEntity(); });
$comments->forEach(function(ElggEntity $container, &$result) { $result['subject'] = 'Re: ' . $container->getDisplayName(); });
```

So you can treat the hooks/events like a collection. Note that this is entirely optional.

Just something I've been exploring recently. Some of the benefits:
- Stronger typing. Each event(stream). The string,string approach to identifying hooks/events does not allow you to type-hint very well, which results in a lot of repetetive/defensive `instanceof` checks.
- Less control structure logic (if/else/foreach). More declarative.
- Can pass filtered/altered event streams as arguments without duplicating the logic or forcing clients to know about and call the correct function.
- Can be exposed via the relevant parent object (e.g. the Elgg\Database object can have onCreate, onUpdate, etc.), instead of through a central, global service that anyone can publish/subscribe to. Makes dependencies/relationships clearer/safer.
- No more null/instanceof checks. instanceof is replaced by type-hinting and nulls are automatically filtered out (unless a default argument `= null` is provided).
- Strong typing and eventstreams-as-objects helps solve the hook/event documentation problem #6111

Drawbacks:
- A little intimidating for those used to straight up if/else logic.

Rebuttals:
- Can still use if/else logic if that is preferred. For example, these are equivalent:

``` php
$onSystemEmails->forEach(function($thing) {
  if ($thing instanceof Foo) {
    // dosomething
  }
});
```

``` php
$onSystemEmails->forEach(function(Foo $thing) {
  // dosomething
});
```

The forEach could be bikesheddable to `subscribe` or `listen`, but I figure it was easiest if we just make them look like collections.

**Comment by jdalsem** [comment]
Closed in favor of #14117
