### ISSUE TITLE
ElggFile objects do not respect dataroot config

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7498]
I don't have time to investigate this further right now, but it seems that `ElggFile` objects save the dataroot into metadata called `filestore::dir_root`: https://github.com/Elgg/Elgg/blob/1.9/engine/classes/ElggFile.php#L381

I moved the dataroot of a site and updated `$CONFIG->dataroot` accordingly. Some ElggFiles are however still trying to find the file from the directory saved as metadata.

Because of this some files cannot be accessed at all.

**Comment by jdalsem** [comment]
@jeabakker can you investigate this now that you are working on the filestore?

**Comment by jeabakker** [comment]
this metadata was removed in #9364 and as mentioned before migration is documented here http://learn.elgg.org/en/stable/admin/duplicate-installation.html#change-the-filestore-data-directory
