### ISSUE TITLE
Previously "ON" comments turned to "OFF" still shows in the river

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#7516]
When a blog owner sets previously "ON" comments to "OFF"  the comments are not shown in the content page, which is okay and correct BUT the comments still show in the river -expected behavior is comments should no longer be shown in the river, as the purpose of the content-owner is now not to show the comments anymore to anyone. The "disappearance" of comment is expected to be in sync.

Using latest 1.9.x Elgg, and just core modules.

**Comment by jdalsem** [comment]
We could also change the behaviour on the content pages... show the comments but disable adding new comments. That way river and entity comment listing is 'in sync'.

**Comment by mrclay** [comment]
It's not clear what behavior is ideal here.

One option: store comment access_id in ->off_access_id and make them private. That would at least allow admins and their authors to see them. Switching back on would restore the access_ids.

**Comment by beck24** [comment]
I think the simplest course of action is the youtube approach.  Comments off = nothing visible, disable all existing comments.

**Comment by jdalsem** [comment]
ok, we can do this dirty on save of entity and `!$entity->canComment` disable all comments... and vice versa to enable

**Comment by hypeJunction** [comment]
I would like to distinguish between canComment permission and commentable
entity types. Comments "off" to me means closed discussion, so it feels
like this beahviour is expected.
I am going to patch canComment with some more lodic similar to likes. We
can then add a setting to blod plugin to switch between behaviors.

**Comment by mrclay** [comment]
I think disabling each comment entity is the cleanest and most reliable way to hide the comments when commenting is Off.

**Comment by mrclay** [comment]
Please see #10059. I'll add tests if this is the approach we want.

**Comment by jdalsem** [comment]
Closing this as i agree with @hypeJunction that current behaviour is as expected. Comments OFF means no comments can be created (like a closed discussion).
