### ISSUE TITLE
Metadata entries might remain in metadata table after deleting the entity they belonged to

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7518]
Use case is a class that adds metadata entries in its constructor:

``` php
class IzapVideos extends ElggFile {
    private $IZAPSETTINGS;

    public function __construct($row = null) {
        parent::__construct($row);

        // set some initial values so that old videos can work
        if (empty($this->videosrc)) {
            $this->videosrc = $this->IZAPSETTINGS->filesPath . 'file/' . $this->guid . '/' . elgg_get_friendly_title($this->title) . '.flv';
        }

        // sets the default value for the old videos, if not set yet
        if (empty($this->converted)) {
            $this->converted = 'yes';
        }
    }
```

The "videosrc" and "converted" metadata entries remain in the database after deleting the entity. Deleting the metadata entries explicitly when deleting the entity fails to work.

A related issue might have already been dealt with in the past (#5214) according to this comment in the elgg_delete_metadata() function:
    // This moved last in case an object's constructor sets metadata. Currently the batch
    // delete process has to create the entity to delete its metadata. See #5214

But it fails to work in the case described above at least and maybe in other cases, too.

**Comment by jdalsem** [comment]
Closing this in favor of #7545
