### ISSUE TITLE
Clean up memcache implementation

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7533]
We have a new backend-agnostic caching interface now (`Elgg\Cache\Pool`). We should switch all existing uses of memcache to use that and then deprecate the ElggMemcache implementation.

https://github.com/Elgg/Elgg/search?utf8=%E2%9C%93&q=memcache

/cc @mrclay

**Comment by mrclay** [comment]
PR #9080

**Comment by ewinslow** [comment]
How confident are we that the tests cover the cases that have been refactored here? The code is complex enough that it isn't obviously correct.

**Comment by mrclay** [comment]
I'm not confident in the test coverage. This should be easier to write tests for.
