### ISSUE TITLE
Elgg Core should come with full ckeditor

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7574]
Currently the ckeditor plugin provides the basic ckeditor package. I think the plugin should deliver the full package, but only load the basic needs. Allowing other plugins to extend the feature set.

http://ckeditor.com/presets

**Comment by Westlake56** [comment]
Pardon my ignorance, at ckeditor.com they show a download of version 4.4.7 (referenced above) on 27 Jan 2015 for what they call the "Full Package", full featured editor for every possible need with 72 plugins. Would this perhaps provide the upload feature right within ckeditor that many are looking for?

**Comment by jdalsem** [comment]
@Westlake56 No it will not, but you could take a look at this plugin https://github.com/ColdTrick/ckeditor_extended that unlocks that feature

**Comment by Westlake56** [comment]
@jdalsem Already using it on one of my other elgg installations, works well.
They did list a file upload plugin at the ckeditor website. At the ckeditor website they also say they use ckfinder which isn't free.
