### ISSUE TITLE
Suggest to drop site categories plugin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7584]
I suggest we drop the site categories for the following reasons:
- current implementation is completely flawed #6150 and fixing it is almost impossible
- looking at the amount of feature requests for this plugin it is probably not a really good implementation at this moment
- it is (in the current state) offering almost the same functionality as tags

If we drop this we could put more focus on improving tag related functionality instead of the categories. It is easier to add support for tags in your plugin instead of support for the site categories plugin...

What do you think?

**Comment by jdalsem** [comment]
moved to 2.0 to allow an easier "removal" of this plugin

**Comment by ewinslow** [comment]
@jdalsem Does this need to block 2.0.0 final?

**Comment by jdalsem** [comment]
@ewinslow in the current state this plugin is very buggy. We can accept that, but then we need to support that in 2.0. Removing it before hand will save us the headache i think.

**Comment by ewinslow** [comment]
OK. Should be a pretty straightforward fix...
