### ISSUE TITLE
Remove `@package` and `@subpackage` documentation requirements

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7606]
I think namespaces make it pretty clear what the package structure is. At this point these are redundant boilerplate annotations that aren't buying us anything, as far as I can tell.

**Comment by jdalsem** [comment]
do you want this removed from all files (classes/actions/etc)? Is it not needed for licensing purposes or something or phpdoc generation?

**Comment by hypeJunction** [comment]
I think we will have to update our phpcs rules first.

**Comment by ewinslow** [comment]
Maybe phpdoc, but in that case we should just mirror the namespace (and that feels like useless boilerplate)

**Comment by hypeJunction** [comment]
I remember phpcs was failing on my plugins with elgg coding standards if those were omitted. I am all in favor of removing them. They are useless given namespaces. I am not even sure how useful they are for phpdoc generators.

**Comment by ewinslow** [comment]
https://github.com/Elgg/elgg-coding-standards/blob/master/src/Elgg/Sniffs/Commenting/ClassCommentSniff.php#L20

Someone just change "required" from "true" to "false" and we'll be good.

**Comment by ewinslow** [comment]
Done. Now we can delete them.

**Comment by jdalsem** [comment]
Anybody up for the task? Assign to yourself if possible, so we know somebody is working on it.

**Comment by jdalsem** [comment]
This will be cleaned up when someone touches a class... no need to hunt them all done
