### ISSUE TITLE
Decide a plan for ElggVolatileMetadataCache

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7626]
A few people want to replace this with a simpler cache, but this class additionally adds metadata-(and access control)-specific cache invalidation logic so I think the best we can do is to have it compose a memory cache of some kind so it's not doing so much.

Or we can leave it in peace. :)

/cc @ewinslow @Srokap

**Comment by jdalsem** [comment]
@mrclay do we even have this cache now?
