### ISSUE TITLE
Support for ServiceWorker

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7631]
http://blog.chromium.org/2014/12/chrome-40-beta-powerful-offline-and.html

I was skeptical at first, thinking appcache might be sufficient, but ServiceWorkers really do look better.

We should make sure we support this somehow. Just allowing devs to load AMD modules in the service worker would be good enough for a first pass, I think.

Doesn't _really_ need to happen until Chrome Stable, but it's now in Beta so that's about 6 weeks. And our releases are 3 months apart, so I figured it worth mentioning.

**Comment by ewinslow** [comment]
So Chrome is now promoting add to homescreen for apps that meet a few criteria, one of which is service worker. I think with the progress that Chrome is making on this front they will push the web ecosystem forward and we will hopefully start to see web app UX reach parity with native apps.

One rub is that service worker only works over https. So we'll need to handle the non-https case I guess...

**Comment by brettp** [comment]
Do we want to invest time putting this in core? It's a feature that's only supported on Chrome right now, and we have a big backlog.

**Comment by ewinslow** [comment]
I personally feel like it has such a huge potential to improve UX without changing any existing client code that it is worth it. It seems like the kind of thing that every site is going to want at some point.

**Comment by jdalsem** [comment]
A plugin exists for this https://github.com/coldtrick/pwa

This might end up in core some time in the future
