### ISSUE TITLE
ElggEntity volatile data is saved to memcache

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7642]

**Comment by ewinslow** [comment]
@mrclay ideas for a fix?

**Comment by mrclay** [comment]
Extract it before save and reinject it after. New public (but `@access private`) methods on ElggEntity.

**Comment by mrclay** [comment]
Or maybe better: move volatile data storage to a central location like the metadata cache.

**Comment by hypeJunction** [comment]
This seems to have been fixed
