### ISSUE TITLE
Create separate user_profile menu for profile page

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7653]
Currently we reuse user_hover menu, so the same elements must appear in both user icon menus and profiles (unless some context hacks are used).

Not sure how to do BC for this.

**Comment by mrclay** [comment]
If anyone has an idea how to do this, please reopen and suggest it. @juho-jaakkola @hypeJunction @jdalsem

**Comment by jdalsem** [comment]
We could just request a new menu 'profile' and provide a register hook in which we do the BC stuff to get it from the hover menu... should not be that hard

**Comment by jdalsem** [comment]
with the related PR merged the profile page now uses the regular title menu for the items
