### ISSUE TITLE
FR: Allow Friends Picker to have Unicode Sorting also

### ISSUE THREAD

**Issue by rhisss** [Elgg/Elgg#7654]
It will be an additional setting in the admin page where admin can choose which Unicode language to be used from a drop down. PHP presumably does alpha sort of Unicode chars by itself so now the characters need to be displayed by Elgg

**Comment by rhisss** [comment]
Any progress on this so far ? Thanks.

**Comment by hypeJunction** [comment]
Friendspicker has been removed from core.
