### ISSUE TITLE
Session write query slow in InnoDB

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7656]
When the users_session table is converted to InnoDB the update query (https://github.com/Elgg/Elgg/blob/1.10/engine/classes/Elgg/Http/DatabaseSessionHandler.php#L56) is very slow. Use the testscript below to test this (switch between MyISAM and InnoDB engine).

```php
require_once(dirname(__FILE__) . "/engine/start.php");

$start = microtime(true);
for ($i = 1; $i < 100; $i++) {
    session_write_close();
    session_start();
}
$end = microtime(true);

echo $end - $start;
```

Assumption:
Session data in the users_session table exists more often then not (once you have a session, it is stored. Every next page it will already exist).

We tested different solutions to this problem by changing the update query.

Currently Elgg uses: `REPLACE INTO`
This means: INSERT -> if that fails -> DELETE all records that prevent insertion (based on unique keys) -> INSERT again

Problem with this approach in general is that it chops holes in your data, as it continuously deletes rows and inserts new ones.

We tried 2 alternatives:

INSERT INTO *** ON DUPLICATE UPDATE ***
```php
$query = "INSERT INTO {$this->db->getTablePrefix()}users_sessions
         (session, ts, data) VALUES ('$id', '$time', '$sess_data_sanitised') 
         ON DUPLICATE KEY UPDATE ts = '$time', data = '$sess_data_sanitised'";
```
This will not remove records, but do an update if a session already exists

UPDATE first THEN insert (more optimistic then option before)
```php
$query = "UPDATE {$this->db->getTablePrefix()}users_sessions 
    SET ts = '$time', data = '$sess_data_sanitised' WHERE session = '$id'";

if ($this->db->insertData($query) !== false) {
    return true;
}

$query = "INSERT INTO {$this->db->getTablePrefix()}users_sessions
         (session, ts, data) VALUES ('$id', '$time', '$sess_data_sanitised') 
         ON DUPLICATE KEY UPDATE ts = '$time', data = '$sess_data_sanitised'";
```

All 3 options have been tested with JMETER and we had 100 sessions triggering the script and we did the jmeter script 10 times.

There is no mentionable performance difference between the 3 options (using MyISAM), however on InnoDB the first (current Elgg) option was not able to perform the tests as they locked up the database in such a way that the scripts could not complete in a fair amount of time.

I suggest we switch to the INSERT INTO ** ON DUPLICATE UPDATE *** (option 2) as we also wish to move to InnoDB at some time + the reduction on the fragmentation of the table (DELETES vs UPDATES)

**Comment by saeedsq** [comment]
Replace Into Table in MySQL InnoDB is extremely slow. This is an issue in mysql which has been fixed & verified in version 5.7:
https://bugs.mysql.com/bug.php?id=71507

I agree with "UPDATE first THEN insert", if you don't plan to upgrade to mysql 5.7
