### ISSUE TITLE
doesn't fetch the menu items (elgg_nav_collapse)

### ISSUE THREAD

**Issue by vikram06** [Elgg/Elgg#7657]
doesn't fetch the any menu items (elgg_nav_collapse) button in aalborg_theme elgg 1.10

**Comment by jdalsem** [comment]
closing this as there came no answer on previous comment

**Comment by zia-uddin** [comment]
'blog/blog/view/728/.elgg-nav-collapse' URL not found in Google webmaster. please help me , how i can fix this problem.

**Comment by ewinslow** [comment]
People are clicking the button before js is bootstrapped.

We should do something more reasonable in this situation...

**Comment by PerJensen** [comment]
I think it's fixed already in  #7865

**Comment by jdalsem** [comment]
yep i think so too

**Comment by vikram06** [comment]
Yes...fixed in #7865

**Comment by vikram06** [comment]
I was faced same problem in elgg community site.when i click toggle button show 403 error.Is currently fixed #7865 in community site??...or one new issues??

**Comment by vikram06** [comment]
Or reopen

**Comment by PerJensen** [comment]
Community site hasn't been upgraded to 1.10 yet.

**Comment by vikram06** [comment]
Okay.please open new issue for commuity site toggle does n't working.i think also issues in elgg 1.9 community site.when i click toggle button shows 403 error.

**Comment by jdalsem** [comment]
As the issue is already fixed in 1.10, opening a new ticket is not needed. The only advice left is to update the community site to 1.10, but that work is not managed here.

**Comment by vikram06** [comment]
+1
