### ISSUE TITLE
Split up css files

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7658]
@ewinslow suggested in another ticket about splitting up css files even further.

So instead of `/css/elements/buttons` you would get `css/elements/buttons/action`

or instead of `css/elements/navigation` you would get `css/elements/navigation/tabs`

etc...

i can see a real benefit in this for themes, as i mostly need just to change some minor elements

please share your thoughts about this

Pros:
- file names could match their css classes more closely, so it's more obvious where to look to edit something
- fine grained loading means only needed css gets loaded (speed). Http/2 makes it cheap to load many resources without exploding the number of requests. This is a very different situation compared to when the css organization was originally devised.
- Fine grained views make it easier for plugins to extend just one view
- fine grained views means a definitive, limited API surface for that view/component, which is more maintainable for us.
- fine grained views means easier parallelizing of work for rapid theme development in a team setting.
  - fine grained views means you can really focus logically on one thing at a time, which is useful even if you end up working on all of them eventually.
- fine grained views encourage clear separation of concerns.
- makes child themes easier to maintain and build
- you wouldn't define multiple php classes in a single file. For the same reason we shouldn't define multiple css components in a single file.

Cons:
- http2 has not seen wide adoption just yet and can't be relied upon to provide a fast experience. Bundling is still the way to go.
- the current level of granularity and naming does not bug the people that are working on theming
- changing the granularity would likely be a breaking change
- would require overriding or extending many more views, which feels like a hassle/less maintainable.

/cc @PerJensen

**Comment by jdalsem** [comment]
little bit related to #6517

**Comment by jdalsem** [comment]
Are we still going to pursue this? 2.0 is good time to do so... Otherwise we should close this ticket.

**Comment by ewinslow** [comment]
I personally would like to see it happen still, but it feels like others have been so ambivalent about it...


Some specific files I'd like to see:

elgg/button.css
elgg/button/{type}.css
elgg/menu.css
elgg/menu/{type}.css
elgg/module.css
elgg/module/{type}.css

You could imagine a similar pattern with other components we have...

**Comment by jdalsem** [comment]
on a side note; we should also split up admin and walledgarden css

**Comment by ewinslow** [comment]
But again, this is not coming from personal experience at the moment, just a general desire to make fine grained resources to streamline development and let the framework worry about losing them efficiently and what not.

**Comment by ewinslow** [comment]
Also keep in mind that 2.0 freeze is days away. It might make more sense to experiment with this more find grained approach in a plugin during 2.x before we go and make it official.

**Comment by hypeJunction** [comment]
I think current level of granularity is good enough. I never felt compelled
to override one single type of button. If I do it, I usually hack them all.

**Comment by mrclay** [comment]
I'm for revisiting in 3.0

**Comment by ewinslow** [comment]
Fine with me.

**Comment by ewinslow** [comment]
Added a summary of arguments above

**Comment by jdalsem** [comment]
@mrclay have you revisited this... and do we still want this for Elgg?

**Comment by hypeJunction** [comment]
Yes, I want this, and will work on it once bigger styling changes are in.
