### ISSUE TITLE
Auto-join objects/users/groups subtables

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7662]
In ege() we can safely auto-JOIN these tables if the following conditions on $options are met (which is very common):

1. type is object, user, or group
2. these are empty: selects, wheres, joins
3. callback is `entity_row_to_elggstar`
4. count is false

I figure sites and plugins aren't used often enough to worry about

**Comment by jdalsem** [comment]
i believe this ticket can be closed
