### ISSUE TITLE
Improve RTE UX inspired by medium clones

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7696]
http://howtox.com/medium-editor-clones-in-js/

I looked at a few editors out there and there are some nice features -- e.g. automatically creating list items when "\* ", "- ", or "1. " is typed at the beginning of a line. Automatic blockquote for "> ". Automatic code block for "```\n", etc. This seems very handy, in addition to autocomplete linking via "@" or "+" triggers.

**Comment by jdalsem** [comment]
When selecting a new editor we need to have more attention for this
