### ISSUE TITLE
PHPStorm displays strike through @internal functions

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7714]
Unfortunately it looks like there are [two different usages](http://phpdoc.org/docs/latest/references/phpdoc/tags/internal.html) for `@internal`: leave notes about internal workings, or mark an API as for internal use only. We're using it to display internal notes about functions like elgg_register_plugin_hook_handler(), and PHPStorm 8.0.2 displays them like deprecated functions.

Yes, PHPStorm made this change in a bug fix release :-1:

**Comment by GaryJones** [comment]
Use the inline version `{@internal Some note here }}` as per https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#examples-7 to leave notes for developers.

**Comment by mrclay** [comment]
@GaryJones thanks!

**Comment by mrclay** [comment]
PHPStorm doesn't understand the difference, it still marks the usage with a strikethrough.

**Comment by mrclay** [comment]
PR #8375

**Comment by GaryJones** [comment]
> PHPStorm doesn't understand the difference, it still marks the usage with a strikethrough

Yeah, I played around afterwards and found the same - sorry for the wrong information.

**Comment by jtraulle** [comment]
In the meantime, you can also disable the inspection check in PhpStorm preferences by unchecking the checkbox for the __InternalEntityUsed__ inspection.

![capture d ecran 2015-05-28 a 08 18 07](https://cloud.githubusercontent.com/assets/613615/7853726/61c62262-0512-11e5-9c49-fef7671bbd6d.png)

**Comment by jdalsem** [comment]
Closed in #8375
