### ISSUE TITLE
Make elgg/elgg a real composer-compatible library for inclusion in the project

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#7721]
**Idea is to:**
- have custom project that just includes `"elgg/elgg": "1.10.0"` in composer.json
- simplify upgrading the core to ticking the version in composer.json from code perspective
- whole elgg core resides in `vendor/elgg/elgg`
- keep plugins in `/mod/` directory as they need to be in that relation to wwwroot and it's hard to change
- devs are responsible for bootstrapping front page controller. Something like:
```php
require_once('vendor/autoload.php');
$app = new ElggApplication($config);
$app->run();
```
or
```php
require_once('vendor/autoload.php');
$app = new ElggApplication();
$app->loadConfigFromFile('settings.php');
$app->run();
```
and rewrite rules that point to it
- devs are responsible for passing configuration programmatically or path to config file
- devs are responsible for passing all requests to front page controller
- we provide basic version of `elgg/installer` that might keep current install script, and serve the purpose of bootstrapping new project and allows to be dropped/rewritten completely after that.

**Benefits:**
- strict separation of Elgg core that's not to be modified, plugins and custom project dependencies
- we encourage plugin installation via composer
- can keep project in custom repo without polluting Elgg fork
- more seamless integration for multiple-framework projects or other very customized work
- core-change meaning becomes more apparent ;-)
- we stop keeping core php files in publicly visible dir which gets rid of possible attack vectors
- we can keep structure of elgg/elgg in similarly functional form as now, so no regression here

My main inspiration is the way Laravel handles that by having core spearate from installer:
- http://laravel.com/docs/4.2/installation#install-laravel

**What do we lack:**
- [x] [WIP](https://github.com/Elgg/Elgg/pull/7939) we rely on specific place of start.php instead of using OO approach. Need ElggApplication instead
- [ ] we might rely on core views/languages/actions locations from plugins, basically need to make engine almost like self-contained plugin
- [ ] we need to either have custom installer to handle bundled plugins or move them into separate dependencies to handle installing into `/mod/` easily
- [x] we need to integrate cache, export, _graphics, js and install into front controller

**Possible dir structure sketch:**
```
/web (wwwroot, only this dir is visible to the outside world)
    /mod
        /blog (installed from composer/installer)
            (plugin files as usual)
    /assets (probably useful dir for static assets, like contents of _graphics, could be added on composer install step)
    .htaccess
    index.php (initially from elgg/installer package or just user-defined one if preferable in project)
/vendor (composer libs dir)
    /elgg
        /elgg
            /actions
            /engine (might move it outside a bit)
            /docs
            /pages
            /languages
            /views
            composer.json (elgg/elgg dependencies)
            index.php (old-fashioned front page controller for people that checkout elgg/elgg directly)
/dataroot (it's just possible to keep it here as it's no longer public dir)
composer.json (custom/project dependencies that include elgg/elgg)
```

**See also:**
- [Community discussion](https://community.elgg.org/discussion/view/1969020/even-more-composer-friendly-elgg)
- [Experimental repository](https://github.com/Srokap/elgg_as_dep) that I use for current testing

**Comment by byhoratiss** [comment]
One thing that seems to be forgotten: today the developer downloads the plugin, place all the files under "mod/plugin_name/" and customizes the code to achieve some requirement.
What happen if we "require" through composer installers (https://github.com/composer/installers) a plugin? 
Where can we do the "customization" process? If we change the code, each time you do a "composer update/install" you can loose some code.

Strange thoughts, maybe you can enlight me! @Srokap

**Comment by mrclay** [comment]
Very cool, thanks

**Comment by ewinslow** [comment]
@Srokap I really want this for 2.0, because I think it would make developing and maintaining customized sites soooo much easier...

What do you think about moving `srokap/elgg_as_dep` to `Elgg/starter-project` and making that depend on `elgg/elgg` at dev-master? We could then just iterate on that based on the bugs we run into.

**Comment by Srokap** [comment]
No problems from me about moving it to Elgg organization, but it's far from production ready. Right now the major issue I'm thinking about is proper way of handling static assets from _graphics and vendors. Add to that situation with bundled plugins and we seem to need a installer for those. My initial research showed no easy way of splitting files between two target locations, so leaning towards composer hooks now.

I don't think that routing stuff via php is a viable option (due to performance of such solution and bypassing all web server goodness), though would be easy to implement without much tinkering.

Not fully convinced about naming it `starter-project`. It has nice ring, but was thinking more about `Elgg/installer` so far.

**Comment by ewinslow** [comment]
What's the next step for this ticket?

I found this resource, which might be of interest:

https://github.com/francoispluchino/composer-asset-plugin

Allows defining and managing static assets with composer... Cool!

**Comment by ewinslow** [comment]
Also, seems like there's been some resistance to php routing because of performance, but we've already discussed a solution to that iirc, which is to cache static assets in the web root for production. We can make this a composer script if it's not possible to do safely from the web server.

**Comment by ewinslow** [comment]
@Elgg/owners 

* composer-asset-plugin is in
* I just added repos for all core plugins (but haven't done any work to switch over transifex, composer, etc. wanted to get some feedback first). I will probably start extracting the repos we've agreed to extract like `twitter_api`, `categories`, and `custom_index`...
* Elgg/starter-project seems very viable!

**Comment by ewinslow** [comment]
I know we've been sensitive to pulling *all* plugins out of core due to the management overhead. I'm still persuaded that the benefits can or already do outweigh the costs, but I want to remain sensitive to that concern and not make any unilateral decisions.

**Comment by ewinslow** [comment]
I used this script to extract histories for each of the plugins, respectively:

```php
<?php

$plugins = [
	"aalborg_theme",
	"blog",
	"bookmarks",
	"categories",
	"ckeditor",
	"custom_index",
	"dashboard",
	"developers",
	"diagnostics",
	"embed",
	"externalpages",
	"file",
	"garbagecollector",
	"groups",
	"htmlawed",
	"invitefriends",
	"legacy_urls",
	"likes",
	"logbrowser",
	"logrotate",
	"members",
	"messageboard",
	"messages",
	"notifications",
	"pages",
	"profile",
	"reportedcontent",
	"search",
	"site_notifications",
	"tagcloud",
	"thewire",
	"twitter_api",
	"uservalidationbyemail",
	"web_services",
	"zaudio",	
];

foreach ($plugins as $plugin) {
	echo "Pushing history for $plugin...\n";
	`git subtree push -P mod/$plugin git@github.com:Elgg/$plugin.git master`;
}
```

**Comment by mrclay** [comment]
Imagine trying to pull off something like https://github.com/Elgg/Elgg/pull/8372/files with separate repos. Or merging up a branch. Seems any merge that involves plugins will be a huge headache. There has to be another approach to this...

**Comment by ewinslow** [comment]
It would be done no differently than the way every other plugin developer has to do it. I'm not sure I understand the problem.

Re: merging up branches with plugin changes, we can delete the plugin from a very low version of Elgg, add via composer, and merge that up so there is no temptation to PR against Elgg/Elgg.

**Comment by ewinslow** [comment]
Something we could do without deleting them from core is just committing a minimal composer.json file (without version number), then at least packagist could serve them from dev-master from their respective `Elgg/*` repos. That would allow us to move forward with testing elgg/starter-project.

**Comment by ewinslow** [comment]
I've moved plugins to separate repos as I think that is the way to go, and that is how they're included via elgg/starter-project.

However, this requires manually running the above script and tagging them individually whenever a change is made. I'd prefer to see them developed independently (with commits made directly to their respective repos) and then have some script that automatically tags each new version ala:

https://www.youtube.com/watch?v=tc2UgG5L7WM

Releasing new code needs to go from minimal effort to 0 effort.

**Comment by mrclay** [comment]
I think the recent development on master has convinced me that managing all bundled plugins separately would be a huge pain. Also when evaluating a new API it's very valuable to see in the PR how it will integrate into plugins. I think we should even pull in stuff like login_as and manage it like the others.

**Comment by ewinslow** [comment]
:'(

**Comment by hypeJunction** [comment]
Well, having all plugins detached would be a valuable insight for the core
team into how plugin devs are dealing with that pain.

**Comment by ewinslow** [comment]
I think we can close this one out. Elgg works as a composer dependency. Now we need to wrap up the discussion about how to deal long term with the bundled plugins when installing in this way. That feels like a separate ticket.
