### ISSUE TITLE
Pagination links don't respect custom offset

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7727]
Current pagination model assumes that offset % limit is 0, that is offset increase by increment of limit. Passing offset=30&limit=20, for instance, produces a list that, if loaded in full via ajax using all pager links, will be missing 10 items.

**Comment by mrclay** [comment]
I can't duplicate this issue on 1.10. Can you give me a blog URL that shows it?

**Comment by jdalsem** [comment]
It is not about the amount (that is correct), but the offset used on the pagenumbers in the pagination. You can also see it here: https://community.elgg.org/activity?limit=5&offset=3

Expect is that the next page offset = `offset + limit`, but it is `limit * pagenumber`
The previous and next button already do it correct (as they do offset +/- limit)

**Comment by mrclay** [comment]
So limit=10&offset=27 should produce links with offsets: 0 (missing), 7, 17, 37, ...

Note that once the user reaches the first page, they will get the "standard" offsets again.

**Comment by jdalsem** [comment]
> So limit=10&offset=27 should produce links with offsets: 0 (missing), 7, 17, 37, ...

correct (27 is missing as that is the current page)

> Note that once the user reaches the first page, they will get the "standard" offsets again.

fine by me

**Comment by hypeJunction** [comment]
Another question we could look into is whether to allow offsets that are
not modulus of limit. So, we could normalize offset to 20 in your example.
The item with offset 27 will fall into the range of 20 to 30.
My main motivation for getting this fixed is using guid to calculate offset
and have an item with guid displayed in the list, I don't really care about
position.

**Comment by mrclay** [comment]
@hypeJunction I considered that. I think it would be worse for core to have to internally "correct" the offset parameter in consideration of limit. I'd rather the pagination view stay dumb and just handle this case.

**Comment by jdalsem** [comment]
so the PR can go in?

**Comment by mrclay** [comment]
I'll look again and merge tonight
