### ISSUE TITLE
IDEA: API to notify lists of users, e.g. "admins"

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7732]
For several use cases it would be useful to e-mail site admins for one thing or another. E.g. #3252. In some cases you'd want to notify all members, but a plugin could filter the list to, say, select 2 admins at random.

It would be great if we could use somehow use the notifications API.

@juho-jaakkola may have some ideas here...

**Comment by jdalsem** [comment]
I do not see why we want a specific feature for this. It adds nothing that we can't already do with the subscribers hooks.
