### ISSUE TITLE
Richer ajax view API

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7733]
I think we could make some easy-ish steps forward that would compliment the integration of a JS framework. Goals:
1. views rendered wrapped with DIVs with data- metadata like view name, params used to display it (e.g. offset, limit) so they know how to refresh themselves, like widgets.
2. ✓ ~~simple API to load/refresh view.~~
3. consider how to handle listings (e.g. ajax pagination, ability to refresh a slice of the list if an items are deleted or need to be re-rendered)
4. ✓ ~~easy API to serve form views with elgg_view_form() wrapping (I have code for this I'll dig up)~~

**Comment by jdalsem** [comment]
ajax/form API already added

**Comment by mrclay** [comment]
Question at this point is whether to pull @hypeJunction hypeLists into core or if moving toward client-side rendering would be better for the future. It looks like hypeLists has a lot of features; are their standouts we could pull in? Or is there no way to split up the functionality between core and a plugin. Can we get input from other devs who've used hypeLists?

**Comment by hypeJunction** [comment]
I personally feel that hypeLists is too hacky, it's more of a workaround than a solution. 
I don't think we are ready for client side rendering, but we could implement some sort of lists API that will make pagination and list updates easier.

A strawman would look like this:

```php

// registers listing view as an ajax view
// or lists should be placed in a specific directory, e.g. /listing
elgg_expose_list('groups/all');

// renders a placeholder with context vars encoded
// requires an AMD module capable of fetching and redrawing the list
echo elgg_list('groups/all');
```

```html
<div class="elgg-list-container" data-view="groups/all" data-context="$context_vars"></div>

<script>
   require(['elgg/list'], function(list) {
     list.draw();
     list.redraw();
  });
</script>
```

**Comment by hypeJunction** [comment]
On the other hand we can pull in Vue.js. So far it's the only JS framework that would allow us to gradually migrate all views.

**Comment by jdalsem** [comment]
In https://github.com/Elgg/Elgg/pull/13516 we added some basic ajax listing logic. That will be it for this ticket.
