### ISSUE TITLE
Remove usages of _elgg_services() from engine/classes/Elgg

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#7734]
As we use DI in this subtree, there should be no need to reach to the global state for DIC, we ought to inject all dependencies into constructor. There's a ton of usages. We should
- [ ] remove `_elgg_services()` usages
- [ ] add test for newly introduced `_elgg_services()` to avoid future regressions

I'll have a look at it.

**Comment by ewinslow** [comment]
Would love to have a lint/sanity check that bans the introduction of more global state.

**Comment by ewinslow** [comment]
This is a good refactoring that we should continue to do, but not a 2.0-blocker.

**Comment by jdalsem** [comment]
No need to keep a global ticket open for this refactoring
