### ISSUE TITLE
idea: view decoration

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7735]
Just a brain dump...

Right now extension happens by either appending or prepending to existing view content. Whether it prepends or appends depends on whether the priority given is greater than or less than 500.

This has two shortcomings:
- This 500 number is pretty arbitrary. I think we decided some time ago that 0 would be a more natural choice, assuming we allow the use of negative numbers.
- it's not possible to extend in a way that "wraps" the content of the original view. For that you would have to extend twice or use the "view,*" plugin hook.

View decoration solves this. Every decorator is on the same priority scale, so there's no magic number that changes the behavior of the decorator.

Unfortunately if we add this we'd now have 3 ways to extend views: extension, decoration, plugin hook.

We could define extension in terms of decoration (extension is just a special case of decoration). The plugin hook would just be a lower level API not meant to be used for normal view decoration.

Finally, this would be consistent with the rest of our design if we go with decoration for services.

**Comment by jdalsem** [comment]
not going to pursue this any time soon
