### ISSUE TITLE
Provide less granular hook for prepare, notification:*

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#7737]
1.9 notifications events are extremely granular, which is a problem if you want to do something like modify the subject for every notification sent. The type passed is `notifications:$action:$type:$subtype`, so you can't use the hook to `prepare, all` without doing icky substring sniffing in the handler.

I think we need to expose a `prepare, notification:all` hook.

**Comment by jdalsem** [comment]
We have ``format, notification:<method>`` that can apply generic changes
