### ISSUE TITLE
htaccess blocks all hidden directories

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#7740]
As of 1.9 htaccess blocks access to all hidden files/directories, the comment gives the justification as excluding .git/
https://github.com/Elgg/Elgg/blob/1.10/htaccess_dist#L128

However sometimes you need access to hidden directories

For example I'm currently working on an OExchange plugin, the spec requires a discovery xml file in a hidden directory: http://www.oexchange.org/spec/#discovery-hostmeta

I think we need to be more specific about what we're blocking here, the blanket policy is too broad.

**Comment by ewinslow** [comment]
I'm fine whitelisting .well-known. Any others?

**Comment by beck24** [comment]
Not that I'm aware of, but if anyone else knows of any we should compile them here and whitelist them all at once.

**Comment by mrclay** [comment]
I'm for whitelisting .well-known for now. Devs can easily send a PR to add others as they come up.

**Comment by beck24** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/10790/commits/bb35cb9c317c1176542b76592c7e70805a91b9d9
