### ISSUE TITLE
User option to send all notifications via encrypted email

### ISSUE THREAD

**Issue by cleverthings** [Elgg/Elgg#7742]
Feature request for in a future release to give users the option of having their email notifications signed and encrypted by elgg server.

**Comment by ewinslow** [comment]
Hey, there! Thanks so much for the feature request.

This seems like an advanced feature best done via plugin. If there are any specific shortcomings that make this impossible via plugin, do let us know.

I do like the idea of encrypting email notifications, though, and might even consider using it on my site of it were available...
