### ISSUE TITLE
Groups plugin shouldn't modify subject of comment notification emails

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7743]
The groups plugin creates following subject for email notifications about group discussion replies:
```Re: <title of discussion>```

The handler however adds it also for ElggComments:
```php
if (($container instanceof ElggEntity) && ($object instanceof ElggComment)) {
    $returnvalue['subject'] = 'Re: ' . $container->getDisplayName();
}
```

This causes the comment email subject to be different depending whether Groups plugin is enabled or not:
 - Enabled: ```Re: <title of content>```
 - Disabled: ```You have a new comment!```

The comment specific logic should be pulled out from the groups plugin.

**Comment by juho-jaakkola** [comment]
@Srokap You introduced this in https://github.com/Elgg/Elgg/commit/91755a86b7ea89db71e29d632c23120b9938e87b. Do you remember if it was intentional that it changes the title both for discussion replies and comments? Or was it intended to affect only the discussion replies?

What do others think, should we always use this kind of subject also for comment notifications:
```Re: <title of commented content>```

**Comment by mrclay** [comment]
Personally I prefer "Re: Title..."
