### ISSUE TITLE
Allow anonymous functions and dynamic methods to be unregistered

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7750]
We all really love anon functions right up until you need to unregister one used as a handler in another plugin. I propose we allow a special syntax for matching an anonymous function in these unregister functions, e.g.

```php
// matches any Closure defined in that file
elgg_unregister_blah('Closure in mod/foo/start.php');

// matches an [$barInstance, 'bing']
elgg_unregister_blah('\Bar->bing');
```

Since this requires Reflection it wouldn't be super fast, but it's not a common need anyway.

**Comment by Srokap** [comment]
I actually imagined that at some point we could have registration api exposed by particular "core app" instance to the plugin and this way we could mark anonymous function by instance or just look at stacktrace (doesn't sound fast either).

Alternative would be to require for now additional parameter "function name" on registration which would be just a logical closure identifier for unregistering. This way we would at least not create global function, but that's not so cool solution.

Maybe some solution would be flipping whole thing around and marking events for particular plugin that are not supposed to be registered by it and just ignoring it during registration. That would make sense as plugin dependency similar to plugin order. It still requires knowing which plugin is just calling the api.

I'm not convinced entirely about any solution yet.

**Comment by ewinslow** [comment]
I think we should consider this a feature. If you want the function to be
unregisterable, that is extra API that you explicitly expose by naming the
function.

**Comment by mrclay** [comment]
To most devs it's an unexpected outcome of using a nicer style, not a conscious decision to disable unregistering. In principle Elgg should nudge devs away from static code rather than imposing costs on those preferring OO/functional. I'll try to convince with a PR.

**Comment by beck24** [comment]
Having something be unregisterable seems like a bad idea, you can't predict what future devs will need, I think it would just lead to people forking things unnecessarily.

**Comment by ewinslow** [comment]
Personally would prefer to nudge toward registering classes instead of
functions. Then we could add di support. Closures still slightly nicer in
many cases, but I maintain that anonymity is a feature. You should not be
able to reference the function in a global way.

**Comment by brettp** [comment]
Agree that anonymous functions should be able to be unregistered. Not
allowing them to be makes exceptions in the API, making it inconsistent. If
people can't unregister functions through the API, they'll fork or start
mucking around in the services to do it manually.

On Wed, Jan 7, 2015 at 3:05 AM, Evan Winslow <notifications@github.com>
wrote:

> Personally would prefer to nudge toward registering classes instead of
> functions. Then we could add di support. Closures still slightly nicer in
> many cases, but I maintain that anonymity is a feature. You should not be
> able to reference the function in a global way.
>
> On Mon, Jan 5, 2015, 8:57 AM Matt Beckett <notifications@github.com>
> wrote:
>
> > Having something be unregisterable seems like a bad idea, you can't
> > predict what future devs will need, I think it would just lead to people
> > forking things unnecessarily.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Elgg/Elgg/issues/7750#issuecomment-68737826>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/7750#issuecomment-68990059>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by mrclay** [comment]
PR #8071

**Comment by mrclay** [comment]
Consensus seems to be that the fix is way too ugly. What do y'all think of allowing `Foo::method` to match `[$foo, 'method']` where `get_class($foo) === 'Foo'`?

**Comment by beck24** [comment]
I would be more in favor that

**Comment by mrclay** [comment]
More limited PR #8181
