### ISSUE TITLE
Add working nginx rules for Elgg 1.X to the docs

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7753]
People are asking again and again on the community site how to get Elgg working with nginx. On the docs site there's a ToDO about adding the community site's rules:
http://learn.elgg.org/en/1.9/intro/install.html?highlight=nginx#other-configurations

I think it should be not too time consuming for anyone with server access to copy+paste these rules. Then it would be possible to simply link to the corresponding page in the docs if the questions is asked again. As it seems not many people know about the correct rules and therefore these question are not answered mostly (always?) so far which is really a pity - and makes not a good impression...

**Comment by iionly** [comment]
See PR #7756.

**Comment by jdalsem** [comment]
related #5929

**Comment by iionly** [comment]
To be dealt with in PR #7759 so closing.
