### ISSUE TITLE
Should be able to add admins from the admin/users/administrators page

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7757]
You can view current admins and revoke privileges, but you can't add them from this page. It's a little weird to have to give two sets of instructions to someone for a) adding admins and b) viewing the list of admins/removing admins.

**Comment by Srokap** [comment]
Sounds fine, though that's something I can easily live without (speaking for myself) and I would prefer to spend some time on better bulk user management in general instead.

**Comment by ewinslow** [comment]
Yea, just trying to transfer ownership of an elgg site to some other folks and writing down what I notice as I teach. Better user management would be great.

**Comment by mrclay** [comment]
General procedure would be: Search user, add admin via click menu. But we don't have search in the admin area! Returning the results in admin context would be useful too.
