### ISSUE TITLE
Add README for running JS tests

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7758]
Here were the commands I had to use on OSX (with homebrew):

```
cd elgg-site
brew install npm
npm install -g karma
npm install -g karma-cli
npm install -g phantomjs
npm install
npm test
```

**Comment by Srokap** [comment]
I'd love to move at some point all such steps into single place, makefile or grunt. Prefering something system agnostic. Could be even npm scripts configured in package.json.

Just saying.

**Comment by ewinslow** [comment]
Yea, why are these not just listed as deps in the package.json?

**Comment by ewinslow** [comment]
Rather they are but it's not enough... Wonder why

**Comment by jdalsem** [comment]
I think currently this works fine
