### ISSUE TITLE
Remove FilePluginFile

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7763]
We just use this to tack on a custom delete method, and this only works when we use the FilePluginFile constructor. This confuses the entity persistence model and will confuse users. See also [these comments](https://github.com/mrclay/Elgg-leaf/blob/7761_filepluginfile/mod/file/classes/FilePluginFile.php).

**Comment by hypeJunction** [comment]
+1. All file logic should exist outside of the file plugin imho

**Comment by mrclay** [comment]
Can we not just add the the delete() logic to ElggFile::delete?

**Comment by hypeJunction** [comment]
I suppose we can. Doesn't it just remove thumbnails? I guess it will come
in handy for when file plugin is disabled, unless nothing in core is
creating those. Maybe just convert it to an event handler?

**Comment by brettp** [comment]
This should be part of #8202.

**Comment by mrclay** [comment]
PR #8346
