### ISSUE TITLE
Metadata events are unpredictable

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7765]
The "create" and "delete" events do not imply the metadata key is new, and using ->setMetadata() to change a key will _not_ trigger the "update" event. This is because setMetadata(), to replace a value, deletes all existing MD, then uses create_metadata, which triggers "create".

Basic problem is the events are tied to low-level implementation details (DB rows) of metadata, yet almost all devs use the higher-level API on ElggEntity.

**Comment by mrclay** [comment]
Probably should replace MD events with an entity-level event "metadataUpdated" triggered only by the high-level setMetadata(). Since we decided events can't have params there's no way to inform the handler of what's changing.

**Comment by mrclay** [comment]
Strawman: deprecate create_metadata, update_metadata, and the changing of ElggMetadata objects (in 3.0 they'd be returned from elgg_get_metadata but not be mutable). In 3.0 the entity API is the only public API for changing it, and it triggers metadata_update before/after events (with $params!)

**Comment by jdalsem** [comment]
We have to deal with the current situation. Any implementation will add new complexity to this logic that will not make things easier to work with. The Elgg community has been used to this metadata behaviour for a lot of years and probably can live with it a few more years.
