### ISSUE TITLE
Copy/paste in CKeditor adds junk styles (font-size)

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7771]
On Chrome/OSX at least, the editor seems to add `style="font-size: 13px;"` all over the place, particularly copy/pasting within lists, and you don't notice it until the output is rendered and some items are smaller.

This is bad for accessibility and responsive design so I'm marking this important.

**Comment by mrclay** [comment]
Was [fixed in 4.0.1](http://dev.ckeditor.com/ticket/9754). not sure what's going on.

**Comment by mojo3159** [comment]
Hi,

I have downloaded the newest full package of 4.4.7 version but the addition of junk styles persists.
E.g. if I copy (of course in visual mode, not from source code):

<div class="my-block">...</div>

and I paste it to some other place I will get:

<div class="my-block" style="width:480px">...</div>

This breaks responsive design. 
Is it possible to turn off this behavior?

**Comment by jdalsem** [comment]
Elgg comes bundled with 4.4.7. Expecting the issue no longer being present
