### ISSUE TITLE
Release cycle of the bugfix only version

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7777]
As Elgg now released 1.10, the 2 week cycle for bugfixes will apply for the 1.10 version. Does it also apply to the "critical/security fix only" version of 1.9?

**Comment by ewinslow** [comment]
We will release security fixes on an as-needed basis. Not necessarily on the 2-week cycle.

**Comment by jdalsem** [comment]
Then we need to add that to the docs, as it is unclear now
Op 14 jan. 2015 23:58 schreef "Evan Winslow" <notifications@github.com>:

**Comment by ewinslow** [comment]
http://learn.elgg.org/en/1.10/appendix/support.html

"Released on an as-needed basis"

**Comment by jdalsem** [comment]
my bad... must have overlooked it
