### ISSUE TITLE
add support for elgg_require_js and elgg_load_library in ajax loaded content

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7784]
if you use php function to register js files to be loaded, but the code is loaded through ajax calls the libraries / amd modules will not be loaded. We could pass the external_files and the amd dependencies and let the ajax success handler load the modules (similar as handling messages)

**Comment by hypeJunction** [comment]
+1

**Comment by ewinslow** [comment]
I could get behind this if we have a new, higher-level `elgg.view()` API that does it. I wouldn't want to put it in the low-level elgg.get or anything.

**Comment by jdalsem** [comment]
This is part of elgg/Ajax
