### ISSUE TITLE
Navbar toggle does not work - 1.10

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#7790]

**Comment by mrclay** [comment]
More info? I can't reproduce.

**Comment by PerJensen** [comment]
Aalborg theme 1.10. Minimize your browser window and open the menu.

**Comment by PerJensen** [comment]
It seems that a class identifier is not accepted anymore, must be id.

**Comment by mrclay** [comment]
Can you tell what needs to be changed?

**Comment by mrclay** [comment]
PR #7865

**Comment by mrclay** [comment]
(unfortunately, for BC we're stuck using the unfiltered `$(this).attr('href')` to get the toggle selector)
