### ISSUE TITLE
Fatal error: Call to a member function getURL() on a non-object in mod/pages/views/default/pages/icon.php on line 23

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#7793]
This error occurs in a group. For some reason there is no URL available for a page, but I do not know which page. As a result /pages/all fails as well as trying to get a list of pages in that group and the pages widget in the group.

I suggest checking if getURL() is callable. Something like this ?

<a href="<?php if (is_callable(array($annotation, 'getURL'))) { echo $annotation->getURL(); } ?>">

**Comment by mrclay** [comment]
We have to verify there's a page object to begin with.

**Comment by gerard-kanters** [comment]
Do you think there is no page object ? I think there is, but for some reason it is incomplete.

**Comment by mrclay** [comment]
I think the page is missing its annotation (or you can't see it). See #7794 but I'm not sure the best way to deal with this rare situation.
