### ISSUE TITLE
Document how to add composer support to plugins

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7798]
At some point we perhaps even might want to just stop allowing new uploads to the community and just pull elgg related plugins from packagist, but I imagine that would be a more dramatic step...

**Comment by Srokap** [comment]
See https://community.elgg.org/pages/view/1630158/experimental-community-plugins-mirror-as-composer-repository, part called "How to make elgg plugin work with composer"

Would need that in more user friendly version.

I generally think we could use separate composer-related page in docs regarding installing Elgg with composer, making plugins installable with it and perhaps basic workflow.
