### ISSUE TITLE
Improvement in Group Plugin (Elgg 1.9.X)

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#7805]
Here is an improvement that I think would be great if implemented in the group plugin.

1. A new sidebar menu called "Group Profile" should be included along with other group menu.
2. If the user is a member of the group, the link of on the group name will take the user to the activity page of the group.
3. If the user is not a member of the group, the link on the group name will take the user to the "Group Profile" page of the group.

Here's what need to be done. Edit the following in the start.php file of the groups plugin.

1. To add the group profile link: added the code after line 68
```
elgg_register_plugin_hook_handler('register', 'menu:owner_block', 'groups_profile_owner_block_menu');
 ```
and add the code after line at 405
```
/**
 * Add profile block link
 */
function groups_profile_owner_block_menu($hook, $type, $return, $params) {
 if (elgg_instanceof($params['entity'], 'group')) {
  if ($params['entity']->activity_enable != "no") {
   $url = "groups/profile/{$params['entity']->guid}";
   $item = new ElggMenuItem('profile', elgg_echo('Group profile'), $url);
   $return[] = $item;
  }
 }
 return $return;
}
```

2 & 3. link on the group name that will take the user to the activity or profile page: modify the following function code on line 356
```
function groups_set_url($hook, $type, $url, $params) {
	$entity = $params['entity'];
	$title = elgg_get_friendly_title($entity->name);
 if (!($user instanceof ElggUser)) {
       $user = elgg_get_logged_in_user_entity();
    }
    if (!($user instanceof ElggUser)) {
       return "groups/profile/{$entity->guid}/$title";
    }
    if(is_group_member($entity->guid, $user->getGUID())==true)
 {
 return "groups/activity/{$entity->guid}/$title";
 }
 else
 {
 return "groups/profile/{$entity->guid}/$title";
 }
}
```

**Comment by mrclay** [comment]
I'm against this on the basis that links to different URLs should have different text. For particular sites it might make sense but could be implemented by a plugin without modifying core.

**Comment by rohit1290** [comment]
I know this is possible by a plugin without modifying the core but I think this would be a great idea if implemented in the core. 

Now think like this.. Currently if a user opens a particular group he/she will be opening the group profile page with all the group summary. He\she will be more interested in the recent activity because he already know what that group is all about. Now consider another user who is not a member of the group. Now for the start, he/she should be taken to the profile page where the user would be able to see the group summary (all the details of the group). Later on if that person joins the group, then from that point he will be able to access the activity page rather than the profile page which he has already seen at the time of joining.

I m just making a suggestion here, rest its upto the team to decide.

**Comment by mrclay** [comment]
I like the core of the idea, which is that, after you join a group, it's less likely you care about profile data like description, tags, etc. Some group owners do, however, update the description to highlight new stuff for members, but it seems rare.

Instead of leading to different URLs, I'd rather split the group page into 2 tabs: profile, activity (and your selection persists if you're logged in).

**Comment by mrclay** [comment]
Or better, at the top of the activity listing, have a checkbox "take me here when I click on this group". if you check it, your choice is persisted, and that checkbox then displays in the "profile" tab. This gives the user control of her preferred default while not bugging her with a separate settings page.

**Comment by rohit1290** [comment]
I really like your idea. I agree that some group owners would like to highlight the changes made in the profile page. Now here's what my idea is, whenever a group owner makes any changes to the group profile, it will post one line on the group activity page "%s has updated the %s of the group" where the first %s will show the name of the owner making the changes and the second %s will show the section that is updated i.e. description, tag, name etc.

**Comment by jdalsem** [comment]
There are too many variables with this approach... because this is such a matter of preference we should leave this to site customizations rather then providing a core feature.
