### ISSUE TITLE
Keep comment access_id in sync with container

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7807]
Arck's solution would be better than nothing: https://github.com/arckinteractive/comment_access_sync. What it doesn't do (for practical reasons) is call events on the comments it updates.

**Comment by beck24** [comment]
In 1.9+ where comments are entities instead of annotations I think events should probably be called, there may be other things attached to comments that need to know when access changes.

**Comment by iionly** [comment]
Just came across this ticket: https://community.elgg.org/discussion/view/2056898/conflict-with-clipping-avatar.

A bohus entity as suggested there might also be a way to avoid problems with container_entity not being accessible.

**Comment by beck24** [comment]
Not sure that's the link you meant to post

**Comment by iionly** [comment]
Oops. copy+paste from wrong tab. It's not the correct link (https://github.com/Elgg/Elgg/issues/4951).

**Comment by beck24** [comment]
In this case I think we should make the access of the comments match the container, the dummy entity might be a good use case elsewhere

**Comment by mrclay** [comment]
FYI for #4905 we actually considered the non-syncing behavior a feature because it didn't allow object owners to widen the visibility of comments made by others. /cc @hypeJunction @twentyfiveautumn

Obviously I've changed my mind on this because not syncing just makes the system more complex (user may be able to see some but not all comments).

**Comment by mrclay** [comment]
While this does mask one problem that could lead to #7984, I don't think it should be accepted as a fix for that issue. See https://github.com/Elgg/Elgg/issues/7984#issuecomment-81638075

**Comment by hypeJunction** [comment]
@mrclay What are your thoughts on constant ACLs instead of batch operations?

**Comment by beck24** [comment]
I'm not a fan of the constant ACLs due to the query complexity and the issues that have arisen both with ACCESS_FRIENDS and with ACCESS_PRIVATE

**Comment by mrclay** [comment]
@hypeJunction not sure what you mean by "constant ACLs", but indeed ACCESS_FRIENDS is problematic; it was a great hack but doesn't support inheritance.

**Comment by ewinslow** [comment]
Yea, lets not introduce another ACCESS_FRIENDS into the system... We need these things to be real acls...

**Comment by mrclay** [comment]
I'm back to thinking #4905 was right. Silently syncing by default is not necessarily better than nothing.

What's the worst situation that the current behavior commonly results in?

**Comment by beck24** [comment]
The current behavior results in:

Comment threads where some comments are not visible to some people - confusing when you see replies to non-existent statements.  In one active community I manage this has manifested in arguments when people didn't reply to an important comment because they couldn't see it, but the author was expecting some timely response.
Access mis-matching when you can see comments but can't see the thing they're commenting on - leads to WSOD currently.  If we fix the WSOD by simply not rendering the view then we end up with invalid search results.  We will see counts higher than the number of comments we can see.  If the comments that can't render are the first results we'll see something like this:

## Comments

(nothing here)

```+ 10 more```

**Comment by ewinslow** [comment]
Consider email -- if you forward a conversation, everyone you forward it to can potentially get the whole history, even if they were not originally added.

Based on this ubiquitous precedent, I think I agree that we should let social norms dictate what people do, and not impose technical restrictions. However, perhaps everyone should be notified when the access control is changed, or we throw up a warning saying "hey, you're about to expose existing comments to a wider audience than originally intended. Make sure this wouldn't surprise any participants before sharing more widely."

**Comment by beck24** [comment]
I'm fine with having some sort of UI notification, I would consider that a nice feature actually

**Comment by iionly** [comment]
Not syncing the access level of comments on changing the access level of the container entity is not only a headache regarding WSOD issues but even more so it results in possibly incomplete threads being displayed to different users depending on when the comments have been added.

If threaded comments ever become a feature the problem of out-of-sync access levels would only get much worse!

How about that:

Access level of container entity can be changed only on one of two conditions:

* there haven't been made any comments yet or

* the user changing the access level after comments have been added is an admin (or maybe also allow it to be done by group owners/group admins). In this case the access level of all comments get updated, too.

**Comment by beck24** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/8062
