### ISSUE TITLE
CSS selector .elgg-table-alt td, th

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7808]
Admin stylesheet has rules for these selectors: ```.elgg-table-alt td, th```. Shouldn't th be prefixed with elgg-table-alt?

**Comment by juho-jaakkola** [comment]
Yes, seems like it.

**Comment by hypeJunction** [comment]
Should this be fixed in 1.10 or 1.x?

**Comment by juho-jaakkola** [comment]
I suppose technically would have to be 2.0 because this might break someone's theme.

It's however very minor change and it's unlikely anyone has modified the admin styles. So I'm fine with 1.10.

**Comment by mrclay** [comment]
Yeah, 1.10 is fine with me

**Comment by Srokap** [comment]
@hypeJunction Can we please try to not push unwanted branches to the upstream? I assume https://github.com/Elgg/Elgg/tree/hypeJunction-patch-1 is pushed to Elgg/Elgg by accident? It creates unnecessary junk in dependant integrations that needs to be cleaned up and if we keep removing it we start risking deleting bad branch (in case of making another mistake), which would be a real bummer. I'd just prefer not have to do such cleanups at all.

We were talking about allowing additional branches only for long running stuff, which I assume https://github.com/Elgg/Elgg/tree/f_7543_resource_views is, rightt @mrclay ?

Generally I don't fancy that, but can live with it in few justified cases. Own fork is a veryhood place to keep ton of junk https://github.com/Srokap/Elgg/branches ;-)

One example of things that need to be cleaned up from those is packagist: https://packagist.org/packages/elgg/elgg not to mention travis notifications.

I realize that it may still happen by accident when so may folks have write access, but please try to mitigate that risk in your workflow.

**Comment by hypeJunction** [comment]
Oh, totally sorry. I did this via github and thought it would be creating a
branch in my fork.

**Comment by Srokap** [comment]
It's just inconvenient, but makes me wonder about securing tags against mistakes: https://github.com/Elgg/Elgg/issues/7810

I'll remove branch from packagist.

**Comment by hypeJunction** [comment]
You can delete from github as well. I will make a proper pull request later.

**Comment by Srokap** [comment]
Ok, thanks!

**Comment by hypeJunction** [comment]
Closed by #7809
