### ISSUE TITLE
Consider signing of tags with GPG

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#7810]
And to verify all tags on Travis. That is to avoid accidental tag overrides. That's especially important as we slowly encourage using packagist directly instead or releases on elgg.org and some tags mixup would go unnoticed. 

We had accidental branch pushes before, but I imagine it's possible to do similar mixup with tags when messing around with two other forks for example.

As we seem to run packaging only on osuosl servers, we could just keep the key there and use only from release script. That could be verified by additional test on Travis that would just check signatures of all tags in main repo.

I'm not crazy about implementing it really, but I feel it's important for security when having large group of people with write permissions.

**Comment by jdalsem** [comment]
We now use protected branches (https://github.com/Elgg/Elgg/issues/8974), so we should be much safer now. I do not see the need for even more protection (at this moment)
