### ISSUE TITLE
Move widgets parts of core js libs to AMD

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7817]
The following parts of the Elgg javascript core could be AMD-ed

js/lib/widgets.php (require js in page/layouts/widgets)

**Comment by mrclay** [comment]
I think @ewinslow and I are of the opinion that it's not worth the effort dealing with back compatibility.

**Comment by jdalsem** [comment]
Well it is 10% (2.5kb) of the javascript that is loaded (on a clean install of Elgg, with no plugins enabled) which is never used, so seems a little pointless. 

> not worth the effort dealing with back compatibility

Elgg did it with the friendspicker ui (https://github.com/Elgg/Elgg/commit/039be39ec1832362454ebda3114f3677f9b3c03a), so why not with the widgets?

**Comment by mrclay** [comment]
In hindsight https://github.com/Elgg/Elgg/commit/039be39ec1832362454ebda3114f3677f9b3c03a broke BC (if someone had registered a new script for "elgg.userpicker") and the switch to AMD would (now) be rejected under semver. You have some options:

Today, override the js/elgg view and get rid of widgets. Next minor version: add a hook so plugins can switch out those file locations without overriding the whole view. 2.0: AMD everything.

**Comment by jdalsem** [comment]
Luckily i already know what i can do with plugins, i only hoped we could clean up core more, but this seems one for the long run...
