### ISSUE TITLE
Registering notification events for annotations crashes the notification service

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#7822]
```
elgg_register_notification_event('annotation', 'likes', array('create'));
```

causes

> ( ! ) Fatal error: Call to undefined method ElggAnnotation::getContainerGUID() in /var/www/html/elgg/engine/classes/Elgg/Notifications/SubscriptionsService.php on line 65

It's trying to find subscription records for the container guid, which annotations don't have. We either need to not allow notification event registration for non-entities, or to cover the case of an annotation and look up the container guid of the annotated entity.

**Comment by jeabakker** [comment]
fixed in #10230
