### ISSUE TITLE
Why is elgg_view_entity_list marked as private

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7826]
The function `elgg_view_entity_list` is marked as private. I believe this should be a public function as it is very normal to call this function from plugins that have their own "wrapper" functions to get entities and require a default way of listing them.

Is it a good idea to mark this as a public function?

**Comment by mrclay** [comment]
I don't see why it must be private but I haven't looked at the commit that added that.

**Comment by mrclay** [comment]
@brettp made private in https://github.com/Elgg/Elgg/commit/0ecbe633a83170e0f487f14cc8783117795230e1. I'd be OK making it public again. I've had to use it in plugins as well.

**Comment by mrclay** [comment]
Closing in favor of #7838
