### ISSUE TITLE
Get rid of ege() wrappers

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7831]
I should be able to call `elgg_get_entities(['metadata_names' => 'icontime']);` and Elgg just knows how to handle it. Same with annotations, relationships, etc. Advantages:

 - Can get rid of lots of functions as well as associated listing functions
 - In some cases could *combine* the powers of multiple wrappers
 - Simplifies APIs that decorate $options
 - Don't have confusing goose-chase docs like "this thing accepts all ege() options"
 - Don't have to remember which ege() flavor handles what
 - Can put all ege() docs in one place

Advantages of current design:

 - It exists now
 - Intention of query is maybe a bit clearer to reader
 - Removing all wrappers may not be possible

**Comment by mrclay** [comment]
Here's an experiment that seems to work: https://github.com/mrclay/Elgg-leaf/compare/Elgg:1.x...mrclay:7831_super_ege

**Comment by juho-jaakkola** [comment]
Nice! Will try to find time to test.

**Comment by jdalsem** [comment]
+1 for the idea, but it will increase the effort if you want to use a custom where for example.

`elgg_get_entities_from_private_settings(['order_by' => 'ps.value']`

vs

`elgg_get_entities(['order_by' => 'ps.value']`

second version will not work as we can not assume private settings are joined

**Comment by mrclay** [comment]
From working on this I don't think it's worth the effort. It's not a significant hurdle to development and I think it would blow up complexity of an already complex system.

That said, a simple component that could determine the right query function based on $options would be useful.
