### ISSUE TITLE
Should there be a public version of get_subtype_id

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7835]
Currently if you need the id of a subtype to use in (custom) queries, it can only be done with this function. It is showing up frequently in our plugins, so i am wondering if there should be a non-private API function to get this info.

**Comment by juho-jaakkola** [comment]
I believe I have also used it.

**Comment by mrclay** [comment]
Lets just make it public. Making a new elgg_ prefixed version just adds more clutter to core and to plugins.

In my ideal schema (I'll share this soon) there's a single "types" table for all internal non-content strings: type, subtype, relationship name, annotation type, etc.

**Comment by iionly** [comment]
One more example of a function that wasn't private when introduced but then made private later. Another related function with the same "belated private" problem: get_subtype_class() (not used as often as get_subtype_id() but for example used in Tidypics and Widget Manager nonetheless).

get_subtype_id() is often used in activate.php of bundled and non-bundled plugins. Removal/renaming would only result in BC issues, so again the best solution would be to make it "public" again.

**Comment by mrclay** [comment]
Closing in favor of #7838
