### ISSUE TITLE
Deal with private API stuff still needed by plugins

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7838]
[Source](https://community.elgg.org/discussion/view/1847926/deleting-functions-marked-access-private?offset=10#elgg-object-1864622):

 - [x] Make public  elgg_view_entity_list (#7826),
 - [x] Make public get_subtype_class,
 - [x] Make public get_subtype_id,
 - [x] Make public access_get_show_hidden_status,
 - [x] Make public access_show_hidden_entities,
 - [x] Make public version of _elgg_html_decode,
 - [x] Consider what to do about elgg_get_upgrade_file_version,
 - [x] Consider what to do about generate_action_token,
 - [x] Consider what to do about _elgg_services()->hooks->getOrderedHandlers().

cc @iionly

**Comment by jdalsem** [comment]
can we also add public helper functions for: `_elgg_services()->db->enableQueryCache()` and `disableQueryCache()`?

**Comment by jdalsem** [comment]
assigned to 1.11 as i would like to give clarity to devs about the usage of the functions.

**Comment by iionly** [comment]
Bummer! Now Elgg 1.11 got released without the clarification on the future of these private functions.

How about you simply vote on it to get this matter sorted out? It would really, really be quite helpful to know what will be decided. And I think it should even be possible to make these functions public (again) in a bugfix release (the sooner the better) as there wouldn't be any changes in functionality.

**Comment by beck24** [comment]
d'oh, I guess this got overlooked.  I vote to make them public, I've needed to use almost all of the listed functions in plugins.

**Comment by ewinslow** [comment]
making them public sounds fine with me.

**Comment by iionly** [comment]
@Elgg/owners wouldn't it be good to decide on how to proceed with these functions for example before the final 2.0 is out?

**Comment by mrclay** [comment]
PR #8766

**Comment by iionly** [comment]
Has elgg_view_entity_list() been forgotten? Issue #7826 has been closed with reference to this issue here but now the PR does not deal with it.

**Comment by jdalsem** [comment]
elgg_view_entity_list() has not been forgotten https://github.com/Elgg/Elgg/pull/8766/files#r35903761
