### ISSUE TITLE
Remove rst docs from docs.elgg.org

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7842]
E.g. http://docs.elgg.org/master/en/intro/install.html

This is still live and crawled by Google. It is taking away from learn.elgg.org

**Comment by jdalsem** [comment]
what is holding us back to drop docs.elgg.org??

**Comment by Srokap** [comment]
Being nice to 1.7 users as well as respecting work done on translations I suppose. We're talking here about old rst docs builds that should be removed. I think that unless it becomes a burden, we might leave those parts of the docs that we're never migrated. Making some global header template indicating that it's outdated docs and pointing to learn.elgg.org would be nice.

**Comment by jdalsem** [comment]
why not add a no-index to the robots.txt or add a meta header

**Comment by ewinslow** [comment]
Removed old rst docs and disallowing all crawling from robots.txt
