### ISSUE TITLE
get_registered_entity_types() cannot check types with no subtype

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7843]
E.g. even if "group" was registered as a type, `get_registered_entity_types('group')` returns false.

**Comment by Srokap** [comment]
I wonder why we don't just use the subtypes data from database for that purpose. We load it anyway, so whole process of additional registering entity types seems somewhat obsolete.

Apart from that i'm not sure what really would we like to return for the types without subtype. Empty string?

**Comment by mrclay** [comment]
These functions should be given aliases like elgg_register_as_searchable. Current names are meaningless.
