### ISSUE TITLE
Facility for generating changes between current Elgg version and target Elgg version

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7844]
The auto-generated CHANGELOG is really great, but it occurred to me that what you really want to know is "what are the changes between my current version and the version I'd like to upgrade to".

So, a tool for dynamically generating changelogs between two arbitary versions of Elgg would be great.

How to expose this and make it useful? that's another question. But it does make me question how much we even need to check in a CHANGELOG.md file into the repo at all, if we had this tool.

The overarching motivation here would be to pull the version string out of core entirely, and just use git tags. 

This would all be meant to simplify our overhead even more.

**Comment by Srokap** [comment]
That sounds very natural to add to my core version widget. I could try to parse the changelog from github, but putting it into some json file (in additon to human-readable one) would simplify the parsing process if we ever change the format.

I'm happy to consider adding core version widget along with the changelog checker to the core, though there wasn't much interest in it when I originally did the plugin. Let me know if you'd like it.

**Comment by jdalsem** [comment]
So basically it is the diff between online version and local version of the changelog

**Comment by jdalsem** [comment]
Just fetch the github releases/tags to have them in a dropdown selector to select which version to diff

**Comment by mrclay** [comment]
My gut feeling is that lists of changes don't matter as getting solid feedback on compatibility of the plugins in your installation, and so I see great value in Pawel's code_review plugin. How could we allow it to review 3rd party plugins based on an Elgg version that you *haven't yet* upgraded to?

**Comment by ewinslow** [comment]
I like this a lot. You should definitely submit to core.

Mrclay, plugin compatiblility also sounds awesome but seems like a different ticket...

**Comment by jdalsem** [comment]
We have the changelog, automated release notes and the github diffs if you really need it. No need to keep this ticket open
