### ISSUE TITLE
Subscriptions overhaul

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7859]
## Current system

Currently Elgg subscriptions are relationships with the name: `notify<notification_method>`.

If user **101** wants to be notified via email when user **202** creates content, the following relationship is created between them:

| guid_one | relationship | guid_two |
| --- | --- | --- |
| 101 | notifyemail | 202 |
- User **101** will receice a notification of _every_ piece of content that **202** creates regardless of their type
- User **101** can receive a notification _only_ if the created content is an entity (there is no support for annotations, metadata or relationships)
## Suggestion

Braindump of my current thoughts to make the subscriptions better:

Instead of using relationships, let's create a very own table for subcriptions. The structure could be something like this:
- **id**: Unique identifier of the row
- **user_guid** GUID of the user subscribing to receive notifications
- **action**: The action that triggers the notification
- **target_guid**: GUID of the action's target 
- **method**: The notification method (email, sms, etc)
- **type**: Type of the target
- **subtype**: Subtype of the target

This kind of data structure would allow very granular subscriptions.
## Examples:

| id | user_guid | action | target_guid | method | type | subtype |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 101 | create | 202 | sms | object | blog |
| 2 | 101 | create | 303 | email | annotation | likes |
| 3 | 101 | update | 303 | email | object | blog |
| 4 | 202 | create | 404 | site | relationship | member |
1. User **101** receives an SMS notification when user **202** creates a blog.
2. User **101** receives an email when someone likes the blog **303** (that **202** created)
3. User **101** receives an email when someone updates the blog **303**
4. User **202** receives a site_notification when someone joins the group **404**

There is a lot of stuff to figure out before something like this could be implemented. So don't treat this yet as a valid plan.

**Comment by juho-jaakkola** [comment]
Hm... I suppose we also need an own column for ```actor_guid```. In the first example row the user **202** should in fact be the actor and not the target, right?

**Comment by juho-jaakkola** [comment]
...or should the actor/target issue be figured out by the separate notifications system? I'm not sure yet.

**Comment by juho-jaakkola** [comment]
Note to self: Moodle seems to have very granular subscriptions system. Might be a good idea to check how it's handling them.

![moodle](https://cloud.githubusercontent.com/assets/883920/6044400/a9988c08-ac9b-11e4-8f90-64be3d585253.png)

**Comment by mrclay** [comment]
Studying Moodle's data model would indeed be a good idea.

My first impression is that having to have a row for each possible action on an entity is too granular, though you could store `any` or `*` to match any action.

Reusing the target_guid column for different things (sometimes the object, sometimes the container) seems confusing. Could we borrow from the river schema? E.g.
id, subscriber_guid, notification_method, (river columns)

**Comment by jdalsem** [comment]
As this is a Elgg 2.0 thing, you could do the rename as suggested in #6686 if that is appropriate.

**Comment by jdalsem** [comment]
related to #5911

**Comment by ewinslow** [comment]
I think this could be largely alleviated by adding a name to the notification relationship:

`notify:{name}:{method}`

`{name}` can be arbitrary so it can represent an arbitrarily complex query. And it doesn't require another table, which would be somewhat limiting if we ever wanted to have a subscription query that the table didn't have the right fields to represent.

I also recommend that we continue to call it "notifications" rather than subscriptions because that is what the rest of the world calls this feature.

**Comment by ewinslow** [comment]
maybe we could name it like event registration:

on:{event}:notifyby:{method}

Examples:

```
// every time the upgrade script is run
$site on:upgrade:notifyby:web $admin

// every time a new group is created on the site
$site on:new_group:notifyby:sms $admin

// email me about new comments on this post
$post on:new_comment:notifyby:email $user
```

**Comment by mrclay** [comment]
@ewinslow :+1: if it covers all the use cases

**Comment by jdalsem** [comment]
Improved subscriptions logic added in https://github.com/Elgg/Elgg/pull/13408
