### ISSUE TITLE
Site menu breaks on page loading

### ISSUE THREAD

**Issue by insideth** [Elgg/Elgg#7861]
With responsive navigation, on page loading if you click on menu button page breaks.

![image](https://cloud.githubusercontent.com/assets/6679837/6045323/90309488-ac99-11e4-8a08-7db645fca51c.png)

I have tested it in my Elgg 1.8 & 1.9 installation and at Elgg community website (see sreenshot) with Aalborg theme enabled.

You can reproduce it refreshing the page and just clicking on the menu buttom. This issue is more evident with slow connection (like mobile internet connections)

**Comment by mrclay** [comment]
Yes, this button abuses the href property. Should probably be a data- attribute.

**Comment by mrclay** [comment]
PR #7865
