### ISSUE TITLE
Account statistics shows counts for internal-only entities

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7862]
This should probably only show entity types/subtypes that have been registered as public-facing with elgg_register_entity_type(). E.g. on my site all users own an internal-use-only object used as a container; this shouldn't show in stats.

**Comment by mrclay** [comment]
@hypeJunction have any thoughts on this since you contributed #7845?

**Comment by hypeJunction** [comment]
The concept of public facing entity types is still a bit foggy. I think we
first need to define what it's meant to mean.

**Comment by hypeJunction** [comment]
To clarify my earlier remark: widgets are public facing entities and
providing a count of those would make sense in stats, however widgets are
not searchable.

**Comment by jdalsem** [comment]
I think all counts are interesting, but maybe we could visually organize them in "searchable" entities and the rest

**Comment by mrclay** [comment]
Simple solution: Allow injecting $vars['stats'] into the core/settings/statistics/numentities view. If not set go ahead and use get_entity_statistics(). Plugin can then use the view_vars hook (#7864) to inject the desired stats.
