### ISSUE TITLE
Ajax loading animations should be immediate

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7868]
The goal is to convey immediate responsiveness to the user, so we shouldn't wait for an image to load. If a connection has been lost the image might not load at all.

Let's try to replace the GIF with a CSS animation in supporting browsers, or at least make the GIF a data URL in the CSS.

http://caniuse.com/#feat=datauri
http://caniuse.com/#feat=css-animation
http://fgnass.github.io/spin.js/

**Comment by jdalsem** [comment]
could be easily fixed when we have the fontawesome icons #7239

**Comment by hypeJunction** [comment]
I have switched to data URLs a while ago. I gave up on font awesome spins
as they are a bit hacky and you are stuck with only 3 usable icons.

**Comment by jdalsem** [comment]
data uri seems like the easiest fix for now (support is fine), only wondering if we should add it to the css or as an inline style (to save size/bandwidth on the css file)

**Comment by mrclay** [comment]
After DOM loads, `$('<img />')[0].src = '...';`. Does this old trick still work? I'm suspicious modern browsers delay loading until it's visible in the doc.
