### ISSUE TITLE
elgg_get_page_entity()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7870]
Elgg already keeps track of the "page owner", it might well do the same for the main entity being viewed to eliminate the need for hacky things like sniffing the URL or extending object views just to capture $vars['entity'] in elgg_set_config().

I understand our resistance to creating more global state, but other than passing all state down into every view, there's no other great way to get to this commonly needed item.

We should also pass this to JS.

**Comment by jdalsem** [comment]
We could set it when there is an `elgg_view_entity` where `full_view = true`

**Comment by mrclay** [comment]
That assumes no listings will use full view, but for that risk you don't have to update any plugins. Seems like a winner.

**Comment by mrclay** [comment]
Cheap workaround:

```php
elgg_register_plugin_hook_handler('view', 'all', function ($h, $t, $v, $p) {
    if (!empty($p['vars']['full_view']) && $p['vars']['entity'] instanceof ElggEntity) {
        elgg_set_config('full_viewed_entity', $p['vars']['entity']);
    }
});
```

**Comment by jdalsem** [comment]
combine this with an `elgg_get_page_entity()` and `elgg_set_page_entity()` and you have a game changing dev feature

the hook should however only set if the current value is empty, to allow page handlers to set the entity for example

**Comment by mrclay** [comment]
I figure we would call elgg_set_page_entity() directly inside elgg_view_entity(). The code I posted just allows sniffing the entity today.

**Comment by hypeJunction** [comment]
I think this also goes hand in hand with elgg_entity_gatekeeper(). Not sure
elgg_view_entity() is necessarily the right place for this. I think this
should be called explicitly by plugins - magic might be lead to unexpected
results.

**Comment by beck24** [comment]
I agree with @hypeJunction on that

**Comment by jdalsem** [comment]
> I think this also goes hand in hand with elgg_entity_gatekeeper()

i do not see the link between the page_entity and the entity_gatekeeper

> I think this should be called explicitly by plugins

disagree as `full_view  => true` is the right concept of showing the full view of a single entity and therefore it is most useful to set this automatically in `elgg_view_entity`

**Comment by mrclay** [comment]
One problem with "automatic" setting in another function is you don't know when that function will be called. It's already very confusing to debug all the places the page owner is set; I think manual setting is probably best even though we don't get it "for free".

**Comment by hypeJunction** [comment]
A user profile would have a page entity, but you don't use elgg_view_entity()  to display it. Neither do you have full entity view for groups. A blog full view does not include comments (those appended in the page handler), so I don't think full entity means anything here. 
Perhaps revisiting  #5481 would be worth a while.
Page owner and page entity are concepts that should be handled on a page handler level, and now in lower level views. If you were to display a list of entities and passing full_view, you would have page entities changing with each new item rendered.

**Comment by jdalsem** [comment]
we already have that in place `object\elements\full`, but its usage is not wide spread (blog uses it though from its `object/blog` view)

**Comment by mrclay** [comment]
The fact that our own plugins don't consistently use elgg_view_entity() is compelling reason to not rely on it.

Does having a page entity GUID set mean that that GUID is "vetted" (visible to the current user and is the right type for the URL)? The page owner concept is vague about this and I don't like that it loads the entity bypassing access. I feel the entity should be set directly after verifying it's what we expect it to be.

**Comment by mrclay** [comment]
...I mention this because we usually don't fully verify the entity in the router, so putting elgg_set_page_entity() in page handlers would require moving logic there.

**Comment by hypeJunction** [comment]
Hence my mention of elgg_entity_gatekeeper()

**Comment by hypeJunction** [comment]
I suppose the quickest simple solution is to update our best practices to suggest that 'entity' be passed with vars to the page shell and layout, and making sure that all underlying views pass it along.

**Comment by jdalsem** [comment]
@hypeJunction that is unusable. That means only views called from the page handler can be used and not views outside of it (like page/elements/sidebar extensions or headers or footers)

**Comment by jdalsem** [comment]
ho, i misread. You can indeed pass it to the page shell... via the page_draw function

**Comment by jdalsem** [comment]
i think it would be best to rely on `$vars['entity']` adding a magic function is not helping

**Comment by hypeJunction** [comment]
No more globals state please :) We can now add a helper to deduct an entity form current route though
