### ISSUE TITLE
register menu item to multiple menu's at once

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7871]
add the option to pass an array of menu's to 
`elgg_register_menu_item(['topbar', 'footer'], $menu_item)`

**Comment by juho-jaakkola** [comment]
What are the use cases?

**Comment by jdalsem** [comment]
not much, but i thought about it related to owner_block vs user_hover vs a new suggested profile menu. Seems like an easy feature

**Comment by hypeJunction** [comment]
I don't see a difference between you iterating through your array or the
core doing it for you.

**Comment by jdalsem** [comment]
agreed
