### ISSUE TITLE
Move river group string to it's own view

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7872]
The group string is appended to the summary string in river/elements/body, which seems a bit out of place. I think we should move to it's own view or the summary view to make it easier to replace.

**Comment by jeabakker** [comment]
it was moved to the summary view in #10872, is that good enough, or do you still want a separate view?

**Comment by hypeJunction** [comment]
IMO, anything that needs ``<<<HTML`` deserves it's own view

**Comment by jdalsem** [comment]
this is good as is now, as group string is moved to the summary view (just as suggested)
