### ISSUE TITLE
Replace friends filter with "in your network" or "for you"

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7873]
This suggestion is about replacing the "friends" concept with a more reusable "for you" approach.

When listing content we have the default filters "All", "Friends" and "Mine". But how about content i am subscribed to? Or content created in groups i am member of? I suggest we replace the "Friends" tab with a "For you" filter where plugins (like friends, if that is becoming a plugin) can hook into to provide a listing of content that i am interested in. 

This will make that filter more useful and prevents the creation of all kinds of extra tabs, or even the need to remove the friends filter.

**Comment by iionly** [comment]
I think neither the term "for you" nor "in your network" are self-explanatory. As a user I would have difficulties to understand what such a tab shows. I imagine the following questions would arise for example:

* What is the difference between "mine" and "for you"?
* What is the difference between "all" and "in your network"?
* Is "for you" the same as "private"?

How about a single filter tab (in addition to "all" and "mine") with the user's specific ACLs as choices (for example offered by a dropdown selection or whatever seems appropriate) including "friends", "subscription", the user's groups and whatever might be additionally added to the selection by 3rd party plugins.

**Comment by mrclay** [comment]
Agree with @iionly. Seems confusing to the user.

Another problem is it's practically impossible for plugins to additively collaborate on a query without a nasty UNION or WHERE guid IN (query), etc. Maybe you mean collaborate on a dropdown of individual queries?

Ideally the filter tabs and dropdowns could be built through some hook-based query builder or convention that cuts down on boilerplate.

**Comment by ewinslow** [comment]
Seems like this proposal as currently specified is not going to happen
