### ISSUE TITLE
Put all friends related stuff into a plugin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7874]
Discussed in multiple tickets, i suggest we make some effort to move all friends related stuff (UI, access, related views, actions) all into a separate plugin.

Elgg 2.0 is a nice moment to do this. It could make the core more lightweight and allows Elgg to be better useful in communities where the friends concept is not needed (or even a burden).

**Comment by juho-jaakkola** [comment]
I'm afraid it would be extremely difficult to move *everything* into a plugin. But we could start by moving all the user facing features.

This was actually done once (by my ex-workmate), but reverted shortly after. I haven't yet searched for the reason.

**Comment by jdalsem** [comment]
What would be the difficult part?

**Comment by juho-jaakkola** [comment]
One issue is that should all plugins always check ```elgg_is_plugin_active('friends')``` before adding Friends to the filter menu? That doesn't seem right.

**Comment by juho-jaakkola** [comment]
This issue has a good summary: #3445

**Comment by jdalsem** [comment]
> One issue is that should all plugins always check elgg_is_plugin_active('friends') before adding Friends to the filter menu? That doesn't seem right.

That is why i suggested #7873

**Comment by ewinslow** [comment]
@jdalsem is this something you still want to get to? I'm not sure I see the planning/persuading/testing/etc. happening this month.

**Comment by jdalsem** [comment]
> One issue is that should all plugins always check elgg_is_plugin_active('friends') before adding Friends to the filter menu? That doesn't seem right.
> 
> That is why i suggested #7873

Still need some feedback on the above comment and ticket before i can proceed with this

**Comment by jdalsem** [comment]
Closing this as #7873 did not get anybody enthousiastic
