### ISSUE TITLE
Add more generic usage to every elgg_entity

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7888]
Do we want to add this kind of generic functionality to ElggEntities (or ElggObjects)?

 - [ ] read/unread #3498
 - [ ] featured/unfeatured #6293
 - [ ] published/unpublished #3137

There are multiple tickets related to adding more entity related concepts to core. Do we want this in?

**Comment by mrclay** [comment]
I don't think devs will ever agree on how the model should work. E.g. I'd rather give new content "unread" relationships that get deleted, than to fill the DB with "read" relationships. There's also the issue of context. Some could want something featured in a group, and different things site-wide.

In general I think a lot of this becomes easier to build if we work on #2567

**Comment by ewinslow** [comment]
I'm with Steve that we should just make lists easier to manage. I don't think we want/need the elgg entity class api to grow much more.

**Comment by ewinslow** [comment]
Especially since I disagree with him and think that tracking "read" relationships makes more sense. ;)

**Comment by jdalsem** [comment]
> I don't think we want/need the elgg entity class api to grow much more.

if this is the conclusion, it means we can close all the tickets mentioned above. Agreed?

**Comment by mrclay** [comment]
Closing them is fine with me

**Comment by ewinslow** [comment]
Yea, let's just focus on the lists api

**Comment by jdalsem** [comment]
Closed all related tickets. Now expecting a lot from the lists API:)
