### ISSUE TITLE
Lightbox is unusable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7895]
Every time I need to open something in a lightbox and do something more than just display the content, I end up tossing Elgg's lightbox, and using something else instead.
We need a simple AMD solution that doesn't require loading a script, loading a stylesheet, and then going through the multitude of views to figure out how to modify the settings.
It seems a lightbox is a very common feature that will be used accross pages, so I think we should just add the css to the main stylesheet, and convert the js to AMD module.

**Comment by mrclay** [comment]
Do you find Colorbox unusable, or the integration with Elgg? I've found with the data-colorbox-opts attribute and the official docs I'm pretty productive. Can you give an example?

**Comment by hypeJunction** [comment]
It does it's job when you already have the triggers and data in your DOM. But there is no easy way to just display arbitrary HTML content in a lightbox.

For example, if I just wanted to load something via elgg.ajax and only display part of the response in a lightbox, I would first have to load the js and css on the page, then somehow ensure that I have the js and css loaded, then use the colorbox api.

Something straightforward would be nice:

```js
var ligthbox = require(['elgg.lightbox']);
lightbox.open({ 
   // colorbox options
});
lightbox.close();
```

**Comment by mrclay** [comment]
Yep, convert lightbox to AMD, and have it load CSS somehow.

**Comment by jdalsem** [comment]
Converting all JS to AMD is on the roadmap for 2.0. This needs to be piece of cake then

**Comment by hypeJunction** [comment]
Yes, I think we can close this as it will be taken care of by Steve's new ajax api.

**Comment by mrclay** [comment]
Let's leave this until the APIs/fix is firmly in place.

**Comment by mrclay** [comment]
Related https://github.com/Elgg/Elgg/issues/8405

**Comment by hypeJunction** [comment]
Along the lines of my thinking: https://github.com/hypeJunction/elgg_lightbox/blob/master/views/default/js/lightbox/test.js
