### ISSUE TITLE
Entity view as volatile data

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7899]
```elgg_view_entity()``` currently checks entity metadata ```->view``` before doing it's magic to identify the view by type and subtype.

What are your thoughts on adding an option to pass the view with volatile data? Use cases are numerous: embed lists, search results etc. Currently, we have to reinvent the lists, if we want to render an item with a different view.

**Comment by mrclay** [comment]
The general problem is how to preset the view used when rendering 1 or several entities. I think that's solvable another way. Mostly I'm not crazy about using an entity as storage for a very temporary rendering option.

**Comment by mrclay** [comment]
Actually I think the changes to allow reading the view from vdata is fine, I just wouldn't want that to be the common way to specify the view. I could imagine it being useful for overriding the view specified for the rest of a list

**Comment by mrclay** [comment]
elgg_view_entity() and the list functions should allow passing in the entity view. Then I'd change this to allow the vdata view to always take precedence.

**Comment by mrclay** [comment]
I think we're now leaning towards something like this:
```php
echo elgg_list_entities([
    // query stuff
    'item_view' => 'the_view_name'
]);
```

Actually I'm concerned that using volatile data at all would require code to "clean up" that data after rendering, and if this wasn't done, other plugins who might render the entity would get a surprise.

**Comment by hypeJunction** [comment]
Good point on volatile data clean up.

**Comment by mrclay** [comment]
Strawman ideas:
`item_view` is string => same view for all items.
`item_view` is array => default view is "__default" key, GUID keys for specific elements.
`item_view` is callable => view is return value after passing in the entity.

**Comment by hypeJunction** [comment]
SGTM.
Can you review the PR and tell me what you think?
I have rewritten the embed list and invitation request list using the new approach. Make life much easier, and keeps the code way cleaner.

**Comment by hypeJunction** [comment]
@mrclay , I am trying to think of use cases, where you would be mixing different views in the list and I can't come up with anything aside from search results. Perhaps keeping it simple would be better. Alternatively, the entity_view can do the dispatching and serve an alternative view if necessary.

**Comment by mrclay** [comment]
Yeah, let's keep it simple

**Comment by hypeJunction** [comment]
After sleeping on this, I think a single item_view param would be cleaner. The actual view can dispatch if necessary.
Re: closures. It would be great to have them, but ultimately views are closures, but better, since you can override them in plugins.

**Comment by hypeJunction** [comment]
Closing in favor of a parameter approach in #7903
