### ISSUE TITLE
Allow plugins to collaborate on Ajax requests

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7923]
You might want to trigger some change based on some user action of another plugin. E.g. in comment_tracker, we're going to auto-subscribe the user to an object if you comment on it or *like it or any of the comments on it*. Having the Ajax request be transparent [creates problems](https://github.com/AU-Landing-Project/comment_tracker/pull/19#issuecomment-74029614).

I'm imagining two new client-side hooks. One would be fired on elgg.action, ideally letting you alter the request in some way. The other would be fired when the response returns, giving you preliminary access to the response. On the server side we would create a way for events/hooks to inject data into the Ajax response.

In our case, our server side event (firing during a like) could inject data into the response and we could react to that data client-side.

Obviously today there's no standard way of making a JSON response if it's JSON at all, so we'd have to clean up our act and make a standard JSON response container for Ajax requests and nudge devs to use it.

@juho-jaakkola @ewinslow @hypeJunction

**Comment by mrclay** [comment]
Even the limited-power client side hooks would be useful immediately. In our case when the likes response came back we could fire our own request to get the info we need. Not as elegant as 1 request, but useful.

**Comment by ewinslow** [comment]
Don't we already trigger before/after hooks for actions client side?

**Comment by hypeJunction** [comment]
@mrclay Did you sneak this in with elgg/Ajax?

**Comment by mrclay** [comment]
Fixed by #8955
