### ISSUE TITLE
Non-private _elgg_* functions fate

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#7924]
We have following functions not marked explicitly as private:
- `_elgg_add_metastring` - not used in the core, warning says explicitly to not use it `ou should not call this directly. Use elgg_get_metastring_id().`
- `_elgg_comments_permissions_override` - missing `@access private` tag?
- `_elgg_comments_notification_email_subject` - missing `@access private` tag?

I'd just remove the first one and mark next two as private as the prefix is petty much giving up that it's internal thing. Objections?

BTW we have 184 `_elgg_*` functions. Awfully a lot of stuff in global scope.

**Comment by ewinslow** [comment]
These all private. Have no mercy

**Comment by ewinslow** [comment]
We can delete _elgg_add_metastring, yes.

**Comment by jdalsem** [comment]
:+1:
