### ISSUE TITLE
How to handle jqueryui?

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7925]
I did some testing with an almost neglectable server response (on a basic Elgg install). Browser time until domReady was still 1 second. Biggest reason: jquerui. Not including that library reduced domReady to 500 ms.

We should really switch it to amd loaded modules, but we probably can not do this right now, as plugins assume ui to be available, so we should plan this for 2.0.

We should also drop jquery-migrate while we are at it.

**Comment by ewinslow** [comment]
+1

**Comment by ewinslow** [comment]
This has been moved to bottom so that's much better now, but agree we should convert to AMD.

I am going to do this in #8393. Also see #8281

**Comment by ewinslow** [comment]
I don't see this changing for 2.0. It's at the bottom now which is much better than before.

**Comment by jdalsem** [comment]
Closing for the same reason as #7099 https://github.com/Elgg/Elgg/issues/7099#issuecomment-115393209
