### ISSUE TITLE
Race conditions with AMD and plugin hooks

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7926]
How does a plugin use AMD and plugin hooks, but guarantee that its hook handlers are registered by the time they're triggered in another module?

**Comment by mrclay** [comment]
Strawman: We define a module "elgg/hooks", which (somehow) has all active plugins as dependents. Modules that trigger hooks can only do it by depending on elgg/hooks.

**Comment by mrclay** [comment]
To participate, a plugin provides a module PLUGIN_ID/hook_handlers, which can depend on any module EXCEPT elgg/hooks. The elgg/hooks module will be defined via PHP to depend on all the plugin hook_handlers modules.

So now a module can require(elgg/hooks) with confidence that all hooks have been registered.

This creates a perf issue because defining elgg/hooks could mean *always* requiring a deep tree of mofules. But that seems to be the cost of implementing hooks in a lazy-loading async environment.

**Comment by mrclay** [comment]
Strawman 2: Any modules that trigger hooks could do something like this:

```js
// elgg module
define(function (require) {
    <?php echo elgg_inject_amd_deps($vars); ?>

    // use trigger hook...
});
```

elgg_inject_amd_deps() looks for `$vars['amd_dependencies']` and if it's an array of strings, it returns something like:

```js
require('string1'); require('string2');
```

Now any plugin can register dependencies on this module:

```php
elgg_register_amd_dependency('elgg/module', 'myplugin/hooks');
```

Where this function sets up a handler for the `"view_vars", "elgg/module"` hook (PHP), where it sets `$vars['amd_dependencies'][] = 'myplugin/hooks'`.

**Comment by mrclay** [comment]
We could make the above idea more powerful (and dangerous):

```js
define(function (require) {
    <?php echo elgg_prepend_amd($vars); ?>
});
```

...where we allow a plugin to inject arbitrary JS code at the top of the definition.

**Comment by mrclay** [comment]
Simpler (and more dangerous): just allow plugins to prepend code to the body of the definition function.

```js
// elgg module
define(function (require) {
    <?php echo elgg_view('js/elgg/module/head'); ?>

    // use trigger hook...
});
```

**Comment by juho-jaakkola** [comment]
I thought we're currently not caching the AMD modules? (We cannot use PHP unless we cache the views.)

**Comment by mrclay** [comment]
All AMD modules are loaded through /cache. In this case indeed these modules would have to be in .php files unfortunately.

**Comment by mrclay** [comment]
I think my [first idea](#issuecomment-74243352) was a lot better. It doesn't introduce require the plugin dev to know all the views that use a particular hook.

**Comment by mrclay** [comment]
@ewinslow got any input here?

**Comment by ewinslow** [comment]
Ideas:

Make the rendering more React-like, such that plugins can load their modules lazily and the ui will auto update when the new hook is registered because the result of triggering the hook will be different. This is my preference but seems like not an option in many cases like ckeditor which doesn't seem like it can work like that (reinitializing with different options during editing).

Actually that's my only idea. The other one is the same as Steve's: prevent hook triggers until plugins have loaded their required modules.

**Comment by mrclay** [comment]
If our hooks API didn't exist, how would we implement the task of giving plugins the opportunity to filter values in an AMD a system?

**Comment by mrclay** [comment]
I'm soliciting help on SO: http://stackoverflow.com/questions/29145748/how-can-server-side-plugins-collaborate-on-amd-module-configuration

**Comment by mrclay** [comment]
An idea I had while writing the SO post: #8082

**Comment by mrclay** [comment]
The decoration solution is working! #8085

**Comment by mrclay** [comment]
I feel like this is important to solve as we push more folks into AMD. Need some fresh ideas. StackOverflow had nothin'

**Comment by mrclay** [comment]
#8319 has some ideas here

**Comment by mrclay** [comment]
Idea 5(?): Server-side we configure AMD module methods to be registered as client-side hook handles. A declarative API would be ideal:

```php
// client-hooks.php
return [
  [
    'hook' => 'init',
    'type' => 'system',
    'module' => 'plugin2/hooks',
    'method' => 'init',
    'priority' => 100,
  ],
];
```

The result is a module `elgg/booted` containing a series of statements (in plugin order) like:
```js
// from mod/plugin2/client-hooks.php
elgg.register_hook_handler('init', 'system', require('plugin2/hooks')['init'], 100);
// from mod/plugin5/client-hooks.php
elgg.register_hook_handler('config', 'something', require('plugin5')['alterSomething']);
```

The `elgg/booted` module is always required, but modules that consume hooks must depend on it explicitly.

**Comment by mrclay** [comment]
I like that #8365 adds a formal API (`elgg/Plugin`) which we could use to add features to the system (like [behaviors](https://github.com/Elgg/Elgg/pull/8319/files#diff-c314b2119f66bb13b742e8f97de2fb64R5), or server-side config data) and there's no need for a separate config file. You drop the standard boot module in the right place and Plugin gives you an init function and whatever we add in the future.

**Comment by mrclay** [comment]
I think the benefit of Idea 5 is also that hook handlers are forced to be globally accessible (via `require()`) methods, which could allow us to add an unregister feature.

**Comment by mrclay** [comment]
PR #8993 adds boot modules, and the involved AMD modules provide the APIs to register and trigger hooks with proper blocking: You can only register in your plugin's boot module, and you can only trigger after all plugins are booted (otherwise deprecation warnings).

**Comment by mrclay** [comment]
New PR #8996. Much simpler. Sorry, went crazy with #8993.
