### ISSUE TITLE
Use composer scripts to smooth out development

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7927]
I kind of hate doing /vendor/bin/phpunit when I want to run the tests. And forget about remembering how to build the docs or check for lint errors.

Composer has the concept of "scripts" that you can use so you can run `composer <script>` and it will delegate to other commands or PHP functions or whatever. We already do something similar for the JS with npm.

#### composer lint
```
vendor/bin/phpcs --standard=vendor/elgg/sniffs/elgg.xml --warning-severity=0 --ignore=*/tests/*,*/upgrades/*,*/deprecated* engine/classes engine/lib
composer validate
```

#### composer test
```
/vendor/bin/phpunit
```

#### composer docs
```
sphinx-build -b html -nW docs docs/_build/html
sphinx-build -b latex -nW docs docs/_build/latex
```

**Comment by Srokap** [comment]
I'd rather use Grunt for that purpose. We already have it integrated for docs development (default grunt task currently).

In general I do like to keep all the Elgg-related commands in one place whether would it be makefile, npm scripts, composer scripts or grunt. Grunt however gives us file watches for free.

**Comment by ewinslow** [comment]
Closing in favor of grunt then.

**Comment by ewinslow** [comment]
I figured since the PHP stuff is managed with composer, we could just use it to run PHP-related things, but I do like the file watching.

**Comment by ewinslow** [comment]
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

Eh... I've changed my mind. I do like file watching but I find composer and npm scripts far simpler to set up and understand. Simplicity is a feature.

**Comment by Srokap** [comment]
Really? For me those are very crude mappings to cli commands while Grunt has lots of builtin features in modules. If you're looking for Grunt equivalent for basic cli commands, you may just add new jobs to https://github.com/Elgg/Elgg/blob/1.10/grunt/exec.js . I did use `load-grunt-config` module that separates configs from main Gruntfile, so it doesn't make it particularly easy to understand, but that's not rocket science really. Only downside I see is that Grunt a bit forces job naming convention, bot we could always define custom aliases to mitigate that. We have two of them currently: https://github.com/Elgg/Elgg/blob/1.10/Gruntfile.js

I can explain any details if needed.

**Comment by ewinslow** [comment]
yes, really.

We already have the CLI commands set up. Composer just allow us to give them simple aliases. I think I'd prefer to avoid the complexity of "plugins" and "load-grunt-config" and "details", and I certainly prefer using Composer for php-related commands (php unit tests, php code style checks, etc.) over a JS tool.

**Comment by ewinslow** [comment]
Note also that these are not mutually exclusive. Grunt can always watch files and run composer/npm commands if we need it to. All our PHP project configuration is in one place (composer.json). All our JS project configuration is in one place (package.json). That's also a feature.

I'm not blocking grunt from being used, but I hope you wont block me from adding some simple aliases to composer.json, either.
