### ISSUE TITLE
Menu section class names should use dashes

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7935]
We replace non-word characters with dashes for menu names, but not section names. This could be a BC break to fix.

**Comment by jdalsem** [comment]
Sections currently replace unwanted chars with dashes

**Comment by hypeJunction** [comment]
Not in section names

**Comment by jdalsem** [comment]
Just tested that class names of sections have dashes... where do you see it otherwise?

**Comment by hypeJunction** [comment]
name your menu with an underscore

**Comment by hypeJunction** [comment]
Looks like it was fixed along the way https://github.com/Elgg/Elgg/blob/master/views/default/navigation/menu/default.php#L26
