### ISSUE TITLE
View stack

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7937]
I often find it hard to come up with new context names to push/pop when I need something rendered differently. I think it could be really helpful to maintain a view stack that could be either available in the context stack, or in its own stack. Views could then use something like ```elgg_in_view()``` to check if the view is being rendered within another view.

**Comment by mrclay** [comment]
I think you can implement this with the new "view_vars" hook, but generally I'm not crazy about the "context" system, or at least the way contexts are magically set (and undocumented) by core. #5912

My main worry here is this allows plugins to depend on particular view hierarchies and would mean even more rigidity when trying to refactor in a BC way.

**Comment by hypeJunction** [comment]
I will sleep on it. Just put it out there to hear some thoughts.

**Comment by ewinslow** [comment]
A more concrete use case would be helpful. I agree with Steve that context
seems awkward  for changing rendering (global state) and it's not clear
when such a think will trigger.

In general it seems bad for a view to need to know all possible contexts it
could be rendered in and change based on that information. The dependency
there is backwards. I bet it results in some logic consolidation though,
which is probably why it was done...

**Comment by hypeJunction** [comment]
Agreed that the logic is backwards. Closing
