### ISSUE TITLE
Suggestion: drop rel='popup' in favor of 'toggle'

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7944]
Currently `rel='popup'` is barely used in core and only causes issues like #3087. I suggest we drop this in 2.0 and replace the current occurences with `rel='toggle'`

**Comment by mrclay** [comment]
Seems like we should deprecate this. Ideas how?

**Comment by jdalsem** [comment]
how do we normally deprecate js functionality?

**Comment by mrclay** [comment]
I'm not convinced rel=popup is worth the effort. A discussion on community and a 2.x PR calling `elgg.deprecated_notice` on usage would be the 1st steps.

**Comment by hypeJunction** [comment]
I would prefer to keep `rel="popup"`. I think toggle is suitable for static DOM elements, where as a popup is an element with fixed/absolute positioning relative to the viewport.
I will make a PR for 3.0 that improves dev usability of the popup component.

**Comment by hypeJunction** [comment]
Popup has many more applications, and it was barely used in core because it was a pain in the butt to use. #9453 aims to make it easy to work with popups. I am going to close this, please reopen if you disagree.
