### ISSUE TITLE
Allow disabling deprecation notices

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7945]
Maybe via developers plugin...

**Comment by iionly** [comment]
+1

Such an option would help to concentrate on other (maybe more severe) issues without getting side-tracked by possibly many (even if always the same) deprecation warnings. And if you want to deal with the deprecation issues at last, you could enable this option and fix them (possibly supported by Code Analyzer plugin which really helps to deal with them faster).

**Comment by Srokap** [comment]
I'm afraid it would end up being disabled and forgotten, but if people like living with broken windows, I'm not going to stop them. Developers plugin sounds like a good place since it controls logging level already.

**Comment by ewinslow** [comment]
+1 -- we are getting deprecation notices that don't matter much, but some other non-technical admins will see them constantly and probably be scared. They also are not actionable at all -- needs to have a stack trace and/or specify which plugin is causing problems so folks can know which one to upgrade...

**Comment by mrclay** [comment]
Notices are no longer visible.
