### ISSUE TITLE
Less intrusive deprecation behavior

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7946]
Problems we need to solve:

* Plugin devs may continue to use deprecated APIs
* Non-dev admin users see deprecation errors over and over
* They report them as bugs to plugin devs
* They fill error logs with junk (and slow the app)
* Warnings don't include enough context
* Warnings don't collect anywhere for focused review
* We *want* to allow older plugins to continue to be usable

Just brainstorming: Each unique deprecation error is displayed once and placed in a listing available in an admin page. In the admin page the warnings also include more detail (at least the info that normally goes to the error log).

The idea is to make the warnings both less intrusive and more reviewable without grepping through an error log.

**Comment by iionly** [comment]
The Code Analyzer plugin gives some good summary already (it's just missing the deprecation warnings from views). I don't know if it would be necessary to add an additional admin page in core.

**Comment by Srokap** [comment]
Stacktrace, last occurence date, total count + option to clear all current stats. We join events by stacktrace and don't bother handling updates in the code automatically (that's what stats clean is for).

It does seem a bit redundant to code analyzer, however it would catch some cases that code analyzer doesn't cover and would be hard to catch without causing false positives.

It should be possible to extract from a decent log analyzing system, but it seems that most Elgg users don't invest much in their application stack, so giving them ready to use tool might make their life easier.

Not convinced about ROI, but see some value in it.

**Comment by hypeJunction** [comment]
As first step, we should remove register_error() for admins in elgg_deprecation_notice(). Let the logger do it's job.

**Comment by mrclay** [comment]
I've updated the description with the problems we're trying to solve here.

**Comment by mrclay** [comment]
I'd agree with @hypeJunction that admin status just doesn't imply a technical user who knows what to do about deprecation warnings (and usually they're too vague anyway). Compared to current behavior I'd definitely prefer suppressing them completely (including logs) unless a "dev mode" was on (#8016).

**Comment by hypeJunction** [comment]
My above comment wasn't relating to technical knowledge of things, rather duplication of certain warnings.

**Comment by ewinslow** [comment]
Age that Admin status does not imply technical user

**Comment by mrclay** [comment]
Notices are no longer visible.
