### ISSUE TITLE
Make schema migrations simpler

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7947]
Data migrations are probably never going to be easy, but I think we can make schema updates trivial. Closest tool I've seen so far is schematic (https://github.com/andrefigueira/Schematic), but I don't like some of the API decisions and it is licensed gpl3, not compatible with MIT core.

I do like the idea of defining schema in json and having the tool figure out what diffs to make, though.

I started a gist that uses php arrays. JSON would be even more portable, but possibly more limiting too (no built-in static checks).

https://gist.github.com/ewinslow/6445c79c9d0db60ed2dd
## Why?

There's a lot of talk about changing up the schema lately and I just feel like it would be nice to make this process easier on ourselves...
### Track diffs with git, not PHP classes

Several other frameworks support DB migrations, but they take the manual up/down diffing approach. This means there is nowhere in the code where you can look at the current schema. You must deduce it from a sequence of migrations. It is like having a form of version control on top of the one git is already giving us. Wouldn't it be better to just view the diffs with git, and not write them manually? Besides that, `down` strikes me as horribly dangerous and prone to data loss. Migrations should always be safe by default. A framework that performs diffs for you can do this automatically.
### Write the schema you want, let the framework figure out how to get there

The current schema upgrade process in Elgg involves writing both the final schema _and_ the diff from the previous schema. This seems horribly error prone since you can write an upgrade script differently from the final product. It also puts me off doing any schema migrations since I essentially have to put twice as much effort into making sure the migration is bug-free.
### Declarative foreign keys

MySQL requires you to write foreign keys as add/drop commands in a certain order with the tables that are present. This is less than ideal as the foreign key definitions then live farther away from the place where they are relevant (i.e. the table on which they apply). It would be easier (IMO), to write foreign keys in a more declarative fashion and let the framework figure out in what order it should add them.
### Better defaults
- charset = utf8
- collation = utf8_general_ci
- engine = innodb
- nullable = false

If we rely on raw SQL, we cannot rely on any defaults since those may be different depending on the user's server configuration and MySQL version. This also means we can default to InnoDB/UTF8 and not have that information cluttering the schema source code.

**Comment by ewinslow** [comment]
There's a lot of talk about changing up the schema lately and I just feel like it would be nice to make this process easier on ourselves...

**Comment by ewinslow** [comment]
Writing the update script and the new fresh schema for every update puts me off doing it... Would rather just write new, fresh schemas and have computers figure out how to get from a to b.

**Comment by Wouter0100** [comment]
And maybe introduce something like [phinx](https://phinx.org/)? This would simplify our lifes a lot, because working in a team with Elgg is currently a pain in the ass, mostly because of the DB (because we've composer for the dependencies :P). While working locally with multiple versions of databases and so on. Also deploying a new version of some plugins on a live server could be simplified with phinx.
