### ISSUE TITLE
Web services: allow multiple callbacks based on HTTP method

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7951]
I am working with an API that hits the same endpoint with different HTTP methods, and I wanted to use web services to work with the payload, but unfortunately, web services assumes one HTTP method for one exposed method.

**Comment by ewinslow** [comment]
+1

**Comment by hypeJunction** [comment]
Anyone willing to pick this up? Some initial work has been done in #7962

**Comment by mrclay** [comment]
We could revisit after move to own repo.
