### ISSUE TITLE
metadata not fetching correctly

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7953]
in Elgg 1.x i ran into the issue that i can save profile details but they won't show up on profile details.

There seems to be a bug in where `$user->metadataname` returning no value, but `elgg_get_metadata("entity_guid" => "user_guid", "name" => "metadataname")` (this is used by `profile/edit`).

Anybody with an idea what causes this? @mrclay maybe some new metadata caching?

**Comment by mrclay** [comment]
elgg_get_metadata() doesn't pull from that cache, but `->somename` does. When is the write done in relation to the read?

**Comment by mrclay** [comment]
Nevermind, I'm looking through actions/profile/edit.php now.

**Comment by mrclay** [comment]
Definitely a bug populating the cache.

**Comment by mrclay** [comment]
31058a094a50055898692f6930b47b18a4027b4f results in entity metadata to be loaded earlier, when the entities are first loaded, but this happens *before* login occurs, so the MD cache only gets public MD. I just need to reset the MD cache whenever the session user changes.

**Comment by mrclay** [comment]
This is the kind of thing we currently can't test :(

**Comment by jdalsem** [comment]
i did, but unfortunately not automated :)

**Comment by mrclay** [comment]
PR #7954

**Comment by jdalsem** [comment]
@mrclay did #7966 fix this issue?

**Comment by mrclay** [comment]
Yes
