### ISSUE TITLE
Add login as functionality to core

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7958]
Could simply adopt @brettp 's plugin for that https://github.com/brettp/Login-As

**Comment by mrclay** [comment]
@jdalsem :+1:

**Comment by ewinslow** [comment]
So I think if we do this we should just add brett's plugin to the composer "require" list and call it good. No need to pull the actual code into core IMO

**Comment by mrclay** [comment]
Can composer rename the folder "login_as"?

**Comment by ewinslow** [comment]
We just need to get @brettp to add a composer.json file that specifies the plugin name and composer will do the right thing, yea.

**Comment by ewinslow** [comment]
The magic JSON to trigger this is:

```json
{
  "name": "brettp/login_as",
  "extra": {
    "installer-name": "login_as"
  }
}
```

**Comment by ewinslow** [comment]
If we want to make it more "official" we can fork to the Elgg organization and release as "elgg/login_as"

**Comment by jdalsem** [comment]
don't forget to add it to the "bundled" plugin ids (category for plugins listing)

**Comment by Srokap** [comment]
Using extra `installer-name` is not necessary as the package "name" used during installation is the part after `/`. So if the name in composer.json is fine, you can name repository whatever you want and installer will not bother about that.

**Comment by juho-jaakkola** [comment]
I've merged the composer.json to the repo.

**Comment by ewinslow** [comment]
@jdalsem you can just merge up from 1.x to master to have github auto-close these tickets. That would be preferable since we don't want master to diverge too far from 1.x if we can avoid it for the sake of minimizing conflicts.

**Comment by jdalsem** [comment]
@ewinslow thanks, but i do not see the need of merging after each PR just for the sake of closing an issue. That is why i do it manual. Plus merging branches is more for the owners than for the contributors :)

**Comment by ewinslow** [comment]
Very well :)
