### ISSUE TITLE
'send','notification:$method' hook

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7959]
Looking closer at the hook and the callback, it seems the older notification handler approach made more sense. You had one handler for each method. Currently, the only way to alter the behaviour of ```_elgg_send_email_notification()``` for example is to unregister it, otherwise you end up sending the same notification multiple times.

html_email_handler does just that, so there is currently no way to tap in and prevent the emails from being sent to certain users (in core you can still rely on 'email','system').

Unless, I am missing something, there needs to be an extra step somewhere.

**Comment by hypeJunction** [comment]
I think we need a hook to filter notifications methods supported for each user.

**Comment by juho-jaakkola** [comment]
I'm not quite sure what your use case is. You want to prevent sending of emails to specific users?

**Comment by hypeJunction** [comment]
Yes, need to whitelist a couple of emails on a dev instance with the database from the production site.

**Comment by juho-jaakkola** [comment]
It seems ```notify_user()``` would need this hook: https://github.com/Elgg/Elgg/blob/1.10/engine/classes/Elgg/Notifications/NotificationsService.php#L197

But it's not smart to duplicate that stuff between synchronous and asynchronous notifications. We should rather unify them into a single system.

**Comment by hypeJunction** [comment]
Fixed in #10139
