### ISSUE TITLE
switch to a bareboned core css

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7970]
as concluded here https://github.com/Elgg/Elgg/issues/7328#issuecomment-74762904

minimize css as much as possible

**Comment by ewinslow** [comment]
What I had in mind was something like a greyscale theme. I don't know whether that would actually reduce the amount of CSS, but I would hope it would still be pretty/professional looking.

**Comment by ewinslow** [comment]
Either way, not a 2.0-blocker.

**Comment by jdalsem** [comment]
Not the way Elgg is going at this moment
