### ISSUE TITLE
Way to log client-side problems with appropriate visibility

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7982]
As we move a lot a logic client-side we need a system that can decide whether to elgg.register_error, console.log message, or route to some other system, maybe depending on user state/plugin settings.

See: https://github.com/Elgg/Elgg/pull/7979/files#r24994705

**Comment by jdalsem** [comment]
I do think there are a lot of services out there that will help you track your js issues. I don't think we should make one ourselves.
