### ISSUE TITLE
Add a test or establish a test procedure to verify that the upgrade from the previous Elgg version works without errors 

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7989]
The necessity of such a test shows for example in issue https://github.com/Elgg/Elgg/issues/6814.

If it doesn't get immediately noticed that the upgrade from the previous Elgg version (not only previous bugfix version but at least also previous minor version) fails to work it will result in major problems in the long run. It's even worse if it gets only noticed after end-of-life of the release that introduced the bug.

**Comment by jdalsem** [comment]
Added in #11113
