### ISSUE TITLE
ElggEntity::create() should throw exceptions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7997]
`ElggEntity::create()` returns `false` instead of throwing an exception on container permissions failure. Calling methods such as `ElggGroup::create()` do not expect a falsey return and cause WSOD.

**Comment by mrclay** [comment]
I suggest the calling code check if it can write to container first, and we just handle the false return.

**Comment by hypeJunction** [comment]
Not sure if that's BC. Classes extending type classes, might have implemented their ::create() methods relying on these checks done in ElggEntity

**Comment by mrclay** [comment]
But are they going to expect exceptions?

**Comment by hypeJunction** [comment]
Well, in this situation I was presented with an Exception that made no sense - it was related to malformated MySQL query (the guid was missing from the query). It would have been more helpful to get an Exception telling me that owner/container can't contain this entity. That would have been a signal to check container permissions. This way I was lost in classes extending classes trying to find where things were going wrong.

**Comment by mrclay** [comment]
I'm stepping back until I have a chance to really look at this code. I agree that a clearly written exception would help more than the status quo.

**Comment by hypeJunction** [comment]
Adding to `HTTP Responses` milestone - once we add HTTP Exceptions we can decide how to catch it.
