### ISSUE TITLE
Faulty permissions logic in ElggEntity::create()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7998]
```ElggEntity::create()``` checks if the owner can contain an entity of this type. This logic is imho faulty. I have a situation where users can own courses (a subtype of group), but they can not contain them (only other groups or sites can).

**Comment by hypeJunction** [comment]
This should perhaps be ```$owner->canEdit()```?
You can create an entity with an owner_guid of X if you can edit an entity with guid X

**Comment by beck24** [comment]
Yes, that sounds faulty as you may be creating an entity for another container - pretty much what all group content is.

**Comment by hypeJunction** [comment]
This is biting me again. I have custom container logic, where subtype A can only be contained by a group. Checking canWriteToContainer on a user entity fails  because my container hooks disallow it.

**Comment by hypeJunction** [comment]
As per #8291, this is won't fix.
