### ISSUE TITLE
Allow exceptions in actions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8000]
Perhaps we could considering wrapping `action()` with `try()` and catch exceptions. Users would get generic messages based on exception type, admins would get full exception messages. 

I realize that I spend too much time checking instances, canEdit(), canWriteToContainer() permissions and inventing smart error messages. Would be helpful to have an easy way out by throwing an exception from one of the classes.

**Comment by ewinslow** [comment]
+1

**Comment by mrclay** [comment]
I agree that there's too much boilerplate around validation, and the idea seems somewhat easy to implement. Only hesitation is that it feels like an abuse of exceptions (goto).

**Comment by Srokap** [comment]
Fine with me if we stick to specific type of exceptions to be caught and handled as generic messages. We should perhaps differentiate explicitly here between 400 errors and 500, when first ones are caused by bad input data and the latter are server side issues (DB unreachable etc.)

**Comment by hypeJunction** [comment]
@mrclay Classes already throw exceptions that unless are caught in the action result in inconveniences for admins and users, e.g. calling ```->save()``` with a container guid that the user has no write permissions to will result in an Exception (something about can't save base entity information). So, we keep repeat ```canEdit()``` and ```canWriteToContainer()``` calls in every action. These could easily be thrown as Exceptions from ```->save()``` with a generic message that include entity info or type/subtype info.

**Comment by jdalsem** [comment]
@hypeJunction was this fixed somewhere along the line?

**Comment by hypeJunction** [comment]
HttpException can be thrown and will result in error response out of action. I don't think we need anything else at the moment
