### ISSUE TITLE
Adding full CKEditor broke the toolbar icons

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8004]
For some reason 39b15fafaa9463d8f4e6eddd6a27b921435c18bb broke the CKEditor toolbar icons:

![ckeditor](https://cloud.githubusercontent.com/assets/883920/6388801/67356202-bda6-11e4-898e-a49f68992c35.png)

**Comment by jdalsem** [comment]
I had this just once.... after a refresh they were back...

**Comment by juho-jaakkola** [comment]
Not for me. It seems like there's some conflicting styles definitions.

**Comment by jdalsem** [comment]
tried to reproduce it, but can't

**Comment by juho-jaakkola** [comment]
Could someone else test this? I still haven't gotten it to work, but I guess it might be just my own environment.

**Comment by juho-jaakkola** [comment]
I can reproduce this on Chrome but not on Firefox.

**Comment by juho-jaakkola** [comment]
The selector ```.cke_button__link_icon``` has ```!important``` in the declaration which overrides the inline css.

**Comment by jdalsem** [comment]
tried it in Chrome, but still can't reproduce this problem. Shall we close this issue until we have multiple reports?

**Comment by juho-jaakkola** [comment]
This bug has been very weird. It has appeared and disappeared on more than one environment without any logical reason.

I'd prefer someone else still testing this.

**Comment by jdalsem** [comment]
> I'd prefer someone else still testing this.

me too :)

**Comment by juho-jaakkola** [comment]
Apparently this was just my environment since no one else has run into it.

**Comment by schmidtwastl** [comment]
For me, this happened on Firefox after community.elgg.org was upgraded to 1.11 today (does not happen on Chrome & IE)
Reloading Javascript fixed it for me.
