### ISSUE TITLE
Problem whit the instalation of elgg

### ISSUE THREAD

**Issue by Gemlios** [Elgg/Elgg#8006]
Hi. I have a problem whit the instalation of elgg.

The think is, when i install the product the admin panel and the activity folder are lost of my server.

What hapend.

I need be online to install the elgg or i can install offline

Sorry for the wrating, i speack and writ very bad de inglish.

please helpme

**Comment by juho-jaakkola** [comment]
Please use the Elgg community for support: https://community.elgg.org/

**Comment by Gemlios** [comment]
Tanks
