### ISSUE TITLE
Introduce elgg_development_mode

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8016]
elgg_maintenance_mode was a great addition, but I am missing a way to differentiate between development and production modes. 'debug' config doesn't really cut it.

I think we need a global flag that plugins could use to load appropriate settings, and do things differently when in development mode. This would also help with #7946, we could just only show deprecation warning when in development mode.

**Comment by iionly** [comment]
Is a development "mode" the right thing to add? In contrast to the maintenance mode you wouldn't want to use (or should not?) a development mode on a production site. But on a development site the development mode could simply be provided by the developer plugin (plugin is enabled = development mode active).

Any specific flags that control development settings could be set by plugin options within the developer plugin as for example enabling/disabling display of deprecation warnings instead of enabling all of these settings globally in a development mode. The point is that you don't necessarily want all possible development settings to be active at all times.

**Comment by Srokap** [comment]
I think the natural way would be to introduce flag in settings that would define something like:
- development
- staging
- production

flag that would affect default policy for error logging/display and possible development tools behavior.

**Comment by hypeJunction** [comment]
@iionly The point is to provide the plugins with a centralized point of reference, e.g. a payments plugin could use different API keys based on the global development mode flag. The core could hide all deprecation warning when in production mode, perhaps even disable caches.
As a developer I want to easily switch between production/development environments.
@Srokap +1 for adding staging.

**Comment by beck24** [comment]
+1 to the whole idea - it would make syncing production data back to dev a whole lot smoother.  Right now I have to have a checklist of things to change/update.  A global setting that plugins could respond to would be fantastic.

**Comment by hypeJunction** [comment]
I think I am going to invest some time into this. I am not sure if implementing full scale environments is going to provide much ROI. Perhaps a simple config option would suffice. 
Thoughts?

**Comment by twentyfiveautumn** [comment]
+1 I think this would be very helpful.

**Comment by mrclay** [comment]
Strawman: elgg_get_env() returns an environment object that can be used to return info about the environment and particularly make decisions about logging/showing deprecation notices and maybe other types of logging. The object must implement:

```php
interface EnvironmentInterface {
    function isProd(); // bool
    function getName(); // string
    function getData(); // array
    function handleDeprecationNotice(Notice $notice); // void
}
```
...where `Notice` encapsulates the current user, the notice string, version, and a couple methods show() and log(), with pre-wired dependencies. Implementor is then free to do as he/she wishes with any given notice.

By default Elgg would provide an `DefaultEnvironment` with current behavior (obeys settings), but devs could set one by setting `$CONFIG->environment_factory` to a callable that returns the environment.

We could roll this out sooner leaving out the deprecation handling.

**Comment by hypeJunction** [comment]
So, you are basically saying that silencing deprecation would have to be implemented in a plugin that creates a new environment?

**Comment by mrclay** [comment]
In settings.php:
```php
$CONFIG->environment_factory = function(Elgg\Application $app) {
    return new Elgg\Env\DevEnvironment;
};

// or for short

$CONFIG->environment_factory = "dev";
```

**Comment by mrclay** [comment]
Then this object would accessible via `elgg()->env`.

**Comment by hypeJunction** [comment]
I am not sure when I will have time for this. Now that the deprecation warnings are out of my face, this has been downgraded on my priority list.

**Comment by beck24** [comment]
I still think this is going to be super-useful even with deprecation warnings out of our faces.  Especially for us, IK.
Consider all the times we sync dev data from production.  We have to go through a ton of plugin settings to change API keys, username/passwords, notification settings, etc.  Having plugins hold both prod and dev settings then toggling a single switch would be so nice.

**Comment by mrclay** [comment]
PR #8302.

**Comment by mrclay** [comment]
Closing #8302 as it seemed to put too much into this. Is the end goal just an API that returns "prod" (default), "dev", "staging", or "ci"?

**Comment by jdalsem** [comment]
Closing as this is not getting the attention it needs
