### ISSUE TITLE
WSOD if entities not fetched in river/object/comment/create view

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8018]
Should check the 3 entities before using them. https://github.com/Elgg/Elgg/blob/1.10/views/default/river/object/comment/create.php#L13

**Comment by juho-jaakkola** [comment]
Any idea what causes them to be missing?

**Comment by mrclay** [comment]
This was reported on the community. Can only guess a post was deleted/made invisible but the river item of the comment remained. I vaguely remembered we added joins so this couldn't happen. User is on 1.9

**Comment by beck24** [comment]
The joins we added checked if the entities existed and were enabled, as disabling the entities could cause this.  The joins wouldn't have helped if the entity has an access level the user can't see.  I'm not sure how this could happen (in core), but it certainly is possible to end up with such a situation in a plugin.

**Comment by mrclay** [comment]
User comments on page; page reduces its visibility. Is the river item access_id updated for the comment?

**Comment by jdalsem** [comment]
The `river/object/comment/create` view currently has checks on all entities
