### ISSUE TITLE
Switch to SVG for default entity icons

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8019]
We are now at a point, where we only support browsers that have built-in SVG support. For the sake of responsive theming there are couple of things I would like to propose/implement:
1. Replace default icons (especially the file type icons) with single-size SVG
2. Enforce default icon sizes either via html img attributes, or CSS. If you look at #7920, you will see that I am trying to make icon views more consistent by passing them all through icon/default view

**Comment by ewinslow** [comment]
+1 to both of these.

One thing svg still doesn't work for cross-browser is the favicon, but that's the only thing I can think of. Everything else should be fair game.

**Comment by hypeJunction** [comment]
We already have SVG favicons with a fallback to PNG, so that's not an issue anymore.

**Comment by jdalsem** [comment]
with the plans of adding fontawesome to core (#7239), this issue becomes obsolete for the file type icons (as FA has file type icons). Only the default user icon could use a svg version, but we could choose to use FA user and group icon for that also...

**Comment by hypeJunction** [comment]
I am not sure I would want to use fa for file type icons. That defeats the
purpose of having icon URLs

**Comment by jdalsem** [comment]
you can still conditionally have icon urls. It is just elgg_view_entity_icon (sometimes fa-icon, sometimes thumbnail url...). Icons are icons...

**Comment by hypeJunction** [comment]
Not convinced. Let's here some other opinions.

**Comment by jdalsem** [comment]
What would be the difference between a svg-image url as the file icon or a font icon?

**Comment by hypeJunction** [comment]
Consistency

**Comment by beck24** [comment]
I would be fine with using FA for entity icons, it's just so convenient

**Comment by hypeJunction** [comment]
What happens when you don't want to use fa? Do you replace the icon view?
Fa icons are ugly when they are large. Anything over 30px looks flawed. I would be fine with fa if it's BC with 1.x and doesn't require extra steps to get rid of.

**Comment by beck24** [comment]
Fair enough, I've only used them large a couple of times and they looked fine to me, but I know you have more experience with the UI stuff than I do.  Is there a way we can facilitate both ways?

**Comment by hypeJunction** [comment]
Only display fa icon markup if URL is false?

**Comment by hypeJunction** [comment]
Here is some initial work toward this: https://github.com/hypeJunction/Elgg-ui_icons
 * All icons gets standard class selectors that abide by the global icon size config
 * This makes icons (svg or otherwise) stick to their expected dimensions
 * Outsources hover menu to default icon view, so that other entities can build their hover

**Comment by hypeJunction** [comment]
Latest addition to the family: https://github.com/hypeJunction/Elgg-ui_icons_files
![File Type Icons](https://camo.githubusercontent.com/8ff684a5dcbfafc9e210b2a4fa007c3bd646faaa/68747470733a2f2f7261772e6769746875622e636f6d2f687970654a756e6374696f6e2f456c67672d75695f69636f6e735f66696c65732f6d61737465722f73637265656e73686f74732f66696c6574797065732e706e67)

And here is the screenshots from the parent plugin: https://github.com/hypeJunction/Elgg-ui_icons
![User and Group Icons](https://camo.githubusercontent.com/3dbdcddd3460e0d6e981bf15dcc7ac15ab9b235c/68747470733a2f2f7261772e6769746875622e636f6d2f687970654a756e6374696f6e2f456c67672d75695f69636f6e732f6d61737465722f73637265656e73686f74732f73616e64626f782e706e67)

**Comment by hypeJunction** [comment]
With regards to CSS, I am using this currently:

```php
$sizes = elgg_get_icon_sizes('user');
foreach ($sizes as $name => $opts) {
	echo ".elgg-avatar-$name {\n";
		if ($opts['w']) {
			echo "max-width: {$opts['w']}px;\n";
		}
		if ($opts['h']) {
			echo "max-height: {$opts['h']}px;\n";
		}
	echo "}\n";
}

$sizes = elgg_get_icon_sizes('object', 'file');
foreach ($sizes as $name => $opts) {
	echo ".elgg-avatar-object-file.elgg-avatar-$name {\n";
		if ($opts['w']) {
			echo "max-width: {$opts['w']}px;\n";
		}
		if ($opts['h']) {
			echo "max-height: {$opts['h']}px;\n";
		}
	echo "}\n";
}
```

**Comment by hypeJunction** [comment]
Is everyone ok using FA glyphs in a transparent square frame? We can then set the background color closer to what we have now. And replacing colors in SVG is easy.

**Comment by jdalsem** [comment]
with this approach i can't change the background color of the icons with css anymore... am i right?

**Comment by mrclay** [comment]
Hmm, I'd think you could set background of the wrapper element. Anyway I like the direction.

**Comment by hypeJunction** [comment]
> with this approach i can't change the background color of the icons with css anymore... am i right?

Nothing changes in terms of transparent icons - if they are transparent, you can set a background. With core icons currently you can't, as the icons are not transparent.

What I am proposing is that we drop the background I have in favor of a 100% opaque (transparent) background. 

For the SVG to inherit parent background and glyph color, we would have to inline the svg within HTML, which makes it no different than using an actual FA glyph. I am against mixing markup with getIconURL() logic.

Here is actual SVG, which is super easy to read and modify the colors, so we could even keep them as is:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200" xml:space="preserve">
<g>
	<rect class="elgg-svg-avatar-background" style="fill:#7A8184;" width="200" height="200"/>
	<polyline class="elgg-svg-avatar-shade" style="opacity:0.2;fill:#BCBFC4;" points="200,0 200,200 0,200"/>
	<path class="elgg-svg-avatar-path" style="fill:#FFFFFF;" d="M111.4,128.1v18.7c0,0.8-0.3,1.6-1,2.2c-0.6,0.6-1.3,1-2.2,1H89.5c-0.8,0-1.6-0.3-2.2-1
		c-0.6-0.6-1-1.3-1-2.2v-18.7c0-0.8,0.3-1.6,1-2.2c0.6-0.6,1.3-1,2.2-1h18.7c0.8,0,1.6,0.3,2.2,1
		C111.1,126.6,111.4,127.3,111.4,128.1z M136.1,81.2c0,2.8-0.4,5.4-1.2,7.9c-0.8,2.4-1.7,4.4-2.8,6c-1,1.5-2.4,3.1-4.3,4.7
		c-1.8,1.6-3.4,2.7-4.5,3.4c-1.1,0.7-2.8,1.6-4.8,2.8c-2.2,1.2-3.9,2.9-5.4,5.1c-1.4,2.2-2.2,3.9-2.2,5.2c0,0.9-0.3,1.7-1,2.5
		c-0.6,0.8-1.3,1.2-2.2,1.2H89.2c-0.8,0-1.4-0.5-2-1.4c-0.6-1-0.8-1.9-0.8-2.9v-3.5c0-4.3,1.7-8.4,5.1-12.2
		c3.4-3.8,7.1-6.7,11.2-8.5c3.1-1.4,5.3-2.9,6.6-4.4s1.9-3.5,1.9-5.9c0-2.2-1.2-4.1-3.6-5.8c-2.4-1.7-5.2-2.5-8.4-2.5
		c-3.4,0-6.2,0.7-8.4,2.3c-1.8,1.3-4.6,4.3-8.4,9c-0.7,0.8-1.5,1.2-2.4,1.2c-0.6,0-1.3-0.2-1.9-0.6l-12.8-9.8
		c-0.7-0.5-1.1-1.2-1.2-1.9c-0.1-0.8,0-1.5,0.4-2.2C72.7,56.9,84.8,50,100.7,50c4.2,0,8.4,0.8,12.6,2.4c4.2,1.6,8,3.8,11.4,6.5
		c3.4,2.7,6.1,6,8.3,9.9C135.1,72.7,136.1,76.9,136.1,81.2z"/>
</g>
</svg>
```

**Comment by hypeJunction** [comment]
We could also just remove fallback icon URLs from all hooks and inline fallback icon views in the icon view. Advise dev to do the same.

**Comment by jdalsem** [comment]
downside of this approach would be that you have to modify some extra icons... but benefits win, so i am pro your suggestion

**Comment by hypeJunction** [comment]
That would only work with SVG icons obviously.

**Comment by jdalsem** [comment]
can we also switch to SVGs for the favicons??

**Comment by hypeJunction** [comment]
Support for SVG favicons is not great. http://caniuse.com/#feat=link-icon-svg
#8788

**Comment by jdalsem** [comment]
Not going to switch to SVG for the entity default icons. Icons have the ability to be generated for any size at this moment so if in a theme a better optimized size is requested, it is available.
