### ISSUE TITLE
Replace mbstring with grapheme_* from intl library

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8025]
So says slide 51 of this preso:

http://www.slideshare.net/g13n/internationalisation-primer-4932772?next_slideshow=1

**Comment by ewinslow** [comment]
Not happening for 2.x

**Comment by hypeJunction** [comment]
Is this still something we want or need?

**Comment by jdalsem** [comment]
i do not care for this at this moment. If someone needs this, feel free to provide a PR
