### ISSUE TITLE
Assertion failure testing fails on PHP 7.x

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8034]
It [looks like](https://travis-ci.org/Elgg/Elgg/jobs/53161295#L372) PHP7 changed the format of assertion failure exception messages from `assert(): Assertion failed` to the more helpful `assert(): assert(is_string($key) || is_int($key)) failed`. Unfortunately we rely on those:
https://github.com/Elgg/Elgg/blob/master/engine/tests/phpunit/Elgg/Cache/StashPoolTest.php#L50

**Comment by ewinslow** [comment]
That was silly to rely on the exact failure message, so this will be good to change...

**Comment by ewinslow** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/8047
