### ISSUE TITLE
phpcs failing on Travis

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8035]
https://travis-ci.org/Elgg/Elgg/jobs/53161296#L240

Although squizlabs/php_codesniffer [is being installed](https://travis-ci.org/Elgg/Elgg/jobs/53161296#L112), maybe `phpcs` is no longer placed in the path?

**Comment by ewinslow** [comment]
Hmmm... :( we could go complain to them about it? Breaking change in a minor release?

**Comment by ewinslow** [comment]
In the mean time we can require an old version that does have the binary on the path.

Or could this be a Travis issue where composer binaries are no longer available?

**Comment by Srokap** [comment]
I didn't follow that change, but I don't see why `vendor/bin/phpcs` was changed to global version when moved to composer.json lint script?

There's no reason for /vendor/bin to be added to $PATH automatically and it's better not to rely on that when we have it hidden behind grunt or composer.

**Comment by ewinslow** [comment]
According to
https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually
you should not need to add vendor/bin/.

**Comment by ewinslow** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/8047
