### ISSUE TITLE
canEdit() allows invalid $user_guid argument

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8038]
You can pass in GUIDs of non-users (e.g. 1), and it will function just fine, calling the plugin hook sending `user => (site object)`.

Also you can pass in a non-existent/deleted GUID and it will silently convert this to the session user.

In both cases I doubt we want to silently let this pass this through.

**Comment by jdalsem** [comment]
agree

**Comment by mrclay** [comment]
As @jdalsem mentioned, we may want to ignore access while calling get_user() to allow the case of "hidden" users. I've heard some systems have these. Then again, it might make a nasty BC break to change that behavior.

**Comment by mrclay** [comment]
Options: throw InvalidArgumentException? Just return false and log an error for nicer BC?

**Comment by ewinslow** [comment]
+1 for return false + log

**Comment by jdalsem** [comment]
Also consider this comment https://github.com/Elgg/Elgg/pull/8031/files#r28133396

**Comment by mrclay** [comment]
PR #8944
