### ISSUE TITLE
Metadata causes a lot of db writes

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8043]
Calling ```$entity->foo = 'bar'``` currently triggers this:
 1. [That particular metadata gets removed regardless if it has changed
at all](https://github.com/Elgg/Elgg/blob/1.10/engine/classes/ElggEntity.php#L401-L415)
 2. [The metadata gets written again to the database](https://github.com/Elgg/Elgg/blob/1.10/engine/classes/ElggEntity.php#L425-L430)

Is there a reason why we don't:
 1. Compare the value to existing db value and act only if it has changed
 2. Update the existing row instead of writing a new one

Something related to caches or ACLs perhaps?

**Comment by mrclay** [comment]
We let anyone blow away all existing values regardless of access_id on any write, which is a bit nutty. Theoretically re-setting a value could result in changing the access_id. I continue to think ditching access_id would be an improvement.

The way I see it writes are so infrequent that inefficiencies don't bother me too much.

See also #7765.

**Comment by jdalsem** [comment]
Mostly fixed by #8596. Updates now only happen if data changed. Changing from a DELETE/INSERT to UPDATE/INSERT is worth considering, but not a very big issue.. I suggest a close for now
