### ISSUE TITLE
Missing "view_vars" hook on 1.10.2 ?

### ISSUE THREAD

**Issue by byhoratiss** [Elgg/Elgg#8045]
I've just realized that the hook "view_vars" does not exist on 1.10.2 codebase, but it is on the [Docs](http://learn.elgg.org/en/latest/guides/hooks-list.html#views).

This is the ElggViewService from [master branch](https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/ViewsService.php#L244) and this is the one from [1.10.2 version](https://github.com/Elgg/Elgg/blob/1.10.2/engine/classes/Elgg/ViewsService.php#L222)

Sounds like a PR merge problem,

Any ideas?

**Comment by juho-jaakkola** [comment]
You're looking at the documentation for Elgg 1.11 which hasn't been released yet.

As you can see the hook doesn't exist in the Elgg 1.10 docs: http://learn.elgg.org/en/1.10/guides/hooks-list.html
