### ISSUE TITLE
Install.php FAIL

### ISSUE THREAD

**Issue by AndreCezimbra** [Elgg/Elgg#8052]
Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\elgg\engine\classes\Elgg\Di\ServiceProvider.php on line 194

Trying to install new release 1.10.3

**Comment by Srokap** [comment]
Elgg requires PHP version of 5.4 or higher which is described in requirements: http://learn.elgg.org/en/1.10/intro/install.html

Please don't post here support issues, but only core bugs. For the support ask your questions at https://community.elgg.org/
