### ISSUE TITLE
data_views should be bundled if web_services is bundled

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8053]
This just bit me. Bundling the web_services plugin for BC is less effective if the data_views plugin isn't also bundled. The only included views are JSON. Missing XML views breaks BC and also makes the docs worthless: http://learn.elgg.org/en/1.10/guides/web-services.html#response-formats

Refs #5034

**Comment by ewinslow** [comment]
mmm.... indeed. I'd be fine with adding them back with composer. Pretty
low-cost fix...

**Comment by brettp** [comment]
It looks like data_views doesn't actually work: https://community.elgg.org/discussion/view/2085687/data-views-plugin-serialise-object-to-xml-deprecation

**Comment by mrclay** [comment]
Strawman: copy the function into data_views as `data_views_object_to_xml()`. Allows us to keep the core one deprecated.

**Comment by mrclay** [comment]
Fixed by #9409
