### ISSUE TITLE
Support SMS

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8063]
If it hasn't happened already it will soon -- more people have smartphones than email addresses. Sending messages to a phone number will be the most reliable way to communicate with someone. We should support this out of the box!

**Comment by hypeJunction** [comment]
You mean to say that we should have basic API for that? I don't think sending actual SMS is possible without a vendor, which in most cases will cost site owners $$$.

**Comment by juho-jaakkola** [comment]
I was today in a meeting where I was asked to make a quote about adding the possibility (API) to register using a phone number instead of an email. They said it would be OK for them to wait for it to get added into Elgg core!

**Comment by ewinslow** [comment]
There are email gateways you can use to send outgoing messages for free.

**Comment by ewinslow** [comment]
The catch is that you generally have to know the carrier, so it's a little extra data entry which is a slight bummer

**Comment by brettp** [comment]
FWIW, this was an option waaaay back in Elgg 1.5...

On Fri, Mar 13, 2015 at 8:53 AM, Evan Winslow <notifications@github.com>
wrote:

> The catch is that you generally have to know the carrier, so it's a little
> extra data entry which is a slight bummer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8063#issuecomment-78958106>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by ewinslow** [comment]
!!

**Comment by ewinslow** [comment]
If your client is going to wait for it to be supported in core, they might be waiting a while
