### ISSUE TITLE
Needed: Method for background scripting of events

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#8066]
Sometimes user-triggered-actions can take a while, but there's no sense having a white page churning delaying the next page load while this is happening, that's bad UX.
In 1.8 I've been using vroom https://community.elgg.org/plugins/1222696 and deferring such functions to shutdown.  It's worked well for me, but we should have some way of facilitating this in core so everyone can handle such performance issues in a standardized way.

The events queue in cron is good for things like notifications, but is likely not timely enough for things that need to happen right away (things that impact user access/relationships).

See previous discussion: https://github.com/Elgg/Elgg/pull/8061#issuecomment-79641897

**Comment by beck24** [comment]
Some way of chunking/multi-threading it would be awesome.  If I have to loop through 800 users and do something it would be nice to have 4 threads looping through 200 users each or something.  Makes it much faster (to the limits of I/O anyway).

**Comment by ewinslow** [comment]
I believe the db queue is meant to be real time. We could look at what we
need to do to enhance that.

**Comment by jdalsem** [comment]
i think for now the database queue will suffice... a custom dequeuer will probably (same as the notifications) check every minute, so that would be 'instant' enough...
