### ISSUE TITLE
Elgg rewrite test fails 

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#8067]
https://github.com/Elgg/Elgg/blob/1.9/install/ElggRewriteTester.php#L92 

first tests on allow_url_open with file_get_contents() and then curl. Better results are given when curl is tested first (see my experience https://community.elgg.org/discussion/view/2064241/upgrading-a-https-site-to-19. 

I propose to reverse the test order, like this:

if (function_exists('curl_init')) {
    // try curl if installed
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 5);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $response = curl_exec($ch);
    curl_close($ch);
} elseif (ini_get('allow_url_fopen')) {
    $ctx = stream_context_create(array(
    'http' => array(
    'follow_location' => 0,
    'timeout' => 5,
    ),
    ));
    $response = file_get_contents($url, null, $ctx);
}

**Comment by mrclay** [comment]
Instead of either or we should try both.

**Comment by gerard-kanters** [comment]
Yes both would be better.  It crossed my mind that it probably would be better to "ini_set('allow_url_fopen')" instead of get, but only in the either case. In both case, try both (true and false) :-)

That way http based servers more likely pass the test no matter how the setting is. For https based servers, it is more clear how to change behavior in case of failure.

If one gets beyond the upgrade script, it is more likely one will go on and helps improving the plugins and solve deprecation notices and a lot of awful things still happening when upgrading to 1.9. A user push is sometimes all developers need to get on fixing their code.

**Comment by sathish4fri** [comment]
This issue occurs in wamp server when i am installing it new  with 1.10.5 and latest . @gerard-kanters 
solutions is working perfectly .

**Comment by jdalsem** [comment]
This has been fixed in https://github.com/Elgg/Elgg/pull/8268
