### ISSUE TITLE
JS for showing inline comment editing checks for a data element instead of visibility

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8068]
https://github.com/Elgg/Elgg/blob/master/js/lib/comments.js#L86

This is problematic if the form is exposed or hidden by other means. Is there a reason for using a data attribute instead of checking :visible or :hidden, or even re-using the hidden class?

**Comment by mrclay** [comment]
@juho-jaakkola may have some idea why that was done.

**Comment by juho-jaakkola** [comment]
@mrclay that particular line of code was in fact added by you. :)
