### ISSUE TITLE
elgg 1.10.3 - login deprecated in 1.9

### ISSUE THREAD

**Issue by xavgra2** [Elgg/Elgg#8070]
Hi, 
I just upgrade my production instance to 1.10.3, and I have this error once I login :+1: "Deprecated in 1.9: the login event was deprecated. Register for login:before or login:after.
Is there a way to correct this ?

**Comment by ewinslow** [comment]
Hey! Thanks for upgrading! Hope you like the improvements.

We use GitHub for bugs in Elgg, but not support for managing an Elgg site. Please direct support request to community.elgg.org. Lots of information available there.

**Comment by xavgra2** [comment]
I totally understand, but for me it's a bug.
I don't use an external plugin to login, and I have this error message each time a user is login in.
Is there a log file or something else to find which plugin use this deprecated feature ?

**Comment by ewinslow** [comment]
Please ask on the community site.
