### ISSUE TITLE
Stop committing changelog to repo

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8072]
It probably makes sense to commit as part of the tag comments, but even then, probably not. It creates a duplicate source of truth (commit history vs changelog). We need to present that view of the changelog somewhere, but in the repository itself seems suboptimal.

This is just one step in my ultimate plan to make releasing as easy as creating the git tag and pushing it to github. For elgg core, releasing isn't currently too bad since we have our script that does what we need, but I am thinking here too about other projects that we have or might want to manage (i.e. pulling out code from core into more modular libraries or plugins. Really I don't want to have to run scripts before/during tagging in order to make the release happen. Any build scripts should be reactive in that they run automatically when releases are tagged (and can be re-run without extra side-effects if they are ever found to have bugs or something).

**Comment by jdalsem** [comment]
changelog is no a part of the code anymore... we do have CHANGES.txt but that is more a release notes file and that is something we still want.
