### ISSUE TITLE
Scrutinizer getting code coverage from Travis is unreliable

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8074]
In order for Scrutinizer to succeed, Travis needs to be run simultanously.

 - If you run Scrutinizer without running Travis, it waits 20 minutes without receiving anything
 - If you run Travis without running Scutinizer, Travis sends the data but there's no process at Scrutinizer's end, so the data never gets processed

I don't know if there's anything we can do at the moment, but I'm documenting this in case we need to take an action later.

Scrutinizer team is currently wondering whether they should e.g. allow fetching the data through Travis' API instead of just waiting for it to be sent: https://github.com/scrutinizer-ci/scrutinizer/issues/109

**Comment by juho-jaakkola** [comment]
Well I suppose what we could do already is to extend the timeout to hours instead of minutes?

**Comment by jdalsem** [comment]
i believe this is currently much more reliable... or at least we have less issues. closing this for now
