### ISSUE TITLE
Release 1.7.23?

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8075]
@iionly is advocating a 1.7.23 release to fix #6814

What should we do? Make people download from github or do an official release?

**Comment by brettp** [comment]
I thought we had already decided not to make the release and just have clear instructions. If it's still up for debate, no, I don't think we need to make a new 1.7 release.

**Comment by beck24** [comment]
I don't really care either way

**Comment by mrclay** [comment]
Doesn't seem worth our time.

**Comment by iionly** [comment]
I thought the course of action that had been decided on for https://github.com/Elgg/Elgg/issues/6814 was to make a new 1.7 release for which I had provided https://github.com/Elgg/Elgg/pull/8027 to the 1.7 branch.

The instructions (to be added to the docs) would be an additional task (as the docs of Elgg 1.8 and/or 1.9+ would be affected). But without a 1.7.23 release being available it would be quite pointless to add instructions to the docs to upgrade to 1.7.23 before upgrading from 1.7 to 1.8.

I have to say that I'm slightly irritated that it seems too much to provide any solution (even if just a makeshift by a new 1.7 release) to the fact that the upgrade path from 1.7 to 1.8 is completely broken.

**Comment by ewinslow** [comment]
I agree that making an official release is not worth our time.

Here is the solution for those upgrading from 1.7: download the latest code straight from the 1.7 branch on github, upgrade, then do the upgrade to 1.8.

@iionly, if you have anything to add, please do. We want to make it possible to upgrade (and we have), but I don't think we care to do an official release.

**Comment by juho-jaakkola** [comment]
I can take care of releasing it. (At least uploading a zip)

**Comment by juho-jaakkola** [comment]
I've added:
 - tag
 - changes
 - zip packages

@iionly can you verify that the zip package is working as intended?

**Comment by iionly** [comment]
@juho-jaakkola thanks! I've tested it and upgrading works flawless. I've noticed that the ChangeLog file (only included in the zip on the community site) seems to have lost quite a number of entries. But this doesn't affect functionality.
