### ISSUE TITLE
Allow class name as event/hook handler

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8077]
Idea by @ewinslow:

``` php
namespace MyPlugin\Events;
class UserLogin {
  const KLASS = __CLASS__;
  public function __invoke($e, $t, \ElggUser $user) {
    // logic
  }
}

elgg_register_event_handler('login', 'user', UserLogin::KLASS, 100);

elgg_unregister_event_handler('login', 'user', UserLogin::KLASS);

// PHP 5.5+
elgg_register_event_handler('login', 'user', UserLogin::class, 100);
```

Internally the handler would just be the string `MyPlugin\Events\UserLogin`, which could be a function name, so we would need to first check function_exists(). If that fails we ask the DI system for an object of that type.

**Comment by mrclay** [comment]
We could add a simple way to register factories for class names on our existing autoloader:

```php
elgg_register_factory(UserLogin::KLASS, function () {
    // return new object
});
```

This gets stored under the key `class:MyPlugin\Events\UserLogin` on our service provider.

**Comment by juho-jaakkola** [comment]
I wonder how costly it is to get the name from the Class constant. AFAIK PHP needs to create a new stdClass instance when a class constant gets called.

All of the plugins do their ```elgg_register_*_handler()``` calls on every page load and there may easily be hundreds of handlers on a complex site.

I've been wondering whether we should be caching handlers like Drupal does. E.g. register them when plugin gets activated instead of registering them on every page load. (This might be micro optimization, though.)

**Comment by juho-jaakkola** [comment]
Off-topic-ish brain dump: how about allowing a service as event/hook handler?

Maybe something like:
```php
elgg_register_event_handler('login', 'user', array(
    'service' => array('userlogin', 'doStuffOnLogin')
);
```
In this case events service would call:
```php
_elgg_services()->userlogin->doStuffOnlogin();
```

**Comment by mrclay** [comment]
@juho-jaakkola See #6795. You're correct that referencing the KLASS constant would necessarily autoload the class, that's unfortunate. So before PHP5.5 it would have to be raw strings.

**Comment by ewinslow** [comment]
Yea, the `KLASS` thing is a bit of a kludge. Can't wait till we require PHP 5.5!

**Comment by ewinslow** [comment]
It is clever, though, I grant you that. And I may actually prefer it to using strings while we're on 5.4...

**Comment by mrclay** [comment]
Early PR: #8083

**Comment by juho-jaakkola** [comment]
Where does the name "KLASS" come from? Does it actually mean something?

**Comment by mrclay** [comment]
@juho-jaakkola it's a plain class const which has to be explicitly added to the class. PHP5.5 adds official `::class` syntax.

**Comment by juho-jaakkola** [comment]
Yes, but I mean did you invent the name yourself? Or is "KLASS" a universally used way of referring to the class name? i.e. used also in other PHP frameworks?

**Comment by mrclay** [comment]
I've never seen it before.

**Comment by brettp** [comment]
I assumed it was derived from [klassy](http://www.urbandictionary.com/define.php?term=Klassy)...

**Comment by ewinslow** [comment]
We just can't use CLASS because that will cause things to break in 5.5

**Comment by jdalsem** [comment]
Is this discussion still relevant? We have PHP 5.5 in master...

**Comment by mrclay** [comment]
Latest PR: https://github.com/Elgg/Elgg/pull/8399

**Comment by jdalsem** [comment]
@mrclay do we still want something with this or is https://github.com/Elgg/Elgg/pull/10009 enough?
