### ISSUE TITLE
Dissuade devs from using dynamic event/hook handlers

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8079]
Giving an anonymous function, a dynamic method callback, or an invokable object as an event/hook handler would result in a notice, to encourage devs to use handlers that can be removed by other plugins.

This is an alternative to #8078 and #7750

**Comment by jdalsem** [comment]
We are using this kind of functionality in core so much i don't think we should prevent the usage. We mentioned the downside of this kind of callbacks in the docs (http://learn.elgg.org/en/2.3/design/events.html#unregister-event-hook-handlers) so that is enough for now i think
