### ISSUE TITLE
Serialize non-scalar plugin settings values by default

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8081]
I often rely on non-scalar values as plugin settings, and every time it's a bunch of boilerplate with hijacking the action to serialize the values before saving, and to unserialize them afterwards. 
Thoughts on whether the core could support at least serialization on save? I suppose unserialization is more complicated due to getter logic.

**Comment by mrclay** [comment]
I'd like to know if lots of other devs are storing serializations...

**Comment by ewinslow** [comment]
Can you list some example cases where this is needed?

**Comment by beck24** [comment]
I know I have done it in the past, I can't think of what it was for right now.  In general I try to avoid it when possible just because I hate the boilerplate that goes along with it, but having a default behavior of to handle arrays as plugin settings would be nice.  If someone needs to do something different they still have the option of the hijacking the action.

**Comment by hypeJunction** [comment]
I tend to group settings into array, because a) it's easier to manage in a form, b) retreiving plugin settings is currently a costly operation (I know Steve has done some perf optimizations there), c) it's hard to reconstruct multi-level config arrays/objects from key/value pairs, d) there is not other storage mechanism in the API that would support arrays/objects. 
For example, I am now working on the timezone support for events, and I want to expose a setting to allow admins pick which timezones should be supported in input views. So, it's an array of timezones. There is no way to simply convert checked values to whatever serialized input, everything requires either hijacking the action, or hook into action and replacing request values etc.

**Comment by twentyfiveautumn** [comment]
I occasionally store serializations as well

**Comment by mrclay** [comment]
In general I'm really uneasy in allowing end users to save any shape of data structure they want and just storing it as is and encouraging devs to unserialize these values. If we're not careful we'll provide a classic attack vector where the user provides his own pre-serialized string value, which could contain objects.

**Comment by mrclay** [comment]
I'm for reducing boilerplate but not letting devs off the hook for proper input validation.
