### ISSUE TITLE
Decide namespacing standard for plugins

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8087]
@ewinslow's suggestion: `Vendor\Plugin\Class` e.g. `Elgg\Htmlawed\ValidateInputHook`

I think this would be better for that use case: `Elgg\Htmlawed\Hooks\ValidateInput`

Some plugins might even use `Elgg\SomePlugin\Hooks\Menus\EntityRegister`, which would obviously (?) be called by the `'register', 'menu:entity'` hook.

**Comment by ewinslow** [comment]
SGTM

**Comment by juho-jaakkola** [comment]
I guess we'll need a similar example as the plugin skeleton: http://learn.elgg.org/en/latest/guides/plugins/plugin-skeleton.html

It would include all of the basic needs for a plugin.

**Comment by jdalsem** [comment]
We are not going to describe any specific structure plugin devs should use. They should use what works best for their plugins.
