### ISSUE TITLE
ElggBatch with count or calculation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8095]
It seems that whenever ElggBatch, we have to implement special logic to see if count or any of the calculation params are present in the options array, and use ege\* insead of batch. 
Would it make sense for the ElggBatch to check for these and terminate after first iteration?

**Comment by jdalsem** [comment]
Why would you use an ElggBatch _**with**_ a count?

**Comment by hypeJunction** [comment]
https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/BatchResult.php

**Comment by jdalsem** [comment]
still don't see why you would need to... feels like using a hammer to screw

**Comment by hypeJunction** [comment]
The point is that `ElggBatch` doesn't check if `count` is present in the options array before passing it on to the getter. So there is a wasted ege call that produces a result that doesn't get output.

```php
$groups = new ElggBatch('elgg_get_entities', [
	'count' => true,
	'types' => 'group',
]);

foreach ($groups as $group) {
	echo 'something'; // nothing is printed
}
```

**Comment by jdalsem** [comment]
Yeah, but you can do multiple things... 

ignore count and return as if count was false (returning entities)
throwing an exception reporting an invalid parameter for ElggBatch
return a count???

The question is what do you expect it to do...

**Comment by hypeJunction** [comment]
I don't care. Just logged an issue when bumped into this.

**Comment by jdalsem** [comment]
Ok, so we need some opinions on what people expect when passing count to ElggBatch...
i expect it gets ignored (without a warning), as we want entities and not a count when using ElggBatch

**Comment by hypeJunction** [comment]
Let's just strip any options that lead to math calculations from options and log error if present.

**Comment by jdalsem** [comment]
fine by me... i think error is maybe too aggressive

**Comment by mrclay** [comment]
I'd prefer to log error and leave current behavior. What's the risk there?
