### ISSUE TITLE
Cookie-based language detection

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8097]
Even assuming we implement user-agent language detection eventually (i.e. #2047) I think this would still be valuable. User's browser may be misconfigured and it would be much easier to offer a ui-widget to change a cookie than to offer support on how to change preferred language in your browser.

**Comment by ewinslow** [comment]
Inspired by #4400

**Comment by jdalsem** [comment]
This plugin https://github.com/ColdTrick/language_selector already has the cookie behaviour and the language selection (with a list of flags in the header) We can reuse some of the experience we have with this plugin.

**Comment by ewinslow** [comment]
Any screenshots or demos for that plugin?

**Comment by ewinslow** [comment]
Not a 2.0 blocker. Still think it's valuable.

**Comment by jdalsem** [comment]
Going to links like: `your-elgg-site.com/blog?hl=nl` will set the requested language as a cookie. That cookie will be used as a preferred language. So cookie based language selection is implemented. A feature to switch the language (somewhere in the interface) can be implemented easily by themes or plugins. Not going to add this in core
