### ISSUE TITLE
Race condition when deleting users

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#8099]
This has happened a couple of times on the community site, and I wasn't completely sure this was the reason, but it happened tonight as I deleted as spammer and confirmed my suspicions.

The user delete action is initiated - this triggers the 'delete', 'user' event
That event clears so the system prepares to delete the user - it recursively deletes all content owned or contained by the user.
After this the user entity is finally deleted.

If the user is active at the time of deletion and posting content, new content can be posted between the time of the recursive delete and the user entity being deleted.  This leaves an orphaned entity in the database and leads to WSOD wherever it's displayed.

**Comment by beck24** [comment]
This may also happen if a process disables a user, it may leave content enabled for a disabled user on race conditions

**Comment by mrclay** [comment]
In the case of delete, one option would be to, post-delete, have a few cleanup queries to delete any content owned/contained by the user. Like the DB cleaner but focused on that entity. Another would be to add a "being_deleted" column in entities that gets set to 1 early in the delete. The methods that save entities/metadata/et al would first check that none of the related entities are being deleted.

Both these create their own problems.

**Comment by brettp** [comment]
Another option - Kill the user's session before starting the delete / ban.

**Comment by mrclay** [comment]
Yeah, deleting session(s) should be step 1 and could go in 1.10 IMO

**Comment by mrclay** [comment]
Other users or the system could still generate content related to the user

**Comment by mrclay** [comment]
We need to add a user_guid column to the sessions table. There's no practical way to log out user 123 without risk of logging out other users who happen to have an array with `s:4:"guid";i:123;` in their session data. We'd have to capture all matching sessions and unserialize the data to be sure, and PHP doesn't offer a usable unserialize for session data.

**Comment by mrclay** [comment]
PR #9633 (just ban the user during the duration of delete/disable)
