### ISSUE TITLE
Site went blank after update

### ISSUE THREAD

**Issue by BigMoses777** [Elgg/Elgg#8101]
Hello, I am new to all of this. I installed elgg last week and all was well. I updated it this morning and it has now disappeared and I have no idea what to do. My admin link and link from my website do the same. In chrome they produce a blank page, in IE it comes up with a "cannot display the page" error. Would love any help or advice. Thanks

**Comment by brettp** [comment]
Hi. Please check the [troubleshooting docs](http://learn.elgg.org/en/1.10/appendix/faqs.html) for some ideas, and use the community site for support: https://community.elgg.org/ If this is a core bug, feel free to reopen this ticket with more info. Thanks.
