### ISSUE TITLE
ElggMenuBuilder::compareByText should strip HTML before comparison

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8102]
Menu items accept HTML as 'text' parameter, and given tags are not identical across multiple menu items (e.g. a different class), sorting menu by text produces random sorting order.

**Comment by mrclay** [comment]
Agreed

**Comment by hypeJunction** [comment]
@jeabakker are you making a pull request?

**Comment by jeabakker** [comment]
sorry forgot ;)

**Comment by jeabakker** [comment]
fixed in #8149
