### ISSUE TITLE
In views, check returned objects before use

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8103]
See https://github.com/Elgg/Elgg/issues/7984#issuecomment-81638075

I at least know there are cases of this in the river views.

**Comment by beck24** [comment]
I grepped for ->getContainerEntity() and looked to see where a missing result might cause problems: https://github.com/beck24/Elgg/tree/7984-view-wsod

Didn't want to create a PR yet as the same should be done for getOwnerEntity as well as the river methods

**Comment by mrclay** [comment]
@beck24 does this still exist anywhere?

**Comment by beck24** [comment]
hmm, I thought I had fixed this.  Apparently not.

https://elgg.org/discussion/view/2506463/fatal-error-when-searching-in-elggorg#elgg-object-2506487

**Comment by jdalsem** [comment]
The specific situation mentioned by @beck24 is no longer present. If there are more issues like this please provide a PR. Developers should assume that there is the possibility provided data is unavailable and should check for it. This does not only apply to views but also in functions. No generic way to prevent this.
