### ISSUE TITLE
Remember me fatal error

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8104]
Just tried logging into the community site clicking "Remember me" and got this error:

Duplicate entry 'XXX' for key 'PRIMARY'

QUERY: 
INSERT INTO elggusers_remember_me_cookies (code, guid, timestamp)
VALUES ('XXX', 11814, 1427204361)

**Comment by mrclay** [comment]
So you already had a matching cookie yet it didn't log you in...or it tried the insert twice for some reason.

**Comment by mrclay** [comment]
In any case we probably want try/catch around any inserts on tables with constraints.

**Comment by mrclay** [comment]
can you find/recover the existing row? The timestamp would help

**Comment by brettp** [comment]
It's an empty set. I was logging in from a second browser, if that would make a difference.

**Comment by brettp** [comment]
This happened again. The error ts is 1427390200, the existing row's ts is: 1425122849.

**Comment by mrclay** [comment]
Is it possible in both cases that the browser you were using to log in already had an old elggperm (remember me) cookie? Or were these definitely new sessions/incognito? It may be too hard to debug the root cause of this; if I can't find it easily I may just throw in a delete for existing code.

**Comment by brettp** [comment]
These were on different computers completely, but I had logged into
Community before on both, so a cookie might have been set. On the one that
threw the error, it looked like my session had timed out, because I didn't
manually log out.

On Fri, Mar 27, 2015 at 2:07 PM, Steve Clay <notifications@github.com>
wrote:

> Is it possible in both cases that the browser you were using to log in
> already had an old elggperm (remember me) cookie? Or were these definitely
> new sessions/incognito? It may be too hard to debug the root cause of this;
> if I can't find it easily I may just throw in a delete for existing code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8104#issuecomment-87036431>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by mrclay** [comment]
Simplest fix I can think of #8303

**Comment by mrclay** [comment]
I now notice the better fix would be to get rid of the unnecessary unique key on the column `users_remember_me_cookies.timestamp`.
