### ISSUE TITLE
Add an official events plugin

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8106]
I'm assuming we'd do this via composer, but this would be really awesome to have events supported "out of the box"

**Comment by ewinslow** [comment]
Prior discussion: https://community.elgg.org/discussion/view/2068014/should-we-add-an-events-directory-to-the-community-site

**Comment by ewinslow** [comment]
@jdalsem @jeabakker we tried to hail you on the community but no response so I'm trying again here where mentions actually do something.

**Comment by ewinslow** [comment]
Also adding @hypeJunction @beck24 who participated in the previous discussion

**Comment by ewinslow** [comment]
This would be great to get resolved during the hackathon

**Comment by hypeJunction** [comment]
We have since implemented timezone support, reminder notifications, and better iCal feeds. Working on some UI elements now.
If we can identify the needs first, I am sure, we could add the missing parts.

https://github.com/arckinteractive/events_api
https://github.com/arckinteractive/events_ui

**Comment by iionly** [comment]
Isn't there a significant difference between installing an events plugin on the community site and addition of an events plugin as core plugin?

Supporting events management on the community site might be a useful feature (though only future will tell if there are really that many events to manage). But I'm not sure if an events plugin would be the first plugin that comes to my mind when thinking about what plugins to add to core additionally. But maybe the majority of Elgg users has other priorities that I'm not aware of.

**Comment by hypeJunction** [comment]
I must agree with @iionly. I was a bit confused here. The needs for events
are so different across sites.
Perhaps better Notable API (or an interface for working with date/time
values) in core as well timezone normalization would be a good start.

**Comment by twentyfiveautumn** [comment]
I would be in favor of having events as a core plugin.

**Comment by beck24** [comment]
I agree with @hypeJunction - probably because we've gone through the same experiences.  Events seems to be one of the more heavily customized features in the majority of our sites.  That's why we built the new plugin the way we did - splitting the API from the UI as best we could.  Ultimately it points to a requirement for better date handling in core.  I'm not opposed to adding an event plugin though, people who don't want it simply don't enable it, and it is a base expected functionality in a social system.

**Comment by ewinslow** [comment]
Base expected functionality of a social system was my motivation as well.

It's a pretty common and basic content type that we don't support.

**Comment by jdalsem** [comment]
With the current focus of ColdTrick's Event Manager on organizing events, i do not see the need to add it as a core module. I do see the need for adding good basic agenda features to core and maybe we will change Event Manager to extend those agenda features with Event capabilities... that would make more sense.

**Comment by ewinslow** [comment]
@jdalsem OK, sounds good Jeroen thanks for you input.

**Comment by ewinslow** [comment]
So... what now?

* Add events_api and events_ui via composer
* Add only events_api via composer
* Merge events_api and events_ui code into existing elgg/events plugin and include that via composer
* Something else?

@brettp @mrclay @Srokap thoughts on this?

**Comment by ewinslow** [comment]
Actually just @Elgg/team-elgg and @Elgg/contributors -- events would be a huge thing to take on. Do we see enough value in officially blessing one plugin/data model that others can build on, or do we prefer to leave the community to pursue their own events options for now? Perhaps it'd be best to give arck's plugin more time to bake?

**Comment by hypeJunction** [comment]
Baking would go much faster if we had some yeast, that is bug reports,
contributions, ideas. At this point the plugins are indeed somewhat raw.
Above all we need to port them to 1.9+, as we are building for 1.8 due to
client requirements.
I am torn to be honest. On one hand, I would love to see our work get
attention from the core team and the community, on the other hand there is
more room for improvement and real-life testing and case studies.

**Comment by ewinslow** [comment]
Sounds like a good reason to try it out on the community site first before blessing it officially

**Comment by rhisss** [comment]
All scripts/software similar to Elgg  (except Buddypress and Elgg) support Event-out-of-the-box. Many users who need Event out of the box will be pursuing other scripts straightway and so one may not hear their "demand"in the script community not having such Event plugin. Event essentially comes with an Attending "Yes | No | Maybe" and a location map. Recurring events, sessions, calendar, geeky and other detailed stuffs are not what all people are looking for always. But basic Events - Location, Attendee, and tagging friends (with so and so friends) are what is being used most.

Out-of-the-box - means plugin developed by core team or by some other but bundled with the core download.

The most important aspect ( and the most important one neglected by Elgg and Buddypress) is integration of the Events form with the status box (just as Hypewall integrates file, link etc) - it makes it intuitive, one-place, and easy to add the Event. This is the future - whether Elgg adopts such form now or will keep on delaying as  future milestone or will never will be one of the important  factors of rise (or fall) of the  Elgg. IMHO. Please have a look how "they" deal with Events
http://demo.jomsocial.com/index.php
http://easysocial.stackideas.com/profile
Thanks.

**Comment by iionly** [comment]
Whatever is decided on in case any event functionality is added to the Elgg core package please make it a plugin-only addition. There are already several full-working event management alternatives available and it would be kind of annoying if you wouldn't be able to continue to use any of them (especially if they fit your needs better) just because there's a event support added to core.

**Comment by twentyfiveautumn** [comment]
It seems the logical route for any plugin to make it into core would be to 
* release it to the community
* do a PR
* core developers decide

at the end of the day we can all use whatever plugins we want.

**Comment by twentyfiveautumn** [comment]
While we're right here I may as well throw my hat in the ring:
[Bootstrap Supercharged Files](https://community.elgg.org/plugins/2043782)
It seems like the ability for the file plugin to play audio and video is a core function.

**Comment by ewinslow** [comment]
Seems like this is taken care of best by a third-party. Closing.
