### ISSUE TITLE
Add Widget Manager plugin in addtion (or instead) of custom_index plugin to Elgg core

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8107]
The custom_index aka Frontpage plugin provides only a very simple index page without any way of configuring the index page on-site (which might be already a too complex problem to solve for non-devs who want to customize the index page on their site).

The Widget Manager plugin is a very mature plugin by now and not only provides an easy way to customize the index page by drag+drop but in addition offers the same feature also for group profile pages. It also comes with some nice additional widgets and allows for customizing profile pages and dashboard pages in the same way (UI-wise) as the index page / group pages.

Widget Manager support for core plugins could be added to the Widget Manager plugin itself if it's added as a core widget (so it would no longer be necessary to rely on additional plugins to have index page widgets for core plugins). Also, if the Widget Manager plugin would be a core plugin the number of 3rd party plugins providing suitable widgets might increase which would help site admins to configure their sites even more.

**Comment by brettp** [comment]
I'm good with pulling out custom_index. I think it serves mostly as an
example plugin, or as a temptation to edit it in place.

Pulling in Widget Manager means we'd be taking over dev. I'm not convinced
that's good idea. Also, how popular are the widgets? 2 of the 3 projects
I'm on using Elgg have removed all widgets completely. (The 3rd project
doesn't involve modifications to the UI.)

On Tue, Mar 24, 2015 at 3:10 PM, iionly <notifications@github.com> wrote:

> The custom_index aka Frontpage plugin provides only a very simple index
> page without any way of configuring the index page on-site (which might be
> already a too complex problem to solve for non-devs who want to customize
> the index page on their site).
>
> The Widget Manager plugin is a very mature plugin by now and not only
> provides an easy way to customize the index page by drag+drop but in
> addition offers the same feature also for group profile pages. It also
> comes with some nice additional widgets and allows for customizing profile
> pages and dashboard pages in the same way (UI-wise) as the index page /
> group pages.
>
> Widget Manager support for core plugins could be added to the Widget
> Manager plugin itself if it's added as a core widget (so it would no longer
> be necessary to rely on additional plugins to have index page widgets for
> core plugins). Also, if the Widget Manager plugin would be a core plugin
> the number of 3rd party plugins providing suitable widgets might increase
> which would help site admins to configure their sites even more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8107>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by beck24** [comment]
+1 for moving custom_index out, if it's not already it can be used as an example in the tutorial documentation

Not in favor of pulling widget manager in though.
I'm about 50/50 with widgets, some projects make extensive use of them, some don't at all.  I just don't see widget manager as a core necessity.

**Comment by iionly** [comment]
It wasn't my intention to suggest dropping the custom_index plugin without a replacement. If custom_index would be pulled out without adding something else / better there would be no index page / landing page anymore at all out-of-the-box.

As with other plugins suggested to be added to core the Widget Manager plugin could be included via composer. So, it wouldn't necessrily mean to take over development. Of course, it would be a matter Coldtrick would have to decide on first of all.

And to cite @beck24 (comment on adding an event plugin to core) regarding not everyone needing widgets: if you don't need the plugin, simply don't enable it.

**Comment by jdalsem** [comment]
Closing this ticket as there is no need to pull in Widget Manager. If anybody feels the need to drop custom_index, open a new ticket

**Comment by iionly** [comment]
Well, I thought it would make a lot of sense to add Wiget Manager to core as it seems to me a general purpose plugin that would not only improve the handling of the index page / landing page (especially for inexperienced admins) but also make the profile pages and group pages better. And again: the point was to add Widget Manager in the first place and NOT dropping custom_index (especially not without a proper replacement). I also have to scratch my head slightly about the "not needed by everyone" especially considering the current discussion about adding an events plugin - which is surely a much more specific use case and not needed by everyone either.

**Comment by beck24** [comment]
I think the difference is that events are an expected base functionality for social functionality.  While it is a fantastic plugin, I don't think widget manager fits that same criteria.

**Comment by iionly** [comment]
Expectations about base functionality might be quite different for everyone. I thought that adding a multi-purpose / general-purpose plugin to core would make sense - especially if it would be much of an improvement over the existing solution (custom_index) without losing any functionality. Some base expectations I always had since starting with Elgg: why can't I configure the widgets of the index page and group pages in the same way as the widgets on the profile pages? Why do I have to configure the index page by coding even for the core plugins? And I always thought I wouldn't be the only one who has these expectations as there were quite a number of discussions on the community site where people asked just about such functionality and where I always suggested the use of the Widget Manager plugin.

But let's put an end to that discussion.
