### ISSUE TITLE
Missing API to check if JS/CSS has been registered/defined

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8109]
It would be great to have some way to check if JS has been defined before redefining it with a different path. 
Perhaps to make it more useful, we could add version numbers? So, a plugin could check if the vendor lib has been defined and if so what version, and decide whether to provide an alternative source.

**Comment by mrclay** [comment]
Sounds useful. Same goes for `elgg_define_js`

**Comment by jdalsem** [comment]
I currently see no need and no simple way to provide anything useful at the moment
