### ISSUE TITLE
Upload a file button missing from file plugin sidebar search

### ISSUE THREAD

**Issue by twentyfiveautumn** [Elgg/Elgg#8110]
When you search specific file types from the sidebar in the files plugin the page you are taken to is missing the **Upload a flle** button in the title menu.
Even if you click **All** in the sidebar the button is missing.

Adding
```
elgg_register_title_button();
```
to line 20 of **mod/file/pages/file/search.php** corrects the issue.

**Comment by juho-jaakkola** [comment]
I agree it would be better UX to have the button also on the search pages.

**Comment by LBSelometsi** [comment]
hi, ive added the file plugin but i cannot seem to upload nay files whether video, photo or audio, pls assist..
