### ISSUE TITLE
Support migrating data across storage options

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8111]
A secondary goal for the cloud storage project I'm on is to support live migration of data across the different storage options supported. Is this something we'd want in core? My initial reaction is it's a bit out of scope for core, so I was going to implement it as a plugin.

**Comment by jdalsem** [comment]
@brettp is something like this still on your mind? I do not see a lot of enthusiastic comments on this issue... i also do not understand what kind of 'live' data migration you are looking for and why core should provide this

**Comment by jdalsem** [comment]
Closing this as i do not expect anything to happen soon
