### ISSUE TITLE
Aim to support distributions of Elgg

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8112]
This idea was floated before, but now that Composer support is improving I think this is an important step for Elgg. It's very difficult for beginning devs to find, assemble, and configure existing plugins to create a cohesive site outside of Elgg's out-of-the-box UX.

It would be great to be able to spin up one of these sites quickly, and on the dev side to be able to take a site and export it as a distribution without huge difficulty.

Anecdotally, this has been a boon to the popularity of Drupal, which has [300 actively maintained distros](https://www.drupal.org/project/project_distribution?f%5B0%5D=im_vid_44%3A13028&f%5B1%5D=im_vid_46%3A9988&f%5B2%5D=&f%5B3%5D=sm_field_project_type%3Afull&text=&solrsort=iss_project_release_usage+desc&op=Search) in its official catalog.

**Comment by ewinslow** [comment]
I think I'd we can do elgg/starter-project, that will get us 80% of the way there. Distributions then just becomes composer files with a preselected set of plugins... starter-project being the most basic...

**Comment by jdalsem** [comment]
I think we can close this, for now, with the existence of the starterproject

If we really want to support distributions we need to provide some kind of index on the community. I do not see that happening right now
