### ISSUE TITLE
jsTree vendor module

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8113]
Could we move jsTree out of developers mod into the core? I think it's a useful vendor lib to have as an    AMD module. 
As a next step, we should migrate pages plugin to use jsTree with AJAX loading

**Comment by beck24** [comment]
+1 - see this discussion for a good reason for ajaxing the pages usage of jsTree
https://community.elgg.org/discussion/view/2056919/pages-performance-problems-with-many-subpages-in-18x

**Comment by juho-jaakkola** [comment]
+1

**Comment by ewinslow** [comment]
I wish there were a way that both these plugins could just directly depend
on the library and have it automatically dedupe. Core doesn't need it. And
it shouldn't be part of our api, but clearly multiple plugins would find it
useful...

**Comment by hypeJunction** [comment]
We could make it a plugin and expose a view for plugins to use.

**Comment by ewinslow** [comment]
On master we now have a good way to do this with composer. If the plugin defines a composer.json, you can explicitly require a bower asset by running `composer require bower-asset/{name}:^version` in the plugin's root. In this particular case the command would just be `composer require bower-asset/jstree:^3.0.1` or somesuch.

I want to write a blog post about making your dependencies explicit/direct. No one should be depending on their dependencies' dependencies. It's a recipe for breakage, but it's also completely the mindset of every current plugin and plugin developer out there. Elgg's community is not used to dependency managers, and probably all these dependency managers (`composer`, `amd`, `bower`, etc.) could be confusing for people that are used to the old way: something like "Elgg core includes jquery, so I'll just assume it's available". Rather, plugins (like AMD modules) should declare their own dependency on jquery explicitly if they want to use it...

I guess bottom line is that I'm closing this in favor of explicit composer dependencies. Reopen if you strongly object for some reason.

**Comment by ewinslow** [comment]
@hypeJunction It appears you don't consider this ticket resolved. Can you reopen and explain why?

**Comment by hypeJunction** [comment]
@ewinslow I see multiple problems in your way of thinking:

1. Not all vendor libs are public, nor all have been registered with bower.
2. Not all plugin authors will want to make their plugins public, nor will all want to register them with packagist
3. Unless you build an installer a-la WordPress that will support multiple plugin databases, and allow installing plugins by upload, you are forcing non-tech users to learn composer/cli.
4. If we allow installing plugins by upload, we can't rely on composer/bower to resolve dependencies, and plugins should have their assets contained within the plugin structure, so the above solution doesn't really solve the problem with sharing assets.
5. Currently, we have to register static third party resources by calling elgg_define_js/elgg_register_css, so we need to know where they are located relative to start.php. Unless there is a naming convention, you run the risk of requiring same library multiple times. So if I were to require jquery.jstree, while developer tools requires jstree, that's a performance hit, and possibly broken JS.

**Comment by hypeJunction** [comment]
6. What if a plugin wants to use a CDN distribution of the asset? Composer/bower fall out of the picture, and you end up with having a versioning problem again.

**Comment by ewinslow** [comment]
You seem uncomfortable with the direction we're going with composer. I like the idea of a user-friendly web ui for installing plugins. It could even delegate to composer under the hood. In fact I think we'd have a really hard time building a robust installer without composer because of the dependency problem.

Point number 5 is a good one too. I just don't think putting js libs that core doesn't need into core (which is what this ticket originally suggested) is the way to solve that.

A plugin that just provides jstree would be fine but if you check jstree into that plugin instead of using composer, then you created regular work for yourself to run some install script or go find the latest library and copy paste it in and then release a new version of the plugin each time jstree pushes an update. So I'm just concerned about maintenance effort I guess. I want minimal maintenance effort for whatever solution we adopt.

I don't follow the versioning problem comment when cdns come into play.

**Comment by ewinslow** [comment]
Rather "uncomfortable with the direction I'd like us to go".

**Comment by hypeJunction** [comment]
I have been using composer for over a year now, and I love it. You may remember my post in the community. It pretty much summarizes, why I am not so comfortable with it from a plugin dev standpoint https://community.elgg.org/discussion/view/2131399/composer-dependency-management-and-class-autoloading-lessons-learnt. I trust your judgement on this, of course, and ultimately it's your call, and the time you are going to invest into this.

I mention versioning because it exists with jsTree. In one of my plugins, I use a newer version of jsTree, if we were to rely on composer to resolve both dependencies, we would end up with broken developer tools, as it would pull newer version for my plugin.
