### ISSUE TITLE
Install does not work on 1.8 anymore

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#8114]
There is no /vendor/autoload.php file required for install.php

require_once __DIR__ . "/vendor/autoload.php";

**Comment by ewinslow** [comment]
Looks like the 1.10 branch got pulled in to 1.8... I believe Matt did the
1.10.4 release.

**Comment by ewinslow** [comment]
I think it'd be OK to remove this mistake from the 1.8 history, rather than
'git revert'

**Comment by gerard-kanters** [comment]
It turns out you need composer install on 1.8 too. I will close the ticket

**Comment by gerard-kanters** [comment]
No it was not that easy, lots of errors when using composer.

**Comment by gerard-kanters** [comment]
BTW: The zip on elgg download page is also not working :-(

**Comment by ewinslow** [comment]
I already explained the problem... ?

**Comment by Srokap** [comment]
Yup, we got unwanted code in 1.8 branch for some reason. Need to clean this up. Don't try to find reason in it @gerard-kanters as it's not supposed to work.

**Comment by Srokap** [comment]
It looks like smb did the forced push of the 1.8 branch I'd say.

Trying to figure out what happened:
- Github says: `1.8 Updated 6 days ago by beck24` but might just mean the last commit pushed into 1.8 branch.
- cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f 1.8.20 release
- c15580b25316fd9ef42df5a65b1a0be57a6aef65 Steve merges 1.8 into 1.9

I see no explicit merge of 1.10 into 1.8, just 1.8 fast-forwarded (?) to 1.10.

I say we do a hard reset of 1.8 on the last tagged release (1.8.20). Let's confirm we all have the same SHA for this tag:
- Github says cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f
- My local repo says cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f
- My fork says cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f

@Elgg/owners @Elgg/contributors please verify that this it the commit SHA you're seeing on your not updated local copy if you have one.

Whole thing reminds me of https://github.com/Elgg/Elgg/issues/7810

**Comment by beck24** [comment]
I don't remember doing any commits for 1.8 as recently as 6 days ago so
it's likely that this is my mess up.  Not sure how or why offhand, I'll see
what I can find when I get home.  Likely force resetting it to 1.8.20 is
fine and the easiest fix.  Sorry folks!

**Comment by Srokap** [comment]
@beck24 I'm not convinced that's your fault. It's just your commit on top of current 1.8 branch. That's a bummer we don't have reliable way of checking who exactly did the push.

**Comment by beck24** [comment]
> BTW: The zip on elgg download page is also not working :-(

I just tested 1.8.20 from the elgg.org/download.php zip package and it's working fine

**Comment by beck24** [comment]
I think you're right, I don't think it was me - my fork/local 1.8 branch is way behind at https://github.com/Elgg/Elgg/commit/ff09ef148b209bb068f4ccd2cc8f94250ed8a2d3

**Comment by beck24** [comment]
Before I fix it I just want someone to verify the methodology - don't want to mess things up more in an irreversible manner.  This should do the trick right?

```
git clone https://github.com/elgg/elgg.git .
git checkout 1.8
git reset cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f
git push -f origin 1.8
```

**Comment by juho-jaakkola** [comment]
I won't be able to check my local SHA until Monday.

@beck24 The commands look good, but use ```--hard``` to automatically get rid of the untracked files that don't belong to 1.8:
```
git reset --hard cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f
```

**Comment by beck24** [comment]
ok, I have reset the 1.8 branch

**Comment by juho-jaakkola** [comment]
I did have the same SHA as Pawel mentioned: ```cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f```.

**Comment by jeabakker** [comment]
i also have cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f as the last sha

**Comment by brettp** [comment]
I'm on ff09ef148b209bb068f4ccd2cc8f94250ed8a2d3.

On Mon, Mar 30, 2015 at 4:06 AM, Jerôme Bakker <notifications@github.com>
wrote:

> i also have cd72cd6
> <https://github.com/Elgg/Elgg/commit/cd72cd6a0e65ae20fc6ea727cd03d244cbd9e41f>
> as the last sha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8114#issuecomment-87584479>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt
