### ISSUE TITLE
Plugins can't be activated with a language file with an empty array

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#8116]
This is the return array and the error:
```PHP
return array(	
	//'example' => 'Example',
);
```

> customizations (guid: 20) cannot start and has been deactivated. 
> Reason: Cannot register languages for plugin customizations (guid: 20) at ...

**Comment by juho-jaakkola** [comment]
Indeed.
 - Array is checked here: https://github.com/Elgg/Elgg/blob/1.9/engine/lib/languages.php#L93
 - Exception is thrown here https://github.com/Elgg/Elgg/blob/1.9/engine/lib/languages.php#L239
 - ...and catched here: https://github.com/Elgg/Elgg/blob/1.9/engine/lib/plugins.php#L349

I'm not sure if this should be considered a bug or not. It is maybe a bit overkill to disable the whole plugin.

This problem will most likely be fixed once the overhaul for the i18n code gets finished. Let's keep this open until that.

**Comment by PerJensen** [comment]
Lets do that. Maybe it's not a bug, but I see no reason not to allow the plugin to activate.

**Comment by jdalsem** [comment]
Provided a PR to fix this, as it plugins are shown as activatable, but crash during activating as the language file was empty. The PR correctly handles the situation where there is a language file, but it returns an empty array

**Comment by PerJensen** [comment]
Nice fix and working, tested manually.
