### ISSUE TITLE
Documentation Page 404 Error

### ISSUE THREAD

**Issue by moshefeit** [Elgg/Elgg#8117]
I'm new to Elgg. I don't know if it's only me, or it is happening. But the [documentation page](https://learn.elgg.org/en/latest/index.html) is showing **404 Error**.

Also, browser showed the "I understand the risk"/"Add exception" window.

**Comment by brettp** [comment]
Thanks for the report. This was due to a misconfiguration on our side after some server tweaks I made. I've fixed the DNS problem, but it might take a while to show up. You can always visit the docs at http://elgg.readthedocs.org/en/1.10/
