### ISSUE TITLE
Warning: require_once(__DIR__//public_html/engine/lib/autoload.php) [function.require-once]: failed to open stream: No such file or directory in /home/a1498378/public_html/install.php on line

### ISSUE THREAD

**Issue by SSachith** [Elgg/Elgg#8118]
Warning: require_once(__DIR__//public_html/engine/lib/autoload.php) [function.require-once]: failed to open stream: No such file or directory in /home/a1498378/public_html/install.php on line 15

after i upload files to www.000webhost.com and going to 
![elgg](https://cloud.githubusercontent.com/assets/11797930/6993152/42ecd044-db09-11e4-8e88-a55b5a3e6d06.png)
  "www.mybebsite/install.php" i get abrove erro.please anyone help me.thanks!

**Comment by SSachith** [comment]
please hell me to slove this

**Comment by Srokap** [comment]
I seriously doubt it' a core bug, but rather your mistake in server setup. Please seek support at https://community.elgg.org/, we handle here only core bugs.

When writing on community please include detailed information on which package are you using, but I'd advise to first check if yo uploaded files correctly.

**Comment by SSachith** [comment]
thanks

**Comment by SSachith** [comment]
thanks!
