### ISSUE TITLE
Trigger a system event after loading translations

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8119]
It seems that plugins do not have a way to add/modify translations only when the simplecache is regenerated. I can't find a place to add some translations from database without doing unnecessary DB queries on each page load.

**Comment by beck24** [comment]
How does translation_editor handle it?

**Comment by hypeJunction** [comment]
Quick look at the code doesn't reveal any special logic. Looks like the translations are loaded on plugins boot. Maybe @jdalsem can clarify

**Comment by jdalsem** [comment]
Translation editor stores no strings in the database, but in one big (merged) translation file that gets added to the translations during boot (there is no difference between cache on/off).



> It seems that plugins do not have a way to add/modify translations only when the simplecache is regenerated

you could do:
```php
if (elgg_is_simplecache_enabled()) {
    add_translation('en', $only_when_enabled_translations_array);
}
```

Or are you looking for something else?

**Comment by jdalsem** [comment]
my bad, you only wanted when the simplecache is regenerated... there is no hook or event currently in Elgg that you can rely on to only do something during the reset of the language cache...

Maybe `reloadAllTranslations` could use an event trigger...
