### ISSUE TITLE
elgg-avatar-large extends the entire width of its parent

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8122]
There's width: 100% on the wrapper and the image. This causes the avatar to stretch to the full width of the parent container, which I don't think is desired behavior. You can see this in the theme preview.

**Comment by brettp** [comment]
Should mention this is both aalborg and stock themes.

**Comment by hypeJunction** [comment]
I think the intention is to downsize it to the parent width. Perhaps max-width is needed as well.

**Comment by brettp** [comment]
If it's trying to downsize to the parents width (to avoid overflow?) it should use only max-width. The biggest problem is that it's inconsistent with the other sizes, which have explicit dimensions.

**Comment by hypeJunction** [comment]
IMHO, we should be getting rid of fixed sizes, they are pain in responsive design.

**Comment by PerJensen** [comment]
We had a discussion about it here, https://github.com/Elgg/Elgg/issues/5602

**Comment by brettp** [comment]
@5602 was related and probably where the width: 100% came from, but it talked about images that are too small or require upscaling...not exactly the same.

> IMHO, we should be getting rid of fixed sizes, they are pain in responsive design.

Maybe, but there's a demonstrable bug in the large avatar icons right now that we should address. We don't use width: 100% or expect the parent to set the width for any of the other avatars or icons. Which makes me think this was a special case for the profile page.

**Comment by twentyfiveautumn** [comment]
Seems we should just reject avatar uploads smaller than 200px wide.

**Comment by Srokap** [comment]
We already have special case for large avatar by making it non-square. For those who are square it's obvious to determine fixed dimensions, but for rectangle, extending it is pretty elegant approach to the problem of fitting it into the page. Also I think we should go into responsive first approach. We could have some more function-related class name than `elgg-avatar-large` for a css class, especially if it's supposed to be treated as part of the reusable api. `elgg-avatar-large` does not mean much and can be interpreted in various ways, but something like `elgg-image-fluid` or `elgg-image-elastic` is better describing what's happening here.

**Comment by jdalsem** [comment]
This should not be a problem in master anymore
