### ISSUE TITLE
Tags for discussion topics are saved with a leading space

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8123]
The discussion/save action uses split(",", $tags) instead of string_to_tag_array(), so surrounding whitespace is saved as part of the tag.

This looks like it was introduced in 1.8, so fixing it will require an update to trim whitespace on existing tags.

**Comment by brettp** [comment]
This was actually introduced in 1.9. 1.9's Elgg_Database::sanitizeString() doesn't trim but <= 1.8's sanitise_string() did. This means all metastrings added since 1.9 are not trimmed.

IMHO this is regression with at least adding metastrings, and possibly with sanitizeString(). Are there any use cases for metastrings with whitespace padding?

**Comment by beck24** [comment]
I can't think of any
