### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by Hanzolo** [Elgg/Elgg#8125]
I tried to upgrade elgg on my localhost from 1.9.8 to 1.10.5
When I want to run the upgrade.php afterwards I get the following error:

Parse error: syntax error, unexpected '[' in /var/www/html/elgg/engine/classes/Elgg/Di/ServiceProvider.php on line 194

There it is written:

$params = $c->config->get('cookies')['session'];

**Comment by juho-jaakkola** [comment]
You need to upgrade to PHP 5.4
