### ISSUE TITLE
Forward to comment after posting it

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8130]
Currently user is taken by default to the commented object after posting a comment:
```php
forward(REFERER);
```

Couldn't we just always forward to the comment itself:
https://github.com/Elgg/Elgg/blob/master/actions/comment/save.php#L95

**Comment by juho-jaakkola** [comment]
It seems we could get rid of the ```is_edit_page``` variable completely. https://github.com/Elgg/Elgg/search?utf8=%E2%9C%93&q=is_edit_page

**Comment by jdalsem** [comment]
Seems logical, are there usecases where there is something special? Like commenting on something but not on the form attached to the object? Like from the activity stream (although that currently is tackled because it is an ajax call)

**Comment by jdalsem** [comment]
Is the action also used for edits? Those are also sometimes inline...

**Comment by juho-jaakkola** [comment]
I cannot think of any use case where we could *not* forward to the comment itself.

**Comment by jdalsem** [comment]
> I cannot think of any use case where we could not forward to the comment itself.

me neither... besides the ajaxed save actions i mentioned before

**Comment by juho-jaakkola** [comment]
But we're not using forwarding at all when the comment is saved using ajax, right?

**Comment by jdalsem** [comment]
hmm i noticed commenting on the river is not ajax (i thought it was), thus we still need REFERER

**Comment by juho-jaakkola** [comment]
Quick fix would be to allow passing in the referer URL as a parameter. The comment URL would be used unless explicitly told to do forward somewhere else.

**Comment by mrclay** [comment]
PR #9441
