### ISSUE TITLE
add a way to add toggle menu items from php / output/url states

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8158]
We currently have this js:
'elgg.ui.registerTogglableMenuItems('feature', 'unfeature');'

can't we come up with a way to autodetect those with a generic js function? or register the menu items as toggleable from php?

This could prevent adding js files or have inline js for just toggleable menu items.

Any preference?

**Comment by ewinslow** [comment]
Yea, it would be great to have this be more automatic so people don't have to register custom JS to make it work.

**Comment by ewinslow** [comment]
One idea I had for these toggle buttons is to have folks provide some structure like so::

```php
[
  "type" => "toggle-button",
  "is_pressed" => true, // use some actual logic for the default value
  "pressed" => [
    "label" => "Unfeature",
    "icon" => "thumbs-down",
    "href" => "/action/unfeature",
    "method" => "POST", // anything other than GET will submit via XHR
    "class" => "pressed",
  ],
  "unpressed" => [
    "label" => "Feature",
    "icon" => "thumbs-up",
    "href" => "/action/feature",
    "method" => "POST",
    "class" => "unpressed",
  ],
]
```

The other option is to make it more generic and just let people list options for what actions to take:

```php
$item = [
  "type" => "select",
  "value" => 'feature', // use some actual logic to get default action
  "options" => [
    "feature" => [
      "label" => "Feature",
      "icon" => "thumbs-up",
      "href" => "/action/feature",
      "method" => "POST",
    ],
    "unfeature": [
      "label" => "Unfeature",
      "icon" => "thumbs-down",
      "href" => "/action/unfeature",
      "method" => "POST", // anything other than GET will submit via XHR
    ],
  ],
];
```

**Comment by ewinslow** [comment]
One thing we really need in order to have a responsive UI is optimistic updates. So even if we haven't reached the server, we want to update the UI as if the request was successful. This is perhaps the hardest part of this all because you need to be able to reflect the new state of the world on the client without duplicating logic in JS and PHP. I haven't figured out how to do this yet :(

**Comment by hypeJunction** [comment]
@mrclay @ewinslow Please take a look to see if this is worth pursuing for core: https://github.com/hypeJunction/Elgg-ui_element_states

**Comment by mrclay** [comment]
@hypeJunction you could easily do optimistic updates with that, since the component already knows the next state. Thoughts: our existing actions tend to just output some user message; for Ajax requests they should at least respond with some client-consumable data like `{"success":true}`. The implementation assume 200 response means success, when potentially the state should be reverted or even moved to a different state. But this is a very useful start.

**Comment by hypeJunction** [comment]
I don't like optimistic updates to be honest. Like with core Add friend implementation - tge button disappears too fast without any feedback and then a message follows 20 seconds later. But yes, we could switch between states easily on failure.

**Comment by hypeJunction** [comment]
I am going to use this on a project and polish it up. I have noticed that we have lost status codes and the hooks strip messages, so we need something to indicate response status. Once I have time I plan to work on allowing Symfony Response from actions and page handlers.

**Comment by mrclay** [comment]
Consider how we'd use it for likes. I guess in that case the likes module would register for the ajax_response hook to get a peek of the data returned.

**Comment by mrclay** [comment]
Can we also give states to menu items a similar way?

**Comment by hypeJunction** [comment]
Menu items use `output/url`. I think it should work as is, but you would have to assign some default values to `text` and `href`, those would then be replaced by `state` values. I haven't tried yet. But yes, it can be done.

**Comment by hypeJunction** [comment]
Furthermore, we will need to teach ajax api to handle error codes with response body. Current it's dumb and only shows connection to server lost error.

**Comment by mrclay** [comment]
Agree there should be 1 markup element, but the need to define all states server-side for every draw bothers me a bit. What if: changing a state requires fresh data; there are lots of states; or rendering the inactive states is expensive. I guess it's fine for our typical uses.

**Comment by hypeJunction** [comment]
If we have the common interface for toggling states we can then teach it to fetch data if fresh data is required. IMO, at this point, we should just address basic use cases of Add/Remove friend and Like/Unlike.

**Comment by mrclay** [comment]
Packing future rendering data into the menu item feels like we're making this too complex and will end up with JS that's too magical to work with. Would rather elgg/likes.js be compiled with all the logic it needs to operate and we strive to keep server-side rendering pretty basic. Just a SPAN with basic parameters the module needs to draw the initial state.
