### ISSUE TITLE
[Feature request] - Indicate already invited users in groups/invite

### ISSUE THREAD

**Issue by michelesbw** [Elgg/Elgg#8167]
It could be useful to indicate somehow if users have already been invited to a group (ie. "already invited" below their name) instead of letting a group owner invite and then read error message "User has already been invited", what do you think?

Cheers
M

**Comment by jdalsem** [comment]
I agree completely.. it was already on the wishlist for group tools https://github.com/ColdTrick/group_tools/issues/69

**Comment by michelesbw** [comment]
Nice!

**Comment by michelesbw** [comment]
After looking at https://cloud.githubusercontent.com/assets/83539/3819172/e9c6e55c-1ce7-11e4-8d6e-25e9e3edb082.png I think we're maybe talking about 2 different things:
- see invitations (yours)
- make invitations (my suggestion). If I am a group admin and want to invite friends then in the list I got all of them without any indication of who has already been invited. This could be improved imho
Cheerrs

**Comment by jdalsem** [comment]
> I think we're maybe talking about 2 different things

yeah we were :) but the other one is also cool

**Comment by michelesbw** [comment]
:)
