### ISSUE TITLE
Improve usage of 'class' var in views

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8168]
Currently there are multiple uses of the 'class' var in views. Best way is to handle them as arrays and allow views to append/reset items in this array. There should be a check for duplicates somewhere.

This ticket is a result of this discussion: https://github.com/Elgg/Elgg/pull/8135/files#r28132648

**Comment by mrclay** [comment]
@jdalsem is there more to do on this?

**Comment by jdalsem** [comment]
The question is if we want to prevent duplicates in classes for example... maybe filter them in elgg_format_attributes?

**Comment by jdalsem** [comment]
As the incidental duplicates are not causing any realworld problems, i am closing this
