### ISSUE TITLE
Deprecate/ban use of anonymous functions or not?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8186]
We know anonymous functions are impossible to unregister as handlers, but some appear to be in favor of banning their use or nagging developers to avoid them. Just thought I'd start a discussion here.

Personally it would kind of bug me to not be able to use them even though it makes my plugins' actions less reversible. I'd be OK just discouraging devs not to use them.

**Comment by beck24** [comment]
I have nothing against anonymous functions themselves, my issue is with the inability or very ugly/hackish ways required to unregister them when used in events/hooks.  The point of a framework, as far as I'm concerned, is to have a bunch of really useful default behaviors and convenience functions but also provide nice easy ways to change that behavior.  Using anonymous functions in this way feels like it's going against that, and as soon as someone runs into something they can't do, that's when forking/hacking occurs.
So I'm definitely in favor of banning such usage in core.  As far as plugin devs - part of me leans toward outright banning because I don't want them used, though the libertarian part of me says that's probably going too far.  I would definitely like to discourage them.  I unregister stuff all the time, and the idea of an otherwise really useful plugin doing something irreversible really irks me.

**Comment by hypeJunction** [comment]
I'd say there is nothing we should do other than reiterate why anonymous
functions are discouraged. You can't stop plugin devs from doing crazy
things.

**Comment by brettp** [comment]
This seems like a good case for reflection. Some quick tests looks like we could generate a name that can be used to unregister from what we have available through reflection:

```php
<?php

/**
 * @elgg_handler_name test
 */
$test = function() {
	echo "hello";
	return true;
};

$r = new ReflectionFunction($test);
var_dump($r);

$t = ReflectionFunction::export($test, true);
var_dump($t);

var_dump($r->getDocComment());

var_dump($r->getFileName());
var_dump($r->getStartLine());
```

I'm thinking of a couple possibilities:
* Use a combination of getFileName() and getStartLine() to create a name like `<modname>_7`.
* Require anonymous functions to have a docblock that tags the closure with a name. Loudly reject closures without this.

I think asking people not to use a language feature is a failure on our side. That said, not being unable to register a handler could cause people to edit or fork code.

**Comment by beck24** [comment]
That seems way more complicated than simply naming the function in the first place...

**Comment by brettp** [comment]
Agreed, but it maintains flexibility for people who do use anonymous
functions. If I had to pick, I'd rather ban anonymous functions than allow
a single plugins a "trick" that prevents them from being modified by other
plugins. Either way, it just feels wrong and overly restrictive.

On Tue, Apr 14, 2015 at 11:30 AM, Matt Beckett <notifications@github.com>
wrote:

> That seems way more complicated than simply naming the function in the
> first place...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8186#issuecomment-92911072>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by mrclay** [comment]
@brettp did you see #8071?

**Comment by brettp** [comment]
I did not. Looks like you've been down this path already. Looks like that
puts me in the "ban anonymous functions" boat.

On Tue, Apr 14, 2015 at 2:04 PM, Steve Clay <notifications@github.com>
wrote:

> @brettp <https://github.com/brettp> did you see #8071
> <https://github.com/Elgg/Elgg/pull/8071>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8186#issuecomment-93001424>.
>



-- 
Brett Profitt
Elgg Lead Developer

Elgg: http://elgg.org/
Skype: brett.profitt
Twitter: http://twitter.com/brettprofitt

**Comment by hypeJunction** [comment]
I have started using anonymous functions as a callback for 'init', 'system'. If anyone wants to unregister it, they might as well disable the plugin.

**Comment by beck24** [comment]
You have a good point that it's unlikely that you need to unregister the init handler, but I would argue for consistency, and using it in one event and not others is inconsistent - especially if new devs see your code as an example of how to do things... so stop it I guess is what I'm saying

**Comment by hypeJunction** [comment]
Perhaps you are right. I will reconsider.

**Comment by juho-jaakkola** [comment]
I agree with Matt.

**Comment by mrclay** [comment]
Created https://github.com/Elgg/Elgg/issues/8207. Reopen if we need to do more.
