### ISSUE TITLE
Unable to log in with user id

### ISSUE THREAD

**Issue by Westlake56** [Elgg/Elgg#8191]
I just installed 1.11.0 as an upgrade to 1.10.4.

Log in issue, problem when user id is the same as the first part of the email address. Here is what I mean;
user id: datadan
email: datadan@rogers.com

If you try to log in with the user id it gives an error, log in not valid. If you log in with the email address it works fine.

The user id must be different than the first part of the email address. 

I do run the social login plugin in case that is causing the issue. https://community.elgg.org/plugins/1440827

**Comment by mrclay** [comment]
I'm not able to reproduce this. My username is "admin", changed my email to "admin@example.com" and logged in fine with username"

**Comment by Westlake56** [comment]
Sorry it must have been some type of glitch, password storage or cookie issue on my end. I just tried registering as a new user with the user id the same as the first part of the email address and it works fine.
