### ISSUE TITLE
Can't remove CKeditor's contextmenu plugin

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8195]
`Plugin "contextmenu" cannot be removed from the plugins list, because it's required by "liststyle" plugin.`

Liststyle apparently gives you a context menu allow you to change list style, e.g. to square. Which gets stripped by Htmlawed anyway.

**Comment by jdalsem** [comment]
Is this with a stock Elgg or with a customized set of ckeditor options?

**Comment by juho-jaakkola** [comment]
stock Elgg

**Comment by mrclay** [comment]
To be clear, I think removing CKeditor's context menu is the fix to this bug, not just suppressing the JS error.

**Comment by jdalsem** [comment]
I think you meant to remove the liststyle plugin... i updated the PR
