### ISSUE TITLE
Docs for 1.11

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8197]
- [x] Add 1.11 branch to learn.elgg.org (and Elgg-es, Elgg-de)
 - [x] Add 1.11 to release policy: http://learn.elgg.org/en/latest/appendix/support.html
 - [x] Update "1.X Documentation" titles
 - [x] Update badges references
 - [ ] Update scrutinizer configuration
 - [x] Update reference.elgg.org build script

**Comment by juho-jaakkola** [comment]
1. I'm not aware how this happens. I assumed 1.11 would get added automatically after a while. Apparently it is not so.
2. I ran out of time when doing the release.

**Comment by juho-jaakkola** [comment]
1. I've activated the 1.11 branch in Read The Docs and set it as default

**Comment by Srokap** [comment]
We should write down somewhere a checklist for such updates.

We also should have updated:
- badges references
- scrutinizer configuration
- reference.elgg.org build script

**Comment by iionly** [comment]
Translation of docs is also not available for Elgg 1.11 branch on learn.elgg.org, e.g.
http://elgg.readthedocs.org/de/1.10/ works but
http://elgg.readthedocs.org/de/1.11/ fails.

While there haven't been many docs translated yet the languages available for selection at learn.elgg.org seem incomplete, too. My guess is that the available languages (de, es) have been enabled manually at some point. But some others are missing that already have at least something of the docs already translated.

**Comment by juho-jaakkola** [comment]
How can we update the titles at learn.elgg.org?

**Comment by ewinslow** [comment]
I don't know what scrutinizr config needs updating. The one in Elgg/Elgg doesn't seem to refer to the docs at all.

**Comment by ewinslow** [comment]
BTW, anyone else feel like this is too much overhead just to cut a release? :)

**Comment by jdalsem** [comment]
@Srokap what about the scrutinizer config? What change is needed there?

**Comment by jdalsem** [comment]
Closing this as i do not know what scrutinizer config means
