### ISSUE TITLE
layout difference 1.10 vs 1.11

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8199]
There is a difference in the spacing on the admin side of Elgg between 1.10 and 1.11 (both with aalborg active)

Adv site settings 1.10
![advanced settings elgg 1 10](https://cloud.githubusercontent.com/assets/881958/7139549/336e5474-e2c7-11e4-9d2b-30fd0e35aaa4.png)

Adv site settings 1.11
![advanced settings elgg 1 11](https://cloud.githubusercontent.com/assets/881958/7139554/3ac00cd6-e2c7-11e4-86e7-cddbee2bf1e1.png)

**Comment by mrclay** [comment]
Need to add a space after the checkboxes.

**Comment by jeabakker** [comment]
in https://github.com/Elgg/Elgg/blob/1.11/views/default/input/checkbox.php#L49
```php
echo elgg_format_element('label', ['class' => $label_class], $input . $label);
```
replace with
```php
echo elgg_format_element('label', ['class' => $label_class], $input . ' ' . $label);
```
solves this

**Comment by hypeJunction** [comment]
Perhaps we could solve this with CSS 
```css
input[type="checkbox"]:after {
  content: " ";
  display: inline;
}
```

**Comment by jeabakker** [comment]
the problem was that in 1.10 there was a new line in the html code which provided the 'space' this can't be achieved by elgg_format_element.
My solution is also something different than 1.10 was
@hypeJunction solution is even more invasive because **all** checkboxes will get a space after even if this is not intended. Eg. if i have a table-cell with a checkbox (no label) in your suggestion this will add a space in the cell and this could cause layout issues

**Comment by mrclay** [comment]
#8262

**Comment by jeabakker** [comment]
thx @mrclay
