### ISSUE TITLE
Only send whitelisted content types with uploaded files

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8211]
http://security.stackexchange.com/a/8655/4982 includes this terrifying comment: "`<script>` tag will load and execute a payload from an URL that returned Content-Type-Disposition: attachment header"

So even with `Content-Disposition: attachment`, we don't want to send any "active" Content-Type, like text/html, application/x-shockwave-flash, crossdomain.xml.

It sounds to me like the best option is to only send files with `application/octet-stream` unless we can sniff the file/matches an ext on a whitelist of trusted MIME types.

**Comment by mrclay** [comment]
I guess the Q is, what's the harm in sending, say, a Word file with `Content-type: application/octet-stream`?

**Comment by hypeJunction** [comment]
I see no harm

**Comment by twentyfiveautumn** [comment]
Same sort of approach, in my file plugin I'm adding a switch statement to handle different mime types and if it falls though to default it's an error message "unrecognized file format"

**Comment by twentyfiveautumn** [comment]
if it even smells like microsoft I'm probably not going to allow it ;)

**Comment by twentyfiveautumn** [comment]
thinking of HTML accept attribute on the upload form as well.
