### ISSUE TITLE
View vars leaking into markup

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8218]
We need some stricter filtering of vars before formatting attributes. We end up with attributes such as ```entity_allows_comments="entity_allows_comments"```. Perhaps we could at least check for underscores in attribute names and filter those out.

**Comment by ewinslow** [comment]
removing underscores sgtm

**Comment by mrclay** [comment]
PR #8252

**Comment by mrclay** [comment]
I don't think banning underscores is going to work: https://github.com/Elgg/Elgg/pull/8252#issuecomment-96968082
