### ISSUE TITLE
input/access with custom options and no value

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8219]
Scenario:
Default access level = 1

```php
echo elgg_view('input/access', array(
   'options_values' => array(
       0 => 'Private',
       2 => 'Public',
   )
));
```

Resulting select contains an option 1 => Missing access level name

So the view should not assign a default site-wide value if a custom set of options is provided and does not contain that default value.

**Comment by hypeJunction** [comment]
@jdalsem Will you grab this? Or should I?

**Comment by jdalsem** [comment]
you can
