### ISSUE TITLE
Assign multiple values to input/select is not working

### ISSUE THREAD

**Issue by augusto-moreira** [Elgg/Elgg#8221]
The input/select cannot assign selected options because it compares a value in the array $value with an array value in the options_value.
To work correctly it should search the array keys not the array values.

**Comment by augusto-moreira** [comment]
Proposal fix in https://github.com/Elgg/Elgg/commit/2d225b31a45c6216aac73263415e638b132259db

**Comment by hypeJunction** [comment]
I suppose we need to check if multiple option is set. Your proposal will only work with options_values and not options.

**Comment by augusto-moreira** [comment]
With options_values set, we need to check both multiple and single values. Even a single value must match the array key not the array value.
If only options array is set then we don't need to check the key because the options array doesn't have keys (only values).

**Comment by jdalsem** [comment]
This currently is no longer an issue
