### ISSUE TITLE
Possible problem with session cookies configuration bootstrapping

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#8223]
I kept seeing this problem that instead having `Elgg` cookie used for session, I get stuck with `PHPSESSID`. Initially I thhaoght it might be sth wrong with my setup using php built-in webserver, but I see it on Apache as well. Testing using e0482f46e76cd6cffc8801ef100d77a7fde255dd (master branch)

To reproduce, 
- install Elgg.
- Delete all cookies from the browser for Elgg page.
- Refresh page.
- See `PHPSESSID` showing up instead of expected `Elgg`.

Functionally it works just fine.

**Comment by mrclay** [comment]
Fix #8224
