### ISSUE TITLE
Add $query as a second param to elgg_normalize_url

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8225]
Could we consider adding $query array as a second param to elgg_normalize_url() to avoid constructs like:

```elgg_http_add_url_query_elements(elgg_normalize_url($url), $query)```

I think this would be cleaner:

```elgg_normalize_url($url, $query)```

**Comment by mrclay** [comment]
I would rather roll it into #5227

**Comment by ewinslow** [comment]
+1 for handling this in an OO service.
