### ISSUE TITLE
elgg deprecation 1.11 getSubtype()

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8234]
Hello,
I'm trying delete a comment with ajax call with the code below:
```php
$comment_guid = get_input('guid');
$comment = get_entity($comment_guid);

if (elgg_instanceof($comment, 'object', 'comment') && $comment->canEdit()) {
    if ($comment->delete()) {
        system_message(elgg_echo('generic_comment:deleted'));
    } else {
        register_error(elgg_echo('generic_comment:notdeleted'));
    }
} else {
    register_error(elgg_echo('generic_comment:notfound'));
}

if (elgg_is_xhr()) {
    header("Content-Type: application/json");
    print(json_encode($response));
}

forward(REFERER);
```
but I get this deprecation warning:
> Deprecated in 1.9: Use getSubtype().

This deprecation is released as they said : 
> only show deprecation notice if user reads ->subtype after save/load

but I'm not after saving of loading anything. I'm just before deleting! I got this deprecation error on deleting a blog, either (even when I'm not using an ajax call). the deprecation warning comes from `elgg_instanceof(...)` and `canEdit()` functions. But I don't know how to fix it and even what is wrong, which I get this warning!
How do I fix this issue? I'm doing something wrong?

Thanks in advance.

**Comment by mrclay** [comment]
Your error_log will have a stack trace. This is probably coming from an old plugin. We're getting rid of the visual deprecation notices because they're useless. Instead watch your error log or turn on visual logging in the developers plugin.

I'm closing this as not an elgg bug. Please use the community for support.
