### ISSUE TITLE
Eliminate roadblocks to OO APIs

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8238]
There's considerable desire to stop adding global functions and expose OO services to plugins; here's what's in our way IMO:

- There's no public service locator.
- We must decide whether we want this locator to be accessible globally (e.g. `elgg()`) and/or inject it into plugins where needed.
- If not global, we need to get it into event/hook handlers. This will take changing our mind and adding params into events, or my preferred solution of overhauling events so handlers accept a single Event object with the core SL pre-injected.

**Comment by ewinslow** [comment]
I vote `elgg()`. This suggestion was rejected some time back when I initially proposed it, but I can't see any real downsides. It seems like a good short-term compromise.

After that the question becomes how to open the service locator for extension by plugins. But we can take one thing at a time. Moving off of global functions would be great...

**Comment by mrclay** [comment]
To jump ahead a bit, my current thinking is that any plugin can provide a get_plugin.php script which returns a customized plugin object (also a DI container). 1. This eliminates collisions on a global SL, and 2. Plugin authors gain static analysis for services provided by their own SL.

**Comment by Srokap** [comment]
I was imagining something like
- require plugin to provide object instead of start.php (name of object could be set in manifest.xml)
- instead of loading start.php, instiantiate object and pass to the constructor _something_ that would contain DIC for plugins and provide all the api (no global functions at all)
- we could provide slightly different objects to different plugins to have more control over context (ie. could track which plugin does what without looking at backtrace)
- I imagined that this object would be ElggApplication with possible additional layer of facade for additional in-plugin context that I mentioned

It was mostly loose thoughts though.

**Comment by brettp** [comment]
> require plugin to provide object instead of start.php (name of object could be set in manifest.xml)

If we decide to add configuration, I'd like to get away from manifest.xml and to composer.json. [There's an "extra"](https://getcomposer.org/doc/04-schema.md#extra) field that could be of use.

**Comment by Srokap** [comment]
I'm fine with any way of storing it, no matter if it's manifest.xml, composer.json or even package.json.

**Comment by brettp** [comment]
To the question, I'd rather have it injected into a plugin object and not be global. This encourages better plugin design. What are the use cases for having a global locator?

**Comment by mrclay** [comment]
Use case for global locator is anywhere we can't inject it. E.g. global function event handlers.

**Comment by brettp** [comment]
Actions are another one. 

Why not both? Injecting into a plugin object would help with testability, and we'd still keep the flexibility non-injectable situations.

**Comment by mrclay** [comment]
Yep, inject in new APIs, elgg() anywhere. We also need to determine:

- Which services will remain "private"?
- Will private services live in the same container? e.g. as `->_configTable`
- Which services must be split into a public/private pairs?
- Or are we willing to have public services with `@internal` public methods? See https://github.com/Elgg/Elgg/issues/7714#issuecomment-67784261

**Comment by mrclay** [comment]
Right now Application (#8247) *composes* our SL but at least @Srokap is interested in making *it* the SL. With this design I think we'd move much of the guts of Application into a "core" or "boot" object. So you'd `(new Elgg\Application)->core->boot()` to boot up Elgg. I think that's probably cleaner than having Application handle both booting and service location.

**Comment by Srokap** [comment]
I don't want to make Elgg\Application the DIC itself, rather something like

```php
class PluginInitClass implements Elgg\Plugin\InitInterface {
    function __constructor(Elgg\Application $app) {
        $app->services->hooks->registerHandler('init', 'system', array($this, 'init'))
    }

    function init() {
        // usual initialization code
    }
}
```
Though it's questionable if it makes any sense to not inject "services" directly and be done with it. We will be already during plugins load, so no point in giving devs ability to trigger it by having Elgg\Application. I don't imagine other uses now, so perhaps plain DIC will be enough.

As for publicity of the services, I'd like to have two separate groups, internal and public, where public could be just facades to internal ones that either return instance from _elgg_services() via factory, or return object that additionally limits the methods that are public. In perfect situation using of private api would not be possible through the public DIC.

**Comment by ewinslow** [comment]
I like that this is getting attention and discussion. Hope this can make it in soon.

Like the idea of having service-location + DIC going forward. Seems like a good migration path.

**Comment by mrclay** [comment]
#8273 seems like a simple solution. We'd just selectively expose keys off the service provider.

**Comment by mrclay** [comment]
We've got a direction to work with now.
