### ISSUE TITLE
sorting input/select

### ISSUE THREAD

**Issue by twentyfiveautumn** [Elgg/Elgg#8241]
I've added a small bit of code to input/select that sorts the options in alphabetical order and always puts the selected option at the top. For both $options and $options_values.

I'll do a PR on it if there is any interest...

**Comment by mrclay** [comment]
Having the selected element at the top isn't always desirable, and I'd expect the view user to give the options in the order they want. Plugins can also re-order via the [view_vars, input/select] plugin hook.

**Comment by twentyfiveautumn** [comment]
Thanks @mrclay
