### ISSUE TITLE
modifying menus on prepared plugin hook

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8255]
Hello,
I registered a menu and try to modify some parameters of its items on prepared plugin hook in some other plugins. According to the codes blow: 
```php
$menu = elgg_trigger_plugin_hook('register', "menu:$menu_name", $vars, $menu);

$builder = new \ElggMenuBuilder($menu);
$vars['menu'] = $builder->getMenu($sort_by);
$vars['selected_item'] = $builder->getSelected();

// Let plugins modify the menu
$vars['menu'] = elgg_trigger_plugin_hook('prepare', "menu:$menu_name", $vars, $vars['menu']);
```
after the last line we don't have anything to apply last changes; such as changing the 'selected_item' using the modified menu or changing "section" of a menu item or etc.

I think we need an update function in "ElggMenuBuilder" class.

**Comment by mrclay** [comment]
Why not make those changes in the "register" hook? The "prepare" hook is a kind of a "last call for adjustments". I think it would be pretty costly to analyze the menu at that point.

**Comment by SirbitoX** [comment]
from the documentations: 
>prepare, menu:<menu_name>
>    Trigger by elgg_view_menu(). Used to sort, add, remove, and modify menu items.

So I think the "prepare" hook is used when we need a minor adjustment like the example I mentioned before. Using "register" hook to adjust a menu item in other plugins isn't a dirty way??

**Comment by juho-jaakkola** [comment]
No, it's not considered dirty.

**Comment by jdalsem** [comment]
Closing this as it is more of a question (which was answered) than an issue
