### ISSUE TITLE
Travis can't connect to DB

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8265]
I waited for Travis to revert their .org builds, but still all our builds fail, seemingly due to MySQL. I'm rerunning successful builds on some old branches to see if it's a new code problem:
1.11: https://travis-ci.org/Elgg/Elgg/builds/60137415
1.10: https://travis-ci.org/Elgg/Elgg/builds/58797808
1.9: https://travis-ci.org/Elgg/Elgg/builds/46787670

cc @Elgg/owners

**Comment by mrclay** [comment]
Both 1.9 and 1.10 branches build fine. Must be something in 1.11.

**Comment by Srokap** [comment]
It seems to pass on 1.11 as well https://travis-ci.org/Elgg/Elgg/builds/60709318

From what I can tell, it's a MySQL issue itself. We get error saying that the server has gone away, so it's unlikely that it originates from our code.

**Comment by mrclay** [comment]
Seems like Travis resolved something on their end.
