### ISSUE TITLE
1.x problem with nginx config  

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#8270]
1. install fresh installation of 1.11.1 using nginx and mysql.
2. when viewing the site, the browser (firefox) produces error messages in the console that show that reportedcontent.js and languages/en.js cached files are missing. the result is that javascript fails on all pages.

```
GET 
http://dev.11.ureka.org/cache/1430489025/default/js/languages/en.js [HTTP/1.1 404 Not Found 1ms]
GET 
http://dev.11.ureka.org/cache/1430489025/default/js/elgg/reportedcontent.js [HTTP/1.1 404 Not Found 128ms]
Error: Script error for: languages/en
http://requirejs.org/docs/errors.html#scripterror require-2.1.10.min.js:8:251
Error: Script error for: elgg/reportedcontent
http://requirejs.org/docs/errors.html#scripterror
```

i raised this in the community and got no response. i am not able to do any coding with elgg until this is resolved. i have used the nginx rewrite configuration that is included with elgg and so far have not seen any problems other than this one.

**Comment by mrclay** [comment]
Are *any* of the `/cache/*` files loading?

**Comment by mrclay** [comment]
And anything in your server's error log?

**Comment by propertunist** [comment]
yes, some files are loading from the cache path - such as css/js.
the server log contains only a pair of entries, one for each of the files i mentioned. (i have disabled repeating errors in the ini files for the server). the entries just reflect the browser errors by saying that the files could not be found at the path defined by the cache route.

**Comment by propertunist** [comment]
i have got elgg sites running locally here, successfully, from the 1.8, 1.9 and 1.10 series.. but both of the 1.11 releases are failing with the same type of javascript errors.
a similar error is produced in 1.11 series sites when i enable the developer plugin.

**Comment by mrclay** [comment]
It sounds like nginx is not forwarding the requests to PHP. Is your config [fairly standard](http://learn.elgg.org/en/1.11/intro/install/nginx.html)?

**Comment by propertunist** [comment]
i have used various versions of the nginx config.. from very basic, to more advanced. i got the same result every time.
i have just downloaded 1.11.2 and i can run it fine.

**Comment by propertunist** [comment]
aha! i just found the cache directives that were causing this problem in the nginx configuration file.

i have no idea why these are a problem in 1.11.x and not in earlier versions though. does anyone know?
```
        location ~* \.(css|js)$ {
            expires 24h;
            add_header Cache-Control "public";
    }
```

**Comment by dipenpatel235** [comment]
I have faced same error then i have comment  one line and append below line.
see below example and after that it is fine to me .i am using elgg 1.11

        location /cache {
#                rewrite ^/cache\/(.*)$ /engine/handlers/cache_handler.php?request=$1&$query_string;
                rewrite ^/cache/(.*)$ /engine/handlers/cache_handler.php?request=$1 last;

        }

**Comment by mrclay** [comment]
Problem still in 1.12: https://github.com/Elgg/Elgg/blob/1.12/install/config/nginx.dist

**Comment by dipenpatel235** [comment]
yes....because in that required to change 
"location /cache {"      replace By  "location ~ ^/cache/ {"

**Comment by jdalsem** [comment]
In Elgg 2.x this file was updated and the cache line is no longer present
