### ISSUE TITLE
Convert JS AMD/Async

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8281]
Views from #8275:
- [x] ckeditor/init: From this view it looks like CKEDITOR_BASEPATH must be a global var defined before ckeditor is loaded.
- [x] theme_sandbox/modules/widgets
- [x] notifications/subscriptions/collections
- [x] notifications/subscriptions/forminternals
- [x] notifications/subscriptions/jsfuncs
- [x] zaudio/audioplayer
- [x] core/friends/collection
- [x] core/friends/collectiontabs
- [x] core/friends/tablelistcountupdate
- [x] input/autocomplete
- [x] input/friendspicker
- [x] page/walled_garden

Stuff found via elgg_register_js():
- [x] lightbox
- [x] $ autocomplete stuff
- [x] elgg.friendspicker
- [x] elgg.avatar_cropper
- [x] $ imgareaselect
- [x] elgg.ui.river
- [x] elgg.admin
- [x] elgg.upgrades
- [x] jquery.editable
- [x] elgg.embed
- [x] elgg.discussion
- [x] elgg.thewire
- [x] elgg.walled_garden

**Comment by hypeJunction** [comment]
Re: ckeditor. I have implemented some of my thoughts here: https://github.com/hypeJunction/ckeditor_addons. I needed a way to serve alternative configuration based on who is logged in.

**Comment by ewinslow** [comment]
I believe we decided this was not worth all the BC breaks for 2.0

**Comment by hypeJunction** [comment]
I have converted the lightbox to an AMD module. We can get it done with BC breaks.
https://github.com/hypeJunction/elgg_lightbox

**Comment by jdalsem** [comment]
checked all todos
