### ISSUE TITLE
Drop https login

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8282]
Was just chatting with @juho-jaakkola  and we concluded that https login feature doesn't do anything but mislead people. It doesn't add any security in case the connection is intercepted before the page is served, you can still submit the form insecurely by manually changing the scheme in the form action etc.
We propose to drop it entirely, and document that production sites should *always* be deployed behind https.

**Comment by mrclay** [comment]
SGTM

**Comment by beck24** [comment]
+1

**Comment by ewinslow** [comment]
This is a duplicate. Definitely agree, though.

**Comment by ewinslow** [comment]
#5729
