### ISSUE TITLE
Decide on interface name conventions

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8293]
Options:

 1. NameInterface (@hypeJunction, @beck24)
 2. IName
 3. Name (@ewinslow, @mrclay, @juho-jaakkola)

**Comment by hypeJunction** [comment]
1.

**Comment by ewinslow** [comment]
@Elgg/owners

We need to get this resolved once and for all so we can move forward on some PRs.

My opinion is that interfaces are the only identifiers that get to be excused from containing some implementation details in their name.

Class names should contain some implementation details because that is what classes are: implementations.

I contend that if we name interfaces like "NameInterface" or "IName" then we will encourage concrete classes with undescriptive names like "Name" just because they're the "first" or "default" implementation of an interface.

**Comment by beck24** [comment]
I vote for 1

**Comment by ewinslow** [comment]
@hypeJunction @beck24 any particular reasoning?

**Comment by hypeJunction** [comment]
It looks like camelCase with an l (L) in front. Plus it's easier to read
and register with your eyes

**Comment by ewinslow** [comment]
I'm thinking of the case where we have plugins using DI and type hinting on our interfaces.

With option 1, we end up with this:

```php
class SomeService {
  public function __construct(ConfigInterface $config, DbInterface $db, InputInterface $input) {}
}
```

Personally I'd much rather have folks writing this:

```php
class SomeService {
  public function __construct(Config $config, Db $db, Input $input) {}
}
```

I don't understand your point "It looks like camelCase." What makes the Interface suffix easier than no suffix at all?

Thanks for disussing this rather insignificant but oh-so-important issue of naming conventions (Naming things is the hardest thing in computer science...).

**Comment by ewinslow** [comment]
Strong arguments in favor of the suffix:

 * PSR uses Interface suffix
 * Symfony2 standards require Interface suffix

But I'd still like to know why the suffix is desirable in the first place.

**Comment by hypeJunction** [comment]
Option 2 looks like camelCase that start with an L in lower case, so it's hard to read.
Option 3 is fine to me, but I imagine we are going to end up with abstract/concrete classes inheriting the interface name, so it will be confusing when ```class Config implements Config```. I suppose, if we are going to use a namespace for interfaces, option 3 should be acceptable with ```class Config implements Interfaces\Config```

**Comment by ewinslow** [comment]
I guess I'd argue that this conflict is positive because it encourages us to come up with more descriptive names like InMemoryConfig, SqlBackedConfig, MixedBackendConfig, etc. I.e. describe the implementation somewhat in the name of the class doing the implementing.

**Comment by mrclay** [comment]
I've switched my vote to Name for the simplicity in user code. In practice we can use something like `use Elgg\Services\Config as ConfigInterface` in our concrete classes to disambiguate, or just list the whole interface name.

Aside: I think it's important in the ServiceProvider to declare concrete classes in the `@property-read`s because internal Elgg core may need to call non-interface methods and we want IDEs to recognize them. The Application properties can list the interfaces.

**Comment by ewinslow** [comment]
@brettp @Srokap @jdalsem Any more thoughts/reasoning to consider?

**Comment by mrclay** [comment]
Should be noted that PSR-2 doesn't standardize "FooInterface", that's just an example valid class name. Also the massively popular Laravel uses "Vendor\Contracts\Foo".

I'm going to push forward with Elgg\Services\Name. Fairly easy to change later.

**Comment by ewinslow** [comment]
We have a majority listed in favor of option 3, and @hypeJunction has said he's ok with it, too.

If we don't hear from folks in 3 more days I think we will just consider "no suffix" to be the standard.

**Comment by mrclay** [comment]
FYI I've already merged https://github.com/Elgg/Elgg/commit/fac589b2c0a5502d02c967292fc166728742cef6. If we wanna change it I'm happy to help.

**Comment by hypeJunction** [comment]
I was looking through some of the existing API and we already use option 3
for some interfaces, e.g. Queue. I suppose we can just continue doing so.

**Comment by beck24** [comment]
I'm not strongly opinionated on it either way, what we have is fine

**Comment by ewinslow** [comment]
Sounds like this is decided then. Would be good to document it in our coding standards before we close this ticket.

**Comment by mrclay** [comment]
I'm starting to doubt this decision. I'm working on several PRs that expose interfaces and it's getting confusing to tell between, e.g., \Elgg\Services\AjaxApi\Response (interface) and \Elgg\AjaxApi\Response (concrete object passed to handler). Further, the "Services" namespace works for services, but most of our interfaces are probably not going to be services. I'm going back to preferring the simple \Elgg\ConfigInterface and \Elgg\AjaxApi\ResponseInterface, so the interfaces sit right next to the implementations.

**Comment by ewinslow** [comment]
This tells me we need to pick more descriptive names for the concrete
implementations.
