### ISSUE TITLE
break lines in comments of blog

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8294]
Hello,
Follow below steps:
1. Add a comment **with some break lines** to a "Full view" bolg
2. Now try to edit the comment and save it.
You see that the break lines have disappeared. This is because of the following codes in js/lib/comments.js file in root of elgg:
```javascript
if (json.status === 0) {
    // Update list item content
    that.$item.find('[data-role="comment-text"]').html(value);
}
``` 
We need to add a function like ```nl2br()``` function of php on ```value``` variable to change the ```\n``` to ```<br />``` element.
The ```nl2br()``` function of js is something like:
```javascript
function nl2br (str, is_xhtml) {
	var breakTag = (is_xhtml || typeof is_xhtml === 'undefined') ? '<br />' : '<br>';
	return (str + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + breakTag + '$2');
}
```
and the mentioned code of ```comments.js``` file should be modified as below:
```javascript
 that.$item.find('[data-role="comment-text"]').html(nl2br(value));
``` 
Is there any alternative way to fix this bug without changing the core libraries??

**Comment by hypeJunction** [comment]
Does this happen with CKEditor on?

**Comment by SirbitoX** [comment]
Yes.
I developed a plugin and replaced element of the comments (input/textarea) with "input/plaintext" in it to avoid loading CKEditor on comments, but the break lines disappeared again.
When I deactivated the CKEditor and the plugin which I developed, it works correctly.

**Comment by mrclay** [comment]
We need a JS port of autop, or simpler, re-fetch the content from PHP.

**Comment by mrclay** [comment]
Really fetching from PHP is the only way the author can get an accurate view of what others will see (autop, linkify, htmlawed, etc.)

**Comment by mrclay** [comment]
PR #8297

**Comment by SirbitoX** [comment]
@mrclay
Thanks.
