### ISSUE TITLE
API to extend widget context

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8295]
When using exact match widget layout, some helpful widget types are not available, as they are registered with an 'all' keyword.
We should either treat 'all' keyword as suitable for exact match, or add an API for plugins to easier extend widget context.

**Comment by jdalsem** [comment]
I would suggest we remove the support for 'all'. This causes a lot of problems if you have extra contexts besides the 'profile' and 'dashboard'. In core 'all' means it works on 'profile' and 'dashboard'. I would suggest deprecating 'all' and require registering for the exact contexts (and default in this case to `['profile', 'dashboard']`

**Comment by hypeJunction** [comment]
SGTM. I would default to `null` and use `default_widgets` hook (or whatever it was)

**Comment by jdalsem** [comment]
`all` has been deprecated in https://github.com/Elgg/Elgg/commit/341d94efd7c43fed934a3bcc03e25fbc61dc7c9f widgets now need to be registered explicitely
