### ISSUE TITLE
Using $jsonexport to produce json output has been deprecated

### ISSUE THREAD

**Issue by saeedsq** [Elgg/Elgg#8312]
Message: Deprecated in 1.9: Using $jsonexport to produce json output has been deprecated

Deprecated code usage in elgg core codes

File /mod/web_services/views/api/output.php, line 17
$jsonexport = $export; -> deprecated
You should use: 
echo json_encode($export);

**Comment by SirbitoX** [comment]
https://github.com/Elgg/Elgg/issues/8256
I didn't get the right answer!

**Comment by jdalsem** [comment]
Fixed with #8572
