### ISSUE TITLE
Once again language files fetched from Transifex with "non-allowed" language codes

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8316]
This time it's ro_RO.php. There are a few language files included in 1.11.1 (not checked earlier versions).

The code ro_RO is not included in the array of allowed languages (additionally the upper case letters are breaking consistency even if the code would be in the list of allowed languages). I guess the file should be named ro.php instead.

**Comment by iionly** [comment]
This is still an issue with Elgg 1.11.2...

**Comment by iionly** [comment]
Hopefully fixed by https://github.com/Elgg/Elgg/pull/8954.

**Comment by juho-jaakkola** [comment]
Yep. I've tested, and it changes ```ro_RO``` to ```ro_ro```.
