### ISSUE TITLE
elgg_define_js() affects the path of similarly named modules

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8317]
I was surprised to find that this:

``` php
elgg_define_js('ckeditor', [
    'src' => '/mod/ckeditor/vendors/ckeditor/ckeditor.js',
]);
```

affects how RequireJS looks for the module `ckeditor/foo`.

Instead of the `js/ckeditor/foo.js` view, RequireJS tries to load `/mod/ckeditor/vendors/ckeditor/ckeditor/foo.js`. It's a reasonable behavior but unexpected from our docs.

**Comment by ewinslow** [comment]
Indeed.

**Comment by jdalsem** [comment]
@mrclay is this still an issue?

**Comment by mrclay** [comment]
I think it was a ckeditor thing. Not an issue anymore.
