### ISSUE TITLE
AMD loading is slow

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8320]
One thing really apparent with #8319 is how slow AMD loading is once the number of modules starts to pile up. During development (without simplecache) it's extra painful.

RequireJS's optimizer doesn't work on URLs, so some sort of downloader step would be needed to go that route.

I still think pushing commonly used modules into js/elgg is a decent and straightforward way to optimize, but the `define()` calls have to explicitly include the module names for this to work. And some sort of API would make this cleaner.

**Comment by mrclay** [comment]
PR #8342 for 1.x

**Comment by mrclay** [comment]
Strawman 2: We start by offering 2 bundles named "home" and "not_home" (each becomes active on the appropriate pages). Plugins can add modules by appending to the array passed through the hook `bundle_amd, <bundle>`. If any modules are bundled, the page will get a synchronous script loading the view `js/elgg/bundles/<bundle>`.

**Comment by jdalsem** [comment]
Closing this as there is no clear way forward
