### ISSUE TITLE
Consider reverting #8280

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8321]
#8280 was long requested but I think @hypeMachine made good points that it doesn't gain you much in real world usage.

I'd kinda prefer to add a dead simple way to register a JSON service with the client-side handling that actions have. I'll try to PR that today.

**Comment by jdalsem** [comment]
i disagree on #8280 being not so useful. I have multiple plugins that could benefit from this fix as i now needed to created wrapper ajax views to use forms in ajax loaded content.

If you are going to make it even better... fine by me

**Comment by hypeJunction** [comment]
hypeMachine thinks it doesn't hurt if someone finds it useful. I personally avoid using ajax page handler, and serve content from a place I have control over, i.e. a plugins page handler (without a page shell, if xhr).

**Comment by mrclay** [comment]
Ha, mobile github pages don't autocomplere usernames. I used to go to http://hypem.com/ all the time.

**Comment by mrclay** [comment]
Preferred alternative: #8323

**Comment by ewinslow** [comment]
Realistically, are we going to revert that pr or can we just add a newer better way?
