### ISSUE TITLE
roles plugin warning

### ISSUE THREAD

**Issue by fatemejon** [Elgg/Elgg#8322]
Hello, 
I found this warning in roles plugins :

PHP WARNING:  "array_intersect(): Argument #2 is not an array" in file /var/www/honeybee/mod/roles/lib/roles.php (line 590),

PHP WARNING: "implode(): Invalid arguments passed" in file /var/www/honeybee/mod/roles/start.php (line 254), 

I think we should check the second argument to be an array to prevent releasing these warnings in both cases.

**Comment by jdalsem** [comment]
The roles plugin is not part of the Elgg bundled plugins. Please report this at the appropriate plugin repository (or plugin page on the Elgg community)
