### ISSUE TITLE
Proposal: JSON-only endpoints with client/server side collaboration

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8323]
(90% of this is [done](https://github.com/Elgg/Elgg/compare/master...mrclay:json_endpoint), but I figure it would be best to stop and get input here)

**Server side**

Create an endpoint via `elgg()->jsonEndpoints->register($name, $handler)`. ($handler can be a class name if it's invokable).

On a request for that endpoint, the $handler receives a single Api object with properties:

* elgg: the Elgg\Application object
* ttl: (int) How long the client can cache the response, default: 0

If the handler returns a symfony Response object, we set the expires (if non-zero) and `send()` it.

Otherwise, we pass the return value through a `[jsonResponse, $endpoint_name]` hook (for plugin collaboration), wrap the value to encapsulate system messages, and turn it into a JsonResponse.

**Client side**

An AMD module provides a class `Endpoint(name)` with methods to `fetch` a value and `load` it into a jQuery-wrapped `$target`, both automatically using `elgg/spinner` by default.

Before you receive the data, the system messages container is processed and removed, and the data is filtered through the client hook `[jsonResponse, $endpoint_name]`. We could have an Endpoint method `listen` to simplify registering listeners created by other plugins.

To simplify, there are no URL segments, just a `data` object sent in the fetch options which is accessed via `->input` server-side (query string/POST body).

While fetching, you can set `data.response_ttl` to preset the TTL of the response. I've found this quite useful in the past.

**Comment by mrclay** [comment]
Goal is to make it dumb easy to define and use endpoints without the gotchas/magic of our ajax views and actions.

**Comment by ewinslow** [comment]
Can you write up some more complete docs with code samples that focus first on the developer experience? You've explained a lot here and after reading the code and your description twice I think I've got it, but some code samples would probably help I think...

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/issues/8373#issuecomment-105994096 there's a use case for allowing the response to send the client a list of modules to require().

**Comment by mrclay** [comment]
WIP #8391

**Comment by mrclay** [comment]
Better: #8402

**Comment by mrclay** [comment]
Note the goal of this ticket has shifted away from creating new endpoints and is now to add the richer Ajax experience to all the existing request handlers in a BC way.

**Comment by mrclay** [comment]
#8402 is the way to go.

**Comment by mrclay** [comment]
#8955 is updated for 2.x
