### ISSUE TITLE
account dropdown in Chrome

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8324]
The account dropdown in the topbar (top right) isn't working in Chome. In Firefox I don't have any problems.

The dropdown shows up, but if i move my cursor to go to one of the menu items the dropdown disappears?!

**Comment by iionly** [comment]
Elgg version used? Aalborg theme or default theme?

It works for me on Elgg 1.11 without issues both on Aalborg theme and default theme.

**Comment by jeabakker** [comment]
Elgg 1.11.1 (and elgg 1.11 branch from github) and Aalborg theme

**Comment by mrclay** [comment]
Can't duplicate. Maybe investigate using the inspector?

**Comment by jeabakker** [comment]
i can't reproduce it anymore.
Maybe fixed in the mean time, or a issue with my 2 installations?
