### ISSUE TITLE
Switch to alameda from requirejs

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8326]
https://github.com/requirejs/alameda#api

Seems like it is more modern-browser friendly and since we only officially support IE10+, seems like the way to go. Also, comes with a basic Promise implementation so we can do:

```js
var Promise = require('Promise');
```

to support IE which doesn't have native promises yet. Once IE gets native promises we just delete that line, or perhaps never really have to delete it since `prim` would surely just set its export to be equal to the native browser promise.

**Comment by ewinslow** [comment]
It's also substantially smaller, so performance.

**Comment by mrclay** [comment]
I'm not sure the gain from switching is worth forcing a lot of devs to manually switch back to RequireJS for IE9 users. Plus we already have [$.Deferred](https://api.jquery.com/category/deferred-object/). We could wrap it in a simple Promise module if really necessary.

**Comment by ewinslow** [comment]
I don't think theyd have to switch back. Perhaps theyd just need to provide some polyfills for older browsers.

**Comment by ewinslow** [comment]
Or we could provide the polyfills

**Comment by ewinslow** [comment]
E.g. https://cdn.polyfill.io/v1/docs/ is trivial to add.

**Comment by ewinslow** [comment]
Not that important right now
