### ISSUE TITLE
Pages plugin - deprecated write_access

### ISSUE THREAD

**Issue by slyhne** [Elgg/Elgg#8327]
In Elgg 1.11.1 I get this warning when creating a top-level page:

WARNING: Deprecated in 1.11: The input/write_access view is deprecated. The pages plugin now uses the ['access:collections:write', 'user'] hook to alter options. Called from [#14] /home/devk/www/mod/pages/views/default/input/write_access.php:5<br /> -> [#13] /home/devk/www/engine/classes/Elgg/ViewsService.php:391

At least core should be free of deprecated messages :-)

**Comment by yelloff** [comment]
Same for 2.0-rc1

**Comment by mrclay** [comment]
PR #9152

**Comment by mrclay** [comment]
On second thought, this behavior is intentional in 1.x. If a plugin has overridden/extended input/write_access, we still want it used. It should be removed in 2.0.
