### ISSUE TITLE
Firefox has long FOUC on master branch

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8328]
With simplecache this is mostly a first-load or manual refresh issue, without it's every page load.

**Comment by mrclay** [comment]
PR #8329

**Comment by mrclay** [comment]
I believe Firefox is, unlike other browsers, not treating CSS as a [render-blocking resource](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css?hl=en), so it will happily start rendering before the CSS loads...at least if there's no script element following them. Moving a script below the CSS links causes FF to stop and wait for the CSS.

@stevesouders have you written about this? I surely got this trick from you.

**Comment by mrclay** [comment]
Created a test page and my statement above isn't true generally, but is definitely happening with Elgg at the master branch. Raw HTML then re-rendering once the CSS arrives. Strange.

**Comment by mrclay** [comment]
`<script></script>` below CSS: FOUC
`<script>;</script>` below CSS: No FOUC!

**Comment by Yepoleb** [comment]
Thanks for this fix! Used it in my own project.

**Comment by ernestbuffington** [comment]
In the metatags plugin that I installed...

In the file itself metatags.php

Is there any reason if the $site_name is in the title of a post that it would be removed? Ex. https://politicalexchange.network/blog/view/283/the-politicalexchange-network-has-gone-online

It removed the word "developerExchange" from the metatag. If I put a space between political and Exchange it goes away.

This piece of code is creating the meta tag but it is striping out the site name if it exists.

```
<meta property="og:title" content="<?php
$title = trim($title);
if (strpos($title, '- ') == 0) {
    $title = str_replace('- ', '', $title);
}
echo $title;
```
I really do not see where it could be doing this or I would have removed whatever piece of code was doing it. Any help would be awesome. Thanks
