### ISSUE TITLE
Add a "lightDb" service for incomplete boot operations

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8330]
Lots of plugins are creating their own mysql connections to get simple things like dataroot. master allows getting the DB instance before full boot (we use this for cache handler), but we're about to migrate to Doctrine DBAL inside Elgg\Database so this will be much heavier.

Would be nice to offer a `lightDb` service that gives you a super minimal reading only API without loading DBAL.

**Comment by ewinslow** [comment]
Do you mean lighter for perf, or a lighter api, or both?

**Comment by mrclay** [comment]
Perf primarily but I less code to maintain would be best.

**Comment by mrclay** [comment]
@hypeJunction would a lightweight way to grab config/datalist values work for you? Like elgg_get_config during the boot phase does. Ideally our HMAC API should work identically.

I'm not going to put time into this until we get more use cases from plugin devs.

**Comment by hypeJunction** [comment]
I believe so. The only use case I have for reading anything from the DB without booting is to get datalist values.
https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/Servers/Server.php

**Comment by hypeJunction** [comment]
FYI, I got tired of maintaining 4 different versions of each plugin for each Elgg version, so I am bootstrapping and shimming all my plugins to work across all Elgg versions since 1.8

**Comment by mrclay** [comment]
Just use composer to pull in the whole Elgg 1.11 for your shims :smile:

**Comment by hypeJunction** [comment]
ROFL. I could do that, but that it would be a bit drastic. So far I only needed a few core classes. For JS and notifiations, I check the versions explicitly, and use the relevant logic.

**Comment by jdalsem** [comment]
Do we still need this? With the latest changes for generic file and icon handling, i do not see the need for any work on this. Also booting Elgg is not that costly anymore as it used to be

**Comment by mrclay** [comment]
I'd like to keep this on my radar for future refactoring.

**Comment by jdalsem** [comment]
No refactoring happening any time soon
