### ISSUE TITLE
Argument 2 passed to elgg_extract() must be of the type array, null given

### ISSUE THREAD

**Issue by fatemejon** [Elgg/Elgg#8333]
Hello, 
I get this warning in Elgg engine :
 ```php
PHP WARNING:  (IRDT): "Argument 2 passed to elgg_extract() must be of the type array, null given, called in /var/www/elgg/engine/lib/comments.php on line 280 and defined" in file /var/www/elgg/engine/lib/elgglib.php (line 1246), referer: http://localhost/members/expert_request
```
Is it an important issue or not? Should it be fixed?
Thanks.

**Comment by juho-jaakkola** [comment]
Seems like this might actually be a core bug https://github.com/Elgg/Elgg/blob/1.11/engine/lib/comments.php#L280

This is not an error but just a warning, so it is not that important. It should get fixed nevertheless.

**Comment by fatemejon** [comment]
thanks again .

**Comment by mrclay** [comment]
PR #8385
