### ISSUE TITLE
Rich Text Editor's Link dialogue doesn't work within lightbox

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8335]
You can't focus on text inputs. This is a [known bug in jQuery UI dialog](http://bugs.jqueryui.com/ticket/9087), but the proposed solution didn't work for me.

**Comment by jdalsem** [comment]
Any specific browser you have this issue with? Can't reproduce this with Firefox

**Comment by jdalsem** [comment]
Closing this as i can not reproduce this
