### ISSUE TITLE
Make forward() testable

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8338]
Problem: forward() always exits.

Strawman: Make an Elgg\ForwardingException that can hold location if available. forward() throws this and core catches it, sending the header and exiting. Tests can catch and inspect the location and state.

Issue with above: user code could catch that exception, but at least it jumps execution safely out of the active scope.

**Comment by mrclay** [comment]
#8397

**Comment by jdalsem** [comment]
actions and the forward behaviour can be tested (#11309)
