### ISSUE TITLE
Async elgg/echo module

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8345]
Strawman: require-ish front end

```js
var echo = require('elgg/echo');

// static strings only
echo(function(echo){
    alert(echo("foo:hello", username) + ". " + echo("foo:greeting"));
});

// allows dynamic keys
echo(["foo:location", "foo:" + area], function (location, area) {
    alert(location() + ": " + area());
});
```

Backend we split language files into "packs". A pack is a named list of simple patterns, which identifies the language keys within. All keys unmatched by any pack end up in the `_rest_` pack. A plugin can register a new pack name, but the list of patterns is built by plugin hook. The echo module has knowledge of these packs and so knows which to request to meet the dependencies. The request may be AMD-ish (module "elgg/lang-packs/en/PACK") but we could roll our own if necessary.

cc @ewinslow

**Comment by mrclay** [comment]
We could potentially lean on [RequireJS's i18n](http://requirejs.org/docs/api.html#i18n) module to load packs, but I don't think we want end user modules to worry packs.

**Comment by mrclay** [comment]
PR #8350

**Comment by ewinslow** [comment]
So I really like the idea of making `elgg/echo` its own thing. That is a no-brainer.

The exact async api here for getting individual language strings, though, I'll have to noodle on. It's similar to AMD, so that's a positive, but I feel like the main downside is the extra asynchronicity inside the module. Seems like the standard way that AMD wants you to deal with this special dependency is via loader plugin:

```js
define(function(require) {

// static strings only
var hello = require('elgg/echo!foo:hello');
var greeting = require('elgg/echo!foo:greeting');
var location = require('elgg/echo!foo:location');

alert(hello([username]) + ". " + greeting());

// callback require syntax allows dynamic keys
require(["elgg/echo!foo:" + area], function (area) {
    alert(location() + ": " + area());
});

});

**Comment by mrclay** [comment]
It's verbose, but readable. Seems like we should be moving away from direct translator usage toward some sort of templating that has that built in.

Wild idea: 

1. we provide the loader form as you describe. For now it's dumb and just loads the whole language file
1. module elgg/legacy-echo depends on our current languages file and returns the current synchronous form of elgg.echo. This gives a more direct path to upgrading JS to AMD.
1. An advanced site option allows js/elgg to **not** block on languages, but instead load it async. Include a stern warning and link to docs.

I get the impression that core seldom if ever needs echo on page load and where it is being used we can rewrite easily. Seems like this would make development with simplecache off so much faster loading.

**Comment by mrclay** [comment]
Forgot to mention: the core is that we can promise the AMD stuff in 1) and 2) will always work, but the legacy elgg.echo might fire too early if setting 3) is enabled.

**Comment by mrclay** [comment]
...instead of legacy-echo we add a function argument to elgg.echo that makes it async.

**Comment by ewinslow** [comment]
Option 1 seems good to me. Api allows us to optimize later.

**Comment by ewinslow** [comment]
This will be yet another BC break for 2.0... Performance gains are with it though, IMO. 1MB of JavaScript not downloaded is just huge...

**Comment by ewinslow** [comment]
According to http://requirejs.org/docs/plugins.html#api it should look something like this:

```js
// elgg/echo.js
define(function(require) {
  var vsprintf = require('vsprintf');

  return {
    load: function(name, req, onload, config) {
      // This is still the naive approach of loading the whole languages file for now
      // I suspect we need to switch to something like a falcor approach to avoid
      // emitting too many http requests
      req(['languages/' + config.locale], function(translations) {
        onload(function(args) {
          return vsprintf(translations[name] || name, args || []);
        });
      });
    }
  };
});
```

Usage looks like we discussed. Assuming you have this translation map:

```json
{
  "hello": "Hi, %s!"
}
```

You would include that translation string like so:

```js
define(function(require) {
  var hello = require('elgg/echo!hello');

  console.log(hello(['Steve']));
  // "Hi, Steve!"
});
```

**Comment by mrclay** [comment]
I've started work on this. What's "done" (untested) is the meat of the translation lookup module:
https://github.com/Elgg/Elgg/compare/Elgg:master...mrclay:echo_loader?expand=1#diff-99fb4e10fdca64994bc01e84cf63c8b0R1
It's a simple async key/lang lookup that auto-loads packs as necessary.

**Comment by mrclay** [comment]
New plan for backend loading. Packs are loaded via:
`"cache/$ts/_lang/$lang/pack/$name"`
If key doesn't match a pack, we load individually:
`"cache/$ts/_lang/$lang/key/$key"` where $key is encoded as a valid view name.

This eliminates ever having to download the huge "rest" pack, and allows piggybacking off the existing CacheHandler in the short term.

**Comment by ewinslow** [comment]
Sounds fine to me, as long as that url structure isn't hardcoded anywhere in plugin code. Don't see any reason why it would be, but might be good to be explicit that the exact URL itself is not part of the public api so people don't code against it.

**Comment by mrclay** [comment]
Loading arbitrary packs and keys is way messy. To keep it simple we should split the languages into two module. "critical" keys (selected by core and plugins) in an always required module, the rest in another.
