### ISSUE TITLE
Need more fine-grained notification settings

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8353]
Currently we have `get/set_user_notification_settings` which allows you to configure a user's notification settings by notification type (email, sms, site, etc.).

However, it seems like it would be useful to split these settings by channel/campaign. E.g. I want emails about "account_security" and "promotions" but sms for "new_messages" and "likes_on_my_content" but no notifications about "event_invites". So there is more control for users over what types of notifications get sent and how.

**Comment by juho-jaakkola** [comment]
Adding channels is an interesting idea. The issue #7859 has a similar approach but it doesn't group the subscriptions by type.

**Comment by juho-jaakkola** [comment]
Do you envision the channels as something that actually gets saved to the database? Or just a parameter that gets passed around the subscriptions system telling which of the detailed subscriptions data should get fetched from the database?

**Comment by ewinslow** [comment]
just a parameter.

**Comment by ewinslow** [comment]
Closing on favor of #7859 as it is more general.
