### ISSUE TITLE
Auto-load CSS/JS associated with views

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8373]
I was noticing the `dashboard/blurb` view:

```php
<div class="elgg-col elgg-col-2of3">
<?php 
	echo elgg_view('output/longtext', array(
		'id' => 'dashboard-info',
		'class' => 'elgg-inner pam mhs mtn',
		'value' => elgg_echo("dashboard:nowidgets"),
	));

?>
</div>
```

It has a corresponding css view, `dashboard/css`:

```css
#dashboard-info {
	border: 2px solid #dedede;
	margin-bottom: 15px;
}
```

Seems like we could cut down on some boilerplate and encourage modular development practices here. Suppose the css view were named `dashboard/blurb.css` instead. Then Elgg could detect that there is a CSS file corresponding to this view and load that on the current page whenever the view is rendered.

Currently `dashboard/css` is registered to extend `css/elgg`. In general this seems bad because you're paying the cost of the css for all pages even though you only need it when the corresponding HTML is included (i.e. very few pages).

If we went with the convention, the directory would look like this:

```
views/
  default/
    dashboard/
      blurb.php
      blurb.css
```

This seems like a good thing to me. Much clearer and the parts that change together stay together.

The only rub is that we need to support loading css files outside the css/* directory. Hopefully this is not too hard to support...

...and of course it'd be cool to do all the same stuff with JS. In this case, a `dashboard/blurb.js` view would be auto-loaded, if it exists.

One place you can see this coming in *really* handy is the resources/* views. Pages often need custom CSS and/or JS. This would be a convenient way to automatically deliver those dependencies if present.

**Comment by hypeJunction** [comment]
At the end of the day, the only way to be sure your CSS is loaded on ajax
requests is to extend css/elgg.

**Comment by mrclay** [comment]
Require can use a CSS file as a dependency. Mix this with the "attachBehaviors" approach I'm pushing and you have a full solution for Ajax.

**Comment by ewinslow** [comment]
@hypeJunction We could make it such that this works by spitting out `<script>require(['foo/bar']); require(['css!foo/bar'])</script>`. That way even `/ajax/view/foo/bar` would include the required JS and CSS when needed.

**Comment by ewinslow** [comment]
Actually, probably want to do so only on ajax/view requests, though, so that normal page loads can benefit from early triggering of CSS via <link> tags in head.

But anyways, I think moving toward little bundles of HTML/CSS/JS is the right way forward. I just never had the thought to do it like this until last night when I realized that what I wanted to do at a page level for the `resources/*` views could just be done for *every* view.

**Comment by mrclay** [comment]
Not crazy about auto-linking due to magic, but also because it won't work for ajax views. It could, however, work in the new ajax API I'm working up, by extending the data wrapper to notify the client.

We may want to check that the `.css` file isn't already extending css/elgg.

**Comment by mrclay** [comment]
Oh, I see you were going to add a SCRIPT to ajax views. Seems like require would need adjusted URLs like `../foo/bar` to pop out of the `js` basePath.

**Comment by ewinslow** [comment]
Other proposal was to lift everything out of the js/ base path for 2.0. Same with css

**Comment by ewinslow** [comment]
There's a little rub if you run sync and then async, I guess, which is that CSS is loaded with <link> in the one case and `require` in the other. So that will lead to duplicated stylesheets. Wonder how much difference it makes in practice, though... Hopefully well designed stylesheets can be loaded twice without issue?

**Comment by mrclay** [comment]
If we wanted to stick with the named CSS resources we have now, we could provide a module API to load those via ajax. I.e. `elgg_load_css()` client-side. That would help with https://github.com/Elgg/Elgg/issues/7895#issuecomment-73761276

**Comment by mrclay** [comment]
Related #8405

**Comment by hypeJunction** [comment]
I think we should go ahead with the JS part of this. Would definitely help with deprecating javascript and not having to figure out a BC way to extend a view to require the JS.

`

**Comment by mrclay** [comment]
For the magic route, `elgg_view_exists()` calls for non-existent views are cheap in 2.0. We would add hundreds of them.

I'd prefer manually registering via `elgg_require_for_view('view/name', 'module/name')`. Besides reducing API mystery, this allows re-using modules for various views.

**Comment by hypeJunction** [comment]
SGTM. I can tackle later in the week.

**Comment by hypeJunction** [comment]
@mrclay I am writing a test to test if the module was registered as dependency. I am injecting `\Elgg\Amd\Config` into views service, but that's not going to work for tests since it doesn't use `_elgg_services()`. Any workarounds?

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/pull/9562#discussion_r57350836 Seeing this in action makes me think this feature isn't so great. While views calling `elgg_require_js()` isn't ideal, it makes readers of the view more clearly aware of the dependency, and allows them to override it easily.

It seems our recent motivation for this is updating views in 2.x in a BC way, but we can pretty reliably do that with elgg_extend_view, or a view_vars hook handler.

**Comment by mrclay** [comment]
We can mitigate this somewhat by documenting the dependency in the view's phpdoc. I guess I wonder what big gain this gives us, for the cost of maintaining more code.

**Comment by hypeJunction** [comment]
Well, I think the point Ewan was making is to use magic to load the dependencies. So, we can scrap the public API and use it internally to do the magic. I would be happy with that.

**Comment by mrclay** [comment]
Yeah, I think that would be an improvement, but it's still API that has to be supported forever.

There's a bigger problem with the magic though: A 2.0+ plugin may already have views `foo.php` and `foo.js` but we have no idea if that `foo.js` is AMD and if it is whether it's safe to require.

**Comment by hypeJunction** [comment]
Let it sit for a bit. We can use view extensions for BC tickets, and merge this in later if there is a general feeling it's an improvement.

**Comment by ewinslow** [comment]
I think the decision *not* to use the magic I initially requested is a good one. The point of this was to reduce boilerplate by encouraging a particular convention, but I no longer feel that is necessary. Explicit dependencies are a big win for maintainability.

**Comment by hypeJunction** [comment]
I am going to close this as I doubt we will get anywhere with it. We can reopen at later stage if someone has an itch.
