### ISSUE TITLE
Eliminate pagesetup event

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8374]
It's unwise to make assumptions about the state of the system based on a view being rendered. How soon can we do this?

- [x] deprecate pagesetup in 2.3 (#9727)

**Comment by mrclay** [comment]
In principle I'm not against delaying the registration of resources until we know that page is being created, but I'd prefer a manual elgg_setup_page() instead of implicit triggering.

**Comment by hypeJunction** [comment]
I think there has never been a clear understanding of what pagesetup event should be used for. It seems we have it for historical reasons, as it was used for menu registration. I can't think of many use cases for it now. Perhaps we should start by identifying what it's supposed to do, and then decide where and how to trigger it?

**Comment by mrclay** [comment]
cc @ewinslow. Strawman: deprecate it, fire it after "init", remove the binding to views.

**Comment by hypeJunction** [comment]
@mrclay I don't think your strawman is going to work. Pagesetup tends to sniff for both context and page owner, both of which can change when resource view is drawn.
I propose we deprecate it, and advise to use `init` hook for run-time login, `register` hooks for menu registrations, and `shell` hook to modify things before page is drawn.

**Comment by mrclay** [comment]
For 2.0 I suggest we trigger it on the 1st view **unless that view is a "resources/" view**, in which case we trigger on 2nd. This should duplicate 1.x behavior and eliminate a lot of bugs (and fixes like #9271 and #9322). /cc @juho-jaakkola

**Comment by mrclay** [comment]
PR #9440

**Comment by mrclay** [comment]
@hypeJunction your last comment sounds like a good plan.

**Comment by mrclay** [comment]
Seeking community comment: https://elgg.org/discussion/view/2476212/the-pagesetup-system-event-is-going-away

**Comment by mrclay** [comment]
Alternate plan: deprecate it, but whitelist core plugin functions from warnings. Pros: we move away from it, little core dev work, no new bugs trying to migrate old stuff.

**Comment by hypeJunction** [comment]
That sounds reasonable.  I don't mind keeping it around until we can safely remove it.

**Comment by mrclay** [comment]
I've updated #9727, which was already doing that.

**Comment by jeabakker** [comment]
page setup was removed with #10434
