### ISSUE TITLE
Clarify docs for register, user hook

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8377]
From the documentation "register, user" hook:
> Triggered after user registers. Return false to delete the user.

So, it is expected that this hook triggered in ```register_user($username, $password, $name, $email, $allow_multiple_emails = false)``` function and after registering the user successfully. Or at least this function should triggers another hook if the usage of "register, user" is different. This helps developers use this hook every where that ```register_user``` is called (register action, adduser action and etc).

**Comment by mrclay** [comment]
The docs should specify that the hook is triggered by the `register` action, not by the function.

Aside: You can cancel inside the function using the `create, user` event.
