### ISSUE TITLE
Should Elgg host a end-user plugin documentation website

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8379]
Next to a developers learn.elgg.org, why not provide a plugin documentation website? That site could also be hosted on readthedocs. We only need to find a good way so developers can keep the documenation in their own code, but have it combined/scraped to the centralized documentation site...

This is something a lot of end users could benefit from.

To keep some kind of quality control, elgg should host the central repo code and accept PR's to add the extra plugins. Plugins should have some form of standardized formating/structuring of the pages and a minimal set of pages/section that it needs to describe.

**Comment by mrclay** [comment]
Are you suggesting end user docs for the website (by plugin)?

**Comment by mrclay** [comment]
If so, I'd prefer tour integration (#5937 which @juho-jaakkola is close on), a page-level help feature (See WordPress's admin area), or some sort of inline help.

**Comment by ewinslow** [comment]
Added https://github.com/Elgg/Elgg/issues/8380 for the inline-help suggestion, which I like.

**Comment by jdalsem** [comment]
@mrclay i meant the by plugin documentation. We have multiple plugins that have, or should have, extended installation/admin documentation or have a large list of features that require instructions. It would be great to have it available on a centralized documentation site. If Elgg is not doing it, we will probably create such a site for ourselves, but something like this could benefit every dev/sysadmin/communitymaster or end user

**Comment by ewinslow** [comment]
But why a centralized site vs within Elgg admin area?

**Comment by jdalsem** [comment]
Because that requires you to install the plugin first to read up on its uses

**Comment by mrclay** [comment]
Good point!

**Comment by mrclay** [comment]
A standard for docs within plugins would also allow us to render those in the Community plugin repo (if it can be protected from XSS)

**Comment by ewinslow** [comment]
A good point indeed.

Yea, docs on community site sounds handy.

**Comment by jdalsem** [comment]
The idea is still a very good one, however i am closing this ticket as there is noone working actively on it
