### ISSUE TITLE
Require all simplecacheable views to have a filename extension

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8381]
The lack of an extension on views like js/elgg and css/elgg seems like the main reason we cannot have PHP-less routing of simplecached views. There is no way to have a filesystem that looks like so:

```
cache/12345678/default/js
  elgg # file
  elgg/ # directory
    dev.js
```

Note that this transition could be made in a 1.x plugin already, so authors wouldn't have to make this switch and upgrade to elgg 2.0 at the same time.

Can anyone think of a more automatic way to make this happen?

**Comment by ewinslow** [comment]
Lack of an extension also prevents seamless integration with AMD

**Comment by ewinslow** [comment]
This would unfortunately be a major breaking change that would break practically all plugins 1.8-style.

**Comment by mrclay** [comment]
So all simplecache views would basically be:
```
/views/default/foo
  bar.html(.php)?
  bar.js(.php)?
  bar.css(.php)?
```

I suppose we could implement a limited set of aliases so extending `js/elgg` would actually extend `js/elgg.js` and similarly for CSS.

**Comment by mrclay** [comment]
Wrong button.

**Comment by mrclay** [comment]
When you say "PHP-less routing" do you mean served by the HTTPd directly?

**Comment by mrclay** [comment]
If so I don't see that as must-have since the entire cache/ URL space is trivially cacheable via Varnish and other HTTP caches.

**Comment by ewinslow** [comment]
Yes, you have the right idea of what I'm going for.

Yes, served by httpd directly.

Varnish is a great point, and maybe that's a good enough reason to close this ticket.

If we do decide that, then there is no reason to block movement of all static assets including images to the views system.

I believe i recall @Srokap having concerns about this.

**Comment by mrclay** [comment]
Service through PHP also allows auto-minify, and I don't know how we'd direct HTTPds to the "correct" view location among the plugins.

**Comment by ewinslow** [comment]
This is something we need to make a firm decision on for 2.0
