### ISSUE TITLE
Allow aggregated CSS registration

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8388]
Currently, if a component requires multiple stylesheets, you have to register and load each one individually. It would be logical to group/aggregate them, imho.

Instead of:

```php

elgg_register_css('slick', '/mod/elgg_slider/vendors/slick-1.5.0/slick/slick.css');
elgg_register_css('slick-theme', '/mod/elgg_slider/vendors/slick-1.5.0/slick/slick-theme.css');
elgg_register_css('elgg.slick', elgg_get_simplecache_url('css', 'page/components/slider.css'));

elgg_load_css('slick');
elgg_load_css('slick-theme');
elgg_load_css('elgg.slick');
```

do something like:

```php
elgg_register_css('slick', [$path1, $path2, $path3,]);
elgg_load_css('slick');
```

**Comment by jdalsem** [comment]
Not a fan, as i can not overrule/reregister 1 of the 3 files this way...

**Comment by hypeJunction** [comment]
Good point. Didn't think of that.

**Comment by mrclay** [comment]
I don't think it's worth pouring more work into this API, but I think the right way to do this would be to declare some CSS resources as dependent on others.
