### ISSUE TITLE
Pull ColdTrick/plugin_manager improvements into core

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8412]
Nice work. https://github.com/ColdTrick/plugin_manager

@jdalsem @jeabakker

**Comment by beck24** [comment]
I believe this has been discussed and voted on before.  I was in favor, but we were outvoted by people opposed (I don't even remember the arguments against...)

**Comment by beck24** [comment]
ah, I was thinking of this thread: https://github.com/Elgg/Elgg/issues/3148

**Comment by mrclay** [comment]
Only suggestion would be remove the check icons and add an explicit [Enable]/[Disabled] button on the right. Toggling a plugin's state is an important operation that should look like taking a big action.

**Comment by ewinslow** [comment]
Agreed that pulling that stuff in would be a net improvement. Perhaps the Coldtrick guys would like to submit a PR?

**Comment by mrclay** [comment]
This would be good work for new-to-Elgg devs to dip their feet into.

**Comment by jdalsem** [comment]
i assume you do not want to pull this in via composer but just replace the current core plugin management features with the features of the plugin_manager plugin am i right? That may be not that easy for new devs, but i am willing to take this, so i am assigning it to me.

**Comment by mrclay** [comment]
Does the plugin work at any priority, ie doesn't override stuff from other plugins? It would be useful for core to be able to support "core" plugins that not only ship with Elgg but behave more like core functionality (can't be disabled, always starts before other plugins). I vaguely remember hearing this is how functionality is added to WordPress now.

**Comment by mrclay** [comment]
...ideally we could pull plugins in as a part of core and just remove the stuff they override.
