### ISSUE TITLE
Support plugins as core components

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8415]
There are cases where we want to bring in 3rd party plugins into core, but have them truly be part of core. ie we they startup with core, can't be moved or disabled, and maybe don't show up in the plugins list. Ideally don't add DB overhead...

We'd pull in, say, plugin_manager, via composer, and just remove the overridden stuff and unused code paths.

https://github.com/Elgg/Elgg/issues/8412

**Comment by mrclay** [comment]
Maybe they live in engine/mods to avoid confusion

**Comment by jdalsem** [comment]
Don't think this is something we will pursue any time soon
