### ISSUE TITLE
master: lightbox CSS broken

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8416]
It's registered to the js/lightbox.css view? @ewinslow

**Comment by ewinslow** [comment]
OK, that's something I can patch.

**Comment by mrclay** [comment]
For now let's roll this back to the 1.x CSS (in vendors). Reasons:
* none of the bower-asset example CSS match ours
* if we serve from views we'll have to rewrite the paths in the CSS or pull the images into views (and they'd live in `css/`).

**Comment by mrclay** [comment]
PR #8469. cc @jdalsem @jeabakker

**Comment by ewinslow** [comment]
(more confirmation that the css/ and js/ prefixes were mistakes). Ugh.

**Comment by ewinslow** [comment]
I'm fine with this. It's just unfortunate.
