### ISSUE TITLE
entity int columns don't return ints

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8417]
when asking `$entity->container_guid` this is not an int, but a string. `$entity->getContainerGUID()` is an int.

This applies to all entity int database columns. This was fixed for ->guid, but not the others in #4111

Should be fixed for all int columns

**Comment by jdalsem** [comment]
related / duplicate here #4136

**Comment by mrclay** [comment]
This should be take care of for int columns.

**Comment by jdalsem** [comment]
@mrclay why do you think this is fixed?

**Comment by mrclay** [comment]
I can't find the test for it, but see https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/AttributeLoader.php#L256

**Comment by jdalsem** [comment]
Yep, that looks like this is fixed!
