### ISSUE TITLE
master: new jquery-iu version can't be loaded synchronously

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8418]
The view file for jquery-ui.js was missing, but when I added it I get the dreaded Mismatched define() error, problem being, unlike jquery, jquery-ui define()s itself anonymously. Adding the explicit name "jquery-ui" to the source file fixes it, but obviously we need another solution. @ewinslow

**Comment by ewinslow** [comment]
Hmm... I thought I had restricted the version number appropriately but I
guess not.

We can revert to an older version that doesn't have this issue or we can
require people to load it with AMD or we can try to get a patch upstream
into jquery-ui.

Personally I'm in favor of the AMD route, but some may find that too
harsh...

**Comment by mrclay** [comment]
Patch with str_replace in the PHP file.

**Comment by mrclay** [comment]
PR #8422

**Comment by mrclay** [comment]
Another option, wrap content with this:
```js
!function(){
var define;

// code

}();
```
