### ISSUE TITLE
Ditch custom repositories in favor of actual bower/npm packages

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8420]
This custom repositories config needs to be copied to `elgg/starter-project` in order to install successfully. It'd be better just to drop them in favor of equivalent newer packages that are already registered with bower/npm.

```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "bower-asset/sprintf",
                "version": "0.7.0",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/alexei/sprintf.js/archive/v0.7.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-imgareaselect",
                "version": "0.9.10",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/odyniec/imgareaselect/archive/v0.9.10.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-ui-extensions",
                "version": "dev-master",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/scottgonzalez/jquery-ui-extensions/archive/fb7fd7df3d70e0288394f07bfe78262b548c30d6.zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "bower-asset/jquery-jeditable",
                "version": "1.7.3",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/tuupola/jquery_jeditable/archive/1.7.3.zip"
                }
            }
        }
    ],
}
```

**Comment by ewinslow** [comment]
I think we need to drop this before 2.0.0, even if it is a breaking change (removing libraries that exist in core). How would @Elgg/owners and @Elgg/contributors feel about whitelisting this as a breaking change that can go in after the freeze date? It significantly impacts the convenience of composer, IMO, by the fact that you cannot just `composer require elgg/elgg:2.0` in an existing plugin to get the Elgg classes and assets that you need in order to test your plugin in isolation.

**Comment by ewinslow** [comment]
I.e. this is one reason I wanted #7080

**Comment by hypeJunction** [comment]
I am fine with that as long as starter project lists them all.

**Comment by ewinslow** [comment]
But that's the issue I'm trying to fix. I don't want starter project to have to list them all.

**Comment by mrclay** [comment]
What is blocking this?

**Comment by ewinslow** [comment]
Life? ;)

We just need to pick alternate packages and rewrite existing usage to use the new libraries. Then we can ditch the custom repos.

Alternatively, we just check in the code for these 4 libs so they don't need to be downloaded through composer at all. That might be easier short term...
