### ISSUE TITLE
Declarative hooks and events registration

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8430]
Example of registering for the init system event:

``` php
<?php
// /mod/example/events.php
namespace Elgg\Blog;

return [
  'init' => [
    'system' => [
      Hooks\InitSystem::class => 500,
    ],
  ],
];
```

Example of unregistering a handler from the init system event:

``` php
<?php
// /mod/example/events.php
namespace Elgg\Blog;

return [
  'init' => [
    'system' => [
      Hooks\InitSystem::class => null,
    ],
  ],
];
```

Benefits:
- all handlers must be unregisterable, since they must be strings in order to be registered in the first place
- no need to think/teach about elgg lifecycle (init system) when registering hooks/events
- reduce clutter in start.php

Cons:
- yet another way of doing something the system already does
- improvement is only incremental and may not justify the effort?

**Comment by mrclay** [comment]
I considered this for a recent PR but both cons you list convinced me not to.

**Comment by ewinslow** [comment]
Btw I blew a couple hours today trying to figure out the interactions between pagesetup system and init system. It would be nice if that just went away.
