### ISSUE TITLE
Filter as sugar for passing a value through a plugin hook

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8433]
Hooks are great for making code collaborative but the syntax is ugh:
- `elgg.trigger_plugin_hook` and `elgg_trigger_plugin_hook` are both long
- requires 2 names for the hook/type and no one can agree on how to use these
- Params is the 3rd arg even though we often don't need it

I suggest adding a "filter" function with a more pleasant API:

``` php
$foo = elgg_filter('myPlugin:foo', $foo);
```

is the equivalent of:

``` php
$foo = elgg_trigger_plugin_hook('filter', 'myPlugin:foo', null, $foo);
```

This would reduce boilerplate and clarify meaning to encourage devs to make more values alterable.

This would also ease the pain of making module methods swappable:

``` js
require('elgg/booted'); // ensure hooks registered #8365
return {
  foo: elgg.filter('myModule:foo', function() {
    // default implementation
  })
};
```

**Comment by mrclay** [comment]
I'm not wedded to the name. I doubt "filter" would be conflated with list filtering.

**Comment by mrclay** [comment]
PR #8454

**Comment by mrclay** [comment]
I think asking for the plugin ID explicitly would be better (don't have to remember convention).

**Comment by jdalsem** [comment]
Closing this as i think we can live with the current naming and implementation. Reopen if you disagree
