### ISSUE TITLE
Remove add_translation() use in elgg_profile_fields_setup()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8437]
This seems like misuse of the translation system. Low priority.

**Comment by jdalsem** [comment]
What alternative are you thinking of??

**Comment by mrclay** [comment]
It's basically using the language system as a config hash, just for one page. It's also just confusing. We don't want plugins doing stuff like this.

**Comment by jdalsem** [comment]
It is not limited to one page... anywhere you need a 'translated' profile field you could potentially use it... groups also uses it.

This way you can use "profile:<fieldname>" anywhere on your site (even if those fields are dynamically created in the back end).
