### ISSUE TITLE
elgg_get_viewtype() checks get_input('view') for every view

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8438]
Boot should sniff input once and set $CURRENT_SYSTEM_VIEWTYPE accordingly, and users should use elgg_set_viewtype() for changing it.

We should remove the test that makes sure set_input('view') has an effect on viewtype.

**Comment by mrclay** [comment]
@ewinslow this could help offset perf costs in your views overhaul

**Comment by jdalsem** [comment]
PR was already made before... https://github.com/Elgg/Elgg/pull/7908

**Comment by mrclay** [comment]
@jdalsem Let me know if you don't have time to work on this. I'm happy to get this in.

**Comment by mrclay** [comment]
master PR #8663
