### ISSUE TITLE
Remove elgg_register_viewtype_fallback()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8439]
This was added in 1.7 and isn't used by core. Anyone using it? It complicates view rendering.

**Comment by hypeJunction** [comment]
I used it a few times to set fallback to default.

**Comment by mrclay** [comment]
Are those sites/plugins likely to be upgraded to 2.0? Would adapting to another solution be feasible?

**Comment by hypeJunction** [comment]
Likely not. Moved away from custom view types.

**Comment by ewinslow** [comment]
My original motivation was to allow viewtypes like "mobile" and "tv" without having to overwrite *every single view*.

**Comment by beck24** [comment]
Oh, I've used it quite a bit in a private project - found it useful for creating switchable sub-themes where only a few views needed to be overwritten

**Comment by mrclay** [comment]
This isn't blocking anything so let's leave it for now.
