### ISSUE TITLE
Add the event [cache_rebuild, system]

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8441]
Gives a clear path to caching tons of stuff: handlers for events, hooks, pages, actions, notifications; widget types, etc. The event would fire directly before [init, system] *only if* either of the simple/system caches were off or were being refreshed. It would pass in an API object with registration methods for the stuff we allow caching.

E.g. we could add registerPageHandler() to the API. Devs could then move their page handler registration out of the "init" event. The "init" event is still fired so uncached values could still be added/overridden.

Issues: This means a single boot up calling the event would be required to flush the caches, and we'd have to move all cache saving to directly after the event. Also, how would a plugin register for the event?

**Comment by mrclay** [comment]
Decent question is how expensive are these registration calls anyway? Would also involve work to adapt plugins and you'd only get benefit if a lot of plugins used it.

**Comment by juho-jaakkola** [comment]
Are there benefits with using a hook instead of e.g. reading the info from a file found in each plugin's dir?

**Comment by mrclay** [comment]
Not really. Would prefer them to use a given API though. We could give them a template to use:
```php
/* @var \Elgg\Services\CacheRebuild $api */

// use $api to register resources that don't change between requests
```

**Comment by jdalsem** [comment]
Do we really need something like this? We have a flush function to clear the cache. Cache will then (most of the time) be generated on first use... much better i think than generating all at once... And if you really need to regen a lot of content, you could also do so during flush
