### ISSUE TITLE
Blank page if view is missing

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8448]
In #8446 I only got a blank screen. I thought it was a WSOD and wondered why the error is not getting logged in the error log. But in fact Elgg was just not printing anything.

IIRC Elgg does check whether a view exists. Apparently a missing view just isn't getting logged anywhere.

**Comment by mrclay** [comment]
Besides missing the error, a blank page makes sense for a full page resource view. Kinda makes a case for a function like elgg_view_resource('foo') which always uses the `default` viewtype and handles a missing view somehow.

**Comment by ewinslow** [comment]
Another idea is to have a strict mode or something that turns on display_errors, throws exceptions on rendering a truly missing view, etc. Don't necessarily have to choose one or the other.

**Comment by ewinslow** [comment]
@mrclay Is this fixed now that we have `elgg_view_resource`?
