### ISSUE TITLE
crop avatar bug

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8449]
Hi,

Follow these steps:
* go to edit avatar
* upload a new picture
* use avatar cropping tool
* try to move the selected area

you can see that the selected area doesn't move! Perhaps, the reason is because of loading the relevant js files in header before loading the image file.

**Comment by juho-jaakkola** [comment]
Which Elgg version?

**Comment by SirbitoX** [comment]
I'm developing on last version of Elgg (1.11.2). I tested this issue on https://community.elgg.org and it didn't work correctly, either.

**Comment by juho-jaakkola** [comment]
I'm not able to reproduce the bug. I tested both with Firefox and Chrome.

**Comment by mrclay** [comment]
@SirbitoX what browser/version/OS were you using?

**Comment by SirbitoX** [comment]
@mrclay :
Chrome/Version 43.0.2357.124 m/Windows 7
Firefox/Version 38.0.5/Windows 7

@juho-jaakkola I emphasize that just for the first time you upload an image this bug appears. and if you refresh the page every thing would work correct.

**Comment by saeedsq** [comment]
I encountered the same issue. Chrome Version 43.0.2357.124 m, Windows 7
Here is the console error:
Uncaught Error: Mismatched anonymous define() module: function (a){function b(b){var g=b||window.event,h=i.call(arguments,1),j=0,l=0,m=0,n=0,o=0,p=0;if(b=a.event.fix(g),b.type="mousewheel","detail"in g&&(m=-1*g.detail),"wheelDelta"in g&&(m=g.wheelDelta),"wheelDeltaY"in g&&(m=g.wheelDeltaY),"wheelDeltaX"in g&&(l=-1*g.wheelDeltaX),"axis"in g&&g.axis===g.HORIZONTAL_AXIS&&(l=-1*m,m=0),j=0===m?l:m,"deltaY"in g&&(m=-1*g.deltaY,j=m),"deltaX"in g&&(l=g.deltaX,0===m&&(j=-1*l)),0!==m||0!==l){if(1===g.deltaMode){var q=a.data(this,"mousewheel-line-height");j*=q,m*=q,l*=q}else if(2===g.deltaMode){var r=a.data(this,"mousewheel-page-height");j*=r,m*=r,l*=r}if(n=Math.max(Math.abs(m),Math.abs(l)),(!f||f>n)&&(f=n,d(g,n)&&(f/=40)),d(g,n)&&(j/=40,l/=40,m/=40),j=Math[j>=1?"floor":"ceil"](j/f),l=Math[l>=1?"floor":"ceil"](l/f),m=Math[m>=1?"floor":"ceil"](m/f),k.settings.normalizeOffset&&this.getBoundingClientRect){var s=this.getBoundingClientRect();o=b.clientX-s.left,p=b.clientY-s.top}return b.deltaX=l,b.deltaY=m,b.deltaFactor=f,b.offsetX=o,b.offsetY=p,b.deltaMode=0,h.unshift(b,j,l,m),e&&clearTimeout(e),e=setTimeout(c,200),(a.event.dispatch||a.event.handle).apply(this,h)}}function c(){f=null}function d(a,b){return k.settings.adjustOldDeltas&&"mousewheel"===a.type&&b%120===0}var e,f,g=["wheel","mousewheel","DOMMouseScroll","MozMousePixelScroll"],h="onwheel"in document||document.documentMode>=9?["wheel"]:["mousewheel","DomMouseScroll","MozMousePixelScroll"],i=Array.prototype.slice;if(a.event.fixHooks)for(var j=g.length;j;)a.event.fixHooks[g[--j]]=a.event.mouseHooks;var k=a.event.special.mousewheel={version:"3.1.12",setup:function(){if(this.addEventListener)for(var c=h.length;c;)this.addEventListener(h[--c],b,!1);else this.onmousewheel=b;a.data(this,"mousewheel-line-height",k.getLineHeight(this)),a.data(this,"mousewheel-page-height",k.getPageHeight(this))},teardown:function(){if(this.removeEventListener)for(var c=h.length;c;)this.removeEventListener(h[--c],b,!1);else this.onmousewheel=null;a.removeData(this,"mousewheel-line-height"),a.removeData(this,"mousewheel-page-height")},getLineHeight:function(b){var c=a(b),d=c["offsetParent"in a.fn?"offsetParent":"parent"]();return d.length||(d=a("body")),parseInt(d.css("fontSize"),10)||parseInt(c.css("fontSize"),10)||16},getPageHeight:function(b){return a(b).height()},settings:{adjustOldDeltas:!0,normalizeOffset:!0}};a.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})}
http://requirejs.org/docs/errors.html#mismatch

**Comment by mrclay** [comment]
This working on page refresh suggests to me a race condition with JS loading.

Are there any JS/network errors in the devtools console?

**Comment by SirbitoX** [comment]
@mrclay 
No, there isn't any error in the console.
I think the JS relevant to cropping the image loads before loading the image completely and the JS could not detect dimensions of the image so it breaks. And on page refresh it works fine because the image has been cached by the browser (i.e. it loads immediately).

**Comment by SirbitoX** [comment]
@juho-jaakkola @mrclay 
Do you have any idea how to fix this?

**Comment by SirbitoX** [comment]
@juho-jaakkola @mrclay 
This issue will be fixed if the following codes in ``` \js\lib\ui.avatar_cropper.js ``` be wrapped by ```$(window).load(function () { ... });```:

```js
$('#user-avatar-cropper').imgAreaSelect(params);

if ($('input[name=x2]').val()) {
	var ias = $('#user-avatar-cropper').imgAreaSelect({instance: true});
	var selection = ias.getSelection();
	elgg.avatarCropper.preview($('#user-avatar-cropper'), selection);
}
```

the result should be something like this:
```js
$(window).load(function () {
		$('#user-avatar-cropper').imgAreaSelect(params);

		if ($('input[name=x2]').val()) {
			var ias = $('#user-avatar-cropper').imgAreaSelect({instance: true});
			var selection = ias.getSelection();
			elgg.avatarCropper.preview($('#user-avatar-cropper'), selection);
		}
	}
);
```

**Comment by mrclay** [comment]
PR #8541
