### ISSUE TITLE
CKeditor only works on reload

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8456]
https://github.com/Elgg/Elgg/issues/8413#issuecomment-111060895 and I swear I've experienced this too, but don't remember which branch. My guess: we're not making the dependencies explicit and so on when resources load immediately from cache, the order of execution is wrong.

**Comment by mrclay** [comment]
In general we need to test more thoroughly with Firefox/IE and with simplecache on/off

**Comment by jdalsem** [comment]
Still can't reproduce this issue

**Comment by jdalsem** [comment]
Closing as there is no way to reproduce the issue... or it resolved itself
