### ISSUE TITLE
Use canComment for discussion reply permissions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8458]
I have encountered a problem after filtering permissions to only allow group admins to create discussion topics, other users were not able to post replies.

This line here: https://github.com/Elgg/Elgg/blob/1.x/mod/groups/lib/discussion.php#L234 should perhaps be checking either canComment() or canWriteToContainer() on the topic, as ability to create new discussion topics is different from posting repies. Not sure if there are places where this needs to be changed.

**Comment by mrclay** [comment]
canComment() sounds appropriate.

**Comment by hypeJunction** [comment]
@juho-jaakkola Is this still an issue/

**Comment by juho-jaakkola** [comment]
Yes. The current code is just checking if user is allowed to write to the group, but not if user is allowed to post a reply to the discussion: https://github.com/Elgg/Elgg/blob/2.0/mod/discussions/views/default/resources/discussion/view.php#L41
