### ISSUE TITLE
AMD weirdness

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8465]
Something strange is happening with the following setup:

```php
elgg_define_js('dropzone', array(
	'src' => '/mod/hypeDropzone/vendors/dropzone/dropzone-amd-module.min.js',
	'deps' => array('jquery'),
	'exports' => 'dropzone',
));
```

View ```js/dropdzone/dropzone.js```, was calling:

```js
define(['elgg', 'jquery', 'dropzone'], function (elgg, $, dropzone) {
   // do stuff
});
```

Require was trying to fetch ```/mod/hypeDropzone/vendors/dropzone/dropzone-amd-module.min/dropzone.js```

Renaming the defined module to ```dropzone/lib``` solves the problem.

**Comment by mrclay** [comment]
What branch?

**Comment by mrclay** [comment]
I think you're getting bit by #8317

**Comment by hypeJunction** [comment]
1.11. Seems like it

**Comment by mrclay** [comment]
One workaround: name your module with custom src something like "dropzone-lib". So your modules containing "dropzone" aren't seen as descendants.

**Comment by mrclay** [comment]
Closing as dupe. If you've got ideas for warning other devs, share them in #8317
