### ISSUE TITLE
lightbox css not loaded correctly in master branch

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8466]
a lot wrong with line 1622 in lib/views.php... no time to figure out what it is...

**Comment by jeabakker** [comment]
introduced in https://github.com/Elgg/Elgg/commit/86f0a5d16d971078b118d95e2896ddf95d984c08#diff-5bbefe66200525a450e1eac0ebf4e21cR190

**Comment by mrclay** [comment]
Dupe of #8416
