### ISSUE TITLE
GaufretteDirectory::getFiles() is slow

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8467]
No matter your Directory path, `getFiles()` must scan the entire filesystem because it uses `Gaufrette\Filesystem::listKeys`. E.g. if you make a local filesystem at Elgg's root, even if you `->chroot()` into subdirectories, getFiles() will scan the entire Elgg filesystem including `vendor` and `.git`.

**Comment by ewinslow** [comment]
That is pretty bad indeed... thanks for catching it.

**Comment by mrclay** [comment]
PR #8495
