### ISSUE TITLE
Elgg\Filesystem\Directory needs a way to list only children

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8468]
getFiles() automatically returns the whole tree. Maybe add a `$recursive = true` argument?

**Comment by mrclay** [comment]
It's not even supported in Gaufrette's Local adaptor.
https://github.com/KnpLabs/Gaufrette/issues/175
https://github.com/KnpLabs/Gaufrette/pull/7#issuecomment-1257271

We'd have to extend their Local adaptor to add it. This is built into Flysystem: https://github.com/thephpleague/flysystem/blob/master/src/Directory.php#L24

**Comment by ewinslow** [comment]
I forget why we didn't use flysystem before, but I'm sure glad we have our little wrapper to at least ease some of the migration pain...

**Comment by ewinslow** [comment]
@mrclay does that actually work though? It will get top-level files but will it get directories too? We need to be able to get directories, not files.

I figured it wasn't too bad to do this expensive thing since the end result would be cached eventually anyways.

**Comment by mrclay** [comment]
PR #8495
