### ISSUE TITLE
Make config service private again

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8472]
My thought here is that exposing a 2nd API to do the same thing is not wise. I'd rather reserve public services for new stuff and at some major junction have a big deprecation of globals and expose services to replace them. At at that point, all those function bodies switch to using `elgg()` so devs can easily see how to upgrade each usage.

**Comment by mrclay** [comment]
At at that junction, all those function bodies switch to using `elgg()` so devs can easily see how to upgrade each usage.

**Comment by ewinslow** [comment]
Agree. It's really odd that only one service is available via this method and so many others aren't.

I wouldn't necessarily agree with deprecation on the global methods though. Feels like too much churn for plugin and the value prop to them is unclear. Are we just going for raw speed by avoiding loading so many fns up front? I feel like that's not quite enough bait unless we can quantify that it really makes a big difference...

**Comment by mrclay** [comment]
Good point

**Comment by mrclay** [comment]
#8516
