### ISSUE TITLE
Remove liststyle from removePlugins: 'liststyle,contextmenu,tabletools,resize',

### ISSUE THREAD

**Issue by fatemejon** [Elgg/Elgg#8480]
i see this error when liststyle is in removePlugins: 'liststyle,contextmenu,tabletools,resize':
 in elgg\ckeditor\config.js address :
"NetworkError: 403 Forbidden - http://localhost/elggs/cache/1434261276/default/js/blog/save_draft"

and every thing is ok when i remove liststyle from removePlugins !!!
please check .
thanks .

**Comment by jdalsem** [comment]
why the close if i may ask?

**Comment by fatemejon** [comment]
i see that liststyle remove from removePlugins !!!
and the error was Wrong.
 sorry .
