### ISSUE TITLE
master: jquery-ui not available where needed

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8483]
I'm not sure if this is only due to some work in progress (too many open AMD / jquery issues to be able to follow for me...) or if it has gone unnoticed so far that jquery-ui is not avalable on all the pages that rely on it being loaded, e.g. in admin section or profile pages or dashboards.

Error is for example: "$(...).sortable is not a function"

It seems it's currently necessary to do a
```php
elgg_require_js('jquery-ui');
```
to get it working. Directly within a AMD module it fails to work with
```php
require('jquery-ui');
```
though which is kind of annoying as this prevents to declare the dependencies directly where they need to be resolved but to deal with solving them indirectly.

**Comment by mrclay** [comment]
This might get fixed by #8479

**Comment by mrclay** [comment]
Nope. Problem is, unlike jQuery, jQuery UI won't automatically run its factory in an AMD environment. Easiest solution I see is to `require(['jquery-ui'])` at the top of elgg.js

**Comment by mrclay** [comment]
We just add it to the dependencies of the `elgg` module...

**Comment by mrclay** [comment]
PR #8484

**Comment by iionly** [comment]
Your fix works for me.

Question is what to decide with regards to https://github.com/Elgg/Elgg/issues/7925, https://github.com/Elgg/Elgg/issues/7191 and https://github.com/Elgg/Elgg/issues/7099 because it seems it's kind of a "either/or" decision to make.

**Comment by mrclay** [comment]
Making UI only available via require() seems unacceptable for 2.0 IMO. Plenty of plugins have not switched to AMD yet and even if they did they did not have the UI module available to them

**Comment by iionly** [comment]
When I said "works for me" I also meant "I prefer your solution"! :smile: 

I'm currently updated the JS code in all my plugins to AMD usage. The jquery-ui issue turned up when testing my Fivestar plugin (fully AMDed already for 1.X) on master. And I was very annoyed when I realized that even with all JS code in AMD modules it seemed like I would have to make a separate release of the plugin for Elgg 2.0 just because the jquery-ui libs are handled differently on master than on 1.X - especially when the approach of requiring the lib seemed so very inconsistent (inconsistency is the main reason why I say "very" annoyed as it seems that with every new JS lib I need to get working with AMD I need to figure out yet another way of getting it to work).
