### ISSUE TITLE
Readable access for groups shows as limited

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8491]
Readable access for groups that the user is member of (canWriteToContainer) should be displayed as a group label and not limited.

**Comment by mrclay** [comment]
Can you tell what branch?

**Comment by hypeJunction** [comment]
1.11

**Comment by hypeJunction** [comment]
I want to make a PR, but can't think of an inexpensive way to check if the collection owner is a group and the user is a member...

**Comment by mrclay** [comment]
It seems like ACL labels need to be stored as an entity or something where we can rely on Elgg's vanilla access control to show it.

**Comment by mrclay** [comment]
But that might help in the short term: fetch a group with GUID matching the ACL owner. If the query returns a result, show the group name.

**Comment by hypeJunction** [comment]
Hmm, feels like we are going back to the original implementation...
