### ISSUE TITLE
Some legacy URLs get __elgg_uri added to the query leading to redirect loop

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8494]

**Comment by mrclay** [comment]
I don't quite get this...

**Comment by hypeJunction** [comment]
Sorry :)
legacy_urls plugin appends __elgg_uri to the forward URL somewhere along the flow. I think it happens with /pg pages only.

**Comment by mrclay** [comment]
OK I get it, thx

**Comment by hypeJunction** [comment]
Fixed by #8498
