### ISSUE TITLE
forward('', '404') outputs a blank page non-default viewtype

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8506]
It should maybe register an error and forward home? That's what I'm doing in https://github.com/Elgg/Elgg/pull/8496/files#diff-dc34c2b06846278bbedf8ab656094d59

**Comment by jdalsem** [comment]
Instead of forwarding for 404 page not found issues you should throw exceptions. The exception will at least make it to the output. We have no idea in what format that should be... but probably better than an empty page.
