### ISSUE TITLE
isCacheableView bug checking fallback viewtype

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8512]
https://github.com/Elgg/Elgg/blob/c44740d59be73bf531cd1d311b85c00278fd0c3c/engine/classes/Elgg/ViewsService.php#L450

**Comment by jdalsem** [comment]
care to clarify... is the link still pointing to the correct line?

**Comment by mrclay** [comment]
I fixed the link but don't remember exactly what the bug is.

**Comment by mrclay** [comment]
That typo is gone.
