### ISSUE TITLE
unextending a view in admin context

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8517]
Hi,
How could I unextend a view in admin context (e.g. unextending a JS file or something) ?
I searched around this but I have not found anything.
I asked a similar question in Elgg community: https://community.elgg.org/discussion/view/2204306/prevent-loading-specific-js-files-in-admin-section

I really stuck with this issue.

**Comment by hypeJunction** [comment]
I will respond in the community.

**Comment by SirbitoX** [comment]
@hypeJunction you didn't answer me in community again. Please inform me if you have any idea how to fix it.

**Comment by mrclay** [comment]
@SirbitoX Do not use this repo to pester users for support.

**Comment by SirbitoX** [comment]
@mrclay I didn't mean that, sorry!
