### ISSUE TITLE
Move non-API state out of $CONFIG

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8524]
A lot of refactoring in minor releases is blocked by fear of breaking plugins that access `$CONFIG->some_prop`. E.g. "views". We should identify should-be-private state and move it from `$CONFIG` to `$_ELGG`, and formally declare that off-limits. I think this could be straightforward work with low risk of breaking core stuff.

**Comment by ewinslow** [comment]
Would it be cheating to just make a list of things that are considered private and post that they are no longer considered part of the API?

**Comment by ewinslow** [comment]
Without doing anything technically to prevent their use.

**Comment by ewinslow** [comment]
`$_ELGG` approach may be simple enough that it's a moot point

**Comment by mrclay** [comment]
Yes, cheating. It would mean plugins breaking in 2.x, not good.

**Comment by mrclay** [comment]
Do we really want to keep any of these? https://github.com/Elgg/Elgg/blob/master/docs/info/config.php

**Comment by ewinslow** [comment]
Not really no

**Comment by iionly** [comment]
What are the effects on plugins quering any of these $CONFIG variables with elgg_get_config()?

**Comment by mrclay** [comment]
If they're removed, egc() would return null.

**Comment by iionly** [comment]
That would be VERY BC breaking then :disappointed:

**Comment by ewinslow** [comment]
It would help if you listed your use cases for accessing internal "private"
state directly instead of going through explicitly public API. Then we can
improve the explicitly public API.

The need to keep this internal state fixed is making lots of refactoring
much more difficult than it should be and hurts or ability to make elgg
testable and stable.

We don't want to break plugins just for kicks though, so I'm glad you're
saying something. How can we help? Is there some compromise we can come to?

**Comment by mrclay** [comment]
We can focus on components we know we want to refactor in 2.x.

**Comment by iionly** [comment]
* elgg_get_config('sitename'): Used in Tidypics for watermarking
* elgg_get_config('default_access'): Loginrequired plugin to adjust available access levels if this custom walledgarden plugin is used
* elgg_get_config('language'): Used in various plugins to determine language to be used by 3rd party scripts (e.g. Tinymce) and used in various plugins in connection with notify_user() to allow for delivering notifications in the language of receiving user (not sending user!)
* elgg_get_config('site') / elgg_get_config('site_guid') / elgg_get_config('wwwroot'): Used in various plugins. While there might be public API functions available it would still be necessary to update them all.

Not sure if the following variables are also planned to be removed:
* elgg_get_config('profile_fields'): Used in Celebrations plugin to handle custom profile fields added
* elgg_get_config('elgg_cron_periods'): Croncheck plugin of mine
* elgg_get_config('icon_sizes'): Used in a couple of plugins

Not included usage of elgg_get_config('dbprefix') as it's used in just too many places / plugins.

**Comment by mrclay** [comment]
PR #8552
