### ISSUE TITLE
Remove elgg_get_view_location() in 2.0

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8527]
Not used in core, and I don't see a use case that would be wise. It doesn't check file existence, and if views are set via mod/plugin/views.php (#8513), it can't return a usable path for those.

A `views/` path is just no longer a useful shorthand for the exact location of a view file.

**Comment by mrclay** [comment]
elgg_get_view_location() could be left in. We could also expose the exact view file location to plugins, if that would be valuable.

The only case I can imagine is a plugin detecting if another plugin "won" the view and overriding it before render.

**Comment by ewinslow** [comment]
Agree removing it seems like the best option.

**Comment by jdalsem** [comment]
in none of our plugins we use this, so remove it
