### ISSUE TITLE
the use of $vars when using elgg_view_resource

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8532]
You can do elgg_view("resource/view", $vars), but you can not do elgg_view_resource("view", $vars)

This could confuse people and also does not allow you to build up view parameters in a page handler and then pass it to the view. Instead you are forced to use set/get_input functions to do this. Pre 2.0 this was normal, but with the resource views approach, wouldn't it be nice if we got rid of that habit?

Only thing we need is to open up elgg_view_resource and pass $vars

**Comment by mrclay** [comment]
Maybe @ewinslow can elaborate on the rationale for not passing via $vars?

**Comment by mrclay** [comment]
I vaguely remember there being a good argument for this. Maybe check the discussions on those PRs?

**Comment by ewinslow** [comment]
It was an easier refactor from the previous status quo where everything was using get_input. I think passing via vars makes a lot of sense, but would want to update all the plugins to use that approach consistently if we do switch.

**Comment by ewinslow** [comment]
Certainly makes things more consistent to use `$vars' and makes the inputs hookable, too. Can't see any downside!

**Comment by mrclay** [comment]
SGTM

**Comment by mrclay** [comment]
PR #8547
