### ISSUE TITLE
#8513 commit msg is inaccurate

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8539]
https://github.com/mrclay/Elgg-leaf/commit/f3881cf400765cbd91db67afdb59b610fa5d3e84
 - We load jQuery UI **sync**
 - We remove `$CONFIG->viewpath` and `$CONFIG->view`

How/do we deal with this? /cc @ewinslow

**Comment by ewinslow** [comment]
Reopen tickets. Was it supposed to read *synchronously*?

**Comment by mrclay** [comment]
Yeah

**Comment by ewinslow** [comment]
Doh

**Comment by mrclay** [comment]
The guides/upgrading doc is correct and the tickets in the `Fixes` declarations are correct, so maybe we just leave it.
