### ISSUE TITLE
master: prefix paths in views.php

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8546]
Let's say we allow this in views.php:
```php
  'prefix/' => __DIR__ . '/vendors/prefix/dist',
```
A few problems:
1. We still have to scan `dist` to find view files. We no longer guess filenames at runtime (a good thing)
2. If `dist` has subdirs, we could pull a lot more into views than we want.

Would it compromise this feature to limit scanning to the given directory? I.e. you might have to do this:
```php
  'prefix/'        => __DIR__ . '/vendors/prefix/dist',
  'prefix/images/' => __DIR__ . '/vendors/prefix/dist/images',
```

@ewinslow

**Comment by ewinslow** [comment]
Original motivation for prefixes was to be able to include the source of an entire AMD library like jquery or dojo into views very easily.

https://github.com/jquery/jquery/blob/master/src

I think not doing this recursively by default would make this use case significantly more painful.

If folks want to only include a single directory depth, they can just provide a custom callback as you have done. Php has some helpers for this like `glob` that make it not too painful.

**Comment by mrclay** [comment]
PR #8553

**Comment by mrclay** [comment]
How about we also put the core `_graphics` dir back in place for better BC?
