### ISSUE TITLE
WSOD on egefac() with metadata_names

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8567]
Not unique table/alias: 'n_table'

**Comment by hypeJunction** [comment]
Working with 1.11

**Comment by hypeJunction** [comment]
This only applies to ```'count' => true```. I suspect thiscomes from refactor in https://github.com/Elgg/Elgg/pull/7964. I guess we need to extend the scope of tests.

**Comment by mrclay** [comment]
Duplicate of #5515
