### ISSUE TITLE
Convert resource views to use `$vars` instead of `get_input` (core views)

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8569]
Let's make sure we're following this best practice before we ship 2.0...

**Comment by mrclay** [comment]
I forgot that if we don't get this done we'll have to support these views as it for 2.x, so I think this is pretty critical.

**Comment by mrclay** [comment]
(Technically these are BC changes but I still think we should sneak them in.)

**Comment by ewinslow** [comment]
I agree. I am treating alpha as "known breaking issues yet to come still". Certainly anything already on the milestone is fair game.

**Comment by mrclay** [comment]
PR #8755
