### ISSUE TITLE
Limit group listings to subtype "default"

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8571]
In practice this means adding `'subtype' => ELGG_ENTITIES_NO_VALUE,` to the queries. This limits listings to groups created by the groups plugin.

I've made differently used "discussion" groups that use a custom subtype and I don't want these showing up in the main listings. The problem is, I can imagine a use case where devs _do_ want those groups listed.

This is a case where hookable query options (#6256) would let us have either way.

**Comment by hypeJunction** [comment]
That would be of great help. I think I have already made a few clones of the group plugin just to accomplish that.
This also applies to the users listings (members plugin)

**Comment by mrclay** [comment]
We could add a plugin hook just for the group listing options.

**Comment by jdalsem** [comment]
Fixed as part of #11327
