### ISSUE TITLE
Allow adding/modifying groups/all filters

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8573]
E.g. If I want to add an "alpha" filter to list all in order, I have to make a whole page.

Strawman: in groups_handle_all_page() turn the switch statement into looking for the view `"groups/listings/all_{$selected_tab}"`. If the view exists, use it, otherwise `"groups/listings/all_default"`.

Plugins can already add to the filter menu.

**Comment by jdalsem** [comment]
Hmmm... feels a bit hacky. A route hook and a resource view is all it takes right now. We do not have this kind of behaviour in other listings...

**Comment by hypeJunction** [comment]
I also feel that resource views now give enough control
