### ISSUE TITLE
system.api.list should not leak PHP functions used for method execution

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8574]
system.api.list WS method should not expose internal function names

**Comment by mrclay** [comment]
Is this just extraneous info output in the response? SGTM.

**Comment by juho-jaakkola** [comment]
What exactly is being exposed?

**Comment by hypeJunction** [comment]
The name of the php function used. With all the parameters specified, I am
afraid this can be used as an attack vector.
