### ISSUE TITLE
Rewrite notifications JS as AMD

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8575]
Hi,
When I was implementing around notification plugin, I encountered the following issue:

I wanted to overwrite the save form of notification to remove friend picker from it so I commented the line below in ``` notifications\views\default\forms\notificationsettings\save.php ```:
```php 
echo elgg_view('notifications/subscriptions/forminternals', $vars); 
```
but when I did so the JS relevant to clicking on the email icon broke. The reason is the ``` jsfuncs.php ``` file is called in ``` forminternals.php ``` however the other parts of save form need these JS function.
I think, it's better to call ``` jsfuncs.php ``` directly in ``` save.php ``` file and remove it from ``` forminternals.php ```. Something like:
in ``` notificationsettings\save.php ``` file:
```php
...
/* @var ElggUser $user */
$user = $vars['user'];

echo elgg_view('notifications/subscriptions/jsfuncs',$vars);
echo elgg_view('notifications/subscriptions/personal', $vars);
echo elgg_view('notifications/subscriptions/collections', $vars);
echo elgg_view('notifications/subscriptions/forminternals', $vars);

?>
...
```
and in ``` notifications/subscriptions/forminternals.php ``` file:
```php
...
<?php

	}

	//echo elgg_view('notifications/subscriptions/jsfuncs',$vars);
		
?>
...
```

p.s. I already know that another way to remove or replace the friend picker is using "replacement" parameter. But in this case the scenario is the same either.

**Comment by mrclay** [comment]
We will be converting this script to an AMD module. You're welcome to help with that effort.

P.S. You can override views. It's very unwise to modify core files.

**Comment by SirbitoX** [comment]
@mrclay I'm developing on elgg for months. I'm familiar with overwriting the views. So definitely I overwrote this file and removed "forminternals" file. But a JS file is called in it that is used by the other views either. So I think it is unwise to call a shared JS in a specific file which by removing that file the other views break.

**Comment by mrclay** [comment]
I agree it's a poor design. I'm saying that moving all the scripts to AMD module(s) is a better use of our time. I'll reopen this ticket and change the title to reflect that.

**Comment by SirbitoX** [comment]
@mrclay  :+1:

**Comment by hypeJunction** [comment]
Moving the discussion over to #10287
