### ISSUE TITLE
Decide which deprecated features to remove in 2.0

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8579]
My PR #8577 removes everything that's been deprecated in 1.8 or earlier.

Now I noticed that even some of the 1.10 deprecations have already been removed: https://github.com/Elgg/Elgg/commit/805ecb1de083fd2a16e739afa487a03537bae85e#diff-e08156463e7221d38b24328b08ca4952L16

Would it be OK to remove *everything* that's been deprecated before 2.0? Have we already agreed on some course of action?

**Comment by mrclay** [comment]
I count 1 view in #8367 removed that was deprecated in 1.10, probably by mistake. I'm definitely OK removing stuff deprecated in 1.8 and earlier. Not sure about 1.9 and later. Maybe if we can identify those that are likely to block refactoring in 2.x...

**Comment by beck24** [comment]
I think if it's been deprecated in the 1.x branch we can remove it in 2.0 regardless of when that deprecation occurred

**Comment by jdalsem** [comment]
if deprecated in 1.x remove in 2.0.... that is the deprecation policy

**Comment by juho-jaakkola** [comment]
I remember someone wondering whether we should leave some of the newer deprecations intact to make migration from 1.x easier.

@ewinslow was it you?

**Comment by ewinslow** [comment]
Ya, that seems like a reasonable train of thought. If it's not blocking progress on some feature, I don't see why we'd need to rip it out just yet.

**Comment by ewinslow** [comment]
There are some things though the we are deprecating in 1.12 that were removing in 2.0 since they are blocking progress :). Case-by-case.

**Comment by ewinslow** [comment]
Closing this as we should just decided case-by-case based on how much bc pain it will cause.

**Comment by juho-jaakkola** [comment]
Yep, sounds good.
