### ISSUE TITLE
custom JOINs are being added above core JOINS in elgg_get_entities_from_annotation_calculation?

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#8580]
as is documented in this community thread, when i provide a JOIN parameter to elgg_get_entities_from_annotation_calculation that references an alias that is created in the core code, an SQL error is thrown:

https://community.elgg.org/discussion/view/2223883/changing-the-sequence-of-where-clauses-in-elgg-get-entities-from-annotation-calculation

this appears to be because my join is being used in the final query above/before the core JOIN that contains the alias that i am referencing. as matt stated, the custom JOINs would be more appropriately added after the core JOINs.

**Comment by hypeJunction** [comment]
Can confirm running into this

**Comment by propertunist** [comment]
what did you use as a workaround?

**Comment by hypeJunction** [comment]
Writing a custom query was inefficient, I just created a metadata that is
updated when annotations are created/updated/deleted.

**Comment by hypeJunction** [comment]
I mean I didn't find one. I needed to also list entities with no
annotations, and I couldn't build a query with custom joins/selects using
ege*, partially because of that bug

**Comment by propertunist** [comment]
aha ok. i think in my case i could use a custom query, but i think i will just disable the feature that uses this lookup until the elgg core is fixed as it is non essential. thanks

**Comment by propertunist** [comment]
so i have come up against this same bug in a different way now. any chance of a fix for this in core?

**Comment by mrclay** [comment]
Why not try to dig in and fix it?

**Comment by propertunist** [comment]
mainly because:
a) i am not familiar enough with elgg core to feel that i am not wasting my time ;)
b) i am locked out of github due to a problem with ssh / netbeans on my dev machine (so i haven't uploaded anything for months).. neither github support or netbeans forums could figure out the problem.
c) i've got a long list of non core things to fix.

none the less, i will look and see what i can find.

**Comment by mrclay** [comment]
For b) try http://superuser.com

**Comment by propertunist** [comment]
so one of the fixes is needed here: https://github.com/Elgg/Elgg/blob/1.12/engine/lib/metastrings.php#L219

i ammended that line to become: 
```
array_unshift($joins, "JOIN {$db_prefix}entities e ON n_table.entity_guid = e.guid");
```
and that fixed one of my problems.
now i need to find the other place where a similar change is needed to allow my other query to run correctly. i think it is in an annotation file, but i haven't found it yet.

**Comment by propertunist** [comment]
seems i have been able to resolve my two issues here with just one change to elgg core. :)
so i will move on to figuring out how to upload to github again!

**Comment by propertunist** [comment]
i now have github working locally (after reinstalling the OS) and have also found another correction that is needed in relation to this original issue. the same/similar fix is needed for the river file too:
```
$joins[] = "JOIN {$dbprefix}entities oe ON rv.object_guid = oe.guid";
```
becomes
```
array_unshift($joins, "JOIN {$db_prefix}entities oe ON rv.object_guid = oe.guid");
```
in engine/lib/river.php

**Comment by propertunist** [comment]
if i create a pull request for this does it need to go into 2.x ? i ask because i am using 12.x and would prefer the fix to go into 12.x and above and am not sure of the protocol here.

**Comment by mrclay** [comment]
Fix 1.12 if the problem exists there.

**Comment by propertunist** [comment]
had some issues with git / github and ended up somehow with two commits and i am unsure how to delete the first one.

**Comment by propertunist** [comment]
hmm.. travis failed the commit due to the commit message, except as far as i know the commit message is in the required format.

**Comment by beck24** [comment]
I think the parameter in the brackets should only be one word, and there may be a length limit to the message title.

try:

```fix(river): custom joins added after default joins```

**Comment by propertunist** [comment]
ok, that was my only thought on it too. unfortunately, i am not up to the level of super magician with github and have no idea how to properly revoke the two commits i have already made. the first commit was made from a fork that i then deleted because it over-wrote my local elgg file structure (which was a nightmare in itself!) and so now i have no local version of that fork from which to act against github's reference to it.
is there a command along the lines of: git undo noob errors ?

**Comment by propertunist** [comment]
this has now been resolved
