### ISSUE TITLE
elgg_normalize_url can cause a lot of php errors

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8581]
elgg_normalize_url assumes $url is a string (as it should be provided), but it doesn't check it, so if it's not a string but for example an array this causes a lot of php errors

My use case:
```php
$friendly_url = $entity->friendly_url;
echo elgg_normalize_url($friendly_url);
```
For some weird reason $friendly_url became an array and now my php log is flooded

I need to fix this on my side, but also some input validation should be done in elgg_normalize_url

**Comment by eduardojunio** [comment]
That was fixed in #8879 pull request. =)

**Comment by mrclay** [comment]
If Elgg accepts this PR you might not know you had a problem on your end.

I.e. We should either leave it as is or log warnings in all functions that expect strings.

I don't like the return false approach unless this was a new API, but even then.

**Comment by eduardojunio** [comment]
So why you don't close this issue?

**Comment by beck24** [comment]
> For some weird reason $friendly_url became an array

Probably my old nemesis:
https://github.com/Elgg/Elgg/issues/4268

**Comment by mrclay** [comment]
Yes.
