### ISSUE TITLE
profile/edit action should not assume all profile fields are passed

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8582]
Currently the profile/edit action retrieves all input based on `elgg_get_config('profile_fields')`. This means that if you do not pass the input, it will get removed.

I suggest a (breaking) change to change this behaviour in a check where the profile field will only be removed when it is passed as empty to the action.

So if a profile field is ommited in the form, it will not be removed.

The use case for this change is that there could be a difference between what you show on the profile details and what you are able to edit. Sometimes you have a seperate proces to add profile data (like from a backend system) that should only be shown on the details, but not be able to edit this on the profile edit form. Profile Manager has the ability to make those fields "non-editable", but is still required to add them as hidden inputs in the profile/edit form.

This is a breaking change as you no longer can assume that not sending profile fields to the profile/edit action will remove them. If you want to remove them, you should change to sending an empty value for these fields.

If i can get a few :+1: i can make a PR for it, so we can do this in 2.0

**Comment by hypeJunction** [comment]
I would prefer a plugin hook that will look at the context rather than passing flags via inputs.

**Comment by hypeJunction** [comment]
On a second thought, any input contained within the HTML form is passed on to the action, so checking if the key is present in the request should be enough.

**Comment by jdalsem** [comment]
Same PR is done for group profile actions #8642
