### ISSUE TITLE
the text labels are missing from empty lists 

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#8583]
in previous elgg versions there were text labels that were presented to users if lists were empty, such as media items from friends or the main river. the present version of elgg (1.11.2) has no such labels and there is just an empty space. this means that if i view friends' videos and my friends have uploaded no videos, i just see an empty box - which for new users can be confusing.

ideally, there would be customisable text strings for all lists, so that all lists in each context can present a custom string of text when the list is empty. e.g. 'you don't have any friends here yet..' or 'your friends haven't added any items to the community yet..' etc.

**Comment by hypeJunction** [comment]
You can pass ```'no_results' => "Custom no results test"``` to ```elgg_list_entities()```

**Comment by propertunist** [comment]
i see, but that means that all the lists need to be over-ridden to activate that behavior doesn't it?

**Comment by hypeJunction** [comment]
You can use ```'view_vars','page/components/list'``` and add it to all lists that do not have it

**Comment by propertunist** [comment]
aha! ok, thanks

**Comment by propertunist** [comment]
i just added the plugin hook handler and it looks fine, except that the string is not outputted under the list. the string does get picked up by hypeLists in the container data fields.
```
elgg_register_plugin_hook_handler('view_vars', 'page/components/list', 'sorted_empty_list_hook');
```
```
function sorted_empty_list_hook($hook, $type, $return_value, $params)
{   
    if ($return_value['no_results'] == '')
    {
        $return_value['no_results'] = elgg_echo('sorted:no_results');
    }
    return $return_value;
}
```
is there anything missing from my code?

**Comment by hypeJunction** [comment]
Empty lists are not rendered, only a <p> is outputted. That's the expected behavior, imho.

**Comment by propertunist** [comment]
huh?
;)

i thought the intention of adding the no_results handler was to choose what is shown in the case of an empty list.
oh, so i disabled hypeLists and now i see some text in place of an empty list. so are you saying that it is hypeLists that is blocking the no_results text?
i'm not sure why that would be the expected behavior when there is an explicit 'no_results' field that is being ignored. i prefer to see a message in place of an empty box since otherwise there is no cue for users to grasp what the purpose of the page is and why it is empty.

**Comment by hypeJunction** [comment]
Open a ticket at hypeLists and let's discuss there. I don't think others
should be bothered by third party stuff.

**Comment by propertunist** [comment]
ok

**Comment by propertunist** [comment]
so i have tested this further and even when hypeLists is disabled i am still not getting the no_results text to output in the browser after i pass it to elgg_list_entities in the options array.
