### ISSUE TITLE
Connect hooks design and hooks list in docs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8585]
We need a more logical arrangement of:
http://learn.elgg.org/en/1.11/design/events.html?highlight=hooks#plugin-hooks
http://learn.elgg.org/en/1.11/guides/hooks-list.html?highlight=hooks

**Comment by mrclay** [comment]
The events page should be moved into guides/. If we think it's needed, we could make a hooks menu item and have it redirect to events.
