### ISSUE TITLE
NullMessageTemplate class

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8599]
@ewinslow shouldn't the classname be the same as the file name? It is missing the Template.
Also the extend fails as Elgg/I18n/Message does not exist. Shouldn't it be MessageTemplate??

**Comment by ewinslow** [comment]
This code was checked in but never used. We should use it and iron out these remaining issues...

**Comment by jdalsem** [comment]
I ran into this using @srokap his code_review plugin which loads all classes

**Comment by ewinslow** [comment]
Gotcha. Useful!

**Comment by Facyla** [comment]
+1 to add an empty Elgg/I18n/Message class so the code analyzer can run (useful tool when updating plugins !) :)

**Comment by mrclay** [comment]
Private classes not in use and with no immediate plans of use should be removed. We pull stuff like this in thinking it has no cost, but that's clearly wrong. It's also noise to every dev that tries to dig in and understand the I18N system.

**Comment by Facyla** [comment]
Ok, agree.
As long as the included core classes don't break automatic code review the solution seems OK to me. Code_review is a very useful plugin for plugins developers when updating themes and other plugins, and the only way to make it work on the whole system is whether to add the missing class that is extended by other classes, or remove the other included I18n classes.

**Comment by mrclay** [comment]
Short term we can just delete this file.
