### ISSUE TITLE
Writing web services should require less work

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8605]
I feel like exposing functions currently requires too many repetitive steps. First, you need to document all the parameters when exposing the function. Then you need to list all those parameters as arguments in your function, then document them all over again.

I am thinking of adding an associative array of parameters as the last argument passed to the function on method execution. That way the method function can skip listing all arguments and use ```func_get_args()``` to get an assoc array that it can work with. In the long run, we should however consider making a breaking change and switching to assoc array by default. If the web service needs 10 or 20 or more parameters to run, using them all as arguments is tiresome.

I am open to other ideas if anyone has them.

**Comment by juho-jaakkola** [comment]
>In the long run, we should however consider making a breaking change and switching to assoc array by default

Suggested also here #3512. Would you be able to do it for 2.0?

**Comment by hypeJunction** [comment]
I suppose I could. But I would want to make it on top of #8604
For 3.0, we should really just rewrite the whole thing. Such a mess

**Comment by hypeJunction** [comment]
I could also just leave 1.x alone and just make all changes to master

**Comment by hypeJunction** [comment]
What is our policy for removing functions without deprecation? Can we do that in a major release?

**Comment by juho-jaakkola** [comment]
semver.org:

When you deprecate part of your public API, you should do two things:
 - (1) update your documentation to let users know about the change
 - (2) issue a new minor release with the deprecation in place. Before you completely remove the functionality in a new major release there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

**Comment by juho-jaakkola** [comment]
So deprecate it in 1.12.0 and you can remove it in 2.0.0.

**Comment by hypeJunction** [comment]
Proposed implementation here: #8610 
Will deprecate thing in 1.12 once we know if that's the direction we want to head

**Comment by hypeJunction** [comment]
No more interest in this.
