### ISSUE TITLE
elgg-1.11.2/activity Error 404

### ISSUE THREAD

**Issue by MonsieurVaros** [Elgg/Elgg#8611]
Hello,

I just install Elgg, not in the var/www/ directory but in a private directory with a symbolic link to the /var/www/ directory.

After the installation, the creation of the admin account, I got a 404 error : http://localhost/elgg-1.11.2/activity not found.

I fact, the setup is not able to create the activity directory. This is not a permission issue cause the whole directory is in 777 mod.

It seems the setup doesn't work with symbolic link.

After retry, the setup is not able to create any directory with or without symbolic link.

**Comment by mrclay** [comment]
Elgg does not create directories, it uses mod rewrite to route requests to index.php. What happens if you request `/index.php?__elgg_uri=/activity` ?

**Comment by ewinslow** [comment]
Closing this. Not obviously a bug in Elgg. You are welcome to ask for further support on community.elgg.org.
