### ISSUE TITLE
master: use of live() in elgg/admin.js

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8613]

**Comment by jdalsem** [comment]
There still is a lot of deprecated jQuery usage in core. I was hoping we could get rid of the default loaded jquery-migrate js, but I think that was a false hope

**Comment by mrclay** [comment]
i think we've already removed jquery-migrate. I'm not against putting it back in, but we'll have several betas to iron out the current deprecated usages. cc @ewinslow

**Comment by ewinslow** [comment]
+1 for just migrating during alphas/betas.
