### ISSUE TITLE
Replace reportedcontent whistle with exclamation-triangle icon

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8628]
Maybe [bell](http://fortawesome.github.io/Font-Awesome/icon/bell/) or [exclamation-circle](http://fortawesome.github.io/Font-Awesome/icon/exclamation-circle/).

**Comment by jdalsem** [comment]
Need to do a poll for that :smile:

**Comment by jeabakker** [comment]
i was trying to find a ``whistle`` but is hasn't been added yet https://github.com/FortAwesome/Font-Awesome/issues/984

i like bell

**Comment by jdalsem** [comment]
I also think [exclamation triangle] (http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/) icon is an option (like alerting misuse/abuse or reporting foul play) 

Also the [flag](http://fortawesome.github.io/Font-Awesome/icon/flag/) icon is appropriate, like in flagging content as incorrect/incomplete/out of date/containing abusive language

**Comment by hypeJunction** [comment]
I have also seen bullhorn used for that: http://fontawesome.io/icon/bullhorn/

**Comment by mrclay** [comment]
+1 for exclamation-triangle.
