### ISSUE TITLE
master: Hover menu icon doesn't work

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8629]
Noticed it in theme sandbox. It looks correctly set to use fa-caret-down, but CSS isn't right.

**Comment by jeabakker** [comment]
#8538 introduced that simplecache file should have a valid extension, the webfonts haven't been added (yet)

- .eot
- .ttf
- .woff
- .woff2
- .otf

https://github.com/Elgg/Elgg/blob/ebccf0112b1e15c190d1a7a1c16b03497e8ea2a4/engine/classes/Elgg/Application/CacheHandler.php#L17

**Comment by jdalsem** [comment]
@jeabakker don't think that is what @mrclay is seeing...

**Comment by jdalsem** [comment]
my guess it is a aalborg theme only issue...

**Comment by mrclay** [comment]
@jdalsem your guess is correct

**Comment by mrclay** [comment]
PR #8650
