### ISSUE TITLE
Nudge admins toward symlinking /cache to views_simplecache

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8638]

**Comment by ewinslow** [comment]
Could also just make this part of the composer install/update process.

**Comment by jdalsem** [comment]
@mrclay what was the intention with this issue?

**Comment by mrclay** [comment]
If I'm in advanced settings and have checked simplecache, but not added the symlink, I should get a reminder to do that.

**Comment by hypeJunction** [comment]
I still think we should try and do it in the background.  Create the symlink, get headers, if not working, delete the link and nudge.
