### ISSUE TITLE
master: elgg config file not read 

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8652]
In my Elgg project i was unable to boot Elgg. Reason: Elgg settings file is in /engine/settings.php, but https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Config.php#L190 resolves to /settings.php

I believe @ewinslow should be able to answer this

**Comment by mrclay** [comment]
(Temp workaround, symlink /settings.php to /engine/settings.php)

**Comment by mrclay** [comment]
I guess the Q is: is the intention to move settings.php to / or leave it at /engine/ and fix line 190?

**Comment by ewinslow** [comment]
Intention is to move it to root. That makes more sense for projects where elgg is a dependency

**Comment by ewinslow** [comment]
Apologies. One of those things I worked out during development and then failed to document

**Comment by ewinslow** [comment]
What do we need to do here? Add something to the docs? Add a script to Elgg\Composer\PostUpdate to copy the file to the new, correct location?

**Comment by mrclay** [comment]
Just fallback to /engine/settings.php if /settings.php doesn't exist? If neither, then push to installer I guess.

**Comment by mrclay** [comment]
PR #8661. I think most users will have the legacy location so I checked there first.
