### ISSUE TITLE
master: discussion needs a site menu item

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8668]

**Comment by juho-jaakkola** [comment]
I left this out deliberately so it works the same way as earlier when used with groups. Now that I think of it, I agree we should add a menu item.

**Comment by mrclay** [comment]
Yes. And a note in docs/guides/upgrading on how to remove it.

**Comment by iionly** [comment]
Or making it a plugin setting to give a choice to site admins without the need to modify code.

**Comment by mrclay** [comment]
Is there a plugin that allows registering arbitrary menu items? I always feel that'd be better than introducing settings that we'd then need to maintain forever.

**Comment by jdalsem** [comment]
I would suggest just adding it, like we do with all the other plugins. There is the ability to manage the menu with plugins if you do not want it. Maybe with #3119 we could add the ability to 'disable' menu items that get added automatically

**Comment by jdalsem** [comment]
> Yes. And a note in docs/guides/upgrading on how to remove it.

Current docs on menu items should suffice i guess. No real question for upgrade
http://learn.elgg.org/en/1.11/guides/menus.html?highlight=menu#advanced-usage

**Comment by juho-jaakkola** [comment]
Yeah, lets just add it.

**Comment by mrclay** [comment]
Agreed
