### ISSUE TITLE
elgg 2 feature request: Facilitating "invitation-only" sites: Letting users invite others even when registration is disabled.

### ISSUE THREAD

**Issue by isoguci1** [Elgg/Elgg#8677]
The case of "invitation-only" sites:
There are cases where you do not want anyone passing by the door to register and enter your site. But the existing members of the site should be able to invite their friends.

**Comment by mrclay** [comment]
I like this idea. A good middle ground between open registration and admins having to create each user.

**Comment by mrclay** [comment]
A plugin could allow users to have a specific number of invitations...

**Comment by isoguci1** [comment]
As for plugins there were two options:
1- Registration by invitation (https://community.elgg.org/plugins/1142917/releases/1.0) but does not work with 1.11.x.
2- Premium plugin by Webgalli: invitation only registration for 1.8 (http://www.webgalli.com/elgg_plugins/profile/3975/invitation-only-registration-for-elgg-18///) which is only for 1.8.

I think this functionality is a basic one and would be good to have as a standard option.

**Comment by hypeJunction** [comment]
It would be a good place to showcase how new HMAC API works

**Comment by iionly** [comment]
I think this has been suggested before (don't know at the moment if there's still an open issue about it ).

In case the invitation of new users by existing users with account creating (theoretically) disabled I think it should be added an option in any case to give the site admin the choice to allow these invitations or not. There could be different reasons why a site admins doesn't want any new accounts to be created and even invited people creating account could undermine these reasons. In the worst case a spammer would be able to invite his "friends" and flood the site with spam while the site admin had the intention to just prevent this to happen by disabling account creation.

**Comment by hypeJunction** [comment]
This should be its own plugin. Admins can just not enable it.
