### ISSUE TITLE
Create user - password flow

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8679]
Allow specifying (offer random) password, but by default send the new user an email token and they create password and review profile as first action.

**Comment by mrclay** [comment]
If specified password, offer options to not send it over email, and nudge the user to change it after logging in.

**Comment by ewinslow** [comment]
Similar to #8647

**Comment by jdalsem** [comment]
We are keeping the current way for the registration. Alternatives are easily created with plugins.
