### ISSUE TITLE
Allow more locale codes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8683]
There's a huge list of locales in iOS: http://stackoverflow.com/a/28357857/3779

From Transifex we're receiving translations in Serbian (Latin), Chinese (Simplified Han), and Romanian (Romania). While it would be nice to stick to two-char language codes, this is totally unrealistic, and the Elgg core team is in no way qualified to say which codes should be considered too specific.

I think we should pull all those codes ([that are supported by Transifex](https://www.transifex.com/languages/)) in (in a [normalized form](https://github.com/Elgg/Elgg/pull/8681/files#diff-2d105b58e1b35c054f963a1dd752c614R577)) and the community members that speak those languages should sort out which locales they want to put effort into.

What's the downside here?

**Comment by ewinslow** [comment]
SGTM

**Comment by mrclay** [comment]
The cost would be an additional 300 codes and names in the JS translation files.

**Comment by ewinslow** [comment]
So a few kilobytes before gzip.

**Comment by mrclay** [comment]
I updated #8681 to do this

**Comment by iionly** [comment]
Well, personnally I don't see the necessity for most of these new codes (e.g. en_DE... come on!). I also don't know if anyone would be able to evaluate the full correctness of the translations for all these codes (maybe the easiest would be en, en_GB, en_US but for others I think it's basically impossible).

Also, it could get messy with a lot of very incomplete translations (hoping that there won't be too many guys who think it funny to just add s stub of a translation of any exotic language/dialect just to have yet another entry added). When adding all these additional codes it might be more urgent to also fix https://github.com/Elgg/Elgg/issues/6822 to allow for disabling any unwanted translations in any easy way (without the need to delete the files manually).

**Comment by hypeJunction** [comment]
I miss the days when translations were plugins. I find all these languages
in core extraneous, and make it hard grepping things. Plus there is no
interface to disable unwanted translations.
The problem is if you have a site where the majority of plugins are
non-bundled, all of these translations become incomplete. And there is no
way to say, I only want my site in language x.
Can't we add a bundled plugin that takes translations from Transifex and
enable it by default?

**Comment by iionly** [comment]
I would much prefer all translations within a single plugin, too. On pre-1.9 (with the old language file scheme) it was even easier to do that because you could put all translated files for a specific language into the same directory (https://github.com/Elgg/Elgg/issues/6712). If this would still work with the new language file scheme and all language files of all translations would be put together within a single plugin, it would at least be much easier to disable unwanted translations as you wouldn't have to delete the files from numerous different folders but only from one place.

@hypeJunction If you only want a single language to be offered, you could use my Monolingual plugin (https://community.elgg.org/plugins/1138644).

**Comment by mrclay** [comment]
The more pointed question I'm asking here is, should a developer be able to use any language available in Transifex? If not, who will decide which ones can't be used?

I agree language management in the system is lacking and can be addressed in the other tickets.

**Comment by mrclay** [comment]
I'll make another PR to more simply address the limited issue we're having making releases.

**Comment by ewinslow** [comment]
I don't follow how pulling translations into a plugin solves any of the
problems mentioned here.

**Comment by jdalsem** [comment]
> Plus there is no interface to disable unwanted translations.

Translation Editor is your friend

**Comment by iionly** [comment]
@jdalsem 
> Translation Editor is your friend

It's surely a plugin that has a certain purpose. But I don't think that the main purpose of the Translation Editor plugin is to be able to disable certain translations to be offered. If the languages are offered by Elgg core it should be an core option to configure the translations to be offered - even more so as there's quite a number of translations included that are very incomplete.

@ewinslow as long as there's no option in core to disable unwanted translations it would be much easier for admins to handle the translation issue if translations would be bundled in core. You would be able to find all files in one place and can easier delete unwanted files or in case you don't want any translations at all you simply disable this plugin.

**Comment by ewinslow** [comment]
The amount of work needed for us to support that does not sound worth it. We might as well just put in the effort to do it the right way.

**Comment by ewinslow** [comment]
And furthermore the idea of putting all translation for core and plugins in a single bundled plugin sounds so distasteful to me that I would actively block any attempt to implement such a workaround.

I think users deciding for themselves what quality of experience they want is an acceptable status quo. Letting admins whitelist languages would be a solid improvement over that.

**Comment by iionly** [comment]
Whatever. I see no sense for me to continue to participate in this discussion. I'll fix this on my own for me instead as I have a certain feeling that this will be one more of the kind of little annoying issues that won't get fixed anytime soon.

**Comment by jdalsem** [comment]
> If the languages are offered by Elgg core it should be an core option to configure the translations to be offered

True, that is why #6822 is still open

**Comment by ewinslow** [comment]
Agreed. A PR implementing #6822 would be most welcome and encouraged!

**Comment by mrclay** [comment]
Perhaps for 2.0 we need a cut down version of #8681 that just has the normalization and doesn't add all the Transifex languages? That would also get us closer to a process for validating Transifex's PHP syntax before updating our files (#8924).

**Comment by mrclay** [comment]
Alright, #8954 is good to go here.

**Comment by jdalsem** [comment]
Not going to add any other languages codes at the moment. If we receive new translations via Transifex, we can add those translation codes to the list.
