### ISSUE TITLE
friends lib runtime error when no one is logged in

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8684]
`\engine\lib\friends.php` line 189 throws a runtime error when no one is logged in. This is because of a wrong proposition for if condition.

``` php
...
if (elgg_get_logged_in_user_guid() == elgg_get_page_owner_guid()) {
    ...
}
...
```

It's not considered that both functions in if condition may return 0 value.
It would be fixed with something like this:

``` php
...
if (elgg_is_logged_in() && elgg_get_logged_in_user_guid() == elgg_get_page_owner_guid()) {
    ...
}
...
```

**Comment by SirbitoX** [comment]
PR https://github.com/Elgg/Elgg/pull/8685

**Comment by jdalsem** [comment]
This has been fixed
