### ISSUE TITLE
Document implementation details of blog drafts

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8690]
Trying to change the `status` and `created_time` metadata cause `access_id` metadata to be set to 0 (ACCESS_PRIVATE).
I had encountered this issue when I was trying to implement a script to publish all blogs with `draft` metadata.
Is this known as a bug? or changing metadata like this is a known mistake?

**Comment by SirbitoX** [comment]
I realized that the reason is we set ``` future_access ``` metadata for the draft blogs and change ``` access_id ``` metadata to ``` ACCESS_PRIVATE ```. If it is a good way to handle draft blog then at least we should mention it in documentation where I didn't find anything anywhere.

In the other hand I think this is a poor way to couple two separate metadata just because make "not showing the draft blogs" easy. Because I didn't find any other rational reason to change the ``` access_id ```. Even the core developers of Elgg in ColdThrick haven't took care of this coupling in their popular plugin "*blog_tools*".

**Comment by saeedsq** [comment]
I have faced the same issue too:

For ease of use, we wanted to implement a feature that enables editors to create quick draft blogs with some custom extra data. so we implemented our own custom blog save. We were struggling about not showing draft blogs in list view. Finally we noticed that the draft status does not matters to list blogs, however it is the private access id which matters here.

I agree with @SirbitoX, this is a business logic misinterpreting.
What if a scenario comes that you want to list & share a private blog via some special users but not the draft ones. I guess this solution does not meet the Elgg flexibility & extensibility goal!
"blog_tools" is the best sample!

**Comment by mrclay** [comment]
In that case you'd set future_access to a friend collection ID (if I understand correctly).

**Comment by mrclay** [comment]
If you're saying blog_tools has a bug, you should make an issue there.

**Comment by saeedsq** [comment]
Although it is not a good practice: I think that even if you want to handle draft status with private access, It would be better if you take care of it in ElggBlog save method not the save action.

```php
public function save() {
	if($this->status == "draft") {
		$this->future_access = $this->access_id;
		$this->access_id = ACCESS_PRIVATE;
	}
	elseif($this->status == "published" && $this->access_id == ACCESS_PRIVATE && $this->future_access) {
		$this->access_id = $this->future_access;
		$this->deleteMetadata('future_access');
	}
	parent::save();
}
```

It will be reusable, time saving & a better approach.

**Comment by SirbitoX** [comment]
@mrclay I think it would be better to implement some functions (e.g. ``` publish_blog(...) ``` and ``` draft_blog(...) ```) in core to draft or publish a blog instead of making the documentation complex. In the other hand this would help developers use benefits of it every time they want publish or draft a blog in their codes.
I think it gives us more functionality if we separate the logic of publishing and drafting from ``` save() ``` function which is more general.

**Comment by jdalsem** [comment]
metadata no longer has access... so this issue is obsolete
