### ISSUE TITLE
Move all topbar items to right with "Account" as first

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8699]
Along with #8698 this would look like:

![left topbar 2](https://cloud.githubusercontent.com/assets/170687/8527030/4b9abfae-23d8-11e5-95ad-23ec8b6f434e.png)

Account menu expanded:

![left topbar](https://cloud.githubusercontent.com/assets/170687/8527044/5ddb98c8-23d8-11e5-8382-4958149d7d6c.png)

cc @PerJensen thoughts?

**Comment by mrclay** [comment]
Really "Administration" doesn't have anything to do with the account. I'd rather have a gear icon on the left for opening /admin and have the user's icon open to a menu with options (Profile, Settings, Log out).

**Comment by mrclay** [comment]
Better, the gear could replace the bottom right "gear menu" added in developer tools 1.12. It would just be always available to admins.

**Comment by hypeJunction** [comment]
Might as well get rid of the topbar and move account items above search in
the toolbar, then combine all menus for mobile.

**Comment by PerJensen** [comment]
@hypeJunction messages, profile and friends under account and skip the profile icon?

**Comment by hypeJunction** [comment]
@PerJensen, I means combine with the tools menu when in mobile. Just a thought. Not sure why @mrclay wants to move things to right side, so just putting in my 2 cents

**Comment by mrclay** [comment]
I suggested move to right for a little balance, since H1 and site menu are on the left.

**Comment by hypeJunction** [comment]
Let's just keep as is. Themes usually leave the topbar be, and this will be
an annoyance, when site owners are unhappy because their users can no
longer find things where they used to

**Comment by PerJensen** [comment]
@mrclay Yes, and there's no reason to have two topbar menues. We could drop .elgg-menu-topbar-alt.

**Comment by mrclay** [comment]
I can do this as a plugin, just thinking if there are obviously non-BC improvements we could make in very little time.

![no_topbar](https://cloud.githubusercontent.com/assets/170687/8529358/645c5dcc-23e7-11e5-9a29-401687e88a7a.png)

**Comment by jdalsem** [comment]
There are some plugins that need the topbar, like notifications or login_as...

**Comment by mrclay** [comment]
My latest thinking on this: Topbar goes away, some items move into the navbar area on right, others into a new user account menu (similar to G+).

The new menu in the navbar area: (The gear would only be seen by admins and would open the admin lightbox currently in the developers plugin)
![01_tablet-layout](https://cloud.githubusercontent.com/assets/170687/12270939/b21fc4fc-b926-11e5-935b-42632d8dab3f.png)

The user account menu:
![03_topbar-hover1](https://cloud.githubusercontent.com/assets/170687/12270940/b2205192-b926-11e5-8dad-8a3d7d03da4f.png)
![04_topbar-hover2](https://cloud.githubusercontent.com/assets/170687/12270942/b22990e0-b926-11e5-835a-c69a77a61dfb.png)

**Comment by hypeJunction** [comment]
I like the looks of it. A lot cleaner. 
Not sure what "new user account menu" means - if it's adding a new menu to core, I beg you not to. Can we leverage user_hover menu for that?

**Comment by mrclay** [comment]
This was done in https://github.com/mrclay/Elgg-mrclay_aalborg, which works in 1.12. I don't think I added a menu, but I doubt I handled it super cleanly.

**Comment by mrclay** [comment]
Replaced by #10201
