### ISSUE TITLE
chore make groups likeable again

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8703]
#8701 made groups not likeable, but they were likeable objects pre 2.0, so i guess we should restore that

**Comment by mrclay** [comment]
How did one like a group in 1.x and where did it show up?

**Comment by hypeJunction** [comment]
API allowed liking objects and groups, but not users. I don't think there was any UI for it.

**Comment by mrclay** [comment]
So why must we make groups likable if there's no UI? It's a species case few would know about.

**Comment by mrclay** [comment]
It would make sense to bring a sensible UI to core or let the plugin that does it also make it likable.

**Comment by jdalsem** [comment]
Good question! You were able to like them via the river activity (user created group X). On group listings though, they the like menu items were visually stripped (however not the likes count). So you could like via the river and view on the listing page. That is why i would like to have it available as it was possible (and it makes sense).

**Comment by jdalsem** [comment]
users where hardcoded not allowed to be liked, but groups were not.

**Comment by mrclay** [comment]
Ok. SGTM. Liking a creation action is a weird proxy for liking the thing, but that's a river design quirk. If I want to like a group I have to go dig in the river... Very odd UX.

**Comment by mrclay** [comment]
...I guess really we're abusing liking groups to allow liking the creation event. Another reason for river items to be entities. I'll shut up now :)

**Comment by jdalsem** [comment]
> Ok. SGTM. Liking a creation action is a weird proxy for liking the thing, but that's a river design quirk. If I want to like a group I have to go dig in the river... Very odd UX.

I didn't say it was a good practice, however i did not want people to lose functionality. Besides i use liking groups a lot in templates.

**Comment by mrclay** [comment]
Yeah, I'm fine keeping our vestigial quirks for BC. If you use it a lot, should we consider adding UI to core? It could go in as a default-off setting in 2.1, eg.

**Comment by jdalsem** [comment]
> Yeah, I'm fine keeping our vestigial quirks for BC. If you use it a lot, should we consider adding UI to core? It could go in as a default-off setting in 2.1, eg.

Fine by me...

**Comment by hypeJunction** [comment]
Well, given it was a plugin quirk, I says that the plugin in question can
just use the hook and make groups likeable again. It just takes one line of
code for the plugin, and hours of maintenance overhead for core...

**Comment by jdalsem** [comment]
Huh? It is just 1 line for core to make it likeable again. Just do that. Plugins can take care of extra UI then...

**Comment by hypeJunction** [comment]
Well, if you make it likeable, the like button will show in summary view,
but it won't show on group profile. Smells like bad UX

**Comment by jdalsem** [comment]
Currently it will not show in summary AND profile, but only on river activity. May be bad UX, but not breaking change (for bundled plugins)

**Comment by hypeJunction** [comment]
IMHO, it will show in summary view if you make groups likeable. I thought the whole point of this ticket was to remove randomly showing Likes menu in summary and river views:
https://github.com/Elgg/Elgg/blob/master/mod/likes/start.php#L99
https://github.com/Elgg/Elgg/blob/master/mod/likes/start.php#L157

**Comment by jdalsem** [comment]
Nope... this ticket is only created to allow the groups entity to be likeable again (as it was pre 2.0). Not for the UI to change.

**Comment by hypeJunction** [comment]
I meant the original https://github.com/Elgg/Elgg/pull/8701
As it currently stands, making groups likeable affects the UI. I don't really care either way, as I don't use bundled likes plugin on any of the client sites.

**Comment by jdalsem** [comment]
> As it currently stands, making groups likeable affects the UI.

Still don't see why this is the case...

**Comment by hypeJunction** [comment]
Any likeable entity gets a menu item thanks to:
```php
elgg_register_plugin_hook_handler('register', 'menu:river', 'likes_river_menu_setup', 400);
elgg_register_plugin_hook_handler('register', 'menu:entity', 'likes_entity_menu_setup', 400);
```

**Comment by jdalsem** [comment]
true, but Groups always removed them nonetheless 
https://github.com/Elgg/Elgg/blob/master/mod/groups/start.php#L377

**Comment by hypeJunction** [comment]
Seems like that defeats the purpose of making groups likeable then...
Either we should make groups likeable with UI on summary and profile, or
keep them unlikeable, remove extra code fron the menu hook and and let the
plugins care about the permissions and the UI.

**Comment by jdalsem** [comment]
> Seems like that defeats the purpose of making groups likeable then...

Not true. If an entity is likeable is not related to this visual choice to limit the amount of items in the menu.

Improving the likeability of groups is another ticket.

**Comment by hypeJunction** [comment]
It's not about visual choices, but consistency.
