### ISSUE TITLE
Allow passing parameters to toObject()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8708]
It would be helpful to provide some parameters to describe expected output, e.g. specifying whether you want recursive export.

**Comment by mrclay** [comment]
I think the user is a better judge of what (s)he'd want from a recursive operation and how that data would be structured. You might want all contained objects, I might want just counts. I guess feel free to propose what "recursive" would look like to you.

**Comment by hypeJunction** [comment]
I don't suggest specifying arguments, rather adding an array of params,
which propagate to the hook handler. Similar to what we did with
getIconUrl()

**Comment by mrclay** [comment]
:+1:
