### ISSUE TITLE
Duplicate plugin code in master and repo

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8712]

**Comment by ewinslow** [comment]
Where exactly? I thought I got all of these except maybe one in the admin area

**Comment by iionly** [comment]
It might occur only if you install it via composer. Get the plugins pulled from separate repos then?

I found the .live in

<document root>/mod/messageboard/views/default/messageboard/js.php

while it isn't in

<document root>/vendor/elgg/elgg/mod/messageboard/views/default/messageboard/js.php

**Comment by ewinslow** [comment]
Yea, that sounds like the problem.

**Comment by jdalsem** [comment]
there is no .live in the master branch in this file

**Comment by iionly** [comment]
But it still is in https://github.com/Elgg/messageboard/blob/master/views/default/messageboard/js.php and when doing a composer-based install of Elgg 2.0 (starter-project) the bundled plugins get fetched from their separate repos.

I guess the reason is that https://github.com/Elgg/Elgg/pull/8696 is still WIP.

**Comment by jdalsem** [comment]
Hmmm i do not like it that Elgg already has seperate repos without them being maintained. Those seperate repos are out of date. Maybe someone from @Elgg/owners can shed some light on the plans for these repos

**Comment by mrclay** [comment]
We're working to automate syncing them from Elgg/Elgg. I hope their descriptions will mention that they're read-only subtree splits off of Elgg, e.g. like the Symfony component repos.

**Comment by ewinslow** [comment]
There is much disagreement on this topic, unfortunately. I personally would like to see them either managed completely separately or deleted entirely.

**Comment by mrclay** [comment]
I'm fine with re-opening #5945 for more discussion.

**Comment by iionly** [comment]
@mrclay regardless if discussing here or in https://github.com/Elgg/Elgg/issues/5945. One of the issues should be open for discussion until there's a decision of what to do and the problem is fixed in some way.
