### ISSUE TITLE
Files gallery/list toggle should go in page menu

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8718]
...not in the "extras" where it will likely be missed.

**Comment by jdalsem** [comment]
Is title menu also an option? Page menu is probably ending up somewhere in the right bottom...

**Comment by mrclay** [comment]
...I'm about to propose moving the page menu above the owner block :)

**Comment by mrclay** [comment]
Actually, page menu is usually for different content. Logical place would be next to the tabs (right above the listing it affects).
