### ISSUE TITLE
Move example settings to install/config/?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8719]
That's where htaccess.dist is.

**Comment by jdalsem** [comment]
Makes sense

**Comment by iamjoross** [comment]
Hello, is this still an issue?

**Comment by jdalsem** [comment]
yes... but it is not really important, why do you ask?

**Comment by jdalsem** [comment]
@mrclay if you do this you can completely ignore your elgg-config folder... i believe you were touching this recently?

**Comment by mrclay** [comment]
Now that 2.3 sites are using it I don't see much value in ditching it.

**Comment by jdalsem** [comment]
we are not ditching it, only moving the example file to a more logical location

i am fine not pursuing this further though
