### ISSUE TITLE
Cannot change the extension of assets in views

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8721]
E.g. while you can map pdf.**jpg** to the view "file/icons/pdf.**gif**", simplecache will still serve it as "image/gif". Same problem would go occur converting to SVG, or overriding an MP3 with an OGG, etc.

I think any solution would require some sort of client-side aliasing data.

**Comment by ewinslow** [comment]
Yea, it'd be nice if this "just worked"...

**Comment by ewinslow** [comment]
Simplecache would have to be able to look at the extension of the file that defines that view, I guess?

**Comment by jdalsem** [comment]
Not worth the effort to fix this. Both approaches have downsides. There are not that many usecases that require this behaviour. If so, there is also the option to change the URL.
