### ISSUE TITLE
New user registers on the site, the administrator does not receive notification.

### ISSUE THREAD

**Issue by olairmarcos** [Elgg/Elgg#8725]
New user registers on the site, the administrator does not receive notification. This feature is important for when the administrator needs to manually make the approval of the new user.

**Comment by mrclay** [comment]
Someone on the community may know a plugin that does admin-approved registration. It's not built into core.

**Comment by jdalsem** [comment]
This plugin provides uservalidation by admin and will also notify admins on new subscriptions 
https://github.com/ColdTrick/uservalidationbyadmin
