### ISSUE TITLE
Pages: Move content above metadata

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8726]
At the very least I think we should make the content more prominent in some way.

**Comment by mrclay** [comment]
<img width="761" alt="content-first" src="https://cloud.githubusercontent.com/assets/170687/8638391/10770cc0-2888-11e5-9615-6d0fd938cf0e.png">

**Comment by iionly** [comment]
Why? This would be inconsistent with any other type of content then, wouldn't it?

**Comment by mrclay** [comment]
Just brainstorming I guess. I don't see Pages as blog post or other user content. In my experience they're often used to substitute for a wiki, not *personal* content.

**Comment by jdalsem** [comment]
> Why? This would be inconsistent with any other type of content then, wouldn't it?

Agreeing with this comment
