### ISSUE TITLE
Wrong (or at least unnecessary) rewrite rule on zip install of Elgg 2.0

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8732]
.htaccess contains the rewrite rule
```
RewriteRule ^(_graphics|js)/(.*)$ vendor/elgg/elgg/$1/$2
```
This makes no sense at least when installing Elgg 2.0 using a zip archive. I don't know if it might even result in issues.

**Comment by mrclay** [comment]
All these files are now served via /cache. I think this was left behind when we put _graphics back into place. It can be removed right @ewinslow?

**Comment by ewinslow** [comment]
Ya

**Comment by mrclay** [comment]
@iionly wanna submit a PR to remove this?

**Comment by iionly** [comment]
Maybe I'll manage next weekend.
