### ISSUE TITLE
master: .elgg-icon smaller than in 1.x

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8733]
Problem is that the Fontawesome icons seem to be smaller (they look much too small for my liking!) or at least they are not aligned in the same way as the icons were aligned on 1.X.

For example, replacing the old elgg-icon-delete icon (used with ```<div class='elgg-icon elgg-icon-delete'>```) with the new way of getting the icon to show (```elgg_view_icon('delete')```) the Fontawsome icon is slightly too low aligned in relation to the surrounding elements.

**Comment by iionly** [comment]
Oh great! Alignment within Elgg core is alright. It's just no longer right for 3rd party plugins. Now how to fix that? I'm beginning to tend towards using just my own set of icons within my plugins and no longer care about consistency - especially as I think that the fontawesome icons are just too small and using "fa-lg" doesn't seem to work either.

**Comment by PerJensen** [comment]
> they look much too small for my liking!

Default size can be changed in elements/icons.css

**Comment by iionly** [comment]
I don't think so.

You can increase the width/height of the area reserved to icons in elements/icon.css but this won't result in the icons being larger as the icon images used will stay the same.

The font awesome icons will only work when using either elgg_view_icon(), e.g. elgg_view_icon('delete') or if using <div class='elgg-icon fa fa-times'></div> (meaning the old <div class='elgg-icon elgg-icon-delete'></div> won't work anymore at all).

The icons of the fa class seem to me to be slightly smaller than the old Elgg icons of Elgg 1.X (probably too small for small screens / touchscreens). There are other fa classes available (fa-lg, fa-2x etc.) that would display larger icons but using these classes doesn't work at all (tried it within a div directly and also by changing the fa class to be used in output/icons.php where the icon mapping is done). If you ask me, there should be fa-lg used at least instead of fa or it should at least work to change the class used.

**Comment by mrclay** [comment]
Ideally we wouldn't set the font-size of elgg-icon at all and let it display inheriting from surrounding text. If you want to A/B these visually and choose a more precise font-size (currently 16px) or vertical-align value to match the old ones, we could do that.

**Comment by mrclay** [comment]
If it wasn't made clear, the FA "icons" are font glyphs, so font-size, vertical-align, color, etc. all can be used to adjust them.

**Comment by iionly** [comment]
I realized that I tried the "fa-lg" icons in the wrong way. It's not "la-lg" instead of "fa" but rather "fa fa-lg" in output/icons.php.

@Steve: removal of font-size in icon.css.php sounds good (not to forget also to change it in Aalborg theme as I just had to learn...). Without font-size (or at least increasing it) it would also work with larger fontawesome icons ("fa fa-lg" instead of "fa" only).

Alignment issue is caused by css of the plugin I tried it with. This explains then also why the alignment for example in the entity menu of Elgg core was right but not with the custom icon added by this plugin.

**Comment by mrclay** [comment]
To my eyes, font-size: 18px is closer to the size of the old icons overall.

**Comment by iionly** [comment]
Align issue is not an issue actually. I had some margin added within the plugin to get the alignment of the custom icon used with the 1.X icons, so I would have to change / remove this margin within the plugin for 2.X.

But the wrong alignment with this custom icon only became noticeable on 2.X because the fa icons are smaller (at least displayed smaller than the old icons).

With an increase to 18 - 20 px seems the fa icons seem to match the old icons in size. Even with 22 px they might not be too large, yet (thinking of think fingers on small touchscreens...). But then the tiny avatar might look too small beside an icon (e.g. in topbar).

**Comment by juho-jaakkola** [comment]
I agree the icons should be larger by default.

**Comment by ewinslow** [comment]
@iionly want to submit a PR for this? 

For whoever takes this on: would help to have before/after screenshots attached to the PR.

**Comment by iionly** [comment]
I don't know if I will have any time to provide a PR in the near future.

**Comment by juho-jaakkola** [comment]
I'm currently working almost full time on a 2.0 project, so I will fix this this sooner or later. Cannot say when exactly.

**Comment by juho-jaakkola** [comment]
Additional problem is that the glyphs themselves have different sizes despite having the same font size.

For example ```fa-users``` uses much more of the available space than ```fa-remove```:

![fa-icons](https://cloud.githubusercontent.com/assets/883920/9273286/df31ddea-4293-11e5-9bfb-333882aee7b0.png)

This is caused partly by the fact that the remove icon *isn't* really a remove icon but an alias for "times" icon (as in "2 times 3 equals 6"). So in a way this is a design flaw in Font awesome.

We could define icon specific font sizes, but IMO that would be hacky.

I'll look into fa issue tracker and see if anyone else has reported anything similar.

**Comment by juho-jaakkola** [comment]
Based on the issue tracker Font awesome seems to have a lot of problems with consistency.

This issue https://github.com/FortAwesome/Font-Awesome/issues/1540 might improve the size of the delete icon, but the style is quite different from what Elgg users are used to. (Also the issue is still unresolved.)

I guess at this point the only way to fix the inconsistencies is to define font-size separately for each icon.

Something like ```font-size: larger;``` might be a good approach because that way sites could still define the base size for all icons using a single CSS selector.
