### ISSUE TITLE
Why no default elgg-icon-* classes anymore on Elgg 2.0?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8734]
Replacing the underlying icons with Fontawsome icons is one thing. But why dropping the icon classes? If only the icons would have been replaced it wouldn't have been necessary to make any updates in the code of plugins to get them working on 2.0. Now it's necessary change the code - and not only the class name but also change to elgg_view_icon().

With the icon classes still available there would also be some kind of consistency possible, e.g. the same icon for the same functionality throughout the site. With the plugin dev having the choice to select any Fontawesome icon for a specific purpose it's much harder to achieve consistency.

**Comment by mrclay** [comment]
It's my understanding that elgg_view_icon() uses a mapping of legacy icon names to new FA names. I wasn't too involved in that change, maybe you can look up the PR.

If we can increase BC, I'd be for it.

**Comment by iionly** [comment]
elgg_view_icon() does the mapping. But it's no longer possible to use the elgg-icon-* classes, i.e.
```
<div class='elgg-icon elgg-icon-delete'></div>
```
does no longer work simply because the elgg-icon-* classes were removed.

Wouldn't it have been an alternative to just change the icons within the elgg-icon-* classes to the fa icons instead of removing the icons?

**Comment by mrclay** [comment]
Yes. We should probably try to do that.

**Comment by hypeJunction** [comment]
Precisely my objections to https://github.com/Elgg/Elgg/pull/8578

**Comment by mrclay** [comment]
Does anyone wanna step up to fix these? Is reverting to the 1.x icons really an option? @jeabakker @jdalsem @ewinslow

**Comment by iionly** [comment]
I wouldn't say reverting to the old icons would be necessary but only adding the old icon classes then using the fa icons (same class name, different icon).

**Comment by jeabakker** [comment]
what would be the use case for NOT using elgg_view_icon()? In some of my old code i didn't use elgg_view_icon(), but i'm working on removing the old code.

So i'm very interested in the use case

**Comment by hypeJunction** [comment]
Not all HTML is generated with PHP. It should be possible to build a mock
HTML page using nothing but tags. Plus one may want to replace the icon
using JS. A plugin can't know what icon system the theme is using, so
.elgg-icon classes should deliver the icons without the plugin knowing the
vendor library used for icons.

**Comment by mrclay** [comment]
This is a new major version and we haven't promised to support whatever static markup in a plugin forever. It's never been easier to use PHP to generate static view files.

That said, if someone wants to make a BC version of all the FA icon classes (and basically map the rest of fa- into elgg-icon-, I'm fine with that.

**Comment by mrclay** [comment]
Essentially the goal would be that `class="elgg-icon elgg-icon-exclamation-triangle"` would be enough, for all the FA icon names.

Who wants to take that on very soon?

**Comment by mrclay** [comment]
Even if we revert, we can easily add the better implementation in a separate plugin and pull it in in 2.1.

**Comment by hypeJunction** [comment]
Here is the sass map if anyone wants to take up on it, I don't care about it enough to invest time:

```sass


.elgg-icon-arrow-left:before  {
	content: $fa-var-arrow-left;
}
.elgg-icon-arrow-right:before  {
	content: $fa-var-arrow-right;
}
.elgg-icon-arrow-two-head:before  {
	content: $fa-var-arrows-h;
}
.elgg-icon-attention:before  {
	content: $fa-var-exclamation-triangle;
}
.elgg-icon-attention-hover:before  {
	content: $fa-var-exclamation-triangle;
	color: $primary-color;
}
.elgg-icon-calendar:before  {
	content: $fa-var-calendar;
}
.elgg-icon-cell-phone:before  {
	content: $fa-var-phone;
}
.elgg-icon-checkmark:before  {
	content: $fa-var-check;
}
.elgg-icon-checkmark-hover:before  {
	content: $fa-var-check;
	color: $primary-color;
}
.elgg-icon-clip:before  {
	content: $fa-var-paperclip;
}
.elgg-icon-clip-hover:before  {
	content: $fa-var-paperclip;
	color: $primary-color;
}
.elgg-icon-cursor-drag-arrow:before  {
	content: $fa-var-times;
}
.elgg-icon-delete-alt:before  {
	content: $fa-var-times-circle;
}
.elgg-icon-delete-alt-hover:before  {
	content: $fa-var-times-circle;
	color: $primary-color;
}
.elgg-icon-delete:before  {
	content: $fa-var-times;
}
.elgg-icon-delete-hover:before  {
	content: $fa-var-times;
	color: $primary-color;
}
.elgg-icon-download:before  {
	content: $fa-var-download;
}
.elgg-icon-download-hover:before  {
	content: $fa-var-download;
	color: $primary-color;
}
.elgg-icon-eye:before  {
	content: $fa-var-eye;
}
.elgg-icon-facebook:before  {
	content: $fa-var-facebook;
}
.elgg-icon-grid:before  {
	content: $fa-var-th;
}
.elgg-icon-grid-hover:before  {
	content: $fa-var-th;
	color: $primary-color;
}
.elgg-icon-home:before  {
	content: $fa-var-home;
}
.elgg-icon-home-hover:before  {
	content: $fa-var-home;
	color: $primary-color;
}
.elgg-icon-hover-menu:before {
	content: $fa-var-toggle-down;
}
.elgg-icon-hover-menu-hover:before {
	content: $fa-var-toggle-down;
	color: $primary-color;
}
.elgg-icon-info:before  {
	content: $fa-var-info;
}
.elgg-icon-info-hover:before {
	content: $fa-var-info-circle;
	color: $primary-color;
}
.elgg-icon-link:before  {
	content: $fa-var-link;
}
.elgg-icon-link-hover:before  {
	content: $fa-var-link;
	color: $primary-color;
}
.elgg-icon-list:before  {
	content: $fa-var-th-list;
}
.elgg-icon-lock-closed:before  {
	content: $fa-var-lock;
}
.elgg-icon-lock-open:before  {
	content: $fa-var-unlock;
}
.elgg-icon-mail-alt:before  {
	content: $fa-var-envelope-o;
}
.elgg-icon-mail-alt-hover:before  {
	content: $fa-var-envelope-o;
	color: $primary-color;
}
.elgg-icon-mail:before  {
	content: $fa-var-envelope;
}
.elgg-icon-mail-hover:before  {
	content: $fa-var-envelope;
	color: $primary-color;
}
.elgg-icon-photo:before  {
	content: $fa-var-picture-o;
}
.elgg-icon-print-alt:before  {
	content: $fa-var-print;
}
.elgg-icon-print:before  {
	content: $fa-var-print;
}
.elgg-icon-push-pin-alt:before  {
	content: $fa-var-bookmark;
}
.elgg-icon-push-pin:before  {
	content: $fa-var-thumb-tack;
}
.elgg-icon-redo:before  {
	content: $fa-var-repeat;
}
.elgg-icon-refresh:before  {
	content: $fa-var-refresh;
}
.elgg-icon-refresh-hover:before  {
	content: $fa-var-refresh;
	color: $primary-color;
}
.elgg-icon-round-arrow-left:before  {
	content: $fa-var-arrow-circle-o-left;
}
.elgg-icon-round-arrow-right:before  {
	content: $fa-var-arrow-circle-o-right;
}
.elgg-icon-round-checkmark:before  {
	content: $fa-var-check-square-o;
}
.elgg-icon-round-minus:before  {
	content: $fa-var-minus-circle;
}
.elgg-icon-round-plus:before  {
	content: $fa-var-plus-circle;
}
.elgg-icon-rss:before  {
	content: $fa-var-rss;
}
.elgg-icon-search-focus:before  {
	content: $fa-var-search;
}
.elgg-icon-search:before  {
	content: $fa-var-search;
}
.elgg-icon-settings-alt:before  {
	content: $fa-var-cog;
}
.elgg-icon-settings-alt-hover:before  {
	content: $fa-var-cog;
	color: $primary-color;
}
.elgg-icon-settings:before  {
	content: $fa-var-cogs;
}
.elgg-icon-share:before  {
	content: $fa-var-share;
}
.elgg-icon-share-hover:before  {
	content: $fa-var-share;
	color: $primary-color;
}
.elgg-icon-shop-cart:before  {
	content: $fa-var-shopping-cart;
}
.elgg-icon-shop-cart-hover:before  {
	content: $fa-var-shopping-cart;
	color: $primary-color;
}
.elgg-icon-speech-bubble-alt:before  {
	content: $fa-var-comments;
}
.elgg-icon-speech-bubble-alt-hover:before  {
	content: $fa-var-comments;
	color: $primary-color;
}
.elgg-icon-speech-bubble:before  {
	content: $fa-var-comment;
}
.elgg-icon-speech-bubble-hover:before  {
	content: $fa-var-comment;
	color: $primary-color;
}
.elgg-icon-star-alt:before  {
	content: $fa-var-star;
	color: $alert-color;
}
.elgg-icon-star-empty:before  {
	content: $fa-var-star-o;
}
.elgg-icon-star-empty-hover:before  {
	content: $fa-var-star-o;
	color: $primary-color;
}
.elgg-icon-star:before  {
	content: $fa-var-star;
}
.elgg-icon-star-hover:before  {
	content: $fa-var-star;
	color: $primary-color;
}
.elgg-icon-tag:before  {
	content: $fa-var-tag;
}
.elgg-icon-tag-hover:before  {
	content: $fa-var-tag;
	color: $primary-color;
}
.elgg-icon-thumbs-down-alt:before  {
	content: $fa-var-thumbs-o-down;
}
.elgg-icon-thumbs-down-alt-hover:before  {
	content: $fa-var-thumbs-o-down;
	color: $primary-color;
}
.elgg-icon-thumbs-down:before  {
	content: $fa-var-thumbs-down;
}
.elgg-icon-thumbs-down-hover:before  {
	content: $fa-var-thumbs-down;
	color: $primary-color;
}
.elgg-icon-thumbs-up-alt:before  {
	content: $fa-var-thumbs-o-up;
}
.elgg-icon-thumbs-up-alt-hover:before  {
	content: $fa-var-thumbs-o-up;
	color: $primary-color;
}
.elgg-icon-thumbs-up:before  {
	content: $fa-var-thumbs-up;
}
.elgg-icon-thumbs-up-hover:before  {
	content: $fa-var-thumbs-up;
	color: $primary-color;
}
.elgg-icon-trash:before  {
	content: $fa-var-trash-o;
}
.elgg-icon-twitter:before  {
	content: $fa-var-twitter;
}
.elgg-icon-undo:before  {
	content: $fa-var-undo;
}
.elgg-icon-user:before  {
	content: $fa-var-user;
}
.elgg-icon-user-hover:before  {
	content: $fa-var-user;
	color: $primary-color;
}
.elgg-icon-users:before  {
	content: $fa-var-users;
}
.elgg-icon-users-hover:before  {
	content: $fa-var-users;
	color: $primary-color;
}
.elgg-icon-video:before  {
	content: $fa-var-film;
}
```

**Comment by iionly** [comment]
What I still don't understand is how it will be possible to avoid conflicts between plugins with the definition of the mapping included in output/icon.php. It has been mentioned that it's trivial to make adjustments by "changing only one file". But as I see it you would have to override this file for any changes to take effect. How will this work with two plugins overriding it?

**Comment by mrclay** [comment]
You can add your CSS to elgg.css (later or more specific selectors) for one. Otherwise, yeah, we need to refactor this based on our goals of extensibility. How do you think it should work?

**Comment by iionly** [comment]
The only other option to allow for configuration of icons used seems to introduce a plugin hook. Though I'm not sure it this would be a better (e.g. easier to use) option. If the elgg-icon-* classes would be defined in css it would also work without the need of a plugin hook, right?

**Comment by iionly** [comment]
Closing due to lack of interest. If I'm in need to have some elgg-icon classes for myself I will create them on my own.
