### ISSUE TITLE
Breaking change in elgg_is_xhr()?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8735]
Can't track down the commit that changed the behaviour of ```elgg_is_xhr()```. I have noticed this in 1.12 branch, but this could have happened earlier. 
This function used to check the query parameter as well as the headers, now it only checks the header using Symfony request. This breaks the output for some JS that was passing ```X-Requested-With``` as a URL query parameter.

**Comment by hypeJunction** [comment]
In case anyone else encounters this problem while using jquery.form plugin: removing ```iframe``` option rectifies the issue in modern browsers, as the plugin is capable of handling file uploads without using iframes.

**Comment by mrclay** [comment]
If jquery.form uses iframes by default, I think we should issue a fix and add query checking back in.

**Comment by mrclay** [comment]
It used to check all input: https://github.com/Elgg/Elgg/commit/6e05a5d7486ede1c8408144b823b895c6282f270

**Comment by mrclay** [comment]
FYI elgg.embed.submit() sets `X-Requested-With` in the data (specifically for iframe handling), so we shouldn't have removed this.

**Comment by mrclay** [comment]
PR #9443
