### ISSUE TITLE
Getting logged in at community site with foreign account!!!

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8736]
So far it hasn't happened to me but it seems it has happened several times now and I think this is VERY serious: https://community.elgg.org/discussion/view/2204605/what-happened-to-my-account

Maybe it has something to do with persistent login. As far as I remember there was some change made not too long ago in connection with that (don't remember the commit though at the moment).

Possibly there are spammers involved here as all foreign accounts seem to be of spammers. But something is very fishy here...

**Comment by iionly** [comment]
Changlog of 1.11 revealed the issue I had in mind: https://github.com/Elgg/Elgg/issues/8104 fixed with https://github.com/Elgg/Elgg/pull/8303.

I don't know if this commit has anything to do with the login to foreign accounts problem.

**Comment by mrclay** [comment]
All I can think to do is revert #8303 and live with the occasional fatal errors during login until we can get another fix in or seriously study this system. I can't fathom how this is happening.

**Comment by mrclay** [comment]
Here's a start: #8737

**Comment by mrclay** [comment]
@iionly and @Elgg/contributors I'd really appreciate giving the class Elgg\PersistentLoginService (and its integration points) a look over to see if there's just something I'm not seeing here.

**Comment by hypeJunction** [comment]
Could this anyhow be related to reduced enthropy due to Crypto notices we have been seeing?

**Comment by mrclay** [comment]
I suppose, though I don't see see any such warnings in current error_log.

**Comment by mrclay** [comment]
There are no duplicate or empy codes in the remember me table. Low entropy could still be an issue but it seems more unlikely. We should look into what's being stored in APC.

**Comment by mrclay** [comment]
It looks like we need to remove the unique index on the `timestamp` column, though it may not fix this problem. Why would we want to prohibit codes from being created on the same second?

**Comment by mrclay** [comment]
@hypeJunction I think you're right. If ElggCrypt were occasionally giving users the same remember me tokens, this would all make sense:

User A logs in and gets an Elggperm cookie with token T (I'm ignoring hashing for simplification here). Later, User B logs in and is given the same token T.

Before #8303, the insert would fail with a fatal error due to duplicate token, so user B would never be sent the Elggperm cookie with T (that came after the insert).

After #8303, on user B's login we delete T from the table and re-insert it now linked to user B. So later when user A loses his regular session, the system looks at his cookie T, linking him now to user B.

**Comment by mrclay** [comment]
That suggests 1. the old logic of relying on the primary key to avoid duplicates was a good idea, and 2. we need to focus on a fix to #8603 and vet the token generation process in general.

**Comment by mrclay** [comment]
My research in https://github.com/Elgg/Elgg/issues/8603#issuecomment-121736471 I think removes the hypothesis of generating duplicate tokens. So it's more likely they're getting passed between users some way.

**Comment by hypeJunction** [comment]
It seems to me that the cookie should also identify the user/device and we should match the id with the remember me token. Perhaps we can suffix the token with sha of the guid and token time/last login time.

**Comment by mrclay** [comment]
I've considered that, too but that's just recognizing defeat that those cookies are leaking between users.

I haven't heard of this problem on any other Elgg site. Have you? I need to dive into community's plugins.

**Comment by hypeJunction** [comment]
I have seen odd errors popping up during upgrades, but nothing that would indicate a problem with identical cookies. I believe we had an issue on one of the sites that looked similar, @beck24 did the debugging, so he may shed some light.

**Comment by mrclay** [comment]
I've got #8737 ready, which would fix the ElggCrypto bug and bail on the persistent login if a hash were already detected. If the issue continues on community.elgg, we'd know that the tokens leaking between users is the way it's happening, not by ElggCrypt generating dupe hashes.

**Comment by beck24** [comment]
I'm not sure which problem @hypeJunction is referring to, but I haven't seen anything like this one

**Comment by mrclay** [comment]
I created #8742 for deployment on community to gather info. PTAL if you have time.

**Comment by beck24** [comment]
That looks good to me, lets get it on community and see what happens...

**Comment by mrclay** [comment]
Nothing from the logging code yet. Even if it happens it won't point out how a user ended up with another's Elggperm cookie, which is what I think is happening.

**Comment by mrclay** [comment]
I think we should review and merge #8737 and leave community on a branch with the extra logging code for now.

And aggressively review all community plugins for cookie/session usage, but I'm not taking that on by myself.

**Comment by mrclay** [comment]
No logged incidents since putting that code in place, and I haven't seen anything on community about it. Regardless, the ElggCrypto bug is real so I think #8737 needs some consideration.
