### ISSUE TITLE
More generalization and flexibilty for NotificationService

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8740]
Let's consider a scenario which we want register a notification event with a arbitrary actor not the forced one (i.e. the logged in user) provided right now.
I tried to achieve this by using a hook that is triggered in `enqueueEvent(...)` method of `NotificationsService` class:

``` php
...
$params = array(
    'action' => $action,
    'object' => $object,
);
$registered = $this->hooks->trigger('enqueue', 'notification', $params, $registered);
...
if ($registered) {
    $this->queue->enqueue(new \Elgg\Notifications\Event($object, $action));
}
```

I though that I could create my own `Event` with arbitrary "actor" and add it to the queue and then return false in the called hook handler. But I couldn't do something like this while we couldn't access `queue`, which is protected, in the hook handler.
I believe we need more flexible solutions to enqueue the notification events and I think one of available solution could be the one I tried to do.

**Comment by SirbitoX** [comment]
There isn't any way to pass "actor" to ``` enqueueEvent(...) ``` method?? This could be a better solution?

**Comment by juho-jaakkola** [comment]
What is the use case?

**Comment by SirbitoX** [comment]
@juho-jaakkola The main case of suggesting more flexibility is when a the actor and the subscribed user is the same the notification isn't sent.
But let's consider that we want to send a notification (using queue) to user when s/he changes her/his password. According to admin's accesses, admin can change the user's password, either. So the actor of the notification will be admin instead of the user.
In the other cases that we want notify any user using queued notifications whose actor is the same user we encountered this problem.

**Comment by juho-jaakkola** [comment]
So in your use cases the notification will be sent only to a single user? In a case like this you should be using the ```notify_user()``` function instead of the NotificationService. Is there a reason that prevents that?

**Comment by SirbitoX** [comment]
I'm aware of ``` notify_user() ``` function but it will send the notification instantly on the action and it slows down the page loading and web server responding.
In future I plan to use the tools such as "celery" to send notifications and I prefer to use "NotificationService" totally.

**Comment by jdalsem** [comment]
Closing this. You can pass `actor` to `Elgg\Notifications\Event`. This can be any `ElggEntity`. Not being able to receive notifications from yourself will be tracked in this ticket #7754
