### ISSUE TITLE
master: fatal error on login (log table crashing)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8741]
It happened now twice in two days that the error_log table crashed on login (as admin) on a 2.0alpha1 test installation (installed with zip). I never had any issues with tables crashing on this server in years, so I suspect something is wrong with 2.0alpha1.

Error log entry is:

[Wed Jul 15 20:19:32.662482 2015] [php5:error] [pid 6614] [client 127.0.0.1:47069] Exception #1436984372: exception 'DatabaseException' with message 'An exception occurred while executing 'INSERT DELAYED into elgg_system_log\n\t\t\t\t(object_id, object_class, object_type, object_subtype, event,\n\t\t\t\tperformed_by_guid, owner_guid, access_id, enabled, time_created, ip_address)\n\t\t\tVALUES\n\t\t\t\t('39','ElggUser','user', '', 'login:before',\n\t\t\t\t0, 0, 2, 'yes', '1436984372', '127.0.0.1')':\n\nSQLSTATE[HY000]: General error: 145 Table './elgg20zip/elgg_system_log' is marked as crashed and should be repaired\n\n QUERY: INSERT DELAYED into elgg_system_log\n\t\t\t\t(object_id, object_class, object_type, object_subtype, event,\n\t\t\t\tperformed_by_guid, owner_guid, access_id, enabled, time_created, ip_address)\n\t\t\tVALUES\n\t\t\t\t('39','ElggUser','user', '', 'login:before',\n\t\t\t\t0, 0, 2, 'yes', '1436984372', '127.0.0.1')' in /home/xxx/public_html/elgg20zip/engine/classes/Elgg/Database.php:413\nStack trace:\n#0 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/Database.php(241): Elgg\\Database->executeQuery('INSERT DELAYED ...', Object(Doctrine\\DBAL\\Connection))\n#1 /home/xxx/public_html/elgg20zip/engine/lib/database.php(81): Elgg\\Database->insertData('INSERT DELAYED ...')\n#2 /home/xxx/public_html/elgg20zip/engine/lib/system_log.php(249): insert_data('INSERT DELAYED ...')\n#3 /home/xxx/public_html/elgg20zip/engine/lib/system_log.php(304): system_log(Object(ElggUser), 'login:before')\n#4 [internal function]: system_log_default_logger('log', 'systemlog', Array)\n#5 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/EventsService.php(56): call_user_func_array('system_log_defa...', Array)\n#6 /home/xxx/public_html/elgg20zip/engine/lib/elgglib.php(588): Elgg\\EventsService->trigger('log', 'systemlog', Array)\n#7 /home/xxx/public_html/elgg20zip/engine/lib/system_log.php(322): elgg_trigger_event('log', 'systemlog', Array)\n#8 [internal function]: system_log_listener('login:before', 'user', Object(ElggUser))\n#9 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/EventsService.php(56): call_user_func_array('system_log_list...', Array)\n#10 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/EventsService.php(84): Elgg\\EventsService->trigger('login:before', 'user', Object(ElggUser))\n#11 /home/xxx/public_html/elgg20zip/engine/lib/elgglib.php(609): Elgg\\EventsService->triggerBefore('login', 'user', Object(ElggUser))\n#12 /home/xxx/public_html/elgg20zip/engine/lib/sessions.php(328): elgg_trigger_before_event('login', 'user', Object(ElggUser))\n#13 /home/xxx/public_html/elgg20zip/actions/login.php(52): login(Object(ElggUser), false)\n#14 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/ActionsService.php(131): include('/home/xxx/pu...')\n#15 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/ActionsService.php(120): Elgg\\ActionsService::includeFile('/home/xxx/pu...')\n#16 /home/xxx/public_html/elgg20zip/engine/lib/actions.php(20): Elgg\\ActionsService->execute('login')\n#17 [internal function]: _elgg_action_handler(Array, 'action')\n#18 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')\n#19 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/Application.php(385): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#20 /home/xxx/public_html/elgg20zip/engine/classes/Elgg/Application.php(341): Elgg\\Application->run()\n#21 /home/xxx/public_html/elgg20zip/index.php(8): Elgg\\Application::index()\n#22 {main}, referer: http://xxx.xxx/~xxx/elgg20zip/

**Comment by mrclay** [comment]
Are you using a different MySQL server? We need to remove the "DELAYED" in those queries and delay the query for shutdown.

In your case it looks like the table crashed (MyISAM, sigh) and needs to be repaired.

**Comment by iionly** [comment]
I'm using MariaDB 10.0. But I'm using it for quite some time already and so far never had any issues with Elgg 1.X.

**Comment by iionly** [comment]
I guess MariaDB is part of the problem. It not only happens with my 2.0 installations but also with my 1.X installations. The log table crashes each time after a server restart (or possible on server shutdown already). The only reason I've not noticed this before on the 1.X installations is probably due to using my no_logging plugin that turns off logging.

**Comment by iionly** [comment]
Archive engine wasn't loaded by MariaDB. So, my fault.
