### ISSUE TITLE
File object filenames are prone to collisions

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8749]
The file/upload action uses time() to ensure filenames are unique.

Ideally we'd save() first, then store under the GUID directory.

First site that hits this issue should fix it ;)

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/commit/09499677fa11b468c6a0771082d35ecdf73c02d4#diff-3d65181de6e2c77aa5509806b895f846
