### ISSUE TITLE
ElggEntity::create verifies the owner writable as container, even if that's not the container

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8774]
If you create an object in a group, ElggEntity::create will call `$owner->canWriteToContainer(0, $type, $subtype)` even though the $owner (you) will not be the container. This results in a `container_permissions_check` hook in which you are `$params['container']`, which is not at all true.

This  has worked so far because, up until now, handlers haven't really cared if the content was created under a user or a group. Instead, content placement was controlled upstream by UI code hiding forms from users, e.g.

For discussions, though, (and other types going forward) we want to use the container hook to determine whether that *subtype* can be created in the given container, a fairly reasonable usage. A few obvious solutions:

1. Don't check container for the owner if (s)he is not the real container. (potential BC issues)
2. Somehow let hook handlers know that this isn't the *real* container. (shouldn't affect existing code)

**Comment by mrclay** [comment]
@ewinslow PTAL and also at #8773. Obviously an alternative would be to remove the owner check from create(), but this seems safer for 2.0.

**Comment by mrclay** [comment]
#8773 takes approach 2, introducing a `checking_owner` flag. It might be better to simply add `$params['real_container']` to the hook!

**Comment by mrclay** [comment]
I'm going to try to assess when/why that owner check was added.

**Comment by hypeJunction** [comment]
I believe we have discussed this previously and I had opened a ticket a few
months back because I was running into this issue. You had some
reservations, so you may way to look back at that as well.

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/commit/792112a10ead7451933d2f9813ae050034b2b5a6

**Comment by mrclay** [comment]
From the commit I assume this was done to affect widget permissions. @hypeJunction can you find that ticket?

**Comment by mrclay** [comment]
Dupe of #4231
