### ISSUE TITLE
Add support for .env.php file that returns an array of environment-specific config

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8777]
This would effectively replace `settings.php`. I think the `.env.php` makes it clearer that it is supposed to be for environment-specific information, and the leading `.` communicates "private" more effectively.

Laravel had a .env.php for some time but opted instead for https://github.com/vlucas/phpdotenv.

It is probably worth at least looking into the reasons they went that route.

**Comment by jdalsem** [comment]
cc @mrclay

**Comment by mrclay** [comment]
The meat of this is done in [EnvReader](https://github.com/Elgg/Elgg/blob/e2db788fbeadc3094a670db07709b894ccff99a2/engine/classes/Elgg/Config/EnvReader.php), which translates the flat ENV keys into the structured values we have in $CONFIG->cookies and ->db.

**Comment by jdalsem** [comment]
does that mean we have support for an env file already?

**Comment by mrclay** [comment]
Not in master. But we could pretty easily allow env values to override settings.php. Problem is lots of 3rd-party code that reads settings.php directly, but there's no way to control that. The mrclay branch makes it easier to build a Elgg\Config standalone via a factory method.

**Comment by mrclay** [comment]
E.g. in settings.php we could allow
```php
// allow any ELGG_ env vars to override config
$CONFIG->allow_env_override = true;
```

**Comment by jdalsem** [comment]
not seeing this happen for 3.0

**Comment by hypeJunction** [comment]
This would make elite a lot easier, and shouldn't take so much effort given that @mrclay has done it already in his fork

**Comment by jdalsem** [comment]
still not a blocker for an Elgg 3.0 release as it could probably also be added in 3.1

**Comment by jdalsem** [comment]
Not going to pursue this
