### ISSUE TITLE
Widgets are always created with container = owner

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8779]
Seems like this could lead to permissions trouble.

**Comment by juho-jaakkola** [comment]
In what cases could it cause problems?

**Comment by mrclay** [comment]
I would think group widgets would be contained by the group. I don't know of any problems off hand, just might be a surprise to devs. If there's no real danger here we can close this.

**Comment by juho-jaakkola** [comment]
@jdalsem @jeabakker How is ColdTrick/widget_manager handling this?

**Comment by jdalsem** [comment]
switch based on context ("index" => owner is site, "groups" => owner is group, "dashboard/profile" => owner is user)

**Comment by jdalsem** [comment]
so we create them as the title of this issue suggest. That is the best way i think, as index widgets and group widgets should not be owned by users... We indeed handle the permission issues that are related to this (like private widgets)

**Comment by jdalsem** [comment]
Lets keep current behaviour.... there are currently no known issues with this approach
