### ISSUE TITLE
`config.php` for DI

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8785]
We should support putting/customizing our Injector configuration in `config.php` at the root of plugins. It would be possible to get any value with `elgg_get_config($str)`

Example:

``` php
<?php

return [
  'likes:types' => ['comment', 'discussion', 'blog', 'plugin_project', 'plugin_release'],
];
```

**Comment by ewinslow** [comment]
I like PHP-DI the best out of the DI libraries I've seen. PHP-centric (no yaml/JSON/whatever configuration) and simple but powerful API.

**Comment by mrclay** [comment]
Would be great to allows plugins to collaborate on a config data structure. A most naive implementation: each config file decorates an array $config and returns it.

**Comment by ewinslow** [comment]
Can you give an example of what you have in mind? Not sure what you mean by decorate here exactly.

**Comment by mrclay** [comment]
include each config.php with $config in scope.

**Comment by ewinslow** [comment]
Ah. I wasnt figuring that would be necessary, since php-di covers that use case.

**Comment by jdalsem** [comment]
we now have elgg-plugin.php. We could use that file to add more features for config. I would like to see a real life usecase and a PR for that so we can discuss that further. Closing this issue for now.
