### ISSUE TITLE
Make overriding the favicon easier

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8788]
Our favicon situation is a little lame, currently. Folks have to override 6+ different files in order to get rid of the Elgg branding. One for every size/type of favicon.

It should be possible to put one SVG or high-quality PNG file somewhere in a plugin and have Elgg generate/override all the different size variations. We could consider allowing folks to upload it from the admin area too, but I figure it'd be best to get a good developer experience down and then we can build any admin-area-upload feature on top of that...

I'm not sure how to make this work with a _single_ file, though. Seems like we can't just use the views system, since we don't have a way to dedupe images. 

Maybe it could be a config option?

``` php
<?php
// config.php
return [
  'favicon' => __DIR__ . "/favicon.svg";
];
```

**Comment by hypeJunction** [comment]
Can be closed
