### ISSUE TITLE
Add ElggUser::canUseAsOwner

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8790]
The goal is to prohibit user A from creating content owned by user B by default. We currently do this via a couple mechanisms:
1. If the content is placed in user B's container, the container write check fails by default.
2. if the content is placed in a group, we (currently #4231) also do a container write check on user B, which fails.
   In essence, we abuse the container write check hook (lying about the real container) to make sure user A can't make content owned by user B.

In 3.0 we should introduce `ElggUser::canUseAsOwner` and a `owner_permissions_check` hook, both only used when the created entity has an owner_guid and it doesn't match the logged in user. That way, we can eliminate the hacky container check on the user (when the user isn't the real container).

This would require handling this hook in messages (sender creates content under the recipient) and possibly other places.

**Comment by jdalsem** [comment]
Leaving current logic as is
