### ISSUE TITLE
Make it really easy to set up reply-by-email functionality for notifications

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8795]
People expect to be able to reply to the email notifications that we send. Currently we put warnings like "please do not reply to this email" and such. But this just feels like a cop-out.

@beck24 has some experience with this:

> We've done it with a number of sites - it requires some setup on the email side of things so it won't work out of the box. You need a catch-all email address so you can send notifications to something like reply-[crypto-token]@example.com
> 
> PHP has native imap reading capabilities, on cron it checks the email folder, parses the email to match the crypto token to an ElggObject that identifies the discussion. The content of the email is parsed and posted as a reply/comment (since this is done while logged out it needs some explicit permissions auditing).
> 
> One big problem we've run into is automatic out of office replies - annoying when they clutter up the site with such responses, and worst case they can sometimes get caught in infinite loops of replies triggering notifications triggering replies. We've got some filtering in place to try to combat that, though it's only marginally effective as people write their own out of office replies with different language structures - so far we've only dealt with english but the problem would be compounded dealing with multiple languages. A system of strict duplicate checking for replies over a small number of characters seems to have worked decently well to stop the loops.

**Comment by ewinslow** [comment]
@beck24 is the crypto token necessary to ensure people can't just spam a predictable address like `reply-{guid-of-discussion}@example.com`?

**Comment by ewinslow** [comment]
@beck24 Have you tried a time-based throttling? Like replies not accepted in the first 1-2s after sending the notification?

**Comment by ewinslow** [comment]
You could imagine wanting to support users initiating discussions via email, too, ala google groups.

Having to type in `reply+crypto-token@domain.tld` becomes a non-starter. We'd rather folks be able to send email to `support@elgg.org` for example, and have that just automatically posted in one of the groups in the community.

Any experience with that?

**Comment by beck24** [comment]
yeah the crypto token is to prevent spamming, also depending on the site it identifies the person replying.  Some sites require that the reply come from the same email address the notification was sent to, but that breaks for users who have forwarders set up.  The token allows for the possibility of making it available to people who use forwarders with a slight trade off for exclusivity.

We haven't tried time-based throttling but that also might be a good avenue to pursue.

I have also done the discussions via email exactly like google groups.  In that case the group has a distinct alphanumeric identifier set in the group settings.  Then members can email something like ```discussions+general@elgg.org```.

The script looks for the group with the identifier of 'general', checks to make sure the email address belongs to a member, and posts the discussion.  In this case we've been enforcing it such that the email address must match the users email address or the discussion will fail to post.

**Comment by jdalsem** [comment]
Still would like something like this, but not going to see anything happening soon
