### ISSUE TITLE
deprecated warning: elgg_get_view_location

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8798]
In 1.12 this deprecated notice is shown
> WARNING: Deprecated in 1.12: elgg_get_view_location is going away in 2.0. Called from [#7] \engine\lib\deprecated-1.12.php:53
 -> [#6] \engine\lib\views.php:1577

Shouldn't this be handled already?

**Comment by ewinslow** [comment]
What do you mean by "handled"?

**Comment by jeabakker** [comment]
it was deprecated in 1.12, but there is still a reference to it in core, shouldn't that have been removed/replaced?

**Comment by ewinslow** [comment]
Oh I see. It is a deprecated function that core uses, so it always triggered the deprecation warning.

Yea, that's a bit awkward I suppose. If you have any recommendations on how to avoid this, I'm open to it.

**Comment by jdalsem** [comment]
Fixed in #9247
