### ISSUE TITLE
Make elgg.config.wwwroot dynamic

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8799]
Is there a reason we don't just determine ```wwwroot``` from ```window.location```? 
I am working on a site that uses rewrite rules to rewrite subdomain names to URL query params, and having a cached wwwroot parameter is causing cross-origin issues.

```js
elgg.config.wwwroot = window.location.protocol + '//' + window.location.host + '/';
```

**Comment by ewinslow** [comment]
Elgg can be installed in a subdir.

**Comment by hypeJunction** [comment]
Good point.
