### ISSUE TITLE
MultiViews with root settings.php breaks settings URLs

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8806]
It is not possible to access www.site.com/settings/* if ```settings.php``` is located at the Elgg root.

This also could be a problem with other magic/common Elgg directories like "views" or "actions".

Possible solutions:

 1. Prefix with `elgg-` (`elgg-settings.php`, `elgg-views/`, etc...)
 1. Move `index.php` handler into subdir (e.g., `public/index.php` like Laravel). Means you have to do some more work to make sure that "/public" isn't part of your website's path. :cry: 
 1. Place into `elgg-config/` directory: (`elgg-config/settings.php`, `elgg-config/views/`, etc.).
 1. Rename settings to something better like `.env.php` (might be a good idea anyways, but we'd still need to address the `views/`, `actions/`, etc. conflict.)
 1. Make `engine/start.php` the default location for non-composer installs.
 1. Just `elgg-` prefix the settings file.

**Comment by ewinslow** [comment]
Hmm... seems like a rewrite problem. Did you experience this on elgg.org?

**Comment by juho-jaakkola** [comment]
No, I didn't. Apparently there it is also in the root? I'll check if I'm just doing something wrong.

**Comment by ewinslow** [comment]
Yes, it is in the root there as well

**Comment by ewinslow** [comment]
https://elgg.org/settings seems to work for me.

**Comment by mrclay** [comment]
Apache MultiViews causes problems like this. I avoid it.

**Comment by ewinslow** [comment]
@juho-jaakkola Any updates here?

**Comment by ewinslow** [comment]
Please reopen if you can confirm this is a problem with stock Elgg. Otherwise, we can't support every possible configuration of htaccess users might want to do...

**Comment by juho-jaakkola** [comment]
This happens only if installing from git, but not when installing as a composer dependency.

We will be providing Elgg as a composer dependency within the .zip releases, so I'm not sure if it's worth fixing.

**Comment by ewinslow** [comment]
I'm able to access https://development-ewinslow.c9.io/elgg/settings/user/evan fine with elgg installed at root. I think this is a local configuration issue.

**Comment by juho-jaakkola** [comment]
This was indeed caused by Apache MultiViews.

**Comment by vPriVate** [comment]
I've downloaded the .zip, no composer install.
You're right that you can't provide every possible server configuration. But this is on a hosted apache-server with no problems with the 1.x versions and after a clean install without any changes of the distributed htaccess (OK, a prior move to another server was needed to use PHP 5.6).
IMO this is a problem which affects a lot of users, so it would be nice if there will be at least a guide how to fix this...

**Comment by vPriVate** [comment]
> This was indeed caused by Apache MultiViews.

There is no such line in the htaccess. It is possible to deactivate MultiViews by setting
`Options -MultiViews`, but this doesn't have an affect on it :(

**Comment by mrclay** [comment]
> It is possible to deactivate MultiViews by setting `Options -MultiViews`

The main Apache config int /etc/ can disallow you from altering `Options` in .htaccess. If you also get white screen from http://example.org/version that's MultiViews in action.

That said, MultiViews is indeed a common setting that we may need to take into account. Maybe our .htaccess can work around this.

**Comment by ewinslow** [comment]
Reopened for now.

**Comment by mrclay** [comment]
Basically if a RewriteCond would match a PHP file in the root, but the URL doesn't contain `.php` we want to still rewrite.

**Comment by mrclay** [comment]
This seems to work for me when MultiViews is on:

```
# If match one of these files, still route through Elgg (in case MultiViews is enabled)
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule ^((version|settings)\.php)$ index.php?__elgg_uri=$1 [QSA,L]

# Everything else that isn't a file/directory gets routed through Elgg
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?__elgg_uri=$1 [QSA,L]
```

We still have the problem that a plugin can't route a URL like `/views` because it's a directory. I can now see the logic in having all core files/dirs start with something like `wp-`.

**Comment by ewinslow** [comment]
Yes, I was just thinking this, too. WordPress takes the prefix approach.
Larval takes the public subdir approach.

Another approach we could do is support putting all the magic framework
stuff in an elgg/ or elgg-config/ directory.

**Comment by vPriVate** [comment]
Another idea would be not to place the settings.php into the root or to rename it (e.g. elgg-settings.php)...

**Comment by ewinslow** [comment]
Right, so to summarize:

1. Prefix with `elgg-` (`elgg-settings.php`, `elgg-views/`, etc...)
2. Move `index.php` handler into subdir (`public/index.php`). Means you have to do some more work to make sure that "/public" isn't part of your website's path.
3. Place into `elgg-config/` directory: (`elgg-config/settings.php`, `elgg-config/views/`, etc.)

**Comment by ewinslow** [comment]
Updated the original ticket description with a summary of possible solutions. My current favorite is 3, since it solves the problem for all current and future files, and makes the root directory much less noisy.

**Comment by mrclay** [comment]
Another option for .htaccess
```
# If you have settings.php in the root and cannot disable MultiViews, you will need to
# uncomment this to access URLs starting with /settings.
#RewriteCond %{REQUEST_FILENAME} -f
#RewriteRule ^(settings\.php)$ index.php?__elgg_uri=$1 [QSA,L]
```

**Comment by mrclay** [comment]
I think for 2.0 we punt this and ask users to configure their servers in a sane way, add the above (commented out) to htaccess_dist and mention the issue in release notes.

**Comment by juho-jaakkola** [comment]
SGTM

Maybe also add section to the FAQ http://learn.elgg.org/en/1.12/appendix/faqs.html

**Comment by mrclay** [comment]
PR #8919

**Comment by mrclay** [comment]
Fixed by #8919

**Comment by mrclay** [comment]
Huh, #8919 doesn't actually work. Something very similar was definitely working before. Grr.

**Comment by mrclay** [comment]
PR #8922. I gave up on trying to mitigate the effects of MultiViews.

@vPriVate you will have to figure out how to disable MultiViews in your server config, or move `settings.php` into `engine/`.

**Comment by vPriVate** [comment]
As I already said, I've downloaded the zip and was "forced" to place the settings.php into the root. Does it work without further configuration when I move it to the engine/-directory? If yes, why it has been moved to the root?
Maybe MultiViews haven't worked with Elgg 1.X neither and no one have noticed that yet, but it is no solution to force the user to change the configuration of the apache. That isn't possible for everyone, especially if the site is hosted at a webhosting provider, like mine.
I would guess that a lot of users will have issues upgrading to Elgg 2.X due to this problem and "newcomer" wouldn't give Elgg a chance if they have to change the configuration of the apache...

**Comment by mrclay** [comment]
keeping `engine/settings.php` the default location for non-composer installs seems reasonable.

**Comment by beck24** [comment]
I'm not familiar with apache multiViews but if it's also going to affect any other directory such as /views /actions etc, then simply moving/renaming the settings.php doesn't really solve it.
I would vote for prefixed directories.

**Comment by ewinslow** [comment]
Option 3 remains my favorite because then we don't need to support fallbacks for every single magic directory, we just shove everything into a single magic subdirectory and we can keep names simple like views, actions, etc.

**Comment by mrclay** [comment]
PR #8989. I think moving the views/ dir isn't necessary (but if so, I vote for inside engine/).
