### ISSUE TITLE
problem with  login_as/

### ISSUE THREAD

**Issue by enraiser** [Elgg/Elgg#8813]
I first loggedin as some user, and then clicked logout button , 
After then I was completely stopped from accessing the site.
I am using elgg 1.11
[Wed Aug 05 18:48:43 2015] [error] [client 117.247.92.109] PHP Fatal error:  Call to a member function getIconURL() on a non-object in ...mod/login_as/views/default/login_as/topbar_return.php on line 12, referer: .....

**Comment by iionly** [comment]
Already issue at https://github.com/Elgg/login_as/issues/1 (and also in Brett's original repo at https://github.com/brettp/Login-As/issues/17).
