### ISSUE TITLE
Make plugins installable from admin area

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8814]
There is a genuine and legitimate concern that switching to composer will have a substantial negative impact on the non-techy experience.

As a developer I really appreciating the ease that a composer managed site brings, I'm not willing to move backwards. I literally don't think I could continue working on Elgg if I had to go back to manually managing plugins and upgrades and syncing these configurations between installations.

However, some people on the other side of the development spectrum feel similarly about the move to composer. It's so developer centric that is going to make it impossible for people to just naively install plugins or unzip them to a location in their elgg dir.

I don't think this has to be an either-or kind of thing. I think we can give a great experience for non technical users while also catering to developers who like their command line and automation.

There two main use-cases we'd want to support:
## Installation of a plugin from an existing zip file

This is the classic download-from-community-then-upload-to-server workflow.

A common mistake I see in this workflow is installing a plugin to the wrong location. E.g. trying to install my "Facebook Theme" to "facebook_theme-master" instead of just "facebook_theme". If we provide a GUI for just uploading an arbitrary zip file as a plugin, we can make sure the unzip and installation process is smooth so that this doesn't happen anymore.

In my mind the way this would work is providing an upload form in the admin area that takes a zip file, unzipping it into the dataroot somewhere, then symlinking from mod to that directory. That minimizes that amount of writing we have to do inside wwwroot. I suppose we could also just write directly to mod in wwwroot as normal and call it a tradeoff of convenience vs security.
## Installation of a plugin from a composer target

Now that Elgg fully supports being installed as a composer dependency for 2.0, I suspect there will be many plugins that cannot simply be downloaded from github in a zip archive and installed locally. Indeed, you cannot do this with Elgg currently because it requires use of composer to pull down dependencies. It would be nice if folks didn't have to lose access to these plugins just because they aren't comfortable with composer. Also, it would be good not to put an extra burden on developers to set up build processes to package their scripts and dependencies correctly before publishing on the Elgg plugins repo.

Being able to type in a composer target and the version constraint and then having composer run behind the scenes to install it would be great. 

As a further enhancement, being able to search through the community plugins repo, packagist, and other repositories right from within the admin area to find good Elgg plugins seems like a win. One click to install and enable.

**Comment by beck24** [comment]
I like the idea of symlinking to plugins uploaded to dataroot as I don't really want /mod to be writeable.  That might make moving a site more difficult if you have a mix of plugin locations and symlinks that need fixing.

**Comment by jdalsem** [comment]
Going to stick with the current way of installing
