### ISSUE TITLE
Deprecate elgg_view_menu_item()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8818]
Original issue: https://github.com/Elgg/www.elgg.org/issues/51#issuecomment-128501414

This is currently what I have to do to modify the link text of a menu item to include an icon and an indicator:

``` php

$text = $item->getText();
if (!preg_match('~<[a-z]~', $text)) {
    $text = elgg_format_element('span', ['class' => 'elgg-non-link'], $text);
}

$icon_view = '';
$icon = $item->getData('icon');
if ($icon) {
    $icon_view = elgg_view_icon($icon);
}

$indicator_view = '';
$indicator = $item->getData('indicator');
if ($indicator) {
    $indicator_view = elgg_format_element('span', ['class' => 'elgg-menu-indicator'], $indicator);
}

$item->setText($icon_view . $text . $indicator_view);

$item_view = elgg_view_menu_item($item);
```

It would be easier to just render the link from within this view. IMHO.

**Comment by ewinslow** [comment]
By "indicator" you mean some sort of notification counter like so http://cdn.cssflow.com/snippets/app-navigation-with-notification-badges/preview-260.png?

**Comment by ewinslow** [comment]
`elgg_view_menu_item` was introduced in 

https://github.com/Elgg/Elgg/commit/6b045d901840fa0ffcb25170205f506c7a2036ba#diff-f4e9688e8bd201d9a05386a7ad76386e

**Comment by hypeJunction** [comment]
Yes, trying to avoid building html in the register hook.

**Comment by ewinslow** [comment]
I've wanted to bake this feature in for quite some time: https://github.com/Elgg/Elgg/issues/3185 :)

**Comment by hypeJunction** [comment]
There are several menu item tickets floating around. I will put together a
PR. Which branch do features go at this point?

**Comment by ewinslow** [comment]
Master, though we'll probably punt on them until after 2.0 lands.

**Comment by hypeJunction** [comment]
Here is a wrap up of some work I have been doing with the menus: https://github.com/hypeJunction/Elgg-menus_api

Client has requested one column layout with no sidebars, so the owner block and page menus had to relocate elsewhere. Additional entity menus were seen as clutter, so they had to be eliminated as well. What was left is a title menu that accumulates all the menu items with an ellipsis popup.

There are also some features that make working with menus easier:
 * all menu items have text and an optional `icon` parameter. In past I had to write a ton of hooks just to replace core icon menus with icon + text, so that I could use css to toggle display for responsive designs (e.g. icons are problematic in vertically stacked dropdown menus).
 *  each menu, section and item are identified by `data-` attribute, which can be helpful in manipulating menus using JS, or to build a menu editor for example
 * this fixes some randomness in section/item name normalization, which result in discrepancies
 * this allows rendering only certain sections of the menu, or rendering sections in a preset order

If any of these changes make sense in core, please let me know, and I will make a pull request.

![group_menu](https://cloud.githubusercontent.com/assets/1202761/11212290/3fcde7e8-8d35-11e5-968a-23c0f917d919.png)

**Comment by mrclay** [comment]
No time yet to dig deep, but looks really promising.

**Comment by jdalsem** [comment]
icons in menus is already part of master. This issue should be updated with some more specific tasks to be relevant. Alternatively for the remaining tasks new issues could be opened.
