### ISSUE TITLE
Arbitrary data in ElggMenuItem::factory()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8819]
When passing arbitrary parameters to the factory, they do not get added to the item ```data```, but show up as attributes on the menu link:

```php
    $item = ElggMenuItem::factory(array(
				'name' => 'dashboard',
				'text' => elgg_echo('dashboard'),
				'icon' => 'dashboard',
				'indicator' => 25,
				'href' => "$user->username/dashboard",
				'priority' => 100,
				'section' => 'management',
	));
```

rendered into (while ```$item->getData('icon')``` is `null`)

```html
<li class="elgg-menu-item-dashboard"><a href="http://xxx.dev/ismayil.khayredinov/dashboard" icon="dashboard" indicator="25" class="elgg-menu-content"><span class="elgg-non-link">Dashboard</span></a></li>
```

This works, as expected:

```php
	$item = ElggMenuItem::factory(array(
				'name' => 'dashboard',
				'text' => elgg_echo('dashboard'),
				'data' => array(
					'icon' => 'dashboard',
					'indicator' => 25,
				),
				'href' => "$user->username/dashboard",
				'priority' => 100,
				'section' => 'management',
	));
```

**Comment by ewinslow** [comment]
Seems like WAI. What is the problem?

**Comment by hypeJunction** [comment]
The problem is that it's a menu item constructor, not a link constructor, and I would expect the parameters to be stored as item data and then reused by the link.

**Comment by ewinslow** [comment]
Hmm... I see your point. This is a confusing case because there's one set of arguments but two elements where they could potentially go. So some arguments are special-cased and the others just have some default behavior of defining attributes on one of those elements. I guess we chose the <a> tag at some point... I'd be ok with switching to outputting those extra params on the `<li>` tag, but then we'd have to break BC, which it's too late for 2.0 to do, and possibly not worth the hassle at all...

**Comment by hypeJunction** [comment]
We should just make sure the data is populated with arbitrary values. I
don't think we need to break anything.

**Comment by ewinslow** [comment]
Supporting arbitrary attributes was a by-design API choice, IIRC. We can't change this behavior without breaking compatibility. I suppose could *also* include it in the return value of `getData()`. Is that all you're looking for?

**Comment by mrclay** [comment]
Let's first document thoroughly how to use the existing API. I think we could easily break BC if we're not careful here.
