### ISSUE TITLE
"composer update" should not overwrite modifications in .htaccess

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8823]
Modifications to ```.htaccess``` get lost when running ```composer update``` because it always copies ```htaccess_dist``` to ```.htaccess```.

Theoretically we could compare the ```.htaccess``` and ```htaccess_dist``` files, but there isn't really an easy way to find out whether the possible difference is made by an admin or caused by updates in ```htaccess_dist```.

So I guess we should be adding ```.htaccess``` only when doing ```composer install```.

**Comment by juho-jaakkola** [comment]
It seems to me that none of the methods in ```Elgg/Composer/PostUpdate``` need to be ran when updating. So the solution might be just to remove this line from starter-project: https://github.com/Elgg/starter-project/blob/master/composer.json#L16

**Comment by mrclay** [comment]
And rename class PostInstall.

**Comment by juho-jaakkola** [comment]
Another approach would be to check whether the ```$event``` parameters passed into ```PostUpdate``` is "install" or "update" and choose the scripts to run based on it.

@ewinslow Have you planned any future use cases for the update command?

**Comment by juho-jaakkola** [comment]
The combination of #8875 and https://github.com/Elgg/starter-project/pull/22 would fix this using the former approach.

**Comment by ewinslow** [comment]
Sorry for the late reply. There were future uses for post-update-cmd I had in mind that are made slightly more difficult if we don't include it now.

E.g. if we wanted to add default composer commands like `composer test`, or if we wanted to provide a script similar to Laravel's `artisan`.

**Comment by ewinslow** [comment]
post-update-cmd basically just gives Elgg/elgg permission to install scripts at the root of the project.

**Comment by juho-jaakkola** [comment]
Is there something in the current class that both install and update commands need? Or could we add a separate class for update command?
