### ISSUE TITLE
autoloader path in profile/icondirect.php

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8826]
profile/icondirect.php doesn't work when Elgg is installed as a vendor

**Comment by ewinslow** [comment]
What version are you using? I'm pretty sure I had fixed this

**Comment by ewinslow** [comment]
https://github.com/Elgg/Elgg/commit/7610552b22f203f3d2eadb1f20e28b2429e0d234

**Comment by hypeJunction** [comment]
Ok, I will pull in master. I haven't updated since I started the project a week or so ago

**Comment by ewinslow** [comment]
Reopen if you can repro after that.
