### ISSUE TITLE
Thoughts on \Elgg\Application 

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8828]
I am trying to make use of `\Elgg\Application`, but it doesn't really do what I would expect it to do.
IMHO, `Application::create` should become public. Currently, there is no way of instantiating an app without running the boot process, or instantiating a ServiceProvider. `Application::start` is an overkill for my needs (all I need is to get the DB connection). 
Using `Application::start` would probably be ok, if `'init','system'` event were triggered outside of `Application::bootCore`.

**Comment by ewinslow** [comment]
I think there is specifically a desire NOT to encourage use of Application, and instead to feed everything through index.php routing, which *should* (eventually?) be cheap, lazy-loading only the services needed as they are needed. So the "engine boot" process eventually disappears and it just becomes the DI system wiring things together as services as requested...

**Comment by ewinslow** [comment]
Things like getting the list of active plugins would be cached and not require a DB hit on most requests, for example.

**Comment by hypeJunction** [comment]
Would you mind demonstrating that with profile/icondirect.php?

**Comment by ewinslow** [comment]
I will try. Right now I suspect it would substantially negatively impact perf, though, since we haven't optimized all these cases.

**Comment by hypeJunction** [comment]
Well, that's my point. You are talking about future, in the meantime plugin
authors would like to gain from great new features in Elgg.

**Comment by ewinslow** [comment]
Yes, I suppose its a tradeoff between short-term quick-and-dirty solution or longer-term more-ideal solution.

**Comment by mrclay** [comment]
I'd also prefer create() to be public. Maybe document it as experimental/not recommended.
