### ISSUE TITLE
Autoload plugin dependencies

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8829]
As we are moving to dependency management with composer, plugins can no longer be sure where their dependencies are in `elgg-root/vendor/` or in `elgg-root/mod/elgg-plugin/vendor`. To avoid duplication and confusion, it would be helpful if the core checked if `elgg-root/mod/elgg-plugin/vendor/autoload.php` exists, and required it automatically on plugin boot. That would save the hassle of implementing additional steps for zipped installs.

**Comment by jdalsem** [comment]
:+1:

**Comment by mrclay** [comment]
Safe to do in 2.2? I think if we verified `mod/elgg-plugin/composer.json` existed, this would be safer.

**Comment by hypeJunction** [comment]
I tend to install my plugins from root, so presence of `composer.json` is not an indicator.

**Comment by hypeJunction** [comment]
I am not sure about others, but I use `require_once`, so it should be safe for core to do that as well, but I am not sure what happens with `require` and `include` and if composer can handle duplication.

**Comment by mrclay** [comment]
vendor/autoload.php is fine with repeated calls.

**Comment by jeabakker** [comment]
we sometimes use ```include_once``` if this fails, then the autoloader is probably in wwwroot and is already handled by Elgg ;)
