### ISSUE TITLE
Invalid URL on admin area / plugins / plugin info / files

### ISSUE THREAD

**Issue by nlybe** [Elgg/Elgg#8831]
On plugins in admin area, if click on any plugin so opens a lightbox window with all plugin information, if click on any files listed on "Files tab", redirect on a page showing "Unknown plugin"
The URL of each file looks to be wrong.

Tested on Elgg 2.0.0-alpha.2

**Comment by juho-jaakkola** [comment]
I cannot reproduce. What do the URLs look like? What's wrong with them?

**Comment by nlybe** [comment]
Now I checked it on live site and it works
The URL is somthing like http://www.example.com/admin_plugin_text_file/categories/README.md

So in live site it's OK. But in localhost site that the site is in subdirectory, I get this error. 
The url is http://localhost/elgg200/admin_plugin_text_file/categories/README.md

**Comment by juho-jaakkola** [comment]
I cannot reproduce this in a subdirectory either, so this seems like a server configuration issue instead of a bug in Elgg.
