### ISSUE TITLE
core/ajax/edit_comment should pass $entity to forms/comment/save

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8832]
This would eliminate the branching in comment/save to handle missing $entity, which should basically never be necessary; if you can't load the comment's container, we should just `return`.

**Comment by jdalsem** [comment]
Why not load `$entity` from containerEntity if `$comment` is provided in `comment/save`? That eliminates the need to provide `$entity` when editing a comment?

**Comment by hypeJunction** [comment]
To separate models from views?

**Comment by jdalsem** [comment]
`core/ajax/edit_comment` is also a view so determining it there is just as bad if separating model/view is the goal

**Comment by jdalsem** [comment]
closing this as there is nothing to gain
