### ISSUE TITLE
Split data dir into "uploads" and "cache" directories

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8833]
Currently we have lots of directories like 1, 10000, 100000, etc. which store user-uploaded/source-of-truth content (i.e. dangerous to delete) alongside "cache" directories like system_cache, views_simplecache, etc. that store computed data (i.e. safe to delete).

It would be nice if these two kinds of filesystem data were stored in different directories so that backups only backed up the source-of-truth data instead of getting polluted with computable data.

Also, I want to have a "backups" directory for doing DB dumps and data-dir zips, but backups shouldn't include the backups directory itself. It would make it easier/cleaner to implement such a thing if the data dir looked liked:

```
dataroot/
  backups/
  cache/
  uploads/
```

rather than the current:

```
dataroot/
  1/
  10000/
  100000/
  ...
  views_simplecache/
  system_cache/
```

Still not sure if "uploads" is the right word, since I could imagine the data directory being where we store the SQLite DB file if Elgg ever supported SQLite.

**Comment by beck24** [comment]
:+1:

**Comment by mrclay** [comment]
PR #9402

**Comment by mrclay** [comment]
What are the important use cases #9402 doesn't meet? I'm happy to let it sit awhile. cc @juho-jaakkola

**Comment by jdalsem** [comment]
#9402 does the trick for now
