### ISSUE TITLE
Remove undefined callback in uservalidationbyemail

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8838]
`elgg_register_plugin_hook_handler('action', 'user/requestnewpassword', 'uservalidationbyemail_check_request_password');` <- this function is undefined. What is it supposed to do?

PHPStorm found this. I don't know if it's a bug.

**Comment by beck24** [comment]
I recently noticed this in an older 1.8 installation while I was building some SSO integration - so it spans all the way back to at least 1.8.  I don't know what was intended, but I've tested the request password workflow and it seems to work as expected without it.

**Comment by mrclay** [comment]
It's supposed to re-validate the address when a user changes his own email address. A system message says to verify the address but an email is never sent.

**Comment by jeabakker** [comment]
closed with https://github.com/Elgg/Elgg/commit/2fdf010d1e69fbe159bea834fdb2a3b982dfd443
