### ISSUE TITLE
Point to default_page_owner_handler on page ownership docs

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8841]
This function has a lot more magic not described in docs.

More troubling is that, depending on how a plugin in coded, a client could manipulate the page owner via querystring so it doesn't match what the system might expect from the URL segments and the entity being displayed. At the very least we should make it clear that Page Ownership is based on user input and so shouldn't be trusted.

Ultimately I think the querystring sniffing in `default_page_owner_handler` should go away, and possibly replace the whole function with an explicitly-called mechanism for reading info from the URL. If you want the typical Elgg URL structure for content, you ask for it.

**Comment by jeabakker** [comment]
fixed in #9282
