### ISSUE TITLE
Wrong language-string

### ISSUE THREAD

**Issue by vPriVate** [Elgg/Elgg#8842]
Elgg 2.0.0 alpha2
Within the language string 'install:check:enginedir' it is said, that it was not possible to create the settings.php in the engine directory. That's wrong, because it has to be in the root-directory now. (Costs me a lot of time to found that out ;))

On top: In ElggInstaller.php line 966 the string is referred to 'install:check:installdir', which doesn't exists. So either change it to 'install:check:enginedir' (which it was in earlier versions) or change the name of the string to 'install:check:installdir' :)

**Comment by mrclay** [comment]
PR #8871. cc @ewinslow the other langs need to be updated as well, but how to do that...

**Comment by juho-jaakkola** [comment]
The Transifex project for Elgg 2.0 hasn't been set up yet. I think the plan was to wait until we add on own branch for 2.0, so we can mark that as a source for the automatic Transifex updates.

**Comment by juho-jaakkola** [comment]
See #8876
