### ISSUE TITLE
Elgg 2.0 Exception during installation

### ISSUE THREAD

**Issue by vPriVate** [Elgg/Elgg#8843]
When manually creating the settings.php for installation (or moving from the engine directory) then an exception occurs on loading the start-page. It is only possible to do this automatically (when it is possible to set file permissions) or has to be created during the installation. Otherwise you have to call /install.php to start the installation.

**Comment by iionly** [comment]
Duplicate: https://github.com/Elgg/Elgg/issues/5832

**Comment by oscardo** [comment]
Is only /var/www/html/ for default o (/Your_site/www) allow permitions 770 or 777
chmod 770 /var/www/html/*

**Comment by mrclay** [comment]
@oscardo Are you saying the documentation is wrong? If so can you open a new issue?
