### ISSUE TITLE
Date warning causes exception on install

### ISSUE THREAD

**Issue by beck2424** [Elgg/Elgg#8845]
>PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

During installation the error logging isn't controlled so this warning may be displayed and cause an exception:

>RuntimeException' with message 'Failed to start the session because headers have already been sent by "/var/www/html/engine/lib/elgglib.php" at line 935.

**Comment by beck24** [comment]
Fixed in #9259
