### ISSUE TITLE
MIME being checked on missing file (maybe before file save)

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8846]
Test path with `file_exists()` before calling `finfo_file()` or `mime_content_type()`

**Comment by juho-jaakkola** [comment]
Any idea what causes the file to be non-existent in the first place?

**Comment by hypeJunction** [comment]
Will need to investigate. Some race condition I think. Something is
checking the mime before file is actually saved.

**Comment by hypeJunction** [comment]
Found the bugger. Calling `getMimeType()` on an instance of `ElggFile` (not statically), the path is set to filename, whereas it should be normalized to filename on filestore.
