### ISSUE TITLE
Make it easier to include/link to Elgg's license(s) in other projects

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8849]
If a project wants to acknowledge code lifted from Elgg, it's kind of messy. It might be good for our LICENSE file to contain both GPL and MIT (with custom language) licenses and to what they apply. Or separate LICENSE-GPL and LICENSE-MIT files.

**Comment by hypeJunction** [comment]
+1

**Comment by mrclay** [comment]
Strawman: We create LICENSE-GPL.txt and LICENSE-MIT.txt. The MIT one has a header saying it does not apply to the plugins. LICENSE.txt is both concatenated, with a header saying you're free to copy/link to any of the 3 files.

What shall we use for "[copyright holders](http://opensource.org/licenses/mit-license.html)"?

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/10136
