### ISSUE TITLE
Use postcss-cli to auto-clean css

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8858]
https://github.com/code42day/postcss-cli

In combination with autoprefixer, can:
- remove unnecessary prefixes
- auto include prefixes for enhanced browser support (we can use flexbox! Without learning all the vendor prefixes and old syntaxes!)
- fix some CSS syntax errors

If this truly makes flexbox feasible, we can drop support for several constructs like elgg-grid, elgg-image-block, and elgg-layout which were all about implementing nasty CSS hacks so plugins authors didn't have to. But now its quite likely that those aren't needed if flexbox makes them straightforward to implement in a more semantic way... I haven't looked into it deeply but the more we can stop supporting the better I guess...

**Comment by hypeJunction** [comment]
Do we still want this?
IMO, this should be done in a pre-processor, and minify can do the rest.

**Comment by mrclay** [comment]
> this should be done in a pre-processor, and minify can do the rest

If possible yeah.

**Comment by mrclay** [comment]
css-crush is in master.
