### ISSUE TITLE
Delay unread messages counting

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8862]
Just noticed on the community site that when you have an unread message and go on to read the message the indicator still counts the message your are currently reading.

**Comment by mrclay** [comment]
does a refresh clear it?

**Comment by hypeJunction** [comment]
Yes. It's just confusing, when I am reading a message and seeing there is "another" one.

**Comment by jdalsem** [comment]
just move the count to a register menu hook... that way you are probably after the content is drawn (and the read counter is decreased)

**Comment by mrclay** [comment]
The cause is pagesetup being called earlier than it used to (caused by the move to resource views). Fix coming.

**Comment by mrclay** [comment]
Fix #8870

**Comment by mrclay** [comment]
This is kind of the ideal case for a [deferred view](https://github.com/Elgg/Elgg/pull/7603), to eliminate the race condition. We'd not render the unread count until after the message was successfully displayed.
