### ISSUE TITLE
Master: view inspector is broken

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8863]
[Wed Aug 19 14:40:26.626688 2015] [:error] [pid 2180:tid 988] [client 127.0.0.1:64174] PHP Fatal error:  Call to undefined method Elgg\\Debug\\Inspect
or\\ViewComponent::getFile() in D:\\wamp\\www\\xxx\\htdocs\\mod\\developers\\views\\default\\admin\\develop_tools\\inspect\\views.php on line 77,
 referer: http://xxx.dev/admin/

**Comment by mrclay** [comment]
That file isn't matching what's in the master branch.

**Comment by hypeJunction** [comment]
Sorry, I was under impression that starter-project was constrained to dev-master.

**Comment by mrclay** [comment]
I'd guess eventually starter will be tied to tagged releases? cc @ewinslow

**Comment by ewinslow** [comment]
The release workflow we've been going with for now involves updating the specified version of elgg/elgg in elgg/starter-project after a release.

I suppose that means we'll have to have parallel branches for everything, which seems kinda like too much coupling now that I think about it, but meh...
