### ISSUE TITLE
"Class was not found" when extending ElggUser

### ISSUE THREAD

**Issue by dfxyz** [Elgg/Elgg#8868]
Tried to extend ElggUser and registered a subtype of 'user'.

However, putting the extended user class in `mod/your_plugin/classes` won't work, and "Class 'ExtendedUser' was not found, missing plugin?" was logged.

Then I put the class in `engine/classes` and it worked.
So I think there's a bug in class loader.

**Comment by juho-jaakkola** [comment]
The classes that extend ElggEntity work a bit differently. You need to use this to register them: http://reference.elgg.org/entities_8php.html#ac4941cde36cde32db55dec05f4a8af44

**Comment by dfxyz** [comment]
Yeah, I did add_subtype().
This is my init():
```php
function test_init() {
    elgg_register_entity_type('user', 'test_user');
    add_subtype('user', 'test_user', 'TestUser');
}
```
And this is my `classes\TestUser.php`:
```php
<?php

class TestUser extends ElggUser {

    protected function initializeAttributes() {
        parent::initializeAttributes();
        $this->attributes['subtype'] = 'test_user';
    }

    public function hello() {
        echo "Hello World!";
    }

}
```
Still, "Class 'TestUser' was not found, missing plugin?"
It works when add a subtype for 'object' and 'group'. Didn't try 'site'.
Definitely not works for 'user'.

**Comment by juho-jaakkola** [comment]
There shouldn't be anything that prevents extending ElggUser class. I'm however reopening until i have time to test it myself.

**Comment by hypeJunction** [comment]
What version of Elgg are you using? Prior to 1.9 classes wouldn't autoload if they were in nested directories. Not entirely sure, but after a certain point we have started autoloading with PSR-0 (there was a brief period of PSR-2 autoloading as well). I am not entirely sure what we are using now, I am always using composer to autoload plugin classes.
Where is your class located, in /my_plugin/classes/? 
Have you tried registering the class manually with `elgg_register_class()`?

**Comment by hypeJunction** [comment]
Also, did you actually create a user with subtype 'test_user'? When exactly was Class not found error thrown?

**Comment by mrclay** [comment]
Sounds like your plugin is disabled, so Elgg no longer scans its /classes directory, but EntityTable::rowToElggStar still tries to use it.

**Comment by mrclay** [comment]
You need a deactivate.php file like the blog plugin.

**Comment by hypeJunction** [comment]
One more reason to get rid of subtypes table. Argh.

**Comment by hypeJunction** [comment]
Deactivate never gets called if the plugin is deactivated due to fatal
error outside of a handler in the plugin code. And in fact an error in
activate does not stop the plugin from being activated. Meant to open a
ticket about that.

**Comment by dfxyz** [comment]
@hypeJunction I'm using 1.12.1. Class file is stored in `my_plugin/classes/`.
Just tried elgg_register_class(), it returns 1. Still not working.
I changed a current user's subtype to 'test_user'. Once created a TestUser (worked when creating but failed to load in the future).
Some logs here:
```
[21-Aug-2015 09:12:56 Asia/Shanghai] Class 'TestUser' was not found, missing plugin?

[21-Aug-2015 09:12:56 Asia/Shanghai] PHP Fatal error:  Call to undefined method ElggUser::hello() in C:\xampp\elgg\mod\test\start.php on line 25
```

@mrclay No way it's disabled. It works for object's subtype and group's subtype, but not user's subtype.

**Comment by dfxyz** [comment]
Solved in 1.12.3, close this issue.

**Comment by dfxyz** [comment]
There're still some small problem.
* Try changing an existing user's subtype in database, but the user is still an ElggUser.
* Create a new user using the extended class does work, but "class was not found" still shows in the log.

**Comment by mrclay** [comment]
This is unlikely a bug. Please post what you're trying to achieve in the Technical Support area of the community.

**Comment by dfxyz** [comment]
@mrclay I believe it's a bug especially related to extending "user" type.
Extended class works fine when put into `engine/classes` and no more "class was not found" warning.
Sorry, can't log into the community because Twitter is blocked in my location.
I just want to add some new relationships and extend the ElggUser with related functions.

**Comment by beck24** [comment]
It sounds like you're putting your class in the wrong location in your plugin or it's named incorrectly

**Comment by mrclay** [comment]
Elgg uses PSR-0 autoloading out of each active plugin's `classes` directory. If your class is `TestUser`, place your class in `myplugin/classes/TestUser.php`.

**Comment by dfxyz** [comment]
@beck24 @mrclay 
I'm pretty sure that it's not the location problem.
Other classes (subtypes of group and object) work correctly.
It only happens when extending ElggUser and register a subtype of user.

This is my classes directory:
![1](https://cloud.githubusercontent.com/assets/5230009/9867601/308b85e8-5ba2-11e5-99e0-a2adb390f90b.png)

This is the related section in my start.php:
![1](https://cloud.githubusercontent.com/assets/5230009/9867744/c35e7e42-5ba3-11e5-9669-5ea267b2fa26.png)

Anyway, it works now for newly created CYUser in 1.12.3,
Though the warning keeps popping out.

**Comment by mrclay** [comment]
Ah, so during development you created a user with a different subtype (not "user") and that doesn't have a class registered for it. Clean up your install by deleting that user and the old subtype row.

**Comment by dfxyz** [comment]
No. I tried to make the first administrator user be of the subtype I registered later.
Anyway, there must be something not right, but it isn't urgent now.

**Comment by dfxyz** [comment]
@mrclay 
Unfortunately, it's still a real bug. Request to reopen this issue.

Tried to log in as a just-created non-admin CYUser. 
Using elgg_get_logged_in_user_entity then var_dump shows that I'm still a ElggUser, with a log: `[16-Sep-2015 12:54:16 Asia/Shanghai] Class 'CYUser' was not found, missing plugin?`

**Comment by mrclay** [comment]
Does everything work if your class is in engine/classes? Do your other classes load correctly?

**Comment by hypeJunction** [comment]
Just a thought. It is possible that the session is started before the
plugin classes are registered. Perhaps Elgg is trying to instantiate a
logged in user too early in the flow.

**Comment by dfxyz** [comment]
A summary for 1.12.3:
* All other classes which doesn't register as a subtype of user work correctly
* Class registered as a subtype of user only works correctly when put into engine/classes

Just did a little test and discovered something new.
Assumed that I have three users in the system. I changed A's subtype, then created others with CYUser class. (class file is in mod/myplugin/classes/ only)
Try to run a script that `var_dump(get_entity(A or B or C))`:
* When not logged in, all user are CYUsers.
* When logged in as any of A\B\C, logged in user is a ElggUser while others are CYUsers.
The situation is very like what @hypeJunction said above.

**Comment by mrclay** [comment]
@hypeJunction Confirmed, that's the problem.

**Comment by mrclay** [comment]
I don't know if this ever worked. We need a separate, early pass through enabled plugins to add the autoloading. The session must be booted (user loaded) *before* plugin start.php files are executed.

**Comment by 4nanook** [comment]
I fixed this on my installation by installing acl_builder_api" which apparently is required by some other hype-junction plugin but not listed in it's manifest.

**Comment by jdalsem** [comment]
this is no longer a problem (in Elgg 3) as we have runtime subtype/class registration and we do not rely on classname being set in the database
