### ISSUE TITLE
Remove Leave Group from title menu

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8872]
Currently, the first thing you see when visiting the group page is "Leave Group" call to action button in a place reserved for things like "Add a blog" and "Join group". Perhaps that would be a more logical place for "Start a discussion", at least on the community site. Curently one has to click around before figuring out how to add a discussion topic.
"Leave group" should probably go into "My status" menu instead.

**Comment by ewinslow** [comment]
Agreed.

**Comment by hypeJunction** [comment]
@jdalsem you did this, right?
