### ISSUE TITLE
Set up Transifex for Elgg 2.0

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8876]
We have a separate Transifex project (https://www.transifex.com/elgg/elgg-core-2/) for Elgg 2.0, so we need to:

- [x] Upload translation resources
- [x] Upload existing translations
- [x] Set auto-upload sources
- [x] Insert resource categories
- [x] Inform community about the new translation project
- [x] Update Transifex config: https://github.com/Elgg/Elgg/blob/master/.tx/config

**Comment by juho-jaakkola** [comment]
I tried to add a new source but the setting is nowhere to be found. I think this may even be a bug in Transifex. This has happened to me also with other projects.

**Comment by juho-jaakkola** [comment]
Do we want to:
 - Wait until we make a branch for 2.0 and set that as a source
 - Add master as a source now, and change it to 2.0 later when it's created

It would be nice if people could start translating ASAP.

**Comment by juho-jaakkola** [comment]
The setting page in Transifex directs user to the docs and the docs direct user to the settings page. Something's not right. :)

I've sent a bug report to them.

**Comment by juho-jaakkola** [comment]
Ok, so you first need to upload a file manually before you can define the update source for that file.

**Comment by juho-jaakkola** [comment]
I've uploaded all the resources, but haven't set up the auto-update sources yet.

**Comment by juho-jaakkola** [comment]
Community has been informed: https://elgg.org/discussion/view/2310765/translations-for-elgg-20

**Comment by mrclay** [comment]
Thanks for pushing this ahead

**Comment by mrclay** [comment]
What's left here? How can I help?

**Comment by juho-jaakkola** [comment]
We've agreed to create the 2.x branch when we release beta.1: https://elgg.org/discussion/view/2354634/shall-we-make-the-20-and-2x-branches-when-releasing-beta1

When that's done we can configure the automatic update resources in Transifex to point to the 2.x branch, and then Transifex will keep the elgg-core-2 translation resources updated automatically.

After that everything should be taken care of.

**Comment by juho-jaakkola** [comment]
All done!
