### ISSUE TITLE
Content type and subtype should be passed into canWriteToContainer()

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8892]
We should pass entity type and subtype into `canWriteToContainer()` and `can_write_to_container()` always when dealing with a specific content type. This would make the `[container_permissions_check, <type>]` hook much more useful.

My use case: I must prevent regular group members from posting any other content than new discussion topics to the group. Currently it's difficult to remove the "Add new whatever" links from group modules.

The module view `groups/profile/module` already calls `canWriteToContainer()`, so the links could easily be removed with the hook. The hook handler doesn't however receive any information about which content type is in question.

**Comment by hypeJunction** [comment]
Agreed that the method is really only useful when subtypes are passed down
the pipeline. I do that in all of my plugins, but core still needs to fill
in the blanks. Perhaps something we should make a priority for 3.0. I
imagine if we start constraining now, we will break some sites.

**Comment by juho-jaakkola** [comment]
I don't remember how exactly the differently named handlers get called.

The type parameter however defaults to ```'all'```. Doesn't this mean that existing plugin hooks registered for that would get triggered also when called with something more specific? Meaning that this could be done already on 2.x branch.

**Comment by jdalsem** [comment]
This is done in almost all cases where it is needed. Closing this as there is no need to pursue this any further.
