### ISSUE TITLE
No way to retrieve current route

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8895]
There is currently no way to determine the current route, if it's different from current page url.
Let's say we have we have a page handler for `handlerX`, multiple hooks listen `'route','handlerX'` hook and modify the route to `handlerY/blurbZ`. There is not way for the plugin to know that the current page URL is in fact `handleryY/blurbZ` and not `handlerX`.

**Comment by hypeJunction** [comment]
Listening to the `route` hook with high priority doesn't always work, because some devs have a habit of dumping HTML from the `route` hook instead of defining a new route.

**Comment by beck24** [comment]
sorry, I've changed my ways on that lately :)

**Comment by mrclay** [comment]
So I'm getting `route` handlers would ideally allow altering only the identifier? Not sure how we'd deprecate/enforce that. Easier to deprecate `route` completely and use something like `route_identifier` to alter it. But devs could still dump a page there, or even in an init().

**Comment by mrclay** [comment]
We could set a flag before triggering `route` that popped a deprecation notice if certain functions were used within (e.g. elgg_view_page).

**Comment by hypeJunction** [comment]
@beck24 You are/were not alone in this :)
@mrclay I would rather leave the `route` hook and discourage HTML output by stopping treating `false` return as 'page has already been served'. Tell devs to use forward, if they have to. Now we resources views, serving HTML from route hook is very bad taste.

**Comment by mrclay** [comment]
Might I ask what the use case is for this change? After all, you're asking that a bunch of plugins be modified to support it.

**Comment by hypeJunction** [comment]
I am not saying we should modify, but it would be nice to keep reference of route segments and identifier after they have been modified by hook.

My use case is as follows:
In the last iteration of hypeCategories, I have finally implemented context aware category filtering. That is when you are in a blogs context, the category tree allows you to view only blogs in a specific categories. Given that our current routing system is completely unaware of what content type/subtype pairs are displayed on the page, I am using a super-hacky regex-based implementation that sniffs current URL, renders the tree modifying the category-entity URL, then uses reverse lookup to substitute the route with that already defined in categories plugin. This was all working fine with bundled plugins, but once I started implementing this on a client site, I have realized that we use custom routing, where as we use unique namespaces (a-la usernames) to build SEF URLs, then route them back to corresponding page handler. So, in fact I couldn't use regex against `current_page_url()`, but rather the final route.

**Comment by hypeJunction** [comment]
This basically sums up what happens behind the scenes: https://github.com/hypeJunction/hypeCategories/blob/dev/settings/default.php

**Comment by hypeJunction** [comment]
FYI, this is my first attempt at mapping Elgg URLs to specific content types. I see a number of applications, and if I continue using this approach, I imagine routes will always be a pain point. some of the applications I have in mind is search (automatically determine in which context and what entity types to search for), tagclouds (determine which entity types to use to populate the tag cloud), anything to do with annotations and comments (latest comments, most rated, similar content etc).

**Comment by hypeJunction** [comment]
I need a solution for this. `route` hook, IMO, is intended to modify the original URL without issuing a forward. Things go to hell if use the hook, because `current_page_url()` never matches the actual final route, this breaks everything from context to page owners to menus et al.

**Comment by mrclay** [comment]
I guess we first need a rundown of any core components that read from the route/URL before the "route" hook is called. We'd need a way to update those or delay them.

**Comment by mrclay** [comment]
Plugins can now use `route:rewrite` hook for this.
