### ISSUE TITLE
Liked comment notification issues

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8906]
Says "likes your post" and the excerpt is way too long for the email subject and really for the body, too. As this is comment the recipient wrote, a much shorter excerpt will be sufficient. Maybe 50 chars?

**Comment by mrclay** [comment]
@Elgg/owners should this block 2.0?

**Comment by juho-jaakkola** [comment]
Has the message changed between 1.x and 2.x?

**Comment by mrclay** [comment]
Umm, probably not. I just noticed it on community. Removing it from 2.0.
