### ISSUE TITLE
rewrite.php not exists in elgg instalation files

### ISSUE THREAD

**Issue by gandra** [Elgg/Elgg#8907]
I am trying to install elgg version 1.12.2 according to documentation http://learn.elgg.org/en/1.x/intro/install.html
I have uploaded elgg on server, created MySql database and created data folder. After that I open in thew latest chrome my website and process installation starts.
Immediatelly I have expirienced warning:
http://i.imgur.com/I3gpE8F.png
I have tried to open "test" link(which points to rewrite.php page) but this page does not exists???
Here is list of all files in my root folder: http://i.imgur.com/kcQkeei.png I have downloaded latest elgg from https://elgg.org/download.php

I have also posted the very same question on http://stackoverflow.com/questions/32397515/rewrite-php-not-exists-in-elgg-instalation-files

**Comment by juho-jaakkola** [comment]
This is not a bug in the Elgg core but a server configuration issue, so please seek help from the Elgg community forums:  https://elgg.org/discussion/all

**Comment by direktnademokratija** [comment]
ok

**Comment by juho-jaakkola** [comment]
Oh, and the registration is disabled temporarily. So if you don't have a community account yet, send the preferred username to info@elgg.org and we'll create an account for you.

**Comment by direktnademokratija** [comment]
ok. thanks. Email sent.
