### ISSUE TITLE
Warn site upgraders about discussions or auto-enable it

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8920]
I suspect upgrading to 2.0 will effectively turn off the discussions feature until the site owner realizes it's a separate plugin. We should warn them or auto-enable it.

**Comment by juho-jaakkola** [comment]
Indeed, this just bit me this week. I suggest we add a new upgrade script that takes care of the job.

**Comment by juho-jaakkola** [comment]
I'll be ridiculously busy during the next couple of weeks. Would anyone have time for this?

**Comment by mrclay** [comment]
Why didn't this existing upgrade work for you? https://github.com/Elgg/Elgg/blob/2.0/engine/lib/upgrades/2015062900-1.11.2-discussion_plugin-e28c7afa4f5f24ec.php#L28
Should we just enable it even if groups is off?

**Comment by mrclay** [comment]
I'm leaning towards calling this done via the existing upgrade.

**Comment by juho-jaakkola** [comment]
I in fact thought that this was about the groups tool setting. But the setting name has not changed in 2.0, right? So if group has had discussions enabled in 1.x they should still be enabled in 2.x?

Best to check this...

**Comment by juho-jaakkola** [comment]
Yes, name of the group tool option is still the same "forum", and the upgrade script seems valid. Closing.
