### ISSUE TITLE
Datepicker i18n is broken

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8921]
The `input/date` view causes the error:

> Mismatched anonymous define() module

**Comment by mrclay** [comment]
I see only an input/date view in 2.0. Is that what you mean?

**Comment by mrclay** [comment]
OK, yes. The i18n files are AMD modules and we need to require() them.

**Comment by mrclay** [comment]
Each of these i18n modules depends on "datepicker", which we can't load via AMD. So each will have to be loaded [while hiding "define"](https://github.com/Elgg/Elgg/blob/2.0/views/default/jquery-ui.js.php#L4)

**Comment by mrclay** [comment]
PR #8934. I decided to manually define() the datepicker module. We may end up having to do this to other elements of jQuery UI since we're not loading it via require().

**Comment by juho-jaakkola** [comment]
I'm still getting this for individual languages:

> Requested view is not an asset

**Comment by juho-jaakkola** [comment]
This is incorrect when installed as a composer dependency: https://github.com/Elgg/Elgg/pull/8934/files#diff-0091fae98da654aa46227aa3132ea527R35

**Comment by juho-jaakkola** [comment]
I'm not yet familiar with the ```views.php```file.

How is it supposed to handle both cases:
 - Elgg installed in the site root
 - Elgg installed under ```vendors/``` as a composer dependency

**Comment by mrclay** [comment]
See https://github.com/Elgg/Elgg/blob/2.0/engine/classes/Elgg/Application.php#L257. So if Elgg is installed in `vendor/` and the site path has its own `views.php`, we merge it after the plugins.

**Comment by mrclay** [comment]
Both views.php are used, with the "site" version overriding the "engine" version.

**Comment by mrclay** [comment]
Not overriding as in views, just merged together.

**Comment by mrclay** [comment]
Ah. Maybe the array value should be `"vendor/...` instead of `__DIR__ . "/vendor/...`

**Comment by mrclay** [comment]
New fix #8956
