### ISSUE TITLE
All languages loaded to display settings page

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8923]
The current syntax error in `mod/embed/languages/it.php` shouldn't affect me loading my settings page, right?

**Comment by mrclay** [comment]
The issue is getInstalledTranslations() calls reloadAllTranslations().

If it's an admin we do show language completeness, but that already separately calls reloadAllTranslations(), so the call in getInstalledTranslations() doesn't seem necessary.

**Comment by iionly** [comment]
The problem with a faulty language file does also occur when running a site upgrade.

**Comment by mrclay** [comment]
This is probably not worth worrying about in the short term
