### ISSUE TITLE
Transifex provides translations with PHP syntax errors

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8924]
Short term strawman: Add a manual check of the `/admin/settings/basic` page in the release process.

**Comment by ewinslow** [comment]
For example?

**Comment by mrclay** [comment]
See error: https://github.com/Elgg/Elgg/blob/1.12/mod/embed/languages/it.php#L6

**Comment by mrclay** [comment]
PR #8952

**Comment by mrclay** [comment]
I opened https://github.com/transifex/transifex-client/issues/96. Might help, might not.
