### ISSUE TITLE
Option to alter the output of elgg_get_excerpt() function.

### ISSUE THREAD

**Issue by teamwebgalli** [Elgg/Elgg#8925]
It will be better is there is an option to alter the output of elgg_get_excerpt(). 

For example in some of our user cases we needed to pass a "...read more..." text with hyperlinks and class / id names instead of the current "...." output thing. If this is available, we don't have to unnecessarily duplicate the same code for this simple thing.

**Comment by juho-jaakkola** [comment]
So something like:
```php
$link = elgg_view('output/url', array(
    'src' => $entity->getURL(),
    'text' => '... read more ...',
));

echo elgg_get_excerpt($long_text, 100, array(
    'ellipsis' => $link,
));
```

**Comment by teamwebgalli** [comment]
Yes juho. This is enough for our current usage scenario.

**Comment by mrclay** [comment]
Hmm, I'd rather move the body of elgg_get_excerpt() into a view, giving sites full flexibility.
