### ISSUE TITLE
Cannot prevent relationships from being created

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#8927]
Since 1.9 it appears you cannot prevent relationships from being created by using an event handler.

The relevant code is at 
https://github.com/Elgg/Elgg/blob/1.9/engine/lib/relationships.php#L119
https://github.com/Elgg/Elgg/blob/1.12/engine/classes/Elgg/Database/RelationshipsTable.php#L127
https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/Database/RelationshipsTable.php#L120

The result of the event is boolean, but it passes that value into delete_relationship if the return is false.  The delete_relationship function expects the id of a relationship.
I'm either missing something or this is probably breaking a lot of things (and making my plugin upgrades impossible)

**Comment by juho-jaakkola** [comment]
We can fix the next Elgg 1.12.x to pass in the id instead of the boolean, right?

**Comment by beck24** [comment]
Yes, but that means version 1.9 - 1.11 are inherently broken - I feel like this couldn't have gone undiscovered this long - has nobody tried to prevent someone from joining a group or becoming friends?

**Comment by beck24** [comment]
@todo - are there no tests for this?

**Comment by juho-jaakkola** [comment]
> that means version 1.9 - 1.11 are inherently broken

Well yes, but I don't see why we would need to add the fix to them when its so easy to just upgrade to 1.12.x.

**Comment by beck24** [comment]
My own selfish reasons - I'm upgrading plugins for a university that works at the pace of an inefficient government and I'm under contract to give them 1.9 AND 1.12 compatible plugins, which is currently impossible :(

**Comment by mrclay** [comment]
For broken versions you could prevent these actions via removing UI elements, and/or intercept the action URLs.

Yeah, a bummer we're missing tests here.

**Comment by mrclay** [comment]
PR #8928

**Comment by beck24** [comment]
Unfortunately it's not quite that easy, some of the UI elements are bulk user management tools where the event is necessary to stop someone slipping an unauthorized person into a group with the batch.  Still need the batch UI available, need to let in the 14 authorized people and keep the 1 unauthorized person out.  Action intercepts can potentially work, but there's so many to worry about across plugins on a heavily modified site.  This event was the gatekeeper... (well the ```'join', 'group'``` event was, but we apparently got rid of that as a useable prevention method)

**Comment by mrclay** [comment]
Workaround: manually delete the unwanted relationship before returning false (or schedule it to be deleted in shutdown). Not ideal, but neither is running unsupported software.

**Comment by beck24** [comment]
Nice, that's a workaround that should work - thanks for the idea!
