### ISSUE TITLE
River items can only be deleted by admins

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8936]
- [x] Add ElggRiverItem::delete() and canDelete()
- [x] deprecate elgg_delete_river
- [x] use hook `permissions_check:delete`, `river` in canDelete()
- [x] default false unless is admin

**Comment by mrclay** [comment]
Due to BC we can't just make elgg_delete_river() start checking permissions. I suggest we just deprecate elgg_delete_river() and have devs use `elgg_get_river()` and `$item->delete()` like we do with entities.

**Comment by hypeJunction** [comment]
While at it, perhaps should add before and after events for river delete.

**Comment by mrclay** [comment]
PR #9964
