### ISSUE TITLE
"Invalid" translations fetched from Transifex

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8937]
There are translations available at Transifex for languages not "valid" for Elgg, i.e. using languages codes not in the array of allowed languages of Elgg. Additionally, it wouldn't even necessary for these translations to use such invalid codes because there are valid codes available (e.g. ro.php instead of ro_RO.php and eu.php instead of eu_es.php).

These languages can be selected as site / user language but this results in problems like AMD modules not loading correctly (e.g. within my extended_tinymce plugin).

I would suggest to fix the problem for the already existing translations at Transifex by dropping the languages with invalid languages codes and re-uploading these translations using the corresponding valid language codes. For the Japanese translations this approach has already been taken (ja_JP.php changed to ja.php). It's really becoming urgent to fix this problem once and for all (especially before the final 2.0 is out). And I would also suggest to not allowing any new arbitrary language to be added at Transifex but only languages that are valid (for Elgg) in the future.

**Comment by iionly** [comment]
Am I the only one with this problem? It happens both on Elgg 1.X and 2.X for me when trying ro_RO.php or eu_ES.php (error from require.js when trying to load the languages). When renaming these language files to ro.php and eu.php respectively there's no problem anymore. Even worse when selecting sr@latin you even get a fatal error already when trying to select this language ("Data too long for column 'language' at row 1").

**Comment by mrclay** [comment]
Definitely a problem, and detailed in existing issues. Arriving at a satisfying solution for everyone is the problem.

**Comment by juho-jaakkola** [comment]
I believe this gets fixed in the next release now that #8954 has been merged. The problems was only with language codes such as ```eu_ES``` but not with ```eu_es```, right?

**Comment by iionly** [comment]
I've only tested by renaming the eu_ES.php files to eu.php (same with ro_RO.php files). But I guess eu_es.php is likely to work, too, because the pt_br.php files hasn't shown the same issue. As the next Elgg version are due to be released soon we will soon find out...

**Comment by iionly** [comment]
Closing for now. If it isn't fixed in the next 1.12.X and 2.X releases I will re-open.
