### ISSUE TITLE
Allow (some) user lookups to find hidden/disabled users

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8941]
When we added entity::canDelete() [we allow it to look up hidden/disabled users](https://github.com/Elgg/Elgg/commit/6b12e45db14e635a1fca450f441ca0ff0fae20f0#diff-8a29a646367211561f3d07149076efffR1088). It's odd we do this for canDelete, but not canEdit or others (AFAICT).

cc @jdalsem

**Comment by jdalsem** [comment]
We moved that discussion to https://github.com/Elgg/Elgg/issues/8038 as you can read here https://github.com/Elgg/Elgg/pull/8031#discussion_r28133682

**Comment by mrclay** [comment]
PR #8944
