### ISSUE TITLE
Figure out a way to list all views in a directory

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8947]
Some plugins have the need to list all views located in a specific view directory. This is not possible anymore in Elgg 2.0 because the ```$CONFIG->viewpath``` value has been removed.

It would be nice to figure out either:
 - A new feature that does the job
 - Some kind of a workaround

#### Example case:

[Anypage](https://github.com/brettp/anypage) is [using](https://github.com/brettp/anypage/blob/1.9/classes/AnyPage.php#L394) the view location to list all layouts in ```views/default/page/layouts/```, so that user can use the layout of their choice with each anypage object.

#### Some ideas:
 1. A hook for defining available layouts (initial though is there aren't enough use cases to make it worth adding it)

 2. This works (but is it safe?):
```php
$viewpath = dirname(elgg_get_engine_path()) . "/views/default/";
```

**Comment by juho-jaakkola** [comment]
Not really a blocker for 2.0, but it would be nice to figure it out right away.

**Comment by juho-jaakkola** [comment]
Besides core Anypage is also checking for custom layouts from plugins.

**Comment by mrclay** [comment]
The views service has full paths for all views, the question is how to expose this.

**Comment by mrclay** [comment]
PR #8965

**Comment by mrclay** [comment]
@ewinslow are you against exposing this? If so, do you have any other ideas for this use case?

**Comment by beck24** [comment]
This is fine by me - we need something like this to be public API

**Comment by ewinslow** [comment]
I'd be comfortable with an api that lists views, but not at the directory/filesystem level. You cannot assume anything about the views available just given a directory path.

**Comment by ewinslow** [comment]
I don't see how this use case is addressed by the PR. Views can no longer be guaranteed to reside in a views/default structured directory.

**Comment by ewinslow** [comment]
We could just as easily have an API that lists all views by name without mapping to a full file path. These views can then be filtered by prefix to determine which page/layouts/* views are available, but then you still need to render them using elgg_view, rather than working directly with the file

**Comment by mrclay** [comment]
Array of view names per viewtype seems acceptable.

**Comment by mrclay** [comment]
PR #8987 limits the list to view names.
