### ISSUE TITLE
Deprecate logged-in-user magic from permission checks

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8953]
Most of our permission checks default to the logged in user in case a user is not explicitly passed into the permission check functions.

Deprecating this feature will:
- Make permission checks safer as it forces devs to think what they're doing instead of relying on magic
- Reduce the complexity of core

**Comment by juho-jaakkola** [comment]
We might also type hint ```ElggUser``` to further reduce boilerplate.

**Comment by mrclay** [comment]
Transition might be tricky. We'd have to leave the default as `0` and interpret `null` as logged out, which might present a BC break.

**Comment by juho-jaakkola** [comment]
I forgot that sometimes we may need to check also non-logged-in users. Could an empty ElggEntity object represent a non-logged in user?

```php
$container->canWriteToContainer(new ElggUser());
```

**Comment by mrclay** [comment]
A long time ago I proposed a UserState value object with just a few methods (getUser, getGuid, isLoggedIn). The value is in eliminating ambiguity. null means you don't have it, and the API can fetch it for you. If you pass it in, the API knows you *intend* for that state to be used.

Using a `new ElggUser` to mean logged out user I think would be dangerous as it leaked into other areas of the API. E.g. so many places we use a boolean check to see if there's an object or falsey.

Something like this would be BC safe:
```php
function doSomething($user = 'not_given') {
    // here we can safely distinguish between these values:
    // ElggUser = logged in
    // null = logged out
    // 'not_given' = pull from session, throw exception, or whatever
}
```

**Comment by mrclay** [comment]
Eh, that's no good either, same problem as using 0.

**Comment by mrclay** [comment]
Using entityTable->getUserForPermissionsCheck() internally, this seems no longer a big problem. If it's really worth breaking a ton of API to be more strict, we can use something [like this](https://gist.github.com/mrclay/d80696e5ad6a71b70bb2), which can unambiguously represent a logged out user.

**Comment by jdalsem** [comment]
Going to leave this as is

**Comment by hypeJunction** [comment]
I don't think we should leave it as is

**Comment by jdalsem** [comment]
for now we will... both ideas were not solving the issue. Can reopen this when there is something better
