### ISSUE TITLE
Invite Friends

### ISSUE THREAD

**Issue by starphysique** [Elgg/Elgg#8957]
Testing 2.0 beta 1. When inviting friends and adding multiple addresses (one per line), identical invite code is created multiple times and sent to each unique email address.

**Comment by starphysique** [comment]
and it appears that you can keep using. ad infinitum, the same "unique" code.

**Comment by hypeJunction** [comment]
That's expected behavior. The invite code is unique to the inviting user, not the invitee. Invitees are still expected to go through the registration process, and the invite code is used to friend them with the inviting user. 
If you need unique codes, you would have to implement some custom logic.
