### ISSUE TITLE
Elgg 2.X: elgg.echo() not working in any other language than English within AMD modules

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8958]
see also https://elgg.org/discussion/view/2368031/how-to-get-elggecho-working-in-user-language-within-amd-module

It seems this is a problem on Elgg 2 only (currently on Elgg 2 beta1 installed from zip). On Elgg 1.10/1.11 it's working as intended also when elgg.echo() is used within an AMD module.

**Comment by juho-jaakkola** [comment]
I've noticed the same.

**Comment by mrclay** [comment]
PR #8964
