### ISSUE TITLE
uservalidationbyemail plugin hijacks forward location indiscriminately

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#8960]
If uservalidationbyemail is active, and you hook into ```action/register```, you cannot do ```forward(REFERER)``` as the plugin hijacks that url whether or not registration has occurred.

This can be made more selective by setting the handler after a successful registration.

**Comment by mrclay** [comment]
Sounds good

**Comment by beck24** [comment]
This is a non-issue since at least 1.12
