### ISSUE TITLE
Discussions plugin is missing from Transifex config

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8972]

**Comment by juho-jaakkola** [comment]
I updated the config locally but Transifex client isn't still pulling the translations. Not even when using the ```-f``` flag.

**Comment by juho-jaakkola** [comment]
Now it started working for no apparent reason...

**Comment by mrclay** [comment]
I wonder why `Fixes #` no longer auto-closes...

**Comment by juho-jaakkola** [comment]
It's because 2.x is the default branch. Issues won't get marked done until they're merged there.
