### ISSUE TITLE
FR: elgg_entity_gatekeeper() returns the entity

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8973]
Normally the entity_gatekeeper is used to prevent access to pages handling a certain entity. Current usage is (most of the time) the following example:

```php
$guid = (int) get_input('guid');
elgg_entity_gatekeeper($guid, 'object', 'blog');
$blog = get_entity($guid);
```

Currently the gatekeeper returns nothing (void). If we could change this to returning the entity it has 'protected', this could improve the example above as follows:

```php
$guid = (int) get_input('guid');
$blog = elgg_entity_gatekeeper($guid, 'object', 'blog');
```

**Comment by jdalsem** [comment]
the same could also apply to the group_gatekeeper

**Comment by hypeJunction** [comment]
I am not sure I like that. I don't think gatekeeper functions should be returning anything. It's confusing when you a expect an entity in return, and itstead you are forwarded to another page...

**Comment by juho-jaakkola** [comment]
I agree with @hypeJunction

**Comment by mrclay** [comment]
I think this was proposed before and got similar resistance. It doesn't seem to save considerable work or eliminate common errors, so I'm leaning against it as well.

**Comment by beck24** [comment]
I agree, it reduces one line of boilerplate but adds a somewhat unexpected return value to the function.

**Comment by mrclay** [comment]
FYI this idea is at least 3 years old :) https://github.com/Elgg/Elgg/pull/5791#discussion_r5164145

**Comment by jdalsem** [comment]
Both my proposals (i forgot i submitted it before) got shot down hard... however this still keeps popping up when developing plugins

**Comment by mrclay** [comment]
With autocomplete I counted about 3 seconds of typing savings. But now every time I approach this code I have to wonder whether the Elgg version in the plugin's manifest has this new behavior, and every time I give advice I have to add "only in Elgg 2.3+". So to me it seems like a bad trade off for this specific case.

That said, in general I'm probably underestimating the benefits of an API that moves forward and is cleaner to write for. I'll try to remember that.
