### ISSUE TITLE
1.12 branch is missing

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8974]
shouldn't there be a 1.12 branch? Or is 1.x the 1.12 branch???

**Comment by mrclay** [comment]
I don't what happened. When I fetched from origin it listed it. Anyway I pushed my copy back up.

cc @Elgg/owners

**Comment by mrclay** [comment]
Ah, accidental delete after merge https://github.com/Elgg/Elgg/pull/8971#event-415125839

**Comment by jdalsem** [comment]
Maybe we should start using protected branches: https://github.com/Elgg/elgg/settings/branches

cc @Elgg/owners

**Comment by beck24** [comment]
ooh, I didn't know that option existed.  We definitely need that.

**Comment by mrclay** [comment]
Done. I protected 1.12, 1.x, 2.0, 2.x, and master

**Comment by juho-jaakkola** [comment]
Oops, sorry about that! :/

**Comment by ewinslow** [comment]
Awesome so helpful!

On Tuesday, September 22, 2015, Juho Jaakkola <notifications@github.com>
wrote:

> Oops, sorry about that! :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/Elgg/issues/8974#issuecomment-142366819>.
>


-- 
Evan Winslow
http://community.elgg.org/profile/ewinslow
