### ISSUE TITLE
FR: elgg_spinner support text to show in spinner

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8979]
When starting the Elgg spinner (loading ajax content), it would be nice if we optionally could add text to the `spinner.start()` function so we can provide feedback to the end user what we are waiting on.

So `spinner.start(elgg.echo('Waiting on the pizza guy'));` results in:
![waiting on the pizza guy](https://cloud.githubusercontent.com/assets/861833/10073597/61070b64-62ca-11e5-8bd1-6befb9df0745.png)

**Comment by mrclay** [comment]
SGTM but I don't foresee myself using this as I fear it will often disappear before users can read it. That would frustrate me as a user. Maybe a better place for the message would be near the UI element activated to start the action.
