### ISSUE TITLE
Container magic in ElggEntity::create()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8981]
In `ElggEntity::create()`, `$container_guid` is set to `$owner_guid` if `0`. However later, the code tries to get container entity using `$this->getContainerEntity()`, rather than using `get_entity($container_guid)`.

Not sure what's going on there, but I getting:
`ERROR: User 2 tried to create a (object, album_image), but the given container 2 could not be loaded.`

**Comment by Daltonmedia** [comment]
Anyone an idea already what could be causing this?
