### ISSUE TITLE
Members search page is lacking pagination

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8986]
No pagination when searching for users via the sidebar input box on the member search page... could be a bug, but we could also handle it as a feature :)

Example here: https://elgg.org/members/search?member_query=ben

**Comment by mrclay** [comment]
Works for me. Maybe an elgg.org issue?

**Comment by mrclay** [comment]
It works with an explicit limit https://elgg.org/members/search?member_query=ben&limit=10
