### ISSUE TITLE
Multiple Authentication Modules

### ISSUE THREAD

**Issue by solace** [Elgg/Elgg#8988]
Hi,

The documentation on http://learn.elgg.org/en/latest/guides/authentication.html suggests that multiple authentication methods should be able to be used at one time, however I am having difficulty with the implementation of this.

I have users using the native Elgg authentication method. And I have an LDAP module which authenticates users via LDAP. Both in isolation work fine, however if I try to authenticate with a native auth user while the LDAP module is enabled, the auth fails.

I have tried to invoke the `register_pam_handler` with importance set to `sufficient` instead of `required`, but it still just returns a fail from LDAP, when it should succeed on native.

Is there something I'm missing in making both available and having auth return success if one of the methods succeeds?

Thanks

**Comment by hypeJunction** [comment]
I am quite sure that PAM works as it should, so my guess is you are misunderstanding the auth flow. PAM handlers usually do not start the session, you have to call `login()` explicitly:

```php

if (elgg_authenticate($username, $password) === true) {
   login($user);
}
```

That will iterate through all `'user'` PAM policies and return `true` if any of them passes. Every failed PAM should log an error (if logging is enabled).

**Comment by solace** [comment]
I had that, but for some reason it was failing before, but seems to work now. Peculiar. Oh well, thanks.
