### ISSUE TITLE
2.0: Use elgg-plugin.php for plugin config data

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8992]
In #8991 I add a convention for a plugin config file. Instead of separate files for views and whatever else we come up with, should we have all configuration in `elgg-config.php`?

```php
// mod/example/elgg-plugin.php
return [
    'views' => [
        'default' => [
            ...
        ],
    ],
];
```

**Comment by mrclay** [comment]
@hypeJunction since you're working on a 2.0 plugin, do you have any thoughts on this?

**Comment by hypeJunction** [comment]
I would be in favour if plugins can access/overwite each other's config. Otherwise I quite like narrow-purposed files.
It would also be cool if those values could be fed to `elgg_get_plugin_setting`

**Comment by jdalsem** [comment]
This has been fixed with https://github.com/Elgg/Elgg/pull/10077
