### ISSUE TITLE
Document configuring AMD modules via [config, amd]

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8997]
This lets us sneak server-side data to modules via the elgg/require_config module. The idea is to eliminate the need for PHP modules just to pass a bit of server data in.

**Comment by hypeJunction** [comment]
This is very interesting, I didn't realize we could. Looking forward to learning more.

**Comment by mrclay** [comment]
See https://github.com/mrclay/Elgg-leaf/blob/elgg_echo_8345/engine/classes/Elgg/Amd/Config.php#L243 and https://github.com/mrclay/Elgg-leaf/blob/f9ed77ecab124c4e757682cbabda53b29e44ca35/views/default/elgg/echo.js#L6

**Comment by hypeJunction** [comment]
:8ball: Thought it would be cooler to just attach it to `elgg.config` so it's available across all modules.

**Comment by hypeJunction** [comment]
On a second thought, I think it's easier to just create a new AMD module and require it as needed.

**Comment by hypeJunction** [comment]
In case of `lang`, I don't see why you would want to pass that via AMD config. We already have `elgg.config.language` available in the global scope.

**Comment by mrclay** [comment]
Yeah that's simpler.

The thought Evan and I had was that elgg is right now a big God object and I try to avoid depending on it, but realistically that's not going to change soon. First big painful change will be making elgg truly async.
