### ISSUE TITLE
AMD elgg module blocks on too many translations

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8999]
Elgg currently loads over 27K (gzipped) of translations by default, and these block all modules dependent on the "elgg" module. By switching to an asynchronous replacement for `elgg.echo()`, we can instead depend on a tiny subset of translations (likely <1K) known to be needed, and load the rest as they are needed.

What we should agree on here is the strategy going into 3.0. After several iterations in PRs, I propose this (implemented in #8991):
- in 2.1, deprecate `elgg.echo` and add an async (require-based) API
- in 3.0:
  - let plugins to declare translation keys likely to be needed on the home and other common landing pages
  - the `elgg` module blocks on a minimal language module with only those keys
  - load the remaining keys in a 2nd module when one of them is needed
- in 2.x, allow devs to preview the 3.0 behavior via an experimental setting

**Comment by iionly** [comment]
Would it make sense to discuss about this on the community site to decide on what to do exactly and how to prepare the change for Elgg 3.0?

What I don't understand is what exactly a "tiny subset of translations" is referring to. Is it only the keys used by elgg.echo() in JS code or does it also refer to possibly more keys? Isn't there any other way to implement the asyncronous elgg_echo without the need to manage such a separate subset?

**Comment by mrclay** [comment]
If elgg.echo() gets called during page load, you want that key loaded early. E.g. [for ckeditor](https://github.com/Elgg/Elgg/pull/8991/files#diff-5b8929791a079a39479e79b581cb70a0R1).

> Isn't there any other way to implement the asyncronous elgg_echo without the need to manage such a separate subset?

Yes, that's what #8991 does in 2.x. The full language file gets loaded, but elgg/echo provides async access to it. But at some point someone has to make a decision of which keys to load automatically. Loading each one separately would kill performance.

**Comment by mrclay** [comment]
Strawman 2: Give site owners the ability to split file loading and specify early keys, but leave elgg.echo() as is. "elgg" would only block on the early keys, the rest could be required but not block anything. Good: Plugins wouldn't have to be rewritten; site owners that need perf can focus on it. Bad: default would remain status quo; site owners could break some of their client-side translations.

**Comment by jdalsem** [comment]
Closing this as i have never experienced this behaviour myself
