### ISSUE TITLE
2.0: Remind users to symlink the _graphics dir if they need it.

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9003]
If installed via composer, old plugins maybe point directly to _graphics files so they will need a symlink.

**Comment by jdalsem** [comment]
Do we still need this? The Elgg 2.0 upgrade guide mentioned not to directly refer to `_graphics`

**Comment by jdalsem** [comment]
Closing this as we are well into 2.x and not experiencing big issue with this
