### ISSUE TITLE
[feature requests] - Improve registration proces for email verification with a invalid emailaddress

### ISSUE THREAD

**Issue by ghost** [Elgg/Elgg#9008]
Hello,
We have many mistyped email addresses causing new users registration failure. They of course blame the platform for not sending validation email, not knowing about their mistake so, possibly, having the email field double-checked in registration form woud be better.
Cheers

**Comment by mrclay** [comment]
I'd prefer adding https://github.com/mailcheck/mailcheck to core. Having a 2nd e-mail field to verify is less common and could be easily done in a plugin.

**Comment by michelesbw** [comment]
Thanks for taking this into consideration Steve. Well if that script has a wide db of email domains then nice but don't agree on "less common" because also Facebook has 2nd email field :)

**Comment by mrclay** [comment]
Good point but remember Facebook doesn't really have to worry about users abandoning their registration form. Most sites have to make that UX as quick and painless as possible.

**Comment by michelesbw** [comment]
True, either one would be a good improvement imho.
