### ISSUE TITLE
FR prevent auto disabling of plugins with a setting

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9009]
It would be nice if auto disabling invalid plugins could be turned of with a config in settings.php.

When updating plugins you sometimes run into the problem that the site is used while updating. When replacing plugins with newer versions this could result in those plugins being disabled.

With a config line in settings.php this behaviour could be prevented
`$CONFIG->auto_disable_plugins = false`

**Comment by mrclay** [comment]
If, e.g., `start.php` and some classes are missing, and we don't deactivate, letting full requests be served seems like a bad idea.

Could we make a more minimal maintenance mode that doesn't fully boot plugins, but relies on a $CONFIG option?

**Comment by jdalsem** [comment]
what is "not fully booting plugins"? you can add a disable file in the mod dir to not boot plugins already

**Comment by mrclay** [comment]
I guess I just mean users get a nice maintenance mode screen AND plugins don't boot.

**Comment by mrclay** [comment]
Would using `git pull` for deployment eliminate this problem?

**Comment by mrclay** [comment]
You're probably right that having core disable the plugin is probably worse than potentially crashing a few requests.

**Comment by mrclay** [comment]
I guess I'm not opposed as long as the option comes with sufficient warnings (the system, cache locations, and other plugins will all assume those files exist).
