### ISSUE TITLE
Integer casting in relationships API

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9019]
Had a typo in my code and was surprised to see a relationship added with the site entity:

``` php
add_entity_relationship('something true', 'relationship', $guid_two);
```

**Comment by mrclay** [comment]
Almost all our APIs cast int. I'm not sure this is worth worrying about, but [this](http://php.net/manual/en/function.is-int.php#82857) seems the most sane (positive) int validation.

**Comment by jdalsem** [comment]
Not going to do anything about it. In all our apis we do this the same way... just try to set `access_id` on an entity to 'foo' and it also has similar issues. We are not going to fix this for this specific case.
