### ISSUE TITLE
lightbox and forward

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9027]
Not sure if there is an easy solution, but whenever a page handler uses `forward()`, lightbox receives and displays a json object. Too bad we use `elgg_is_xhr()` to assume `Accept: application/json`

**Comment by mrclay** [comment]
Does it do the same if you just `return` instead of `forward()`?

**Comment by hypeJunction** [comment]
Not really an option with `forward('', '404')` that is used all over the place

**Comment by mrclay** [comment]
Workaround: Make requests with a query string option or HTTP header that triggers unregistering ajax_forward_hook().

ajax_forward_hook() should be making sure ajax_action_hook() actually fired first. I.e. it's logic shouldn't apply to non-actions. That might be a BC bugfix.

**Comment by mrclay** [comment]
@ewinslow I assume in https://github.com/Elgg/Elgg/commit/c3277515ae8ad8aea53e53562fef01d339fcdeb1 the intention was to send the JSON wrapper back only on actions?

**Comment by ewinslow** [comment]
Yes

**Comment by mrclay** [comment]
Next step: PR on 1.12 making sure ajax_forward_hook() does nothing if ajax_action_hook() was not previously called.

**Comment by hypeJunction** [comment]
While at it, should probably do something about https://github.com/Elgg/Elgg/issues/8735

**Comment by hypeJunction** [comment]
I don't think we can fix this in a BC way. I am pretty sure I have seen people rely on json wrapper for non-action URLs. 
One thing we could do is check the forward reason, and send a proper HTTP header for error pages. `elgg.ajax` should be able to interpret it as an error, and lightbox will fail silently.

**Comment by hypeJunction** [comment]
Sort of a possible fix in #9210

**Comment by mrclay** [comment]
> I have seen people rely on json wrapper for non-action URLs

Yep, as I'm [documenting here](https://github.com/Elgg/Elgg/pull/8955/files#diff-ba10b90f7fa335aca7ec12c93cf7ea31R287), using `forward()` anywhere in an ajax request causes the JSON wrapper and `output, ajax` hook to be used.
