### ISSUE TITLE
FR: save:before event

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9033]
Sometimes this would be preferable to the create/update events. Consider a plugin that wants to make sure a user's objects stay private. With update/create you're always reacting to the given data and have to re-save(), which calls the update event again.

save:before would basically let you alter attributes before the storage phase (and calling save() during the save:before event would register an error and be ignored).

Not sure it should let you cancel it though...

**Comment by juho-jaakkola** [comment]
+1

**Comment by mrclay** [comment]
#9187 will probably be necessary in whatever scheme we choose, because plugins will need to detect changes.
