### ISSUE TITLE
Vertical alignment of (enlarged) delete icon in river entity menu not right and sometimes partly hidden

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9035]
The (font awesome) delete icon is now increased to make it appear in the same size than the other icons. But on the river page the delete icon appears to be lower aligned than the other entity menu icons. Even worse, of the river entry has only content in the title line but no body the delete icon is even party hidden.

**Comment by hypeJunction** [comment]
Screenshot? It's hard to visualise what you are talking about.

**Comment by iionly** [comment]
Delete icon in entity menu outside activity page (everything seems alright):

![delete-icon2](https://cloud.githubusercontent.com/assets/1773681/10534202/3a63c83c-73d5-11e5-9479-9ca597c5dafe.jpg)

Delete icon in entity menu of an entry on activity page (not alright):

![delete-icon1](https://cloud.githubusercontent.com/assets/1773681/10534206/4ee97176-73d5-11e5-8874-3b5f4077182e.jpg)

**Comment by mrclay** [comment]
Simplest solution I can see is: 
```css
.elgg-icon-delete {
    line-height: 1em;
}
```

**Comment by mrclay** [comment]
That should probably be on .elgg-icon. That would allow any other icons to be enlarged like we do times.

**Comment by hypeJunction** [comment]
Meh on adding more styling to icons, they should really just inherit everything. But I don't care that much, since all my themes are custom.

**Comment by mrclay** [comment]
@iionly Wanna send a PR for 2.0? Just add `line-height: 1em` to all the definitions of `.elgg-icon`.

**Comment by iionly** [comment]
Done.

**Comment by mrclay** [comment]
Fixed by 12a8908cad89e6badb118ab00bc69924ec0f0c37
