### ISSUE TITLE
IDEA: Ignore metadata access in 3.0

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9050]
Basically the API wouldn't change but md.access_id would be ignored on queries and in the metadata cache. Always reads a public. Baby step to removing it from the API completely.
- Deprecation PR 2.x: #9069
- Implementation PR master: #10270

**Comment by hypeJunction** [comment]
I think we should first solicit any real life use cases for metadata access
that people may have. I am sure we have done something "creative" with it
in the past, but can't think of anything right now. I would be happy to see
md access gone for good.

**Comment by hypeJunction** [comment]
Also would this mean public for annotation access?

**Comment by mrclay** [comment]
One use case for md access is user profile fields. But you can sort of emulate access ID via another metadata value: `$user->field1` ... `$user->field1_access_id`. Querying wouldn't be as straightforward.

I don't see why annotations don't have to be touched for this.

**Comment by beck24** [comment]
Yeah, profile fields, and the profile icon access plugin uses metadata access id, but can be easily modified to fit any other model so that use case doesn't concern me.

**Comment by mrclay** [comment]
Already passes tests! https://github.com/mrclay/Elgg-leaf/commit/7a3bc3d171cc75c5459e82d0af4c91ac7f7b281c

All profile fields are public of course :)

**Comment by mrclay** [comment]
Converting profile fields to annotations or ElggObjects would be the way to go since we have to search them considering ACCESS_ID.

**Comment by hypeJunction** [comment]
> Converting profile fields to annotations or ElggObjects would be the way to go since we have to search them considering ACCESS_ID.

We will loose the ability to use `ege_from_metadata`

**Comment by mrclay** [comment]
See #9050

**Comment by mrclay** [comment]
See #9052. Already working surprisingly well.

**Comment by beck24** [comment]
Ooh, that's going to make for some upgrade hell...
How far spread out is profile info in some our apps where it's something like

    echo $user->md_name

or

    if ($user->md_name == value) {
        // special case
    }

All of those need to be done by fetching an annotation first?

**Comment by mrclay** [comment]
Well we could have profile fields stored in both. Annotations for access-controlled display and searching, metadata for BC (without the access control of course).

**Comment by mrclay** [comment]
Another option is to keep using MD for fields, but control access some other way. Or keep access_id in the API, but ignore it unless explicitly asked for in an elgg_get_metadata option.

**Comment by beck24** [comment]
>Or keep access_id in the API, but ignore it unless explicitly asked for via an elgg_get_metadata option. That gives 99.9% of the benefit (faster queries, more MD cache hits), while providing an easier upgrade path for plugins.

I like the sound of this option.

**Comment by mrclay** [comment]
But my preference would be to pull the band-aid off completely. I don't like leaving arguments like $access_id in the API but not having them work as they do elsewhere.

It also makes deprecation harder. Ideally we'd give a deprecation notice whenever someone passed in an int for `$access_id` in `create_metadata()` or `setMetadata()`, or set `$md->access_id`. If we kinda sorta still allow it, we can't do that.

**Comment by mrclay** [comment]
Do we have to worry about group profile data at all?

**Comment by mrclay** [comment]
PR #9069 is the deprecation strategy

**Comment by gerard-kanters** [comment]
We are using SOLR for querying MD for profiles and groups See https://github.com/arckinteractive/elgg_solr/pull/30 

We have several use cases for this. 

I also like the idea of of having less tables (to avoid joins) and  remove the distinction between metadata and annotations.

**Comment by jdalsem** [comment]
Because of the deprecation in 2.3 this is now a must fix for 3.0
