### ISSUE TITLE
Elgg 2.0: tables crashing!

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9057]
I'm using MariaDB (version 10.0.21) and this might be part of the problem with tables crashing.

First time at all that I had a problem with tables crashing was happening both on 1.X and 2.X not long ago and in this case it was due to the archive engine not being loaded (https://github.com/Elgg/Elgg/issues/8741). Then I had another issue with table crashing because the AriaDB engine of MariaDB not being able to handle delayed queries (https://github.com/Elgg/Elgg/issues/8744). Fixed that by using "max_delayed_threads = 0" in my.cnf.

But now I have yet another issue with table crashing. Now it happens only on Elgg 2.0 (beta) and in this case it's the private_settings table that crashed. Twice! It seems to happen when garbagecollector runs (weekly cron). Though I'm not sure because after repairing the table I couldn't reproduce the crash when I re-run the cronjobs.

Anyone else has similar problems?

Log entries:
```
[Sun Oct 25 00:00:04.032187 2015] [php5:error] [pid 23481] [client 127.0.0.1:43835] Exception #1445724004: exception 'DatabaseException' with message 'An exception occurred while executing 'SELECT value FROM elgg_private_settings\n\t\t\twhere name = 'period' and entity_guid = 23':\n\nSQLSTATE[HY000]: General error: 144 Table './elgg20zip/elgg_private_settings' is marked as crashed and last (automatic?) repair failed\n\n QUERY: SELECT value FROM elgg_private_settings\n\t\t\twhere name = 'period' and entity_guid = 23' in /xxx/elgg/elgg/engine/classes/Elgg/Database.php:413\nStack trace:\n#0 /xxx/elgg/elgg/engine/classes/Elgg/Database.php(366): Elgg\\Database->executeQuery('SELECT value FR...', Object(Doctrine\\DBAL\\Connection))\n#1 /xxx/elgg/elgg/engine/classes/Elgg/Database.php(217): Elgg\\Database->getResults('SELECT value FR...', '', true)\n#2 /xxx/elgg/elgg/engine/classes/Elgg/Database/PrivateSettingsTable.php(312): Elgg\\Database->getDataRow('SELECT value FR...')\n#3 /xxx/elgg/elgg/engine/lib/private_settings.php(67): Elgg\\Database\\PrivateSettingsTable->get(23, 'period')\n#4 /xxx/elgg/elgg/engine/classes/ElggEntity.php(657): get_private_setting(23, 'period')\n#5 /xxx/elgg/elgg/engine/classes/ElggPlugin.php(877): ElggEntity->getPrivateSetting('period')\n#6 /xxx/elgg/elgg/engine/classes/ElggPlugin.php(278): ElggPlugin->__get('period')\n#7 /xxx/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(938): ElggPlugin->getSetting('period', NULL)\n#8 /xxx/elgg/elgg/engine/lib/plugins.php(361): Elgg\\Database\\Plugins->getSetting('period', 'logrotate', NULL)\n#9 /zzz/elgg20zip/mod/logrotate/start.php(40): elgg_get_plugin_setting('period', 'logrotate')\n#10 [internal function]: logrotate_archive_cron('cron', 'weekly', '', Array)\n#11 /xxx/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(38): call_user_func_array('logrotate_archi...', Array)\n#12 /xxx/elgg/elgg/engine/lib/elgglib.php(800): Elgg\\PluginHooksService->trigger('cron', 'weekly', Array, '')\n#13 /xxx/elgg/elgg/engine/lib/cron.php(67): elgg_trigger_plugin_hook('cron', 'weekly', Array, '')\n#14 [internal function]: _elgg_cron_page_handler(Array, 'cron')\n#15 /xxx/elgg/elgg/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_cron_page...', Array, 'cron')\n#16 /xxx/elgg/elgg/engine/classes/Elgg/Application.php(393): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#17 /xxx/elgg/elgg/engine/classes/Elgg/Application.php(349): Elgg\\Application->run()\n#18 /zzz/elgg20zip/index.php(8): Elgg\\Application::index()\n#19 {main}
[Sun Oct 25 00:00:04.162988 2015] [php5:error] [pid 23481] [client 127.0.0.1:43835] Exception #1445724004 : fatal error in exception handler : An exception occurred while executing 'SELECT value FROM elgg_private_settings\n\t\t\twhere name = 'elggx_fivestar_view' and entity_guid = 138':\n\nSQLSTATE[HY000]: General error: 144 Table './elgg20zip/elgg_private_settings' is marked as crashed and last (automatic?) repair failed\n\n QUERY: SELECT value FROM elgg_private_settings\n\t\t\twhere name = 'elggx_fivestar_view' and entity_guid = 138
[Sun Oct 25 00:01:01.626306 2015] [php5:error] [pid 682] [client 127.0.0.1:43872] Exception #1445724061: exception 'DatabaseException' with message 'An exception occurred while executing 'SELECT  e.*, plugin_oe.*, r.id FROM elgg_entities e  JOIN elgg_private_settings ps on ps.entity_guid = e.guid  JOIN elgg_objects_entity plugin_oe on plugin_oe.guid = e.guid  JOIN elgg_entity_relationships r on r.guid_one = e.guid  WHERE  ps.name = 'elgg:internal:priority' AND  (r.relationship = 'active_plugin' AND r.guid_two = '1') AND  ((e.type = 'object' AND e.subtype IN (1))) AND  (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY CAST(ps.value as unsigned), e.guid':\n\nSQLSTATE[HY000]: General error: 144 Table './elgg20zip/elgg_private_settings' is marked as crashed and last (automatic?) repair failed\n\n QUERY: SELECT  e.*, plugin_oe.*, r.id FROM elgg_entities e  JOIN elgg_private_settings ps on ps.entity_guid = e.guid  JOIN elgg_objects_entity plugin_oe on plugin_oe.guid = e.guid  JOIN elgg_entity_relationships r on r.guid_one = e.guid  WHERE  ps.name = 'elgg:internal:priority' AND  (r.relationship = 'active_plugin' AND r.guid_two = '1') AND  ((e.type = 'object' AND e.subtype IN (1))) AND  (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY CAST(ps.value as unsigned), e.guid' in /xxx/elgg/elgg/engine/classes/Elgg/Database.php:413\nStack trace:\n#0 /xxx/elgg/elgg/engine/classes/Elgg/Database.php(366): Elgg\\Database->executeQuery('SELECT  e.*, pl...', Object(Doctrine\\DBAL\\Connection))\n#1 /xxx/elgg/elgg/engine/classes/Elgg/Database.php(200): Elgg\\Database->getResults('SELECT  e.*, pl...', '', false)\n#2 /xxx/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(599): Elgg\\Database->getData('SELECT  e.*, pl...')\n#3 /xxx/elgg/elgg/engine/lib/entities.php(507): Elgg\\Database\\EntityTable->fetchFromSql('SELECT  e.*, pl...', NULL)\n#4 /xxx/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(471): _elgg_fetch_entities_from_sql('SELECT  e.*, pl...', NULL)\n#5 /xxx/elgg/elgg/engine/classes/Elgg/Database/MetadataTable.php(484): Elgg\\Database\\EntityTable->getEntities(Array)\n#6 /xxx/elgg/elgg/engine/classes/Elgg/Database/RelationshipsTable.php(347): Elgg\\Database\\MetadataTable->getEntities(Array)\n#7 /xxx/elgg/elgg/engine/lib/relationships.php(205): Elgg\\Database\\RelationshipsTable->getEntities(Array)\n#8 /xxx/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(413): elgg_get_entities_from_relationship(Array)\n#9 /xxx/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(338): Elgg\\Database\\Plugins->find('active')\n#10 /xxx/elgg/elgg/engine/classes/Elgg/Application.php(255): Elgg\\Database\\Plugins->load()\n#11 /xxx/elgg/elgg/engine/classes/Elgg/Application.php(391): Elgg\\Application->bootCore()\n#12 /xxx/elgg/elgg/engine/classes/Elgg/Application.php(349): Elgg\\Application->run()\n#13 /zzz/elgg20zip/index.php(8): Elgg\\Application::index()\n#14 {main}
```

**Comment by beck24** [comment]
The only site I've extensively used 2.0 with so far is the elgg community, but no such issues as far as I'm aware.

**Comment by iionly** [comment]
It might be another issue with MariaDB on my server (possibly not used on the community site server). On the other hand, it seems to happen only with the 2.0 test installation and not with the multiple 1.X test installations on the same server (and I'm not aware that anything significantly changed for 2.0 within the core plugins logrotate, garbagecollector that run at their cronjobs at the time the table is crashing).

The 2.0 test installation is a zip installation. Is the community site Elgg 2.0 installation a composer installed site? That might be the reason why it happens on my test server but not on the community site. But I'm at a loss at finding out why the table is crashing in the first place. I only see the log entries when the table has already crashed.

**Comment by jdalsem** [comment]
There are no similar reports, so assuming for now the problem is related to your specific situation. If you have more information please let us know

**Comment by iionly** [comment]
I still have this problem occasionally. But only on Elgg 2 and no longer on 1.X since turning of delayed inserts (by adding max_delayed_threads = 0 to my.cnf).

The problem is to reproduce the issue. It seems it's always the private_settings table which is crashing and always in connection with executing the weekly cronjobs. This interval triggers only logrotate and garbarge collection and I think the latter is causing the table to crash.

If it would be my server situation only why is it happening on Elgg 2 only currently? Anyone some ideas how to improve the chances of reproducing the issue? Today I tried with manually triggering the weekly cronjobs but no table crashed...

**Comment by iionly** [comment]
Okay. Got the crashing private_settings table again on execution of weekly cronjobs. I think I can also reproduce the table crash by manually calling the cron/weekly in the browser very fast (second time immediatelly after the first time is finished). I don't know if it also matters what scripts are registered for the cron intervall. In my case, the weekly intervall has garbagecolletion and logrote.

The first fatal error might be some explanation for the problem:

[Thu Sep 01 22:31:45.275890 2016] [php5:error] [pid 11447] [client 127.0.0.1:60172] Exception at time 1472761905: exception 'DatabaseException' with message 'An exception occurred while executing 'INSERT into elgg_private_settings\n\t\t\t(entity_guid, name, value) VALUES\n\t\t\t(1, 'cron_latest:weekly:ts', '1472761904')\n\t\t\tON DUPLICATE KEY UPDATE value='1472761904'':\n\nSQLSTATE[HY000]: General error: 144 Table './elgg20zip/elgg_private_settings' is marked as crashed and last (automatic?) repair failed\n\n QUERY: INSERT into elgg_private_settings\n\t\t\t(entity_guid, name, value) VALUES\n\t\t\t(1, 'cron_latest:weekly:ts', '1472761904')\n\t\t\tON DUPLICATE KEY UPDATE value='1472761904'' in /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Database.php:443\nStack trace:\n#0 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Database.php(249): Elgg\\Database->executeQuery('INSERT into elg...', Object(Doctrine\\DBAL\\Connection), Array)\n#1 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Database/PrivateSettingsTable.php(381): Elgg\\Database->insertData('INSERT into elg...')\n#2 /xxxx/vendor/elgg/elgg/engine/lib/private_settings.php(99): Elgg\\Database\\PrivateSettingsTable->set(1, 'cron_latest:wee...', 1472761904)\n#3 /xxxx/vendor/elgg/elgg/engine/classes/ElggEntity.php(658): set_private_setting(1, 'cron_latest:wee...', 1472761904)\n#4 /xxxx/vendor/elgg/elgg/engine/lib/cron.php(160): ElggEntity->setPrivateSetting('cron_latest:wee...', 1472761904)\n#5 [internal function]: _elgg_cron_monitor('cron', 'weekly', 'Log rotated\\n', Array)\n#6 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(38): call_user_func_array('_elgg_cron_moni...', Array)\n#7 /xxxx/vendor/elgg/elgg/engine/lib/elgglib.php(802): Elgg\\PluginHooksService->trigger('cron', 'weekly', Array, '')\n#8 /xxxx/vendor/elgg/elgg/engine/lib/cron.php(133): elgg_trigger_plugin_hook('cron', 'weekly', Array, '')\n#9 [internal function]: _elgg_cron_page_handler(Array, 'cron')\n#10 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Router.php(95): call_user_func('_elgg_cron_page...', Array, 'cron')\n#11 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Application.php(429): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#12 /xxxx/vendor/elgg/elgg/engine/classes/Elgg/Application.php(377): Elgg\\Application->run()\n#13 /xxxx/index.php(8): Elgg\\Application::index()\n#14 {main}

There are some more fatal errors following immediatelly after but these are related to SELECT queries.

Could it be that the problem with the crashing table is caused by a duplicate triggering of the 'cron', 'all' plugin hook - or a too fast triggering? In /engine/lib/cron.php the function _elgg_cron_monitor() is registered for this plugin hook and within this function the running of the cronjobs is recorded to the private_settings table.

**Comment by mrclay** [comment]
No idea. But garbagecollector runs `OPTIMIZE TABLE` on every Elgg table on a schedule; probably not a good idea. It locks the whole table and requires a [bunch of extra disk space to complete](http://dev.mysql.com/doc/refman/5.7/en/optimize-table.html#c9940).

**Comment by iionly** [comment]
Fixed!!! Finally...

It wasn't an Elgg issue. There was a zero byte TMM file in the mysql folder for the private_settings table of my Elgg 2 test installation (therefore the problem "apparently" occured on Elgg 2 only). The bug report at https://jira.mariadb.org/browse/MDEV-8475 seems to describe the same problem I had. I could repair the table and everything seemed to work fine until the next run of OPTIMIZE TABLE of garbagecollector resulting in the table to crash due to the TMM file. I don't know what caused the file to be created in the first place as it was already from last year. Removal of the file seems to have fixed the problem, i.e. no more crashing of the table even on high frequency execution of the garbagecollector cronjob.
