### ISSUE TITLE
Admins should always get the "gear" icon

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9073]
i.e. pull it out of the developers plugin. Need to let plugins "unrequire" the module if they want.

**Comment by hypeJunction** [comment]
Strawman: Move `elgg_require_js()` call into an extension view, which plugins can overwrite.

**Comment by mrclay** [comment]
I have a PR for a simple "unrequire" #9075.

**Comment by beck24** [comment]
elgg_unrequire_js() is more fitting with existing API patterns

**Comment by hypeJunction** [comment]
Doh, I didn't realize there was a PR for unrequire

**Comment by jdalsem** [comment]
Disagree on having the gear always for admins... those tasks are not as daily as you might expect... only causes more js on the page for admins
