### ISSUE TITLE
Allow cancelling elgg_require_js()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9074]
As more core stuff is delivered via modules, cancelling seems a necessary API.

E.g. if we require the "gear" module for admins (#9073), plugins may want to do that only for certain users. Right now a plugin would have to do some gymnastics to do this.

**Comment by mrclay** [comment]
PR #9075

**Comment by juho-jaakkola** [comment]
Example use cases?

**Comment by mrclay** [comment]
@juho-jaakkola see the description
