### ISSUE TITLE
Match MD/annotation names case-sensitively

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9076]
Currently APIs like elgg_get_metadata() and elgg_get_entities_from_metadata() match names case-insensitively. If element `$e1->foo = 1` and `$e2->FOO = 'foo'`, a metadata search for 'FoO' will match both elements. While this may be useful in some rare cases:
- it's probably surprising to most devs
- it makes the API more complex (we can't just make a simple map of metastring IDs and use them instead of JOINs #5245)
- it likely makes MD queries slower

**Comment by beck24** [comment]
ooh, yeah that is surprising to me...

**Comment by hypeJunction** [comment]
this should be easily fixable with the qb

**Comment by jdalsem** [comment]
We will accept this behaviour (as a quirk). Fixing it will cause more troubles. We added a notice to the documentation that metadata names will be matched case insensitive.
