### ISSUE TITLE
Make mod symlinks relative

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9077]
I've installed Elgg in a vagrant VM but root paths cause issues with the mapped filesystem. E.g. If you run `composer install` from the host system, the symlinks point to host paths inaccessible on the VM, so all bundled plugins fail and are disabled. If you install on the VM, then an IDE on the host can't resolve the links back to the vendor directory.

**Comment by beck24** [comment]
I run into this all the time.  Workaround is to call composer install from within the vagrant box.

```
vagrant ssh
cd /vagrant/elgg/docroot
composer install
```

But having relative symlinks would certainly be nicer
