### ISSUE TITLE
What to do with profile fields if metadata access is ignored

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9083]
If metadata access_id is deprecated in Elgg 3.0 (See #9050), what shall we do with profile fields that currently rely on each field having it's own access id.

Approaches:
- Convert them into annotations
- Convert them into ElggObjects

**Comment by juho-jaakkola** [comment]
I wonder if we could separate the profile field values and access control completely.

The values could still be metadata, but we would have a separate (subtype specific?) field configuration that would know both who can read *and* who can write the fields.

Example: I have a site where I have overridden the profile editing stuff because some profile field values are fetched for an external system and cannot therefore be edited even by the profile owner. Currently all the logic is hard-coded into the views and the action hook.

If we had a configuration objects instead, it would be possible to define both read and write access more flexible way.

I'm not sure how difficult this would be to implement. Might even be a very bad idea. :)

**Comment by mrclay** [comment]
In my implementation PR (currently sitting on 2.0) I convert to annotations, which is a super easy transition, so that's where I lean.

But in general I don't think there's a strong use case for the annotations API anymore. Seems like objects linked with relationships would do fine.

**Comment by mrclay** [comment]
Here's the [port to annotations](https://github.com/Elgg/Elgg/pull/9052/files#diff-c1baef7f570cabd5b24dae13ee62b47f).

**Comment by jdalsem** [comment]
The profile field access is moved to annotations
