### ISSUE TITLE
Check that languages are pulled correctly when releasing 2.0.0-rc.1

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9084]
Writing this down, so we won't forget to do it:

Currently some translations get ignored by Transifex client without any apparent reason.

How to verify: check that Finnish translations file gets included in the discussions plugin when making the release PR. If it is missing, something is still wrong in the ```tx pull``` command used in the release script: https://github.com/Elgg/Elgg/blob/2.x/.scripts/release.php#L52

**Comment by mrclay** [comment]
> without any apparent reason

I recall the reason being a few missing translations, putting some languages under the 95% threshold.

**Comment by juho-jaakkola** [comment]
This problem has occurred also with translations that have 100% completion.

**Comment by iionly** [comment]
Could the problem be connected with the English files at Transifex being from the 2.X branch while trying to get the translations from Transifex for "older" branches?

**Comment by juho-jaakkola** [comment]
No, the Transifex configuration is branch specific at Elgg's end. There's no possibility to accidentally pull from the wrong translation project.

**Comment by juho-jaakkola** [comment]
(If I understood your question correctly.)

**Comment by iionly** [comment]
@juho-jaakkola it wasn't intended to be a question. I just wanted to point out that Transifex takes the English language files from the 2.X branch and then the translated files are pulled in when making a release from a different branch (2.0.X). On Transifex the project is the same (Elgg core 2) but on github the two branches might not necessarily contain the same en.php files (with commits not yet merged into 2.X or commits only made in 2.X). Maybe the script for making releases "forgets" to pull in some translations thinking nothing has changes. But it's just a "maybe" kind of suggestion and more likely the reason for some translations being forgotten is a different one (if it even still happens).

**Comment by juho-jaakkola** [comment]
Translations got pulled correctly in #9115 so closing.
