### ISSUE TITLE
Strawman: Fields config

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9088]
Over the last few months of working with forms, actions and entity exports, I am settling on using more declarative entity field configurations. Metadata is wonderful, and I love the flexibility of just going `$blog->some_random_metadata = 'some_random_value'`, but as the apps grow there is no oversight of what a serializable representation of an entity should look like. 

By declaring all the entity properties in one place, we can:
- render a form to create an entity or update it (in full or in part)
- create or update an entity by simply passing an array of key => value pairs
- serializing an entity into a JSON object
- declare and retrieve searchable values

Now that we can render from fields by passing an array of parameters, we can use hooks to generate type/subtype specific sets of fields. Now, if we could extend the parameters with a few more values, we could use the same config in an action. This is inspired in part by Drupal's implementation:

``` php
 $title = array(
    'input_type' => 'text',
    'output_type' => 'text',
    'name' => 'title',
    'search' => array(
        'type' => 'attribute',
    ),
    'required' => function(ElggEntity $entity) {
        return !$entity->guid;
    },
    'value' => array(
        'setter' => 'elgg_set_verbatim',
        'getter' => 'elgg_get_verbatim',
        'default' => function(ElggEntity $entity, array $params = null) {
            return elgg_trigger_plugin_hook('default_title', 'blog', ['entity' => $entity]);
        },
        'validator' => function($value = null, $rule = '', $expectation = null, array $params = array()) {
            $params['value'] = $value;
            $params['rule'] = $rule;
            $params['expectation'] = $expectation;
            return elgg_trigger_plugin_hook("validate:$rule", 'action', $params, true);
        },
        'sanitizer' => function(&$value = null, array $params = null) {
            $value = htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
        },
    ),
);
```

We could then do cool things like 

``` php
ElggBlog::update([
    'title' => 'Blog Title',
    'icon' => $_FILES['icon']['tmp_name']
]);

ElggBlog::getProperties('some_property_filter_callback');
ElggBlog::export('some_property_filter_callback');
```

**Comment by hypeJunction** [comment]
FYI, I am already using a similar approach for exporting graph objects, and will be using the same config to feed field info into the prototyper. 

Property class: https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/Apps/Handlers/PropertiesHook.php
Entity config: https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/Apps/Handlers/PropertiesHook.php
Group config: https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/Apps/Handlers/GroupPropertiesHook.php
Export worker: https://github.com/hypeJunction/hypeApps/blob/master/classes/hypeJunction/Data/Graph.php#L166

**Comment by mrclay** [comment]
I like it, and @ewinslow proposed something similar in spirit. The hard part is just pushing it through the core integration process. I'd definitely prefer a convention that's been worn down by real world scenarios.

**Comment by mrclay** [comment]
Could we first bring in declarations that solve the biggest problems and flesh more out later?

**Comment by hypeJunction** [comment]
At this point, I just want to know if that's the general direction we could
move towards. I think profile fields config would be a good place to start.
I will be eventually making a PR to allow passing field params instead of
just input names. That will allow select inputs etc. From there we can look
into using callback declarations in actions.

**Comment by hypeJunction** [comment]
Ref #10315

**Comment by jdalsem** [comment]
A fields config service has been introduced. https://github.com/Elgg/Elgg/pull/13478 We will build new features based on that service.
