### ISSUE TITLE
2.0: jQuery migrate is off by default

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9090]
Unless we want to add more docs explaining that stuff like `$().live()` is no longer supported, we need to add the migrate plugin after jQuery.

**Comment by hypeJunction** [comment]
Let's add the docs and force devs to rewrite their code, or they can add
migrate in their projects. It's been what 5 years now?

**Comment by beck24** [comment]
I agree with IK

**Comment by mrclay** [comment]
If we don't include it, we need concise instructions that add it in the right place, testing it with both AMD and views extending elgg.js.

I lean towards adding it because it costs us so little to do so and it's a lot easier for experienced devs to remove it than it is for non-technical site owners to recognize the problem.

**Comment by iionly** [comment]
jquery-migrate not longer being included is already mentioned in the upgrade guide (http://learn.elgg.org/en/2.0/guides/upgrading.html#dropped-jquery-migrate-and-upgraded-jquery-to-2-1-4). And there's also a link included to instructions on how to upgrade the code.

**Comment by mrclay** [comment]
Great. Then I'll just verify the instructions actually work. We've done several shuffles of the client side bootstrap since then.
