### ISSUE TITLE
Remove $CONFIG->siteemail in 3.0

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9096]
This causes a boot-time metadata fetch for a value that's almost never used.

**Comment by hypeJunction** [comment]
Can't we just append it to settings.php during upgrade and get rid of metadata call?

**Comment by mrclay** [comment]
> append it to settings.php

What do you mean by this? I'm suggesting we just let devs do `elgg_get_site_entity()->email` when it's needed.

**Comment by mrclay** [comment]
PR #9862

**Comment by mrclay** [comment]
Fixed by #9862
