### ISSUE TITLE
Allowing Duplicate Usernames to register ?

### ISSUE THREAD

**Issue by Jordan1987x** [Elgg/Elgg#9098]
Wondering why elgg 1.12.4 is allowing new members who register to successfully register and login into the site using an exact same username another member before him/her has already registered ?

**Comment by mrclay** [comment]
We prevent this [here](https://github.com/Elgg/Elgg/blob/1.12/engine/classes/Elgg/Database/UsersTable.php#L409). Are you sure this isn't caused by another plugin?

**Comment by Jordan1987x** [comment]
Im using godaddy as my host. Installed everything properly. Havent added any plugins, simply testing everything as it came when I downloaded elgg 1.12.4 - When i said username I actually meant display name. Is that something that can be changed so people are not on the website with duplicate display names ?

**Comment by beck24** [comment]
Display name is not considered unique.  People may want to use their real names, and real names aren't unique.
You can make it unique with a custom plugin of course.  I'm not aware of any that already exist for this purpose.

**Comment by Jordan1987x** [comment]
am i able to change it to where the display name feature is gone and the username is what is displayed on the website for each individual?

**Comment by mrclay** [comment]
Yes, in a plugin you could force the display name to always be `@<username>`. That's much easier than actually eliminating the field from everywhere. Please use http://learn.elgg.org/ and https://elgg.org/discussion/group/7 for plugin development support.
