### ISSUE TITLE
Is it possible to charge members for registration on elgg 1.12.4 ??

### ISSUE THREAD

**Issue by Jordan1987x** [Elgg/Elgg#9099]
I would like to set it up so there is a fee for members to join my elgg 1.12.4 site when registering. Is there a plugin for this or is anyone able to guide me to the proper keywords to search n order to research the issue? Any input or help I can receive on this matter would be greatly appreciated. Thank you for your time.

**Comment by beck24** [comment]
The best place for these kinds of questions is the elgg community

https://elgg.org/activity

**Comment by Jordan1987x** [comment]
appreciate that. Thank you.
