### ISSUE TITLE
250 character limit in /action/profile/edit makes little sense

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9104]
`action/profile/edit` does not allow values to be more than 250 characters long:

* URLs can be really long, and 250 doesn't cut it
* Tags should be exploded before char length is applied

**Comment by mrclay** [comment]
This is at least as old as 1.6 I think. Allow increasing by hook? What's a reasonable default?

**Comment by hypeJunction** [comment]
Why restrict? Why only on profile? Imho, should be a per-field contraint. If I were to use plaintext view for description, the action wouldn't let me save it if it were more than 250 chars, but if I were to use longtext it would pass it through without caring.

**Comment by mrclay** [comment]
All good points. I don't know that anyone will miss this.
