### ISSUE TITLE
element/forms/label requires label to output required indicator

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9108]
If required, shouldn't we still output the indicator regardless if label is empty?
If not, at least the docs should warn that a label is required for the required indicator to show up.

@hypeJunction

**Comment by hypeJunction** [comment]
Hm, not too keen on this.

**Comment by mrclay** [comment]
Think inputs with placeholders instead of labels. You still might want a required indicator.

**Comment by hypeJunction** [comment]
I am avoid placeholder-only inputs as much as I can, as they are bad UX. The moment the form is autocomplete by the browser, you have no clue what the value is supposed to be. If you are implementing such a thing, you have to at least add a title attribute somewhere.
Required field will have a `elgg-field-required` class, so you can use CSS pseudo selectors on `elgg-field-input` class to add an asterisk. Having a block label with just an asterisk above the field seems odd.

**Comment by mrclay** [comment]
Fair enough. Examples I see of placeholder-only forms require all fields (GitHub, Facebook, Twitter home page register forms) but use dynamic warnings.
