### ISSUE TITLE
Aalborg site menu does not work in mobile firefox

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#9110]

**Comment by iionly** [comment]
Which OS (Android, iOS or FFOS)? Version of Firefox? I can only test on FFOS and it works for me. On iOS it might be a browser issue as Firefox for iphones has just been released if I remember correctly.

**Comment by beck24** [comment]
Android - it's not working on a clients 1.12 installation and it's also not working on the community.  Leads me to think this is a change in FF as I'm pretty sure it was working in the past.

FF 42.0

**Comment by iionly** [comment]
I was able to reproduce - doesn't work even when using FF on an Android emulator (!)... The problem seems to be the collapsed mobile site menu. When requesting the desktop version of the site the menu items can be clicked without issues.

**Comment by iionly** [comment]
Could it be that FF on android has some issues with the "empty" span elements within mod/aalborg_theme/views/default/page/elements/navbar.php? If I add some text output like
'''
<span class="icon-bar">Text</span>
'''
the menu open/closes alright. But I have no idea how to get it working without adding some visible output unfortunately.

**Comment by iionly** [comment]
Maybe solution for 2.0 would be usage of fontawesome navicon (fa-bars). Can't test though (only have an 1.10 installation that I can use with the android emulator).

**Comment by topdog08** [comment]
What about &nbsp; it has gotten me out of a few jams before?

**Comment by topdog08** [comment]
<pre>&nbsp;</pre>

**Comment by topdog08** [comment]
https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by iionly** [comment]
I had already tries using non-breaking spaces but while this resulted in the menu toggle to work it also disturbed the output.

**Comment by beck24** [comment]
I fixed it on the client site by replacing the icon with an image instead of markup, but markup is ultimately the better solution if browsers can stop being dumb.

**Comment by iionly** [comment]
I don't see any other fix than using an image for Elgg 1.X either. For Elgg 2.X switching to a fontawesome icon should work (and there's even the fa-bars icon that would exactly fit).

**Comment by hypeJunction** [comment]
Would setting the css display to block or inline block on an icon fix the issue?

**Comment by iionly** [comment]
Neither inline nor inline-blocks works for me.

**Comment by mrclay** [comment]
Sounds like 1.12 needs an image, and 2.0 will use [fa-bars](http://fortawesome.github.io/Font-Awesome/icon/bars/).

**Comment by mrclay** [comment]
Change for 1.12: https://github.com/Elgg/Elgg/pull/9171

**Comment by mrclay** [comment]
I've started a [discussion](https://elgg.org/discussion/view/2404747/proposed-fix-for-aalborg-site-menu-toggle-in-firefoxandroid) around potential action on this.

**Comment by mrclay** [comment]
PR for 2.0: #9226. This is 1 of 2 final blockers for 2.0.
