### ISSUE TITLE
is_trusted flag is missing from members navigation tabs

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9117]
i am checking SEO for my site and found that the navigation tabs added by the core plugin 'members' are missing the 'is_trusted' => TRUE option. activating this option for internal links is recommended for good SEO.

**Comment by hypeJunction** [comment]
Any reason why we can't sniff the URL in `output/url` and only set `is_trusted` to `false` if the URL is in a different domain?

**Comment by propertunist** [comment]
that would be a good default for external links, yes

**Comment by hypeJunction** [comment]
This will be fixed with #9146
