### ISSUE TITLE
Make fileinfo extension a requirement

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9121]
Making `fileinfo` PHP extension a requirement for running Elgg would make life a lot easier for us.

**Comment by mrclay** [comment]
Is the general problem Windows?

**Comment by hypeJunction** [comment]
It feels that all the mimetype guessing is not something we should concern ourselves with.

**Comment by jdalsem** [comment]
This became obsolete with #9466 i believe
