### ISSUE TITLE
Elgg 2.0: input/autocomplete not working

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9123]
Tested on Elgg 2.0.0-rc.1.

input/autocomplete seems not to work. I've noticed it when testing tagging in Tidypics (match_on 'users'). No reaction at all. It also does not work in the Theme Sandbox (match_on 'groups', 'friends').

input/userpicker seems to work though. Could it be that some changes necessary for userpicker and autocomplete to work on 2.0 have only been made for the userpicker view?

**Comment by iionly** [comment]
Fix suggested by https://github.com/Elgg/Elgg/pull/9124.

**Comment by mrclay** [comment]
PR #9125

**Comment by mrclay** [comment]
Closed by #9125
