### ISSUE TITLE
Deprecate 'handler' logic in entity menu

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9126]
I am working on a different menu system, and one of the most painful things is that you can not display an entity menu in arbitrary place without knowing it's handler. Many enities rely on `handler` param to be set for `edit` and `delete` items to be registered. This is problematic if you are working on a generic solution that should work on any entity, as handlers are not predictable from entity type or subtype. Re-registering these items is also not possible because edit page location and delete action path are unpredictable.

**Comment by mrclay** [comment]
Basically lose _elgg_entity_menu_setup() and the "handler" $vars key for elgg_view_menu(). Seems like we could replace _elgg_entity_menu_setup() by a shortcut for setting up the same handlers.

**Comment by hypeJunction** [comment]
Yes, we need to get rid of all the magic. Given our routes are not set in stone, it's best that plugins explicitly define their edit and delete controller routes.
We should also discourage context sniffing in menu handlers, and advise that `context` parameter be used instead.

**Comment by hypeJunction** [comment]
My current workaround is adding a handler to entity menu hook with a high priority, match current page url against entity url, and if they match, add menu items to the title menu. Too hacky for my taste.
Also see #8818.

**Comment by hypeJunction** [comment]
One other way to look at it is edit and delete handler are 99% copy/paste. Perhaps we can just add standard handlers, so that everything resides under `/edit/$guid` and `/action/delete?guid=$guid`. Plugins can then use route hooks if they want custom logic.

**Comment by hypeJunction** [comment]
Ran into it again today. Need to get rid of it in 3.0

**Comment by hypeJunction** [comment]
This can go out of 3.0 milestone. My current vision is that we will replace it with magic route names.

**Comment by jdalsem** [comment]
And if we want to deprecate it, that can happen in a minor
