### ISSUE TITLE
sphinx-intl is causing tests to fail

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9127]
All of our tests are currently failing:

> sphinx-intl --locale-dir=docs/locale/ build
> Error: no such option: --locale-dir

https://travis-ci.org/Elgg/Elgg/jobs/91383497#L219

**Comment by juho-jaakkola** [comment]
At first I was wondering whether the option has been removed, and if we should define the dir in ```conf.py``` instead. But I haven't found any mention of it being removed. 

Perhaps there's just something wrong with the test environment that's causing ```sphinx-intl``` to not work correctly.

**Comment by juho-jaakkola** [comment]
I've now installed ```sphinx-intl``` locally using ```pip``` and managed to cause the same error. Now I just need to figure out how to fix it.

**Comment by juho-jaakkola** [comment]
Well, apparently upgrading to Sphinx 1.3.1 is one way to fix it.

**Comment by juho-jaakkola** [comment]
Ok, that did *not* fix it.

**Comment by juho-jaakkola** [comment]
(Also I should had made it for 1.10 branch. I didn't notice there was a PR until I had merged this.)

**Comment by juho-jaakkola** [comment]
I had missed the fact that I had locally used:
```
sphinx-intl build --locale-dir=docs/locale/
```
instead of
```
sphinx-intl --locale-dir=docs/locale/ build
```

**Comment by juho-jaakkola** [comment]
Tests are now working. The only problem is that I was hasty and merged the Travis fix to 1.12 branch and now the tests are failing when merging up a fix from 1.11 branch. But I guess there's nothing we can do about that.

**Comment by mrclay** [comment]
So we just need a commit fixing the earlier branch and merge it up carefully?

Good detective work. I never could duplicate the failure on my machine.

**Comment by juho-jaakkola** [comment]
We're providing security fixes to 1.10 until April 2016 and to 1.9 until January 2016 (http://learn.elgg.org/en/2.0/appendix/support.html). So yes, I guess the best course of action is to fix the transifex config all the way in 1.9 an then deal with the conflicts when merging up.

**Comment by juho-jaakkola** [comment]
Before Elgg 1.11 ```sphinx-intl``` was still installed with ```easy_install``` instead of ```pip```. So I'm guessing the tests for 1.10 are working fine.

**Comment by juho-jaakkola** [comment]
I was wrong. Tests aren't working in < 1.11 either.
