### ISSUE TITLE
Upload a file and Add a page invisible for default users in Groups

### ISSUE THREAD

**Issue by Grafcom** [Elgg/Elgg#9134]
Hello,

I'm new with Elgg.... thanks to all the documentation, I am well underway...

I only get something not done. I use the Roles 2.0.0 and Group Tools 5.0 plugin.

In Groups, however, I want the features <b>Upload a file</b> and <b>Add a page</b> invisible for default users.
I have a plugin customizations so I do not work in the core files.

Can someone tell me how and what I should add to get those features invisible?

**Comment by mrclay** [comment]
I see you've found the community. This is for issues with Elgg core.
