### ISSUE TITLE
Add ElggFile::getPathFromRoot()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9137]
We need a new method to quickly get a relative path from data root, otherwise we have to parse it from  `ElggFile::getFilenameOnFilestore()`

**Comment by juho-jaakkola** [comment]
Would ```EntityDirLocator``` class be of any help here?

**Comment by hypeJunction** [comment]
All the logic is already in `getFilenameOnFilestore()`, we just need to throw away the data root path

**Comment by mrclay** [comment]
:+1: for `getPathFromDataRoot()`.

**Comment by hypeJunction** [comment]
So, it looks like the filename on filestore path is returned by the filestore object, which means we need to either introduce a breaking change by adding a new method, or we use filename on filestore, and get rid of the dir_root using substrings.

I think ideally, we would add it to the filestore class, rewrite `getFilenameOnFilestore()` to only append dir_root to the path returned by `getPathFromDataRoot()`

**Comment by hypeJunction** [comment]
Just adding a simple solution for now that doesn't involve breaking changes.

**Comment by mrclay** [comment]
Let's just abandon this and keep the logic in the new file service API. We don't get a gain anyway.

**Comment by hypeJunction** [comment]
The question is do we want to proceed with FileService\File? The whole idea is based on the fact that files are stored on Elgg's dataroot...

**Comment by mrclay** [comment]
Strawman: if `$file->guid && $file->{'filestore::filestore'}` then add `/g{$file->guid}` to the URL. During the serve, we'd fully boot and serve using `getFilenameOnFilestore()` on the loaded entity.
