### ISSUE TITLE
Only set rel="nofollow" for external links

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9146]
Any reason why we don't trust internal links by default? I propose we only default `is_trusted` flag to `false` if the link is outside an Elgg installation. 

See https://github.com/Elgg/Elgg/issues/9117

**Comment by mrclay** [comment]
SGTM

**Comment by hypeJunction** [comment]
Can we treat this as a bug and fix in 1.12?

**Comment by mrclay** [comment]
IMO yes.

**Comment by mrclay** [comment]
Fixed by #9208
