### ISSUE TITLE
Keep track of registered toggleable menu items

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9151]
We need to avoid duplicate registration of toggleable menu items. Event handlers are bound multiple times if called from multiple locations, so have to do this madness: https://github.com/hypeJunction/Elgg-actions_feature/blob/master/views/default/feature.js

**Comment by mrclay** [comment]
> Event handlers are bound multiple times if called from multiple locations

Where does this happen?

**Comment by hypeJunction** [comment]
It's a potential collision with all toggleable menu items. If I were to implement a plugin that needs to toggle between feature and feature, I would be duplicating the event binding, unless I shut down the groups plugin js.

**Comment by jdalsem** [comment]
related to #8158

**Comment by hypeJunction** [comment]
Fixed by #9204
