### ISSUE TITLE
version 2.0 RC1 Composer install on Windows server 2012 R2 IIS 8 not working

### ISSUE THREAD

**Issue by MBlondin** [Elgg/Elgg#9154]
on a Windows server 2012 R2 IIS 8 when trying to run the composer to install Elgg 2.0-RC1 I get the following:

C:\inetpub\wwwroot\elgg2>php composer.phar global require fxp/composer-asset-plu
gin
Changed current directory to C:/Users/ToolsTeam/AppData/Roaming/Composer
A script named lint would override a native Composer function and has been skipp
ed
A script named test would override a native Composer function and has been skipp
ed
A script named travis:install would override a native Composer function and has
been skipped
A script named travis:install-with-mysql would override a native Composer functi
on and has been skipped
Using version ^1.1 for fxp/composer-asset-plugin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/jquery could not be found in any version
, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/jquery-ui could not be found in any vers
ion, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/text could not be found in any version,
there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/requirejs could not be found in any vers
ion, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/jquery-form could not be found in any ve
rsion, there may be a typo in the package name.
  Problem 6
    - The requested package bower-asset/jquery-colorbox could not be found in an
y version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mrclay** [comment]
Did you `git checkout 2.0.0-rc.1` to get the RC? I'd recommend checking out the `2.0` branch instead.

**Comment by mrclay** [comment]
Have you tried install using the [zip file](https://elgg.org/getelgg.php?forward=elgg-2.0.0-rc.1.zip) (which does not require composer)?

**Comment by MBlondin** [comment]
superbe, @mrclay that worked.  Thank you.  Quick on, what is the expedted release of elgg 2.0?

**Comment by mrclay** [comment]
If no more big bugs founds, a couple weeks.
