### ISSUE TITLE
Replace mod/file icons

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9157]
Surely someone does this already.

**Comment by hypeJunction** [comment]
We really need to make a clear distinction between file type icons and
image thumbnails.

**Comment by hypeJunction** [comment]
And we need to normalize file thumbs to same sizes used elsewhere

**Comment by mrclay** [comment]
One easy-ish switch: http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/ and friends.

**Comment by hypeJunction** [comment]
I would vote for getting rid of icons and replacing them with owner icon
and adding simpletype to subtitle.

**Comment by jdalsem** [comment]
maybe we can use the fontawesome svg images as a replacement

**Comment by jdalsem** [comment]
file type icon images have been removed. Listings now show the owner icon.
