### ISSUE TITLE
Theme sandbox grid is deceptive

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9158]
theme sandbox is cheating when displaying a grid by adding custom margins.

**Comment by mrclay** [comment]
The grid CSS works, it just doesn't include gutters between columns. You must nest wrappers inside for padding. How can we make that clearer?

Instead of borders we could display columns with various background colors so you can they all but up against one another.

**Comment by hypeJunction** [comment]
I really don't think Elgg grid is usable. In needs a clearfix wrapper around each row, and nested elements for padding, and it is based on a 5 and 6 columns grids, which are far from being standard. 
I am switching to my own grid system: https://github.com/hypeJunction/Elgg-ui_grid

**Comment by hypeJunction** [comment]
I don't think there is anything actionable here.
