### ISSUE TITLE
Use jQuery custom events?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9162]
I'd like core Elgg JS to fire more events. In cases where the caller isn't receiving data from listeners (and particularly in response to a DOM interaction), it might be better to use jQuery custom events.

Cons: adds 2nd event convention in use; increases $ dependency

Pros: $ events much more widely known; element-centric; bubbling; we not going to escape $ anytime soon.

**Comment by jdalsem** [comment]
not going to do this. It is not wise to add more relationships with jQuery as this js framework is probably going to be removed from Elgg at a certain point
