### ISSUE TITLE
duplicate tags should not be accepted in tag input fields

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9177]
presently it is possible to repeat the same tags numerous times in tag input fields. this results in a problem when we come to use those tags in useful ways, such as the way that the 'related items' plugin uses the tags to search for related items. ideally i would like to see input validation that prevents duplicate tags and also an upgrade process to clear up duplicate tags that may exist for pre-existing entities.

**Comment by mrclay** [comment]
:+1:

**Comment by jdalsem** [comment]
Fixed in #9607
