### ISSUE TITLE
register_elgg_event_handler('create','user', 'set_def_lang'); crash elgg

### ISSUE THREAD

**Issue by hellas1** [Elgg/Elgg#9178]
Elgg 2.0.0-rc.2

When calling 

register_elgg_event_handler('create','user', 'set_def_lang');

Elgg crash with "Server error 500"

Best regards

Henrik Larsen Denmark

**Comment by hypeJunction** [comment]
Check the API. register_elgg_* no longer exist. Use elgg_register_*

**Comment by hellas1** [comment]
Thanks :o)

2015-12-01 21:57 GMT+01:00 Ismayil Khayredinov <notifications@github.com>:
