### ISSUE TITLE
Race condition on add_entity_relationship

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#9179]
I'm occasionally getting this on one of our larger projects:

    Duplicate entry '2276949-friend-2544817' for key 'guid_one'
    
    QUERY: INSERT INTO elgg_entity_relationships
    (guid_one, relationship, guid_two, time_created)
    VALUES (2276949, 'friend', 2544817, 1448870065)

The only way I can see this occurring is by race condition whereby two threads call add_entity_relationship at the same time.  They both pass the check_entity_relationship test and attempt to insert at the same time.

Potential fix:

    INSERT INTO elgg_entity_relationships
    (guid_one, relationship, guid_two, time_created)
    VALUES (2276949, 'friend', 2544817, 1448870065)
    ON DUPLICATE KEY UPDATE time_created = 1448870065

?

**Comment by mrclay** [comment]
The fix seems OK, of course once this is fixed you'll hit other problems ;) Solution: set up the webserver so only 1 request can get handled at a time. [dusts hands] my job here is done.

**Comment by beck24** [comment]
haha, most likely :)

**Comment by topdog08** [comment]
I have also seen this for elgg_users_entity when I got a spike in new users.  Would same fix work there?

Duplicate entry '' for key 'username'

 QUERY: INSERT into elgg_users_entity
                        (guid, name, username, password, salt, password_hash, email, language)
                        values (2595019,

**Comment by beck24** [comment]
No, the same fix could not work for that
