### ISSUE TITLE
$owner_changed_flag in groups/edit action

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9184]
There is still reference to `$owner_changed_flag` in `groups/edit` action, but I don't see it set anywhere. Variable mismatch? Leftover code?

**Comment by juho-jaakkola** [comment]
That sounds bad. It should still be used when changing group ownership.

**Comment by juho-jaakkola** [comment]
We should just fix #4683 in Elgg 3.0 and get rid of all that extra stuff in the save action.

**Comment by hypeJunction** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/9672
