### ISSUE TITLE
IDEA: store initial entity state as volatile data

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9187]
`'update'` events need to know if entity attributes have been modified to do something useful, e.g. move icons to a different location, if the owner has changed. One way to achieve this is to store all attributes as volatile data when entity has been loaded, and replace them once entity has been saved and all event handlers have been processed.

**Comment by mrclay** [comment]
Yeah, I've been thinking this for awhile (see #5604). #9033 might be easier, but would hand over responsibility to plugins to detect changes between two events. Also is a case for event $params.

**Comment by mrclay** [comment]
Actually this will probably be necessary in any scenario where we allow plugins to detect change.

**Comment by hypeJunction** [comment]
In one of my projects I recently implemented a `getFootprint` method, which returns all object vars. I then serialize that data and create an `updated` annotation, so there is a history of all changes made to the object (annotation timestamp and owner represent time of change and person making the change). Obviously, I don't care about metadata access/owners, just a set of key value pairs. Perhaps we could implement something similar, and put all object vars to volatile data on load/save.

**Comment by mrclay** [comment]
So your case needs to consider metadata as just part of the attributes. It would be great if Elgg's API had worked identically between attributes/metadata, but here we are.

**Comment by mrclay** [comment]
I'm thinking: In __set(), if there's a GUID, then we copy the attribute into $entity->original_attributes (private). Basically we don't have to populate this for every loaded entity. Duplicate strings don't add much memory, but it's not free.

**Comment by mrclay** [comment]
...if the key is an attribute. I'm not sure we can do this for the metadata.

**Comment by hypeJunction** [comment]
Nah, let's keep it simple. Metadata changes already get more attention than they deserve in event handling.

**Comment by hypeJunction** [comment]
Do we then trigger an event once `save()` succeeded to notify plugins that attributes have changed? Before the `update` event has fired? Or would plugins listen to `update` event and use some new method to retrieve `original_attributes`?

**Comment by mrclay** [comment]
I think ideally there would be a cancellable update:before event optionally followed by update:after if not cancelled, and both would receive an array of changes in params.

**Comment by mrclay** [comment]
But for BC, simply exposing an API to get the original attributes might be the simplest solution.

**Comment by mrclay** [comment]
Starter implementation #9188
