### ISSUE TITLE
Get rid of imgAreaSelect

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9189]
In 3.x, I would like us to get rid of imgAreaSelect in favor of https://github.com/fengyuanchen/cropper

Here is the API we can plug into core: https://github.com/hypeJunction/Elgg-cropper. We can add `input/avatar` and clean up avatar upload page that tends to break on modern themes that use box-sizing and other modern properties.

**Comment by beck24** [comment]
+1
Though I would prefer to have the 2-step upload then crop process instead of rendering the cropper with the javascript loaded local file as it messes up with rotated images from mobile devices.  Let the upload process handle rotation issues if it wants then crop the result.

**Comment by hypeJunction** [comment]
The JS lib actually supports rotating, so we could either allow users to rotate client-side, or go back to two step process.

**Comment by beck24** [comment]
ok that's good, would make for better UX, but we'd have to make sure if it's rotated client side for the cropper that it's also rotated when the file is saved.  The problem I was having on MFP was the cropper would render the sideways local image then image_orientation plugin would fix the orientation, then the cropping was wrong.
Need rotation on both sides or none at all :)

**Comment by mrclay** [comment]
FYI, some other avatar UX ideas to keep in mind: #8730, #9053

**Comment by hypeJunction** [comment]
Re: #9053. I agree. I no longer think that keeping multiple media in
entity's folder is a good idea. We should upgrade avatars, covers etc to
subclasses of ElggFile. I will be working on these soon.
