### ISSUE TITLE
Changing dataroot breaks file operations for saved ElggFile objects

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9191]
We store filestore metadata, including dir_root, for every persisted ElggFile. When a dev migrates a site there's nothing that updates this metadata, so downloads of these files all break. The thumbs work because those ElggFiles aren't persisted.

Easiest solution is to not store MD for the default filestore and delete it on upgrade if it is pointing to the dataroot. Well, technically easiest is to just ignore the filestore metadata!

**Comment by mrclay** [comment]
If we truly support non-default filestores, we have no good other choice than to release a separate fix tool.

**Comment by juho-jaakkola** [comment]
I vote for dropping the support completely.

**Comment by beck24** [comment]
I have never used a non-default filestore, what's the use case?  Any idea how prevalent (or not) that is?

**Comment by mrclay** [comment]
Use case is storing files in different path, or something like S3. No idea if anyone's using it and [no one's responded](https://elgg.org/discussion/view/2402711/custom-filestore).

**Comment by mrclay** [comment]
Filestore isn't a bad design and doesn't cost much to keep, it was just not so great to always store a path reference by default.

Strawman:

1. We add a warning in the site migration docs about this. Site owners can ideally make a symlink from the old dataroot location to the new.
1. In 1.12 we add an admin tool to migrate old `$file->{'filestore::dir_root'}` paths to the new dataroot. This would be pretty simple.
1. We warn plugin devs that in 3.0 `$file->{'filestore::filestore'}` and `$file->{'filestore::dir_root'}` will no longer be populated for *every* stored ElggFile objects (only custom filestores).
1. In the 3.0 upgrade we delete all filestore metadata that references the default filestore.Plugins are free to use custom filestores, but they support what data gets stored.

**Comment by mrclay** [comment]
PR 1: #9193

**Comment by mrclay** [comment]
In 3.0 files can't have custom filestores. Well, technically you could extend ElggFile and override getFilestore(), but you can't use the serve-file API with them.

We could write a migration to delete all the default filestore metadata, but meh.
