### ISSUE TITLE
Extendable 'edit' layouts

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9192]
'Edit' layouts, with groups being the most annoying of them, are hard to work with. Multiple plugins keep trying to extend, override, hook into, which turns the page into a total nightmare to work with.

I propose the following:

- Create a new menu called `filter:edit` or something similar that is populated in `filters/groups/edit` view
- Register the `index` menu item (could be labeled 'Basic info' or whatever) and `index` resource view.
- Have `resources/groups/edit` check the `tab` query element/view variable, and dispatch to `elgg_view_resource('groups/edit/$tab')`

That way plugins can use the `'register', 'menu:filter:edit'` hook to add a new item pointing to `/groups/edit?tab=$new_tab` or `/groups/edit/$new_tab`, and just place a new view in `resources/groups/edit/$new_tab`.

This could apply to edit profile, or any other entity. Instead of registering new page handlers, and routes, we could just have `/profile/edit/index`, `profile/edit/avatar`, `profile/edit/widgets` etc.

The filter menu view, could be tought to not display a menu if there is only one time.

**Comment by mrclay** [comment]
cc @jdalsem @jeabakker. What other developers extend/add tabs to edit forms that we could bring to this discussion?

**Comment by jeabakker** [comment]
I like the idea, but I extend the group form a lot. How can i register all those extensions under 1 tab? Because registering 10-15 extra tabs won't help the user! ;)

In group_tools i have some JS to grab 'all' extensions and hide them under one tab

**Comment by hypeJunction** [comment]
This is what I did to accommodate ColdTrick's extensions: https://github.com/hypeJunction/Elgg-prototyper_group/blob/master/views/default/resources/groups/edit/settings.php

I have edit/profile and edit/settings as tabs, the former just displays the form, the latter uses `groups/edit` view, which you extend so much ;)

**Comment by hypeJunction** [comment]
Fixed by #10333
