### ISSUE TITLE
Include all files in tests to catch typos

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9212]
E.g. views aren't currently being tested nor even included in the tests, so it is easy to accidentally include a typo or a syntax error.

Simply including all files once in the tests would be enough to catch obvious mistakes.

**Comment by hypeJunction** [comment]
:+1:

**Comment by mrclay** [comment]
As a practical matter we should probably commit to manually testing patches to *stable* releases before we give it a thumbs up.

We already cover engine/lib/*. :+1: for including all classes and `php -l` on all PHP files.

Executing views with trivial/empty `$vars` array would not give me much confidence and give some false confidence. E.g. In output/url missing `$vars['href']` would quietly bypass a big branch of code. Just rendering a bunch of views in a Simpletest would be a good start, but see also #6987.

Actions and `start.php` files are harder nuts to crack. #8397 would convert forward() to an exception, might help, or break stuff :(

**Comment by mrclay** [comment]
Related #9234.

**Comment by hypeJunction** [comment]
We can't simply include all files because e.g. in case of actions there is executable code which may do bad things. I am working on a workaround.

**Comment by jdalsem** [comment]
views (#11326) and actions (#11309 ) are now testable
