### ISSUE TITLE
XFN vs performance

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9218]
`user/default` view needlessly checks the relationship with the current user in order to establish simple XFN. I am not sure who even uses XFN, and it makes little sense given XFN parsers are mostly likely crawling the site as non-logged in users. Additionally, I am not sure how useful XFN information is if it's only present in one link...

**Comment by mrclay** [comment]
:+1: I don't see how it's aiding UX. A plugin can use "view_vars" hook to pre-render the "title" key.

**Comment by hypeJunction** [comment]
master or 2.x. I would call it a performance hog/bug

**Comment by mrclay** [comment]
master. In the short term you can also use view_vars to prerender title without it.
