### ISSUE TITLE
Flood of "mkdir(): File exists" warnings on SimpleCache reset

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9219]
Warnings refer to invalidate() function: https://github.com/Elgg/Elgg/blob/2.0/engine/classes/Elgg/Cache/SimpleCache.php#L177.

I see a `mkdir()` in this line followed by a `_elgg_rmdir()` in the next line. Could it be that it should be the other way round, i.e. first removal and then re-creation?

**Comment by juho-jaakkola** [comment]
The second call does not remove the directory itself, but just its contents. So I believe the call to `mkdir()` can be removed completely.
