### ISSUE TITLE
Feature: Code for automatic "Resend validation" and "Delete" for unvalidated users in Elgg

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#9227]
A feature to send validation mail to all the user who have registered in the past x days and have not validated their email ID yet and also Delete all the unvalidated users who have not validated their email IDs for more than x days.

You can refer this code: https://github.com/rohit1290/Elgg-Unvalidated-Users/blob/master/unvalidated_user.php

**Comment by hypeJunction** [comment]
There is already an action to resend validation, we just need to implement bulk action UI.

**Comment by rohit1290** [comment]
I know there is an action to resend validation. I am asking for automated process for the same. The source code that I have shared can be used via a cron job for the same. In this way the user don't have to worry about re-sending validation mail everyday or deleting the user whos ID are not activated over a certain period of time.

**Comment by hypeJunction** [comment]
I don't think that's good UX neither for admin nor for the end user.

**Comment by juho-jaakkola** [comment]
Automated process is not good for Elgg core. We cannot expect that all sites want to send the emails by default.

It is however trivial to create a plugin that takes care of the automation, so I'm closing the issue.
