### ISSUE TITLE
Check 2.0.0 zip for mangled bower-asset dir

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9233]
For some reason the composer asset plugin places the bower dependencies in `/vendor/bower-asset/bower-asset`, maybe only when installing Elgg as a dependency?

https://elgg.org/discussion/view/2414551/elgg-200-bower-assetbower-asset

**Comment by mrclay** [comment]
Yep, it created `/vendor/bower-asset/bower-asset` :(

**Comment by mrclay** [comment]
I can't reproduce this locally using elgg-starter-project.

**Comment by juho-jaakkola** [comment]
> By default, the plugin will install all the assets in the directory `vendors/{asset-type}-asset` and packages will be installed in each folder with their asset name.

We updated the version some time ago, but according to the docs it should work like before.

**Comment by juho-jaakkola** [comment]
The `elgg-starter-project.sh` also made a valid package locally. There must be something funny on the elgg.org server.

**Comment by juho-jaakkola** [comment]
The composer-asset plugin at elgg.org is at the same version that I have locally:

```
$ composer global show -i
$ fxp/composer-asset-plugin v1.1.1 NPM/Bower Dependency Manager for Composer
```

**Comment by juho-jaakkola** [comment]
I found out that global composer dependencies are in fact user specific. For the `deploy` user the `composer-asset` plugin was still using the old version:

```
fxp/composer-asset-plugin v1.0.3 NPM/Bower Dependency Manager for Composer
```

I updated it, and now the package contents are as they should be:

> /vendor/bower-asset/{package}

This was surprising. The word "global" makes you think it would be the same regardless of which user is running composer.
