### ISSUE TITLE
More reliable build packaging

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9234]
How can we ensure something like #9233 doesn't happen again? Ideally we'd run many of the same checks we run on Travis.

Seems like an explicit check for essential Bower asset files is warranted. It's failed us on Travis due to GitHub API limitations and now due to an old composer-asset-plugin version.

**Comment by jdalsem** [comment]
Can't remember the last time we ran into this issue. We will be moving to GitHub actions in the future for our packaging.
