### ISSUE TITLE
Unifying icon display

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9235]
I am going to start a new issue since #8202 got closed when 1.x branch was deleted.

My latest thoughts on icons: get rid of icons and the concept as such! Images have thumbnails. Other entities may have some sort of icon implementation (e.g. file type icons in file plugin).

* Introduce `ElggImage` class that extends `ElggFile`
* Do cropping on `ElggImage::save()` based on global size config, thumbnails owned by `ElggImage` (to avoid having to move everything if image owner changes). No more spaghetti for cropping in actions.
*  Add `ElggAvatar` that extends `ElggImage` with subtype `avatar`.
* Add API to set/remove entity avatar.
* Add generic pages for editing/cropping avatar entities.

```php
function elgg_get_avatar($entity) {
    // ege* for 'object','avatar' with 'owner_guid' => $entity->guid
}

function elgg_set_avatar_from_upload($input, $entity) {
    $avatar = elgg_get_avatar($entity);
    if (!$avatar) {
       $avatar = new ElggAvatar();
       $avatar->owner_guid = $entity->guid;
       // filename should be set magically in the constructor
    }
    
    $avatar->open('write');
    $avatar->write(file_get_contents($_FILES[$input]['tmp_name']));
    $avatar->close();

    $avatar->save(); // this will generate all the thumbs

    return $avatar;
}
```

We may want to add `'preload_avatars'` option to ege* to reduce queries.

**Comment by mrclay** [comment]
Making avatars entities would help #9053. It introduces some complexity due to access control, but not a dealbreaker.

**Comment by hypeJunction** [comment]
https://github.com/hypeJunction/Elgg-images
https://github.com/hypeJunction/Elgg-avatars
https://github.com/hypeJunction/Elgg-avatars_user
https://github.com/hypeJunction/Elgg-ui_icons

**Comment by hypeJunction** [comment]
https://github.com/hypeJunction/Elgg-file_thumbs
A bit hacky, but works for now.

https://github.com/hypeJunction/Elgg-file_thumbs/blob/master/start.php#L51 A reason to move thumb creation from the action file into an event handler.

**Comment by hypeJunction** [comment]
So, after some more thinking and in-field application:

*Images* plugin now only includes API for working with images:
 * `images()->createFromUpload()` - create image file from upload
 * `images()->createFromResource()` - create image file from a file resource
 * `images()->crop()` - crop source image
 * `images()->isImage()` - check if an entity is an image
 * `images()->createThumbs()` - creates thumbnails for an image
 * `images()->getThumb()` - returns a thumbnail file object
 * `images()->clearThumbs()` - removes all image thumbnails

Files created with this API will only have thumbnails with site-wide dimensions. Old behavior can be achieved with hooks. I am quite done with strange file thumb dimensions, so I am going to pretend they don't exist.

*Images UI* plugin contains page handlers and entity views. 

*Avatars* plugin provides API for setting and removing entity avatars.

*User Avatars* plugin replaces core user avatar handling. The changes are compatible with core implementation, so if plugin is disabled, user avatars will still be visible.

*Icons* plugin replaces default icons with SVGs, adds the `corners` option to the icon view, and wrap all icons in the same markup for cross-browser compatible display (e.g. Safari has issues with round images).

**Comment by hypeJunction** [comment]
Thumbnails are generated for all instances of `ElggFile` that are jpeg, gif and png during `create` and `update:after' events, so plugins no longer have to worry about generating thumbs. 

I am planning to implement a plugin for cover images and video files (conversion to HTML formats, thumbs from video screenshot).

**Comment by hypeJunction** [comment]
See #9636 and #9636. I need some more attention from @Elgg/contributors to get these in before 2.2. Otherwise, I will abandon this mammoth undertaking.

**Comment by hypeJunction** [comment]
Dupe #6152
