### ISSUE TITLE
Elgg\I18n\Translator->getInstalledTranslations() causes lots of notices

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9236]
Al lot of notices like
> NOTICE: Missing el translation for "el" language key

reason: https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/I18n/Translator.php#L409

it should first check if the language key exists before calling it

**Comment by jdalsem** [comment]
Duplicate of #8561 and fixed in #9666
