### ISSUE TITLE
2.0 undocumented migrate action when extending js/admin

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9238]
It is still possible to extend js/elgg, but this does not apply to js/admin anymore. Was this intended? If so, we need it documented somewhere. This is probably intended to get plugin devs to use AMD, but extending js/admin is very common, so explicit documentation about this change is appreciated.

**Comment by mrclay** [comment]
I think this late we should just allow extending js/admin to work. I.e. make an empty view and include it on every admin page. Somehow deprecate it.

**Comment by mrclay** [comment]
It's in the Changelog but not the upgrading plugins guide.

**Comment by mrclay** [comment]
See #9241.
