### ISSUE TITLE
registerTogglableMenuItems doesn't work on user profile

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9239]
If you've registered toggleable menu items in the user_hover menu (specificly the admin section) those don't work on the profile page, but they do in the dropdown.

reason, https://github.com/Elgg/Elgg/blob/2.x/mod/profile/views/default/profile/owner_block.php#L51
it doesn't have the class `elgg-menu`

**Comment by mrclay** [comment]
Sounds good. Wanna send a PR for 2.0 branch?

**Comment by hypeJunction** [comment]
Would make sense to merge #9204 beforehand to avoid conflicts.

**Comment by mrclay** [comment]
Is this still an issue?

**Comment by jeabakker** [comment]
yes, there's no `.elgg-menu` wrapper so the toggleItem doesn't know where to toggle
