### ISSUE TITLE
js requiresConfirmation should also stop event propagation

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9240]
otherwise `.on` registrations of other events on the same element will not be blocked

**Comment by hypeJunction** [comment]
To prevent other handlers from running, you would use `event.stopImmediatePropagation()`. That is same as `return false;`. Not sure using either is healthy in a pluggable framework.
Bubbling might be important to some other scripts that capture DOM events, e.g. capturing clicks withing a certain element for analytics.
I would say we should advise plugin devs to check if `event.isDefaultPrevented()` before handling events on elements with `data-confirm`

**Comment by jdalsem** [comment]
Agreed. Did not think about `event.isDefaultPrevented()`.

**Comment by hypeJunction** [comment]
I think we should just `return false;`
