### ISSUE TITLE
$_SESSION not available in shutdown:system event

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9243]
The session is closed before this event is called, this can cause problems for events which rely on $_SESSION vars.

I thinks it's cause by https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L103, which registers a shutdown function to close the session. Since it's probably one of the first shutdown functions being registered it's called first.

This problem was introduced in Elgg 1.10 with the switch to Symfony Session managment

**Comment by mrclay** [comment]
PR for 1.12: #9248
