### ISSUE TITLE
File upload action - issues with replacing files

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9267]
File upload action preserves the filename of the original file, when the file is being replaced. This has implications if the new file is of different type, as it may lead to wrong mimetype/simpletype detection, if for some reason browser fails to detect mime correctly, or a plugin is trying to detect mimetype, rather than relying on the metadata value.

Not sure what the correct approach to fixing is. Probably restricting replacements of files of the same type would be the least evil solution. I am not sure if replacing the name will affect anything.

**Comment by mrclay** [comment]
PR #9615
