### ISSUE TITLE
Make cron available as a server-side script

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9270]
Was just setting up cron and it's a pain in the butt. First you need to figure what scripts are available on the server, then configure them etc. Then if you change the URL you need to update the crontab.

IMO, it would be great to include it as a server side script that can be run by PHP. We would just boot the application and route to the cron page handler, or just trigger the hook. And finding php on your server is much easier then choosing between lrw, get, curl etc.

**Comment by jdalsem** [comment]
Continued in #10027 with a more generic approach on CLI tools
