### ISSUE TITLE
Pagination with AJAX requests

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9272]
For whatever reason, `navigation/pagination` assumes that `base_url` is referrer URL with XHR requests. That only makes sense in 'ajax' context, IMO.

**Comment by mrclay** [comment]
What logic do you suggest?

Also I've not checked if the elgg/Ajax module pushes the "ajax" context. I'm not sure it should.

**Comment by hypeJunction** [comment]
I don't think it should.

If `base_url` is set, use it.
If not, default to referrer url, if in `ajax`
Else use the current page url

**Comment by mrclay** [comment]
FYI this context is set in `page_owner_boot()`, so the new elgg/Ajax should also set "ajax" context for views/forms, but not actions/paths.

Considering there would be BC implications, what's the use case for defaulting to `current_page_url()` on an ajax request? Something like pjax? Can you not send `base_url` with the request?

**Comment by hypeJunction** [comment]
I have a tabbed layout with tab content being loaded by AJAX via full page URL. If I don't use browser history states, the original page URL becomes the referrer so the pagination points to the wrong page.
Let's say I am on `/groups/all?filter=newest` and I load `/groups/all?filter=alpha` into tab content area: the pagination of the alpha list points to newest rather than alpha.

**Comment by mrclay** [comment]
OK, yeah this behavior is unfortunate in context of a pjax-like solution. How are you working around this currently?

**Comment by hypeJunction** [comment]
Adding `'base_url' => current_page_url()` to list options
