### ISSUE TITLE
2.0: Make sure files like foo.min.js are not minified again

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9276]
We have the check at https://github.com/Elgg/Elgg/blob/2.x/engine/lib/views.php#L1489, but if it only checks the view name it will miss checking the underlying filename.

**Comment by jdalsem** [comment]
@mrclay do you know if this still is an issue? Do you have a PR for it if so?

**Comment by mrclay** [comment]
JS view names are almost always include the filename now.
