### ISSUE TITLE
README in distribution zip is outdated

### ISSUE THREAD

**Issue by amustafa** [Elgg/Elgg#9284]
When you download the distribution zip of 2.0.1 @ https://elgg.org/download.php, the README at the top level says: 

    This is an experimental quickstart skeleton for building a site based on Elgg 2.0.

    **Do not use this in production!** A stable release of 2.0 is not yet available; this will install the latest 
    version on the `2.0` branch, containing very recent fixes. When 2.0 is released, this will point to the 
    latest stable version.

**Comment by mrclay** [comment]
Fix in https://github.com/Elgg/starter-project/issues/31
