### ISSUE TITLE
Discussion: Denormalize metastrings, remove or merge annotations

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#9289]
Update 2016-09-23:
As per discussion during the hackathon, we've decided to:
- [ ] Leave annotations and metadata tables separate (and identical)
- [ ] md.access_id is preserved, but ignored in the API
- [ ] Denormalize name and value fields
- [ ] Remove egefmd() and move the metadata logic into ege()
- [ ] Remove all metastring functions.

Original discussion below:

The normalization for metadata and annotations names / values has caused more headaches than offered benefits. I think Elgg 3.0 would be a good time to take steps to denormalize this table. Immediate benefits are:
- Significantly fewer joins on metadata queries.
- Simpler execution paths and cleaner code for internal methods.
- Easier custom SQL (though, less of a benefit if we properly abstract the DB API).
- Easier query and database debugging.

Along the same lines, annotations and metadata are literally identical behind the scenes. I don't think there's an argument to have separate tables--a flag on the entry would suffice. At the extreme, since the distinction is only philosophical we could remove annotations completely and allow metadata to have all of the additional methods of annotations.

I have an initial once-over against master that I can push if we want to go this direction.
### Before denormalization (two tables):

| id | string |
| --- | --- |
| 1 | foo |
| 2 | bar |
| 3 | baz |

| id | entity_guid | name_id | value_id | value_type | owner_guid | access_id | time_created | enabled |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 12 | 1 | 2 | text | 12 | 2 | 1448478970 | yes |
| 2 | 23 | 1 | 3 | text | 23 | 2 | 1448478981 | yes |
### After denormalization (only one table):

| id | entity_guid | name | value | type | owner_guid | access_id | time_created | enabled |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 12 | foo | bar | text | 12 | 2 | 1448478970 | yes |
| 2 | 23 | foo | baz | text | 23 | 2 | 1448478981 | yes |

**Comment by juho-jaakkola** [comment]
I added a concrete example of the tables in the issue description. Is this what you have in mind?

**Comment by juho-jaakkola** [comment]
Also making a note of a different approach suggested for the metadata table: #9050

**Comment by juho-jaakkola** [comment]
Merging annotations and metadata would cause problems if the same `name_id` is used in both tables.

**Comment by brettp** [comment]
Thanks for making the example clearer with the tables.

Re access_id changes: I agree with @mrclay that we can kill access on metadata, but I think those issues are separate, though they could possibly be addressed at the same time.

Re id collisions: Yes, it would cause issues if there are collisions, but I think it's unlikely there would be because metadata and annotations have been used differently. A quick check against our largest installation shows 0 collisions between 1334844 rows of metadata and 486496 rows of annotations.

We could prepend 'annotation_' to any rows that might collide to ease the transition for devs.

**Comment by juho-jaakkola** [comment]
I was thinking it as two different approaches:
 1. have `metadata` without `access_id` and a separate `annotations` table
 2. merge `metadata` and `annotations` table but leave the `access_id`intact

But apparently you are suggesting that we both merge them and remove `access_id`.

**Comment by juho-jaakkola** [comment]
...*and* denormalize while we're at it. :)

**Comment by brettp** [comment]
Denormalizing is my primary concern...I probably should have made two tickets. I might be missing something, but I still don't see these two issues as being an either / or situation. Access controls and the schema changes can be removed before or after -- it wouldn't affect the decision to normalize.

**Comment by mrclay** [comment]
Should we roll these changes into #7875 and make some bigger changes? because I think a schema change isn't worth the pain to ourselves and plugin devs unless it brings new capabilities.

The comments-to-entities migration really didn't even touch the schema but took a ton of effort and introduced a lot of bugs that took awhile to iron out--but we got tangible new powers. At the end of a big denormalization effort I'm worried we'll just get a few sites running slightly faster, because we've already removed a ton of queries through 1.x-2.x.

I'd love to see https://blackfire.io/ data on elgg.org. Would the foundation pay for that? There's also some low hanging fruit in #9095.

**Comment by brettp** [comment]
I'll into getting Backfire on the community site.

The code for metadata / annotations and the SQL produced is so convoluted because of the normalization. Fewer joins _would_ likely give some performance boosts, but I think speed is only a side effect of simplifying our code.

I'd rather make atomic progressive changes than try to fix all the problems at once. There are some decent features hanging in PR limbo because there was never agreement on how much they should fix.

**Comment by hypeJunction** [comment]
If we denormalize, can we loose type specific tables, e.g. users_entity? I
would be happy to see them go.

**Comment by brettp** [comment]
The original reason for those tables were places to hold attributes that
were too slow to use metadata, so it's something we could consider.

**Comment by hypeJunction** [comment]
This would allow us to eventually combine all ege* functions into one that does exactly what ege_from_attributes() does.

**Comment by juho-jaakkola** [comment]
We need to vote which (if any) changes we want to do for Elgg v3. In any case its best to wait until v2 has enough minor releases before starting any work, so we don't end up with horrendous merge conflicts.

**Comment by hypeJunction** [comment]
If we are going to break SQL queries, we should probably break them all at once, rather than spread them across multiple major releases.

**Comment by brettp** [comment]
> If we are going to break SQL queries, we should probably break them all at once, rather than spread them across multiple major releases.

Agreed with that, but 3.0 is a while away, so we can refine as we go. We don't need to have all the schema changes consolidated.
