### ISSUE TITLE
Impossible to get all remaining entities with elgg_get_entities

### ISSUE THREAD

**Issue by bruno-infotrad** [Elgg/Elgg#9291]
Use case:
- Load n entities on a page
- Provide a way for the user to load all remaining entities

Right now, it does not work because offset is given a value only if limit is not 0 (lines 465-469 in engine/classes/Elgg/Database/EntityTable.php)

**Comment by beck24** [comment]
Took me a minute to understand - you're saying this doesn't work right?

    $entities = elgg_get_entities(array(
        'type' => 'object',
        'subtype' => 'subtype',
        'offset' => 50,
        'limit' => 0
    ));

**Comment by bruno-infotrad** [comment]
Right. I know how to fix it but I just want to make sure I am not breaking anything else before submitting a change.

**Comment by beck24** [comment]
Well, if you have a fix stick it in a PR and we'll take a look.  I think that should be a legitimate usage of egef* functions

**Comment by jdalsem** [comment]
@bruno-infotrad did you have a PR for this?

**Comment by jdalsem** [comment]
You can do this the following way:
```php
$entities = elgg_get_entities(array(
    'type' => 'object',
    'subtype' => 'subtype',
    'offset' => 50,
    'limit' => 18446744073709551615 //largest bigint possible
));
```
Mysql has no decent way to do this otherwise https://dev.mysql.com/doc/refman/5.7/en/select.html#id4651990.  

Elgg could do this hack automatically, but the current way to do it is not that hard.
