### ISSUE TITLE
Bundled plugins deactivating when not using cache in 2.0

### ISSUE THREAD

**Issue by gadgetman2016** [Elgg/Elgg#9298]
When "simple cache" and "system cache" is disabled, bundled plugins are being deactivated. If the cache is reenabled, plugins work fine. From looking at the log it prints a messages like the following:
```
[Sat Jan 09 00:42:33.718738 2016] [:error] [pid 7232:tid 788] [client xxx.xxx.x.xx:xxxxx]
PHP WARNING: 2016-01-09 00:42:33 (EST): "
opendir(C:/EasyPHP-DevServer-14.1VC11/data/localweb/projects/elgg_2/mod/garbagecollector/views/default/plugins,
C:/EasyPHP-DevServer-14.1VC11/data/localweb/projects/elgg_2/mod/garbagecollector/views/default/plugins):
The process cannot access the file because it is being used by another process. (code: 32)"
in file C:\\EasyPHP-DevServer-14.1VC11\\data\\localweb\\projects\\elgg_2\\vendor\\elgg\\elgg\\engine\\classes\\Elgg\\ViewsService.php (line 133),
referer: http://xxx.xxx.x.xx/projects/elgg_2/activity
```

NOTE: I replaced the ip address and port with x's

**Comment by mrclay** [comment]
When Elgg disables a plugin it should tell you in the logs, are you sure that's the only message you're getting?

If you disable the garbagecollector plugin, does the problem go away?

**Comment by gadgetman2016** [comment]
@mrclay , with the garbage collector plugin disabled the following is a message printed when the blog plugin in activated

> blog (guid: 3) cannot start and has been deactivated. Reason: Cannot include start.php for plugin blog (guid: 3) at C:/EasyPHP-DevServer-14.1VC11/data/localweb/projects/elgg_2/mod/blog

It works fine with the cache(s) are enabled.

**Comment by mrclay** [comment]
You should make a detailed post to the tech support group to get more troubleshooting ideas: https://elgg.org/discussion/group/179063

**Comment by mrclay** [comment]
Moved discussion to https://elgg.org/discussion/view/2433408/bundled-plugins-deactivating-when-not-using-cache-in-20 If a bug is confirmed, reopen.
