### ISSUE TITLE
Custom favicon is not working if system cache is enabled

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9308]
Custom favicon dropped to `views/default/` works only if system cache is disabled.

**Comment by juho-jaakkola** [comment]
It seems that this is always used and it cannot be overridden by plugins: https://github.com/Elgg/Elgg/blob/2.0/engine/views.php#L29

**Comment by juho-jaakkola** [comment]
Shouldn't this be run only if system cache is not yet loaded: https://github.com/Elgg/Elgg/blob/2.0/engine/lib/views.php#L1583-L1589?

Currently it gets run on every page load regardless if system cache is on or off. Therefore it overrides the path declarations that are already in the cache.

**Comment by mrclay** [comment]
Yep, seems like a big bug.

**Comment by mrclay** [comment]
PR #9310

**Comment by mrclay** [comment]
Fixed by #9310
