### ISSUE TITLE
Crashes when creating admin user in php 7

### ISSUE THREAD

**Issue by c-cesar** [Elgg/Elgg#9314]
The installer sets up the database, but crashes when landing the page to create admin user. The error message says:

`TypeError: Argument 4 passed to Elgg\\PersistentLoginService::__construct() must be of the type array, null given, called in /srv/http/e/vendor/elgg/elgg/engine/classes/Elgg/Di/ServiceProvider.php on line 195 and defined in /srv/http/e/vendor/elgg/elgg/engine/classes/Elgg/PersistentLoginService.php:38`

The called function is:

```php
$this->setFactory('persistentLogin', function(ServiceProvider $c) {
	$global_cookies_config = $c->config->get('cookies');
	$cookie_config = $global_cookies_config['remember_me'];
	$cookie_name = $cookie_config['name'];
	$cookie_token = $c->request->cookies->get($cookie_name, '');
	return new \Elgg\PersistentLoginService(
		$c->db, $c->session, $c->crypto, $cookie_config, $cookie_token);
});
```

So, the problem 4th argument, $cookie_config, is null.Maybe the problem is in $c->config->get('cookies'), but I don't know.

**Comment by mrclay** [comment]
Can you try installing with this change? #9315

**Comment by c-cesar** [comment]
Fixed for me. The installation finishes and I don't get errors or warnings.
Thanks.

**Comment by juho-jaakkola** [comment]
Thanks for reporting the bug!

It's great that you're testing Elgg on PHP 7, so Elgg will be ready for it once it becomes more widely used.
