### ISSUE TITLE
Error when creating a group in PHP 7

### ISSUE THREAD

**Issue by c-cesar** [Elgg/Elgg#9318]
`Argument 2 passed to elgg_format_element() must be of the type array, null given, called in /srv/http/e/mod/groups/views/default/groups/edit/tools.php on line 24 `
The line is:
`echo elgg_format_element('div', null, elgg_view('input/checkbox', array([long array of options])`
Changing null to array() everything works.
Seems PHP 7 don't handle null as empty any more.

**Comment by mrclay** [comment]
Try #9319
