### ISSUE TITLE
Admin context needs a better error page template

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9327]
Forwarding with an error code in admin context breaks the page:

![admin-error](https://cloud.githubusercontent.com/assets/1202761/12681716/44165b46-c6b0-11e5-9625-098e02e0370b.png)

**Comment by mrclay** [comment]
Is there an easy way to duplicate this?

**Comment by hypeJunction** [comment]
forward('', '400'); from any of the admin views.

**Comment by mrclay** [comment]
Added `forward('', '400')` to top of flush_cache.php and I get the Bad Request page with no problems.

**Comment by mrclay** [comment]
oh, views..

**Comment by mrclay** [comment]
Ugh, pagesetup doesn't get to fire and that's where CSS is registered and menu items registered.

**Comment by mrclay** [comment]
The behavior of `forward('', '400')` (dump an error page without redirecting) is a general source of problems.

**Comment by mrclay** [comment]
See in _elgg_admin_page_handler:
```php
elgg_unregister_css('elgg');
elgg_require_js('elgg/admin');
```
Maybe we just move these lines after the admin view is rendered.

**Comment by mrclay** [comment]
PR #9328
