### ISSUE TITLE
Allow /.well-known directory to be served

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9329]
This is a standard location designed for discovery https://tools.ietf.org/html/rfc5785 and is used to set up Let's Encrypt. https://letsencrypt.readthedocs.org/en/latest/using.html#webroot

**Comment by gerard-kanters** [comment]
If the only purpose of the line in .htaccess is to disallow .git access. This should suffice

RewriteRule .*\.git/.* - [F]
 
letsencrypt will be able to proceed then.

**Comment by beck24** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/10790/commits/bb35cb9c317c1176542b76592c7e70805a91b9d9
