### ISSUE TITLE
Fatal Error in installer

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9334]
Fatal error: Call to undefined method Elgg\Filesystem\File::putContents() in \engine\classes\ElggRewriteTester.php on line 192

**Comment by mrclay** [comment]
This call was added in https://github.com/Elgg/Elgg/commit/f2118efd92888574b741cda0a3f9467a2fdcc511 but putContents() was never added.

**Comment by juho-jaakkola** [comment]
How is it possible we haven't noticed this before? It's a fatal error after all.

**Comment by mrclay** [comment]
Oh, some of this was reverted. That file object usage never got into a 1.x release and appeared in 2.0.

**Comment by mrclay** [comment]
PR #9336. @hypeJunction can you try this?

**Comment by hypeJunction** [comment]
It was a new apache installation and I had to change some conf files for
rewrite rules to work. I will check the PR

**Comment by mrclay** [comment]
Closed by #9336
