### ISSUE TITLE
Breadcrumbs on error pages

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9338]
Error pages show breadcrumbs that are registered before error forward is issued.

**Comment by jdalsem** [comment]
Huh.. how do breadcrumbs persist after a forward?

**Comment by hypeJunction** [comment]
We catch forward reason and instead set headers to `404`, `403` instead of `302`

**Comment by hypeJunction** [comment]
We just need to empty the breadcrumb stack in `elgg_error_page_handler()`

**Comment by jdalsem** [comment]
ok will create a PR for this
