### ISSUE TITLE
Useless data in notifications resource view

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9339]
`resources/notifications/index` loads a large list from the database that seems to not be used anywhere in underlying views.

``` php
if ($people_ents = elgg_get_entities_from_relationship(array(
        'relationship' => 'notify',
        'relationship_guid' => $user->guid,
        'type' => 'user',
        'limit' => false,
    ))) {

    foreach($people_ents as $ent) {
        $people[] = $ent->guid;
    }
}
```

**Comment by mrclay** [comment]
It's very old. I suspect is was for plugins extending the `subscriptions/form/additions` view. In 2.x we could wrap this around it:

```php
if (elgg_view_exists('subscriptions/form/additions')) {...}
```

Safer would be to remove in 3.0 as a breaking change.
 Let's get rid of it in 3.0.

**Comment by hypeJunction** [comment]
Can't wait till 3.0. Rewrote the settings and notifications pages to a tolerable state: https://github.com/hypeJunction/Elgg-user_settings

**Comment by juho-jaakkola** [comment]
It's starting to look like we don't have to write any code for Elgg 3. We'll just copy-paste existing code from Ismayil's plugins. ;)

**Comment by hypeJunction** [comment]
Fine by me :stuck_out_tongue_closed_eyes:

**Comment by hypeJunction** [comment]
I honestly don't have any more patience for redoing things for a millionth time. User settings page breaks every time I modify CSS, so are many other plugins I am writing lately. Just can't be bothered with mechanical tasks any more. They drive me insane, make me hate Elgg and the rest of the world with it. :)

**Comment by mrclay** [comment]
It would be good to make the case for BC-breaking early in their own tickets. Solid plugin code can still be tough to merge in (and test and document); we should deprecate early as possible; other devs deserve a voice in how much their plugins will break, etc.

**Comment by hypeJunction** [comment]
It's one of those cases where I would prefer to just roll out my own plugin and not care what others have to say. The friendspicker is an unwanted child that should have been aborted before it saw the light of day. A case of euthanasia is due, but I don't want to be the one to pull the plug.

**Comment by hypeJunction** [comment]
I didn't hear many rejoicing voices when I made #9085

**Comment by jdalsem** [comment]
Fixed as part of https://github.com/Elgg/Elgg/pull/10340
