### ISSUE TITLE
"User X joined group XYZ" river entries still visible after user accounts are banned

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9341]
I noticed it on the community site.

**Comment by juho-jaakkola** [comment]
AFAIK this is expected behavior. Has this worked differently earlier?

**Comment by mrclay** [comment]
It seems silly that we ban spam accounts (leaving their content/activity items lying around).

**Comment by iionly** [comment]
Most likely, it hasn't worked differently before (1.X). I only noticed it now so clearly because some of the recent spammers joing the Professional services group to make their postings there and the river entry about joining the group is still visible after their accounts were banned.

Banning / deleting spam accounts is another questions. I also don't see any sense in banning them.

But regardless of the reason of the ban (sometimes you might indeed want to ban a user as kind of a warning instead of deleting the account) I don't think it's the expected behaviour that these river entries connected to banned accounts stay visible.

**Comment by juho-jaakkola** [comment]
For automated spam prevention it is best to ban instead of delete. It would be bad if automated spam prevention would accidentally remove an actual user and remove all the user's plugins and community posts with it.

**Comment by iionly** [comment]
Okay. Fully agree with not deleting but banning when automatic spam prevention is used.

But I think the discussion got slightly side-tracked. The point is that some river entries are still visible after a user account is banned - for example about joining groups. My guess is that river entries connected with a banned account are only hidden based on the river entries subject_guid and not based on object_guid / target_guid.

**Comment by mrclay** [comment]
For a user banned, say, a couple days for behavior, why should the system hide all their river items? I think this might make sense for some networks but seems not at all necessary in general, and the current behavior seems a tiny bother.

On community we should we routinely reviewing and deleting banned members that are obviously spammers.

**Comment by juho-jaakkola** [comment]
I agree with Steve.
