### ISSUE TITLE
elgg 1.12 strange behavior

### ISSUE THREAD

**Issue by xpoarte** [Elgg/Elgg#9342]
Hello, first I want to say thanks for the quickly and effective help that you always offer to me to solve my doubts

Now I have a question about a strange behavior, I am implementing masonry and infinite-scroll as a plugin, I tested from elgg 1.8 to 1.12 and work well with the exception of 1.12 where infinite-scroll loads good but can´t find the following pages. I made a lot of tests, checked changes in pagination and navigation, I changed parts of the code of the plugin and compared the differences between version 1.11 and 1.12 but I have not found any solution.

However I discovered that it works correctly after the upgrade from 1.11 to 1.12 (I just replace all files except .htaccess and engine/settings.php) 

Comparing clean installations of version 1.11 and 1.12 I saw that there are not difference between the entries in the database, .htaccess and settings.php files, there are not conflicts with plugins. The infinite-scroll does not work when I do a downgrade from 1.12 to 1.11 neither

I have not idea which is the reason that why fails in version 1.12, because it works fine with an upgrade from 1.11, someone knows why happens this? and any solution? For now my only solution is install 1.11 and then upgrade to 1.12.

I will really appreciate any clue or way to found the reason for this behavior, I have been working for weeks doing tests and do not have any idea what fails. All my tests are in localhost, in pc and mac with safari, explorer and firefox. Works fine in versions 1.8, 1.9, 1.10, 1.11.

Thanks again

**Comment by mrclay** [comment]
Please use the community site for support. If it's indeed an Elgg bug feel free to open a ticket with more details.
