### ISSUE TITLE
"Report this" popup dialog layout opening on profile pages is messed up.

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9343]
When reporting a user (from user menu on profile pages) the form opens in a popup. But the layout of the lightbox is messed up (no border, no background).

**Comment by mrclay** [comment]
Works fine for me. Are you getting any error messages in console/error_log?

**Comment by iionly** [comment]
Sorry. No error. The problem occurs both on Firefox and Chrome. So, I don't think it's a browser issue.

It looks like this for me:
![report_user_profile_page](https://cloud.githubusercontent.com/assets/1773681/12839448/c87a24b6-cbd9-11e5-851c-f3b6a40ba6f1.jpg)

**Comment by iionly** [comment]
It seems it's a problem on the community site only. On my local test installation (2.0.1) it works fine, too.
