### ISSUE TITLE
popup menu and register page have wrong charset

### ISSUE THREAD

**Issue by justangel** [Elgg/Elgg#9345]
popup menu charset bug
![2016-02-05 15-38-37](https://cloud.githubusercontent.com/assets/6223199/12846697/fda2cfe0-cc1e-11e5-8bdb-7e0859065f96.jpg)

register page charset bug
![2016-02-05 15-43-09](https://cloud.githubusercontent.com/assets/6223199/12846747/554e11b4-cc1f-11e5-9efa-cb13da19318b.png)
only Cancel button is ok, all other have wrong charset

**Comment by justangel** [comment]
i use elgg 1.12.8 version

**Comment by mrclay** [comment]
I could not duplicate this. What browser did you use?

**Comment by justangel** [comment]
hi, i tested on brousers: Google Chrome, Opera, Mozilla Firefox, Maxthon and Iron
this bug issued in 90% of cases, step by step:
0 - site is closed for unregistered (need to register/login)
1 - open site http://shareboor.net
2 - click on forgot password (and bug is occured)
3 - click cancel
4 - click register (bug is occured)
5 - click cancel
this is for login screen

**Comment by mrclay** [comment]
The ajax responses are being sent with `;charset=iso-8859-1` in the Content-Type (should be UTF-8). It looks like we don't explicitly send charset in ajax responses (definitely a bug). I wonder why no one else has had this problem...

When pages are sent directly, they're properly marked as UTF-8: http://shareboor.net/register, http://shareboor.net/forgotpassword

**Comment by mrclay** [comment]
You can try adding this to .htaccess: `AddDefaultCharset utf-8`

**Comment by hypeJunction** [comment]
Another use case for using Symfony Response more widely.

**Comment by mrclay** [comment]
PR #9349

**Comment by justangel** [comment]
thx, this solved the problem with popups menus, but with register/recovery password pages not

**Comment by mrclay** [comment]
Let me look more into this...

**Comment by mrclay** [comment]
@justangel Try #9349 again. I've updated it to set charset in more cases.

**Comment by justangel** [comment]
thank you very much @mrclay 

when edited "Router.php" file, immediately stopped delete "/register" in the address bar
I logged on the site
chose a different default language
then I went to check the registration
again removed "/register" in the address bar
"Cancel" button is present
and everything is displayed in the correct encoding

thank you very much for the quick help in our problem

**Comment by mrclay** [comment]
To be clear, are you saying #9349 solves all the problems?

**Comment by justangel** [comment]
@mrclay yes, all is ok for now

**Comment by justangel** [comment]
present "Cancel" btn or not, not critical, everything is fine, it is important
