### ISSUE TITLE
Decide whether to change the support policy

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9347]
We're currently following semver very strictly, so IMO there is no technical reason for us to support anything but the latest minor (x.Y.z) release of the supported major versions.

Add votes and possible alternative suggestions below:

## 1. Support only the latest minor versions of two latest major branches

Visualization of the first suggestion:
![support_policy](https://cloud.githubusercontent.com/assets/883920/15606951/f93a6912-2417-11e6-8623-0092daa355d4.png)

**green:** bug and security fixes
**yellow:** only security fixes

 - @juho-jaakkola

## 3. Something else? Add new options if needed.

**Comment by mrclay** [comment]
By (1) do you mean at 2.1 we'd drop support of 2.0 completely, but we'd keep supporting 1.12 until 3.0 is out? E.g. a security release for 1.12 would not imply making 2.0.x release?

By "current one" (2) do you mean [our consensus 5 months ago](https://elgg.org/discussion/reply/view/2362008/2359491):  (formalized in #9346)?

**Comment by mrclay** [comment]
This should probably be discussed on community, but we can vote here.

**Comment by juho-jaakkola** [comment]
Yes to both.

**Comment by jdalsem** [comment]
Which support are we talking about? Bugfix and/or Security? Currently we have different support periods for both... The bugfix support is already as you describe... Security support however is not.

**Comment by mrclay** [comment]
Security. Users on 2.0 would need to upgrade to 2.1.

**Comment by mrclay** [comment]
Community discussion: https://elgg.org/discussion/view/2469826/support-of-minor-branches

**Comment by juho-jaakkola** [comment]
We really should make a decision before the ElggCamp.

**Comment by juho-jaakkola** [comment]
I added a diagram of the first suggestion (the same image I used at ElggCampSBW16).

**Comment by hypeJunction** [comment]
I think we went down the Route 1 without a vote. I think it makes sense. We can still push fixes to minor releases where they make sense, but only make a release of the latest minor release in two last major releases. That way, if we ever make a security patch to a minor release, it will come with all other bugfixes.

**Comment by jdalsem** [comment]
i think in juho suggestion there will never be any more fixes (not even security fixes) to older minor releases... we should maybe even freeze them in github (if that is possible)... fixes from 1.12 would go directly to latest 2.x branch (2.1 as it currently is). There is no need for releases on 2.0 anymore as it is no longer supported...

**Comment by mrclay** [comment]
@juho-jaakkola nice chart. Yeah, my vote is (1).

I see the logic in deleting unsupported branches (add a tag first if it's not a formal release). Merging through them is a waste of effort and Travis resources. We (or a 3rd party) can always resuscitate a branch and merge in 1.12 fixes should the need arises.

**Comment by juho-jaakkola** [comment]
> i think in juho suggestion there will never be any more fixes (not even security fixes) to older minor releases

Yes, this is correct.

**Comment by jdalsem** [comment]
My vote is also for number 1

**Comment by jdalsem** [comment]
How do we make this official?

**Comment by juho-jaakkola** [comment]
- Update http://learn.elgg.org/en/2.0/appendix/support.html
 - Make a blog post

**Comment by jdalsem** [comment]
- We should also make a final release for 2.0.x after which it is closed....

**Comment by mrclay** [comment]
I think this is settled.
