### ISSUE TITLE
1.12.8 - anomaly bugs with register/forgotpassword pages

### ISSUE THREAD

**Issue by justangel** [Elgg/Elgg#9350]
![2016-02-06 12-48-18](https://cloud.githubusercontent.com/assets/6223199/12866234/96b38e86-ccd8-11e5-8daa-ff44c080e897.png)
![2016-02-06 12-51-08](https://cloud.githubusercontent.com/assets/6223199/12866235/9a3f022e-ccd8-11e5-804f-a962bbc9d565.png)
![2016-02-06 12-56-52](https://cloud.githubusercontent.com/assets/6223199/12866238/9f096f06-ccd8-11e5-881c-04f5c9e7d5ec.png)
![2016-02-06 13-08-20](https://cloud.githubusercontent.com/assets/6223199/12866243/dd1af6d4-ccd8-11e5-85aa-0f0f01dd3656.png)
![2016-02-06 13-02-12](https://cloud.githubusercontent.com/assets/6223199/12866250/ed0675aa-ccd8-11e5-93bd-3c279c23ba08.png)
![2016-02-06 13-14-17](https://cloud.githubusercontent.com/assets/6223199/12866251/f14f4574-ccd8-11e5-9e1d-e242bfacd5b2.png)
![2016-02-06 13-18-38](https://cloud.githubusercontent.com/assets/6223199/12866253/07dffb44-ccd9-11e5-866c-df23cdab7f12.png)
![2016-02-06 13-20-25](https://cloud.githubusercontent.com/assets/6223199/12866254/0c7b716a-ccd9-11e5-9996-87e6560c90a4.png)
![2016-02-06 13-24-02](https://cloud.githubusercontent.com/assets/6223199/12866255/118fe3ca-ccd9-11e5-8ea0-cf58626b204e.png)
![2016-02-06 13-27-16](https://cloud.githubusercontent.com/assets/6223199/12866256/15001ed0-ccd9-11e5-89bd-d919101e9e45.png)
![2016-02-06 13-32-01](https://cloud.githubusercontent.com/assets/6223199/12866258/179a7794-ccd9-11e5-8d16-67e40355bc99.png)
![2016-02-06 13-40-25](https://cloud.githubusercontent.com/assets/6223199/12866259/1fa395ba-ccd9-11e5-9835-b8fa7b639147.png)

**Comment by justangel** [comment]
this bug present on sony xperia too

**Comment by mrclay** [comment]
These cancel button issues are not Elgg related. Report them to the 3rd party plugin(s) you're using.

**Comment by mrclay** [comment]
Disable all plugins not bundled with Elgg. If the problem persists, report it here.

**Comment by justangel** [comment]
![2016-02-06 21-16-55](https://cloud.githubusercontent.com/assets/6223199/12868447/2ba9405a-cd18-11e5-87cb-d6df2b5a0648.png)

**Comment by justangel** [comment]
@mrclay i posted a screenshot, disabled all plugins, problem steal exist

**Comment by mrclay** [comment]
The cancel button is supposed to be present on both the register and forgotpassword forms.

**Comment by justangel** [comment]
yes

**Comment by justangel** [comment]
@mrclay have any ideas about this problem? why "/register" is not added automaticaly in the address bar if the type manually then everything is fine and in correct charset, what code removes /register from address bar and initiates anomalous page?

**Comment by mrclay** [comment]
It's likely this #9345. I've mentioned a PR there.
