### ISSUE TITLE
data-confirm handler

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9369]
The behaviour of data-confirm after the default has been prevented is odd and unpredictable during event propagation. I think we should just `return false;` and stop further propagation. It will be easier for plugins to deal with it.

**Comment by hypeJunction** [comment]
I think @jdalsem was proposing this and I disagreed. Now I have changed my mind. I don't think there is a reason to propagate or call consecutive handlers if user said cancel.

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/issues/9240

**Comment by hypeJunction** [comment]
Dupe ##9240
