### ISSUE TITLE
Typical elgg_language_key_exists() usage creates bugs

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9375]
`elgg_language_key_exists()` doesn't consider that what the developer usually cares about is whether the key will be translated at all. Consider this example:

A plugin checks a language key "foo:$type":

```php
if (elgg_language_key_exists("foo:$type")) {
```

Now a Spanish site installs it, defines that key in "es". This will fail because the plugin's check only checks for the English translations. OK, so the plugin is rewritten:

```php
if (elgg_language_key_exists("foo:$type", get_language())) {
```

Now it's installed on an English site and the key is defined under "en". This will fail for a user who's language is set to "es". So really a dev has to do check both:

```php
if (elgg_language_key_exists("foo:$type", get_language()) || elgg_language_key_exists("foo:$type")) {
```

I think we'd really want a function that would check the fallbacks as well, maybe `elgg_can_echo()`?

**Comment by jdalsem** [comment]
i agree it should check fallbacks, however i think it can be done it the current function... what elgg needs is a new way of storing translations... currently we have seperate arrays for each langauge... is the translation not in Spanish we fall back to English... There is still the bug that fall back is not correct (user->language should fallback to site->language should fall back to 'en'... this is not the case see #4389).

If we change the storage of all loaded languages for the current user into one combined array (array_merge('en', $site_language, $user_language)) then there is just one array to elgg_echo from and to check if language exists. 2 flies one stroke... or something like that :)

I think this approach is a lot easier... and better performing as you can reuse the combined array (cache on disk... serve via javascript)

This approach can be fully backward compatible AFAICS

**Comment by hypeJunction** [comment]
That's quite a nice approach I think.

**Comment by jdalsem** [comment]
```php
$languages = [
$user->language,
$site->language,
'en',
];

$languages = array_unique($languages);

$combined_translations = [];
foreach ($languages as $lang) {
    $translation = load_translation($lang); // or something else to get all translations for a certain language
     $combined_translations = $combined_translations + $translation;
}
```
something like that

**Comment by mrclay** [comment]
Right, then you need unique cache keys; this has to be resolved and cached on demand when the first user selects a new language (changing its involvement in system cache quite a bit). We've known this is what needs to be done a long time; it's just a lot of work.

Steve
-- 
http://community.elgg.org/profile/steve_clay

**Comment by jdalsem** [comment]
It think the amount of cache updates is not that frequent.. we can cache based on the unique combination of languages `md5('en-nl-fr')`.. there are not that many unique combinations on an average site...

**Comment by hypeJunction** [comment]
Can't we automatically merge non-site language keys with site language keys
and English when we cache it. So instead of falling back in code, we would
have the fallback within the array of the user language?

**Comment by mrclay** [comment]
These ideas sound great, but should be fleshed out in #4389.

**Comment by mrclay** [comment]
How about we just note in the docs that devs should always make sure an `en` translation exists when adding a key? That makes `elgg_language_key_exists($key)` effectively safe usage.
