### ISSUE TITLE
IMPORTABT ABOUT UPDATING TO THE LATEST VERSION

### ISSUE THREAD

**Issue by judenshome** [Elgg/Elgg#9387]
GREETINGS PLEASE. 
Dear please i need a guide  for which i can updatemy elgg1.12 to elgg 2.0.2

**Comment by hypeJunction** [comment]
Please read the docs http://learn.elgg.org/en/2.0/admin/upgrading.html
If you have problems, please ask for assistance in the community http://community.elgg.org
