### ISSUE TITLE
Changing identifier in route hook

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9388]
Should the core run the route hook on a new identifier if the route hooks changes the original identifier? e.g. if hook routes 'courses/all' to 'groups/all', all route hooks registered for 'groups' will never be fired. It seems that they should be.

**Comment by mrclay** [comment]
Changing identifier/segments in a handler potentially means partial calling of handlers for the old id and the new id, and we still don't have a clean way to change stuff like current_page_url().

I'd prefer (ideally) a hook to alter the request object before core reads stuff out of it, or a "route:before" hook specifically for changing id/segments (and deprecate doing so in "route").

**Comment by hypeJunction** [comment]
I would be happy with either.

**Comment by mrclay** [comment]
PR #9390
