### ISSUE TITLE
Elgg could use multiple editor configurations

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9391]
Besides the current (default) configuration of ckeditor, we should also add support for other configurations. The default config then would be used for forms like writing a blog or page (where you want to have advanced editor configurations) and we would introduce a "simple" config that only has the basic options. This simple config is what you use for a comment form, discussion reply, about me on the profile.

Should be easy to achieve as we can have multiple configurations and you have to instantiate on a specific class...

**Comment by juho-jaakkola** [comment]
Nice idea

**Comment by hypeJunction** [comment]
Something along these lines: https://github.com/hypeJunction/Elgg-ckeditor_addons

**Comment by jdalsem** [comment]
@hypeJunction looks nice! Maybe we need more than 2 configs, so it should be a bit more extendable in core...

**Comment by hypeJunction** [comment]
IMO, CKEditor is a major performance hog. I have recently been working on a plugin that had a bunch of settings, and I just couldn't get the page to load fast because it took forever for CKEditor to instantiate. I imagine on-demand config will have further performance implications.

**Comment by jdalsem** [comment]
I don't see it being any of a performance issue...

```javascript
$('.default-editor').ckeditor({basic_config});
$('.simple-editor').ckeditor({simple_config});
```
basic and simple config come from the ckeditor config view.. that one is cached. What would be the performance issue you expect?

**Comment by jdalsem** [comment]
it is nice that we can now have multiple configurations, but i think it should be wise if we have at least 2 default configs for a full / default and a simple layout and USE it. I don't think it is enough to have the feature available, but not use it in core... i would like to see a simple layout in (at least) comments and forum... the rest can keep default.

**Comment by hypeJunction** [comment]
Do something about it then.

**Comment by jdalsem** [comment]
will do, now you made it possible. I was wondering... i think introducing new configs and using them is probably a breaking change... or is it?

**Comment by hypeJunction** [comment]
Considering that when you edit a comment inline that was initally written in an editor, you loose most of the markup and nl, I would say we will be fixing bugs.
On the other hand you can just keep current config unless explicitly told otherwise by the calling view

**Comment by mrclay** [comment]
> introducing new configs and using them is probably a breaking change

If inputs on 2.2 suddenly lose CKeditor on 2.3, I'd call that a break. 3.0 isn't far off, just add it to master.
