### ISSUE TITLE
elgg_list_entities does COUNT queries when pagination off

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9403]
The current views (lists and pagination) will handle passing a null in for count in this case, but plugins may have overridden these views and expect count to be present. In 3.0 we could warn devs that these views may receive a null count.

**Comment by hypeJunction** [comment]
IMO, we should move away from this pattern:

```php
$options['count'] = true;
$count = elgg_get_entities($options);
$options['count'] = false;
$entities = elgg_get_entities($options);
// then somewhere down the pipe 'count' becomes $count in $vars
$vars = $options;
$vars['count'] = $count;
```
