### ISSUE TITLE
web_services: missing params result in bad function call

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9411]
(Very old issue but I couldn't find a ticket for it.)

```php
elgg_ws_expose_function('test', 'api_test', [
	'one' => ['required' => false, 'type' => 'int'],
	 'two' => ['required' => true, 'type' => 'int']
]);

function api_test($one, $two) {}
```

http://example.org/services/api/rest/json/?method=test&two=2 results in 2 being passed in as $one, and a PHP warning about missing argument $two (`null` within the function).

Workaround: give the "one" parameter a non-null default.

Given there's a tiny chance devs are relying on this undocumented behavior, can we fix this in 2.x?

- Steve :+1: 
- Ismayil :+1:

**Comment by hypeJunction** [comment]
I believe I ran into it before and used the default parameter

**Comment by mrclay** [comment]
I put you down for a +1 vote for fixing.

**Comment by mrclay** [comment]
PR #9418
