### ISSUE TITLE
Identify steps needed to separate a plugin from core

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9419]
The idea's come up several times of separating plugins from core so they can be versioned independently. These are the steps for doing that for each plugin in 2.x:

In this order:
- [ ] merge 2.x code into https://github.com/Elgg/the_plugin
- [ ] copy RST doc files into it
- [ ] add it to Packagist
- [ ] tag it 2.3.0

In Elgg/Elgg 2.x:
- [ ] remove the plugin
- [ ] add via composer.json (require "~2.3")
- [ ] add admin docs to warn upgraders to make sure to remove `mod/<plugin>` before "composer upgrade" and make sure the plugin stays enabled.
- [ ] point Elgg's RST docs to the plugin repo's docs

**Comment by jdalsem** [comment]
What is the main reason to remove this plugin from core?

**Comment by mrclay** [comment]
The general idea of separating plugins from core so they could have independent versioning... In #9406 it was brought up again so I made this ticket mainly to outline all the work that would really entail in 2.x. It's not *really* about web_services, so I'll change the title/desc.

**Comment by mrclay** [comment]
Our stale plugin repos (Elgg/blog) were made with `git subtree split`. I duplicated this process from the 2.x branch and the old commits matched. It also took like 15 minutes for 1 plugin.

I also did the process with `git filter-branch`, which took seconds. It's not clear to me why a subtree method is preferable.
