### ISSUE TITLE
upload avatar image: invalid image dimensions

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9421]
i just saw that a new member of the community had created an avatar image and that it displays on the profile page, but not in the activity stream. i looked through the site log and saw this:

```
"imagecreatetruecolor(): Invalid image dimensions" in file /mysite/engine/lib/filestore.php (line 164)" 
```

i am also seeing some division by zero errors in the log nearby but the timing suggests that they may not be directly caused by the avatar upload.

**Comment by jdalsem** [comment]
There are currently no other reports related to this issue. If you have steps to reproduce on a clean install of Elgg please let us know.
