### ISSUE TITLE
Core still has uses of global $jsonexport

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9424]
In views:
- export/entity
- export/metadata
- export/relationship

**Comment by hypeJunction** [comment]
To be honest, I still feel it was a mistake deprecating it. Views do not cooperate well on json, and it's much easier to work with an global export array. Perhaps we should add a service instead.

**Comment by mrclay** [comment]
All the export views using it are also deprecated.

**Comment by hypeJunction** [comment]
I know ;) Just my 5 cents of grumpiness

**Comment by jdalsem** [comment]
What do we want with this issue?

**Comment by mrclay** [comment]
I guess make an API that returns a reference to a global object that gets encoded at the very end. A more formalized version of `$jsonexport`. I got no ideas here.
