### ISSUE TITLE
CacheHandler fails to send 304 with mod_deflate

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9427]
I am seeing that all JS files are being reloaded on each page load with simplecache enabled on Apache 2.4 with` mod_deflate`, `mod_headers` and `mod_filter` enabled.

I believe it's a symptom of https://bz.apache.org/bugzilla/show_bug.cgi?id=45023

Solution 1: strip `-gzip` suffix from Request `If-None-Match` before comparing it to hash/etag.
Solution 2: do not send Etag headers if `mod_deflate` is on.

I think I would prefer 2.

**Comment by hypeJunction** [comment]
I might have seen this happen with `ServeFileHandler`, but I think it was no longer an issue after I have rewritten the class to use `Symfony\Component\HttpFoundation\Response`.

I guess longer term solution 3 would be to update `CacheHandler` to use `Response` objects.

**Comment by hypeJunction** [comment]
Background:

* Cache handler responds with a cacheable view and adds an `Etag` which is an md5 of the view contents
* `mod_deflate` gzips the response body and suffices `Etag` with `-gzip` 
* Browser requests a cacheable view, with `If-None-Match` that contains gzip Etag
* Cache handler fails to match the `Etag` of the view to the gziped `Etag` and serves the file again

* If `Etag` is not present, browser just serves the resource from cache, which I guess is a problem with simplecache disabled. So, solution 2 would only work partially?

I don't know enough about gzipping, so maybe someone can chime in on this.

**Comment by mrclay** [comment]
I think it's completely safe to simply strip "-gzip" before comparing If-None-Match.

I see nothing in Symfony's http-foundation that would deal with this issue.

With simplecache on we *could* switch to Last-Modified with If-Modified-Since checking. Doesn't seem necessary though, and we couldn't validate with simplecache off.

**Comment by mrclay** [comment]
So the flow would be:
1. browser requests /cache/...
1. send response ETag `"123456"`
1. mod_deflate 2.4 rewrites it `"123456"-gzip` or `"123456-gzip"` in 2.5
1. user manually refreshes
1. browser sends conditional request with If-None-Match `"123456"-gzip`
1. we remove `-gzip` and respond with 304 and ETag `"123456"`
1. ...does Apache rewrite this ETag? Unknown, but let's assume the worst:
1. browser receives 304 and updates its cache to use ETag `"123456"` (no big deal)

**Comment by mrclay** [comment]
It would be safe to just str_replace out `-gzip` because that can't appear in either of our ETag strategies.

**Comment by hypeJunction** [comment]
Do we need to resend Etag with 304?

**Comment by mrclay** [comment]
Spec says we have to. Would probably be fine not to, but...

**Comment by hypeJunction** [comment]
PR #9429 
Tested manually with both simplecache enabled and disabled. I get 304 responses as I should.

**Comment by hypeJunction** [comment]
Not sure about other browsers, but Chrome keeps sending -gzip Etag even if consecutive 304 response didn't have it.

**Comment by hypeJunction** [comment]
We are not deflating images so there is no issue in file handler.

**Comment by mrclay** [comment]
We really should fix this everywhere we 304 and in 1.12 (LTS).

**Comment by hypeJunction** [comment]
Sorry, I won't have time for that. Too much to do over the weekend and I am finally taking a week holiday.

**Comment by hypeJunction** [comment]
Fixed by #9433
