### ISSUE TITLE
Prevent the deletion of content in the database

### ISSUE THREAD

**Issue by joalbor1** [Elgg/Elgg#9431]
Recently I am learning Elgg to carry out my research on social networks. After studying the performance and functionality that the tool itself offers I found one aspect that hurts me and I do not really know how to fix it.

Then I will explain the problem to which I seek solution, I hope you understand it and can help me. Thanks in advance.

I've noticed that if users (who use the social network that I have installed) eliminate the social network content, it is deleted from the database directly. That is, if the social network information is deleted from the web interface is also removed from the database. This is my biggest problem as I need for my research have access to all the information, also eliminated.

Is there any way to prevent the information deleted from the database? Any plugin? Could I develop my own plugin that prevents this information deleted altogether?

Greetings and thanks.

**Comment by mrclay** [comment]
Please use the Community site for support. https://elgg.org/groups/profile/179063/elgg-technical-support
If you need an account, send the username/e-mail you'd like to info@elgg.org.
