### ISSUE TITLE
comment redirector check for # in url

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9435]
The forwarding after comment->getURL() does
$container->getURL() . '#comment-id';

If however $container->getURL() already contains an # you'll get double # in the url and this no longer works (eg http://example.com/view/object/something#container-id#comment-id)

**Comment by mrclay** [comment]
Which fragment should win?

**Comment by jeabakker** [comment]
i think the comment should win (as this is the comment->getURL())

also it's not comment->getURL(), but the comment page_handler -> _elgg_comment_redirect
