### ISSUE TITLE
comment notification to owner should be offloaded

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9436]
In the comment save action a notification is sent to the owner of the entity being commented on (if owner != comment owner)

Why is this not controlled by the ->getSubscribers() for the comment notification event?

**Reason i have a problem with this:**
I changed the comment notification subject/message in the 'prepare:create:object:comment' hook, this works for everybody except the entity owner

**Comment by hypeJunction** [comment]
The notification system skips recipients if they are content owners. IMO
that should not happen and prepare hook should be to distinguish what
notification is sent based on recipient.

**Comment by jeabakker** [comment]
the notification system skips a notification if the actor (comment creator) is the same as the recipient. 

I would like to add the content owner (eg blog owner) as a recipient.
