### ISSUE TITLE
no link to group membership management

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9438]
with the move to resource views the page setup is triggered before additional contexts are set in the resource view.

This causes a problem on the group profile page, as the link to 'manage membership requests' is only added if `elgg_in_context('group_profile')` during `pagesetup`

possible solution:

1. add the menu item always with a 'context'
2. make a menu:page hook to add the item in the correct context (preferred)

**Comment by mrclay** [comment]
See https://github.com/Elgg/Elgg/issues/8374#issuecomment-191786076

**Comment by mrclay** [comment]
Already fixed by #9271 but not yet released.
