### ISSUE TITLE
user related links in sidebar when page_owner is ElggGroup

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9439]
link to the following pages are present even if the page_owner is a group

- all groups
- my groups
- groups i own
- group invitations

related to #9438

**Comment by mrclay** [comment]
What version? What type of URL shows this?

**Comment by jeabakker** [comment]
it was on the group profile page (2.0.0)

maybe already fixed by #9271

**Comment by jeabakker** [comment]
can't find the error anymore, so closing
