### ISSUE TITLE
Deprecate rel="popup" and rel="toggle" in favour of class selectors

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9458]
`rel` attribute is native for `<a>` tags, which makes it less attractive for use with non-anchor tags. I think we can keep them in without deprecation, just need to update the docs.

**Comment by jdalsem** [comment]
To close this we need to:
- [ ] update the docs
- [ ] add support for class selectors in popup and toggle

Anything else?

What would be the class names?
`elgg-popup` and `elgg-toggle` or `elgg-ui-toggle/popup`
