### ISSUE TITLE
Prefer CSS transitions to $.fadeIn() and $.fadeOut()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9459]
When you have two closely positioned elements (e.g. popup triggers), `$.fadeIn()` and `$.fadeOut()` take too long to complete thus invoking collision logic, i.e. clicking on a new trigger while the popup of the other module is open.

I propose we add `.elgg-hidden` class with the transition, and move away from using `.hidden` as it is known to cause problems (.e.g. with Twitter Bootstrap that also has `.hidden` class, which also sets `visibility: none;`)

**Comment by mrclay** [comment]
Maybe `.elgg-faded-out`? As a dev I'd expect `.elgg-hidden` to hide something immediately.

**Comment by juho-jaakkola** [comment]
Yes, something like `.elgg-faded-out` is better.

**Comment by hypeJunction** [comment]
I think we will need both `.elgg-faded-in` and `.elgg-faded-out`. I will see when I get to it.
.

**Comment by jdalsem** [comment]
No need to change this at the moment. Current jQuery ui has no collision issues. It does things differently then when this ticket was reported.
