### ISSUE TITLE
Allow `feat` in commit messages

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9460]
Our commit message policy is based on Angular commit message format, which uses `feat`. As I use default formation in conventional changelog in my plugins, I keep forgetting that Elgg doesn't support it.

**Comment by juho-jaakkola** [comment]
SGTM

**Comment by mrclay** [comment]
Sure. I think the changelog writer will need to be updated, ideally to treat "feat" as an alias of "feature".
