### ISSUE TITLE
(group)profile icondirect.php shouldn't check size

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9461]
in the profile icondirect there is a check if the icon size is a fixed array of values
https://github.com/Elgg/Elgg/blob/2.x/mod/profile/icondirect.php#L25-L31

this causes problems if a theme/plugin defines custom size-names. 

It would be better to just check if the file (for size x) exists and maybe do a fallback to 'medium'.

this also applies to the group icon.php

**Comment by hypeJunction** [comment]
We should just merge https://github.com/Elgg/Elgg/pull/9263 and be done with size randomness

**Comment by jeabakker** [comment]
I don't think #9263 handles the group profile image.

but if #9147 can also handle that than i'm all for it

**Comment by hypeJunction** [comment]
The idea behind #9147 is to allow any file to be served from filestore without additional page/resource handlers.
I think the reason I didn't make a PR for group avatars is I was waiting for https://github.com/Elgg/Elgg/pull/9188 to clean up group avatar code along the way

**Comment by juho-jaakkola** [comment]
Yes, we should change all icon code to use the new file serving API. Only question is when to do it. For Elgg 3 we should move the icon files from group owner's datadir to group's datadir. That should be the latest time to make the switch.

**Comment by hypeJunction** [comment]
We have made the switch in the files plugin, so we can go ahead and do that for users and groups. File serving API is agnostic to file ownership, the plugin's icon URL handler passes in the file object that needs to be served. We transfer ownership later on. IMHO.

**Comment by juho-jaakkola** [comment]
True, I guess we can switch to the new API right away.

**Comment by hypeJunction** [comment]
I just realized that https://github.com/Elgg/Elgg/pull/9365 made it to master and not 2.x. So, not sure what the course of action is. @mrclay Should we wait till 3.0 to make the switch? If that's the case, @jeabakker can just make a PR to 1.12 to fix this issue?

**Comment by hypeJunction** [comment]
#9464 is in, so it's up to you @jeabakker if you want to keep it open
