### ISSUE TITLE
BinaryFileResponse requires ext fileinfo

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9463]
`PHP Fatal error:  Uncaught exception 'LogicException' with message 'Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)' in \\vendor\\symfony\\http-foundation\\File\\MimeType\\MimeTypeGuesser.php:135`

We should probably set `Content-Type` explicitly in `ServeFileHandler`. I suppose we can't start requiring fileinfo.

**Comment by hypeJunction** [comment]
Related https://github.com/Elgg/Elgg/issues/9121

**Comment by mrclay** [comment]
Try #9466

**Comment by hypeJunction** [comment]
That works with finfo disabled. Not sure which method is kicking in though. As long as we send the Content-Type header, we should not be running into this issue.
