### ISSUE TITLE
Allow retiring views before major releases

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9469]
We occasionally would like to stop using core views in a non-major release (e.g. for #9263 we'd like to retire the `resources/avatar/view` view), but we have no way to tell if/how plugins are using/altering that view.

Always we'd need to know if the view was overridden or if there's a handler for `view_vars` hook.

*Usually* we'd need to know if the view was extended or altered via `view` hook, but this isn't likely to happen for resource views.

**Comment by mrclay** [comment]
```php
_elgg_view_is_used($view, $expected_view_file) {
    // if view location doesn't match, true
    // if view is extended, true
    // if any handlers for [view, $view] or [view_vars, $view], true
    return false;
}
```

**Comment by mrclay** [comment]
We can't detect if plugins render the view, so we always have to keep it functional in BC releases.

**Comment by hypeJunction** [comment]
I am going to give it a shot.

**Comment by mrclay** [comment]
I'm close to done. Sorry!

**Comment by hypeJunction** [comment]
Don't be :) I wasn't sure if you were going to actually work on it.

**Comment by mrclay** [comment]
PR #9471.
