### ISSUE TITLE
"Infinite loop attempting to show error page" for non existing group profile page

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9476]
when attempting to view `/groups/profile/83193874912374912376` you'll get the message "Infinite loop attempting to show error page" instead of the (expected) `404` page

reason is https://github.com/Elgg/Elgg/blob/2.0/mod/groups/start.php#L162 which triggers (for the 2nd time) the error page handler

**Comment by hypeJunction** [comment]
Oh, that's a nice one. Can I just say out loud once again that pagesetup needs to die.

**Comment by mrclay** [comment]
Not a problem in 2.x. Hmm.

**Comment by mrclay** [comment]
So #9440 has introduced this bug. Hell.

**Comment by mrclay** [comment]
Well, more general problem is we allow re-triggering system events.

**Comment by mrclay** [comment]
In 1.12, 404 forwards were allowed to nest, going through elgg_error_page_handler() multiple times, basically the last one "winning" to draw the page.

This was dangerous, but I didn't run into an infinite loop until doing the views overhaul in 2.0. At which point I (wrongly) assumed even twice was a sign of an infinite loop and I added the abrupt exit.

After #9440, the pagesetup is no longer triggered by the resource/group/profile page, so the page resource does the first 404, the error page triggers pagesetup, and the pagesetup handler for group triggers the 2nd 404.

A simple fix would be to allow maybe 3 calls to elgg_error_page_handler() before pulling the plug.

**Comment by mrclay** [comment]
But generally we should also decide what to do when code wants to draw an error page during the process of drawing the error page.

**Comment by hypeJunction** [comment]
We can add proper page handlers for error codes and actually redirect to
them rather than drawing the page within a page.

**Comment by mrclay** [comment]
This might work for 2.0 #9477
