### ISSUE TITLE
Elgg requires global install of composer

### ISSUE THREAD

**Issue by vPriVate** [Elgg/Elgg#9479]
Just trying to install Elgg 2 via composer.
Due to a shared server it is not possible for me to install composer globally to run commands like "composer ...". I have to go the "local" way like "php composer.phar ...".
After creating a new project of elgg/elgg the check of the global requirements (.scripts/check_global_requirements.php) failed because of the unknown command "composer".

Which are the next steps after creating a new project? Can I perform them "the local way"?
Are there other problems expected because of this behavior? Or can I use elgg as usual including the benefits of composer?
Thanks for your replies!

**Comment by hypeJunction** [comment]
Use `alias composer="path/to/composer"`
Please use the community discussions for support.
