### ISSUE TITLE
Installer is broken

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9486]
I am unable to install Elgg 2.1 or Elgg 2.x. I narrowed it down to `_elgg_services()->simpleCache` call, so something is happening in DI factory that's causing an infinite loop...

**Comment by hypeJunction** [comment]
The offender is `Elgg\Config:loadSettingsFile`, which is called by the db factory, called by the simpleCache factory. It sets the location header to install.php thus causing an infinite loop.

**Comment by vPriVate** [comment]
Same here :(

**Comment by mrclay** [comment]
Working on this

**Comment by mrclay** [comment]
PR #9509
