### ISSUE TITLE
2.1.0 zip contains 2.0.3

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9487]
from https://elgg.org/comment/view/2475340/2474886

> The content of the zip compared to the 2.0.3 zip and to the 2.1 branch on github makes me believe that the 2.1.0 zip archive currently available at the community site is NOT version 2.1 of Elgg but basically just 2.0.3 with only updated versions of some dependencies in the vendor folder (but no changes in /vendor/elgg/elgg/ or in the mod folder at all!!!).

- [x] After resolving, remove the warning from the blog post https://elgg.org/blog/view/2474886/elgg-210-released

**Comment by mrclay** [comment]
Yes, when the zip was built 2.1.0 had not yet been tagged. Unfortunately the release script probably gave no errors. cc @juho-jaakkola

**Comment by mrclay** [comment]
cc @iionly

**Comment by juho-jaakkola** [comment]
Oops...
