### ISSUE TITLE
Add warning in upgrading docs

### ISSUE THREAD

**Issue by Wouter0100** [Elgg/Elgg#9488]
We've been struggling with an issue on one of our Egg instances after upgrading from 1.8 to 1.12. Elgg wasn't sending any notifications to the users. 

At the end, it was because our minute cron wasn't running.. There was never a need for this cron, so we never configured it to run.. Could we maybe add a warning in the docs for this? This will save users *ugh* much time.

**Comment by mrclay** [comment]
> There was never a need for this cron...

It was part of the API. 1.8 plugins mave have used it.

> so we never configured it to run..

That was a bad idea that cost you. :) Really sorry, but we definitely don't recommend users leave out parts of the installation.

If you wanna add the warning, figure out which release it started with and make a PR.

**Comment by Wouter0100** [comment]
Yeah, of course. I'll open a PR for this :+1:.

**Comment by iionly** [comment]
The upgrade instructions from 1.8 to 1.9 (new notification system was introduced in Elgg 1.9) already mentions the 1 minute cron interval used (http://learn.elgg.org/en/2.0/admin/upgrading.html#from-1-8-to-1-9).

What seems to be missing is some mention of the need for configuring the cronjobs in the install instructions (http://learn.elgg.org/en/2.0/intro/install.html) for new users knowing about the need to set up the jobs at all. Right now it's only mentined in the administration guides (http://learn.elgg.org/en/2.0/admin/cron.html) that might not get read when installing Elgg (or maybe not at all...).

**Comment by mrclay** [comment]
Indeed, we should add cron to install instructions in 1.9 branch and merge up so all the docs have them.
