### ISSUE TITLE
Formalize deprecation commits

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9489]
#9432 deprecated `$autofeed` but as it was wrapped in a feature commit, that deprecation isn't mentioned in the 2.1 changelog.

We should probably make sure a separate `deprecate(foo)` commit is made for all deprecations, and make that clear in the docs for making PRs.

I've been mentioning _some_ in https://github.com/Elgg/Elgg/blob/2.x/docs/guides/upgrading.rst#deprecated-apis. Is this a good idea?

cc @iionly

**Comment by mrclay** [comment]
Should we update the 2.1 changelog to add in this deprecation (in 2.x)? Obviously we can't edit the tagged one.

**Comment by hypeJunction** [comment]
Let's just require they are mentioned in the docs. I don't think it's feasible to deprecate out of context, e.g. deprecate something without a feature replacing it.

**Comment by mrclay** [comment]
> I don't think it's feasible to ... deprecate something without a feature replacing it

We've done this lots (see every commit marked `deprecate(`). Some old APIs we don't mind to keep around until there's a compelling reason to get rid of them. But anyway...

General issue seems to be that we don't have a formal place for release notes. Crazy idea: We keep a file in docs somewhere. The changelog updater pulls that in and clears it.

**Comment by jdalsem** [comment]
I think it is formalized enough.
- if possible use a `deprecate()` commit
- if deprecation is part of a 'larger' PR (like a `feature`) add a mention in the upgrading docs
