### ISSUE TITLE
FR: group_tool_options should be hookable

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9497]
If we would let the usage of group tool options in the groups plugin use a groups plugin function like `groups_get_tool_options` we could make it have a hook. That way we can move group tool options to a registration hook (and maybe deprecate the usage of `add_group_tool_option`). First step would be to introduce the hook in the groups plugin.

This hook allows for conditional group tool options.

**Comment by mrclay** [comment]
Sounds fine. Pass in the entity (group/null) and container as params to discourage sniffing those. Still I'd see no rush to remove `add_group_tool_option`.

**Comment by jdalsem** [comment]
I am not intending to remove `add_group_tool_option`, however this is a group related function that exists in core... that does not belong there

**Comment by hypeJunction** [comment]
The problem with it being outside of core is you always have to check if groups plugin is enabled.

**Comment by jdalsem** [comment]
> The problem with it being outside of core is you always have to check if groups plugin is enabled.

not if you are registering via the new hook

**Comment by hypeJunction** [comment]
True. But then all the legacy code won't know about those tool options.

**Comment by jdalsem** [comment]
that is why we have deprecation notices... and major/breaking chances

**Comment by mrclay** [comment]
> But then all the legacy code won't know about those tool options.

Right. We can't move any existing core options to the new hook (until 3.0).

**Comment by jdalsem** [comment]
For now... lets leave it as is. I see no reason to drop `add_group_tool_option`
