### ISSUE TITLE
Clean up menu assembly with intermediate representations

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9508]
I think in general menus are too squishy and loosely typed, making it easy for devs to miss, duplicate steps, or do them in the wrong order. We could use types to make sure menus are handled right:

- Elgg\Menu\List: set of items plus some utility methods ([e.g.](https://gist.github.com/mrclay/2242916))
- Elgg\Menu\Menu: name and list
- Elgg\Menu\PreparedMenu: name and sections

An `elgg()->menus` service could have methods to build those up in the particular order we need:

- `build(name, params)` calls register, returns `Menu`
- `prepare(Menu)` builds sections, calls prepare, returns `PreparedMenu`
- `view(PreparedMenu)`

None of this would make it impossible to hack those steps if you needed to.

cc @hypeJunction @jdalsem

**Comment by hypeJunction** [comment]
SGTM

**Comment by mrclay** [comment]
PR #9522
