### ISSUE TITLE
FR: open widgets add panel in a lightbox instead of inline

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9513]
Currently the add panel for widgets is completely loaded on the page... we could move this code into an ajax view and instead of showing it inline, show it in a lightbox

**Comment by mrclay** [comment]
:heart: Do the widgets have descriptions or any info like that we could show with their names?

**Comment by hypeJunction** [comment]
They have a description.

**Comment by jdalsem** [comment]
Wow you must have never used the widget_manager plugin @mrclay ... doing this for a while now in that plugin.

![widgetmanager lightbox](https://cloud.githubusercontent.com/assets/861833/13879842/d7393c92-ed19-11e5-9115-bff0a270ed32.png)

**Comment by mrclay** [comment]
A couple years ago :)
