### ISSUE TITLE
Document issues with type-hinting

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9516]
- Encourage type-hinting in new functions
- Remind that `get_entity()` can return `false` (which will fail a null-accepting type hint)
- Avoid passing around unsaved entities (as we do [here](https://github.com/Elgg/Elgg/blob/2.1/mod/groups/actions/groups/edit.php#L57)). Danger being these will pass type hints but will often be unusable or have unexpected behavior (like empty GUID).

**Comment by jdalsem** [comment]
I do not think this requires additional docs
