### ISSUE TITLE
File thumbs for non-image simpletype

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9517]
File icon hook only checks for `thumbnail` metadata, `thumbnail.php` subsequently chokes after checking `simpletype`.

**Comment by hypeJunction** [comment]
Can we just get #9365 into 2.x. I honestly can't be bothered with the file plugin any more.

**Comment by mrclay** [comment]
Yes provided we deprecate and sniff for used view, as in #9263

**Comment by hypeJunction** [comment]
Fixed
