### ISSUE TITLE
Avatars are not private, even in private community

### ISSUE THREAD

**Issue by dukeritchie** [Elgg/Elgg#9518]
Found in version 2.01, may affect other versions.

When a site is secured using "Restrict pages to logged-in users", avatars can still be viewed by unauthenticated browsers (anonymous users).

By using hostname/mod/profile/icondirect.php?guid=(guid value), a script can run and grab all avatar images.

This isn't a security issue, since no data is breached or privilege escalated.  However, a secure community implies that a user's avatar is also secure from those outside the community, and this is not the case here.

**Comment by hypeJunction** [comment]
We should decide how to handle walled garden sites in #9263

**Comment by beck24** [comment]
I agree having them publicly available probably isn't expected behaviour

**Comment by jdalsem** [comment]
As long as i can remember this was always the case. There was never a system in place that validated the access of a profile icon.

**Comment by hypeJunction** [comment]
I think the problem is not the avatar access level, rather `/mod/.*` being served even if walled garden is enabled.

**Comment by jdalsem** [comment]
that is in this case... but you could stretch the request to more then just the disk access. What if people had a setting to allow only friends to see their avatar? (https://github.com/ColdTrick/profile_manager/issues/62)

**Comment by hypeJunction** [comment]
The problem goes away with the new file serving API, which allows plugins to generate a URL that is not bound to session and thus can be served bypassing walled garden, if needed.

**Comment by hypeJunction** [comment]
Fixed by #9263

**Comment by mrclay** [comment]
#9263 caused all avatar URLs to be not proxy-cacheable. If we keep mod/profile/icondirect.php around, it should deny the request if WG is enabled. So I guess we have to boot, which is a bummer but it's only for this legacy script.
