### ISSUE TITLE
Elgg 2.0/2.1/2.X: possible regression with support of new languages / translations

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9521]
I've noticed that for some languages (with language codes of more than 2 characters) the correct language name (instead of language code) is again not displayed in the language selection dropdown.

I suspect that https://github.com/Elgg/Elgg/commit/72b94d98596e07f038078a27b9be1d6141defc0c hasn't been merged to the Elgg 2 branches or at least not fully merged resulting in at least the changes in the language files missing (both en and also for translations).

**Comment by iionly** [comment]
I think only the changes / new strings in en.php have been missing. The other changes of the commit exist in the 2.0 - 2.x branches. With https://github.com/Elgg/Elgg/pull/9567 the missing strings are added again (to 2.0 branch).

**Comment by mrclay** [comment]
Fixed by #9567
