### ISSUE TITLE
Possible BC break in new widgets AMD module

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9523]
See https://github.com/ColdTrick/widget_manager/issues/76

@hypeJunction details would be great here.

**Comment by hypeJunction** [comment]
I am not sure what is happening exactly. If I wrap ColdTrick's JS to require `elgg/widgets` and call `init()` it works, otherwise it's never called due to error (or would have been called too late).

**Comment by mrclay** [comment]
There are a few issues. In 2.1, `init, system` fires later, in the elgg/init module. I don't think this is a bug, but if a lot of plugins assume Elgg stuff is done by $ domready, this may cause problems.

Also, widgets.init() is no longer tied to `init, system`. That's probably not OK. We probably need elgg/init to depend on any "always required" core modules, at least elgg/widgets.

Lastly, widget_manager's site.js doesn't block on anything but the `elgg` module, so it's basically working on the luck of `init, system` firing really early.

**Comment by mrclay** [comment]
@hypeJunction please take a look at https://elgg.org/discussion/view/2477289/migrating-elgg-libraries-to-amd-modules-in-2x

**Comment by hypeJunction** [comment]
The issue is bigger here. 
In 2.0, dependency on `elgg` was sufficient for the `init,system` to fire. Now you have to depend on `elgg/init`.

**Comment by hypeJunction** [comment]
This is 2.0 code:

```js
define('elgg', ['jquery', 'languages/' + elgg.get_language()], function($, translations) {
	elgg.add_translation(elgg.get_language(), translations);
	$(function() {
		elgg.trigger_hook('init', 'system');
		elgg.trigger_hook('ready', 'system');
	});
	return elgg;
});
```

In 2.0, modules that depend on `elgg` were sure that all the core and plugin code registered for `init` was bootstrapped. It's not the case anymore, that's why widget_manager fails, and I am sure we will see more failing JS code.

**Comment by hypeJunction** [comment]
In case of widget_manager, I think it's up to them to fix. The plugin extends `elgg.js` and does not use an async module. Even though the behaviour did change between 2.0 and 2.1 with regards to when UI libraries are bootstrapped, I think we should discourage plugins from extending `elgg.js`, especially without hook handler registration. @jdalsem, thoughts?

**Comment by hypeJunction** [comment]
@mrclay Sorry, I should have just paid attention to your message :) Just repeated everything you have said. I don't think there is anything to fix here. Let's document that extending `elgg.js` is not ok, and that you should depend on `init/ready`, if you do. It's a trivial fix for plugins to go from `elgg` to `elgg/ready` or bind to `ready` event.

**Comment by mrclay** [comment]
I've actually come around to accepting extending `elgg.js` as long as async `require` is used. I think the big overhaul I was planning to make `elgg` truly async, just isn't worth the trouble for us or for plugin devs.
