### ISSUE TITLE
developer tools no longer shows all hooks/events callbacks

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9527]
in the inspect listing of hooks/events not all registered functions are listed

probably has todo with https://github.com/Elgg/Elgg/commit/3e6a28984bcbcb8e0698ca716fac924dc25fd10e

**Comment by mrclay** [comment]
Can you give me a specific hook and event missing?

**Comment by jeabakker** [comment]
for example i want to inspect all `register` `menu:entity`

currently (elgg 2.1.1) i get this list ;)
![dev_tools hooks](https://cloud.githubusercontent.com/assets/881958/13946021/28aea472-f012-11e5-830f-2916c96b7194.png)

I'm missing just a few registered functions

**Comment by hypeJunction** [comment]
Something is off in your setup, IMO.
![inspector](https://cloud.githubusercontent.com/assets/1202761/13946294/ffda9a90-f013-11e5-86ba-76a1e7e39ee7.png)

**Comment by jeabakker** [comment]
i did a fresh git pull just before the screenshot was made :(

**Comment by hypeJunction** [comment]
Same list in 2.1

**Comment by mrclay** [comment]
And you're sure those calls are being made in the register hook?

**Comment by jeabakker** [comment]
search through core for `menu:entity` and you should get something like the list hype showed, but for me i get a much shorter list :( I don't get why

**Comment by mrclay** [comment]
I also just see `likes_entity_menu_setup`. :confused:

**Comment by mrclay** [comment]
PR #9566

**Comment by mrclay** [comment]
In 2.0 for a (hook, type) parit, each unique priority is stored in a separate array of handlers. Only the last priority in the list was making it through. @hypeJunction had likes disabled, so the 400 priority didn't wipe out the others. This also fixes the priority ordering.
