### ISSUE TITLE
elgg/Ajax instantiation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9533]
The method prescribed in docs does not instantiate `elgg/Ajax`

Doesn't work
```js
var ajax = new require('elgg/Ajax')();
```

Works
```js
var Ajax = require('elgg/Ajax');
var ajax = new Ajax();
```

**Comment by mrclay** [comment]
Probably needs `new (require('elgg/Ajax'))();`. You're suggestion is more readable.

**Comment by hypeJunction** [comment]
I can't believe `you're` one of the `you're` people ;)
