### ISSUE TITLE
Teach elgg/Ajax to handle serialized query data

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9534]
When submitting forms, it is common that request data is a serialized query string returned by `$.serialize`

**Comment by mrclay** [comment]
I considered this and couldn't find an equivalent of `$.unserialize`. We might have to make something like `Ajax.objectify(form)` and recommend ppl use it, though I don't like that idea.

**Comment by hypeJunction** [comment]
Do we really want to allow filtering of form values before the hit the server? Maybe, we don't trigger filter hooks if `data` is a string and just pass it as is?

**Comment by hypeJunction** [comment]
This kind of defeats the purpose of a `POST` request:
https://github.com/hypeJunction/Elgg/blob/discussions-amd/mod/discussions/views/default/discussion/Reply.js#L71

**Comment by mrclay** [comment]
Can you try using this function? particularly a complex form.

```js
/**
 * Convert a form/element to a data object
 *
 * @param {HTMLElement} el HTML element
 * @returns {Object}
 */
function objectify(el) {
	// http://stackoverflow.com/a/1186309/3779
	var o = {};
	var a = $(el).serializeArray();

	$.each(a, function() {
		if (o[this.name] !== undefined) {
			if (!o[this.name].push) {
				o[this.name] = [o[this.name]];
			}
			o[this.name].push(this.value || '');
		} else {
			o[this.name] = this.value || '';
		}
	});

	return o;
}
```

**Comment by mrclay** [comment]
We could both skip request hook on string data, and offer that to allow data to be hookable.

**Comment by mrclay** [comment]
See #9547. I think for 2.1.x devs will have to use the function from my last comment.
