### ISSUE TITLE
FR: automatic registration of widgets

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9538]
Working on #9537 i thought it would be nice to add a feature to autoregister widgets. This would replace the need to register widgets in init

What if in the widget folder (besides the edit and content view) there was a json file with the config of the widget. Widgets with these config files available will automatically be registered. The json_decoded contents of the config file will be used as input for `/ElggWidgetDefinition::factory`.

We could even NOT require the existence of the config file and just register all these widgets. 
- The foldername is the handler.
- The name/description could be magics

If you register your widget again in an init, this will override the autodetected widgets (just as is does currently)

**Comment by hypeJunction** [comment]
:+1:

**Comment by mrclay** [comment]
I don't think widget registration is such a big problem that we have to introduce such magic, but you can easily do it from `elgg_list_views()`.

**Comment by jdalsem** [comment]
i am preferring a config based registration https://github.com/Elgg/Elgg/issues/10348
