### ISSUE TITLE
Add elgg-plugin.php config files

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9544]
We know declarative config would reduce plugin init boilerplate and decouple configuration from event timing. We introduced `views.php` because of this, but we don't want a separate file for each option.

I think this should get scanned early, before any start.php files are executed, so we can cache it.

Should return an array of serializable scalars, no objects (or anon functions) or resources.

Later ideas: start.php not required if elgg-plugin.php present; subtype config; routing; event registration; config vars; configuring the ElggPlugin instance to be auto-injected into some plugin-provided object...

**Comment by mrclay** [comment]
As it's still early, and few plugin authors are using the `views.php` config file, I'd open to deprecating and moving it into `elgg-plugin.php`.

**Comment by hypeJunction** [comment]
I am fine with that. elgg-plugin can read from views.

**Comment by jdalsem** [comment]
we now have elgg-plugin config files
