### ISSUE TITLE
Make MimeTypeDetector strategies configurable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9548]
I was having an issue with the `MimeTypeDetector` on a server, where finfo was giving no results and mime content type was always returning `text/xml`. I had no option but comment out mime content type, it would be easier to do it via config.

**Comment by mrclay** [comment]
Would allowing the configuration of `MimeTypeDetector::$strategies` be enough? Just convert it to service and pass that property through a hook.

**Comment by mrclay** [comment]
The "config" hook could be called right in the ServiceProvider factory, but it feels weird to me.

**Comment by hypeJunction** [comment]
Why not add `$CONFIG->exclude_mime_detection_strategies = []`, inject `\Elgg\Config` into `MimeTypeDetector`

**Comment by mrclay** [comment]
You'd never want to add one or change the order?

**Comment by hypeJunction** [comment]
We can't really rely on hooks because we want this to work with minimal boot. Adding new methods would involve autoloading classes/including files, which would mean we have to boot the core for the plugins to chime in. I am inclined to just leave it as is until somebody else complains. I was able to resolve the server issue.

**Comment by jdalsem** [comment]
Closing this as we can wait until someone complains :smile:
