### ISSUE TITLE
SubscriptionService::getSubscriptions should use Iterator

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9553]
`SubscriptionService::getSubscriptions` should be able to work with `Iterator` instances. It would be a lot more efficient if we could feed an `ElggBatch` and let it resolve subscription methods.
I am working on a feature that notifies all members of the site and I am afraid subscriptions are not scaleable.

**Comment by hypeJunction** [comment]
This scares me: https://github.com/hypeJunction/Elgg-notifications_mass_mail/blob/master/start.php#L111

**Comment by jeabakker** [comment]
With the current implementation of the subscriptions I don't see how we could do this.

Keep in mind that hooks are allowed to add/remove subscriptions. How would that work with an Iterator???

If someone has a great idea feel free to pick this up again
