### ISSUE TITLE
Determine how to warn devs not to override some views

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9554]
Thinking out loud, now that we are moving JS to AMD, we will be stuck with inability to refactor JS due to potential BC implications. Maybe we should exclude AMD views from BC policy

**Comment by mrclay** [comment]
We could explicitly document at the top that some modules are private and shouldn't be overridden.

**Comment by mrclay** [comment]
This is definitely a tough thing to consider. It's what motivated this experiment #8085

**Comment by hypeJunction** [comment]
I like that. We could extend it to all views we don't want overwritten. We
could even implement the checks in the views API.

**Comment by mrclay** [comment]
Oh, like some modules can only be decorated, but not overridden.

**Comment by hypeJunction** [comment]
Yep, it makes sense for modules that return objects. Just decorate the
return value of the required module.
For prototypes/constructors,  we can later add a way to extend the class
with custom methods.

**Comment by hypeJunction** [comment]
So, I have looked at JSDoc and PHPDoc tags and I think we could use `@final` for views to indicate that views should not be extended and/or overwritten. For now, we could just mention in docs that views marked `@final` are excluded from BC policy and are meant for internal use (though they do provide public APIs for consumption hence not sure we can use `@access` here). Later on we could teach the view system to parse the docs to decide whether extensions/overrides are allowed.
JSDoc does not have the `@final` tag yet, but it has been accepted for consideration, so they may add it eventually.

**Comment by hypeJunction** [comment]
Another idea is to create a new directory `_internal` and put all the views we don't want extended/overwritten (AMD modules, deprecated views etc) in there and map view locations.

**Comment by mrclay** [comment]
I think usage of an internal view should look obvious, so I'd be in favor of having `_internal/` (or `_elgg/`) in the names. I think we should wait for 3.0 to move existing views in there; just prepend them with a prominent warning header.

**Comment by mrclay** [comment]
elgg.js is a special case to consider. We don't want overrides, but we do support extending it, and I think we will in 3.0.

**Comment by jdalsem** [comment]
I disagree on the plan to exlude our AMD modules from being backwards compatible. They are just as important as views that you need to be able to rely on.

**Comment by hypeJunction** [comment]
That's exactly the point. We can't effectively refactor code knowing that someone may have overridden or extended the AMD module view.

**Comment by mrclay** [comment]
I changed the title to reflect the general need to mark some views as final.

**Comment by jdalsem** [comment]
> That's exactly the point. We can't effectively refactor code knowing that someone may have overridden or extended the AMD module view.

but we also can not refactor views effectively... don't see why we should exclude the AMD modules for that. I do not think marking views/modules as final will help with this. If it is impossible to be BC, it will just need to go in a major release.

**Comment by hypeJunction** [comment]
> If it is impossible to be BC, it will just need to go in a major release.

Not if it's documented. If we have a convention that makes it clear that certain views should not be touched, then it's up to plugin devs to deal with workarounds.

**Comment by jdalsem** [comment]
The power of Elgg is in the fact you can override various parts of the system (internal or not). If you need to override certain views (even if they are meant as internal) you should still be allowed to do so. Devs should be aware of the usage of the views and need to determine themselves if it is 'save' to override. There will never be a conclusive list of 'internal' views as there always could be the need to override (even if we do not know the usecase yet). Organizing the views in a specific namespace (folder structure) seems way more work for not that much work.

If we run into problems with specific 'important' views, we maybe should just add a note on top of the view file stating it is dangerous to override the view.
