### ISSUE TITLE
elgg/Ajax and race-conditions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9569]
I was able to finally pinpoint what bothers me about `elgg/Ajax`. I don't like the fact that `fetch()` returns a `jqXHR` object - it puts us in the same position as `elgg.ajax`, where we do not know where the handler sequence ends, so we can not reliably trigger a success event/hook, or use something like #8319. The dumb thing about jQuery ajax promises is that there is no way to reorder handlers, they are run in the same order they have been attached to `$.ajax()`

I think `fetch()` should return an instance of self (`this`). We add all the promise methods to `elgg/Ajax` for BC (though I wouldn't worry about it at all).

```js
// plugin
var Ajax = require('elgg/Ajax');
var ajax = new Ajax();
var handler = function() {};
ajax.path('/path').done(handler);

// elgg/Ajax
var that = this;
that.handlers = [];
that.jqXHR = $.ajax(options).then(unwrap_data).done(that.dom_ready);
that.attachDoneHandler = function(handler) {
    that.handlers.push(handler);
};
that.done = that.attachDoneHandler;

that.dom_ready() {
   // call all plugin handlers from that.handlers

   var booted = require('elgg/booted'); // rewrite booted to use closure 
   booted.boot();
}
```

**Comment by mrclay** [comment]
Re: race conditions with hooks, elgg/Ajax should depend on elgg/init. Done!

I'm not sure I follow the other concern. fetch should probably return the more limited promise object instead of the full jqXHR.

I don't see what returning self gives us. Can you give a use case?

**Comment by hypeJunction** [comment]
So, we have `boot/ckeditor` module from #8319:

```js
define(function (require) {
	var $ = require('jquery');
	var Plugin = require('elgg/Plugin');
 
 	return new Plugin({
 		addBehavior: function (context) {
 			$longtexts = $('.elgg-input-longtext:not([data-cke-init])', context);
 			if ($longtexts.length) {
 				require(['elgg/ckeditor'], function(elggCKEditor) {
 					$longtexts
 						.attr('data-cke-init', true)
 						.ckeditor(elggCKEditor.init, elggCKEditor.config);
 				});
 			}
 		}
 	});
 });
```

Ideally, we should be able to reuse this module whenever DOM has been manipulated.

Let's say we have a plugin X that loads a form that contains a longtext input:

```js
define(function(require) {
   var Ajax = require('elgg/Ajax');
   var ajax = new Ajax();
   
   ajax.form('my/form').done(function(markup) {
      $(body).append($(markup));
   });
});
```

We need to call the booted module after the form has been appended to body. Currently we can't do anything from within `elgg/Ajax` to signal that the DOM has been manipulated nor that all handlers have been called.

If we kept `jqXHR` reference as an internal variable in `elgg/Ajax`, we could attach handlers to it, so instead of chaining the above `$.done()` call, we would store in handlers and run in manually in our own `$.done()` handler. We could then either trigger a hook informing the plugins that all handlers for an Ajax request have been completed, or reuse `elgg/booted` module to attach behaviors to the altered DOM.

**Comment by mrclay** [comment]
I think I get it. We're going to start sending back lists of AMD modules to require, but if elgg/Ajax requires them too early, the elements won't be in the DOM. I kinda figured your existing pattern of inline scripts would be the most reliable way to deal with that, or users would manually call attachBehaviors like they do in Drupal.

One concern I have is that if elgg/Ajax depends on elgg/init, then boot plugins can't depend on elgg/Ajax (would create circular dep). But I could make fetch `require(['elgg/init'], ...)`. So boot plugins could get the Ajax reference, but not use it until after boot.

**Comment by mrclay** [comment]
```js
ajax.form('my/form').done(function(markup) {
  var $markup = $(markup);
  $(body).append($markup);
  ajax.attachBehaviors($markup);
});
```

**Comment by hypeJunction** [comment]
Right, what I am talking about here is the exact opposite of what I was trying to do earlier with making `elgg/Ajax` wait for `require()` to complete. Inline `<script>` works, but it is only until you have so many of them on a page (e.g. would look like a total mess with menu items).

Your last example is what I am talking about. I was thinking `elgg/Ajax` could attach behaviors magically on each request, but after thinking about it I think your approach makes more sense.

We don't need to reuse `elgg/booted`, it was just an illustration. We can add a function to `elgg/Ajax` that does the same without all the boot-time logic, i.e. just attaching behaviours to altered DOM.

We should also take into consideration how this is going to work with the lightbox module (and legacy Ajax API), where requests will be handled without `elgg/Ajax`. Once we convert lightbox to AMD, we can attach a handler to its success event, and will need a way to instantiate `elgg/Ajax` and/or attach behaviours.

**Comment by mrclay** [comment]
If we add formal behaviors, I think attachBehaviors() would be on elgg/init, where we already have access to the Plugins. In elgg/Ajax, attachBehaviors() would `require(['elgg/init'], ...)` to avoid circular dep.

**Comment by hypeJunction** [comment]
I guess I am overthinking this. As long as we can easily attach behaviors to DOM content, there is nothing to worry about.
