### ISSUE TITLE
ElggComment::canComment() should be hookable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9573]
`ElggComment::canComment()` and subsequently `ElggDiscussionReply::canComment` return `false` without trigger a hook. IMO should still trigger a hook with default `false`. I have implemented threaded discussion using comments on discussion replies, and this was one of the reasons I had to overwrite the class entirely.

**Comment by mrclay** [comment]
Yep. Delete ElggComment::canComment, and ElggEntity::canComment should cast to int.

**Comment by juho-jaakkola** [comment]
The classes were made like this because there wasn't time to implement threading in core, and we were afraid that plugin devs would make their own thread implementations that would then be incompatible with the future core implementation.

The feature probably isn't coming to core any time soon, so I'm fine with just giving more freedom to plugin devs.

**Comment by beck24** [comment]
I think it should be left for plugins to determine anyway.  Too many different ways of doing things, wouldn't want to pigeon-hole us into a FB single reply thread vs Reddit style infinite-child-replies behaviour or something in between.  Available hooks keep it open for all possibilities depending on context, leave it simple and extendable.

**Comment by hypeJunction** [comment]
I am thinking of adding $default as second argument in canComment and pass it to the hook

**Comment by jdalsem** [comment]
could we, as you are working on it, also introduce a reserved metadata_field for entities to store if `canComment` (would help fixing #4903), or should we leave that, as i mentioned it in the other ticket to hooks... if so we can close #4903

**Comment by jdalsem** [comment]
going to leave this as is. A plugin dev can easiliy extend the comments class to change this behaviour.

If we would change this right now in Elgg we would need to solve various things in the capabilities logic of our entities. Currently the `canComment` right will always allow true for admins, however the functionality might not be supported on a give entity (like the comments).

Changing the current canComment to `default = false` will cause issues. This requires rework that is not going to be tracked in this ticket but in tickets like: #4888 or #7462
