### ISSUE TITLE
How to handle embeds?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9582]
#9572 breaks our embed logic, mainly because our embed logic is flawed in that it relies on URLs to never change.

Strawman 1. Manually set icon/download URLs to use old handlers until we figure out a solution
Strawman 2. We can allow non-expiring URLs in file service (either by setting very high expiration time, or no expiration time; removing the last updated check for certain URLs)
Strawman 3. Use regex callbacks to replace URLs with dynamic equivalents

- [ ] Add ``serve-icon`` handler once #9655 is merged

**Comment by hypeJunction** [comment]
PR for Strawman 2: #9583

**Comment by mrclay** [comment]
Perpetual access to a file despite its access level has its use cases but I think is a bad idea for embeds, which embed real site entities. It's annoying when users break posts by hiding embedded images, but it's sometimes necessary. So I'm strongly in favor of 1 for now.

**Comment by mrclay** [comment]
Strawman 4: new embed URL handler like the old behavior: URL just has GUID. Server verifies visibility and sends expiration of a week, with Cache-Control: private.

**Comment by hypeJunction** [comment]
Strawman 1 will generate deprecation notices for old and new embeds.
Strawman 4 would have to go into core - we want posts to display properly even with embed plugin disabled. We can repurpose `DownloadFileHandler` (`EmbedFileHandler`, `embed-file`) add the `$size` parameter, boot core and trigger a hook, which will return `ElggFile` to serve.

**Comment by hypeJunction** [comment]
It makes me regret we abandoned ECML.

**Comment by hypeJunction** [comment]
If we go down route 4, I would prefer we make it work with all entity types. We could use something like a web component, which resolves a `<a href="embed/$guid?embed">$title</a>` to embed markup client-side, using a hookable Ajax request.

**Comment by mrclay** [comment]
Can you find our last discussion about ECML?

**Comment by hypeJunction** [comment]
https://github.com/Elgg/Elgg/issues/7375

**Comment by hypeJunction** [comment]
oEmbed could be an option here, but I find it weird to combine oEmbed with access controlled content. We would have to share cookies etc.

**Comment by mrclay** [comment]
Wouldn't oEmbed still cost a request that boots the server?

**Comment by hypeJunction** [comment]
It would. ECML is an ideal solution, and has proven to work with BB codes all over the internet, so I would be in favor of reviving it and making proper use of it. Or we could implement ECML 2.0 as a web component that parses a certain tag (`<a> seems most suitable) and replaces markup server-side. The pitfall is that user won't see actual embedded content in WYSIWYG (unless we teach it to display it and then strip it before sending to server), e.g. add `<iframe>`, hide `<a>`, strip `<iframe>` when saving.

**Comment by mrclay** [comment]
I think your never-expiring URL is the most sane option, but we should give content owners more control and information about the consequences of doing this. I mean, a user could always save a content-controlled image and re-upload it on the site or elsewhere.

**Comment by hypeJunction** [comment]
And next time we change something in URL structures, we are back at square one.

**Comment by hypeJunction** [comment]
Strawman 5: Use generic `embed/$file_guid/$size` pattern with `route:rewrite` hook.

**Comment by mrclay** [comment]
:+1: for (5)

**Comment by hypeJunction** [comment]
We would have to boot the engine for 5, but we do it anyway.

**Comment by hypeJunction** [comment]
Also how do we avoid sniffing the context in `file_set_icon_url()`? Should we add a hook to `embed` plugin to do the sniffing and rewriting thumb URLs?

**Comment by mrclay** [comment]
I'm not too familiar with this process, but sounds reasonable.

**Comment by hypeJunction** [comment]
Embed item view calls `elgg_view_entity_icon()`, when user clicks on the item, JS code parses out the img URL and embeds it into the editor. We can't explicitly set entity icon URL (I think), so we have to use `entity:icon:url` hook.

**Comment by hypeJunction** [comment]
PR for Strawman 5 - #9603
