### ISSUE TITLE
Install instructions for installation with composer incomplete?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9595]
The symlinks in mod are not created when doing just the "composer create-project" command as described in the docs. The post-install-cmd script seems not get triggered. Only when doing a "composer install" afterwards the symlinks are created.

Should the script already be executed on "composer create-project", i.e. bug, or would the docs need to be updated to also demand the "composer install" to be done?

**Comment by beck24** [comment]
I think the docs need to be updated to include the 'composer install' step
