### ISSUE TITLE
Should we support "plugin" settings for composer project?

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9597]
Currently the root directory of composer project works like a plugin; You can add for example `views/` directory or `start.php` to it, and they will work as they would work within a plugin.

It currently isn't however possible to define plugin settings from the root, because all the features depend on `plugin_id`.

See for example:
- https://github.com/Elgg/Elgg/blob/2.1/views/default/admin/plugin_settings.php#L19
- https://github.com/Elgg/Elgg/blob/2.1/engine/lib/admin.php#L455

Should we add support for plugin settings and plugin user settings for composer projects?

**Comment by mrclay** [comment]
:-1: I think we'd have to give it an ElggPlugin entity, introducing all sorts of issues.

**Comment by mrclay** [comment]
For now docs should make clear this code isn't a plugin. In fact I think its views override all others but its  start.php may be called first. This feature was not deeply considered.

**Comment by beck24** [comment]
I'm not sure I would even use this feature TBH

**Comment by mrclay** [comment]
I'd be in favor of deprecating it while it's still rarely used (getting feedback from community first). It's hackily implemented and I think is bound to cause confusion for devs learning how to make plugins. AFAIK the one novelty is its start.php can't be disabled.

**Comment by juho-jaakkola** [comment]
Linking to the community discussion: https://elgg.org/discussion/view/2479690/for-those-installing-via-starter-projectelgg-as-a-dependency

**Comment by jdalsem** [comment]
Closing this as i think the discussed features should not be how the composer project should be used.
