### ISSUE TITLE
System cache is broken on 2.1.1

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9602]
Not yet sure what exactly is happening...

**Comment by juho-jaakkola** [comment]
Ok, I'm not able to reproduce in other 2.1 environment. It's probably something site specific.

**Comment by juho-jaakkola** [comment]
This might be a bug after all.

I had set dataroot to `$CONFIG->dataroot` property in `settings.php`, and the `dataroot` setting in the database had an outdated path.

It seems that in some cases `dataroot` gets read from the database instead of `settings.php` causing an error if the value is not a valid.

**Comment by juho-jaakkola** [comment]
The problem started when I upgraded the site from 2.0 to 2.1. Apparently something has been changed in between.

**Comment by mrclay** [comment]
Does it affect all requests? The big change is the migration of boot stuff into BootService.

**Comment by juho-jaakkola** [comment]
Haven't had the time to debug properly, but no, doesn't affect all requests.

**Comment by mrclay** [comment]
Fix in #9605
