### ISSUE TITLE
Add composer script to generate a plugin skeleton

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9604]
The skeleton would live somewhere like /install/plugin_template and get copied into /mod (with some changes based on a given plugin_id), optionally altering the project .gitignore so it gets added to the repo.

Ideally one option would cause it to get ordered at the end when plugin priorities are first set.

cc @juho-jaakkola

**Comment by hypeJunction** [comment]
It would be cool to use Yeoman, so that we can kick start a plugin any time anywhere.

**Comment by jdalsem** [comment]
Not going to put in effort into this at this moment

**Comment by physcocode** [comment]
I would love to see this feature and I would love to work on a pull request for this
@jdalsem if you think this is still suitable for elgg please reopen this issue and ill work on a PR
