### ISSUE TITLE
File thumbnails sent with wrong Content-Type

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9612]
Currently file thumbnails are generated as `jpeg`, but the thumbnail file extension and Content-Type sent is inherited from the source file.

The correct Content-Type is sent in 2.x (serve-file analyzes the file), but previous versions including 2.1 always send the original file's Content-Type.

We also should change the thumb file extensions to `jpg` for consistency, and in case the file is served elsewhere.

- [ ] wait for #9608 to be merged

**Comment by mrclay** [comment]
Currently we're just lucky our MIME detectors are reading the file header, because the serve-file handler has no knowledge of the original file.

**Comment by mrclay** [comment]
Is there risk 3rd party thumbs are relying on thumb extensions matching the original extension?

**Comment by mrclay** [comment]
See the new title and desc on this ticket.

**Comment by mrclay** [comment]
Browsers just assume wrong image types are sent all the time and fix it, but we should fix this in 1.12. I'm working on this now.

**Comment by mrclay** [comment]
When we re-upload (edit) a file, we keep the old filename (!?). And if the new file isn't an image, we leave the old thumbs in place (!?).

**Comment by hypeJunction** [comment]
I have an open ticket for that somewhere

**Comment by hypeJunction** [comment]
Can't find it. The bigger problem is that we allow reuploads with different mime and keep the old filename!

**Comment by mrclay** [comment]
PR #9615
