### ISSUE TITLE
Elgg is too fast ;)

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9630]
So, I have upgraded a site to latest and greatest, and it seems that all the performance improvements we have done lately scare the server. The loading time is so fast that the server is choking on concurrent requests, running out of child processes.

Thoughts and experiences?

**Comment by hypeJunction** [comment]
It's a shared hosting maxed out on child processes. Currently, upgrading to a dedicated server is not an option.

**Comment by mrclay** [comment]
have you symlinked your simplecache directory? http://learn.elgg.org/en/2.0/admin/performance.html#simplecache

**Comment by mrclay** [comment]
Community likely has more expertise
