### ISSUE TITLE
2.2 release

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9631]
While excited about it, I am starting to get worried about 2.2 release. We are packing in a lot of new features. I wonder if we should set a freeze date and make a pre-release to get more feedback from the wild.

**Comment by mrclay** [comment]
Definitely

**Comment by jdalsem** [comment]
We could keep the current date set in the milestone as the freeze date... and release RC's the weeks after

**Comment by hypeJunction** [comment]
There is a consensus, so will just close the issue.
