### ISSUE TITLE
Core Plugins don't start  

### ISSUE THREAD

**Issue by hamidos** [Elgg/Elgg#9634]
in the Dashboard i have this messages : 
blog (guid: 3) cannot start and has been deactivated. Reason: Cannot include start.php for plugin blog (guid: 3) at /var/www/html/starter-project/mod/blog.

messageboard (guid: 23) cannot start and has been deactivated. Reason: Cannot include start.php for plugin messageboard (guid: 23) at /var/www/html/starter-project/mod/messageboard.

messages (guid: 24) cannot start and has been deactivated. Reason: Cannot include start.php for plugin messages (guid: 24) at /var/www/html/starter-project/mod/messages.

notifications (guid: 25) cannot start and has been deactivated. Reason: Cannot include start.php for plugin notifications (guid: 25) at /var/www/html/starter-project/mod/notifications.

pages (guid: 26) cannot start and has been deactivated. Reason: Cannot include start.php for plugin pages (guid: 26) at /var/www/html/starter-project/mod/pages.

profile (guid: 27) cannot start and has been deactivated. Reason: Cannot include start.php for plugin profile (guid: 27) at /var/www/html/starter-project/mod/profile.

reportedcontent (guid: 28) cannot start and has been deactivated. Reason: Cannot include start.php for plugin reportedcontent (guid: 28) at /var/www/html/starter-project/mod/reportedcontent.

search (guid: 29) cannot start and has been deactivated. Reason: Cannot include start.php for plugin search (guid: 29) at /var/www/html/starter-project/mod/search.

thewire (guid: 32) cannot start and has been deactivated. Reason: Cannot include start.php for plugin thewire (guid: 32) at /var/www/html/starter-project/mod/thewire.

uservalidationbyemail (guid: 34) cannot start and has been deactivated. Reason: Cannot include start.php for plugin uservalidationbyemail (guid: 34) at /var/www/html/starter-project/mod/uservalidationbyemail.

**Comment by damieneskimo** [comment]
Hi hamidos How did you solve this problem. It occurred me too when I installed a fresh elgg 2.2

**Comment by hamidos** [comment]
For me it has been  a problem in linux files permissions. Try to change it.

**Comment by beck24** [comment]
That's almost always the case for this

**Comment by damieneskimo** [comment]
Right on. Being solved! Thank you
