### ISSUE TITLE
Symlinking cache

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9637]
I am not sure if I am going crazy or the idea of symlinking /cache to /dataroot/views_simplecache has no merit. Simplecache views are written to dataroot by `CacheHandler` on first request. The symlink would only work if you already have all files in cache, simplecache would need to be regenerated automatically for all cacheable views for the symlink to work.

**Comment by hypeJunction** [comment]
An alternative approach: #9638

**Comment by mrclay** [comment]
I think you didn't try it ;)

**Comment by mrclay** [comment]
If a file is missing, the root `index.php` handles the request and writes it.

**Comment by hypeJunction** [comment]
Using command line, this doesn't always work. I suppose there are group/ownership problem somewhere. Any reason we are not doing this automatically? We added the FollowSymlinks to .htaccess, that was the motivation?

**Comment by mrclay** [comment]
We considered trying to add the symlink automatically, seems not worth the effort to really get it right.
