### ISSUE TITLE
Convention for documenting views

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9641]
Language keys "view_title:the/view/name" and "view_desc:the/view/name".

Description would allow learning about views in the inspector, but title helps components that often need a user-facing label to go with a view. E.g. the input views:

"view_title:input/email" => "Email address"

Of course, you often need different titles in different contexts...

**Comment by jdalsem** [comment]
Related #4590

**Comment by jdalsem** [comment]
We also could get the description out of the comments in the view file (if available). Don't think it is needed to add all this extra stuff (that would be hardly used) to language files.

**Comment by jdalsem** [comment]
Not going to do this. Descriptions are mostly present in the files. Showing them in the inspector is maybe nice to have, but i do not see devs doing that.
