### ISSUE TITLE
Virtual memory usage profiling

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9658]
I feel like we have a memory leak somewhere. Two sites are munching through virtual memory. Where would be the most appropriate place to log stats?

**Comment by mrclay** [comment]
Do you mean requests are ending without returning all memory (PHP/httpd leak), or Elgg is just using more memory?

**Comment by hypeJunction** [comment]
Elgg uses more memory. There are two major changes that could have lead to this: serve-file or boot time cache. A page load with 20 icons eats up 1gb.

**Comment by mrclay** [comment]
You mean the HTML request eats 1GB?

**Comment by hypeJunction** [comment]
Well, that's the problem, I don't know where the problem is. Server peeps blame it on Elgg. When you hit a page with many icons and static assets, memory spikes to over 1Gb and some requests never complete.

**Comment by hypeJunction** [comment]
I looked at the stats again. It seems that now and then the site is being hammered by requests, hence high memory usage. I will monitor it for a bit. It's possible that the spikes also happen when notifications are being sent out.
