### ISSUE TITLE
Make large icon square & upscale by default

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9663]
I have encountered a problem with the `large` icon logic.
The config indicates not square, do not upscale. The avatar crop action, passes large icon through `get_resized_image_*` with cropping coordinates, which makes it a square, however if the cropping box is less than 200px, we end up not upscaling it, so if the cropping box was 20x20, we have a large icon that is 20x20.

**Comment by hypeJunction** [comment]
See https://github.com/hypeJunction/Elgg/blob/icon-service/engine/tests/phpunit/Elgg/EntityIconServiceTest.php#L821

**Comment by hypeJunction** [comment]
I personally dislike large icons being rectangular and always modify the config to make them square. I propose for the sake of consistency we make them square and upscale them. Or stop cropping them.

**Comment by mrclay** [comment]
If the user crops to a tiny 20x20, what's the problem is serving a 20x20 image? Seems like we shouldn't resize any images *up* and rely on clients to do that.

**Comment by mrclay** [comment]
...and set a minimum crop size if that's a worry.

**Comment by hypeJunction** [comment]
I will only spend time on it, if we going to upscale. I refuse to work with images that are inconsistent in their dimensions.

**Comment by juho-jaakkola** [comment]
Changing the icon shapes will cause trouble when upgrading sites, but I agree that in the long run it is better to be consistent. I vote that we make all of them square and upscale them if necessary.
