### ISSUE TITLE
elgg_echo (or \Elgg\I18n\Translator->translate) should report warning on incorrect $message_key

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9673]
There is no validation on $message_key, this can cause php warnings

- check for non string (can cause "Illegal offset type in isset or empty" warnings)
- validate str_len > 0

see: https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/I18n/Translator.php#L40

**Comment by mrclay** [comment]
As long as we're still logging an error. Don't fail silently.

**Comment by jeabakker** [comment]
closed with #10247
