### ISSUE TITLE
Update policy to always require tests

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9681]
Lately not many pull requests contain tests. I feel we are regressing in some areas. I propose that we require tests for any changes to the API.

**Comment by jdalsem** [comment]
i agree, but i also think more attention should go into creating tests for the existing API as our coverage is very low atm

**Comment by hypeJunction** [comment]
I don't think you would purposefully go and study the API to write a test. More natural is to write a test while you are fixing a bug/writing the API, as at that point you have a better understanding of what's happening in the code, what assertions you need to make.

**Comment by hypeJunction** [comment]
I think we are in a good shape
