### ISSUE TITLE
Catalog JS cleanup efforts for 3.0

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9701]
The conversion to AMD in 2.x is creating a lot of code we'll want to make sure to remove for 3.0.
- [x] delete ui.widgets.js, don't inline elgg/widgets.js; require in page/layouts/widgets
- [x] remove explicit name from elgg/widget, add elgg/ready as dependency
- [x] don't inline jquery.colorbox.js
- [x] delete lightbox.js, lightbox/settings.js, and the check for elgg.ui.lightbox.deprecated_settings
- [x] remove lightbox/settings.js cruft from elgg.js
- [x] delete initialise_elgg.js (can do this anytime)
- [x] delete elgg.ui.popupClose
- [x] delete ui.river.js
- [x] delete jQuery.cookie (?)
- [x] delete elgg.ui.initDatePicker
- [x] if #9684 merged: delete elgg.embed, elgg/ckeditor/insert
- [x] if #10153 merged: ...see that PR

**Comment by mrclay** [comment]
It seem like a prominent TODO file *in the repo* would be helpful. The reason is that sometimes PRs add todos, which may not always make it to the GitHub issues. And really, few people are going to go hunting for `@todo` and `TODO` statements in the code because they're often aspirational, instead of concrete steps to take.

**Comment by mrclay** [comment]
...and because it's too easy to close/alter GitHub issues without actually accomplishing the task. In the repo, only a merged PR can remove an item from the repo's TODO list.

**Comment by hypeJunction** [comment]
We could add each task as a github issue and reference the original discussion.

**Comment by mrclay** [comment]
Yeah, we really should not be putting any `TODO`s in source code. I guess worst case I'm imagining is an issue created alongside a PR and the PR gets rejected or altered significantly. Probably too rare to worry about.

**Comment by mrclay** [comment]
`elgg/ckeditor/config` can't be removed yet, must get deprecated first.

**Comment by mrclay** [comment]
PR #10155 handles must of this

**Comment by jdalsem** [comment]
All cleanup todos have been taken care of
