### ISSUE TITLE
No way to remove a usersettings view

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9704]
I want to get rid of user settings for a certain plugin. If I overwrite the view with an empty string, it still renders the form without the body.
I quite dislike our user settings magic. We need to reconsider our approach.

**Comment by hypeJunction** [comment]
I propose we stop outputting empty form markup from `elgg_view_form ()`. Can we consider it a bugfix, or would somebody be relying on having empty forms without any fields and buttons?

**Comment by beck24** [comment]
I can't imagine a scenario where someone would rely on that.  This has annoyed me also.

**Comment by mrclay** [comment]
Better to fix this in 2.x by adding an option to the input/form view.
```php
$allow_empty = elgg_extract('allow_empty', $vars, true);
```

**Comment by jdalsem** [comment]
shouldn't it be default false to be BC?

**Comment by mrclay** [comment]
Maybe "allow_empty_body" would be clearer? This is the default behavior, so default true.

If false, then we `return` if `$body` is empty.

**Comment by jdalsem** [comment]
> Maybe "allow_empty_body" would be clearer

clearer indeed

This however makes it a feature and it means we can not fix it (having empty forms) in core... until 3.x

**Comment by mrclay** [comment]
Having it default to current behavior allows adding in 2.x.

**Comment by mrclay** [comment]
The fix would also involve:
- change view resources/settings/tools to set the option to false.
- change view form/plugins/settings/save to return if no settings. I think that's acceptable for 2.x

**Comment by jdalsem** [comment]
@hypeJunction why was this reopened?? i lost track

**Comment by hypeJunction** [comment]
I have no idea. I think we reverted the changes in core

**Comment by jdalsem** [comment]
Should be fixed by #11011
