### ISSUE TITLE
_elgg_view_may_be_altered does not catch if view is used AS an extension

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9705]
Only checks if it's extended by another view.

**Comment by hypeJunction** [comment]
Does it matter for our deprecation strategy? I don't think it does.

**Comment by mrclay** [comment]
If we deprecate old.css and a plugin inlines it into elgg.css, we need to know don't we?

**Comment by mrclay** [comment]
OK that case probably doesn't matter. If it uses the view in an extension, the deprecation notice will be sent, and it probably doesn't matter if they haven't modified the view.
