### ISSUE TITLE
braindump: auto echo a <formname>_footer view for forms

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9706]
Currently in the forms we echo the save buttons and some hidden inputs most of the time in a div with the class `foot`. This way we have no good way to extend the forms with additional fields before the save/submit buttons. Therefore in some forms we add special (sometimes non-existing) views to extend (like in the register form). What if we make all forms automatically append a magic view in elgg_view_form that adds the footer part, and wraps it in the `foot` div. That way all forms are better extendable (and in a generic way) and we could drop the undocumented special extension views...

So `elgg_view_form` will firstly output the normal form `forms/<form_name>` and then append 
`elgg_format_element('div', ['class' => 'elgg-foot'], elgg_view('forms/<form_name>_footer'))`

**Comment by hypeJunction** [comment]
Yes, I was just thinking about that as well.

```php
echo elgg_view_form('my/form', [], [
  'fields' => [
      [
         'input' => 'file',
         'name' => 'icon',
      ],
  ], // can be filtered by view_vars
  'controls' => [
    [
       'input' => 'submit',
       'value' => elgg_echo('reply'),
    ],
    [
       'input' => 'button',
       'type' => 'reset',
       'value' => elgg_echo('cancel'),
    ]
]);
```

```php

// in elgg_view_form()

$body = elgg_view('forms/my/form', []);
foreach ($fields as $field) {
   $body .= elgg_view_input($field['input'], $field);
}

$body = elgg_format_element('div', ['class' => 'elgg-body'], $body);

$footer = '';
foreach ($contols as $control) {
    $footer .= elgg_view_input($control['input'], $control);
}

$footer = elgg_format_element('div', ['class' => 'elgg-foot elgg-buttonbank'], $controls);
```

**Comment by jdalsem** [comment]
Yeah, moving it into a parameter for elgg_View_form is also an option... but only support for controls (as input) is maybe a bit limited... but if we do:

```php
$footer = elgg_extract('footer', $body_vars, '');
foreach ($contols as $control) {
    $footer .= elgg_view_input($control['input'], $control);
}

$footer = elgg_format_element('div', ['class' => 'elgg-foot elgg-buttonbank'], $controls);
```
we have ultimate flexibility

**Comment by hypeJunction** [comment]
I am trying out your idea in a new plugin and I like it.

**Comment by hypeJunction** [comment]
See #9939 for an alternative approach

**Comment by jdalsem** [comment]
Fixed by https://github.com/Elgg/Elgg/pull/10137
