### ISSUE TITLE
Early access features

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9711]
In a minor release we often wish to add a user-facing feature, but not force site owners to enable it until the next major release. It would be nice to have an API to register and use options that become always-on after the next release.

```php
if (_elgg_wants_feature('register_form_3.0')) { ... }
```

In 2.x that shows up as an option in admin > early access, but in 3.0 it's just always on.

Alternative to this, of course, is just adding a plugin. But that leads to an ongoing growth of plugins.

**Comment by hypeJunction** [comment]
We could use magic view. If `elgg_view_exists('register_form_3.0)`. Sites can add an empty view and enable the feature.

**Comment by mrclay** [comment]
Check out #9713

**Comment by jdalsem** [comment]
Not going for a feature in core to add early access features.
