### ISSUE TITLE
Create tests for view existence

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9714]
To avoid things like #9690, we could write tests to verify view existence for all views present at 2.0 release. Shouldn't be a problem to dump the register and use it as dataProvider. The only question is plugin views. We probably need to enable all bundled plugins for tests (should be worth it to catch other issues as well)

**Comment by mrclay** [comment]
FYI we don't need to start plugins to pull in the views.

**Comment by jdalsem** [comment]
Fixed in #11326
