### ISSUE TITLE
Limiting number of river items shown per page working as intended?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9715]
In elgg_list_river there's this line:
```php
'limit'      => (int) max(get_input('limit', max(20, elgg_get_config('default_limit'))), 0),
```
resulting in a MINIMUM limit of 20 even if default_limit is smaller. Is this really the intended behaviour?

**Comment by mrclay** [comment]
Behavior was intended (mentioned in the commit), but rationale was thin. I didn't want to have 2 separate settings, but in hindsight a separate setting for the river would make sense.

**Comment by iionly** [comment]
Okay, I see. I've just noticed that less than 20 has no effect when thinking about giving an easy suggestion for https://elgg.org/discussion/view/2483969/how-do-you-limit-the-number-of-activity-river-items-to-6. I've never had used the default_limit setting before.

When looking at the line of code setting the limit in elgg_list_river() I thought that the original idea might have been to use 20 as a fallback in case default_limit is undefined or maybe set an upper limit in case default_limit is very large. If default_limit can be set up to a value of 5000, couldn't this cause memory issues? Even if not introducing a second separate setting would it make sense to display some explanation about a value of less than 20 might not having an effect? Also, mentioning the risk of memory issues (in case such a risk might exist) might be worth mentioning in such an explanation.

**Comment by mrclay** [comment]
> If default_limit can be set up to a value of 5000, couldn't this cause memory issues?

That number was chosen fairly arbitrarily. Feel free to add help language to the basic settings page.

**Comment by mrclay** [comment]
...But I don't think it's generally worth worrying about.

**Comment by jdalsem** [comment]
As the limit is intended to be 20 i think the question asked in this issue is resolved. Setting the default limit to 5000 is just a bad idea... but you can find that out by trying.

**Comment by mrclay** [comment]
FYI I answered the community question :) https://elgg.org/discussion/view/2483969/how-do-you-limit-the-number-of-activity-river-items-to-6#elgg-object-2484851
