### ISSUE TITLE
Revert #9717 and consider implementing a more BC way

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9720]
https://github.com/Elgg/Elgg/pull/9717#issuecomment-211408035

**Comment by jdalsem** [comment]
What BC issue are you think of? The fact that if you were assuming there was an empty form element somewhere on the page you use?

Maybe i was a bit enthusiastic about the fix :smile:

**Comment by mrclay** [comment]
Consider using `elgg_view_form()` to generate an empty token-ready form for further generation client-side or via hooks.

Or if you were extending the forms/plugins/settings/save view, you'd no longer get a save button.

These are probably not likely, but "a few devs think this probably won't affect you" isn't a good BC policy.

**Comment by jdalsem** [comment]
This brings back memories of this discussion https://elgg.org/discussion/view/1592243/semver-and-views?offset=10# where was discussed if html output is part of the BC policy...

The stance that we can not change output (outputting nothing is also just changing the output) will halt all development... i can list a number of changes that all modified the html output in a way that could be considered *BREAKING* to a few other developers...

**Comment by mrclay** [comment]
> where was discussed if html output is part of the BC policy

I added a ticket to add this policy to docs.

In the case of #9717, it **completely removes** all output if the input isn't what we expect. Considering we can *easily* do this in a BC way, we should.

**Comment by mrclay** [comment]
Reverted in 06eba739fb8833712cb0c25fc32894543c406ea7
