### ISSUE TITLE
Revert #9700 or require a plugin to enable it

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9721]
I agree with @hypeJunction we probably don't want to roll this out by default in a minor.

**Comment by hypeJunction** [comment]
Let's finish refactoring embed/ckeditor amd modules. It will make it easier to add a plugin setting to ckeditor plugin

**Comment by hypeJunction** [comment]
I have had a chance to see this live while working on ckeditor refactor, and it does feel like a UX-gain, and it doesn't seem as intrusive as I thought it would be. So, if we can live with a slight performance hit, I am fine with it.
