### ISSUE TITLE
Add agreed on views BC policy to docs

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9722]
https://elgg.org/discussion/view/1592243/semver-and-views?offset=10#elgg-object-1675579
1. View names are API.
2. View arguments ($vars array) are API.
3. Removing views or renaming views follows API deprecation policies.
4. Adding new views requires a minor version change.
5. View output is not API and can be changed between patch releases.

**Comment by jdalsem** [comment]
Maybe we should document more about the BC policy than just about the views.. there is nothing related to BC policy to be found in the docs
