### ISSUE TITLE
FR: lazy generated icons

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9729]
Currently with the new icon service we generate all thumbnail sizes based on elgg_get_icon_sizes when the image is uploaded.

This is an issue in some cases:
- If, after upload, a new icon size is added (for example in a new theme)
- If an icon size is never used

What if we only upload the master image and when a thumbnail is required, but is not yet available, and the size is present in elgg_get_icon_sizes, we generate it on demand? That will fix both issues mentioned above.

**Comment by hypeJunction** [comment]
I want to roll in an image manipulation library first. I am not sure we shoudl aupport tgat in core, but either way `entity:icon:file` hook could be used to geenerate missing sizes.

**Comment by jdalsem** [comment]
Why wouldn't you support lazy generated thumbnails in core? The benefits are obvious and generic IMO.

**Comment by hypeJunction** [comment]
If that's the route, then I would stop generating icons and generate them on first request - that would happen when you generate a URL, doesn't seem like a suitable place. Additionally, the core api doesn't keep the original file, so you would have to adapt the api, or generate from master.

**Comment by jdalsem** [comment]
> If that's the route, then I would stop generating icons and generate them on first request

That is my thought



> that would happen when you generate a URL

it would happen when you fetch the URL, not generate it



> keep the original file / or generate from master

Yep, that is what is needed

**Comment by hypeJunction** [comment]
We use file urls to serve existing files without booting the engine. We can't really easily change that at this point.
