### ISSUE TITLE
Consider reverting "Discussions" site menu item

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9731]
A "Discussions" menu item has been added to the site menu in `2.2-dev`. It broke the layout of a site when I upgraded from `2.1` to `2.2-dev` because now site menu requires more space.

Perhaps we should revert adding it.

I would guess that sites in need of the menu item have already added it through a plugin in `2.1`. If not, they probably don't want to have it in `2.2` either.

**Comment by mrclay** [comment]
PR #10111
