### ISSUE TITLE
3.0: Remove pagesetup handlers

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9733]
We probably should not remove these in 2.x for safer BC.

- [x] users_pagesetup
- [x] profile_pagesetup
- [x] _elgg_friends_page_setup
- [x] _elgg_setup_collections_menu
- [x] _elgg_user_settings_menu_setup
- [x] developers_setup_menu
- [x] groups_setup_sidebar_menus
- [x] notifications_plugin_pagesetup
- [x] _elgg_admin_pagesetup
- [x] aalborg_theme_pagesetup
- [ ] login_as_add_topbar_link in login as plugin

Rel #9727, #8374

**Comment by jeabakker** [comment]
pagesetup removed with #10434
