### ISSUE TITLE
ElggEntity::canEditMetadata should check if metadata belongs to entity

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9738]
Our current API allows any metadata permissions to be checked via an unrelated entity. We should fix that situation by checking if metadata's entity is same as the entity whose method is being called.

**Comment by hypeJunction** [comment]
Metadata no longer has permissions.

**Comment by jdalsem** [comment]
i believe this issue was not related to permission, but rather to checking canEditMetadata on metadata objects against unrelated entities...

**Comment by hypeJunction** [comment]
It was related to capabilities service, but the method is deprecated already.
