### ISSUE TITLE
AutoloadManager cache racing conditions

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9744]
We encountered a severe performance issue on a production site which we traced back to the AutoloadManager cache.

Some context
Elgg 2.0.3
Concurrent users: +/- 300
Webservers: 2

The problem
the file /system_cache/autoload_data.php gets overwritten by each request.

Reason
Not all classes are present in the cache file.
On page X a new class is added => save cache
On page Y a new class is added => save cache
This is fine, but if the request of page Y didn't include the the class of page X the new cache doesnt include that class, so if page X is requested again => save cache.

Do this for 300 concurrent users, and you've got problems ;)

We disabled the saving of the cache and the performance of the webserver went from +/- 800-1500ms to +/- 400-500ms.

How can we fix this problem???

**Comment by hypeJunction** [comment]
I think I might have encountered a similar problem, but I couldn't tell for sure.

**Comment by mrclay** [comment]
I don't know that an exclusive lock while writing would completely solve the problem. We need an ACID insert strategy or at least abort write if the file is less than a couple seconds old or an existing lock is encountered.

**Comment by mrclay** [comment]
We should first test this on an install not under load. Maybe there's a logic problem causing writes on every request.

**Comment by mrclay** [comment]
See #9749

**Comment by mrclay** [comment]
I noticed that twitter_api was calling elgg_register_class() on every request (which should be OK) and it was unnecessarily invalidating the class map cache.

**Comment by jeabakker** [comment]
with #9749 in mind, another edge case to think about
plugin X registers class A on path A
plugin Y registers class A on path B

path B ends up in the cache (this is ok), but on the next request the cache will be invalidated (path A != path B, so register and invalidate. Then path B != path A and this ends up in the cache)

**Comment by hypeJunction** [comment]
It feels like we should just outsource class loading to composer.

**Comment by jeabakker** [comment]
> It feels like we should just outsource class loading to composer.

how would that handle classes from plugins without composer support?

**Comment by hypeJunction** [comment]
I forget that those still exist...

**Comment by mrclay** [comment]
Composer also doesn't know which plugins are active, which matters.

> plugin X registers class A on path A; plugin Y registers class A on path B

elgg_register_class() calls are rare; we could just record them and issue a warning if one redefines another. Really we should deprecate all these:

- elgg_register_class
- elgg_register_classes
- elgg_get_class_loader

...and teach devs how to use composer for libs that can't be dropped in /classes.

**Comment by mrclay** [comment]
> Composer also doesn't know which plugins are active

If mod/example/vendor/autoload.php exists, the plugin load could auto-require it...

**Comment by hypeJunction** [comment]
> If mod/example/vendor/autoload.php exists, the plugin load could auto-require it...

https://github.com/Elgg/Elgg/issues/8829

**Comment by mrclay** [comment]
Fixed by https://github.com/Elgg/Elgg/commit/18ea55fa990fab9724cbbd12365d754df19cbde2
