### ISSUE TITLE
Remove autoloading API functions

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9753]
- elgg_register_class
- elgg_register_classes
- elgg_get_class_loader

Plugins can place PSR-0 classes in /classes, or use composer for autoloading and `require __DIR__ . '/vendor/autoload.php';` in their start.php

**Comment by hypeJunction** [comment]
Related
https://github.com/Elgg/Elgg/issues/8829
https://github.com/Elgg/Elgg/issues/9006
