### ISSUE TITLE
Incorrect HTTP status code when db has gone away

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9758]
When for some reason the connection to the database could not be established you get a generic error page with the HTTP status code 200 OK.

This should be something out of the 5xx range. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error

at least there should be a status code 500 here
https://github.com/Elgg/Elgg/blob/1.12/engine/lib/elgglib.php#L852

but why don't i get the errors as defined here
https://github.com/Elgg/Elgg/blob/2.0/engine/classes/Elgg/Database.php#L171-L179

Using Elgg 2.0.3
steps to reproduce:
- change you db username to a non-existing username (eg. add 'xxx')

**Comment by mrclay** [comment]
PR #9760
