### ISSUE TITLE
Admins can't search for user by settings email/username

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9761]
If an admin search query contains "@", we should return first the user with that email in account settings.

The users returned should display the account email alongside. Currently search will return several users with _similar_ addresses, basically false positives you have to weed through by digging into their settings.

Username searches are also spotty. A search for "steveattac" will not return user "steveattack" or "steveattack2". 😢 

Placing this search in the admin probably would make sense as a site can have search disabled, or you want direct LIKE-type matches, not fulltext/solr fuzziness.

**Comment by jdalsem** [comment]
Duplicate / related to #4855
