### ISSUE TITLE
upgrade.php should complain if it can't remove cache directories

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9763]
Motivation: #9645

**Comment by mrclay** [comment]
If the system can't remove every cache directory, should the upgrade continue? If it fails spectacularly, any collected error messages may not be displayed. I suppose we could halt and display messages on `/upgrade.php`, but allow manually continuing to `/upgrade.php?upgrade=update`.

**Comment by jdalsem** [comment]
if it can't remove cache folder you will have way more issues than just the upgrade.php... not going to provide some check in upgrade
