### ISSUE TITLE
Spinner text type validation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9769]
I occasionally see [object Object] under my spinners. 
Refs #8979

**Comment by mrclay** [comment]
I'm guessing beforeSend passes in the XMLHttpRequest.

**Comment by mrclay** [comment]
We can either silently ignore non-strings in the first argument, or wrap our elgg/Ajax beforeSend handler in an anon function.

**Comment by hypeJunction** [comment]
Oe require that object with key spinner_text is passed as an argument.

**Comment by mrclay** [comment]
Our docs plainly recommend `beforeSend: spinner.start,` so I think we just have to ignore non-strings.

**Comment by hypeJunction** [comment]
@jdalsem Will you have time to fix?

**Comment by mrclay** [comment]
PR #9809
