### ISSUE TITLE
change label of the branch for elgg 2.x to be 'current' or 'latest', rather than 'stable'.

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9770]
as per our conversation in the community here: https://elgg.org/discussion/view/2487569/i-think-that-calling-elgg-2x-the-stable-release-and-112x-the-lts-release-is-misleading?offset=10#

steve concurred that it would be best to rename the branch for elgg 2.x away from 'stable' and to something like 'current' or 'latest' since really the more stable branch is 1.12.x. this is in line with other OS projects that use the LTS and STS approach, such as ubuntu.

**Comment by jdalsem** [comment]
Do you know of the specific locations where these references to various releases are mentioned?

**Comment by jdalsem** [comment]
Closing this for now. I am personally not convinced that 'stable' is a bad name for the branch. Elgg has 2 stable branches. One or the other is not per se more (or less) stable than the other. If you have locations in the docs that could benefit from an improved description of a branch please submit a PR to fix the docs.
