### ISSUE TITLE
PHP WARNING: "Argument 2 passed to elgg_extract() must be of the type array, null given

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#9772]
While doing my monthly error log review, I noted that a particular warning was appearing again and again i.e., PHP WARNING: "Argument 2 passed to elgg_extract() must be of the type array, null given, called in /path/to/engine/lib/comments.php on line 284 and defined" in file /path/to/engine/lib/elgglib.php (line 1256)

I saw that there is a check that if the $returnvalue parameter is not an array then it will not allow us to proceed. But what if the array was empty/null? The above PHP warning is generated if a blank or null array is passed. I know this is only a warning but I thought that it would be nice to get this fixed using the below code:

```
if (!is_array($returnvalue) || $returnvalue == null || $returnvalue == "" ) {
	// another hook handler returned a non-array, let's not override it
	return;
}
```
Rest its up to the core team to decide.

**Comment by iionly** [comment]
What version of Elgg are you using?

A similar (the same?) issue has been reported in https://github.com/Elgg/Elgg/issues/8333. It has been fixed in Elgg 1.11.3 (and should also no longer occur on Elgg versions newer than 1.11.3). Elgg versions older than 1.12 don't get any bugfixes anymore at the present time though.

**Comment by rohit1290** [comment]
I am using Elgg 1.12

**Comment by rohit1290** [comment]
Yes, I have seen that issue and the fix was to check that it was an array. But what if a blank array is passed. it will bypass the check as it is an array but still generated the warning as it's a null or blank array.

**Comment by beck24** [comment]
Are you sure an empty array generates that message?  I don't think that's correct, I think it means something is passing a literal NULL, not array()

**Comment by rohit1290** [comment]
if it was a null, then it wud have get filtered out in d current check where null is not an array.

i did a negative testing by creating a blank array and saw that it was bypassing the current check defined in the function. And that is why i came up with the solution that it should also check for null/blank array.

**Comment by hypeJunction** [comment]
PR #9775. It has nothing to do with `elgg_extract()` rather the hook not validating the values properly.

**Comment by rohit1290** [comment]
I have been monitoring my error log for the past 12 hours and the said PHP warning has stop appearing in my error log. hypeJunction solution did the magic.
