### ISSUE TITLE
Allow page handlers/actions to return response arrays.

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9773]
E.g. action success:
```php
return [
  "content" => $data_array,
];
// "status_code" defaults to 200
// "forward_url" defaults to REFERER
// "headers" defaults to []
```
If ajax request, JSON wrapper is sent with content. Page request just gets 307 redirect.

E.g. action failure
```php
return [
  "status_code" => ELGG_HTTP_BAD_REQUEST,
  "forward_url" => $group->getURL(),
];
```

E.g. page handler redirecting
```php
return [
  "forward_url" => $group->getURL(),
];
```

I think in practice we could offer convenience functions/methods to build common array forms.

Other ideas for keys: success_msg, error_msg (instead of system_message/register_error calls)

@hypeJunction has started on this in https://github.com/Elgg/Elgg/pull/9768/files#diff-15c1859e1402cc4d335194bb2d919b56R127.

**Comment by mrclay** [comment]
forward() currently fires hooks. Would "forward_url" do the same? Would a "forward_reason" have to be set? Will those hooks do "safe" operations. E.g. if they call a forward() or send output, what happens?

For ajax requests, should a `register_error()` call make the default status_code 400 or 500?

For the safest BC, I don't think we should apply this logic unless an array is returned. Converting most actions would be converting `forward()` calls.

Returning objects would make it easier for us to give a nicer interface:
```php
return elgg_build_response()
    ->setBadMethodCall()
    ->redirectTo($url);
```
If a ResponseBuilder is returned, we just call toArray() on it...

**Comment by hypeJunction** [comment]
I think we should try and devise an API without using forward and forward hooks. Plugins can piggyback the response array before we send a response. We can keep the old way intact until we feel confident we can part with it.

I don't like the idea of setting a status code when an error is registered. 

I would prefer injecting response builder into response factory methods instead.

Are you planning to work on this? I can tackle some of it next week now that I grasp your stance on things.  Other feedback would also be valuable.

**Comment by hypeJunction** [comment]
See #9779

**Comment by hypeJunction** [comment]
@mrclay Anything left on this one?
