### ISSUE TITLE
NotificationService Call to undefined method ElggRelationship::getContainerGUID() in \engine\classes\Elgg\Notifications\SubscriptionsService.php on line 66

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9780]
The NotificationService can handle all events based of ```\ElggData```, however the ```SubscriptionService``` assumes it's getting an ```\ElggEntity```

This causes a crash if you (for example) use an ```\ElggRelationship```

I'll provide a little more info as i do some more research

**Comment by jeabakker** [comment]
in https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/Notifications/SubscriptionsService.php#L52

current
```php
public function getSubscriptions(\Elgg\Notifications\Event $event) {

	$subscriptions = array();

	if (!$this->methods) {
		return $subscriptions;
	}

	$object = $event->getObject();
	if (!$object) {
		return $subscriptions;
	}

	$prefixLength = strlen(self::RELATIONSHIP_PREFIX);
	$records = $this->getSubscriptionRecords($object->getContainerGUID());
	foreach ($records as $record) {
		$deliveryMethods = explode(',', $record->methods);
		$subscriptions[$record->guid] = substr_replace($deliveryMethods, '', 0, $prefixLength);
	}

	$params = array('event' => $event);
	return _elgg_services()->hooks->trigger('get', 'subscriptions', $params, $subscriptions);
}
```

change to:
```php
public function getSubscriptions(\Elgg\Notifications\Event $event) {

	$subscriptions = array();

	if (!$this->methods) {
		return $subscriptions;
	}

	$object = $event->getObject();
	if (!$object) {
		return $subscriptions;
	}

        if ($object instanceof \ElggEntity) {
		$prefixLength = strlen(self::RELATIONSHIP_PREFIX);
		$records = $this->getSubscriptionRecords($object->getContainerGUID());
		foreach ($records as $record) {
			$deliveryMethods = explode(',', $record->methods);
			$subscriptions[$record->guid] = substr_replace($deliveryMethods, '', 0, $prefixLength);
		}
	}

	$params = array('event' => $event);
	return _elgg_services()->hooks->trigger('get', 'subscriptions', $params, $subscriptions);
}
```

**Comment by jeabakker** [comment]
and in the site_notifications plugin
https://github.com/Elgg/Elgg/blob/2.x/mod/site_notifications/classes/SiteNotificationFactory.php#L14

current:
```php
if ($object) {
	// TODO Add support for setting an URL for a notification about a new relationship
	switch ($object->getType()) {
		case 'annotation':
			// Annotations do not have an URL so we use the entity URL
			$note->setURL($object->getEntity()->getURL());
			break;
		default:
			$note->setURL($object->getURL());
	}
}
```

change to:
```php
if ($object) {
	// TODO Add support for setting an URL for a notification about a new relationship
	switch ($object->getType()) {
		case 'annotation':
			// Annotations do not have an URL so we use the entity URL
			$note->setURL($object->getEntity()->getURL());
			break;
		case 'relationship':
			// relationships do not have an URL so we use the entity URL of guid_two
			$entity = get_entity($object->guid_two);
			$note->setURL($entity->getURL());
			break;
		default:
			$note->setURL($object->getURL());
	}
}
```

**Comment by juho-jaakkola** [comment]
Annotations are easy but with relationships it isn't possible to know whether `guid_one` or `guid_two` should be used as the target entity. At some point I was thinking about adding a hook that plugins could use to let the notifications system know their preference.

**Comment by juho-jaakkola** [comment]
Unfortunately I don't remember the use cases where the direction of the relationship was unclear.

**Comment by jeabakker** [comment]
> Annotations are easy but with relationships it isn't possible to know whether guid_one or guid_two should be used as the target entity.

Agreed, but I checked core and for instance for "user x is now a friend of Y" it would work, as User X is the 'actor' and friend Y is the subject.

**Comment by mrclay** [comment]
It seems a bad idea to assume direction. Creating a way to configure it by relationship name seems best.

**Comment by jeabakker** [comment]
> It seems a bad idea to assume direction. Creating a way to configure it by relationship name seems best.

\ElggRelationship already triggers a plugin hook to get the URL for the relationship, so need need to add anything for it

**Comment by hypeJunction** [comment]
Fixed in https://github.com/Elgg/Elgg/pull/10139
