### ISSUE TITLE
Action names need a sanity check

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9793]
Given action names are used within URLs we need to implement name sanity checks. 
The following tests all fail:

```php
/**
* @dataProvider invalidActionNamesDataProvider
*/
public function testCanCheckActionNamesForSanity($name) {
	$this->assertFalse($this->actions->register($name, "$this->actionsDir/output.php", 'public'));
}

public function invalidActionNamesDataProvider() {
	return [
		['http://test/test'],
		['test//test'],
		['!test'],
		['test*'],
		['test%'],
		['test(.*).php'],
		['test/test.php'],
		['test.jpg'],
		['test[]'],
	];
}
```

**Comment by beck24** [comment]
why do they need sanity checking?  Is there some auto-generated actions from user input?

**Comment by hypeJunction** [comment]
Help devs avoid something crazy from happening, when they pass action names to `elgg_normalize_url()`, getting strange results when thing get trimmed/decoded etc.

**Comment by beck24** [comment]
I'm still not sure I follow as to why this is necessary - but why limit it to actions then?

**Comment by hypeJunction** [comment]
Do we want this? Or we happy with whatever we have now?

**Comment by mrclay** [comment]
Reopen if becomes essential.
