### ISSUE TITLE
Cacheable view served via /ajax/view

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9794]
We currently allow any simple cache view to be served via /ajax page handler, which includes images etc. I am not sure this was the intended behavior - as far as I can understand we wanted to have a BC way to serve only JS/CSS views, but after the big simplecache refactor we are sending everything and with wrong headers.

**Comment by hypeJunction** [comment]
See https://github.com/Elgg/Elgg/pull/9779/files#diff-c9257dc929d8d917d787a940d731a4faR1585

**Comment by mrclay** [comment]
Your fix seems reasonable. As long as elgg/Ajax responses are always served with JSON content type.

**Comment by mrclay** [comment]
I'm sure your bigger Q is should we allow it. I don't know.

**Comment by hypeJunction** [comment]
I am fine either way. I just think it would be odd to serve raw image bytes for example with elgg/Ajax having no clue what the content type is in `value`

**Comment by hypeJunction** [comment]
Not a blocker for 3.0

**Comment by jdalsem** [comment]
This has long been fixed in https://github.com/Elgg/Elgg/commit/bfc860c81622350e3c8f7fe7863b18aeaeab34c9

We currently allow it and send the correct content type
