### ISSUE TITLE
/ajax/view should check if view exists

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9795]
We only check if view is cacheable or allowed, but we don't check if it exists.

**Comment by mrclay** [comment]
I can think of one (probably rare) use case: a plugin registers for ajax a view solely meant to be extended by other plugins, but none do.

**Comment by mrclay** [comment]
Does current behavior log a warning about missing view. I'd leave it at that (don't HTTP error), at least in 2.x

**Comment by hypeJunction** [comment]
Not critical. Nothing is logged, just serves empty string with 200.
