### ISSUE TITLE
Router::route() should bail if page handler is not callable

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9796]
We currently rely on `\Elgg\Application::run()` to redirect to an error page if no output was detected from `\Elgg\Router::route()`. It would perhaps make sense to render and serve a 404 page from the `Router::route()`

**Comment by mrclay** [comment]
I think a 500 is more appropriate. We don't have enough info to assume anything else.

**Comment by hypeJunction** [comment]
This would be a user facing change. Current behavior: forward to 404 if headers not sent.

**Comment by hypeJunction** [comment]
Not an issue anymore.
