### ISSUE TITLE
elgg/Ajax handling of cacheable views

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9797]
Not sure how logical it is to wrap requests to `/ajax/view` in Ajax 2 wrapper for cacheable views. 

Related https://github.com/Elgg/Elgg/issues/9794

**Comment by mrclay** [comment]
Legacy/raw use of $.get still get direct view output, so what's the issue? The point of elgg/Ajax is a consistent transport system with piggybacking of other data.

**Comment by hypeJunction** [comment]
Everything should be wrapped. Dealing with cacheable views served via `/ajax` is a different issue.
