### ISSUE TITLE
discussions tab in groups listing handled in incorrect plugin

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9806]
should be handled by the discussions plugin not the groups plugin

https://github.com/Elgg/Elgg/blob/2.x/mod/groups/views/default/resources/groups/all.php#L23-L38

**Comment by jdalsem** [comment]
Fixed in https://github.com/Elgg/Elgg/commit/c6de14c2f974f85147b06bc0f085fcc492c6bed2
