### ISSUE TITLE
elgg_view_input() needs exceptions

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9808]
Needs to add exceptions for:

- [x] `input/checkbox` - customize label rendering

**Comment by brettp** [comment]
What does this mean?

**Comment by hypeJunction** [comment]
If we use `elgg_view_input()` with type `checkbox` we end up with weird markup:
label on top, then just a checkbox without any label.

**Comment by hypeJunction** [comment]
The fix is almost ready.

**Comment by hypeJunction** [comment]
Done as part of #9892

![single](https://cloud.githubusercontent.com/assets/1202761/16008431/44855748-3178-11e6-9871-a8bf8b78621c.png)
