### ISSUE TITLE
fxp/composer-asset-plugin breaks after composer update

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#9816]
So as I understand old version of `fxp/composer-asset-plugin` relied on old composer api and as a result it breaks with something like (sorry for broken encoding):

```
$ composer global update fxp/composer-asset-plugin
←[32mChanged current directory to C:/Users/Pawel/AppData/Roaming/Compos
er←[39m

←[37;41m
       ←[39;49m
←[37;41m  [ReflectionException]
       ←[39;49m
←[37;41m  Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does
not e  ←[39;49m
←[37;41m  xist
       ←[39;49m
←[37;41m
       ←[39;49m

←[37;41m
       ←[39;49m
←[37;41m  [ErrorException]
       ←[39;49m
←[37;41m  Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAs
setsR  ←[39;49m
←[37;41m  epository::whatProvides() should be compatible with Composer\
Repos  ←[39;49m
←[37;41m  itory\ComposerRepository::whatProvides(Composer\DependencyRes
olver  ←[39;49m
←[37;41m  \Pool $pool, $name, $bypassFilters = false)
       ←[39;49m
←[37;41m
       ←[39;49m

←[32mglobal ←[39m←[32m<command-name>←[39m←[32m [←[39m←[32m<args>←[39m←[
32m]...←[39m
```

See also https://github.com/francoispluchino/composer-asset-plugin/issues/214

In docs we seem to have listed old version: http://learn.elgg.org/en/2.0/intro/install.html#upload-elgg

Perhaps we should bump it to something newer (current latest is 1.1.4, we have 1.1.1 in docs), however it's tricky. Composer will break unless you run it with `--no-plugins` parameter. So ie. I ran: `composer global update fxp/composer-asset-plugin --no-plugins` to mitigate the problem.

Putting that in docs might be useful as well.

**Comment by jeabakker** [comment]
closed in #11019
