### ISSUE TITLE
Cannot open reported content link in new tab, lightbox is broken.

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#9817]
Cmd / Ctrl + clicking on the reported content does not open it in a new tab. Instead, it opens a broken lightbox. The lightbox is broken in normal operation, too. (Chrome, Mac OS)

![screen shot 2016-05-16 at 9 42 44 am](https://cloud.githubusercontent.com/assets/43375/15291193/aeb4a018-1b4a-11e6-9e10-d9a6ba2cb482.png)

**Comment by iionly** [comment]
Maybe already fixed: https://github.com/Elgg/Elgg/pull/9670 (at least the "broken in normal operation" part). I think there hasn't been made a new release since this PR was merged.

**Comment by mrclay** [comment]
Yeah, I need to kick a release out. 2.1 branch doesn't have this issue.
