### ISSUE TITLE
Add a plugin zipped from admin interface

### ISSUE THREAD

**Issue by danelsan** [Elgg/Elgg#9820]
I can add a plugin from a zip file or from a remote url with administrator user?

**Comment by mrclay** [comment]
Some developers have discussed making a plugin to do this. Core developers are generally preferring to install plugins via composer.json.

**Comment by danelsan** [comment]
Not very friendly.. sorry

**Comment by mrclay** [comment]
Try https://github.com/Srokap/srokap_plugin_installer

**Comment by danelsan** [comment]
Thanks,  plug-in good for core also .
