### ISSUE TITLE
Install with composer problem

### ISSUE THREAD

**Issue by danelsan** [Elgg/Elgg#9821]
I read the docs for installation with composer but errors occurs.

composer self-update

  [InvalidArgumentException]             
  Command "self-update" is not defined.  

Maybe is the version of composer?

Thanks

**Comment by jdalsem** [comment]
self-update should work...

https://getcomposer.org/doc/03-cli.md#self-update

**Comment by danelsan** [comment]
I installed again composer, thanks.

**Comment by jdalsem** [comment]
is it working now?

**Comment by danelsan** [comment]
Now working but I read
http://learn.elgg.org/en/2.0/intro/install.html

I'd like to install with git for a developper use.

**Comment by danelsan** [comment]
Sorry, when i run 

**composer create-project elgg/starter-project:dev-master .**

You can also add it manually later by using "composer config github-oauth.github.com <token>"
Reading bower.json of bower-asset/jquery (2.0.0)
Could not fetch https://api.github.com/repos/jquery/jquery-dist/contents/bower.json?ref=a55c5eeb709b584f58a1f3d8d0bc9f1432cd998a, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ubuntu+2016-05-19+1344
to retrieve a token. It will be stored in "/home/daniele/.composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by juho-jaakkola** [comment]
Go get the token from the URL and paste it to the command line.

**Comment by danelsan** [comment]
Where is the token?

**Comment by hypeJunction** [comment]
Follow the URL and click Generate token.
Closing as non-issue. Please ask for further assistance in the community.
