### ISSUE TITLE
email notifications are not sent in recipient's language

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9834]
1. interact with a use of an elgg site that supports multiple languages - whose language is different to yours. e.g. add them as a friend and have them accept the friend connection.
2. the email notification that is sent in response to the interaction is often sent in the language of the other person.

emails need to always be in the language of the recipient.

**Comment by hypeJunction** [comment]
Core notifications are localized to the recipient's language: https://github.com/Elgg/Elgg/blob/2.x/engine/lib/friends.php#L206

You probably use a plugin that hijacks the notifications, i.e. friend_request

**Comment by propertunist** [comment]
oh ok - actually i saw the problem on socialbusinessworld.org, not my own site - but yes, they probably have friend request installed. i did see this same problem on my own site years ago when testing with different languages, so thought it still existed in core. i'll close this issue and pass it on to friend requests then.
