### ISSUE TITLE
Password reset fails if admin changes the account email

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9837]
I'm 60% sure this happened to the account https://elgg.org/profile/jonn. Need to test locally.

**Comment by jdalsem** [comment]
Tested the following:
- user X requests password recover (forgot password) and receives mail
- admin changes emailadress of user X
- user X can still use link provided in password recovery mail

If you thought that was the scenario that was causing trouble, it isn't. Reopen if i did not get the right scenario
