### ISSUE TITLE
Overwrite htaccess.dist in local project

### ISSUE THREAD

**Issue by Wouter0100** [Elgg/Elgg#9839]
Currently, we're having issues with our `.htaccess`. This because it is overwritten every time we run `composer install` when deploying to a test/live server.  

I think we should be able to overwrite the `install/config/htaccess.dist` in the vendor, by defining the same path in our starter-project. So adjust the `copyFromElggToRoot` method in the `PostInstall` to first check it's path to the project itself, and then within Elgg.

I'll look into this in some days, but for now, happy to hear any feedback on this. @jopknoppers?

**Comment by hypeJunction** [comment]
The first question I have is why do you use `composer install` more than once?

**Comment by Wouter0100** [comment]
To update the local environment to the dependencies versions defined in the `composer.lock`. See [this](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file) article (when fast forwarding, go to 'deployment').

**Comment by hypeJunction** [comment]
Can you list the flow step by step?

**Comment by Wouter0100** [comment]
I'm not sure what step by step flow you'd like to see, but: we don't run `composer update` on our test/live server. Only on our local machines. After running `composer update` we making sure all dependencies still work as intended, then we push the generated `composer.lock` to the repo. On this way, we have the exact same dependencies (with the exact same versions) on the test and live server when updating those.

**Comment by hypeJunction** [comment]
Ok, got it. IMO, the `PostInstall` should just check if `.htaccess` exists and bail.

**Comment by Wouter0100** [comment]
That's also a solution :+1:

**Comment by Wouter0100** [comment]
PR is open
