### ISSUE TITLE
Double line in en.php

### ISSUE THREAD

**Issue by KitsuneSolar** [Elgg/Elgg#9848]
Hello, I found bug and has decided make a correction.
https://github.com/Elgg/Elgg/pull/9847

I deleted that line, because it is repeated: 
https://github.com/Elgg/Elgg/blob/2.x/mod/messages/languages/en.php#L12-L18

Line 12 & 18.

I did right thing?

**Comment by mrclay** [comment]
Yes, but follow the instructions we've given you at the bottom of #9847.
