### ISSUE TITLE
User time_created not reliable value for "join date"

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9850]
As brought up [in the community](https://elgg.org/discussion/view/2503378/user-creation-timestamp), the date of user entity creation can be misleading when account validation is delayed. Particularly, ~~the new user river item will have the wrong date and~~ the new user/member listings will not be in the right order.

The simplest fix would be to update ~~river.posted and/or~~ entities.time_created upon validation. It's a little weird to have an entity own metadata and other things that are older than itself, but not a big deal.

This kind of also applies to systems/admins that manually create accounts that get logged into later, but not as common an issue.

**Comment by jdalsem** [comment]
uh... isn't the user site join event a Profile Manager plugin only event???

**Comment by jdalsem** [comment]
i mean a river item created by Profile Manager???

**Comment by jdalsem** [comment]
https://github.com/ColdTrick/profile_manager/blob/master/classes/ColdTrick/ProfileManager/Sites.php#L19

**Comment by jdalsem** [comment]
And as in https://github.com/Elgg/Elgg/issues/9503 is stated this was not something core would like to see :)

**Comment by mrclay** [comment]
I forget what's in core sometimes! Yeah. Only real issue is order of new member listing. I'll update the description.

**Comment by jdalsem** [comment]
I think there should be another approach to solving the 'newest' members... See also https://github.com/Elgg/Elgg/issues/6156 where we discuss the need to list members based on the site relationship... time_created is the time the account is created, so that is correct, but what if we create the site relationship (member_of_site) on validation of the account? That way the members plugin could order by time_created of the relationship, so latest joins appear on top...

**Comment by rohit1290** [comment]
@jdalsem I have also mentioned this on the community. Suppose I registered on "D1-MM-YYYY" and I am validating my email ID after some days, say on "D2-MM-YYYY". So technically I am joining on "D2-MM-YYYY"

**Comment by rohit1290** [comment]
If I add the following two line at https://github.com/Elgg/Elgg/blob/master/mod/uservalidationbyemail/views/default/resources/uservalidationbyemail/confirm.php#L21 will it solve this issue?

```
$user->time_created = time();
$user->save();
```

**Comment by jdalsem** [comment]
@rohit1290 it will update the time_created to represent the date the user has been validated, but keep in mind, that there are multiple ways a user could be validated (for example the admin action).

For Elgg (in general) this would not be a good solution. Multiple plugins could validate/invalidate users... or never at all. Validation timestamps should probably be separate from time_created and should be created during a `'validate', 'user'` event

**Comment by jdalsem** [comment]
Probably profile manager could fix this, by adding the timestamp on first login... but then again... is 'First login' the same as 'Joined'? Think not... Time created is fine by me as a 'joined' date... only issue with that is it shows river activity for a disabled user... but that could be another issue (as that is also possible in other usecases).

**Comment by jdalsem** [comment]
this can be done later... not a blocker for the 3.0 beta release... like to still fix this for 3.0 though

**Comment by jdalsem** [comment]
With https://github.com/Elgg/Elgg/pull/13510/commits/04cc3395bd58df37954a5aaf2bd69cf28117ec4d there now is a consistent validation moment. Plugins can, for example, created 'User joined the site' once the account is validated. For a 'join date' you can now use `$user->validated_ts ?? $user->time_created`
