### ISSUE TITLE
Edit Profile Fields: Unexpected error while performing an AJAX call.

### ISSUE THREAD

**Issue by KitsuneSolar** [Elgg/Elgg#9856]
After rearrange any field, show warning:

> Unexpected error while performing an AJAX call. Maybe the connection to the server is lost.

[elggdiagnostic.txt](https://github.com/Elgg/Elgg/files/294631/elggdiagnostic.txt)

**Comment by mrclay** [comment]
The profile/fields/reorder action exits without sending any output. The newer jQuery version treats empty body as a parse error, which is technically true since elgg.action asks for JSON. Simple fix is to remove the `exit` call from the action.

**Comment by mrclay** [comment]
1.12 is not affected, so we need a patch for 2.1.

**Comment by mrclay** [comment]
Fixed by #9912
