### ISSUE TITLE
ElggUser should have a getLanguage function

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9857]
this is handy if you want to send notifications in the recipients language. You can not use elgg_get_language for that... also $recipient->language is unreliable, because theoretically that is null.

$user->getLanguage should first check $user->language, then fallback to $site->language

**Comment by hypeJunction** [comment]
On top of this we should probably stop setting user language on registration.

**Comment by mrclay** [comment]
Have a `$default = null` argument. If null, use site language, if given, return $default. Allows API user to recognize if the user *has* a language set.

**Comment by smellems** [comment]
`public function getLanguage($default = null) {
		if ($default != null) {
			return $default;
		}
		if $this->language != null {
			return $this->language;
		}
		return elgg_get_language();
	}`

**Comment by hypeJunction** [comment]
@smellems when posting code, you can use three tildes with language name.

```
```php

```
```

**Comment by hypeJunction** [comment]
You would return default if user language is not set.

**Comment by smellems** [comment]
if there is a default return that
if user->language return that
default to elgg_get_language

Should it be user first?

**Comment by jdalsem** [comment]
i do not see the need for a default....

elgg_get_language does not exist and get_language is not usable....

```php
public function getLanguage() {
        $result = 'en';
        
        if (!empty(elgg_get_config('language'))) {
            $result = elgg_get_config('language');
        }

        if (isset($this->language)) {
            $result = $this->language;
        }
        return $result;
}
```

**Comment by jdalsem** [comment]
or we could add $site->getLanguage() to be more consistent...
