### ISSUE TITLE
Custom selects with count option

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9871]
I don't know why, but we currently strip custom selects from ege\* options with `count` option. It has caused problems before, where you can't rely on calculations from custom selects for ordering, and is bound to cause problems when we go to fix https://github.com/Elgg/Elgg/issues/8121.

**Comment by mrclay** [comment]
With count = true, why do we need ordering?

**Comment by hypeJunction** [comment]
Sorry, bad example. 

I was working on a query that was casting a metastring timestamp into a date and then parsing out d/m/y parts for a complex comparison in `where` clauses. 
Last time I had this problem I was working on some math calculations on annotations.

Ultimately, the problem is that `elgg_list_entities()` results in a fatal error with any custom selected fields if they are used in `group by` or `where` clauses.

**Comment by hypeJunction** [comment]
#10060 makes a stronger casw for fixing this. I will write a query to demonstrate how it fails.

**Comment by mrclay** [comment]
So the SELECT clause is used to make a calculated column used in ORDER/GROUP BY. Is this something MySQL 5.7 has issues with as well? If so we may want to encourage using explicit calculations in ORDER/GROUP BY.

**Comment by hypeJunction** [comment]
One of the use case I remembered is getting entities by proximity to certain coordinates. The problem with explicit calculations is that they are extremely long, so SELECT makes most sense to calculate the distance, and then use selected distance value in WHERE and ORDER BY clauses.

**Comment by hypeJunction** [comment]
Here is an example: https://github.com/hypeJunction/hypeMaps/blob/master/classes/hypeJunction/Maps/ElggMapQuery.php#L114
So, I have to use SELECT to get the distance into volatile data, then I have to use the same calculate in the where clause. If you were to write a clause for a < distance < b, you would end up with two really long where clauses.

**Comment by hypeJunction** [comment]
Can be done with QB
