### ISSUE TITLE
get_uploaded_file() doesn't handle multiple file uploads

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#9876]
It assumes only one file is being uploaded.

**Comment by hypeJunction** [comment]
I have started work on an upload service and want to deprecate this function. 
What's your thinking?  How should it behave?  Return an array of contents ;)?

**Comment by brettp** [comment]
My quick fix was to just use the FileBag from request->files. It does
everything I need and is a familiar interface.

**Comment by hypeJunction** [comment]
Ok. I will keep multi upload in mind. My primary goal is to reduce boilerplate and standardize metadata stored with the file entity.

**Comment by hypeJunction** [comment]
See #9929
