### ISSUE TITLE
Error on posting a reply in a discussion

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9877]
This happens in discussion https://elgg.org/discussion/view/2506569/issue-when-you-try-to-report-a-profile only. Posting replies in other discussion threads works without problems. But when posting a reply in this one the reply is not added and I get the error

"The page you were using had expired. Please try again."

I am a member of this group and I'm logged in and the time was surely not long enough for the session to expire so I don't know what could cause the problem.

**Comment by mrclay** [comment]
The image_proxy/image.php script is regenerating the session ID (you'll see it sends Set-Cookie), therefore, the CSRF tokens already in the page fail. There are a couple solutions:

1. don't require tokens if the method is POST and the request Referer/Origin header matches the site's origin. There's no need for CSRF protection for these requests.
2. remove session ID from CSRF tokens (keep the unique key we already keep in the session). A regenerate ID would keep the key and hence not invalidate the tokens.

More immediate workaround: don't regenerate session ID in the image.php plugin file.

**Comment by jdalsem** [comment]
Closing this issue due to lack of progress... reopen if the issue still is present
