### ISSUE TITLE
Formalize using status messages in content

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9880]
There are cases where I want (colored) status messages in the page content, and which do not disappear or have a pointer cursor. I guess I want to be able to put `<p class="elgg-message elgg-state-notice">` into content without fear of behavior/positioning being broken by a plugin.

I guess I'm asking to move `cursor:pointer` out of `.elgg-message { }` and add some comments to discourage plugin devs from applying positioning/behavior based on this class.

**Comment by hypeJunction** [comment]
I think at this point it is easier to add a new class (e.g. `.elgg-message-box`)

**Comment by hypeJunction** [comment]
Actually aalborg has `.elgg-box`
