### ISSUE TITLE
Signed URLs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9884]
I am thinking about a way we could sign and validate URLs. Some use cases would include uservalidationbyemail, certain actions, confirmation links in notifications etc.

I am thinking we could add something like `elgg_sign_url()`, which would parse query parameters, remove `__elgg_ts` and `__elgg_token`, cast values to string, sort by key, and then add HMAC signature as `_elgg_mac` to the URL. `elgg_validate_url_signature()` would then validate query parameters of the given URL.

Thoughts?

**Comment by mrclay** [comment]
Yep, definitely considered it before, and it beats each feature implementing it separately.
