### ISSUE TITLE
elgg-icon-hover is added to some icons - resulting in them being the wrong colour when rendered

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9885]
some icons are outputted with the css class 'elgg-icon-hover' which results in them being a different colour to the others - with no obvious purpose or benefit to this. see here:
https://github.com/Elgg/Elgg/blob/2.x/views/default/output/icon.php

why is this being done?

**Comment by hypeJunction** [comment]
It was done for backward compatibility.

**Comment by propertunist** [comment]
in what sense?

**Comment by mrclay** [comment]
They had the "alternate" color in 1.x. See https://github.com/Elgg/Elgg/pull/8655

**Comment by mrclay** [comment]
I'd agree with changing all core uses to the "non-alt" versions in 3.0.

**Comment by propertunist** [comment]
i have just over-ridden the view in my theme. i think it would be best to remove the hover states at some point, since they 'break' the aesthetic of the current version as a way of attempting to not break the aesthetic of the old version... if i understand the situation correctly.. which i possibly don't. lol

**Comment by jdalsem** [comment]
fixed as part of #10452
