### ISSUE TITLE
Best practices for sticky values in password inputs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9895]
I am noticing that we persist password values through sticky values if forms fail server-side validation. I think we should not be feeding sticky password values back to forms.

**Comment by hypeJunction** [comment]
IMO, input/password should not even accept the value - those end up in the page markup as clear text.

**Comment by beck24** [comment]
I believe it's pretty standard to *not* populate password fields

**Comment by jdalsem** [comment]
so if we change input/password to not accept `$vars['value']` this is ok?

**Comment by beck24** [comment]
I believe so

**Comment by mrclay** [comment]
We should also unset keys `password` and `password2` when saving sticky forms.

**Comment by jdalsem** [comment]
why? input/password will just ignore the value... if someone would like to use them in from the sticky values, i think they should be able to...

**Comment by mrclay** [comment]
I mean `elgg_make_sticky_form` shouldn't store plaintext passwords in the DB session storage.

**Comment by jdalsem** [comment]
elgg_make_sticky_form does not know what is right/wrong... i could use a input/checkbox with the name password...

**Comment by mrclay** [comment]
Good point.
