### ISSUE TITLE
Getting 2.2 out the door

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9900]
It's about that time.

- [x] merge 2.1 into 2.x #9901
- [x] make an RC (this might be a manual process considering the limitations of elgg-starter-project.sh)
- [x] get the RC linked from elgg.org/downloads.php (also might take some work on Elgg/www.elgg.org

**Comment by mrclay** [comment]
How did you blog post as me? https://elgg.org/blog/view/2509074/elgg-220-rc1-is-released Hmmm

**Comment by hypeJunction** [comment]
Good question. I think I was on your blogs, copying the intro, then went to
your blogs via breadcrumbs and pressed Add blog post. So, I guess I used
you as container...

**Comment by mrclay** [comment]
https://github.com/Elgg/Elgg/issues/6186

**Comment by hypeJunction** [comment]
Are we going to make RC.2 or ship 2.2.0? We haven't had any issues reported, so I think we should be fine getting 2.2.0 out the door.
