### ISSUE TITLE
Improve release docs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9905]
- [x] Release workflow should mention how to setup `.transifexrc`
- [x] Make it more prominent that you need to `su deploy`
- [x] Tagging part - not sure how pushing tag to origin from temporary branch makes it available in upstream

**Comment by jdalsem** [comment]
@hypeJunction can you update the docs with the experience of the latest releases?

**Comment by jdalsem** [comment]
These docs are pretty up to date at this moment
