### ISSUE TITLE
maintenance mode clashes with nginx's directive for a custom 503 error page

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9907]
i have been unable to use maintenance mode for several years and today i found the cause.
nginx allows the definition of custom pages for each type of numeric page error (e.g. 404 and 503). if i assign a custom page for 503, when i turn on maintenance mode, i see the nginx 503 error page, instead of the elgg maintenance page. the sending of the header for 503 in the maintenance page triggers nginx and the rest of the elgg maintenance page is ignored.

as a workaround i have commented out the 503 header for the maintenance page by over-riding it in my site's theme. i'm not sure what the solution is, other than to just not have that 503 header used on the maintenance page. technically, the service IS available anyway - since the maintenance page is the desired (temporary) output of the service at the present time and also provides a login for those who can use it.

**Comment by jdalsem** [comment]
Status code 503 is the correct status code for server maintenance. If you have custom error pages or maybe even remove servers from the pool based on status codes this can be an issue. As a server admin you need to decide how you wish to handle this. If changing the status code works for you, then that is fine by me. Elgg will not change this default behaviour for the maintenance page.
