### ISSUE TITLE
groups/my_status appears to contain logical error (PHP7)

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9909]
while testing my site with PHP7 i found this curious issue. group profile pages now crash when the user is logged out. the error is
```
 Call to a member function getGUID() on null
 Error: Call to a member function getGUID() on null in /mysite/mod/group_tools/views/default/groups/sidebar/my_status.php:28
```
this was caused by the $user variable not being set at all in 'my_status.php' on that page because null was returned from: elgg_get_logged_in_user_entity().
however, this was intended to be handled by earlier logic on the page that says:
```
if (!empty($user)) {
	return true;
}
```
except this is backwards! the logic says that if there IS a user then return true, instead of if there isn't a user.
i haven't followed the code through far enough to know why this wasn't already an obvious bug, but anyway - when i removed the exclamation mark to make the logic end the function when there is no user, instead of when there IS a user - the group profile pages stopped crashing and functioned correctly:
```
if (!empty($user)) {
	return true;
}
```

**Comment by mrclay** [comment]
Is this a core issue? group_tools isn't core.

**Comment by propertunist** [comment]
oh, my mistake - i've been looking at code too long and thought it was groups ;)
