### ISSUE TITLE
Webservices: user can only have one auth token at a time

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#9916]
Use case for multiple auth tokens - a mobile app that may be connected to the same account on multiple devices.  Logging into the account on one device should not necessarily invalidate your auth token for other devices.

Currently the apisessions table is set up with a unique key on user guid and the default create_user_token function queries with an on duplicate update

`"INSERT into {$CONFIG->dbprefix}users_apisessions
                (user_guid, site_guid, token, expires) values
                ({$user->guid}, $site_guid, '$token', '$time')
                on duplicate key update token='$token', expires='$time'"`

**Comment by mailvishnuji** [comment]
I also faced this problem while coming through elgg 2.2

**Comment by jdalsem** [comment]
Only sites upgrade from 2.x still have a unique index on the ``user_guid`` column. This unique flag is no longer needed (and can be removed safely). Code allows to add multiple rows for the same user_guid.
