### ISSUE TITLE
Feature request: better / alternative way needed to register entity types for activity page filter

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#9918]
Currently the activity page filter gets populated by using registered entities. But the registered entities - registered for search in the first place - might not all make sense also to be included in the activity page filter. Also the other way round might be a use case, i.e. you need a specific type to be availaible in the activity page filter but not want it included in the site search. I have a need for both use cases and I currently have no idea how to implement them without changes necessary in Elgg core. But even then these changes in core might be rather site (plugins in use) specific and not really a good generic approach.

**Comment by mrclay** [comment]
The vague concept of "registered" type/subtypes should be replaced with specific features. E.g. add a $features argument to elgg_register_entity_type() so you can register for "search" or "type_filtering" directly.

**Comment by mrclay** [comment]
Short term several solutions: 

1. override the core/river/filter view to change $registered_entities.
2. before the rendering swap out the config values for registered_entities and swap them back after rendering. You can do this via view extensions, or using the view_vars and view hooks.

**Comment by hypeJunction** [comment]
See #10069

**Comment by hypeJunction** [comment]
Hook into view_vars for input/select and override options_values and selected value. The only change that's needed in core is resources/river shouldn't assume that type/subtype are text.
