### ISSUE TITLE
livesearch fails when a period symbol is included in the input

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9920]
i have been upgrading the mentions plugin for 2.1.x here (and tinymce_extended) and it is now working fine. in that process, i found that if i typed a period character into the mention search lookup (triggered by starting a word with the @ symbol) and the word included a period symbol, the search would hang and never return anything. looking through the code, i am not 100% sure exactly why this is a problem, but a solution i found is to encode periods into html entities before sending to livesearch via ajax. the only issue with this solution is that it requires a new line to be added to input_livesearch_page_handler() - to convert the encoded character back again:

```
    $q = html_entity_decode($q);
```

**Comment by mrclay** [comment]
If we go that route, `_elgg_html_decode()` should be used instead to avoid activating unsafe HTML.

**Comment by mrclay** [comment]
Hmm. I gave a user the name "@Foo.bar" and was able to search this fine in the user picker, so I'm not sure this is a core bug.

**Comment by propertunist** [comment]
i found it was a bit temperamental. i found thought that 100% of the time if a period is placed in the first 3 characters, the lookup would just get stuck on the 'loading' animation. the only way i got it to work is through my suggestion here.

**Comment by mrclay** [comment]
I renamed the user `@f.bar` and as I added each character the server returned 200s. Anything in your error log?

**Comment by propertunist** [comment]
nothing relevant in the logs that i recall.

**Comment by jdalsem** [comment]
Closing this as it is not reproducable
