### ISSUE TITLE
1.12: warn of missing ext/mysql for php 7 users

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9923]
Otherwise they get an obscure exception:
https://elgg.org/discussion/view/2514988/elgg-11211-with-php-7

**Comment by mrclay** [comment]
I don't know why this does catch it https://github.com/Elgg/Elgg/blob/1.12/engine/classes/ElggInstaller.php#L1045

**Comment by jdalsem** [comment]
Unable to reproduce this issue. Installer is checking the requirements. Doing an upgrade does not do the check. That needs to be done by the user him/herself.
