### ISSUE TITLE
User can receive multiple notifications for an object

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9926]
E.g. https://github.com/Elgg/mentions/issues/34.

cc @propertunist

**Comment by jdalsem** [comment]
If you have multiple triggers for the same entity, this will create multiple notifications. Nothing to do about that at the moment. They might also create different subscribers and a different message. If there are conflicting/similar triggers (create notification and mentioned in text for example), this needs to be resolved in the handling of these triggers.
