### ISSUE TITLE
api section of the online user guide is out of date

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9937]
i am learning about how to implement my own API features here and reading through the guide at: http://learn.elgg.org/en/2.0/guides/web-services.html?highlight=api
i see that some parts are out of date. for example, i am advised to look in  /engine/lib/api.php for example code, but that file no longer exists in elgg 2.0 and i haven't yet found an equivalent. also there is a reference at the bottom of the page to a plugin for Oauth that hasn't been updated since 1.8.

**Comment by hypeJunction** [comment]
Feel free to make pull requests to update those. Web services is an area that the team is wary about, and I don't think anyone is going to invest time into it, especially the docs.

**Comment by beck24** [comment]
why are we wary about it?

**Comment by hypeJunction** [comment]
Aren't you? What was the last time to made a pull request to improve it? Last time I tried, it went nowhere, because there is "hope" for better implementation.

**Comment by beck24** [comment]
I'm not wary.  I guess the one thing to be wary about would be BC which could be holding us back.  Would suck to have a working API break with an upgrade, but with webservices moved to a plugin that's potentially less of an issue now.  I've been using webservices a lot lately, and it's working fine for what it is.  Other than truly restful I'm not sure what a "better" implementation would look like, but I'm not against improvements.

@propertunist - the equivalent would be found in the webservices plugin itself, not sure which file exactly but it's easy to find if you look in the plugin.

**Comment by mrclay** [comment]
There are some web_services improvements [in 2.2](https://github.com/Elgg/Elgg/pull/9418)! All the code was moved to mod/web_services.

**Comment by propertunist** [comment]
i would consider updating the manual text, but i don't really understand it myself at the moment - at least not fully enough to teach others.

**Comment by jdalsem** [comment]
@hypeJunction could you take care of this ticket? You did a bit more with webservices lately than us

**Comment by hypeJunction** [comment]
No, thank you. I don't care for web services in their current state, and not using them. All the work that went into routing was to make web services go away.

**Comment by jdalsem** [comment]
Current state of the docs is fine as is... for starters
