### ISSUE TITLE
dashboard topbar menu item should only be registered if logged in

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9940]
for sites that show topbar if logged out....

**Comment by mrclay** [comment]
Any BC implications doing this? Sounds good

**Comment by jdalsem** [comment]
> Any BC implications doing this

not that i can think of... unless someone created a working dashboard for logged out users and now the link is gone

**Comment by mrclay** [comment]
I assume the current workaround is to register for the "register" or "prepare" hook and remove the items? If it's that easy I'd suggest we make this change on master to eliminate any chance of breaking a 2.x site.

**Comment by jdalsem** [comment]
we should also scan if there are multiple topbar registered items that are logged in only...
