### ISSUE TITLE
elgg_get_embed_url is limited

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9941]
why is this only usable for icons??? it makes sense to have a feature to link to entities / files that serve a static asset/resource

currently there is no way to have a non-expiring public download url for resources

**Comment by hypeJunction** [comment]
What's the use case? `elgg_get_inline_ulr()` without a session binding should work for most cases.

**Comment by jdalsem** [comment]
use case is i want to have a admin maintained list of downloadable files (not using the file plugin). Those files can be embedded anywhere on the site and should not be bound to user/session or expire

Example 1: there could be a page about the Privacy Policy on the site. The policy could also be downloaded as a pdf. The pdf file needs to be uploaded somewhere on the site. File plugin is overkill, so we use a asset library plugin that allows admins to upload static resources... copy paste the download link and use it where ever you need...

Example 2: Site admin defines a list of downloadable images to be used in the text editor (embeddable via the embed plugin). Those images need to uploaded and have a download link...

**Comment by jdalsem** [comment]
Problem with `elgg_get_inline_url()` is it expires

**Comment by jdalsem** [comment]
sorry... problem is a bit simpler 

`elgg_get_inline_url()` gives a unexpired url (if expire = false), however, `elgg_get_download_url()` does not have the ability to set expire to false... why not?

**Comment by jdalsem** [comment]
if `elgg_get_download_url()` should also accept $expire to be false, it would help my usecase, however the url is needlessly long (as i do not need expiration info, i do not need session binding)..

so a simpler download link would be nice...

**Comment by jdalsem** [comment]
i am currently bypassing the expire issue in elgg_get_download_url by manually creating the `FileService\File` object, which works fine for the moment
