### ISSUE TITLE
Unable to crop non-square icons

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9942]
I'm trying to crop a custom icon type, which uses non-square images for all icon sizes.

This part either forces the images to squares or refuses to create them at all: https://github.com/Elgg/Elgg/blob/2.2/engine/classes/Elgg/EntityIconService.php#L257-L262

Should the `if` clause perhaps also check whether image type is `icon` and allow other types to crop as they desire?

**Comment by hypeJunction** [comment]
I would rather fix #9663, but we need political will.

**Comment by juho-jaakkola** [comment]
We cannot change shapes of the `icon` image type until Elgg 3, so I'd like to add my suggestion as a temporary workaround for now. The option to add new image types is quite useless without it.

**Comment by hypeJunction** [comment]
I think we should squeeze in to 2.2.0. Can you make a PR?

**Comment by juho-jaakkola** [comment]
Coming right up.
