### ISSUE TITLE
Input IDs on AJAX

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9955]
I had recently ran into an issue with overlapping input IDs on AJAX requests. The particular issue was with a datepicker that bootstraps using input ID, but I imagine an issue could occur with a longtext as well. We probably need to persist ID iterator across the session.

**Comment by mrclay** [comment]
`microtime() . $static_counter`?

**Comment by mrclay** [comment]
Which views have these generated IDs?

**Comment by hypeJunction** [comment]
`elgg_view_input()` autogenerates them if they are missing.

**Comment by mrclay** [comment]
`base_convert(mt_rand(), 10, 36)` should be a fine suffix. It should be uniquely seeded per request.
