### ISSUE TITLE
it should be able to pass link_class in elgg_view_menu

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9969]
currently the menu default view creates new vars and does not pass link_class to section view and that is not passed to menu/item view and not to elgg_view_menu_item

**Comment by jdalsem** [comment]
we should also change elgg_view_menu_item to output a special view instead of output/url

**Comment by hypeJunction** [comment]
I wanted to get rid of `elgg_view_menu_item()` entirely https://github.com/Elgg/Elgg/issues/8818

**Comment by jdalsem** [comment]
Hmm after a year i am unsure why i even needed this feature and i disagree that elgg_view_menu vars should be passed on to menu items
