### ISSUE TITLE
Should icon service always save 'original' image size?

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#9970]
The EntityIconService has a minor problem. Every time an icon is cropped, the cropping affects all image sizes including the largest 'master' size. This causes the image quality of the master icon to deteriorate every time the icon is cropped.

Perhaps we should always save also the original image with the "size"  `original`. It would be created regardless if it were included in the image size configuration (returned by the icon size hook). Sites could optionally define a size for it, but it would *not* be affected by cropping. This would make sure there's always a high-quality version of each image available.

**Comment by jdalsem** [comment]
i think it should... this would also help if bigger resolutions are added in a future config and you need to recreate the icons

**Comment by hypeJunction** [comment]
I think my original design had that, but I eventually got rid of it. Can't remember why.

**Comment by juho-jaakkola** [comment]
Well, there's always the risk that someone uploads a ridiculously large image.

**Comment by juho-jaakkola** [comment]
Perhaps we could allow passing in an image size config that would skip the resize/crop part and save the image without modification.

**Comment by hypeJunction** [comment]
One option is to calculate if cropping coordinates are a square and decide
based on that  which sizes to crop
On Jul 11, 2016 8:03 PM, "Juho Jaakkola" <notifications@github.com> wrote:

Perhaps we could allow passing in an image size config that would skip the
resize/crop part and save the image without modification.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Elgg/Elgg/issues/9970#issuecomment-231815234>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABJaSdsrYww74RRlP-LU9uLJ-4Z4pbdeks5qUoWMgaJpZM4JJP0u>
.

**Comment by juho-jaakkola** [comment]
> One option is to calculate if cropping coordinates are a square and decide
based on that  which sizes to crop

That won't help with custom image types. They could have any aspect ratio.

How about skipping crop/resize if the configuration value is e.g. an empty array:
```php
array(
    'medium' => array('w' => 100, 'h' => 100, 'square' => true, 'upscale' => true),
    'large' => array('w' => 200, 'h' => 200, 'square' => false, 'upscale' => false),
    'original' => array()
);
```

**Comment by hypeJunction** [comment]
Fine by me. I just don't want duplicate files on the filestore.

**Comment by juho-jaakkola** [comment]
What are the main use cases for creating an image with `saveIconFromElggFile()` so that it creates a dupe? Something like you're browsing an image album and use a "Set this as a profile icon" feature?

I would guess in most cases it is appropriate to make a duplicate. At least I personally would like to have a copy in case the original source image gets removed.

**Comment by hypeJunction** [comment]
Give me some code to read ;)
