### ISSUE TITLE
in ege_ functions default the type to 'object' if subtype is provided (and type is ommitted)

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9973]
instead of 
```
elgg_get_entities([
    'type' => 'object',
    'subtype' => 'thewire',
]);
```
you can just do

```
elgg_get_entities([
    'subtype' => 'thewire',
]);
```

Most usage of ege_ functions is for listing of objects... this just helps a bit..

**Comment by jdalsem** [comment]
Nevermind... bad idea

**Comment by juho-jaakkola** [comment]
I have sometimes thought about the same idea. What made you give it up?

**Comment by mrclay** [comment]
Changing API has cost, especially for new devs trying to make sense of older and newer plugins, but also because it makes it easy to break BC with older Elgg versions for little gain.

**Comment by jdalsem** [comment]
@juho-jaakkola the main reason for not doing this is because the gain is too little and changing it will easily break stuff...
