### ISSUE TITLE
profile/edit action has wrong handling of default field access

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9982]
https://github.com/Elgg/Elgg/blob/2.x/actions/profile/edit.php#L107

the value `ACCESS_DEFAULT` should never ever enter the database.

better would have been 
`$access_id = get_default_access($user)`

**Comment by mrclay** [comment]
Fix in 1.12 would be best.

**Comment by jeabakker** [comment]
closed in #10233
