### ISSUE TITLE
view /river/object/comment/create should not provide space for responses

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#9985]
This will create a blank element with in the html... i see no need for that

**Comment by jdalsem** [comment]
there should also be an easier way to not show the river/responses div (other than passing a space)

**Comment by mrclay** [comment]
More context at #9047.

**Comment by mrclay** [comment]
> This will create a blank element with in the html

The blank element was there before #9047, so I left it in for BC. I think our current policy is markup can change so we can remove this in 2.2 if you want.
