### ISSUE TITLE
Undefined index: list_class in "mod\likes\views\default\likes\before_lists.php" (line 12)

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9994]
if `$vars['list_class']` is not set (for whatever reason) a php notice is issued

**Comment by jeabakker** [comment]
https://github.com/Elgg/Elgg/blob/1.12/mod/likes/views/default/likes/before_lists.php#L12

**Comment by mrclay** [comment]
Fixed #10164
