### ISSUE TITLE
Blog tutorial is outdated

### ISSUE THREAD

**Issue by lehkonev** [Elgg/Elgg#9998]
I went through the [blog tutorial](http://learn.elgg.org/en/2.0/tutorials/blog.html) and it was pretty outdated. The biggest issues are:
- nothing about the manifest file
- objects don't quite automatically get an URL
- no page for viewing a blog post

Anyway, I managed to work it out and get the blog to work, but the tutorial is still outdated.

(I started rewriting some of the tutorial while figuring out stuff so I'll just close this issue once I'm finished with it. :))

**Comment by juho-jaakkola** [comment]
Feel free to open a new pull request right away. We can then give you feedback as you write it.

**Comment by hypeJunction** [comment]
Fixed by #9999
